### ISSUE TITLE
Get feedback

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#100]
Ask people to try it out and get feedback

**Comment by manekinekko** [comment]
I made this [form](https://docs.google.com/forms/d/1mx3CQnOsuhW-VgWXeGzii0NR1nZrlsVlqg759X35Iy8/viewform) and sent this [tweet](https://twitter.com/manekinekko/status/639822726060974080) to ask for feedback...wait and see.

**Comment by gdi2290** [comment]
awesome thanks! :+1:

**Comment by gdi2290** [comment]
some feedback
* AngularConnect:
  * “looks phenomenal” - [jvandemo](https://twitter.com/jvandemo/status/657496628232851456)
* Universal Survey
  * [Willing to use Universal in production](https://medium.com/@wassimchegham/angular-universal-aka-angular-server-rendering-survey-results-1038498c51e9#.7h44nbirc)
    * 30.7% yes
    * 4.7% no
    * 64.7% maybe

**Comment by mikeallisonJS** [comment]
So, my feedback so far..... 

I'd definitely use it in production where I see a fit.
The difficulty of using other webpack modules along-side it is a problem for me long-term. I'm guessing the browserify dependency is the culprit there. 

Overall, it's an amazing, working implementation that I hope gets the support to take off.
There's a 99% change my personal site will go live with it once angular2 hits beta. After that, well who knows.

**Comment by gdi2290** [comment]
@mikeallisonJS do you mind expanding more on your comment about webpack modules alongside it?

**Comment by mikeallisonJS** [comment]
Specifically, using css-loaders, sass-loaders, raw-loaders, etc. to import into the bundle. It breaks the typescript app, which I'm not able to create as a bundle.

**Comment by jeffwhelpley** [comment]
We have created several other issues in the repo to address specific things we want to address. Closing this and if you have any other problems, just post a new issue.
