### ISSUE TITLE
Can universal provide koa-engine?

### ISSUE THREAD

**Issue by 3fuyu** [angular/universal#1023]
Express-engine is good. But we use koa to build project. Can you provide koa-engine? Like #777 .

**Comment by Toxicable** [comment]
We're happy to take a PR for one if you like.
Either a new one or continue on from that one you linked should suffice.

One point of advise would be to use the Common Engine found here: https://github.com/angular/universal/tree/master/modules/common/engine
And here is an example of implementing it: https://github.com/angular/universal/pull/999/files#diff-1d1f74cba58d729d80bea48694d3cd53R33

**Comment by qqaimh** [comment]
Does the koa-engine run perfectly?

**Comment by JomaKar** [comment]
I've seen the PR and I just wanna say there's a beautiful community happy to get news about this topic!

**Comment by Roman-Lo** [comment]
Awesome!!!!!

**Comment by alan-agius4** [comment]
Kindly see https://github.com/angular/universal/pull/1714#issuecomment-745229963
