### ISSUE TITLE
Service Worker conflict at index.html (with official installation instructions)

### ISSUE THREAD

**Issue by goelinsights** [angular/universal#1024]
# Bug Report

#### What is the expected behavior?
Universal works with service worker

#### What is the current behavior?
Universal routes break, giving 404 errors 

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
Install service worker to universal-starter

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?
https://github.com/angular/angular-cli/issues/8872
Per above, currently solving by deleting index.html from the ngsw-config, but this would be well placed in the installation instructions somewhere, as it was difficult to troubleshoot

```
{
  "index": "/index.html",
  "assetGroups": [{
    "name": "app",
    "installMode": "prefetch",
    "resources": {
      "files": [
        "/favicon.ico",
        "/*.css",
        "/*.js"
      ]
    }
  }
```

**Comment by vytautas-pranskunas-** [comment]
Actually it helps SSR to start workin gwith ServiceWorker but going offline is not possible

**Comment by CaerusKaru** [comment]
Documentation PRs are welcome.
