### ISSUE TITLE
NotYetImplemented errors on runing angular universal server 

### ISSUE THREAD

**Issue by samialmorshedi** [angular/universal#1025]
I migrated my application to angular universal V6 which is using express for server-side. When I run my build the app and run it, I get this error !! I total do not know what`s going on! I tested app in prodoction mode but had no error !!

`ERROR { Error: Uncaught (in promise): Error: NotYetImplemented Error: NotYetImplemented at Document.exports.nyi (C:\Users\PC-01\Desktop\project_path\dist\server.js:213490:9) at CookieService.check (C:\Users\PC-01\Desktop\project_path\dist\server.js:279517:48) at CookieService.get (C:\Users\PC-01\Desktop\project_path\dist\server.js:279525:47) at new DateFormatterByTimezonePipe (C:\Users\PC-01\Desktop\project_path\dist\server.js:161863:53) at createClass (C:\Users\PC-01\Desktop\project_path\dist\server.js:12945:20) at createPipeInstance (C:\Users\PC-01\Desktop\project_path\dist\server.js:12824:12) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14043:32) at callViewAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14366:13) at execComponentViewsAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14285:13) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14078:5) at createRootView (C:\Users\PC-01\Desktop\project_path\dist\server.js:13964:5) at Object.createProdRootView [as createRootView] (C:\Users\PC-01\Desktop\project_path\dist\server.js:14476:12) at ComponentFactory_.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:12310:29) at ComponentFactoryBoundToModule.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:7129:29) at ViewContainerRef_.createComponent (C:\Users\PC-01\Desktop\project_path\dist\server.js:12420:45) at RouterOutlet.activateWith (C:\Users\PC-01\Desktop\project_path\dist\server.js:239338:40) at ActivateRoutes.activateRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238683:40) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238635:19 at Array.forEach (<anonymous>) at ActivateRoutes.activateChildRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238634:29) at ActivateRoutes.activate (C:\Users\PC-01\Desktop\project_path\dist\server.js:238559:14) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238498:18 at resolvePromise (C:\Users\PC-01\Desktop\project_path\dist\server.js:1025:31) at resolvePromise (C:\Users\PC-01\Desktop\project_path\dist\server.js:982:17) at C:\Users\PC-01\Desktop\project_path\dist\server.js:1084:17 at ZoneDelegate.invokeTask (C:\Users\PC-01\Desktop\project_path\dist\server.js:632:31) at Object.onInvokeTask (C:\Users\PC-01\Desktop\project_path\dist\server.js:7611:33) at ZoneDelegate.invokeTask (C:\Users\PC-01\Desktop\project_path\dist\server.js:631:36) at Zone.runTask (C:\Users\PC-01\Desktop\project_path\dist\server.js:399:47) at drainMicroTaskQueue (C:\Users\PC-01\Desktop\project_path\dist\server.js:806:35) at ZoneTask.invokeTask (C:\Users\PC-01\Desktop\project_path\dist\server.js:711:21) at Server.ZoneTask.invoke (C:\Users\PC-01\Desktop\project_path\dist\server.js:696:48) at emitTwo (events.js:126:13) at Server.emit (events.js:214:7) at parserOnIncoming (_http_server.js:619:12) at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23) rejection: Error: NotYetImplemented at Document.exports.nyi (C:\Users\PC-01\Desktop\project_path\dist\server.js:213490:9) at CookieService.check (C:\Users\PC-01\Desktop\project_path\dist\server.js:279517:48) at CookieService.get (C:\Users\PC-01\Desktop\project_path\dist\server.js:279525:47) at new DateFormatterByTimezonePipe (C:\Users\PC-01\Desktop\project_path\dist\server.js:161863:53) at createClass (C:\Users\PC-01\Desktop\project_path\dist\server.js:12945:20) at createPipeInstance (C:\Users\PC-01\Desktop\project_path\dist\server.js:12824:12) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14043:32) at callViewAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14366:13) at execComponentViewsAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14285:13) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14078:5) at createRootView (C:\Users\PC-01\Desktop\project_path\dist\server.js:13964:5) at Object.createProdRootView [as createRootView] (C:\Users\PC-01\Desktop\project_path\dist\server.js:14476:12) at ComponentFactory_.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:12310:29) at ComponentFactoryBoundToModule.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:7129:29) at ViewContainerRef_.createComponent (C:\Users\PC-01\Desktop\project_path\dist\server.js:12420:45) at RouterOutlet.activateWith (C:\Users\PC-01\Desktop\project_path\dist\server.js:239338:40) at ActivateRoutes.activateRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238683:40) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238635:19 at Array.forEach (<anonymous>) at ActivateRoutes.activateChildRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238634:29) at ActivateRoutes.activate (C:\Users\PC-01\Desktop\project_path\dist\server.js:238559:14) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238498:18, promise: ZoneAwarePromise { __zone_symbol__state: 0, __zone_symbol__value: Error: NotYetImplemented at Document.exports.nyi (C:\Users\PC-01\Desktop\project_path\dist\server.js:213490:9) at CookieService.check (C:\Users\PC-01\Desktop\project_path\dist\server.js:279517:48) at CookieService.get (C:\Users\PC-01\Desktop\project_path\dist\server.js:279525:47) at new DateFormatterByTimezonePipe (C:\Users\PC-01\Desktop\project_path\dist\server.js:161863:53) at createClass (C:\Users\PC-01\Desktop\project_path\dist\server.js:12945:20) at createPipeInstance (C:\Users\PC-01\Desktop\project_path\dist\server.js:12824:12) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14043:32) at callViewAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14366:13) at execComponentViewsAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14285:13) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14078:5) at createRootView (C:\Users\PC-01\Desktop\project_path\dist\server.js:13964:5) at Object.createProdRootView [as createRootView] (C:\Users\PC-01\Desktop\project_path\dist\server.js:14476:12) at ComponentFactory_.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:12310:29) at ComponentFactoryBoundToModule.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:7129:29) at ViewContainerRef_.createComponent (C:\Users\PC-01\Desktop\project_path\dist\server.js:12420:45) at RouterOutlet.activateWith (C:\Users\PC-01\Desktop\project_path\dist\server.js:239338:40) at ActivateRoutes.activateRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238683:40) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238635:19 at Array.forEach (<anonymous>) at ActivateRoutes.activateChildRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238634:29) at ActivateRoutes.activate (C:\Users\PC-01\Desktop\project_path\dist\server.js:238559:14) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238498:18 }, zone: Zone { _properties: { isAngularZone: true }, _parent: Zone { _properties: {}, _parent: null, _name: '<root>', _zoneDelegate: [Object] }, _name: 'angular', _zoneDelegate: ZoneDelegate { _taskCounts: [Object], zone: [Circular], _parentDelegate: [Object], _forkZS: null, _forkDlgt: null, _forkCurrZone: [Object], _interceptZS: null, _interceptDlgt: null, _interceptCurrZone: [Object], _invokeZS: [Object], _invokeDlgt: [Object], _invokeCurrZone: [Circular], _handleErrorZS: [Object], _handleErrorDlgt: [Object], _handleErrorCurrZone: [Circular], _scheduleTaskZS: [Object], _scheduleTaskDlgt: [Object], _scheduleTaskCurrZone: [Circular], _invokeTaskZS: [Object], _invokeTaskDlgt: [Object], _invokeTaskCurrZone: [Circular], _cancelTaskZS: [Object], _cancelTaskDlgt: [Object], _cancelTaskCurrZone: [Circular], _hasTaskZS: [Object], _hasTaskDlgt: [Object], _hasTaskDlgtOwner: [Circular], _hasTaskCurrZone: [Circular] } }, task: ZoneTask { _zone: Zone { _properties: [Object], _parent: [Object], _name: 'angular', _zoneDelegate: [Object] }, runCount: 0, _zoneDelegates: null, _state: 'notScheduled', type: 'microTask', source: 'Promise.then', data: ZoneAwarePromise { __zone_symbol__state: 0, __zone_symbol__value: Error: NotYetImplemented at Document.exports.nyi (C:\Users\PC-01\Desktop\project_path\dist\server.js:213490:9) at CookieService.check (C:\Users\PC-01\Desktop\project_path\dist\server.js:279517:48) at CookieService.get (C:\Users\PC-01\Desktop\project_path\dist\server.js:279525:47) at new DateFormatterByTimezonePipe (C:\Users\PC-01\Desktop\project_path\dist\server.js:161863:53) at createClass (C:\Users\PC-01\Desktop\project_path\dist\server.js:12945:20) at createPipeInstance (C:\Users\PC-01\Desktop\project_path\dist\server.js:12824:12) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14043:32) at callViewAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14366:13) at execComponentViewsAction (C:\Users\PC-01\Desktop\project_path\dist\server.js:14285:13) at createViewNodes (C:\Users\PC-01\Desktop\project_path\dist\server.js:14078:5) at createRootView (C:\Users\PC-01\Desktop\project_path\dist\server.js:13964:5) at Object.createProdRootView [as createRootView] (C:\Users\PC-01\Desktop\project_path\dist\server.js:14476:12) at ComponentFactory_.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:12310:29) at ComponentFactoryBoundToModule.create (C:\Users\PC-01\Desktop\project_path\dist\server.js:7129:29) at ViewContainerRef_.createComponent (C:\Users\PC-01\Desktop\project_path\dist\server.js:12420:45) at RouterOutlet.activateWith (C:\Users\PC-01\Desktop\project_path\dist\server.js:239338:40) at ActivateRoutes.activateRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238683:40) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238635:19 at Array.forEach (<anonymous>) at ActivateRoutes.activateChildRoutes (C:\Users\PC-01\Desktop\project_path\dist\server.js:238634:29) at ActivateRoutes.activate (C:\Users\PC-01\Desktop\project_path\dist\server.js:238559:14) at C:\Users\PC-01\Desktop\project_path\dist\server.js:238498:18 }, scheduleFn: undefined, cancelFn: null, callback: [Function], invoke: [Function] } }`

**Comment by Toxicable** [comment]
>NotYetImplemented Error:

This error is thrown by Domino: https://github.com/fgnass/domino
They do not implement the whole of the browser API's, in such a case i'd advise doing a platform check and skipping over that function call when on the server.

From your stack track it appears that you're using something to do with Cookies, if you check the Domino docs / Github you may find some more info about how to deal with this.

**Comment by dreamhigh0822** [comment]
@Toxicable Can you explain it in more details how to platform check and skipping over that function calls on the server?
