### ISSUE TITLE
How to implement it in existing project ?

### ISSUE THREAD

**Issue by ishan123456789** [angular/universal#1028]
I have an existing project in angular 6 and I want to implement `ssr` or convert my project to a universal one ,is there a doc for that ?

**Comment by hiepxanh** [comment]
[https://angular.io/guide/universal](https://angular.io/guide/universal) is that it help you?

**Comment by ishan123456789** [comment]
It's quiet a lot different from this project. A lot many more differences from the project used in the https://angular.io/guide/universal

**Comment by ishan123456789** [comment]
The additional step that was missing https://github.com/angular/universal-starter/issues/609
