### ISSUE TITLE
Routing not working in angular 6 angular universal

### ISSUE THREAD

**Issue by mikiol60** [angular/universal#1032]
i have my router-outlet placed in app.component and if I remove that the page loads but without router-outlet no routing can happen. 

This is my app.module.ts

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { AppComponent } from './app.component';
import { ComingSoonComponent } from './coming-soon/coming-soon.component';

import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { AppRoutingModule } from './app.routing.module';
import { CommonModule } from '@angular/common';
import { HttpClientModule } from '@angular/common/http';
import { BrowserTransferStateModule } from '@angular/platform-browser';

@NgModule({
  declarations: [
    AppComponent,
    ComingSoonComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'glplusllc-new' }),
    BrowserTransferStateModule,
    // BrowserAnimationsModule,
    AppRoutingModule,
    HttpClientModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

This is my app.routing.module.ts

`import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { ComingSoonComponent } from './coming-soon/coming-soon.component';
import { AppComponent } from './coming-soon/coming-soon.component';

const routes: Routes = [
  { path: 'comingsoon', component: ComingSoonComponent },
  { path: './comingsoon', component: ComingSoonComponent },
  { path: '', redirectTo: '/comingsoon', pathMatch: 'full' },
  { path: '**', redirectTo: '/' },
];
@NgModule({
  imports: [RouterModule.forRoot(routes), AppComponent,
    ComingSoonComponent],
  exports: [RouterModule]
})
export class AppRoutingModule { }

`

**Comment by SickBeat** [comment]
how did you solve this?
