### ISSUE TITLE
Angular Universal App rendering incomplete list from http request in *ngFor

### ISSUE THREAD

**Issue by FelipeMicali** [angular/universal#1040]
# Bug Report

Every day in this journey to dominate SSR with Angular Universal I end my work day facing new issues that keeps preventing my SPA from being properly indexed by search engines.

I'm using Angular 5.2.11 and all dependencies in the same version. Also, I'm using the transfer state module to prevent additional http calls in the browser app.

#### What is the expected behavior?
By all I know *ngFor in Angular Universal should wait for all async calls to be complete before rendering the template.

#### What is the current behavior?
The problem that I've noticed is that when I perform a http get/post request that retrieves an array of results and I assign this array to a component variable to be rendered as a list with *ngFor directive, the server renders this list incomplete. The number of rendered results are random at each page reload, from almost 3 to less than the entire array length.

#### Minimal reproduction with instructions:
I'm making this request inside ngOnInit and calling it from a service, subscribing to it in the component and assigning the response to the component variable when I receive the success response. I'm not using the async pipe with an Observable, because I need to trigger this request manually in my app architecture, but I've tested this approach already and it also won't work.

#### What is the use-case or motivation for changing an existing behavior?
This is terrible, because Google won't know of all my existing urls, as at each attempt an incomplete and with a random number of results list is visible to it.

Does anyone know how to make the Universal server app always render the complete list from a http async call?

Thanks!

**Comment by Toxicable** [comment]
I attempted to reproduce this issue but was unable to.
Could you provide us with a minimal reproduction?
Minimal meaning that there isn't anything in there that dosen't directly relate to the issue

**Comment by patrickmichalina** [comment]
I have been using Universal extensively and yet to see this issue. I am curious how this is happening to you.

**Comment by FelipeMicali** [comment]
Hello guys, thanks for the feedbacks!

@patrickmichalina I just can't understand why is this happening, but today I've noticed that this is happening in a specific page of my website. In all other pages that I have lists displayed with *ngFor SSR is working properly. Maybe this has something to do with some other logic that I've implemented in this same component. I'll try to remove everything from this component and leave it only with my list request and the *ngFor directive to see if it works, then I'll come back here and report the result.

Anyway, thanks for the feedback, I think the problem is with my code and the order that things are happening.

@Toxicable , I'll try to fix the problem and, if it persists, then I'll reproduce it, so you can help me find the issue with my code. Thanks for your attention!

**Comment by FelipeMicali** [comment]
In the end I've discovered that my directive that uses the IntersectionObserver api was the cause of this issue. I was using it inside my "a" to lazy load images for each one of my list elements. It throws an error in the server when it's invoked and maybe this was preventing the entire list to be displayed.

By preventing this directive to run in the server with isPlatformBrowser solved the issue.

Thanks!
