### ISSUE TITLE
Updating meta tags not working(View Page Source) in Angular6

### ISSUE THREAD

**Issue by cstrd** [angular/universal#1045]
# Bug Report

We built a website using Angular 6 Universal App, Meta tags are not Updating in the View Page Source. (https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable)

Please Check The Code Below

```
this.titleService.setTitle('Dr.S Ramakrishnan | TheRightDoctors');

this.meta.updateTag({name: 'description', content:'TheRightDoctors  Dr.S Ramakrishnan After discharge of a STEMI patient… story continues'});

this.meta.updateTag({name: 'keywords', content:'dr s ramakrishnan,dr s ramakrishnan iit madras,Cardiologist, TheRightDoctors, TheRightDoctors.com, the right doctors,Dr. S RamaKrishnan, Dept. of Cardiology, AIIMS, New Delhi'});

            this.meta.updateTag({
              property: 'vr:canonical',
              content: 'https://therightdoctors.com/one-more-thing/dr-s-ramakrishnan-additional-professor-cad-stroke-and-renal-diseases-are-on-a-scale-that-is-unbelievable'
            });
```
Same tags are displaying in Inspect Element. please check below image

![capture_metatags](https://user-images.githubusercontent.com/11487982/43319307-dbfca904-91c1-11e8-8340-1e5eb8a6084a.PNG)

**Comment by MdShuaib** [comment]
Try to clear your cache , might be a case that meta tags are taking the cache data

**Comment by Gorniv** [comment]
This work for me:  https://github.com/Angular-RU/angular-universal-starter/blob/7008a3f4dc9625088322c34628abcd9972534738/src/app/home/home.component.ts#L23

**Comment by CaerusKaru** [comment]
This can be tracked in #1048, unless @Gorniv's solution works, in which case they can both be closed.

**Comment by prof-jagpreet** [comment]
Meta tags works if they are static.
But if we need meta tags to set dynamically then it is not working.
Which will be very useful in eCommerce product pages where title and description of page can be from api
