### ISSUE TITLE
async data does not render on server

### ISSUE THREAD

**Issue by GabrielCoriiu** [angular/universal#1049]
# Bug Report

#### What is the expected behavior?
Wait for all async calls (promises included) to resolve before rendering the page.

#### What is the current behavior?
The server doesn't wait for the async promises to resolve before rendering

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
please check this repo: https://github.com/GabrielCoriiu/universal-starter-contentful-async
and this: https://github.com/angular/universal-starter/issues/181#issuecomment-412262601

#### What is the use-case or motivation for changing an existing behavior?
SEO

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by Gorniv** [comment]
contentfull don't use TransferState for sync server and browser.
Read how to work TransferState and look https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/transfer-back/transfer-back.component.ts

**Comment by mmmaxi** [comment]
+1

**Comment by krlf** [comment]
> contentfull don't use TransferState for sync server and browser.
What if we don't use TransferState and request async data in a browser as well?

**Comment by GabrielCoriiu** [comment]
It is indeed the case that there was not transfer state between the server and the client. Not it works like a charm. I guess this can be closed. Thanks @Gorniv
