### ISSUE TITLE
Cant pass environment.production to server but will pass to browser version

### ISSUE THREAD

**Issue by Chris-Devine** [angular/universal#1054]
# Bug Report
Following angular documentation for angular universal setup (also in angulars completed demo code) that when building the SSR version, the server side code get the environment.ts file but the browser side gets the environment.production.ts file.

This lead me to 2 hours debugging to find out why my server was unable to call the API on the live environment. 

#### What is the expected behavior?
I should be able to pass --prod type of argument when calling the build of the SSR and both the server and browser can then use the same Environment file

#### What is the current behavior?
 No way to tell server build what environment to use

#### What modules are related to this issue?
no idea

#### Minimal reproduction with instructions:
just try run a build on demo code and check the server file... it will have the dev environment values but the browser will have the production environment version

#### What is the use-case or motivation for changing an existing behaviour?
consistency is life!

**Comment by Gorniv** [comment]
You need write configuration in angular.json like: [Angular-RU/angular-universal-starter/angular.json](https://github.com/Angular-RU/angular-universal-starter/blob/575ae5238e7cc8aa9aa910257c9a395c06ac6cad/angular.json#L144)

**Comment by CaerusKaru** [comment]
@Gorniv is correct.
