### ISSUE TITLE
export 'ViewportScroller' was not found in '@angular/common'  <router-outlet> not in page source

### ISSUE THREAD

**Issue by ohabash** [angular/universal#1065]
# Bug Report

after I build and serve with `npm run build:ssr; npm run serve:ssr` I get a warning...

>WARNING in ./node_modules/@angular/platform-server/fesm5/platform-server.js
852:35-51 "export 'ViewportScroller' was not found in '@angular/common'
 @ ./node_modules/@angular/platform-server/fesm5/platform-server.js
 @ ./dist/server/main.js
 @ ./server.ts

>WARNING in ./node_modules/@angular/platform-server/fesm5/platform-server.js
852:63-84 "export 'ɵNullViewportScroller' was not found in '@angular/common'
 @ ./node_modules/@angular/platform-server/fesm5/platform-server.js
 @ ./dist/server/main.js
 @ ./server.ts

#### What is the current behavior?
contents inside of `<router-outlet></router-outlet>` not rendering on the server. 

#### Environment:
@angular-devkit/architect: 0.6.8
@angular-devkit/build-angular: 0.6.8
@angular-devkit/build-optimizer: 0.6.8
@angular-devkit/core: 0.6.8
@angular-devkit/schematics: 0.7.5
@angular/animations: 6.1.7
@angular/cli: 6.2.1
@angular/platform-server: 6.1.7
@ngtools/webpack: 6.0.8
@schematics/angular: 0.7.5
@schematics/update: 0.8.1
rxjs: 6.2.1
typescript: 2.7.2
webpack: 4.8.3
node: v9.2.0
npm: 5.5.1

**Comment by Gorniv** [comment]
Can you reproduce the problem on fork https://github.com/Angular-RU/angular-universal-starter ? I'll try to help.

**Comment by ohabash** [comment]
I have a better understanding of this error now. I think it is related to https://github.com/angular/universal/issues/1073

**Comment by CaerusKaru** [comment]
My recommendation is to open an issue on angular/angular. We don't really handle angular/common or platform-server issues in this repository.
