### ISSUE TITLE
Improve docs about TransferHttpCacheModule

### ISSUE THREAD

**Issue by intergleam** [angular/universal#1068]
https://github.com/angular/universal/blob/master/docs/transfer-http.md is unclear. I tried to follow and can't use it for a sample http call to a Weather API.
Ideally we need a sample repo

**Comment by Gorniv** [comment]
Are you sure import TransferHttpCacheModule in app.module.ts?
sample repo: https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/transfer-back/transfer-back.component.ts#L27

**Comment by CaerusKaru** [comment]
There's also the official [Angular Universal Starter](https://github.com/angular/universal-starter). Otherwise, PR's are welcome.
