### ISSUE TITLE
feat(socket-engine): add providers

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#1069]
Currently there is no way to inject providers using the Socket Engine, meaning there is also no ability to use lazy loading. See [here](https://github.com/angular/universal/issues/1000#issuecomment-423056207)

**Comment by someApprentice** [comment]
It's super simple to solve this problem!

Just put `providers` argument [here](https://github.com/angular/universal/blob/master/modules/socket-engine/src/main.ts#L33) and ofc in `startSocketEngine()` function.

**Comment by someApprentice** [comment]
https://github.com/angular/universal/pull/1072
