### ISSUE TITLE
upgrade to ng2 0.37 (in progress...)

### ISSUE THREAD

**Issue by valorkin** [angular/universal#108]
goal: to avoid duplication of work

Issue is a "statement of intention", I am currently updating universal to ng2 version 0.37
with type ref fixes and all what will be required
any way, latest master was not working >.<

**Comment by valorkin** [comment]
@gdi2290 @jeffbcross if you would not mind of course

**Comment by gdi2290** [comment]
you're looking for the other Jeff @jeffwhelpley I'll update the repo in a couple of hours

**Comment by valorkin** [comment]
:( almost done too

**Comment by gdi2290** [comment]
@valorkin I'll let you update it then so feel free to ping me on gitter/twitter if you need an immediate response. You might have to sync up some of the changes to bootstrap-server and the bootstrap-common in the angular2 repo. Also keep note of the modified bootstrap process and some of the bindings (such as Docmuent) that were moved

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/commit/ff4fdbce4a8c96752715469196e581a149023302
