### ISSUE TITLE
Remove reflect-metadata polyfill from the server

### ISSUE THREAD

**Issue by D2KX** [angular/universal#1088]
# Proposal
Remove reflect-metadata polyfill from the server

#### What is the summary of the proposal?
One of the promoted features of Angular 7 is the removal of the reflect-metadata polyfill by default, claiming it is only necessary in JIT mode and needlessly slows down performance in production mode. reflect-metadata is still mentioned and automatically added for Angular Universal within the server.ts file however.

#### What is the proposal?
Remove the following line from the Angular Universal/Angular Express Engine schematics, and the documentation:

`import 'reflect-metadata';`

#### Is there anything else we should know?
I have commented out the line in my Universal application and it still runs fine. However, I am not sure if there is anything specific about this polyfill that I am not aware of, that it might still be needed for Universal. But from the sounds of the Angular 7 blog post, it just wastes performance right now.

**Comment by CaerusKaru** [comment]
Should this be in `angular/universal-starter` instead?

**Comment by D2KX** [comment]
I have generated my server with

`ng add @nguniversal/express-engine` (which is awesome btw.!)

which is part of this GitHub project, and which includes this polyfill. I have not looked at universal-starter, but it would also apply there for sure.

**Comment by Toxicable** [comment]
I cant think of anything off the top of my head where doing this would cause an issue.
@D2KX We'd be open to accepting a PR for this change if you have the time
