### ISSUE TITLE
Reducing Time To Interactive for Angular Universal Applications

### ISSUE THREAD

**Issue by tom94zoe** [angular/universal#1092]
#### What is the expected behavior?
The ability to load scripts async or after a user interaction, out of the box. 

#### What is the current behavior?
Time to Interactive is to high for a good PageSpeed result.

#### Minimal reproduction with instructions:
Create an angular universal application and use Pagespeed for monitoring the performance. 

#### What is the use-case or motivation for changing an existing behavior?
Less loading time -> better UX = better SEO ranking

**Comment by tom94zoe** [comment]
Maybe it is possible to abort the loading of the client side rendering for specific pages. 
In my current situation I created some landingpages which only needs Angular to load the data and FxLayout for flexboxing. As a result the page shows only data and routes to other sites but the whole project is loaded. 

Perhaps the whole time-to-interactive issue will be gone with ivy but i think it will last 2 or 3 month until it is available.

**Comment by sahilpurav** [comment]
Ivy is released and we still see slow TTI and high TBT. Getting the good PageSpeed score seems impossible

**Comment by alan-agius4** [comment]
Performance is something that we are looking into. That said, I am closing this issue as it does not provide any action points.
