### ISSUE TITLE
Having issue while build angular universal app Error IS:Mouse Event Not Found-(__metadata("design:paramtypes", [MouseEvent]),)

### ISSUE THREAD

**Issue by prashantdubeymobileprogrammingcom** [angular/universal#1093]
D:\AngularNewANJ>npm run build:ssr && npm run serve:ssr

> anjolee@0.0.0 build:ssr D:\AngularNewANJ
> npm run build:client-and-server-bundles && npm run compile:server

> anjolee@0.0.0 build:client-and-server-bundles D:\AngularNewANJ
> ng build --prod && ng run Anjolee:server:production

Date: 2018-11-16T09:14:19.872Z
Hash: 2a911f8335b2d5cee1fd
Time: 47064ms
chunk {0} common.js (common) 14.9 kB  [rendered]
chunk {1} pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory~pages-diamonds-page-dia~d540290a.js (pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory~pages-diamonds-page-dia~d540290a) 17.6 kB  [rendered]
chunk {2} pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory~pages-diamonds-page-dia~e2cddcba.js (pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory~pages-diamonds-page-dia~e2cddcba) 41.1 kB  [rendered]
chunk {3} pages-promotions-page-promotions-page-module-ngfactory.js (pages-promotions-page-promotions-page-module-ngfactory) 7.79 kB  [rendered]
chunk {4} modules-information-information-module-ngfactory.js (modules-information-information-module-ngfactory) 250 kB  [rendered]
chunk {5} modules-educational-educational-module-ngfactory.js (modules-educational-educational-module-ngfactory) 617 kB  [rendered]
chunk {6} pages-place-order-page-place-order-page-module-ngfactory.js (pages-place-order-page-place-order-page-module-ngfactory) 20 kB  [rendered]
chunk {7} pages-checkout-page-checkout-page-module-ngfactory.js (pages-checkout-page-checkout-page-module-ngfactory) 180 kB  [rendered]
chunk {8} pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory.js (pages-diamond-stud-earrings-page-diamond-stud-earrings-page-module-ngfactory) 167 kB  [rendered]
chunk {9} pages-designer-wedding-band-designer-wedding-band-module-ngfactory.js (pages-designer-wedding-band-designer-wedding-band-module-ngfactory) 13.8 kB  [rendered]
chunk {10} pages-modern-bands-page-modern-bands-page-module-ngfactory.js (pages-modern-bands-page-modern-bands-page-module-ngfactory) 13.9 kB  [rendered]
chunk {11} pages-classic-band-page-classic-band-page-module-ngfactory.js (pages-classic-band-page-classic-band-page-module-ngfactory) 17 kB  [rendered]
chunk {12} pages-wedding-bands-wedding-page-module-ngfactory.js (pages-wedding-bands-wedding-page-module-ngfactory) 7.45 kB  [rendered]
chunk {13} pages-diamonds-page-diamonds-page-module-ngfactory.js (pages-diamonds-page-diamonds-page-module-ngfactory) 79.5 kB  [rendered]
chunk {14} pages-gemstones-page-gemstones-page-module-ngfactory.js (pages-gemstones-page-gemstones-page-module-ngfactory) 30.3 kB  [rendered]
chunk {15} pages-necklaces-page-necklaces-page-module-ngfactory.js (pages-necklaces-page-necklaces-page-module-ngfactory) 52.7 kB  [rendered]
chunk {16} pages-earrings-page-earrings-page-module-ngfactory.js (pages-earrings-page-earrings-page-module-ngfactory) 38.6 kB  [rendered]
chunk {17} pages-bracelets-page-bracelets-page-module-ngfactory.js (pages-bracelets-page-bracelets-page-module-ngfactory) 44.1 kB  [rendered]
chunk {18} pages-rings-main-page-rings-main-page-module-ngfactory.js (pages-rings-main-page-rings-main-page-module-ngfactory) 60.7 kB  [rendered]
chunk {19} pages-product-page-product-page-module-ngfactory.js (pages-product-page-product-page-module-ngfactory) 305 kB  [rendered]
chunk {20} pages-product-list-page-product-list-page-module-ngfactory.js (pages-product-list-page-product-list-page-module-ngfactory) 94.3 kB  [rendered]
chunk {21} pages-home-page-home-page-module-ngfactory.js (pages-home-page-home-page-module-ngfactory) 33 kB  [rendered]
chunk {22} pages-error-page-error-page-module-ngfactory.js (pages-error-page-error-page-module-ngfactory) 1.56 kB  [rendered]
chunk {23} runtime.js (runtime) 3.22 kB [entry] [rendered]
chunk {24} styles.css (styles) 130 kB [initial] [rendered]
chunk {25} polyfills.js (polyfills) 59.6 kB [initial] [rendered]
chunk {26} main.js (main) 729 kB [initial] [rendered]

Date: 2018-11-16T09:15:05.497Z
Hash: b8a2be771a2076ec5676
Time: 29550ms
chunk {main} main.js, main.js.map (main) 4.36 MB [entry] [rendered]

> anjolee@0.0.0 compile:server D:\AngularNewANJ
> webpack --config webpack.server.config.js --progress --colors

Hash: 6ec7ad54492dba6e4db3
Version: webpack 4.9.2
Time: 13925ms
Built at: 2018-11-16 14:45:24
    Asset      Size  Chunks             Chunk Names
server.js  9.59 MiB       0  [emitted]  server
Entrypoint server = server.js
  [0] ./server.ts 1.83 KiB {0} [built]
  [2] external "events" 42 bytes {0} [built]
  [3] external "fs" 42 bytes {0} [built]
  [4] external "timers" 42 bytes {0} [optional] [built]
  [5] external "crypto" 42 bytes {0} [built]
[207] ./src lazy namespace object 160 bytes {0} [built]
[215] external "url" 42 bytes {0} [built]
[274] external "http" 42 bytes {0} [built]
[275] external "https" 42 bytes {0} [built]
[276] external "os" 42 bytes {0} [built]
[286] external "path" 42 bytes {0} [built]
[295] external "util" 42 bytes {0} [built]
[303] external "net" 42 bytes {0} [built]
[334] external "stream" 42 bytes {0} [built]
[402] ./dist/server/main.js 4.16 MiB {0} [built]
    + 397 hidden modules

> anjolee@0.0.0 serve:ssr D:\AngularNewANJ
> node dist/server

D:\AngularNewANJ\dist\server.js:159748
        __metadata("design:paramtypes", [MouseEvent]),
                                         ^

ReferenceError: MouseEvent is not defined
    at D:\AngularNewANJ\dist\server.js:159748:42
    at Object.<anonymous> (D:\AngularNewANJ\dist\server.js:159763:2)
    at __webpack_require__ (D:\AngularNewANJ\dist\server.js:20:30)
    at Object.primeng/components/table/table (D:\AngularNewANJ\dist\server.js:144311:18)
    at __webpack_require__ (D:\AngularNewANJ\dist\server.js:124808:30)
    at Object../src/app/pages/diamond-stud-earrings-page/diamond-stud-earrings-page.module.ngfactory.js (D:\AngularNewANJ\dist\server.js:135809:89)
    at __webpack_require__ (D:\AngularNewANJ\dist\server.js:124808:30)
    at Object../src/main.server.ts (D:\AngularNewANJ\dist\server.js:144061:143)
    at __webpack_require__ (D:\AngularNewANJ\dist\server.js:124808:30)
    at Object.0 (D:\AngularNewANJ\dist\server.js:144112:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! anjolee@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the anjolee@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Prashant.Dubey\AppData\Roaming\npm-cache\_logs\2018-11-16T09_15_25_981Z-debug.log

**Comment by prashantdubeymobileprogrammingcom** [comment]
Please help me to get out of this situation. I need to deploy asap

**Comment by CaerusKaru** [comment]
This respiratory is not a support forum. Better avenues for support include StackOverflow or Gitter
