### ISSUE TITLE
How to disable AOT for angular universal?

### ISSUE THREAD

**Issue by thedewpoint** [angular/universal#1100]
# Bug Report

#### What is the expected behavior?
Angular app with AOT disabled (compiler included in bundle) will still run server side

#### What is the current behavior?
Error being thrown for runtime compiler not included in bundle

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

**Comment by Toxicable** [comment]
Disabling AOT for Universal builds is very much un-advised.
It'll cause requests to go from taking 10's of milliseconds to seconds.
JIT is very slow since it has to compile the application each time, you'll overload your servers very quickly doing this.

**Comment by thedewpoint** [comment]
@Toxicable thanks
