### ISSUE TITLE
Difficulties installing Universal on Angular 7.1.2

### ISSUE THREAD

**Issue by xxdaggerxx** [angular/universal#1101]
My Angular version:
Angular CLI: 7.1.2
Node: 11.3.0
OS: darwin x64
@angular-devkit/architect    0.11.2
@angular-devkit/core         7.1.2
@angular-devkit/schematics   7.1.2
@schematics/angular          7.1.2
@schematics/update           0.11.2
rxjs                         6.3.3
typescript                   3.1.6

----------------
```
ng new testapp
cd testapp
ng add @ng-toolkit/universal
```

_npm ERR! notarget No matching version found for @nguniversal/module-map-ngfactory-loader@~7.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'testapp'
npm ERR! notarget_

I change  "@nguniversal/module-map-ngfactory-loader": "~7.1.0", in package json too:
"@nguniversal/module-map-ngfactory-loader": "~7.0.2",

`npm install`

_npm ERR! code ETARGET
npm ERR! notarget No matching version found for @nguniversal/express-engine@~7.1.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'testapp'
npm ERR! notarget_

I now change "@nguniversal/express-engine": "~7.1.0", to "@nguniversal/express-engine": "~7.0.2",

`npm install`

No Errors.
No i run ng serve to test.

`ng serve`

ERROR in node_modules/@angular/platform-server/src/http.d.ts(9,138): error TS2307: Cannot find module '@angular/http'.

i add "@angular/http": "7.1.2", to package.json

`npm install
ng serve
`
Serves successfully..
Now adding serverless is producing a bunch of new errors, why is this happening?

**Comment by markoddi** [comment]
I get the same error - did you managed to find a solution for this?

**Comment by sod** [comment]
I get the same error with `@ng-toolkit/universal`, so that seem not to work yet with angular 7.1. But that issue should be posted over at https://github.com/maciejtreder/ng-toolkit and there is already an issue https://github.com/maciejtreder/ng-toolkit/issues/523

I followed to guide at https://angular.io/guide/universal and could successfully setup universal with angular 7.1.3, see https://github.com/sod/angular-universal

**Comment by vikerman** [comment]
Hi - The latest version of @nguniversal packages is 7.0.2. We only match the major versions with Angular but not the minor/patch versions.

I think this bug probably belongs to the @ngtoolkit schematics.
