### ISSUE TITLE
Documentation for TransferState

### ISSUE THREAD

**Issue by stevermeister** [angular/universal#1107]
# Feature Request

Is there any **documentation about TransferState behaviour**? 
It's not really clear how it work and all the articles that I found provide only simple example without deep understanding.
 
I'm still looking for an answer for this one https://stackoverflow.com/questions/53853953/transferstate-who-guarantees-that-data-is-already-stored-in-state

**Comment by stevermeister** [comment]
@Gorniv but it's already outdated, right?

**TransferHttpCacheModule** is not used anymore

**Comment by Gorniv** [comment]
@stevermeister why is it outdated?

**Comment by stevermeister** [comment]
can you use **TransferHttpCacheModule** in modern Angular(7+)?

**Comment by stevermeister** [comment]
**BrowserTransferState** is new approach, isn't it?

**Comment by Gorniv** [comment]
https://angular.io/api/platform-browser/BrowserTransferStateModule is a part of TransferState
https://angular.io/api/platform-server/ServerTransferStateModule is a part of TransferState
TransferHttpCacheModule is a module for use BrowserTransferStateModule  and ServerTransferStateModule  with HTTP requests.

https://github.com/angular/universal/blob/master/modules/common/src/transfer_http.ts - how to use TransferState with Interceptor for HTTP
https://github.com/Gorniv/ngx-transfer-http/blob/master/lib/ngx-transfer-http/src/transfer-http.service.ts - another implementation - like HTTP service

**Comment by stevermeister** [comment]
@Gorniv I really appreciate that you are providing some many useful links and wish all the informations be present on official angular docs (https://angular.io/guide/universal)

but for me it's still not clear whether I need TransferHttpCacheModule if I can manage to get the same result with BrowserTransferStateModule: now my app sends http calls only on server and does not duplicate it on client.

**Comment by Gorniv** [comment]
@stevermeister if I comment import at https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/app.module.ts#L25 - I have twice request(server and browser).

**Comment by stevermeister** [comment]
I've created mine with **BrowserTransferStateModule** and it works without TransferHttpCacheModule, that's why I'm so confused

**Comment by CDDelta** [comment]
@stevermeister `TransferHttpCacheModule` automatically transfers your HTTP requests from the server to the client while `BrowserTransferStateModule` provides you with the `TransferState` service for you to write your own behaviour. If you just want to use the `TransferState` service there is no need to import `TransferHttpCacheModule`.

**Comment by stevermeister** [comment]
@CDDelta thank you! that was the answer I was looking for.

also a question: is it one time cache or no? i.e.: if browser sends request that was cached on server second time?

**Comment by CDDelta** [comment]
@stevermeister I am unsure about that but it would make sense for it to be a one time thing.

**Comment by CaerusKaru** [comment]
The docs are up-to-date. Our utility provides a wrapper and useful utilities around `BrowserTransferStateModule`
