### ISSUE TITLE
Global scripts are ignored

### ISSUE THREAD

**Issue by chris13524** [angular/universal#1114]
# Bug Report

#### What is the expected behavior?
The list of global scripts defined in `angular.json` should be compiled into the server code.

#### What is the current behavior?
The list of global scripts defined in `angular.json` are ignored.

#### What modules are related to this issue?
idk

#### Minimal reproduction with instructions:
To reproduce, clone the [`universal-starter`](https://github.com/angular/universal-starter) repo.

In `src/app/app.component.ts` add this function declaration:

    declare function globalFunction(): void;

And call it in the constructor:

    export class AppComponent {
      constructor() { globalFunction(); }
    }

Next, create the file `src/javascripts.js` and add this to it:

    function globalFunction() {
      console.log("Hello, world!");
    }

Finally, edit `angular.json` and add the new JavaScript file to the `scripts` array:

    "scripts": [
      "src/javascripts.js"
    ]

Run `ng serve` and visit `http://localhost:4200`...you should see "Hello, world!" printed to the JavaScript console.

Now build the Universal app using `npm run build:prerender`...you should see the error: `ReferenceError: globalFunction is not defined`.

#### What is the use-case or motivation for changing an existing behavior?
It is common to include global scripts in the `scripts` attribute of `angular.json`. However, when running things out of Angular Universal, these scripts are ignored causing runtime errors.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
Angular CLI: 7.1.4
Node: 8.10.0
OS: linux x64
Angular: 7.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.1.4 (cli-only)
@angular-devkit/schematics        7.1.4
@ngtools/webpack                  7.1.4
@schematics/angular               7.1.4
@schematics/update                0.11.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.23.1
```

#### Is there anything else we should know?

**Comment by rkorebrits** [comment]
Long time without answer, having the same issue. Surprised no-one has a fix for this?

**Comment by alan-agius4** [comment]
This is expected, global scripts are not meant to be executed with the current SSR approach.

**Comment by ChrisGrant** [comment]
> This is expected, global scripts are not meant to be executed with the current SSR approach.

If the is expected, then what are the alternatives here? I'd like to use Universal in an existing Angular project heavily reliant on an external library (Parse for what it is worth https://github.com/parse-community/Parse-SDK-JS) and I'm struggling to get it working.

**Comment by alan-agius4** [comment]
You can use external libraries by importing (using ES6 imports) them instead of using scripts which will make them globally available in the browser.
