### ISSUE TITLE
renderModuleFactory is not returning promise

### ISSUE THREAD

**Issue by kushcrimson** [angular/universal#1116]
# Bug Report

#### What is the expected behavior?
Application should render on localhost

#### What is the current behavior?
I updated my existing Angular universal app following the migration instructions from [,](https://update.angular.io) from 6 to 7. I am able to  successfully build for server side. But on serve
 it's not rendering the page.
It seems like I am unable to get promise responsefrom  renderModuleFactory
```
renderModuleFactory(AppServerModuleNgFactory, {
    // Our index.html
    document: template,
    url: options.req.url,
    // DI so that we can get lazy-loading to work differently (since we need it to just instantly render it)
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  }).then(html => {
    // not getting here         <-----------------------------------------
    callback(null, html);
  });
```
#### What modules are related to this issue?

I am not sure which modules this is related to.but I fixed lots of peer dependencies issue to make application run. :(

#### Environment:
"dependencies": {
    "@angular/animations": "^7.2.0",
    "@angular/cdk": "^7.2.1",
    "@angular/common": "^7.2.0",
    "@angular/compiler": "^7.2.0",
    "@angular/core": "^7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.23",
    "@angular/forms": "^7.2.0",
    "@angular/http": "^7.2.0",
    "@angular/material": "^7.2.1",
    "@angular/platform-browser": "^7.2.0",
    "@angular/platform-browser-dynamic": "^7.2.0",
    "@angular/platform-server": "^7.2.0",
    "@angular/router": "^7.2.0",
    "@nguniversal/express-engine": "^7.0.2",
    "@nguniversal/module-map-ngfactory-loader": "^7.0.2",
    "@ngx-translate/i18n-polyfill": "^1.0.0",
    "browser-detect": "^0.2.28",
    "core-js": "^2.6.2",
    "express": "^4.16.4",
    "hammerjs": "^2.0.8",
    "ngx-infinite-scroll": "^7.0.1",
    "rxjs": "^6.0.0",
    "rxjs-compat": "^6.3.3",
    "ts-loader": "^5.3.3",
    "zone.js": "^0.8.27"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.12.1",
    "@angular/cli": "~7.2.1",
    "@angular/compiler-cli": "^7.2.0",
    "@angular/language-service": "^7.2.0",
    "@types/jasmine": "~3.3.5",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~10.12.18",
    "codelyzer": "~4.5.0",
    "install": "^0.12.2",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.4",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.4",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "npm": "^6.5.0",
    "protractor": "^5.4.2",
    "ts-node": "~7.0.1",
    "tsconfig-paths-webpack-plugin": "^3.2.0",
    "tslint": "~5.12.1",
    "typescript": "~3.2.2",
    "webpack-cli": "^3.2.1",
    "webpack-dev-server": "^3.1.14"
  }

#### ng --version | output

![screenshot 120](https://user-images.githubusercontent.com/15811301/51025382-dc3eab00-15b1-11e9-8c72-79ee26519ce7.png)

**Comment by shubhi15** [comment]
+1

**Comment by martinduris** [comment]
Hi,
same issue here. Has it been resolved ?
Thanks

**Comment by martinduris** [comment]
@kushcrimson i confirm, that after change of `res.render` to `res.sendFile` application start works (even on routes with lazy load modules). Thanks. **BUT -> when you call some page (whatever page) from for example via curl -> you get response as from standart angular app.** e.g:

```
   <!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>App</title>
  <base href="/">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
<link rel="stylesheet" href="styles.af7e7d7427ac58ef77cf.css"></head>
<body>
  <app-root></app-root>
<script type="text/javascript" src="runtime.038ed192e581d36f8e4e.js"></script><script type="text/javascript" src="polyfills.f5ce8ecea387adbb1689.js"></script><script type="text/javascript" src="main.5ed59f0361f3d4341995.js"></script></body>
</html>
```

Can i kindly ask you confirm behavior at your app ?
Thanks a lot
Martin

**Comment by pasevin** [comment]
Same problem, and as @martinduris explained, if res.sendFile is used, it doesn't render on serve, but just serves index.html... Same as running http://localhost:8080/index.html

Has anyone resolved it?
