### ISSUE TITLE
Intercepting xhr2 requests

### ISSUE THREAD

**Issue by maenthoven** [angular/universal#1117]
# Feature Request

#### What is the desired behavior?
Some way to intercept the xhr2 requests.

#### What is the use-case or motivation for the desired behavior?
I'd like to cache data on my frontend server. To do that, I need to be able to intercept the xh2r requests.

```
Client <------> Frontend Server (Angular Universal) <-------> API Server
                                                        ^ 
                                          How to cache this?
```

**Comment by CaerusKaru** [comment]
You can use an `HttpInterceptor` to catch every Http request on the server (by only providing the interceptor in your server module). For more in-depth support on this, please use StackOverflow or Gitter.

**Comment by maenthoven** [comment]
Erm, that is not correct @CaerusKaru ...

Again, see the diagram. The HttpInterceptor can't cache between client page requests.

**Comment by CaerusKaru** [comment]
Let's go over the concepts involved and then we can determine if it's correct or not:

1. A user requests a page that triggers an Http request
1. The server initiates the Http call
1. All `HttpInterceptor`s get called in sequence
1. In one interceptor, if the call has already been made, retrieve it from the cache
1. Otherwise, initiate the request, and then set the cache after the call has succeeded

More details available [here](https://nrempel.com/guides/angular-httpclient-httpinterceptor-cache-requests/) (other results can be found literally by Googling "HttpInterceptor cache")

**Comment by maenthoven** [comment]
Your edit is almost there. The goal is to cache the xhr2 request, which is done OUTSIDE of the renderer / angular application but INSIDE angular universal.

Imagine 2 clients that look at information about a book. I want to cache the API call so that the book is only fetched once from the database.

HttpInterceptors do not support this, because each interceptor is completely unaware of the other client.

**Comment by CaerusKaru** [comment]
Ok I think I understand your ask, and it's both so wild an edge case and so not a Universal issue that I'm not going to comment further on this.

To be clear: you have two clients on the server. One is the Angular application being rendered. The other is some unknown server client, operating independently of Angular. Both, for whatever reason, call the same API, and you'd like to cache the calls, even though they will by default use two separate instances of `xhr2`.

Your recourse here is to override `HttpClient` itself on the server to use the shared instance of `xhr2`, which will have a wrapper around it to provide the caching functionality you require. Please be advised that you'll have to basically reimplement it, and wrap it with the `ZoneMacroTaskWrapper`, as done in angular/platform-server. Like I said earlier, this is the greatest extent of support we're willing to provide on this. Further support can be received on StackOverflow or Gitter.
