### ISSUE TITLE
Generating @nguniversal/express-engine from minimal project throws Schematic error v~7.2.0

### ISSUE THREAD

**Issue by cbstodd** [angular/universal#1118]
# Bug Report

#### What is the expected behavior?
To run: `ng add @nguniversal/express-engine --ngTestApp`
To execute/generate a full install:
`src/main.server.ts`
`src/app/app.server.module.ts`
`src/tsconfig.server.json`

#### What is the current behavior?
Throwing Error:
```
Schematic input does not validate against the Schema: {"--":["--ngTestApp"]}

Errors: 
Data path "" should NOT have additional properties(--).
```
I've tried running without `--`. I got fed up and created a blank/minimal app doing nothing other than the app generation then `ng add @nguniversal/express-engine --ngTestApp` and I'm still getting the error. I've generated other universal apps w/o `express-engine` today and all are working fine until `express-engine`. 

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [X ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
``` ng new ngTestApp --routing```
`> CSS`

#### What is the use-case or motivation for changing an existing behavior?
I've done nothing other than generate the app and tried to install universal/express-engine

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
Angular CLI: 7.2.3
Node: 8.15.0
OS: darwin x64
Angular: 7.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.3
@angular-devkit/build-angular     0.12.3
@angular-devkit/build-optimizer   0.12.3
@angular-devkit/build-webpack     0.12.3
@angular-devkit/core              7.2.3
@angular-devkit/schematics        7.2.3
@angular/cli                      7.2.3
@ngtools/webpack                  7.2.3
@schematics/angular               7.2.3
@schematics/update                0.12.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4
```

NPM Version:
`6.4.1`

#### Is there anything else we should know?

I'm using Node 8.15.0
```json
// package.json
{
  "name": "ng-test-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@nguniversal/express-engine": "^7.1.0",
    "core-js": "^2.5.4",
    "rxjs": "~6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.12.0",
    "@angular/cli": "~7.2.2",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2"
  }
}
```

**Comment by CaerusKaru** [comment]
I think you misunderstand the CLI command.

It's: `ng add @nguniversal --clientProject <projectName>`. You don't pass the name as `--` prefixed.

**Comment by cbstodd** [comment]
I've tried that: And then get the following Error:

```
Schematic input does not validate against the Schema: {"--":["ngTestApp"]}
Errors:

  Data path "" should NOT have additional properties(--).
```

**Comment by CaerusKaru** [comment]
Ok, I have to be as clear as possible:

`ng add @nguniversal --clientProject ngTestApp` is the full command.

**Comment by cbstodd** [comment]
AHHH, So --clientProject is part of the CLI. It worked! Thanks so much for your help! Greatly appreciated!

**Comment by emad-danial** [comment]
i have the error after doing g add @nguniversal/express-engine --clientProject ngTestApp 
Invalid rule result: Instance of class Promise.

**Comment by l-rocher91** [comment]
In my case i had to upgrade my angular app : 
ng update @angular/cli @angular/core
