### ISSUE TITLE
Stopping SSR and returning to client

### ISSUE THREAD

**Issue by UserGalileo** [angular/universal#1122]
# Feature Request

#### What is the desired behavior?

Hi! I don't know if this is something which can be already done in Universal since I haven't found any documentation about this, but: I'd like to know if it's possible, while Angular renders server-side, to stop/abort everything and just serve the normal index file, in order for Angular to bootstrap on the client-side without being rehydrated.

#### What is the use-case or motivation for the desired behavior?

This is the case: on my express server I have decided that some routes must be served with Universal and some others don't. I'm using a client-side mechanism for authentication (localStorage) and if Universal is about to serve a protected page (which shouldn't, but let's say I made a mistake and included that route in the Universal ones), the authentication phase fails, obviously. I'd like, in my authentication guard, to check if I'm on the server (via platform id) and if I am, to stop everything and just go back to the normal client-side behavior. Just as a safety mechanism because I reached some code which shouldn't be reached on the server.

It would be useful too in an interceptor, so that if a request returns 401 and I'm server-side, I shouldn't be making that call in that moment.

Thanks!

**Comment by CaerusKaru** [comment]
It is possible to do this entirely in Express (which controls what gets rendered). Please use StackOverflow or Gitter for support requests.
