### ISSUE TITLE
Some dependencies could cause errors after being bundled with webpack

### ISSUE THREAD

**Issue by euberdeveloper** [angular/universal#1126]
I made a similar issue but I did not know enough yet and it was not clear, so it was misunderstood and marked as duplicate.
It is not exactly a bug with ng universal, but this problem could occur to many developers who want to use ssr with angular and need dependencies such as pug.

To say it fast:

I download the code from angular universal and it works. [example code](https://angular.io/generated/zips/universal/universal.zip)

I add this dependency that I need: `npm i pug-mailer --save`

The server is built, but when it is run, this error occurs:

```
Cannot find module '../lib/utils.js'
    at Function.webpackEmptyContext [as resolve] (
```

The problem is that pug has `uglify-js` as a non-dev dependency. Webpack cannot bundle it.
I could use `webpack-node-externals` to avoid this problem, but then nothing is bundled at all.

Is it possible to bundle all the node_modules into only one file (server.js) **except** for uglify-js, wich will remain in the node_modules, to have a result such as:

```
dist
-----browser
-----server
-----server.js
node_modules
-----uglify-js

```

**Comment by mnahkies** [comment]
I'm facing a similar issue with some of my dependencies, in particular `node-sass`

One thing I'm wondering is whether it would possible to avoid bundling the express server altogether, and just build it to a dist directory as you would a more traditional node service.

I'll be interested in any information around why the webpack approach is used for the express service, and if it is necessary

**Comment by mnahkies** [comment]
I've tried building the express portion of the angular universal setup without webpack and had success:

I'm using a tsconfig.express.json file like this:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "../dist/express-server"
  },
  "include": [
    "server/server.ts",
    "declarations.d.ts"
  ]
}
```

And then building with tsc directly: `tsc -p ./src/tsconfig.express.json` - note that `./src/server/server.ts` is my express server entry point, and `declarations.d.ts` is just a declaration file I have in the project to define some global helper types

This yields a `./dist/express-server/server/server.js` file I can run with `node` - note I also had to adjust the path that the bundled angular application is loaded from, to account for the relative path changing.

Would love to know if there is any compelling reason not to do this? In my testing so far all appears well, but I'll post back here if I encounter any issues with the approach.

**Comment by euberdeveloper** [comment]
Yes, of course webpack is not required, you always can just use typescript to compile it or even write the server directly in JavaScript. Though, this is not recommended since webpack reduces significantly the bundle size and that is why I asked how to configurate webpack to tackle the issue, because I want to keep a good bundle size in my production server (by also removing the node_modules dir, except for the library causing the problem)

**Comment by mnahkies** [comment]
I could be wrong, but I don't see any major advantage to reducing the size of the production server by using webpack. The angular application is still compiled and bundled with webpack into both a client and server side bundle, so it's just the nodejs server portion that is unbundled.

Generally disc space isn't a major constraint on the server side when compared to CPU and RAM (perhaps depending on underlying storage you might experience some slow down in service startup times, but given the way that require caches modules, once the service is started I wouldn't expect any performance differences). Personally I've found the shift to not bundling my server to be a breath of fresh air making it easier to debug and run.

I guess webpack would be useful for the nodejs portion of the code if you had any special loaders / transformations you wanted it to perform. From doing some reading you could consider tweaking your webpack configuration to not bundle the node modules - eg: https://www.npmjs.com/package/webpack-node-externals

Regarding concerns about the size of the node_modules directory, you can reduce this somewhat through careful usage of devDependencies to specify dependencies can be removed for production usage (eg: `npm prune --production`)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.
