### ISSUE TITLE
Angular 5 + Universal does not render fully on the server side

### ISSUE THREAD

**Issue by alizoli** [angular/universal#1128]
We have implemented Angular 5 + Universal for our project kilid.com, we are hoping that the server side rendering app is generating the template of each page properly and also Rest APIs are called on the client. However, it looks like the SSR is not functioning as we still get the initial content of  index.html in any new single page. Moreover, it looks like the application is currently rendering on the client side as all js files are downloaded by the browser. I was wondering if this is a bug or there is a problem on how we actually implemented the SSR app.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
