### ISSUE TITLE
apparently everything is OK, but my first page is not rendered - angular universal

### ISSUE THREAD

**Issue by ali-hasani** [angular/universal#1131]
I have an angular universal project. According to your provided [link](https://github.com/angular/angular-cli/wiki/stories-universal-rendering) and angular documentation this project is now run, but without any errors or warning my first page is not loaded in the browser!
this is browser behavior: 

![problem-with-angular-universal-min](https://user-images.githubusercontent.com/29506320/53014992-322f2a00-345f-11e9-9a0f-7a81a7b55679.png)

It's ready to hand over If your need more information.
Please help friends !

**Comment by GautierLevert** [comment]
Same problem in my project. Everything works fine except the first HTTP request don't give any response. The second and followings work fine.

**Comment by GautierLevert** [comment]
After some tests, my problem occurs only when performing Firestore queries during server side rendering

**Comment by GautierLevert** [comment]
I managed to solve my problem by launching my Firestore query outside of angular zone (with NgZoner.unOutsideAngular).

But I needed to wrap the observable in an Angular zone task (code used : https://gitlab.com/snippets/1839435) to avoid the rendering to be done before the request end.

Here is a sample of my service : 
```typescript
@Injectable({
  providedIn: 'root'
})
export class PageService {
  constructor(
    private firestore: AngularFirestore,
    private zone: NgZone
  ) {}

  downloadPages(): Observable<Page[]> {
    return ZoneObservableWrapper.wrap(
      this.zone.runOutsideAngular(() => this.firestore.collection('pages').get())
        .pipe(
          map(snapshot => snapshot.docs),
          map(docs => docs.map(doc => Page.fromData(doc.id, doc.data())))
        )
    );
  }
}
```

I hope this may help someone with similar issue.

**Comment by coleridge72** [comment]
I was stuck on this for hours, that fixed it for me! thanks

**Comment by alan-agius4** [comment]
Please see: https://github.com/angular/universal/blob/main/docs/gotchas.md
