### ISSUE TITLE
Angular Universal TTFb Take alot Time to Response

### ISSUE THREAD

**Issue by nadermedhet148** [angular/universal#1134]
I have followed all the github repo to build application with universal as I needed it fully rendered HTML for seo. but I had a situation with my Angular app TTFB it takes about 7 seconds to byte. which I am really it's really huge for it. I have tried everything on the web to increase it's performance with luck. I used App Shell, Webpack and even changed my server to nginx to serve static content but it's the same. Also another problem that the page takes about 18 seconds to fully which is really huge. Although I am using i18n because the application it's multi language. When I used App shell, my TTFB decreased to 60 ms which is ideal but the probelm that the page only rendered in the static html for the homepage for the whole app. If i tried to analyze any route it will return the same html which will effect my SEO. I understand that I can use csr and google can index it but i don't want to target only google and can be indexed from any craweler.
However, I tried using prerender instead of server side and it did it's magic and loaded the page very quickly but the problem that my web app is really huge have about 80k routes which is not logic. Although that I have a huge server that can store all of this but I thought that's would be stupid idea. Does anyone know any ideas to solve this situation. you will find below my website link and please let me know what do you think with this situation!!!

**Comment by nadermedhet148** [comment]
now it's about 1000 ~ 2000 ms my problem was using settimeout without run it outside angular with ngzone

**Comment by a-jahanshahlo** [comment]
@nadermedhet148 
Please explain how you resolve your problem?
I have same issues with ASP.NET CORE with SSR. 
my TTFB take about 15s it's really terrible .
