### ISSUE TITLE
Socket-engine Getting the request server side

### ISSUE THREAD

**Issue by RadouaneRoufid** [angular/universal#1136]
# Feature Request

#### What is the desired behavior?
 Actually socket-engine does not support getting the request server side. The idea is to have a manner like for express-engine to inject the request 

`constructor(@Inject(REQUEST) private request: Request) {}`

#### What is the use-case or motivation for the desired behavior?
Sometimes we need to get the request server side to retrieve for example cookies or headers.

#### Is there anything else we should know?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
