### ISSUE TITLE
JSONP support with HTTPClient

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/universal#1141]
# Bug Report

#### What is the expected behavior?
JSONP API calls should work with Angular Universal

#### What is the current behavior?
It's freezing the server 

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
