### ISSUE TITLE
TsConfig paths compiler options is broken

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/universal#1142]
# Bug Report

#### What is the expected behavior?
path aliases should work

#### What is the current behavior?
Build error - cant resolve path

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "src",
    "importHelpers": true,
    "paths": {
      "@shared/*": ["shared/*"]
    }
}

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@shared/guards/authentication.guard'

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

I updated to latest angular core and angular cli

**Comment by cgatian** [comment]
Check  your tsconfig setup in the `tsconfig.server.json`. I ran into this snag, I had bad configuration. It does work!

**Comment by Jucuzzi** [comment]
I met this problem too , import { AppUtil } from 'src/app/app-core/app-util'; doesn't work

**Comment by CraigComeOnThisNameCantBeTaken** [comment]
I was missing the * in my paths
