### ISSUE TITLE
Angular flicker after DOMContentLoaded event triggerd

### ISSUE THREAD

**Issue by nadermedhet148** [angular/universal#1144]
my app  flicker after winow load content 

https://www.webpagetest.org/video/compare.php?tests=190320_RZ_9d574f125fc8bddbf7968a724a786fdf-r:1-c:0

look at 83% it's return to 78% again i think it's decrease my performance

this is my main app bootstrapping 

`document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule)
    .catch(err => console.log(err));
});
` 
and i enabled  initialNavigation in app routes

**Comment by nauraizmushtaq** [comment]
Hi I'm using Angular SSR with ASP.Net using SPA Services. Application became irresponsive when i pass 1K concurrent request using apache JMeter or WebSurg. Most of the time connection timeout shows up or application took more then 120 secs to load the home page.

It would be very helpful if someone could suggest a possible solution
