### ISSUE TITLE
Iframe is not working with SSR

### ISSUE THREAD

**Issue by hamid-mustafa** [angular/universal#1145]
# Bug Report

####  When i implement stripe payment method they will render whole HTML with iframe it will not work with SSR?

**Comment by OlegGranevskij** [comment]
@hamo1122  not work how? You get error in SSR? What if you just add isBrowser check for payments block?

**Comment by csaszika** [comment]
@OlegGranevskij for me SSR works with iframe but not perfectly.

The source content has loaded but with kind of zoomed state. I mean it is like ignoring my requested size. But if I stress the browser with resize for example it corrects itself. Page reloading does not help.

Now a kind of workaround:
this.windowRef.native.dispatchEvent(new Event("resize"));

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
