### ISSUE TITLE
Angular SSR: how to prevent re-rendering of generated HTML in the client side?

### ISSUE THREAD

**Issue by 4z5lz** [angular/universal#1148]
I'm developing a web site with Angular 7 + Angular Universal for server side rendering.

Some Angular component has a tag with some ad page:
`<iframe  src='...'>`
The server sends rendered HTML to the client. Browser gets the HTML and starts loading page in the iframe. But once Angular application bootstraped in browser, HTML again gets rendered on the client side, and as a result loading of the page in the iframe interrupted and starts loading again.

Is there some solution to prevent re-render ready HTML (or some component) again if it's already rendered on the server?

P.S. I'm using StateTransfer to prevent AJAX requests in the client, so it's not an issue.

Thanks!

**Comment by alizoli** [comment]
Hi, we have the same problem, did you manage to resolve this issue?

**Comment by pairmix** [comment]
same issue for me

**Comment by 4z5lz** [comment]
@pairmix @alizoli I still using iframe with this behavior. Unfortunately, Angular rerender DOM again in the client instead of reusing ready HTML

**Comment by arminops** [comment]
Any solutions for now? @4z5lz 

I'm not using any Iframes but still i have rerender issue. 

https://github.com/angular-schule/demo-ssr-playground/issues/5#issue-679513501

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
