### ISSUE TITLE
Add minimal express engine templating 

### ISSUE THREAD

**Issue by ayyash** [angular/universal#1149]
# Feature Request
in Asp.net and other engines, it comes out of the box to pass variables to index.html, it would be nice if ngExpressEngine allowed just a couple of literals (like `#value` or `<% value %>` and let us pass it in the render call.

#### What is the use-case or motivation for the desired behavior?
I can think of one, depending on ip address coming from server to render the homepage with a specific flavor

#### Is there anything else we should know?
Not sure this: https://github.com/angular/universal/blob/master/modules/express-engine/README.md#using-the-request-and-response covers it, but there are no examples to give me a clue

**Comment by mnahkies** [comment]
I agree this could be a nice feature. 

I currently have a module named `document-builder` that reads index.html from the file system and then replaces some placeholders with the appropriate content for the request. Once you have the resolved html as a string you can pass it to the express engine to render like this:

```
app.get("*", (req, res, next) => {
    const document = buildDocumentForRequest(req)

    res.render("index", { req, res, document }, (err, html) => {
        if (err) {
            return next(err)
        }

        res
            .status(200)
            .send(html)
    })
})
```

**Comment by alan-agius4** [comment]
Closing as this is not in scope of the Universal project.
