### ISSUE TITLE
TransferHttpCacheInterceptor doesn't apply cache properly with multivalue query parameter

### ISSUE THREAD

**Issue by daelmaak** [angular/universal#1150]
# Bug Report

#### What is the expected behavior?
Calling HttpClient's get method results in proper application of cached responses via TransferHttpCacheInterceptor in case one of the params properties is array and items were added/removed from that array. See screenshot:
![Screenshot from 2019-04-09 15-06-03](https://user-images.githubusercontent.com/34311965/55802723-177d4700-5ad9-11e9-9578-e8af9df408bf.png)

#### What is the current behavior?
Adding a value to a query parameter isn't necessarily recognized and therefore wrong cached value might be returned.
The problem is in [TransferHttpCacheInterceptor L56](https://github.com/angular/universal/blob/991472d1abe721d2ebba8c5faf89f7177a95bc68/modules/common/src/transfer_http.ts#L56) in `params.get(k)` which should rather be something like `params.map.get(k).join([whatever])` in order to work with the whole array rather than just with the first item of the array (see implementation of [HttpParams.prototype.get](https://github.com/angular/angular/blob/b17d1a9aa3519552dd098db44b9031f4651fbe3c/packages/common/http/src/params.ts#L139)).

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
1. Set up angular project with imported TransferHttpCacheModule
2. Call any endpoint via HttpClient like this
```
this.http.get('http://...', { params: {
  filter: ['color:black']
}})
```
3. Call the same endpoint  
```
this.http.get('http://...', { params: {
  filter: ['color:black', 'brand:apple']
}})
```
4. Notice that TransferHttpCacheInterceptor.prototype.makeCacheKey returns the same cache key now as for the point 2. That results in a wrong cached response being applied instead of getting the right one/calling the api directly.

#### What is the use-case or motivation for changing an existing behavior?
The use case is about using multivalue query parameters in http requests.
If you are interested, I can provide the PR.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: -
  - common: 7.1.1
  - express-engine: 7.1.1
  - hapi-engine: -
  - module-map-ngfactory-loader: 7.1.1
```
Angular CLI: 7.3.6
Node: 8.15.1
OS: linux x64
Angular: 7.2.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6
@angular-devkit/build-angular     0.13.6
@angular-devkit/build-optimizer   0.13.6
@angular-devkit/build-webpack     0.13.6
@angular-devkit/core              7.3.6
@angular-devkit/schematics        7.3.6
@angular/cdk                      7.3.5
@angular/cli                      7.3.6
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.5
@angular/pwa                      0.13.6
@ngtools/webpack                  7.3.6
@schematics/angular               7.3.6
@schematics/update                0.13.6
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

Ubuntu 18.04
```

**Comment by dottodot** [comment]
This is what I've tried which seems to work.

```
    const encodedParams = params
      .keys()
      .sort()
      .map(k =>
        params
          .getAll(k)
          .map(q => `${k}=${q}`)
          .join('&')
      )
      .join('&');
```

**Comment by Jackson88** [comment]
Any updates here?

**Comment by Denrox** [comment]
+1

**Comment by todorpavlovic** [comment]
Any updates ?

**Comment by markusmo** [comment]
We are currently also experiencing this issue with headers. It would be great if we were able to switch off and on this behaviour.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
