### ISSUE TITLE
SSR Only generates html on first page

### ISSUE THREAD

**Issue by mikelsulanjaku** [angular/universal#1151]
# Bug Report

#### What is the expected behavior?
Project generates html in the source for all the children routes

#### What is the current behavior?
Only generates and displays html for the first page when you view source.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ X] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
Have a simple project with more than one router-outlet and build:ssr

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
Angular CLI: 7.3.8
Node: 10.15.3
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cdk                      7.3.7
@angular/cli                      7.3.8
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.8
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.29.0
```

#### Is there anything else we should know?

I have an angular project that contains a Shell module which in turn has a template page with a header, a footer and a main content are with a router-outlet which allows me to load any page within that template. That means I have one router-outlet at the app level and another one at the shell level. I did follow the instructions on the angular universal page and it did successfully generate all the files required for server side rendering. I have a main route also for each extra module I have children routes using the shell template.

app routing at the app level:

const routes: Routes = [
// Fallback when no prior route is matched
{
path: '**',
redirectTo: '',
pathMatch: 'full'
}
];
@NgModule({
imports: [
RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules, enableTracing:false })
],
exports: [RouterModule],
providers: []
})
export class AppRoutingModule {}

At the module level:

const routes: Routes = [
Shell.childRoutes([
{
path: '',
component: CheckoutComponent
},
{
path: 'checkout',
component: CheckoutComponent
}
])
];

@NgModule({
imports: [RouterModule.forChild(routes)],
exports: [RouterModule]
})
export class CheckoutRoutingModule {}

Shell Service:

_export class Shell {
/**

Creates routes using the shell component and authentication.

@param routes The routes to add.

@return The new route using shell as the base.
*/
static childRoutes(routes: Routes): Route {
return {
path: '',
component: ShellComponent,
children: routes,
canActivate: [AuthenticationGuard],

// Reuse ShellComponent instance when navigating between child views
data: { reuse: true }
};
}
}_

Shell component:

Everything is good except that after building and serving the project, when viewing the source on the first page everything is nicely generated in html however, any other route, does render on the browser side but when viewing the source I always see the content of the first page.

How do I make sure that every child route generates html accordingly?

**Comment by mnahkies** [comment]
Once the page has loaded, control is given to the client side bundle which then handles routing, rendering, etc as in a non-SSR rendered Angular application.

Try doing `curl http://localhost:4000/checkout` (replace with correct url) and I believe you'll see the HTML that you're expecting.

This is by design - the universal engine is not intended to render every page for a session, just the first page that is loaded (whether that is the home page, or some other page).
