### ISSUE TITLE
(Angular 7) Prevent some modules (authorized) to be prerendered and keep the default angular behavior

### ISSUE THREAD

**Issue by Bleil** [angular/universal#1153]
# Issue

#### What is the desired behavior?
Prevent some modules (authorized) to be prerendered and keep the default angular behavior

#### What is the use-case or motivation for the desired behavior?
I have some modules that just authorized users can access and there is no need to be prerendered because I just use SSR for SEO.

I am having some issues on how to render that modules because the node server is unauthorized and because of `TransferHttpCacheModule` the browser is not doing the apis calls again.

Can someone help me how to figure it out and fix this?

#### Is there anything else we should know?
I am using the latest version of Angular, using Lazy Modules and followed the Universal tutorial on the official website.

**Comment by CaerusKaru** [comment]
This bug tracker is not for support issues. Please use Gitter or StackOverflow for topics like that.
