### ISSUE TITLE
Universal does not populate app-root tag

### ISSUE THREAD

**Issue by oskarious** [angular/universal#1154]
# Bug Report

#### What is the expected behavior?
Universal should populate app-root tags with html.

#### What is the current behavior?
Universal does not populate app-root. Returns the "normal" non universal index page.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [x] module-map-ngfactory-loader
```
Unsure of where exactly it is happening in the flow.

#### Minimal reproduction with instructions:
Have been unabe to set one up as this is happening in a already fairly large project and am unsure where it exactly fails.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common: 7.1.1
  - express-engine: 7.1.1
  - hapi-engine:
  - module-map-ngfactory-loader: 7.1.1
```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 7.3.1
Node: 8.11.4
OS: win32 x64
Angular: 7.2.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              7.3.1
@angular-devkit/schematics        7.3.1
@angular/cdk                      7.3.2
@angular/cli                      7.3.1
@angular/material                 7.3.2
@ngtools/webpack                  6.1.5
@schematics/angular               7.3.1
@schematics/update                0.13.1
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.9.2
```

#### Is there anything else we should know?
We are adding universal to a already existing project. Apart from having to get rid of a few DOM api calls (to window and document) it seems to have worked well. I also read somewhere that `renderModuleFactory` "fails" silently, i.e. returns the non universal html page if it encounters any DOM api calls, which it should not do anymore. I have also set up a prerender script similar to the one in the universal example that produces index.html files per route, and same thing is happening there with `renderModuleFactory` as opposed to using the `ngExpressEngine`.

**Comment by vikerman** [comment]
Is it possible to create a repro? It is difficult to debug this otherwise. It does sound like an error being ignored silently - But that is definitely not the intended behavior. The server console should print the error in normal cases.

**Comment by m-te** [comment]
I am having the exact same error/problem here
@32000
https://github.com/angular/angular/issues/32000

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
