### ISSUE TITLE
Set 404/505 status when open incorrect page (SEO) Angular 6+

### ISSUE THREAD

**Issue by Denis-Evseev** [angular/universal#1156]
# Bug Report

#### What is the expected behavior?

When open any incorrect pages to see 404 error status. Search engines use it to identify if a page can be crawled or not. Without this error status, Google/Yandex significantly lowers positions 

#### What is the current behavior?

It retrieves 200 Status for all pages...

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

I have tried all solutions mentioned here:
https://github.com/angular/universal/issues/667
https://github.com/angular/universal/issues/969
https://www.thecodecampus.de/blog/angular-universal-handle-404-set-status-codes/

but it seems to me no longer works for Angular 6+. The key change took place in 
import {Response} from 'express'; - it longer allow to set status:
this.response.status(404);

and there is no way to replace it with any object

#### What is the use-case or motivation for changing an existing behavior?

I believe it has MUST HAVE feature of Universal

#### Environment:

Output from: `ng --version`.
Angular CLI: 7.3.8
Node: 8.9.0
OS: win32 x64
Angular: 7.2.13
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
```

#### Is there anything else we should know?

Guys please help, spent 2 days already...

**Comment by UserGalileo** [comment]
Setting the desired status code in the express response is working fine to me, used it in both Angular 6 and 7.

You have to import express' typings, and then you can do:
```typescript
import { Response } from 'express';

// In the constructor
constructor(@Inject(RESPONSE) private response: Response) {}

// Whenever you want to set the 404 code
this.response.statusCode = 404;
```

**Comment by MarkPieszak** [comment]
Closing as answered above.

`RESPONSE` comes from [`@nguniversal/common`](https://github.com/angular/universal/blob/master/modules/common/README.md) as well: https://github.com/angular/universal/blob/master/modules/common/tokens/src/tokens.ts#L12
