### ISSUE TITLE
Strange 404 errors where assets are requested from api endpoint

### ISSUE THREAD

**Issue by dottodot** [angular/universal#1160]
I have a bit of a strange issue that I can't find the cause of, and the issue is only occurring in the universal part of my app. Basically I keep gettings 404 errors in my Sentry logs where it looks like assets are being requested from my api endpoints.

so for example
```
https://api.example.com/page/styles.34c46b0337b6e0cd205d.css
```
and another example is where a telphone number link (which is just html in my footer component) gets sent to the api i.e
```
https://api.example.com/page/tel:+441112223333
```
another bizarre example is the phone number ending up in a query param
```
https://api.example.com/product?$category=tel:+441112223333
```
and the only place that sets the query params is as follows
```
this.products$ = this.route.params.pipe(
      switchMap((params: any) => {
        return this.service.find('product', {
          $category: params['category']
        });
      })
    );
```
so how could a tel link end up in `route.params`.

I just can't see how any of this can be happening so I'm hoping someone can shed some light on the possible cause as I'm baffled.

**Comment by vikerman** [comment]
Hi - Which engine are you using?

In the express-engine we have a default routing that might be tripping you up -

https://github.com/angular/universal/blob/master/modules/express-engine/schematics/install/files/root/__serverFileName%40stripTsExtension__.ts#L46

The server is the only place capable of returning a 404. Can you debug around there? You can then fix `server.ts` routing to suit your needs.

**Comment by dottodot** [comment]
@vikerman thanks for the info. I'll try error logging on my server.ts to see what that throws up. At the moment I'm using an ErrorHandler and HttpInterceptor to catch error in both browser and universal should I not be doing this?

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
