### ISSUE TITLE
Provide the request context in Angular server side

### ISSUE THREAD

**Issue by RadouaneRoufid** [angular/universal#1161]
# Feature Request

#### What is the desired behavior?
Make the request context (cookies, headers, current user...) available in the Angular app server side. 

#### What is the use-case or motivation for the desired behavior?
I'm using universal socket-engine to make server side rendering on my Angular application. I want to provide the request context (cookies, current user...) available in the Angular app server side. 

#### Is there anything else we should know?
After seeing the source code, below the step to be done to make such feature :

1. Adding context attribute to RenderOptions
```
export interface RenderOptions {
  bootstrap: Type<{}> | NgModuleFactory<{}>;
  providers?: StaticProvider[];
  url?: string;
  document?: string;
  documentFilePath?: string;
  context?: any;
}
```

2. Providing the context by dependy injection in modules/common/engine/src/engine.ts 

```
// Declare and export an injection token
export const SERVER_CONTEXT: InjectionToken<any> = new InjectionToken<any>('SERVER_CONTEXT');
...

async render(opts: RenderOptions): Promise<string> {
    // if opts.document dosen't exist then opts.documentFilePath must
    const doc = opts.document || await this.getDocument(opts!.documentFilePath as string);
    const extraProviders = [
      ...(opts.providers || []),
      ...(this.providers || []),
      {provide: SERVER_CONTEXT, useValue: JSON.parse(opts.context)}, // <-- Providing the context
      {
        provide: INITIAL_CONFIG,
        useValue: {
          document: doc,
          url: opts.url
        }
      }
    ];

    const factory = await this.getFactory();
    return renderModuleFactory(factory, {extraProviders});
  }
```

**Comment by mnahkies** [comment]
If you're using the express universal engine, then it sounds like you want to inject the req / res objects: https://github.com/angular/universal/blob/master/modules/express-engine/README.md#using-the-request-and-response

These are the standard express objects that you can find documented here: https://expressjs.com/en/api.html and provide access to things like cookies, headers, etc.

Note that these will be null when the code is executing client side, so be sure to handle this appropriately.

**Comment by RadouaneRoufid** [comment]
I'm not using express engine. This feature will allow every other technology (php, Java...) to inject it's own context server side. In my case, I'm using socket-engine from spring boot backend.

**Comment by RadouaneRoufid** [comment]
Any news on that ?

**Comment by vikerman** [comment]
@RadouaneRoufid - Hi - Are you not able to use the `providers` in the socket engine for this?

https://github.com/angular/universal/blob/master/modules/socket-engine/src/main.ts#L29

**Comment by markharding** [comment]
@vikerman - could you please give an example of how this could work? 

Is it possible to use providers as a kind of middleware?

**Comment by RadouaneRoufid** [comment]
@vikerman Providers cannot be used there because the context is retrieved dynamically after the socket server is started.

I think provoding the context in the renderOptions is the best option. However, the injectionToken **must not** be declared in @universal/common because this package requires "fs" module that does not exist in the browser.

**Comment by alan-agius4** [comment]
Closing as socket-engine is no longer supported.
