### ISSUE TITLE
Dynamic imports for lazy loaded routes doesn't work with express-engine

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1165]
# Bug Report

#### What is the expected behavior?
ng add @nguniversal/express-engine works with the new dynamic imports syntax in Angular 8.0

#### What is the current behavior?
Get an error when doing SSR for lazy route with
 
Cannot 'call' of undefined

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [x] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
git clone git@github.com:vikerman/v8-lazy.git

npm run build:ssr
npm run serve:ssr

Navigate to 'localhost:4000/lazy'

#### Environment:
**@nguniversal versions**
  - express-engine: 8.0.0-rc.1
  - hapi-engine: 8.0.0-rc.1
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by vikerman** [comment]
https://github.com/angular/universal/commit/d8be7af200f

**Comment by naturalfreak** [comment]
When are you planning to release @nguniversal/express-engine version 8 ? New lazy load router is not working for @nguniversal/express-engine version 8.0.0-rc.1.
