### ISSUE TITLE
Server build fails after `ng add @nguniversal/express-engine` to a project that has been updated from Angular 7.0 to 8.0 

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1166]
# Bug Report

#### What is the expected behavior?
Build works after adding @nguniversal/express-engine to project upgraded from 7.0 to 8.0 (works in a new 8.0 project)

#### What is the current behavior?
Build throws an error about polyfills-es5.js.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [x] hapi-engine
- [ ] module-map-ngfactory-loader
```
#### Minimal reproduction with instructions:
(Create a 7.0 project)
ng new test
cd test/

(Update to 8.0)
ng update @angular/core @angular/cli --next

(Add express-engine)
ng add @nguniversal/express-engine

(Build)
npm run build:ssr

#### Environment:
**@nguniversal versions**
8.0.0-rc.1
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?
Works in a new 8.0 project but fails for a project upgraded from 7.0.

**Comment by vikerman** [comment]
Fixed by https://github.com/angular/universal/commit/d8be7af200f

**Comment by tzjoke** [comment]
Yeah, I came across this issue after I upgraded to rc1. Looking forward a stable version to look at new features under universal.
