### ISSUE TITLE
Angular Universal forward IP from client for all SSR API calls

### ISSUE THREAD

**Issue by KoIIIeY** [angular/universal#1168]
# Proposal

#### What is the summary of the proposal?

I determine the user's city by IP and want the assembled page to refer to a specific city. How can I forward IP to all api requests that SSR makes from the node backend (my api in another php backend)? Now there is always 127.0.0.1

#### What is the proposal?

How can I do it?

#### Is there anything else we should know?

**Comment by vikerman** [comment]
You can inject extra information using the `providers` section of ngExpressEngine - https://github.com/angular/universal/blob/master/modules/express-engine/src/main.ts#L27 . This can be injected into the places where you are making the backend calls - either manually or writing a HTTP interceptor to automatically add it to every call.
