### ISSUE TITLE
After running npm run serve:ssr   IDBIndex is not defined

### ISSUE THREAD

**Issue by apunjaval** [angular/universal#1170]
# Bug Report

#### What is the expected behavior?
Node Js should boot up after running  npm run serve:ssr

#### What is the current behavior?

Getting error while running the command npm run server:ssr 

**/valuates_buyer/dist/server.js:230839
proxyRequestMethods(Index, '_index', IDBIndex, [
                                     ^
ReferenceError: IDBIndex is not defined**

#### What modules are related to this issue?
```
 Node.js® Express 
```

#### Minimal reproduction with instructions:

Details of package.json

  "build:client-and-server-bundles": "ng build --prod && ng run buyerdashboard:server:production",
    "build:prerender": "npm run build:client-and-server-bundles && npm run compile:prerender && npm run generate:prerender",
    "generate:prerender": "npm run webpack:prerender && node dist/prerender.js",
    "compile:prerender": "tsc -p prerender.tsconfig.json",
    "webpack:prerender": "webpack --config webpack.prerender.config.js"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-angular": "~0.800.0",
    "@angular/animations": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/platform-server": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@ng-bootstrap/ng-bootstrap": "^4.0.1",
    "@ngu/carousel": "^1.5.5",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "bootstrap": "^4.3.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.1",
    "express": "^4.15.2",
    "firebase": "6.1.0",
    "font-awesome": "^4.7.0",
    "hammerjs": "^2.0.8",
    "ng-bootstrap": "latest",
    "ng-simple-slideshow": "^1.2.3",
    "ngrok": "^3.1.1",
    "node-sass": "^4.12.0",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.3.3",
    "tslib": "^1.9.0",
    "web-animations-js": "github:angular/web-animations-js#release_pr208",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular/cli": "^8.0.1",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/jasmine": "^3.3.5",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "^10.12.18",
    "codelyzer": "^5.0.1",
    "jasmine-core": "^3.3.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^2.0.0",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "^2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "node-gyp": "^4.0.0",
    "protractor": "^5.4.2",
    "rxjs-tslint": "^0.1.6",
    "tar": "^4.4.9",
    "ts-loader": "^5.2.0",
    "ts-node": "~3.2.0",
    "tslint": "^5.12.0",
    "typescript": "3.4.5",
    "webpack": "^4.32.2",
    "webpack-cli": "^3.1.0",
    "webpack-dev-server": "^3.5.1"
  }
}

#### What is the use-case or motivation for changing an existing behavior?
To make website SEO compliant : valuates.com

#### Environment:
**@nguniversal versions**
 Node.js® Express 
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
Angular CLI: 8.0.1
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.1
@angular-devkit/build-angular              0.800.1
@angular-devkit/build-optimizer            0.800.1
@angular-devkit/build-webpack              0.800.1
@angular-devkit/core                       8.0.1
@angular-devkit/schematics                 8.0.1
@angular/cli                               8.0.1
@angular/fire                              5.2.1
@ngtools/webpack                           8.0.1
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   0.0.0
@schematics/angular                        8.0.1
@schematics/update                         0.800.1
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.32.2
-->
```

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/lib/node_modules/node/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'serve:ssr'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.3.1
4 verbose run-script [ 'preserve:ssr', 'serve:ssr', 'postserve:ssr' ]
5 info lifecycle buyerdashboard@0.0.0~preserve:ssr: buyerdashboard@0.0.0
6 info lifecycle buyerdashboard@0.0.0~serve:ssr: buyerdashboard@0.0.0
7 verbose lifecycle buyerdashboard@0.0.0~serve:ssr: unsafe-perm in lifecycle true
8 verbose lifecycle buyerdashboard@0.0.0~serve:ssr: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/akshaypunja/apunja/code/QABuild/buyerdashboardun2/valuates_buyer/node_modules/.bin:/Users/akshaypunja/Downloads/google-cloud-sdk/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Wireshark.app/Contents/MacOS:/Users/akshaypunja/apunja/runtime/apache-maven-3.5.0/bin:/Users/akshaypunja/apunja/runtime/appengine-java-sdk-1.9.54/bin:/Users/akshaypunja/apunja/runtime:/Users/akshaypunja/apunja/runtime/apache-ant-1.10.1/bin
9 verbose lifecycle buyerdashboard@0.0.0~serve:ssr: CWD: /Users/akshaypunja/apunja/code/QABuild/buyerdashboardun2/valuates_buyer
10 silly lifecycle buyerdashboard@0.0.0~serve:ssr: Args: [ '-c', 'node dist/server' ]
11 silly lifecycle buyerdashboard@0.0.0~serve:ssr: Returned: code: 1  signal: null
12 info lifecycle buyerdashboard@0.0.0~serve:ssr: Failed to exec serve:ssr script
13 verbose stack Error: buyerdashboard@0.0.0 serve:ssr: `node dist/server`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:200:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:200:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid buyerdashboard@0.0.0
15 verbose cwd /Users/akshaypunja/apunja/code/QABuild/buyerdashboardun2/valuates_buyer
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/lib/node_modules/node/bin/node" "/usr/local/bin/npm" "run" "serve:ssr"
18 verbose node v12.3.1
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error buyerdashboard@0.0.0 serve:ssr: `node dist/server`
22 error Exit status 1
23 error Failed at the buyerdashboard@0.0.0 serve:ssr script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
#### Is there anything else we should know?

**Comment by apunjaval** [comment]
Code that is throwing the error in server.js is 


/***/ "firebase":
/*!***************************!*\
  !*** external "firebase" ***!
  \***************************/
/*! no static exports found */
/***/ (function(module, exports) {

**module.exports = __webpack_require__(405);**

/***/ }),

/***/ "firebase/app":
/*!*******************************!*\
  !*** external "firebase/app" ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = __webpack_require__(420);

/***/ }),

/***/ "firebase/auth":
/*!********************************!*\
  !*** external "firebase/auth" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

**Comment by vikerman** [comment]
It seems you are using a browser only API (IDBIndex) on the server. 

angularfire should avoid this situation though. Please open a bug in that project if that's not the case.
