### ISSUE TITLE
serve static prerendered files with an express server instead of http-server

### ISSUE THREAD

**Issue by ohabash** [angular/universal#1172]
simply need help with something.

## problem
right now prerendering is working in my universal app. I start the server like this

```
cd dist/browser && http-server
```

but now my site does not have a configurable server. Id like to host an api and the static prerendered paths with an an express server. 

## tried
to added this middleware to `server.ts`

```
app.get('*', function (req, res) {
    res.render(`${req.path}/index`, { req: req });
});
```
that works but unlike `http-server` there is a flicker; maybe something wrong with the `transferState` ?

## was expecting
the express app to serve prerendered routes (`node dist/server`) exactly the same as `http-server` (`cd dist/browser && http-server`)

**Comment by vikerman** [comment]
This is being addressed as part of #1201
