### ISSUE TITLE
Angular Universal and cors issue - Origin is undefined

### ISSUE THREAD

**Issue by roshanj80** [angular/universal#1173]
# Bug Report

I'm using Angular Universal to enable SSR for SEO support.

```
var whitelist = ['https://www.example.com'];
app.use(cors({
  origin: function (origin, callback) {
    if (whitelist.indexOf(origin) !== -1) {
      callback(null, true)
    } else {
      callback(new Error('Not allowed by CORS'))
    }
  },
  optionsSuccessStatus: 200
}));
```

I have also enabled CORS in my backend. 
The problem I'm facing is, **origin** is undefined when Angular is running on the server to fetch all my data initially.

If I disable CORS, and when I don't check my origin, it works perfectly in the browser.

#### What is the expected behavior?

Origin should be my domain from which I'm sending the request.
I understand that origin header will be sent only from the browser, but Angular Universal needs to run on the server initially for SEO support.

With this issue, my APIs cannot be protected when I'm using Angular Universal, and I will be forced to give public access. This is a serious issue, please resolve it ASAP.

**Comment by vikerman** [comment]
Needs investigation. Don't know what's the best way to solve this at the top of my head.

**Comment by vikerman** [comment]
ok - Looked into this a bit.

CORS is meant to be enforced by the browser. In your case you are trying to enforce it on the server. 

On the API server you should just configure the cors middleware to set the right `Access-Control-Allow-Origin` and it is up to the browser to enforce it. There are many cases where you probably won't get the `origin` set correctly - And not just when calling the API during SSR. So you cannot really rely on this being set correctly.

You should just use the CORS middleware to set the allow your domain:port and just let the browser enforce it.
