### ISSUE TITLE
Wrong environment path in server configuration after ng add @nguniversal without default application.

### ISSUE THREAD

**Issue by celom** [angular/universal#1177]
# Bug Report

#### What is the expected behavior?

After adding @nguniversal using _ng add_, without a default workspace application, the environment path from angular.json in projects.[clientProject].architect.**server**.configurations.production.fileReplacement should inherit the same values from projects.[clientProject].architect.**build**.configurations.production.fileReplacement.

#### What is the current behavior?

Environment path is populated with the default "src/environments/environment.ts" value, regardless of the specified clientProject environment path.

![environment_bug](https://user-images.githubusercontent.com/15002036/59593602-24767200-90ea-11e9-87a2-44a6500f861f.PNG)

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:

1. Create empty workspace : ng new appEnvironment --create-application false --routing false --style css
2. Create application : ng g application bug --routing --style css
3. Add @nguniversal to"bug" application : ng add @nguniversal/express-engine --clientProject bug
4. Run build:ssr : npm run build:ssr
[_fail_]

#### What is the use-case or motivation for changing an existing behavior?

Fix bug. Unfrustrate. Promote world peace.

#### Environment:

Angular CLI: 8.0.3
Node: 12.3.1
OS: win32 x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.3
@angular-devkit/build-angular              0.800.3
@angular-devkit/build-optimizer            0.800.3
@angular-devkit/build-webpack              0.800.3
@angular-devkit/core                       8.0.3
@angular-devkit/schematics                 8.0.3
@angular/cli                               8.0.3
@ngtools/webpack                           8.0.3
@nguniversal/express-engine                7.0.2
@nguniversal/module-map-ngfactory-loader   7.0.2
@schematics/angular                        8.0.3
@schematics/update                         0.800.3
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.30.0

#### Is there anything else we should know?

You rock!

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. 

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
