### ISSUE TITLE
Angular does not wait for async (Promise) BEFORE_APP_SERIALIZED hook.

### ISSUE THREAD

**Issue by izmaylovdev** [angular/universal#1179]
# Bug Report

#### What is the expected behavior?
Angular wait until BEFORE_APP_SERIALIZED listener finish work and returned (from listener) Promise resolve.

#### What is the current behavior?
Angular returns a response (html) before listener finish his work (inserting content to the DOM)

#### Minimal reproduction with instructions:
Try to add this provider to your app and check page source code.

```
export const listenerFactory = (rendererFactory, document) => () => new Promise(resolve => {
  const renderer: Renderer2 = rendererFactory.createRenderer(document, {
    id: 'alternate_link_server_injector',
    encapsulation: ViewEncapsulation.None,
    styles: [],
    data: {}
  });

  setTimeout(() => {
     const link = renderer.createElement('link');
     renderer.setAttribute(link, 'rel', 'alternate');
     renderer.setAttribute(link, 'hreflang', 'sometext');
     renderer.setAttribute(link, 'href', 'sometext');
     renderer.appendChild(document.head, link);
     resolve();
  }, 5000); 
});

export const alternateLinkInjectorServerProvider = {
   provide: BEFORE_APP_SERIALIZED,
   useFactory: listenerFactory,
   deps: [RendererFactory2, DOCUMENT],
   multi: true
};
```
#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: ^7.1.1
  - common: ^7.1.1
  - express-engine: ^7.1.1
  - module-map-ngfactory-loader: ^6.0.0

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.13.9
@angular-devkit/build-angular       0.13.9
@angular-devkit/build-optimizer     0.13.9
@angular-devkit/build-webpack       0.13.9
@angular-devkit/core                7.3.9
@angular-devkit/schematics          7.3.9
@angular/animations                 7.2.0
@angular/cdk                        7.3.7
@angular/cli                        7.3.9
@angular/common                     7.2.0
@angular/compiler                   7.2.0
@angular/forms                      7.2.0
@angular/http                       7.2.0
@angular/material                   7.3.7
@angular/platform-browser           7.2.0
@angular/platform-browser-dynamic   7.2.0
@angular/platform-server            7.2.0
@angular/router                     7.2.0
@angular/service-worker             7.2.0
@ngtools/webpack                    7.3.9
@schematics/angular                 7.3.9
@schematics/update                  0.13.9
rxjs                                6.5.2
typescript                          3.2.4
webpack                             4.29.0
```

**Comment by MarkPieszak** [comment]
Can you try to view source and see if those `<link>` tags are being added?
I'm wondering if the front-end is knocking them out during the CSR re-render.

It looks like you're utilizing `BEFORE_APP_SERIALIZED` completely right as well.

Example of it in action here:
https://github.com/angular/angular/blob/071ee64d914e9272b8495563f3ad14f70bf12691/packages/platform-server/test/integration_spec.ts#L54-L64

We might need to investigate this more. 
@vikerman `setTimeout` should be waiting properly here (zones/etc) - strange that this seems to be passing through ?

**Comment by vikerman** [comment]
This is working as intended. BEFORE_APP_SERIALIZED doesn't support an async task.

What is the use case for this?

**Comment by vikerman** [comment]
Yes - Looking at the test case it does appear we should handle async callbacks for BEFORE_APP_SERIALIZED. 

Can you debug the process to see whether it is being treated as an async task here ? https://github.com/angular/angular/blob/7102ea80a91edeecc1645ebe108033c8cb63e4d3/packages/platform-server/src/utils.ts#L57

**Comment by izmaylovdev** [comment]
@MarkPieszak @vikerman All works well. Error was in another part of code... Sorry for disturb. My bad.
