### ISSUE TITLE
remove requirement of input[type="text"] for preboot

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#118]

**Comment by jeffbcross** [comment]
What is the problem? I removed `type=text` from this line in universal starter example and it seems to work fine: https://github.com/angular/universal-starter/blob/9f15960f67e49f2151416cd7d18a9a05a7b3f019/src/app.ts#L8

**Comment by gdi2290** [comment]
this is for preboot to transfer over state in the `value` prop

**Comment by gdi2290** [comment]
preboot using `input[type="text"] ` to query the DOM and transfer over the state from the elements. @jeffwhelpley knows more about preboot than I do

**Comment by jeffwhelpley** [comment]
Yeah, sorry, this is a small issue I will try to fix this weekend. It is just that the preboot selector for text boxes assumes it will be type="text". I need to add the use case where there is an input element without any type attribute (and thus uses the default which is text). This is needed to make sure data typed into `<input name="blah"></input>` is correctly replayed once the Angular client bootstrap is complete.
