### ISSUE TITLE
Confusion with readme 

### ISSUE THREAD

**Issue by devbenzy** [angular/universal#1183]
In the readme file, @angular/cli will generate LAZY_MODULE_MAP in its main output bundle if you put app.platform = 'server'. Where do I set this ?

**Comment by MarkPieszak** [comment]
Those actually come from the built (or future-built) main server file.
Hope that helps!

The nguniversal schematic automatically adds these for you as well :)
`⚡ ng add @nguniversal/express-engine --clientProject {your-projects-name}`

```ts
// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const { 
  AppServerModuleNgFactory, 
  LAZY_MODULE_MAP, 
  ngExpressEngine, 
  provideModuleMap
} = require('./dist/server/main');

// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));
```
