### ISSUE TITLE
Can't use angular universal schematic

### ISSUE THREAD

**Issue by programmerkgit** [angular/universal#1186]
# Bug Report

#### What is the expected behavior?
after `ng add @nguniversal/express-engine --clientProject {my-project-name}`, 
`npm run build:ssr && npm run serve:ssr` should work

#### What is the current behavior?
`
> webpack --config webpack.server.config.js --progress --colors
sh: webpack: command not found
`
$PATH correctly  points to node_modules/.bin/webpack, and ./node_modules/.bin/webpack exists

#### What modules are related to this issue?
```
- [ ] webpack
- [ ] express-engine
```

#### Minimal reproduction with instructions:
`ng add @nguniversal/express-engine --clientProject {my-project-name}`
`npm run build:ssr && npm run serve:ssr`

#### Environment:
Angular CLI: 8.0.2
Node: 10.15.3
OS: darwin x64
Angular: 8.0.0
... common, compiler, compiler-cli, core, elements, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.800.2
@angular-devkit/build-angular              0.800.2
@angular-devkit/build-optimizer            0.800.2
@angular-devkit/build-webpack              0.800.2
@angular-devkit/core                       8.0.2
@angular-devkit/schematics                 8.0.2
@angular/animations                        8.0.3
@angular/cdk                               8.0.1
@angular/cli                               8.0.2
@angular/fire                              5.2.1
@angular/material                          8.0.1
@angular/platform-server                   8.0.3
@ngtools/webpack                           8.0.2
@nguniversal/express-engine                8.0.0-rc.1
@nguniversal/module-map-ngfactory-loader   8.0.0-rc.1
@schematics/angular                        8.0.2
@schematics/update                         0.800.2
rxjs                                       6.5.2
typescript                                 3.4.5
webpack                                    4.30.0

```


#### Is there anything else we should know?

**Comment by MarkPieszak** [comment]
Are you placing your correct project name where `{my-project-name}` is ?
Just tried to reproduce locally, and was able to add the schematic to a new CLI application without any issues.

If it's saying that - the problem might just be that everything didn't `install` properly, make sure all of the additions are in your packagejson (ensure they're in node_modules), and maybe do an `npm i` just incase to install everything and you should be all set :+1:
