### ISSUE TITLE
Don't ship server-side code to the client

### ISSUE THREAD

**Issue by th0r** [angular/universal#1187]
# Proposal

#### What is the summary of the proposal?
It would be great not to ship code fragments wrapped with `if (isPlatformServer(this.platform)) {...}` to the client.

I think occurrences of `isPlatformServer(this.platform)` can just be replaced with `false` in the client bundle and they will be automatically cut out by the minifier as unreachable code.

**Comment by vikerman** [comment]
The way we usually think about this is to have a Injectable() that has the default `providedIn: 'root'` (Tree shakeable provider) implementation pointing to the client version.

And then you would override the implementation with the server specific one in the `app.server.module.ts`. This way you would avoid shipping any code to client. Would that help with your use case?

**Comment by th0r** [comment]
@vikerman this approach usually complicates simple things e.g. slightly different behavior on client/server. In this case you have to:
 - Implement some base class with common functionality
 - Implement client and server classes that extends this base class
 - Provide different modules for client/server

In proposed case it will be just a single `*.service.ts` file with some `isPlatformServer` conditionals.

**Comment by alan-agius4** [comment]
Please see https://github.com/angular/angular-cli/pull/19355
