### ISSUE TITLE
Dynamic component with external source

### ISSUE THREAD

**Issue by favdev** [angular/universal#1197]
This would apply to any prerendered dynamic page that relies on an external source

I'm making an application that needs data from an external API to render. There are many sites so I will need to build a dynamic component to show this information.

Using the external API, you can search for a site via it's name but it's finicky and requires you to spell it exactly. Just using the word 'near' would return no results for example.

I understand that I will need to use Angular Universal at some point to prerender the page, I'm just wondering how we get from google search to dynamically rendered page as a result.

My questions are:

1. How do the other sites in those search results know what to render?

2. How are they able to show results on a google search if they need a site code to get that information and it isn't in the search (e.g. 0806500)?

3. Is this possible with Angular Universal?

![google-search](https://user-images.githubusercontent.com/51066860/60784850-ef62ba00-a193-11e9-96f1-1dce0345cdd2.png)

**Comment by MarkPieszak** [comment]
Yes definitely. There are different ways you could achieve things like this regardless of framework, but you'll need things like sitemaps / etc to let search engines be aware of some of this dynamic content that you could be rendering.

Some example information on the topic: https://thecontentworks.uk/dynamic-pages-seo-friendly/

Unfortunately this outside of the scope of Universal itself, but you should be able to apply typical strategies with Universal without a problem!
