### ISSUE TITLE
Add `initialNavigation: 'enabled'` to schematics 

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1200]
We have a lot of issues reported with  flickering in lazy routes in Universal. The solution is to set `initialNavigation: 'enabled'`.

This is a good default for Universal apps and we should automatically try to change `app.routing.module.ts` to set this flag as part of `ng add @nguniversal/express-engine`

**Comment by Splaktar** [comment]
@jbogarthyde FYI this wouldn't be the 'default' for Angular, but it would be part of enabling Universal if using `ng add`.

**Comment by Splaktar** [comment]
Based on the discussion in https://github.com/angular/universal/issues/1184, it looks like Preboot is required for most real world apps to avoid flicker. 

Is there some way to enable that as part of the Schematic? 
Or to add more complete docs for it other than just linking to it from the [SSR Guide](https://next.angular.io/guide/universal)?

**Comment by vikerman** [comment]
We are working on it at https://github.com/angular/universal/pull/1248

**Comment by Splaktar** [comment]
> @Splaktar We are working on it at #1248

@vikerman that PR only appears to cover the RouterModule initialNavigation configuration. It doesn't seem to cover Preboot or documenting how to install/configuring Preboot. In many real world apps, it's been reported that Preboot has been the only solution to resolve their flickering issues.
