### ISSUE TITLE
Angular CLI builder for a devserver/live reload

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1202]
Need to create an Angular CLI Architect builder that can provide development server that builds in watch mode and live reloads whenever the project changes.

We can consider replacing `ng serve` with this builder as part of the @nguniversal schematics.

**Comment by almgwary** [comment]
Any updates ?

**Comment by alan-agius4** [comment]
Also related to https://github.com/angular/universal/issues/1022

Hi @almgwary, this is something that we are currently looking at.

**Comment by alan-agius4** [comment]
Let's close this in favour of https://github.com/angular/universal/issues/1202 since there is more discussion over there.

Duplicate of https://github.com/angular/universal/issues/1202
