### ISSUE TITLE
screen is not defined

### ISSUE THREAD

**Issue by mohamedelmancy** [angular/universal#1204]
# Bug Report

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by m98** [comment]
@MarkPieszak This should be closed as it has not any information.
