### ISSUE TITLE
Template not rendering native external webcomponents

### ISSUE THREAD

**Issue by Noeldesarrollo** [angular/universal#1208]
When using Angular SSR, template render just works with angular components, but external components, like native webcomponents are not rendering.

I think bootstraping of external components through CUSTOM_ELEMENTS_SCHEMA are not registering components properly.

This code just apply for angular components: 

```typescript
const componentFactory = componentFactoryResolver.resolveComponentFactory(component)

viewContainerRef.createComponent(componentFactory)
```

**Comment by vikerman** [comment]
This is a known issue. We use Domino(https://github.com/fgnass/domino) for DOM API on the server and that doesn't support custom elements.

We have hacked together shims in the past for this. Will see if we can provide a solution as prt of Universal for this.
