### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by Temkit** [angular/universal#1209]
# Bug Report

#### What is the expected behavior?

serve:ssr -> run the app

#### What is the current behavior?
Error while running the app : **serve:ssr** 

> 
> 
> /Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123788
>                 var blob = new Blob([src], { type: 'text/javascript' });
>                            ^
> 
> ReferenceError: Blob is not defined
>     at module.exports (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123788:28)
>     at /Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123801:30
>     at Object.D/Az.5../worker.js (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123949:15)
>     at s (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123339:13)
>     at /Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123339:71
>     at /Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123344:27
>     at Object.D/Az.1../recorder.js (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123549:15)
>     at s (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123339:13)
>     at /Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123339:71
>     at Object.<anonymous> (/Users/knewtone/OneDrive/knewtone.com/projects/WorkSpace/softwares/yet/dist/server/main.js:123722:48)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! yet@3.1.1 serve:ssr: `node dist/server`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the yet@3.1.1 serve:ssr script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/knewtone/.npm/_logs/2019-07-24T09_19_18_327Z-debug.log

#### Minimal reproduction with instructions:

**Package.json**

> 
> {
>   "name": "yet",
>   "version": "3.1.1",
>   "config": {
>     "host": "******",
>     "cloudfront": "******",
>     "speccloudfront": "******"
>   },
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve",
>     "startprod": "ng serve --configuration=production",
>     "localbuild": "npm run commit && ng build --configuration=production && npm run deploy",
>     "build": "ng build --configuration=production",
>     "commit": "git add -A && git commit -m 'an other commit' && git push",
>     "compile:server": "webpack --config webpack.server.config.js --progress --colors",
>     "serve:ssr": "node dist/server",
>     "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
>     "build:client-and-server-bundles": "ng build --prod && ng run yet:server:production --bundleDependencies all"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "~8.1.2",
>     "@angular/cdk": "~8.1.1",
>     "@angular/common": "~8.1.2",
>     "@angular/compiler": "~8.1.2",
>     "@angular/core": "~8.1.2",
>     "@angular/forms": "~8.1.2",
>     "@angular/http": "~7.2.15",
>     "@angular/material": "^8.1.1",
>     "@angular/platform-browser": "^8.1.2",
>     "@angular/platform-browser-dynamic": "^8.1.2",
>     "@angular/platform-server": "^8.1.2",
>     "@angular/pwa": "^0.801.2",
>     "@angular/router": "~8.1.2",
>     "@angular/service-worker": "~8.1.2",
>     "@nguniversal/express-engine": "^8.1.1",
>     "@nguniversal/module-map-ngfactory-loader": "8.1.1",
>     "@types/lodash": "^4.14.136",
>     "@types/lodash-es": "^4.17.3",
>     "aws-amplify": "^1.1.32",
>     "aws-amplify-angular": "^3.0.7",
>     "aws-sdk": "^2.498.0",
>     "bcryptjs": "^2.4.3",
>     "blob-polyfill": "^4.0.20190430",
>     "body-parser": "^1.19.0",
>     "classlist.js": "^1.1.20150312",
>     "core-js": "^3.1.4",
>     "express": "^4.17.1",
>     "graphql": "^14.4.2",
>     "graphql-tag": "^2.10.1",
>     "hammerjs": "^2.0.8",
>     "lodash": "^4.17.15",
>     "mapbox-gl": "^1.1.1",
>     "moment": "^2.24.0",
>     "ngx-daterangepicker-material": "^2.1.7",
>     "ngx-mapbox-gl": "^3.3.1",
>     "ngx-summernote": "^0.6.5",
>     "rxjs": "~6.5.2",
>     "summernote": "^0.8.12",
>     "web-animations-js": "^2.3.2",
>     "written-number": "^0.9.1",
>     "zone.js": "~0.9.1"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.801.2",
>     "@angular/cli": "~8.1.2",
>     "@angular/compiler-cli": "~8.1.2",
>     "@angular/language-service": "~8.1.2",
>     "@types/jasmine": "~3.3.15",
>     "@types/jasminewd2": "~2.0.6",
>     "@types/node": "~12.6.8",
>     "codelyzer": "^5.1.0",
>     "jasmine-core": "~3.4.0",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~4.2.0",
>     "karma-chrome-launcher": "~3.0.0",
>     "karma-coverage-istanbul-reporter": "~2.0.6",
>     "karma-jasmine": "~2.0.1",
>     "karma-jasmine-html-reporter": "^1.4.2",
>     "node-sass": "^4.12.0",
>     "protractor": "~5.4.2",
>     "ts-loader": "^6.0.4",
>     "ts-node": "~8.3.0",
>     "tslint": "~5.18.0",
>     "typescript": "~3.4.3",
>     "webpack-cli": "^3.3.6"
>   }
> }
> 

#### Environment:
**@nguniversal versions**
    "@nguniversal/express-engine": "^8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
```
<!--
Output from: `ng --version`.
Angular CLI: 8.0.6
Node: 12.3.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.800.6
@angular-devkit/core         8.0.6
@angular-devkit/schematics   8.0.6
@schematics/angular          8.0.6
@schematics/update           0.800.6
rxjs                         6.4.0
-->
```

**Comment by Temkit** [comment]
> npm install --save-dev blob-polyfill

**in server.ts :** 

```
import { Blob } from "blob-polyfill";
....
global['Blob'] = Blob
```

**Comment by vikerman** [comment]
@Temkit - I'm guessing adding the above solved your issue?
