### ISSUE TITLE
Set Ivy specific flags on startup

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1211]
Ensure Ivy specific flags are set in server entry point as part of the schematics.

The ones known so far

```
(global as any)['ngI18nClosureMode'] = true;
(global as any)['ngDevMode'] = false;
```

**Comment by alan-agius4** [comment]
These are already defined in webpack via the cli.

https://github.com/angular/angular-cli/blob/4aaec9c7467d0ec6f7db4b5345e86c2de4799891/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L318

https://github.com/angular/angular/blob/894c4b53904cdd62fe2a3c92ca9350709624ad99/packages/compiler-cli/src/tooling.ts#L19
