### ISSUE TITLE
Provide a way to specify externals in the server build

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1213]
Currently we set --bundleDependencies all in the default schematics.

This is causing issues in certain libraries that don't bundle well. See #1207, #1195 

The workaround is to go back to --bundleDependencies to 'none' and ship all of node_modules.

But it might be worthwhile to explore whether we can expose some mechanism to add certain imports as 'external' in the server builder config so that only those node_modules can be selectively shipped (Though that is up to the user to do that correctly)

**Comment by alan-agius4** [comment]
Address via https://github.com/angular/angular-cli/pull/16359
