### ISSUE TITLE
support for latest @hapi/hapi v18+

### ISSUE THREAD

**Issue by EMCP** [angular/universal#1215]
# Feature Request

#### What is the desired behavior?
Support HAPIJS SSR via the newly located `@hapi/hapi` npm package... `hapi` is deprecated
https://github.com/angular/universal/blob/master/modules/hapi-engine/package.json#L15

#### What is the use-case or motivation for the desired behavior?
`hapi` is deprecated

#### Is there anything else we should know?
you can add an alias to easily support the new location

https://twitter.com/hapijs/status/1120237590668386304

**Comment by EMCP** [comment]
I confirmed that the packages pulled in by `ng add @nguniversal/hapi-engine --clientProject MyProjectName` are all using the old v17 namespace.. and all should be bumped to use `@hapi/`

Is anyone possibly there to work on that or can I submit a possible PR ?

**Comment by CaerusKaru** [comment]
I've opened #1218, but it's blocked on Bazel issues for now. You can still upgrade, and use Hapi with the alias as mentioned.
