### ISSUE TITLE
build failed NgControlStatusGroup 

### ISSUE THREAD

**Issue by aayman997** [angular/universal#1219]
Angular forms 
 The issue is caused by package @angular/.... Forms

I am trying to build my app using angular universal but I keep getting error in Angular forms without knowing the cause of the issue

`ERROR in Illegal State: referring to a type without a variable {"filePath":"D:/Easy Schools/Yep/primary/yepfront/node_modules/@angular/forms/forms.d.ts","name":"NgControlStatusGroup","members":[]}`

### Is this a regression?

 No
 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre>ERROR in Illegal State: referring to a type without a variable {"filePath":"D:/Easy Schools/Yep/primary/yepfront/node_modules/@angular/forms/forms.d.ts","name":"NgControlStatusGroup","members":[]}<code>

</code></pre>

## 🌍  Your Environment

**Angular Version:** 
<pre>8<code>

</code>
Angular CLI: 8.1.3
Node: 12.5.0
OS: win32 x64
Angular: 8.1.3
... cdk, cli, common, compiler, compiler-cli, core
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.801.3
@angular-devkit/build-angular              0.801.3
@angular-devkit/build-optimizer            0.801.3
@angular-devkit/build-webpack              0.801.3
@angular-devkit/core                       7.3.9
@angular-devkit/schematics                 7.3.9
@angular/animations                        8.2.3
@angular/forms                             7.2.15
@angular/http                              7.2.15
@ngtools/webpack                           8.1.3
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        7.3.9
@schematics/update                         0.801.3
rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.35.2
</pre>

**Anything else relevant?**

**Comment by CaerusKaru** [comment]
We need a minimal reproduction repository in order to investigate this issue. Simply saying: "`@angular/forms` causes issues" is not enough.

**Comment by alan-agius4** [comment]
Closing as the author didn’t get back to us.

If you are sill experiencing the issue, please feel free to open a new bug report with a minimal reproduction.
