### ISSUE TITLE
Development environment almost unsable with cookies auth

### ISSUE THREAD

**Issue by Avcajaraville** [angular/universal#1223]
# Bug Report

#### What is the expected behavior?

I would run my `ng start` command along with `nodemon` and see autorefresh working properly.

#### What is the current behavior?

Right now, every time I make a change on the code, angular cli refreshes and I'm redirected to the login page, thus, every time I make a change on the code, I need to login again and navigate back to where I was.

#### What modules are related to this issue?
```
- "@angular/core": "^8.2.4"
- "@nguniversal/express-engine": "^8.1.1"
- "express": "^4.17.1"
```

#### Minimal reproduction with instructions:

Right now, the story goes like this:

Basic setup:
- I'm developing a fully SSR site with angular 8.
- My server returns data from endpoints, being the response either json or html, depends on the request.
- The endpoints are the same for both types of response (this is important, for the part I talk about proxy conf).
- Most of the endpoints are hidden, only accessible for logged in users. It uses the classic cookies based authorization. So we need to send the cookies on each request.

First thing I did was to set up a proxy conf file. Due to the fact that all my endpoints are the same, I can't create a rule like '/api/whatever'.

So I need to create something like:
```
{
  "/": {
    "target": "http://localhost:4000",
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  }
}
```
This is always returning me a nice `Failed to lookup view “index” in views directory`. The reason being that `ng serve`, along with the previous proxy.conf.json was calling my express server, and because I didn't have it compiled, there is no dist folder (PS: if I build, I get the same redirection, but this time, built files are used, and thus, I can't see my changes while developing).

My next though was to use a proxy and only proxyfying json request, something like:
```
const PROXY_CONFIG = {
  "/": {
    "target": "http://localhost:4000",
    "logLevel": "debug",
    "changeOrigin": true,
    "bypass": (req, res, proxyOptions) => {
      if (req.headers.accept.includes("html")) {
        return '/src/index.html';
      }
    }
  }
}

module.exports = PROXY_CONFIG;
```

This works more or less, as now I'm not getting any express error, html files are being serving straight from the specified file, and json are going through express. 

But each time I make a change, I need to login again and navigate to where I was.

This definitly have to do with the way I do authentication on my app, which is via an auth guard that uses transfer state, something like:
```
if (isPlatformServer(this.platform) && this.response.locals.user) {
  this.transferState.set(key, this.response.locals.user);
  this.user.setUser(this.response.locals.user);
}
const user = this.transferState.get<ClientUser>(key, null);
if (user) {
  this.user.setUser(user);
}
```

With my proxy conf approach, none of the ifs are fulfilled and Im always logged out.

Would love to find a approach that enables me to develop quickly.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
