### ISSUE TITLE
Angular : share on social media with @ngx-share

### ISSUE THREAD

**Issue by CheickD** [angular/universal#1235]
# Bug Report
I use the plugin @ngx-share to sahre (webpages) on social media (Twitter, Linkedin & Facebook).
Twitter use the information I give but not Facebook & Linkedin
#### What is the expected behavior?
I want to share a webpage on Facebook/Linkedin/Twitter, with these informations : og:title and og:description.

#### What is the current behavior?
Twitter share the webpage with only the og:description but doesn't share the og:title...
Facebook & Linkedin share the webpage but use the title and the description of the index.html file.

#### What modules are related to this issue?
```
- [ ] @ngx-share
```

#### Environment:
**@nguniversal versions 7**
  - @ngx-share:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?

**Comment by CheickD** [comment]
`<ul *ngIf="univers === 'org'">
    <li *ngIf="toggleShareOrg" [class]="'reseaux facebook c-' + univers"><button shareButton="facebook" [url]="pageUrl" [title]="pageTitle" [description]="pageDescription">facebook</button></li>
    <li *ngIf="toggleShareOrg" [class]="'reseaux twitter c-' + univers"> <button shareButton="twitter" [url]="pageUrl" [title]="pageTitle" [description]="pageDescription">twitter</button></li>
    <li *ngIf="toggleShareOrg" [class]="'reseaux linkedin c-' + univers"> <button shareButton="linkedin" [url]="pageUrl" [title]="pageTitle" [description]="pageDescription">linkedin</button>
    </li>
  </ul>`

**Comment by CaerusKaru** [comment]
This likely isn't an issue with Angular Universal. A better avenue for support on this would be StackOverflow or Gitter.
