### ISSUE TITLE
ngx-socket.io in Angular Universal

### ISSUE THREAD

**Issue by SushmaThalapaneni** [angular/universal#1236]
Hi,

I have a requirement to use sockets in my project. So, I used ngx-socket.io npm library in my project. But when I use ngx-socket.io in my home page. Am unable to load home page and its throwing 504 gateway error.

**Note:** Without sockets am able to load my root page.

Can anyone please help on this ?

**Comment by The-Noah** [comment]
I have the same issue. Sorry for not being any help but if I figure it out I will make sure to share it.

**Comment by CaerusKaru** [comment]
Can you look at this thread on using socket.io and see if it helps you? https://github.com/angular/universal/issues/846

**Comment by SushmaThalapaneni** [comment]
I have removed ngx-socket.io library and installed "**socket.io-client**" plugin and wrapped the connection and events related code inside platform browser as below. 

import { isPlatformBrowser } from '@angular/common';
import { Inject, PLATFORM_ID } from '@angular/core';

constructor(@Inject(PLATFORM_ID) private platformId: Object) {
  if(isPlatformBrowser(this.platformId)) { // check if this is runing in browser
    this.socket = io('http://localhost:3000/'); // call io constructor
    this.init(); // do the all initilization, e.g. this.socket.on('message', msg => {})
  }
}

Now its working fine.

Thank you.
