### ISSUE TITLE
Server Side Rendering: Event is not defined

### ISSUE THREAD

**Issue by Rlcolli4** [angular/universal#1239]
# Bug Report
When I compile my server.js by running `npm run build:client-and-server-bundles && npm run webpack:server` and run my server with `node server.js` the server is unable to start and throws the following error: `

The node module I am using that causes the error has tried to address the issue in his own repo ([#42](https://github.com/vitalii-andriiovskyi/ngx-owl-carousel-o/issues/42)), his suggestion however did not fix my issue. 

#### What is the expected behavior?
In previous versions of Angular and Angular Universal we did not have an issue with the compiled server.js. It should be able to build with the installed node modules and run the server side rendering without issue.

#### What is the current behavior?
Using Angular 8 and @nguniversal/module-map-ngfactory-loader 8.1.1 building the server.js at run time causes the node server to crash and become unusable for server side rendering.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [X ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
1. Create an Angular 8 application
2. Install the following with npm using `--save`:
     - "@nguniversal/module-map-ngfactory-loader": "^8.1.1"
     - "ngx-owl-carousel": "^2.0.7"
     - "ngx-owl-carousel-o": "^2.0.1"
     - "ngx-pagination": "^3.2.1"
3. Run the following command `npm run build:client-and-server-bundles && npm run webpack:server`
4. Run `node dist/server.js`
5. Check the console for an error, you should see the stack trace for "Event is Not Defined"

#### What is the use-case or motivation for changing an existing behavior?
Upgrading from one version of Angular to another should not break existing behavior.

#### Environment:
```
**@nguniversal version**
  - module-map-ngfactory-loader:

Angular CLI: 8.2.0
Node: 12.4.0
OS: win32 x64
Angular: 8.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.802.0
@angular-devkit/build-angular              0.802.0
@angular-devkit/build-optimizer            0.802.0
@angular-devkit/build-webpack              0.802.0
@angular-devkit/core                       8.2.0
@angular-devkit/schematics                 8.2.0
@angular/cdk                               8.1.2
@angular/material                          8.1.2
@ngtools/webpack                           8.2.0
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.2.0
@schematics/update                         0.802.0
rxjs                                       6.5.2
typescript                                 3.5.3
webpack                                    4.38.0
```

#### Is there anything else we should know?
We compile the server.js at build time and it is deployed out with the production code, modifying the file post build is not preferred and in some cases not possible as its not always a developer pushing out the build.

**Comment by CaerusKaru** [comment]
You'll need to polyfill `Event`, it's a browser-only global, so unavailable on the server (NodeJS doesn't have a DOM for DOM Events)
