### ISSUE TITLE
pages not server-side rendered - `<app-root></app-root>` still not compiled

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/universal#1243]
After setting the universal configuration, fix all compilation bugs related to DOM/BOM objects, the server-side rendering for the pages doesn't working properly

**package.json**

    "@angular/core": "^7.2.9",
    "@angular/platform-browser": "^7.2.9",
    "@angular/platform-browser-dynamic": "^7.2.9",
    "@angular/platform-server": "^7.2.8",
    "@nguniversal/common": "^8.1.1",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "7.1.1",

**app.module.ts**

    imports : [
        BrowserModule.withServerTransition({ appId: 'serverApp' }),
        BrowserTransferStateModule,
        ...
      ]
**server.ts**
 
    ...
    app.engine('html', (_, options, callback) => {
      const engine = ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [
          provideModuleMap(LAZY_MODULE_MAP),
          {provide: 'host', useFactory: () => options.req.get('host'), deps: []}
        ]
      });
      engine(_, options, callback);
    });
    
    app.set('view engine', 'html');
    app.set('views', join(DIST_FOLDER, 'browser'));
    
    // Serve static files from /browser
    app.get('*.*', express.static(join(DIST_FOLDER, 'browser'), {
      maxAge: '1y'
    }));
    
    // All regular routes use the Universal engine
    // app.get('*', (req, res) => {
    //   res.render('index', {req});
    // });
    
    app.get('*', (req, res) => { res.sendFile( join(DIST_FOLDER, 'browser' , 'index.html'), {req}); });
    
**tsconfig.server.json**

   ```
 {
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "commonjs",
    "types": ["node"],
    "typeRoots": ["../node_modules/@types"]
  },
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ],
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}

```

**angular.json**

   ```
  ....
   "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
      ....
```

**package.json**

   ```
 "scripts": {
   ...
   "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run ngx-bbn-zvendo:server:production",
    "ssr-only": "ng run ngx-bbn-zvendo:server:production && npm run compile:server && node dist/server"
   ....
}
```
What's wrong in my project?

**Comment by kovaletsyurii** [comment]
Can you please show server.tsconfig.json, angular.json and package json scripts for running ssr too?

**Comment by waseem-isaac-BBN** [comment]
> Can you please show server.tsconfig.json, angular.json and package json scripts for running ssr too?

I updated the issue body @kovaletsyurii

**Comment by vikerman** [comment]
Is it possible to create a small repro github repo? (Maybe remove all logic except for a small AppModule+AppComponent)

**Comment by waseem-isaac-BBN** [comment]
related to https://github.com/angular/universal/issues/1305
