### ISSUE TITLE
ERROR TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by waseem-isaac-BBN** [angular/universal#1251]
`ERROR TypeError: Cannot convert undefined or null to object`
    at Function.keys (<anonymous>)
    at new ConfService (....\dist\server.js:155899:89)
    at _createClass (....\dist\server.js:24259:20)
    at _createProviderInstance (...\dist\server.js:24220:26)
    at resolveNgModuleDep (....\dist\server.js:24184:21)
    at NgModuleRef_.get (....\dist\server.js:24893:16)
    at resolveDep (.....\server.js:25264:45)
    at createClass (....\dist\server.js:25144:32)
    at createDirectiveInstance (....\dist\server.js:25015:20)
    at createViewNodes (....\server.js:26241:36)

...
**package.json**

    "@angular/core": "^7.2.7",
    "@angular/platform-server": "^7.2.7",
    "@angular/pwa": "^0.12.4",
    "@angular/service-worker": "^7.2.7",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.1",

**server.ts**
 
    ...
    app.engine('html', (_, options, callback) => {
      const engine = ngExpressEngine({
        bootstrap: AppServerModuleNgFactory,
        providers: [
          provideModuleMap(LAZY_MODULE_MAP),
          {provide: 'host', useFactory: () => options.req.get('host'), deps: []}
        ]
      });
      engine(_, options, callback);
    });
    
    app.set('view engine', 'html');
    app.set('views', join(DIST_FOLDER, 'browser'));
    
    // Serve static files from /browser
    app.get('*.*', express.static(join(DIST_FOLDER, 'browser'), {
      maxAge: '1y'
    }));
    
    // All regular routes use the Universal engine
    // app.get('*', (req, res) => {
    //   res.render('index', {req});
    // });
    
    app.get('*', (req, res) => { res.sendFile( join(DIST_FOLDER, 'browser' , 'index.html'), {req}); });
    
**tsconfig.server.json**

   ```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app-server",
    "baseUrl": "."
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
}


```

**angular.json**

   ```
  ....
   "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }
      ....
```

**package.json**

   ```
 "scripts": {
   ...
  "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node dist/server",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run new-project-x:server:production",
    "ssr-only": "ng run new-project-x:server:production && npm run compile:server && node dist/server"
   ....
}
```
What's wrong in my project?

**Comment by vikerman** [comment]
This seems like a bug in your code since ConfService is at the top of stack. Please re-open if you found a more specific issue with SSR. Thanks!

**Comment by waseem-isaac-BBN** [comment]
`Undefined injector` Yes I found it ,  
but still don't know why it is undefined :))
