### ISSUE TITLE
(docs): angular universal prerender

### ISSUE THREAD

**Issue by kuncevic** [angular/universal#1254]
Hi guys, I just noticed that https://github.com/angular/universal-starter become obsolete now so https://angular.io/guide/universal is the source of truth on the subject. 

However the docs does not tell how to approach prerender strategy - any ideas on that?

UPDATE:
Just noticed https://github.com/angular/universal/issues/1201 and https://github.com/angular/universal/pull/1206 still work in progress.

**Comment by vikerman** [comment]
Yes. We are working on this and will be updating the guide for 9.0. Thanks.
