### ISSUE TITLE
TypeError: observer.disconnect is not a function

### ISSUE THREAD

**Issue by kovaletsyurii** [angular/universal#1255]
I have angular universal application, which use angular/material

When server render page without material components(like mat-tabs, mat-checkbox ) - all works fine. When page contains material components - I got the next console error:

errors:
[ TypeError: observer.disconnect is not a function]
  message:
   '1 errors occurred during unsubscription:\n1) TypeError: observer.disconnect is not a function',
  name: 'UnsubscriptionError',
  errors:
   [ TypeError: observer.disconnect is not a function
         at ContentObserver._cleanupObserver (/Users/user/.../node_modules/@angular/cdk/bundles/cdk-observers.umd.js:167:26)

**Comment by kovaletsyurii** [comment]
To fix this a am added the next hardcode to my server.ts
```
global['MutationObserver'] = function () {
  return {
    observe: () => {},
    disconnect: () => {}
  }
};
```

**Comment by vikerman** [comment]
This sounds like a bug in Angular material - But they have some basic test to ensure tabs work with SSR. Is it possible to create a repro? (And I'll file the relevant bug in the Material repo). Thanks!

**Comment by alan-agius4** [comment]
Closing as the author didn’t get back to us.

If you are sill experiencing the issue, please feel free to open a new bug report with a minimal reproduction.
