### ISSUE TITLE
fix: problems with cjs sourcemaps in npm dist

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#127]
There seems to be a problem with the sourcemaps which can cause confusing when using the node-inspector. When an error shows up in the terminal the files referenced for js built files and in the console when using node-inspector they throw an error when not correctly filing the ts files  

related https://github.com/angular/angular/issues/4701

**Comment by jeffbcross** [comment]
There's been some recent work to fix sourcemaps in angular in the alpha 47 release, but I'm not sure if it fixed this particular issue. Can you see if you can still reproduce?

**Comment by gdi2290** [comment]
sourcemaps are fixed
