### ISSUE TITLE
DOM interfaces which are placed in decorated classes/functions/properties broke a build

### ISSUE THREAD

**Issue by constantant** [angular/universal#1277]
# Bug Report

#### What is the expected behavior?
Even using DOM interfaces in decorated classes/functions/properties, SSR must work without hacks in `server.ts` like
```
global['Document'] = null;
global['HTMLElement'] = null;
global['MouseEvent'] = null;
global['DragEvent'] = null;
global['KeyboardEvent'] = null;
global['File'] = null;
```

#### What is the current behavior?
In case using a DOM interface, e.g
```
@HostListener('mouseup', [ '$event.target' ])
onMouseup(target: HTMLElement) {...}
```
SSR fails with an error, e.g
```
/somewhere/dist/server/main.js:124530
    Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:paramtypes", [HTMLElement]),
                                                                                   ^

ReferenceError: HTMLElement is not defined
 ...
```

#### Minimal reproduction with instructions:
Decorate anything which has DOM interface metadata.
```
@HostListener('mouseup', [ '$event.target' ])
onMouseup(target: HTMLElement) {...}
```
```
constructor(@Inject(DOCUMENT) private readonly _doc: Document, ...)
```

#### Environment:
Angular 8

**Comment by alan-agius4** [comment]
Hi, you should be able to solve this by removing `emitDecoratorMetadata` from your tsconfig.

Since Angular-CLI 8 this shouldn’t be needed.

**Comment by constantant** [comment]
Hi @alan-agius4,
How should I apply this `emitDecoratorMetadata`?
I tried `true` and `false` but the result is the same -- en error

My `tsconfig.json`
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "module": "esnext",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types",
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}

```

**Comment by alan-agius4** [comment]
The value should be `false`, also make sure that you are not setting this in a child tsconfig.

**Comment by CaerusKaru** [comment]
Since Angular v8, this should no longer be an issue, closing.
