### ISSUE TITLE
TypeError global hadle. 

### ISSUE THREAD

**Issue by kovaletsyurii** [angular/universal#1279]
When somewhere in my application occur an TypeError, my angular universal application has been crash. For example when api request respond with 404 status or when api server is down. 
Can i catch this errors globally, or I only can catch them manually using try .. catch construction? 

For example - redirect to another route without application crashing?

**Comment by CaerusKaru** [comment]
Hello, this is not an issue with Angular Universal. For support requests, please use Gitter or StackOverflow.
