### ISSUE TITLE
docs: add guides for node profiling and debugging

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#128]
This is more of a problem with Node.js than it is an Angular problem. We need to either direct people places where they can learn about profiling their node app or create a guide for it. I'm assuming this may also be a problem with WebWorkers

**Comment by gdi2290** [comment]
We might be able to leverage n|sold from NodeSource (cc @dshaw) for better profiling of node/debugging applications. They also have a node installer we may also want to consider directing people to their installer for most users who are just starting out with node.js for universal

**Comment by manekinekko** [comment]
We can also suggest using VCode, which has a straightforward debugger for node.
![image](https://cloud.githubusercontent.com/assets/1699357/12404310/9f865fa4-be3a-11e5-96f7-4464d13b2697.png)

**Comment by gdi2290** [comment]
VCode is a good idea and it also has great typescript support

**Comment by jeffwhelpley** [comment]
Folding this into #258
