### ISSUE TITLE
server.ts is part of the TypeScript compilation but it's unused

### ISSUE THREAD

**Issue by magnattic** [angular/universal#1282]
# Bug Report

#### What is the expected behavior?
Angular Universal (express-engine) works with Angular 9 and ivy.

#### What is the current behavior?
When I create a brand new project with Angular 9.0.0-next.9 and add universal to it, I get the following error on `npm run build:ssr:
> WARNING in /home/xyz/code/ng9-uni/server.ts is part of the TypeScript compilation but it's unused.
Add only entry points to the 'files' or 'include' properties in your tsconfig.

Running `npm run serve:ssr` outputs:
> ng9-uni@0.0.0 serve:ssr /home/xyz/code/ng9-uni
> node dist/ng9-uni/server/main.js

and then just stops

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
> npm i -g @angular/cli@next

> ng new ng9-uni && cd ng9-uni
> ng add @nguniversal/express-engine@next --clientProject ng9 uni
> npm run build:ssr
> npm run serve:ssr

#### Environment:
**@nguniversal versions**
  - common: 9.0.0-next.3
  - express-engine: 9.0.0-next.3
```
Angular CLI: 9.0.0-next.9
Node: 11.14.0
OS: linux x64
Angular: 9.0.0-next.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.9
@angular-devkit/build-angular     0.900.0-next.9
@angular-devkit/build-optimizer   0.900.0-next.9
@angular-devkit/build-webpack     0.900.0-next.9
@angular-devkit/core              9.0.0-next.9
@angular-devkit/schematics        9.0.0-next.9
@angular/cli                      9.0.0-next.9
@ngtools/webpack                  9.0.0-next.9
@nguniversal/common               9.0.0-next.3
@nguniversal/express-engine       9.0.0-next.3
@schematics/angular               9.0.0-next.9
@schematics/update                0.900.0-next.9
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.41.0

```

#### Is there anything else we should know?

**Comment by alan-agius4** [comment]
Can you try to add the universal via `ng add @nguniversal/express-engine@9.0.0-next.5` instead pls?

**Comment by magnattic** [comment]
That seems to work, thank you!
