### ISSUE TITLE
.net core - cookie appending not working

### ISSUE THREAD

**Issue by BayanAbuawadCL** [angular/universal#1284]
# Bug Report
can't append cookie to the browser via SSR, 
when I run my client on port 4200 (no SSR) it works perfectly.

#### What is the expected behavior?
HttpContext.Response.Cookies.Append("key", "value");
should append cookie to the browser.

#### What is the current behavior?
HttpContext.Response.Cookies.Append("key", "value");
does not append cookie to the browser.

Angular CLI: 8.1.1
Node: 10.16.0
OS: win32 x64
Angular: 8.1.1

rxjs                                       6.4.0
typescript                                 3.4.5
webpack                                    4.35.2

.net core 2.2

**Comment by asad-naeem** [comment]
I was facing the same issue but I noticed that the code was perfectly fine but it was not working even. So I swapped the code lines like that
Startup.cs
`  public void ConfigureServices(IServiceCollection services)
        {
            services.AddControllersWithViews();
            services.AddScoped<ILoggerManager>(_ => new LoggerManager("UI DI Registration"));

            services.AddDistributedMemoryCache(); // Adds a default in-memory implementation of IDistributedCache
            services.AddSession();

            services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme).AddCookie();
            services.AddSingleton<IHttpContextAccessor, HttpContextAccessor>();            
        }`
` public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseExceptionHandler("/Home/Error");
            }

            app.UseSession();

            app.UseStaticFiles();

            app.UseRouting();
            app.UseCookiePolicy();

            app.UseAuthentication();
            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllerRoute(
                    name: "default",
                    pattern: "{controller=Home}/{action=Index}/{id?}");
            });  
        }`
-------------------------------------------------
Adding a static file for cookie management
public static class CookieExtenion
    {
        public static string Get(this IHttpContextAccessor _httpContextAccessor, string _key)
        {
            return _httpContextAccessor.HttpContext.Request.Cookies[_key];
        }

        /// <summary>  
        /// set the cookie  
        /// </summary>  
        /// <param name="key">key (unique indentifier)</param>  
        /// <param name="value">value to store in cookie object</param>  
        /// <param name="expireTime">expiration time</param>  
        public static void Set(this IHttpContextAccessor _httpContextAccessor, string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();
            if (expireTime.HasValue)
                option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            else
                option.Expires = DateTime.Now.AddMilliseconds(10);

            _httpContextAccessor.HttpContext.Response.Cookies.Append(key, value, option);
        }
        /// <summary>  
        /// Delete the key  
        /// </summary>  
        /// <param name="key">Key</param>  
        public static void Remove(this IHttpContextAccessor _httpContextAccessor, string key)
        {
            _httpContextAccessor.HttpContext.Response.Cookies.Delete(key);
        }
    }
-------------------------------------------------------------------------------------
HomeController
                {
                    string key = "UserDTO";
                    // Get Cookie
                    var cookieresult = _httpContextAccessor.Get(key);
                    // Set Cookie            
                   _httpContextAccessor.Set(key, "Test Value", 10);   
                }

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
