### ISSUE TITLE
consider pure di option 

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#129]
it would be great if the developer could mark services/components/etc as stateless so that the di doesn't have to recreate the instance on each request/response cycle.
```typescript
@Injectable({ pure: true })
class StatelessService {

}
```

at the same time it might be interesting to specify the default configuration for the service rather than the angular compiler setting the default to `useClass` (too bad classes don't hoist)

```typescript
@Injectable({
  pure: true,
  useFactory: () => new StatelessService(),
  deps: []
})
class StatelessService {

}
```

**Comment by jeffbcross** [comment]
Closing so @gdi2290 can open this on angular/angular
