### ISSUE TITLE
Refactor preboot build system to use webpack

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#13]
currently uses browserify but we should switch to webpack

**Comment by gdi2290** [comment]
webpack needs to be introduced first before switching preboot to it

**Comment by gdi2290** [comment]
Jeff mentioned he can take this one

**Comment by jeffwhelpley** [comment]
Changed this to medium effort because I haven't used webpack before and the preboot setup is non-trival. I do not plan on working on this until after Angular Connect, so if anyone else has time before then, feel free to take this over.

**Comment by gdi2290** [comment]
yeah don't worry about this

**Comment by gdi2290** [comment]
I'll close this for now
