### ISSUE TITLE
perf(bootstrap): create application prior to req/res lifecycle on server

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#130]
To reduce the work that needs to be done in the context of each request, a design should be considered where an application may be partially bootstrapped. Only platform injectors should be bootstrapped.

**Comment by jeffwhelpley** [comment]
@gdi2290 I forget. Did you already implement this or is there still room for improvement with the platform bootstrap?

**Comment by gdi2290** [comment]
yeah this was done in a core refactor for bootstrap
