### ISSUE TITLE
Deploying Angular Universal App to Google Cloud App Engine gives 500 Server Error

### ISSUE THREAD

**Issue by francdore** [angular/universal#1308]
# Bug Report

#### What is the expected behavior?
I just want to see the first component loaded which is lazy loaded.

#### What is the current behavior?
Currently when I run my app on App Engine, I get a 500 Server error and when I check the error login using gcloud app logs tail -s default, I get the following errors:

`Error: Failed to lookup view "index" in views directory "/srv/dist/browser"      at Function.render (/srv/server.js:12387:17)`

`Error: Cannot find module './server/main'      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)`

So there must be something wrong in my Angular app.

#### What modules are related to this issue?
```
- [ ] express-engine
```

#### Minimal reproduction with instructions:
I created a brand new Angular 8 App. I added Angular Universal using ng add @nguniversal/express-engine --clientProject APPNAME

Then I ran npm run build:ssr which puts the project files in the dist folder in this structure:

```
dist
    browser
        All the normal Angular app files like index.html etc
    server
        main.js
    server.js
    app.yaml - Added by my
    package.json - Added my me
```

Then I added app.yaml containing: runtime: nodejs10
I also added a package.json file containing:
```
{
    "main": "server.js",
    "scripts": {
        "start": "node server.js"
    }
}
```

Then I log into my app on the Google Cloud Platform, and open Cloud Shell in my browser. I then click the pencil/edit icon which opens the default file explorer on the Google Cloud Account. I upload all the files there that's under the dist folder, but I move server.js outside of the dist folder.

Folder structure that I'm uploading.

```
dist
    browser
        All the normal Angular app files like index.html etc
    server
        main.js
server.js
app.yaml
package.json
```

Then I run gcloud app deploy which runs fine without errors and uploads the files to my project cloud bucket.

When I visit my app > app-name.appspot.com, I get a 500 server error and the error logs gives the above errors.

#### Environment:
**@nguniversal versions**
"@angular/common": "~8.2.11",
"@nguniversal/express-engine": "^8.1.1",
"@nguniversal/module-map-ngfactory-loader": "8.1.1",

```
Angular CLI: 8.3.13
Node: 10.16.3
OS: win32 x64
Angular: 8.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.13
@angular-devkit/build-angular              0.803.13
@angular-devkit/build-optimizer            0.803.13
@angular-devkit/build-webpack              0.803.13
@angular-devkit/core                       8.3.13
@angular-devkit/schematics                 8.3.13
@angular/cli                               8.3.13
@ngtools/webpack                           8.3.13
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.13
@schematics/update                         0.803.13
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
```

**Comment by alan-agius4** [comment]
Seeing the above structure, you might need to change the dist folder variable in your `server.ts` file. Removing `dist/` from it should be enough.

**Comment by alan-agius4** [comment]
Hi, are you still experiencing the issue? If so, can you kindly provide a minimal reproduction? 

Thanks.

**Comment by alan-agius4** [comment]
Closing as the author didn’t get back to us.

If you are sill experiencing the issue, please feel free to open a new bug report with a minimal reproduction.
