### ISSUE TITLE
refactor(middleware): create generic middleware without using Express views

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#131]
This would allow developers to use the middleware with other backend frameworks without being tied to Express.

**Comment by jeffwhelpley** [comment]
Closing as we have now separated out Express dependency to a angular2-express-engine. The core library (soon to be renamed from universal to angular2-unversal) does import angular2-express-engine as well as angular2-hapi-engine but that is just for convenience for users so they can access the different engines from one import. The core lib works without any server framework dep.
