### ISSUE TITLE
NavigationEnd not triggered when cached response used in TransferHttpCacheModule

### ISSUE THREAD

**Issue by dottodot** [angular/universal#1311]
# Bug Report

#### What is the expected behavior?
For NavigationEnd to work as normal

#### What is the current behavior?
If I remove `TransferHttpCacheModule`  from my app `NavigationEnd` is always triggered on my routes however when `TransferHttpCacheModule` is enabled the first time I visit the route and data is fetched via http `NavigationEnd` is triggered but on the second visit when the response is fetched from the cache `NavigationEnd` is not triggered.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
```
Angular CLI: 8.3.14
Node: 10.17.0
OS: darwin x64
Angular: 8.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.14
@angular-devkit/build-angular              0.803.14
@angular-devkit/build-optimizer            0.803.14
@angular-devkit/build-webpack              0.803.14
@angular-devkit/core                       8.3.14
@angular-devkit/schematics                 8.3.14
@angular/cdk                               8.2.3
@angular/cli                               8.3.14
@angular/flex-layout                       8.0.0-beta.27
@angular/material                          8.2.3
@angular/material-moment-adapter           8.2.3
@angular/pwa                               0.801.3
@ngtools/webpack                           8.3.14
@nguniversal/common                        8.1.1
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.1.3
@schematics/update                         0.803.14
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2
```

#### Is there anything else we should know?

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
