### ISSUE TITLE
perf(benchmarks): create benchmark comparing rendering on server and client

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#135]
The goal is to determine differences in user-perceived render time, which can be referenced against common device and network capabilities to determine how the two approaches (pre-or-post-render) compare under different conditions.

There should be benchmarks of applications with different UI and data characteristics, comparing rendering just in the UI, and pre-rendering from the server. Over time, as more optimizations are available (such as inlining data and assets, service worker integration, etc), benchmarks should compare against optimized and unoptimized approaches as well.

Benchpress may be the best tool, but may need some features to support this.

The first benchmark could be based on the [angular/universal-starter](https://github.com/angular/universal-starter) app.
- [ ] Total req/res time to pre-render page and load all assets
- [ ] Total time to load and render page in client without pre-rendering, including load time

Ideally, test with these variables, using mobile emulation features in chrome devtools:
- [ ] Simulated connection quality
- [ ] Simulated hardware

TODO: 
- Determine how to analyze and report on data, to segment by device processing power and network latency/throughput.
- Determine whether benchpress is the best tool, and if so, what modifications need to be made.

**Comment by jeffwhelpley** [comment]
Should we merge #133 and #135?

**Comment by gdi2290** [comment]
@alexpods can you also get benchpress setup for the repo

**Comment by jhades** [comment]
Hi all, I'm testing an universal app  (angular 2 RC1 and universal 0.100.1) and i'm getting time to first byte TTFB from one to two seconds. The REST calls made for that view amount to 600ms.

I was trying to profile it (no conclusions so far) and noticed that the debug info shows up a lot even in an application running in production mode:

![screen shot 2016-05-18 at 10 34 53 pm](https://cloud.githubusercontent.com/assets/5454709/15374094/f8c61452-1d48-11e6-8fc1-5ed6d16a73f2.png)

This seems related to core https://github.com/angular/angular/issues/8508 It seems that debug info is still there even in production mode? Hard to say if this could have a high impact on the rendering times.

**Comment by jeffwhelpley** [comment]
Good find. I suspect, though, that this won't be a huge change. The much bigger win should be with the offline template compilation. Also, note that we have not done any performance optimization yet since we were waiting for OLTP to land first. My goal is to get TTFB down well under a second before we declare Angular Universal is production ready.

**Comment by gdi2290** [comment]
I think there was an issue in core saying thatprod mode isn't working
