### ISSUE TITLE
Cannot match any routes

### ISSUE THREAD

**Issue by pmknk** [angular/universal#1352]
Hello.
After running the application, i get an error:
Cannot match any routes. URL Segment: 'favicon.ico'
Cannot match any routes. URL Segment: 'main-es2015.46f062672db1d7f802c7.js',
Error: Cannot match any routes. URL Segment: 'styles.fa6bbdadea760fd840c0.css'
and much more.

I guess that engine can't find resources from index.html.

Can anybody help me?

**Comment by pmknk** [comment]
![1](https://user-images.githubusercontent.com/32387573/70058379-d994dc00-15ef-11ea-9b91-13b4f514635e.png)

**Comment by alan-agius4** [comment]
You might have the incorrect path provided to `express.static`. Check that the path points to the current folder on disk.

**Comment by pmknk** [comment]
@alan-agius4 
this is the express.static

![image](https://user-images.githubusercontent.com/32387573/70067130-dead5780-15fe-11ea-9a82-e6dfda3060b2.png)
![image](https://user-images.githubusercontent.com/32387573/70067144-e5d46580-15fe-11ea-8a80-907c000f8da7.png)

**Comment by alan-agius4** [comment]
Can you kindly provide a reproduction of the steps needed to replicate this?

**Comment by pmknk** [comment]
fixed by changing position of routes.
express.static should be before res.render index
