### ISSUE TITLE
serve-ssr builder always says "Compiled successfully" even on error

### ISSUE THREAD

**Issue by vikerman** [angular/universal#1372]
# Bug Report

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
ng new univ
cd univ
ng add @nguniversal/express-engine@next

ng run univ:serv-ssr
< Compilation succeeds >
< Make an error >
< Console shows an error but still prints "Compiled successfully" >

**Comment by alan-agius4** [comment]
I think this is expected as during watch we use the forked type checker which doesn’t emit a compilation error to block webpack.

Will double check

**Comment by alan-agius4** [comment]
Closing as this is working as expected.
