### ISSUE TITLE
withServerTransition({ appId: 'demo.in' }) conflicts ViewEncapsulation.Emulated behaviour

### ISSUE THREAD

**Issue by yaseen-nadaf** [angular/universal#1380]
# Bug Report

#### What is the expected behavior?
ViewEncapsulation.Emulated works fine if we have appId some normal word or name for example appName.

#### What is the current behavior?
If we have it as appName.com or appName.in then styles of respective components are not getting applied as they should (because of ViewEncapsulation.Emulated).

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
In app.module.ts file, inside imports array, write in the fashion given:
BrowserModule.withServerTransition({ appId: 'appName.in' })

#### What is the use-case or motivation for changing an existing behavior?
So that we can include the domain name as appId.

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common: ~8.2.14
  - express-engine: ^8.1.1
  - hapi-engine: 
  - module-map-ngfactory-loader: 8.1.1
```
Angular CLI: 8.3.20
Node: 10.16.0
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.20
@angular-devkit/build-angular              0.803.20
@angular-devkit/build-optimizer            0.803.20
@angular-devkit/build-webpack              0.803.20
@angular-devkit/core                       8.3.20
@angular-devkit/schematics                 8.3.20
@angular/cdk                               8.2.3
@angular/cli                               8.3.20
@angular/flex-layout                       8.0.0-beta.27
@angular/material                          8.2.3
@angular/material-moment-adapter           8.2.3
@ngtools/webpack                           8.3.20
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.20
@schematics/update                         0.803.20
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
```

#### Is there anything else we should know?
No

**Comment by vikerman** [comment]
This is not supported. Can you use `demo_in` instead ?

**Comment by yaseen-nadaf** [comment]
Is underscore supported?


*Thanks & Regards*
Yaseen Nadaf
Mob: +919916917329
Mail: yaseen.nadaf.0786@gmail.com

**Comment by vikerman** [comment]
The appid is used as prefix to CSS names for ViewEncapsulation.Emulated as described in https://angular.io/api/core/APP_ID . So underscore should work and period doesn't work.

**Comment by yaseen-nadaf** [comment]
Yup, it's working, thanks for reference and response.


*Thanks & Regards*
Yaseen Nadaf
Mob: +919916917329
Mail: yaseen.nadaf.0786@gmail.com
