### ISSUE TITLE
Build failure even after using isPlatformBrowser

### ISSUE THREAD

**Issue by maddy2894** [angular/universal#1386]
# Bug Report

#### What is the expected behavior?
The code inside isPlatformBrowser condition should not work during SSR.

#### What is the current behavior?
Build fails even though isPlatformBrowser is used.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
[1] Download finished sample code of "tour of heroes" from https://angular.io/guide/universal 
[2] npm install --save pouchdb-browser
[3] use this code in `app.component.ts`: 
`import {Component,Inject,PLATFORM_ID,} from '@angular/core';`
`import { isPlatformBrowser } from '@angular/common';`
`import PouchDB  from 'pouchdb-browser';`
`@Component({`
  `selector: 'app-root',`
  `templateUrl: './app.component.html',`
  `styleUrls: ['./app.component.css']`
`})`
`export class AppComponent {`
  `title = 'Tour of Heroes';`
  `testBrowser: any;`
  `constructor(@Inject(PLATFORM_ID) protected platformId) {`
   `if (isPlatformBrowser(this.platformId)) {`
      `this.testBrowser = new PouchDB('Hello');  //Should not work for SSR`
`    }`
`   }`
` }
`

#### What is the use-case or motivation for changing an existing behavior?
Using angular universal for SSR

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: NA
  - common: NA
  - express-engine: 8.2.6
  - hapi-engine: NA
  - module-map-ngfactory-loader: 8.2.6

Output from: `ng --version`:
<img width="513" alt="Screen Shot 2019-12-13 at 3 50 19 pm" src="https://user-images.githubusercontent.com/42700140/70770145-5d08b700-1dc0-11ea-9b81-78a2eb34248d.png">
 
macOS Catalina 10.15.2

#### Is there anything else we should know?
No.

**Comment by vikerman** [comment]
Hi - what is the error and where do you see it?

**Comment by maddy2894** [comment]
It throws:
`var f$1 = fetch;
          ^
ReferenceError: fetch is not defined`
 Which is caused by pouchDb and I tried placing it under isPlatformBrowser condition, but still, this error is thrown.

Image of the code: 
<img width="406" alt="Screen Shot 2019-12-13 at 8 33 53 pm" src="https://user-images.githubusercontent.com/42700140/70789852-f5fef880-1de7-11ea-9893-262477b8d55d.png">

**Comment by vikerman** [comment]
It looks like PouchDB code has a reference to fetch in it's top-level. So just the import is causing the failure.

At the very top of server.ts you can try adding

global['fetch'] = () => {};

So that that statement is parsed but the actual fetch will never get executed on the server

**Comment by maddy2894** [comment]
Using similar solution https://github.com/KillerCodeMonkey/ngx-quill/issues/91#issuecomment-565407124 solved the issue. Thank you
