### ISSUE TITLE
Error on adding Universal: "Invalid rule result instance of class promise"

### ISSUE THREAD

**Issue by g-hamilton** [angular/universal#1387]
# Bug Report

#### What is the expected behavior?
On this command:
`ng add @nguniversal/express-engine --clientProject black-dashboard-pro-angular`
I expect Universal installation to complete with no errors.

#### What is the current behavior?
The installation quits part way with the error message:
**Invalid rule result instance of class promise**

I'm stuck debugging this and any help would be much appreciated!

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

#### Is there anything else we should know?
My package.json:

```
{
  "name": "black-dashboard-pro-angular",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "install:clean": "rm -rf node_modules/ && rm -rf package-lock.json && npm install && npm start"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "8.2.9",
    "@angular/common": "8.2.9",
    "@angular/compiler": "8.2.9",
    "@angular/core": "8.2.9",
    "@angular/fire": "^5.2.1",
    "@angular/forms": "8.2.9",
    "@angular/platform-browser": "8.2.9",
    "@angular/platform-browser-dynamic": "8.2.9",
    "@angular/router": "8.2.9",
    "@fullcalendar/core": "4.3.1",
    "@fullcalendar/daygrid": "4.3.0",
    "@fullcalendar/interaction": "4.3.0",
    "@swimlane/ngx-datatable": "16.0.2",
    "@types/algoliasearch": "^3.34.5",
    "@types/mixpanel-browser": "^2.23.2",
    "algoliasearch": "^3.35.1",
    "angular2-multiselect-dropdown": "4.6.3",
    "bs-stepper": "1.7.0",
    "chart.js": "2.8.0",
    "core-js": "3.2.1",
    "country-flag-emoji": "^1.0.3",
    "d3-scale": "3.1.0",
    "devextreme": "19.1.6",
    "devextreme-angular": "19.1.6",
    "firebase": "^7.2.3",
    "fullcalendar": "3.10.1",
    "jw-bootstrap-switch-ng2": "2.0.5",
    "mixpanel-browser": "^2.30.1",
    "ngx-bootstrap": "5.1.2",
    "ngx-chips": "2.0.2",
    "ngx-toastr": "11.1.0",
    "nouislider": "14.0.2",
    "perfect-scrollbar": "1.4.0",
    "rxjs": "6.5.3",
    "stream": "0.0.2",
    "sweetalert2": "8.18.1",
    "tslib": "1.10.0",
    "zone.js": "0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.803.8",
    "@angular/cli": "8.3.8",
    "@angular/compiler-cli": "8.2.9",
    "@angular/language-service": "8.2.9",
    "@schematics/angular": "8.3.8",
    "@types/jasmine": "3.4.2",
    "@types/jasminewd2": "2.0.8",
    "@types/node": "12.7.11",
    "codelyzer": "5.1.2",
    "jasmine-core": "3.5.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "4.3.0",
    "karma-chrome-launcher": "3.1.0",
    "karma-coverage-istanbul-reporter": "2.1.0",
    "karma-jasmine": "2.0.1",
    "karma-jasmine-html-reporter": "1.4.2",
    "protractor": "5.4.2",
    "ts-node": "8.4.1",
    "tslint": "5.20.0",
    "typescript": "3.5.3"
  }
}

```

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng version`?

**Comment by g-hamilton** [comment]
Sure.

No output from ng --version.

Node version: v11.2.0

NPM version: 6.12.0

MacOS Mojave

**Comment by alan-agius4** [comment]
Hi,

1) Can you explain what do you mean no output from `ng --version`? -> Is an error thrown?
2) Can you run npm ls `@angular-devkit/schematics`?

Also it is important to point out that Node.js 11 has reached its end of life and is no longer supported by the Node.js team. Please consider updating to a supported version. Version 12 is recommended for optimal performance.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by moises291202** [comment]
I have the same error while ejecuting `ng add @nguniversal/express-engine --clientProject project-name`

 ng --version
Your global Angular CLI version (8.3.14) is greater than your local
version (7.0.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

Angular CLI: 7.0.7
Node: 10.16.0
OS: win32 x64
Angular: 7.0.4
... animations, common, compiler, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@angular/compiler-cli             7.2.15
@ngtools/webpack                  7.3.9
@schematics/angular               8.3.22
@schematics/update                0.10.7
rxjs                              6.5.4
typescript                        3.1.6
webpack                           4.29.0



**package.json**
{
  "name": "byte-pl",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.0.0",
    "@angular/common": "~7.0.0",
    "@angular/compiler": "~7.0.0",
    "@angular/core": "~7.0.0",
    "@angular/forms": "~7.0.0",
    "@angular/http": "~7.0.0",
    "@angular/platform-browser": "~7.0.0",
    "@angular/platform-browser-dynamic": "~7.0.0",
    "@angular/router": "~7.0.0",
    "@auth0/angular-jwt": "^2.1.2",
    "@larscom/ngrx-store-storagesync": "^5.7.7",
    "@ngrx/store": "^8.6.0",
    "@ngrx/store-devtools": "^8.6.0",
    "@nguniversal/express-engine": "^8.2.6",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.1",
    "@nguniversal/socket-engine": "^7.1.1",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/http-client": "^4.2.0",
    "@ngx-loading-bar/router": "^4.2.0",
    "@okta/okta-angular": "^1.3.0",
    "@schematics/angular": "^8.3.22",
    "json-object-mapper": "^1.6.0",
    "ng-push": "^0.2.2",
    "rxjs": "^6.5.3",
    "rxjs-compat": "^6.5.4",
    "stream": "0.0.2",
    "swiper": "^4.5.1",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.9",
    "@angular/cli": "~7.0.6",
    "@angular/compiler-cli": "^7.2.15",
    "@angular/language-service": "~7.0.0",
    "@types/core-js": "^2.5.2",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "^2.0.8",
    "@types/node": "^8.10.53",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "^2.1.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}
