### ISSUE TITLE
When exactly is application serialized on server?

### ISSUE THREAD

**Issue by flyingmutant** [angular/universal#139]
Let's say my page component does some HTTP API calls in constructor, and renders the responses after some light processing (so, the most common non-static page setup).

Will the API calls happen on client, on server, or on both? Do I have any control on when the server-side app is considered to be ready to be sent to the client?

**Comment by gdi2290** [comment]
we solved this, but it's not documented

**Comment by flyingmutant** [comment]
Can you please link to the source code?

**Comment by jeffwhelpley** [comment]
@flyingmutant You do not currently have control over this, but it is something that will be configurable in the future. For now, the server side runs through one tick:

https://github.com/angular/universal/blob/master/modules/universal/server/src/core/application_ref.ts#L253

This will cover the use case you mention where you are doing an HTTP call in the constructor of a component.

**Comment by flyingmutant** [comment]
Thanks! Will the call be repeated from the client? Or will constructors not run on the client?

**Comment by jeffwhelpley** [comment]
By default out of the box, the exact same code is run twice. Of course, while the client is bootstrapping and making the second round of http calls, the user is already looking at the server rendered view.

Part of the configurations I mentioned we are in the process of adding, however, would allow you to optimize this process in different ways including caching database calls so they don't have to be run again on the client.

Also, in case you are wondering, the default functionality includes a library called preboot that is included in the server rendered view. This tiny piece of inline JavaScript records all events that occur on the page while the client is bootstrapping and then plays it back to the client once it is ready. So, even though the application code is being run twice, the user shouldn't notice anything. They see the server rendered view immediately and can start interacting with the page right away.

**Comment by flyingmutant** [comment]
Thanks again.
