### ISSUE TITLE
Adding "include" on tsconfig.server.json breaks server build.

### ISSUE THREAD

**Issue by maddy2894** [angular/universal#1391]
# Bug Report

#### What is the expected behavior?
ng run {{projectname}}:server should succeed.

#### What is the current behavior?
Adding files under "include" on tsconfig.server.json breaks the build.
```JSON
tsconfig.server.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "src/app/app.server.module#AppServerModule"
  },
  "include": [
    "./server/**/*"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```
I am trying to add server files during build through tsconfig.server.json, but it fails the build. I tried adding the file to tsconfig.json and tsconfig.spec.json. 
```JSON
tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  },
  "include": [
    "./src/**/*",
    "./server/**/*.ts"
  ]
}
```

```JSON
tsconfig.spec.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "baseUrl": "./",
    "module": "commonjs",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts",
    "custom.d.ts",
    "./server/**/*"
  ]
}
```

**ERROR**
```
/main.server.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Environment:
**@nguniversal versions**
  - aspnetcore-engine: NA
  - common:NA
  - express-engine: 8.2.6
  - hapi-engine:
  - module-map-ngfactory-loader: 8.2.6

<img width="513" alt="Screen Shot 2019-12-13 at 3 50 19 pm" src="https://user-images.githubusercontent.com/42700140/70967817-96586400-20eb-11ea-9017-cbeb351a6933.png">

macOS Catalina

**Comment by alan-agius4** [comment]
Hi @maddy2894, what is happening here is by setting the `include` Un-referenced files which are not under the server are not being included in the compilation.

To fix this you would need to add `main.server.ts` as per of the compilation using `includes` or `files`.

More info: 
https://www.typescriptlang.org/docs/handbook/tsconfig-json.html

**Comment by maddy2894** [comment]
By server, you mean angular express server? I am using node server at the backend too

**Comment by alan-agius4** [comment]
I meant server folder

**Comment by maddy2894** [comment]
This is how my `main.server.ts` file looks like, 
```
import { enableProdMode } from '@angular/core';

import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

export { AppServerModule } from './app/app.server.module';
```
What do you suggest me to add?

**Comment by alan-agius4** [comment]
Try the below

```
tsconfig.server.json
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "src/app/app.server.module#AppServerModule"
  },
  "include": [
    "main.server.ts",
    "./server/**/*"
  ],
  "exclude": [
    "test.ts",
    "**/*.spec.ts"
  ]
}
```

**Comment by maddy2894** [comment]
Now I am getting a different error for a file I don't need to be included in the dist/server folder
```
image.blot.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' 
or 'include' property.
```
I do not need image.blot.ts to have complied, I tried writing it under "exclude" but that doesn't seem to work

**Comment by alan-agius4** [comment]
Hi @maddy2894, this looks like something related to your project structure and configuration and not caused by Angular. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
