### ISSUE TITLE
Can not add express-engine to fresh Angular 9 Project

### ISSUE THREAD

**Issue by Trojaner** [angular/universal#1413]
# Bug Report

#### What is the expected behavior?
It should add the express engine and angular universal

#### What is the current behavior?
An error occurs and nothing changes:
`Debug Failure. False expression: node_modules/@types/node/ts3.2/index.d.ts linked to nonexistent file XXXX/testapp/node_modules/@types/node/ts3.2/index.d.ts`
The file exists and is not empty:
```
// NOTE: These definitions support NodeJS and TypeScript 3.2.

// NOTE: TypeScript version-specific augmentations can be found in the following paths:
//          - ~/base.d.ts         - Shared definitions common to all TypeScript versions
//          - ~/index.d.ts        - Definitions specific to TypeScript 2.1
//          - ~/ts3.2/index.d.ts  - Definitions specific to TypeScript 3.2

// Reference required types from the default lib:
/// <reference lib="es2018" />
/// <reference lib="esnext.asynciterable" />
/// <reference lib="esnext.intl" />
/// <reference lib="esnext.bigint" />

// Base definitions for all NodeJS modules that are not specific to any version of TypeScript:
// tslint:disable-next-line:no-bad-reference
/// <reference path="../base.d.ts" />

// TypeScript 3.2-specific augmentations:
/// <reference path="fs.d.ts" />
/// <reference path="util.d.ts" />
/// <reference path="globals.d.ts" />
```

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [ ] builders
- [] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
```
ng new testapp [ I selected SCSS + RouterModule ]
cd testapp
ng add @nguniversal/express-engine@next --clientProject testapp
```

#### What is the use-case or motivation for changing an existing behavior?
Adding Angular Universal for a new Angular 9 Ivy based project

#### Environment:
**@nguniversal versions**
  - common: 9.0.0-rc.7
  - express-engine: @next (9.0.0-next.13)
```
Angular CLI: 9.0.0-rc.7
Node: 12.7.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.7
@angular-devkit/core         9.0.0-rc.7
@angular-devkit/schematics   9.0.0-rc.7
@schematics/angular          9.0.0-rc.7
@schematics/update           0.900.0-rc.7
rxjs                         6.5.3
```

**Comment by sudogroot** [comment]
I am having the same problem here

**Comment by Avcajaraville** [comment]
Same issue here. Same dependencies.

**Comment by alan-agius4** [comment]
Thanks for reporting this, I'll be taking a look tomorrow.

**Comment by Avcajaraville** [comment]
Thanks so much @alan-agius4, outstanding work! Really nice to face this issue and see it is fixed so quickly! Things like this makes me love our profession even more. Really appreciate it 🙌

**Comment by alan-agius4** [comment]
@Avcajaraville, glad to help and thanks a lot for your kind feedback 😊
