### ISSUE TITLE
Generating the files in the server folder based on some modules in Angular Universal

### ISSUE THREAD

**Issue by aroshanzamir** [angular/universal#1414]
I want to enable server side rendering on my Angular project(Angular 8) with Angular Universal. When I run the following command, It will create 2 folders in dist folder named server and browser and another file named server.js

`npm run build:ssr`
the generated files in the server folder are based on all modules, components, ... of the project.

How can I restrict Angular Universal to generate the files (in the server folder ) based on some modules for example only for the site.module ,because I don't need SEO on all pages.

**Comment by alishmki** [comment]
I have the same problem as you , and I do not know how to solve it

**Comment by captainjackrana** [comment]
Better to conditionally specify the routes in your `server.ts` file for which you want to serve the pre-rendered html.
And serve the basic index.html file for all other routes
