### ISSUE TITLE
fix templateUrl using node http

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#142]
templateUrl uses XHR service

**Comment by mcpDESIGNS** [comment]
@gdi2290 @jeffwhelpley Love what you guys are doing, great project/idea. I wasn't sure how to get in touch with you guys, but how could I join the team to start helping in contributing?

**Comment by jeffwhelpley** [comment]
@mcpDESIGNS We would love some help! @gdi2290 and I are cleaning up the open issues this week, so we will have some specific stuff you can work on by the end of the week and will let you know. Thanks for reaching out!

**Comment by mcpDESIGNS** [comment]
Great! Glad to help
I think making Angular 2 isomorphic is crucial, I'll contribute as much as I can !

Is there any documentation someplace I can read about how everything works & fits together so far?

**Comment by jeffwhelpley** [comment]
The best intro right now is to watch the two talks we gave recently:

https://www.youtube.com/watch?v=0wvZ7gakqV4
https://www.youtube.com/watch?v=MtoHFDfi8FM

You can also read our origin design doc (though it is not 100% up to date):

https://docs.google.com/document/d/1q6g9UlmEZDXgrkY88AJZ6MUrUxcnwhBGS0EXbVlYicY/edit

**Comment by mcpDESIGNS** [comment]
I was just reading through the docs, found you guys through the videos, great work!
Looks like I have plenty of reading to do then. Thanks and keep me in the loop!

**Comment by gdi2290** [comment]
@mcpDESIGNS are you still interested in adding this feature? what you need to do is replace `XHRImpl` 
[modules/universal/server/src/platform/node.ts#L103...L104](https://github.com/angular/universal/blob/e7bdf86f04afd172bf4d9cb71db3764c13acacc3/modules/universal/server/src/platform/node.ts#L103...L104) with your own version `NodeImpl` that has the same interface as [modules/angular2/src/platform/browser/xhr_impl.ts](https://github.com/angular/angular/blob/89f32f808f061a5d70ecd4362c4f51d240014fa0/modules/angular2/src/platform/browser/xhr_impl.ts)

**Comment by dbabaioff** [comment]
Fixed: https://github.com/angular/universal/pull/167

**Comment by gdi2290** [comment]
<img width="62" alt="merged" src="https://cloud.githubusercontent.com/assets/1016365/12177951/c1b0628e-b523-11e5-8dfa-d1e19e6f19a8.png">
via https://github.com/angular/universal/commit/8e3b2fae97f6fb3ab97c5e26ceb27f08902c8f4b

**Comment by mcpDESIGNS** [comment]
Oh shoot sorry just seeing this would of loved to of helped!
I'll talk with you guys tomorrow during the meetup, would be great to get caught up on the project @gdi2290
