### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by a-jahanshahlo** [angular/universal#1421]
there is anyway to show splash screen on first loading?

**Comment by alan-agius4** [comment]
Hi @a-jahanshahlo, can you please elaborate why would you need splash screen when using SSR, I cannot see any reason why you'd want that as you'd loose all the benefits from SSR.

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
