### ISSUE TITLE
Compression of server dont work with webpack

### ISSUE THREAD

**Issue by MaciejTest** [angular/universal#1422]
After compress with : 
    optimization: {
        minimize: true,
        minimizer: [
            new TerserPlugin({
                extractComments: true,
                cache: true,
                parallel: true,
                sourceMap: true,
                terserOptions: {
                    compress: true,
                    ecma: 5,
                    mangle: true
                  },
        
        })],

!function(e){var t={};function n(o){if(t[o])return t[o].exports;var i=t[o]={i:o,l:!1,exports:{}};return e[o].call(i.exports,i,i.exports,n),i.l=!0,i.exports}n.m=e,n.c=t,n.d=function(e,t,o){n.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:o})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,t){if(1&t&&(e=n(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var i in e)n.d(o,i,function(t){return e[t]}.bind(null,i));return o},n.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(t,"a",t),t},n.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},n.p="",n(n.s=439)}([function(e,t,n){"use strict";n.d(t,"d",(function(){return

TypeError: Right-hand side of 'instanceof' is not an object

**Comment by alan-agius4** [comment]
Hi @MaciejTest, this is most likely due to `keep_fnames` is `false` by default when setting `compress: true`

**Comment by MaciejTest** [comment]
Thanks it works. I have another question because i have big main.js 2MB in server folder and i want to minimize it maybe there is some way to do it.

**Comment by alan-agius4** [comment]
2mb is a reasonable size of a minimised server bundle.

**Comment by MaciejTest** [comment]
I talking about main.js not server.js no it`s quite big and is not compressed. I want to  compressed it or  split into chunks and if i split it with webpack  main.js dont work on browser or in server side so please some help.
