### ISSUE TITLE
documentation request for use cases and applications for universal/modules/socket-engine/

### ISSUE THREAD

**Issue by laurencefass** [angular/universal#1427]
# Feature Request

#### What is the desired behavior?
documentation request for use cases and applications for universal/modules/socket-engine/

#### What is the use-case or motivation for the desired behavior?
im currently using express engine for SSR and I don't really understand application or use of socket engine

#### Is there anything else we should know?
thanks

**Comment by CaerusKaru** [comment]
If you're using express-engine, there is no need for socket-engine, just like there's no need for hapi-engine. socket-engine is meant for users who render in non-JavaScript settings, and want a minimal layer for JavaScript-based rendering.

**Comment by alan-agius4** [comment]
Closing as socket engine is no longer supported.
