### ISSUE TITLE
exclude folder is not working and compiling together

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#1438]
In normal compiling using 'ng serve' and 'ng build' the exclude from the tsconfig file works, but when I run compiling with, ng universal the folder is included and the error.
And the folder is just where I have my schematics models, I don't use in compilation.

#### What modules are related to this issue?
```
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

#### Minimal reproduction with instructions:
the folder is called @schematics
![Captura de Tela_selecionar área_20200107092113](https://user-images.githubusercontent.com/11314585/71895209-2a3baf80-312f-11ea-9211-b2ad5d64483f.png)

File tsconfig.app.json
```javascript
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "outDir": "./out-tsc/app",
        "types": ["node"]
    },
    //"src/**/*.ts"
    "include": ["src/**/*"],
    "angularCompilerOptions": {
        "enableIvy": false,
        "allowEmptyCodegenFiles": false
    },
    "exclude": ["node_modules", "src/test.ts", "**/*.spec.ts", "@schematics"]
}
```

File tsconfig.server.json
```javascript
{
    "extends": "./tsconfig.app.json",
    "compilerOptions": {
        "outDir": "./out-tsc/app-server",
        "module": "commonjs"
    },
    "files": ["src/main.server.ts"],
    "angularCompilerOptions": {
        "entryModule": "./src/app/app.server.module#AppServerModule",
        "enableIvy": false
    }
}
```

in exclude I already tried to put "@schematics" and "**/@schematics/*" but whatever form of compilation error, why take this folder.

I also tried to modify the server copying webpack and put the code snippet below, but it didn't work the same.
![Captura de Tela_selecionar área_20200107101332](https://user-images.githubusercontent.com/11314585/71897820-69b9ca00-3136-11ea-9b95-880103039291.png)

Erro Img
![Captura de Tela_selecionar área_20200107101014](https://user-images.githubusercontent.com/11314585/71897670-f9ab4400-3135-11ea-8939-03fcdcbaf624.png)

![Captura de Tela_selecionar área_20200107092608](https://user-images.githubusercontent.com/11314585/71895423-cc5b9780-312f-11ea-8f23-8f7db9c7b05b.png)

**Comment by alan-agius4** [comment]
You need to create a separate tsconfig and configure ts-loader in webpack.config.json.

By default ts-loader will use the `tsconfig.json` which will include all workspace files within the compilation. 

Note: this is not required in version 9

**Comment by GlauberF** [comment]
it really worked, thanks
