### ISSUE TITLE
Hosting in Azure App Service stopped working after upgrade

### ISSUE THREAD

**Issue by Chreekar** [angular/universal#1447]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [x] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.6

### Description

After upgrading to express-engine 9.0.0-rc.0 through angular cli and building our project, the produced main.js file now contains the following code:

`mainModule&&mainModule.filename===__filename&&function run(){...`

However, when running this in an App Service in Azure, mainModule will look like this:

<pre><code>Module {
  id: '.',
  path: 'D:\\Program Files\\iisnode',
  exports: {},
  parent: null,
  filename: 'D:\\Program Files\\iisnode\\interceptor.js',
  loaded: false,
  children: [
    Module {
      id: 'D:\\home\\site\\wwwroot\\server\\main.js',
      path: 'D:\\home\\site\\wwwroot\\server',
      exports: {},
      parent: [Circular],
      filename: 'D:\\home\\site\\wwwroot\\server\\main.js',
      loaded: false,
      children: [],
      paths: [Array]
    }
  ],
  paths: [
    'D:\\Program Files\\iisnode\\node_modules',
    'D:\\Program Files\\node_modules',
    'D:\\node_modules'
  ]
}</code></pre>

Therefore the statement `mainModule.filename===__filename` will be false (since __filename will be the path to main.js and not interceptor.js) and the application will not start. This was not the case before upgrading. If I remove this statement it seems to work.

## 🔬 Minimal Reproduction
- ng update @nguniversal/express-engine --next
- npm run-script build:ssr
- Deploy to Azure App Service, change web.config from 
`<add name="iisnode" path="server.js" verb="*" modules="iisnode"/>` 
to 
`<add name="iisnode" path="server/main.js" verb="*" modules="iisnode"/>`

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.6
Node: 12.14.0
OS: win32 x64

Angular: 9.0.0-rc.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, upgrade
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.8
@angular-devkit/build-angular     0.900.0-rc.8
@angular-devkit/build-optimizer   0.900.0-rc.8
@angular-devkit/build-webpack     0.900.0-rc.8
@angular-devkit/core              9.0.0-rc.8
@angular-devkit/schematics        9.0.0-rc.6
@angular/cdk                      9.0.0-rc.7
@angular/flex-layout              8.0.0-beta.27
@angular/material                 9.0.0-rc.7
@ngtools/webpack                  9.0.0-rc.8
@nguniversal/builders             9.0.0-rc.0
@nguniversal/common               9.0.0-rc.0
@nguniversal/express-engine       9.0.0-rc.0
@schematics/angular               9.0.0-rc.6
@schematics/update                0.900.0-rc.6
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

**Comment by alan-agius4** [comment]
Hi, thanks for this issue. There are a handful of thing that you can do;

The problem here is that the `interceptor.js` will `require` the application files rather than executing it. https://github.com/tjanczuk/iisnode/blob/8657944f8803d84514c0c7ddd48c046aa68e6edf/src/scripts/interceptor.js#L210

1) If you don't depend on app-shell or prerendering you can remove the statement.

2) You provide a custom interceptor that doesn't `require` but rather spawn the `main.js`

3) Amend the logicical statement to something like the below;
```ts
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const mainFileName = mainModule && mainModule.filename || '';
if (mainFileName === __filename || mainFileName.includes('iisnode')) {
  run();
}
```

Personally, I'd go for the latter, which I think we should also include it by default, however it'd like so confirmation that it works prior in doing any chances.

Thanks

**Comment by Chreekar** [comment]
Thank you, option 3 works like a charm!
