### ISSUE TITLE
support node v13

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/universal#1453]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [x] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...

https://github.com/angular/universal/blob/c765baddd05cc735c237eeed903dc2e1205bc688/package.json#L19-L21
please support node v13

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
```json
  "engines": {
    "node": ">=10.13.0 <14.0.0"
  },
```

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Thanks for opening the issue, however odd versions of Node JS versions are not supported. The main reason is that these versions will never go in LTS mode and after six months they will become unsupported by the Node team.

See: https://nodejs.org/en/about/releases

**Comment by alan-agius4** [comment]
Also, the version you pointed out, is the engine required used to work on the Universal repo and not using the `@nguniversal` packages.
