### ISSUE TITLE
Angular 9 - Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by mvgadagi** [angular/universal#1455]
# 🐞 Bug report

Hello Everyone,

Today I have tried to upgrade my Angular 8 Universal to Angular 9 Universal and after upgrading, I am getting the below, 

Error :
`Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.engine (D:\NodeProjects\angular-9\dist\server.js:47017:23)
    at View.render (D:\NodeProjects\angular-9\dist\server.js:132351:8)
    at tryRender (D:\NodeProjects\angular-9\dist\server.js:129250:10)
    at Function.render (D:\NodeProjects\angular-9\dist\server.js:129202:3)
    at ServerResponse.render (D:\NodeProjects\angular-9\dist\server.js:139121:7)
    at module.exports.app.get (D:\NodeProjects\angular-9\dist\server.js:143:9)
    at Layer.handle [as handle_request] (D:\NodeProjects\angular-9\dist\server.js:130974:5)
    at next (D:\NodeProjects\angular-9\dist\server.js:130722:13)
    at Route.dispatch (D:\NodeProjects\angular-9\dist\server.js:130697:3)
    at Layer.handle [as handle_request] (D:\NodeProjects\angular-9\dist\server.js:130974:5)`

My Configurations:
package.json
```json
"@angular/animations": "^9.0.0-rc.9",
    "@angular/cdk": "^9.0.0-rc.8",
    "@angular/common": "~9.0.0-rc.9",
    "@angular/compiler": "~9.0.0-rc.9",
    "@angular/core": "^9.0.0-rc.9",
    "@angular/forms": "~9.0.0-rc.9",
    "@angular/http": "^7.2.16",
    "@angular/material": "^9.0.0-rc.8",
    "@angular/platform-browser": "~9.0.0-rc.9",
    "@angular/platform-browser-dynamic": "~9.0.0-rc.9",
    "@angular/platform-server": "^9.0.0-rc.9",
    "@angular/router": "~9.0.0-rc.9",
    "@ng-toolkit/universal": "^7.1.2",
    "@nguniversal/common": "^9.0.0-rc.0",
    "@nguniversal/express-engine": "^9.0.0-rc.0",
    "@nguniversal/module-map-ngfactory-loader": "^9.0.0-next.9"
```

tsconfig.json
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"],
    "types": ["node", "jest"]
  }
}
```
tsconfig.app.json
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "types": ["node"]
  },
  "files": [
    "main.ts",
    "polyfills.ts"
  ]
}
```
tsconfig.server.json
```
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app-server",
    "baseUrl": ".",
    "module": "commonjs"
  },
  "angularCompilerOptions": {
    "entryModule": "app/app.server.module#AppServerModule"
  }
,
  "files": [
    "main.server.ts"
  ]
}
```

server.ts
```typescript
import 'zone.js/dist/zone-node';
import { enableProdMode } from '@angular/core';
// Express Engine
import { ngExpressEngine } from '@nguniversal/express-engine';
// Import module map for lazy loading
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';

import * as express from 'express';
import { join } from 'path';
const requestIp = require('request-ip');
import * as cors from 'cors';
import * as bodyParser from 'body-parser';

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Express server
export const app = express();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist/browser');

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {
	AppServerModuleNgFactory,
	LAZY_MODULE_MAP
} = require('./dist/server/main');

// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
app.engine(
	'html',
	ngExpressEngine({
		bootstrap: AppServerModuleNgFactory,
		providers: [provideModuleMap(LAZY_MODULE_MAP)]
	})
);

app.use(cors());
app.use(requestIp.mw());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

app.set('view engine', 'html');
app.set('views', DIST_FOLDER);


app.get(
	'*.*',
	express.static(DIST_FOLDER, {
		maxAge: '1y'
	})
);

// All regular routes use the Universal engine
app.get('*', (req, res) => {
	res.render('index', { req });
});
```

**Comment by alan-agius4** [comment]
Hi, it seems that you didn’t use `ng update @nguniversal/express-engine —-next` to update.

More info about updating from Angular 8 to Angular 9 can be found here: https://update.angular.io/#8.0:9.0

**Comment by mvgadagi** [comment]
> Hi, it seems that you didn’t use `ng update @nguniversal/express-engine —-next` to update.
> 
> More info about updating from Angular 8 to Angular 9 can be found here: https://update.angular.io/#8.0:9.0

Yes, I had followed and tried this in fact but still the same errot

**Comment by mvgadagi** [comment]
@alan-agius4 Can you share any repos with Angular 9, It seems bug worth checking

**Comment by alan-agius4** [comment]
You can check our integration repost https://github.com/angular/universal/tree/master/integration

**Comment by lucaswxp** [comment]
I got the same error.

When upgrading to angular 9, I receive this message:

```
** Executing migrations of package '@nguniversal/express-engine' **

▸ Update @nguniversal/express-engine to version 9.
Cannot read property 'match' of undefined
✖ Migration failed. See above for further details.
```
Could this be related? I can't get server side rendering to work either. @mvgadagi, did you manage to solve it?

**Comment by mvgadagi** [comment]
> I got the same error.
> 
> When upgrading to angular 9, I receive this message:
> 
> ```
> ** Executing migrations of package '@nguniversal/express-engine' **
> 
> ▸ Update @nguniversal/express-engine to version 9.
> Cannot read property 'match' of undefined
> ✖ Migration failed. See above for further details.
> ```
> 
> Could this be related? I can't get server side rendering to work either. @mvgadagi, did you manage to solve it?

@lucaswxp I guess ng update is not able to handle the upgrade from Angular 8 Universal to Angular 9 Universal, so I have created all together Angular 9 fresh repo and performed ng update for universal and it's working
