### ISSUE TITLE
Universal model

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#146]
We need an approach for model objects (i.e. schema + validation) that can be used in any environment (i.e. client, server, mobile, web worker, etc.) and with non-JS tech like .NET, Java, etc. This may not require any code, but just best practices for creating simple JSON like objects that can be easily serialized.

The one trick with this will be that since it must be easily serializable, we can't include functions for validations. So, we may need to come up with a common format for validations that would be understood by any implementing library. For example:

```
{
  name: { type: string, required: true, regex: /foo.*/ },
  details: { type: string }
}
```

My example here is taken from the Mongoose.js format, but is just provided as an idea to get the discussion going.

**Comment by napsio** [comment]
Whats about https://github.com/json-schema/json-schema?

**Comment by jeffwhelpley** [comment]
@napsio I have seen that project before but it seems like it is not active anymore. No updates since May 8th, no responses to issues posted, a bunch of pending PRs, etc. @fge @kriszyp what is the status of the json-schema project?

**Comment by simb** [comment]
Perhaps the specification for JSON API could be helpful in determining a format. Not sure about validations though. http://jsonapi.org/

**Comment by jeffwhelpley** [comment]
This issue is putting the cart before the horse. We first need to greatly expand on the low level capabilities for data sharing between server and client. Agreed that we can eventually follow something like the JSON API spec, but I am going to close this for now since I don't expect us to do anything on this for awhile and it may not even be needed once data caching is in place.
