### ISSUE TITLE
Angular 9 Prerendering - Bug in generating static routes

### ISSUE THREAD

**Issue by SachinShekhar** [angular/universal#1479]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Don't know.

### Description

 
Fails to detect routes from lazy-loaded modules and doesn't generate static routes when routes in routeFile is in specific order.

## 🔬 Minimal Reproduction

My main routes are like this:
<pre><code>
[
{ path: 'xyz1', loadChildren: import(module1-file).then(m => m.module1) },
{ path: 'xyz2', loadChildren: import(module2-file).then(m => m.module2) },
{ matcher: ... , loadChildren: import(module3-file).then(m => m.module3) },
{ matcher: ... , loadChildren: import(module4-file).then(m => m.module4) },
{ path: '', loadChildren: import(module5-file).then(m => m.module5) }
]
</code></pre>
All paths lazily load modules first (with proper import syntax). There are also static routes inside all of the modules like `{ path: 'xyz', component: ...}`. Catch all path `**` is inside module5.

**First Bug**
`ng run project-name:prerender` fails to detect even one route. I don't expect it to detect from `matcher`, but it should be able to detect static paths from other modules.

**Second Bug**
When I provide it `routeFile` with following routes:
<pre><code>
/module5-path1
/module1-path1
/module2-path1
/module5-path2
/module5-path3
...
</code></pre>
Only first 3 routes are generated. No error is thrown.
When I change the sequence of routes as follows:
<pre><code>
/module5-path1
/module5-path2
/module5-path3
/module1-path1
/module2-path1
...
</code></pre>
All routes are generated successfully.
As order shouldn't matter, this is definitely a bug.

## 🔥 Exception or Error
<pre><code>

Unable to extract routes from application.
An unhandled exception occurred: No routes found.
</code></pre>
No error message for the second bug.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.7
Node: 12.6.0
OS: win32 x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.7
@angular-devkit/build-angular      0.900.0-rc.7
@angular-devkit/build-ng-packagr   0.803.14
@angular-devkit/build-optimizer    0.900.0-rc.7
@angular-devkit/build-webpack      0.900.0-rc.7
@angular-devkit/core               9.0.0-rc.7
@angular-devkit/schematics         9.0.0-rc.7
@angular/cdk                       9.0.0-rc.6
@angular/fire                      5.2.3
@angular/flex-layout               8.0.0-beta.27
@angular/material                  9.0.0-rc.6
@angular/platform-server           9.0.0-rc.8
@angular/service-worker            8.2.12
@ngtools/webpack                   9.0.0-rc.7
@nguniversal/builders              9.0.0-rc.0
@nguniversal/common                9.0.0-rc.0
@nguniversal/express-engine        9.0.0-rc.0
@schematics/angular                9.0.0-rc.7
@schematics/update                 0.900.0-rc.7
rxjs                               6.5.4
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi, would you be able to provide a minimal reproduction? I will go a long way for us to fix this bug faster.

**Comment by SachinShekhar** [comment]
@alan-agius4 Here, you go: https://github.com/SachinShekhar/angular-ssr-prerendering-bug
Check commit messages for more details.

**Comment by wagnermaciel** [comment]
`Unable to extract routes from application.` is coming from [utils.ts](https://github.com/angular/universal/blob/master/modules/builders/src/prerender/utils.ts#L47) which means guess-parser's `parseAngularRoutes` is throwing

**Comment by alan-agius4** [comment]
//cc @mgechev

**Comment by mgechev** [comment]
We can close this issue and move the discussion to [guess-js/guess](https://github.com/guess-js/guess).
