### ISSUE TITLE
Upgrade from Angular 8 to 9 (rc.11) breaks SSR / Prerender

### ISSUE THREAD

**Issue by rickvandermey** [angular/universal#1480]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8

### Description

When upgrading my angular 8 application to angular 9, SSR stops working. the localhost returns an error: `Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped`

## 🔬 Minimal Reproduction
created a branch: https://github.com/rickvandermey/angular-starterkit/tree/feature/angular-9
- `npm run certificate:generate:mac && npm run clean:install && npm run start:ssr`(for windows: remove ssl from `serve` inside 'angular.json' and run `npm run clean:install && npm run start:ssr`

## 🔥 Exception or Error
`Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped`

## 🌍 Your Environment
```
Angular CLI: 9.0.0-rc.11
Node: 12.10.0
OS: darwin x64

Angular: 9.0.0-rc.11
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------

@angular-devkit/architect                  0.900.0-rc.7
@angular-devkit/build-angular              0.900.0-rc.7
@angular-devkit/build-optimizer            0.900.0-rc.7
@angular-devkit/build-webpack              0.900.0-rc.7
@angular-devkit/core                       9.0.0-rc.11
@angular-devkit/schematics                 9.0.0-rc.11
@angular/http                              7.2.16
@ngtools/webpack                           9.0.0-rc.7
@nguniversal/common                        9.0.0-next.14
@nguniversal/express-engine                9.0.0-next.14
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        9.0.0-rc.11
@schematics/update                         0.900.0-rc.11
rxjs                                       6.5.4
typescript                                 3.6.4
webpack                                    4.41.2
```

**Comment by alan-agius4** [comment]
Hi, seeing your reproduction it seems that you didn't update using `ng update @nguniversal/express-engine --next`

Read more about updating here: https://update.angular.io/#8.0:9.0

**Comment by rickvandermey** [comment]
well tried that aswell, but the error remains the same

**Comment by alan-agius4** [comment]
From the code in the reproduction it doesn't seem that any migration was executed for ng universal.

Can you try to run;
```
ng update @nguniversal/express-engine --migrate-only update-9
```

**Comment by rickvandermey** [comment]
```
Using package manager: 'npm'
Collecting installed dependencies...
Found 92 dependencies.
** Executing 'update-9' of package '@nguniversal/express-engine' **

❯ Update @nguniversal/express-engine to version 9.
Cannot read property 'kind' of undefined
✖ Migration failed. See above for further details.
```

**Comment by NazimMertBilgi** [comment]
> ```
> Using package manager: 'npm'
> Collecting installed dependencies...
> Found 92 dependencies.
> ** Executing 'update-9' of package '@nguniversal/express-engine' **
> 
> ❯ Update @nguniversal/express-engine to version 9.
> Cannot read property 'kind' of undefined
> ✖ Migration failed. See above for further details.
> ```
> 
> Doğru bir şekilde derlendiğim noktadayım, kalan tek şey lazy_module_map'nin tembel yükleme modülleriyle derlenemediği, [https://github.com/rickvandermey/angular-starterkit/tree/feature/angular- 9](https://github.com/rickvandermey/angular-starterkit/tree/feature/angular-9)

Have you found a solution for lazy modules? @rickvandermey

**Comment by rickvandermey** [comment]
```
// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
	server.engine(
		'html',
		ngExpressEngine({
			bootstrap: AppServerModule,
			providers: [
				{
					provide: MODULE_MAP,
					useValue: 'lazy',
				},
			],
		}),
	);
```

**Comment by NazimMertBilgi** [comment]
Thank you. Where is the MODULE_MAP import ? @rickvandermey

**Comment by rickvandermey** [comment]
`import { MODULE_MAP } from '@nguniversal/module-map-ngfactory-loader';`

**Comment by matheusochi** [comment]
> this seems to work for me for now
> 
> ```
> // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
> 	server.engine(
> 		'html',
> 		ngExpressEngine({
> 			bootstrap: AppServerModule,
> 			providers: [
> 				{
> 					provide: MODULE_MAP,
> 					useValue: 'lazy',
> 				},
> 			],
> 		}),
> 	);
> ```

I tried this but it doesn't work. I'm updating from 6.0 and I am not used to work with universal.
Any advice would be appreciated!
