### ISSUE TITLE
Is there anyway to keep encoded strings (character entities) ?

### ISSUE THREAD

**Issue by kuncevic** [angular/universal#1484]
I want to hide my email for spam crawlers so I decided to encode my email string. Here is detailed explanation of the approach http://www.wbwip.com/wbw/emailencoder.html

So, when I am running a universal prerender it is turning the decoded string back to normal which is something I do not want to happend, ref: https://gitter.im/angular/universal?at=5e38077aea9ba00b84ab8fa1

Do you have any ideas how to keep encoded string with angular universal in that particular case?

**Comment by alan-agius4** [comment]
I'm sorry, but this issue is not caused by Angular.

```js
const domino = require("domino");

const window = domino.createWindow('<body>&#097;</body>', '');
window.document.serialize(); 
// "<html><head></head><body>a</body></html>"
```

Please contact the author(s) of the [Domino ](https://github.com/fgnass/domino) project or file an issue on their issue tracker.
