### ISSUE TITLE
routes are not matching in ssr

### ISSUE THREAD

**Issue by santhoshraju621** [angular/universal#1487]
Hi,

I am using angular universal for server-side rendering. there is an issue is with routing in the universal.

I have in my angular router is like "/:keyword" and I am passing to the angular router like this "/jobs-in-Visakhapatnam%20%2F%20Vizag" this route is working fine in the browser. but whereas in server environment. it is throwing me to the page not constructed. page of my application. you can check the live link of my website.  https://www.gradsiren.co.in/jobs-in-Visakhapatnam%20%2F%20Vizag

can anyone help me resolve the issue?

Thanks in advance.

**Comment by alan-agius4** [comment]
Can you setup a minimal repro please?

**Comment by alan-agius4** [comment]
Closing as no further information was provided.
