### ISSUE TITLE
Is Angular Universal support MySQL?

### ISSUE THREAD

**Issue by pokakhoaitay** [angular/universal#149]
Hi team, Is Angular Universal support MySQL? If yes, where i shoud to learn about how to implement  it?
Thank you !

**Comment by jeffwhelpley** [comment]
Angular Universal is back end agnostic. For example, let's say you use a particular node.js library to connect to your MySql database like [this one](https://github.com/felixge/node-mysql). You obviously would not use that on the front end. I would suggest you only use this library in your API on the back end and have both your web client and web server use http to call out to that same API. In that way, your Angular app would have no knowledge of MySQL at all (i.e. it would all be in your API and everything would just call into your API).

**Comment by pokakhoaitay** [comment]
Thank you so much for your useful information.
