### ISSUE TITLE
Angular 9 You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by docaohuynh** [angular/universal#1490]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
I follow https://github.com/angular/angularfire/blob/master/docs/universal/getting-started.md to build angular universal but got error

## 🔥 Exception or Error
<pre><code>

Error: You must pass in a NgModule or NgModuleFactory to be bootstrapped
    at View.eval [as engine] (webpack://app/./node_modules/@nguniversal/express-engine/fesm5/express-engine.js?:160:23)
    at View.render (webpack://app/./node_modules/express/lib/view.js?:135:8)
    at tryRender (webpack://app/./node_modules/express/lib/application.js?:640:10)
    at Function.render (webpack://app/./node_modules/express/lib/application.js?:592:3)
    at ServerResponse.render (webpack://app/./node_modules/express/lib/response.js?:1012:7)
    at app.get (webpack://app/./server.ts?:50:9)
    at Layer.handle [as handle_request] (webpack://app/./node_modules/express/lib/router/layer.js?:95:5)
    at next (webpack://app/./node_modules/express/lib/router/route.js?:137:13)
    at Route.dispatch (webpack://app/./node_modules/express/lib/router/route.js?:112:3)
    at Layer.handle [as handle_request] (webpack://app/./node_modules/express/lib/router/layer.js?:95:5)
</code></pre>

## 🌍 Your Environment
<pre><code>
Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.1
@angular-devkit/build-angular              0.900.1
@angular-devkit/build-optimizer            0.900.1
@angular-devkit/build-webpack              0.900.1
@angular-devkit/core                       9.0.1
@angular-devkit/schematics                 9.0.1
@angular/cli                               9.0.1
@angular/fire                              6.0.0-rc.1
@ngtools/webpack                           9.0.1
@nguniversal/common                        9.0.0
@nguniversal/express-engine                9.0.0
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.0.1
@schematics/update                         0.900.1
rxjs                                       6.5.4
typescript                                 3.7.5
webpack                                    4.41.2
</code></pre>
## 🌍 Package json
<pre><code>
"dependencies": {
    "@angular/animations": "~9.0.0",
    "@angular/common": "~9.0.0",
    "@angular/compiler": "~9.0.0",
    "@angular/core": "~9.0.0",
    "@angular/fire": "^6.0.0-rc.1",
    "@angular/forms": "~9.0.0",
    "@angular/platform-browser": "~9.0.0",
    "@angular/platform-browser-dynamic": "~9.0.0",
    "@angular/platform-server": "~9.0.0",
    "@angular/router": "~9.0.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2",
    "firebase": "^7.8.0"
  },
  "devDependencies": {
    "@angular-devkit/architect": "^0.900.0-0 || ^0.900.0",
    "@angular-devkit/build-angular": "~0.900.1",
    "@angular/cli": "~9.0.1",
    "@angular/compiler-cli": "~9.0.0",
    "@angular/language-service": "~9.0.0",
    "@nguniversal/express-engine": "^9.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "express": "^4.17.1",
    "firebase-tools": "^7.12.1",
    "fuzzy": "^0.1.3",
    "inquirer": "^6.2.2",
    "inquirer-autocomplete-prompt": "^1.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-loader": "^6.2.1",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.7.5",
    "webpack-cli": "^3.3.10",
    "ws": "^7.2.1",
    "xhr2": "^0.2.0"
  }</code></pre>

**Comment by tieppt** [comment]
Angular Universal v9 is changed. please follow official docs.
https://angular.io/guide/universal

**Comment by docaohuynh** [comment]
Thanks @tieppt 
It works perfectly on local, do you know how to deploy in firebase functions
