### ISSUE TITLE
Prerender without express-engine/hapi-engine

### ISSUE THREAD

**Issue by alan-agius4** [angular/universal#1493]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
At the moment, to add the prerender builder the user needs to add either express-engine or hapi-engine. However, pre-render users might such functionality and can be used with any server.

We should make it more easy and require less dependencies and boilerplatting when using prerender without SSR.

**Comment by wagnermaciel** [comment]
Would using a custom server require providing a custom server builder, too? By custom server I just mean not using express-engine or hapi-engine

**Comment by alan-agius4** [comment]
No, they can use the current server builder. What will change is the `ng add` part. To something like `ng add nguniversal/builders`
