### ISSUE TITLE
Angular 9 SSR, router-outlet empty problem

### ISSUE THREAD

**Issue by NazimMertBilgi** [angular/universal#1501]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ x ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

**Problem:**
https://i.ibb.co/4Rrgg6v/problem.png

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by NazimMertBilgi** [comment]
Hi, where is the Angular 9 SSR lazy loading setup document? @alan-agius4

**Comment by alan-agius4** [comment]
Lazy loading is SSR is no different that then browser lazy loading.
