### ISSUE TITLE
ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1502]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction

npm run build:ssr
npm run dev:ssr
## 🔥 Exception or Error
<pre><code>
ERROR Error: Uncaught (in promise): ReferenceError: localStorage is not defined
ReferenceError: localStorage is not defined
    at new CheckPremissionService (E:\ssr\dist\overseas\server\main.js:220920:9)
    at Object.CheckPremissionService_Factory [as factory] (E:\ssr\dist\overseas\server\main.js:220949:87)
    at R3Injector../node_modules/@angular/core/__ivy_ngcc__/bundles/core.umd.js.R3Injector.hydrate (E:\ssr\dist\overseas\server\main.js:55687:39)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.1
Node: 12.14.1
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.1
@angular-devkit/core         9.0.1
@angular-devkit/schematics   9.0.1
@schematics/angular          9.0.1
@schematics/update           0.900.1
rxjs                         6.5.3
</code></pre>

**Comment by chris13524** [comment]
https://angular.io/guide/universal#working-around-the-browser-apis

**Comment by alan-agius4** [comment]
Closing as per above.
