### ISSUE TITLE
 inject() must be called from an injection context

### ISSUE THREAD

**Issue by GlebStepenko** [angular/universal#1504]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
I try to open a page in a browser after build:ssr 

## 🔬 Minimal Reproduction
git clone git@github.com:GlebStepenko/universal.ivy.error.git

or

ng new app-ssr
cd app-ssr
add  "postinstall": "ngcc" in package.json
ng add @nguniversal/express-engine
npm run build:ssr

add simple nodejs server in app.js

<pre><code>
'use strict';
require('zone.js/dist/zone-node');
const express = require('express');
const ngUniversal = require('@nguniversal/express-engine');
const appServer = require('./dist/app-ssr/server/main');

/* Server-side rendering */
function angularRouter(req, res) {
 /* Server-side rendering */
 res.render('index', { req, res });
}

const app = express();

app.get('/', angularRouter);

/* Serve the static files generated by the CLI (index.html, CSS? JS, assets...) */
app.use(express.static(`${__dirname}/dist/app-ssr/browser`));

/* Configure Angular Express engine */
app.engine('html', ngUniversal.ngExpressEngine({
 bootstrap: appServer.AppServerModule,
}));
app.set('view engine', 'html');
app.set('views', 'dist/app-ssr/browser');

/* Direct all routes to index.html, where Angular will take care of routing */
app.get('*', angularRouter);

app.listen(3000, () => {
 console.log(`Listening on http://localhost:3000`);
});
</code></pre>

node app.js
go to in browser in localhost:3000

## 🔥 Exception or Error
<pre><code>
Error: inject() must be called from an injection context
    at injectInjectorOnly (/Users/gleb/work/temp/app-ssr/app-ssr/dist/app-ssr/server/main.js:1:1624478)
    at Module.ɵɵinject (/Users/gleb/work/temp/app-ssr/app-ssr/dist/app-ssr/server/main.js:1:1624794)
    at Object.BrowserModule_Factory [as factory] (/Users/gleb/work/temp/app-ssr/app-ssr/dist/app-ssr/server/main.js:1:2287168)
    at R3Injector.hydrate (/Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:11505:39)
    at R3Injector.get (/Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:11328:37)
    at /Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:11268:77
    at Set.forEach (<anonymous>)
    at new R3Injector (/Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:11268:35)
    at createInjector (/Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:11233:16)
    at new NgModuleRef$1 (/Users/gleb/work/temp/app-ssr/app-ssr/node_modules/@angular/core/bundles/core.umd.js:24243:33)

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.13.1
OS: darwin x64

Angular: 9.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by alan-agius4** [comment]
Hi, what is the reason of not using the `server` bundle directly `node dist/app-ssr/server/main,js`? This already contains the express instance and configuration.

If you want to use an Angular dependency outside of the bundle you'd need to export it from the server bundle. An example can be found here: https://github.com/angular/universal/issues/1485#issuecomment-581805693

**Comment by GlebStepenko** [comment]
Hi.
Thanks, but i can't from the technical reasons use express instance from server bundle. I use my own express instance and my configuration.

how i can export dependency from server bundle if they are missing in this bundle.
after 
const {AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap, renderModuleFactory} = require('./dist/app-ssr/server/main');

AppServerModuleNgFactory or LAZY_MODULE_MAP is underfined.

**Comment by GlebStepenko** [comment]
Hi @alan-agius4 
Thanks, but i can't from the technical reasons use express instance from server bundle. I use my own express instance and my configuration.

how i can export dependency from server bundle if they are missing in this bundle.
after 
const {AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap, renderModuleFactory} = require('./dist/app-ssr/server/main');

AppServerModuleNgFactory or LAZY_MODULE_MAP is underfined.

**Comment by alan-agius4** [comment]
`AppServerModuleNgFactory` and `LAZY_MODULE_MAP ` are no longer generated using Ivy.

You need to use the following
`AppServerModule` instead of  `AppServerModuleNgFactory`
`provideModuleMap` & `LAZY_MODULE_MAP` are no longer needed why using `import()` lazy syntax
`renderModule` instead of `renderModuleFactory`
```

**Comment by GlebStepenko** [comment]
thanks,  it works

**Comment by aheadmode** [comment]
Thank you Alan for your support so far.

We are looking for a solution to directly `require()` multiple packaged and localized angular server modules into one single instance of express. We definitely want to avoid running a separate server instance for each language, since we support over 32 languages.

app.server.ts
```js
import {enableProdMode} from '@angular/core';

import {environment} from './environments/environment';

if (environment.production) {
  enableProdMode();
}

export {AppServerModule} from './app.server.module';
export {renderModule, renderModuleFactory} from '@angular/platform-server';
```

gateway.ts (the express server)
```js
export function app() {
  const bundles = [{
    engine: "en.html",
    moduleName: 'AppServerModule',
    modulePath: "dist/app/server/en/main"
  },{
    engine: "jp.html",
    moduleName: 'AppServerModule',
    modulePath: "dist/app/server/jp/main"
  }]

  // Start up the Node server
  const app: express.Application = express();
  
  // Register an ngExpressEngine engine for each i18n bundle
  bundles.forEach(function(bundle, lang: Language) {
    const module = require(path.join(process.cwd(), bundle.modulePath));
  
    app.engine(bundle.engine, ngExpressEngine({
        bootstrap: module[bunde.moduleName] // we reference AppServerModule here
      }
    ));
  });
  
  ...
  // Later we switch the app.engine view engine during runtime on a per-request basis (depending on request cookies and request parameters)
}
```

Unfortunately we can not get the AppServerModule bootstrapped. We tried both server engines, **express** and **hapi***, but the error message remains always the same

Error (the source code is located at /home/debug/buildserver/fragment)
```sh
Error: inject() must be called from an injection context
    at injectInjectorOnly (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:2805193)
    at ɵɵinject (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:2805509)
    at Object.ApplicationModule_Factory [as factory] (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:3208672)
    at R3Injector.hydrate (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1133109)
    at R3Injector.get (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1129894)
    at /home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1129002
    at Set.forEach (<anonymous>)
    at new R3Injector (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1128980)
    at createInjector (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1128355)
    at new NgModuleRef$1 (/home/debug/buildserver/fragment/dist/app/gateway/main.js:1:1304470)

```

Your help would be appreciated.

**Comment by aheadmode** [comment]
@alan-agius4
