### ISSUE TITLE
Make server.ts be able to serve prerendered files without having to write /index.html

### ISSUE THREAD

**Issue by wagnermaciel** [angular/universal#1506]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
I would like to make `server.ts` behave more like a CDN in that it would be able to serve prerendered files without having to go to `/[route]/index.html`.

### Describe the solution you'd like
I'd like to change the default installation of [`server.ts`](https://github.com/angular/universal/blob/master/modules/express-engine/schematics/install/files/__serverFileName%40stripTsExtension__.ts#L33) to do this:

```
  // If the given route has been prerendered, returns the file path to the cached html document.
  function getCachedFile(route) {
    const file = join(distFolder, route, 'index.html');
    if (existsSync(file)) {
      if (route !== '/') {
        return file;
      }
      const cachedIndexFile = join(distFolder, 'index.original.html');
      if (existsSync(cachedIndexFile)) {
        return cachedIndexFile;
      }
    }
  }

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    const file = getCachedFile(req.path);
    if (file) {
      return res.sendFile(file);
    }
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });
```

**Comment by wagnermaciel** [comment]
@alan-agius4 I'd like to hear your thoughts on this.

**Comment by alan-agius4** [comment]
I think the above is a good approach though I'd refrain from using the term `caching` as that might imply that it's a caching laying. 

Though that brings up a bigger question, in the "real world" what are the use cases of having a hybrid mode ie: Prerendering + SSR?

//cc @kyliau, @CaerusKaru and @MarkPieszak thoughts?

**Comment by kyliau** [comment]
I think the idea sounds good. We just have to be a little careful in terms of security. There needs to be some kind of "whitelist" of pre-rendered routes otherwise users could "probe" the server to see what's available on disk.

**Comment by alan-agius4** [comment]
Probably from an implementation POV, we should use expess static with
middlewares to avoid checking for file existence and reduce security
concerns though for hapi we need to do some investigation.

**Comment by alan-agius4** [comment]
I think in express by changing the path in first middleware https://github.com/angular/universal/blob/57a0399133ccb7bc43a5024e0c40c7f8fafa6180/modules/express-engine/schematics/install/files/__serverFileName%40stripTsExtension__.ts#L28

To `*` the middleware fullbacking should get enabled

**Comment by kyliau** [comment]
That seems like a clean and elegant solution!

**Comment by wagnermaciel** [comment]
Would this handle the `index.html` --> `index.original.html` case?

**Comment by alan-agius4** [comment]
@wagnermaciel yes if you do something like the below;

```ts
  server.get('*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
  // The below RegExp is to ensure that the universal middleware is not called for paths with extensions (ex: invalid.js)
  server.get(/(\/[-\w]*)+$/, (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });
```

**Comment by alan-agius4** [comment]
Actually thinking about it more, I think the above will break SSR for the root page, because it will find the `index.html` and it will serve that.

**Comment by wagnermaciel** [comment]
Hey, had time to think about this today and wanted to build on top of your idea.

I haven't run or double checked this but I was thinking we could do something like:

```ts
function renderRoute(req, res) {
    res.render(indexHtml, {
        req,
        providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }],
    });
}

// Handle the edge case independently. By not calling "next" we are avoiding
// allowing requests to "/" to be handled by other middleware down the line.

app.use('/', (req, res, next) => {
    const cachedIndexFile = join(distFolder, 'index.original.html');
    if (existsSync(cachedIndexFile)) {
        res.sendFile(cachedIndexFile);
    } else {
        renderRoute(req, res);
    }
});

// If we reach here, we know we are not dealing with "/" and don't need to
// worry about statically serving the wrong route.

app.use('*', express.static(distFolder, { maxAge: '1y' }));

// Anything that reaches here should just get rendered normally.

server.get('*', (req, res) => {
    renderRoute(req, res);
});
```

**Comment by alan-agius4** [comment]
@wagnermaciel, I'll try to take a look in the coming days!

If only we generated the prerendered pages to some other filename ex: `default.html`, `static.html` it would be so much easier :)
