### ISSUE TITLE
Handling 3rd party lib without webpack config

### ISSUE THREAD

**Issue by kirill-chirkov-at-clouty** [angular/universal#1508]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.x.x

### Description
Before webpack config termination in version 9, I used to have some hack for 3rd party libs like fabric.js that are not working in server environment, here's `externals` config piece:
```javascript
  externals: {
    './dist/server/main': 'require("./server/main")',
    // These externals below helps fabric to launch without errors in server:
    'canvas': 'undefined',
    'jsdom/lib/jsdom/utils': JSON.stringify({ Canvas: null }),
    'jsdom/lib/jsdom/living/generated/utils': JSON.stringify({ implForWrapper: null }),
    'jsdom': JSON.stringify({ JSDOM: null })
  },
```

Related discussion in fabric.js issues: https://github.com/fabricjs/fabric.js/issues/6015. Low chances that this would be fixed in fabric.

I'm not talking about fabric in general, but about every lib that requires this kind of pattern to tweak webpack externals in order to launch correctly.

## 🔬 Minimal Reproduction
1. Install fabric: `npm i fabric`
2. Use fabric somewhere at any place in application:
```typescript
if (isPlatformBrowser(this.platform)) {
    require('fabric');
}
```
I used platform check and dynamic import to demonstrate that this is enough for server build to break.
3. run `npm run build:ssr` which stands for `ng build --prod && ng run clouty-front:server:production`

## 🔥 Exception or Error
Here comes error from fabric which uses binaries for its launch (which require node-loader):
<pre><code>
ERROR in ./node_modules/canvas/build/Release/canvas.node 1:2
Module parse failed: Unexpected character '�' (1:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.2
Node: 13.1.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.6
</code></pre>

**Comment by alan-agius4** [comment]
You can use the `externalDependencies` option. Which can be configured in `angular.json` under the server options.

Ex:
```js
"server": {
  "builder": "@angular-devkit/build-angular:server",
  "options": {
    "progress": false,
    "outputPath": "dist/express-engine-ivy-prerender/server",
   "externalDependencies": [
       "fabric",
    ],
    "main": "server.ts",
    "tsConfig": "tsconfig.server.json"
  },
```

**Comment by kirill-chirkov-at-clouty** [comment]
Thanks for the advice, that actually works!
