### ISSUE TITLE
HttpClient throws "unknown error" for 302 redirects

### ISSUE THREAD

**Issue by joeflateau** [angular/universal#1512]
# 🐞 Bug report

Calling `HttpClient#get("https://unpkg.com/ffpreset/README.md", { responseType: "text" })` results in the following being logged:

```
ERROR HttpErrorResponse {
  headers:
   HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://unpkg.com/ffpreset/README.md',
  ok: false,
  name: 'HttpErrorResponse',
  message:
   'Http failure response for https://unpkg.com/ffpreset/README.md: 0 Unknown Error',
```

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [ ] builders
- [ x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

I'm not sure

## 🔥 Exception or Error
ERROR HttpErrorResponse {
  headers:
   HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
  status: 0,
  statusText: 'Unknown Error',
  url: 'https://unpkg.com/ffpreset/README.md',
  ok: false,
  name: 'HttpErrorResponse',
  message:
   'Http failure response for https://unpkg.com/ffpreset/README.md: 0 Unknown Error',
  error:
   ProgressEvent {
     type: 'error',
     target:
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [XMLHttpRequestUpload],
        _method: 'GET',
        _url: [Url],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     currentTarget:
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [XMLHttpRequestUpload],
        _method: 'GET',
        _url: [Url],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     lengthComputable: false,
     loaded: 0,
     total: 0 } }
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 10.18.1
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by joeflateau** [comment]
I should have noted that this only happens on the SSR side. The request works just fine in the browser.

**Comment by codystevelarson** [comment]
@joeflateau  I'm having the exact same problem making calls to an external endpoint to handle cms data. Only happens when the app is running on the server. You have any luck with a solution yet?

Calling to direct endpoints (ex. /content/getNavHeaderContent) work without issue, but any endpoint that redirects (ex. /pages/about > return redirect(/content/getPageContent?id={id})) fail immediately with the "Unknown Error" Status Code 0.  Calling the (ex. /content/getPageContent?id={id}) endpoint directly works on when running on the server. 

This error is the only thing in the way of finishing this project, and I would rather not make the client change their API to handle this weird edge case.

**Comment by joeflateau** [comment]
I did not. I ended up changing to avoid the redirect 😔

**Comment by CaerusKaru** [comment]
This doesn't look like an issue with Angular Universal, and is likely an issue with the configuration of the request or the server (or both). Please see [here](https://github.com/angular/angular/issues/22022#issuecomment-363602769) for greater depth on the issue (or use Google).

**Comment by joeflateau** [comment]
@CaerusKaru I can assure you I've used Google. The issue you linked me to is a CORS issue. My issue is only server side. The client side works as expected. This is not a CORS issue.

**Comment by CaerusKaru** [comment]
I linked to the CORS comment to illustrate that a status of 0 is indicative of something wrong with the request or its environment and not with the framework making the request.

If you scroll down further on that issue, there is a SO link, one of the responses is that it could be a TLS issue on the server where you don’t have certificates enabled correctly. Again, just one possibility, but it doesn’t indicate anything wrong with Angular Universal itself.

If we are in error, and you can show definitively that it is only Universal at issue, we are happy to reopen this issue.
