### ISSUE TITLE
After upgrade to v9, window is undefined after declaring it in server.ts when using it outside the Angular zone

### ISSUE THREAD

**Issue by faropoulos** [angular/universal#1518]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Yes, the previous version in which this bug was not present was: v8

### Description

Before upgrading to v9 of Angular and Universal, in order to freely use the window, document, localStorage etc properties, i did declare them as nodejs global variables using domino and dom-storage modules. 

```typescript
import {createWindow} from 'domino';
import Storage from 'dom-storage';
const window = createWindow();
(global as any).window = window;
(global as any).document = window.document;
(global as any).navigator = window.navigator;
(global as any).localStorage = (global as any).window.localStorage = new Storage(null, {strict: true});
(global as any).sessionStorage = (global as any).window.sessionStorage = new Storage(null, {strict: true});
```

After the update, there was a server.ts.bak file created, and the guide described that i have to manually move the code. I did and transferred the above code as follows:

```typescript
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // SSR Workaround
  const window = createWindow();
  (global as any).window = window;
  (global as any).document = window.document;
  (global as any).navigator = window.navigator;
  (global as any).localStorage = (global as any).window.localStorage = new Storage(null, {strict: true});
  (global as any).sessionStorage = (global as any).window.sessionStorage = new Storage(null, {strict: true});

  server.engine('html', ngExpressEngine({bootstrap: BoxServerModule}));
  server.set('view engine', 'html');
  server.set('views', distFolder);
  server.get('*.*', express.static(distFolder, {maxAge: '1y'}));
  server.get('/sitemap.xml', (req, res) => res.sendFile(__dirname + '/browser/sitemap.xml'));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, {req, providers: [{provide: APP_BASE_HREF, useValue: req.baseUrl}]});
  });

  return server;
}
```

## 🔬 Minimal Reproduction

Download the SSR boilerplate and user window.localStorage in a component without checking if isBrowser. Then transfer the above code that i user for the window and dom-storage mock in the server.ts file.

## 🔥 Exception or Error

Running the server with ```npm run serve:ssr``` will give you the ```ReferenceError: window is not defined``` error.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.2
Node: 12.4.0
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cdk                      9.0.0
@angular/cli                      9.0.2
@angular/material                 9.0.0
@ngtools/webpack                  9.0.2
@nguniversal/builders             9.0.0
@nguniversal/common               9.0.0
@nguniversal/express-engine       9.0.0
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.6

</code></pre>

**Comment by faropoulos** [comment]
I managed to understand what is causing the problem. Using window, document etc outside the angular zone, causes this error. I don't really get why, maybe the TS files are imported earlier before the server.ts. 

I was using localStorage inside a *.utils.ts file. that file was not any of the Angular File types (Service, Component, Provider etc). It was a regular JS Module file exporting a bunch of functions and objects. Is there a way to go past that? It would be a shame to not be able to use native DOM API. Also i don't like the use of providers (DOCUMENT, WINDOW etc). That's why i implemented the window object server side with domino.

**Comment by alan-agius4** [comment]
The problem with the above logic, is that you are defining the `window` global object during execution of the `app` method. This comes after the JS parsing phase which correctly fails because `window` is not defined. 

So in order to "fix" that you need to defined the globals outside of the method and move it before the import of `main.server.ts`. That said, I would strongly suggest to use DI tokens instead, and the global approach should only be used if one of your dependent library uses the global window object without checking if it's available or not.
