### ISSUE TITLE
How to deploy the latest Angular Universal on azure App Service?

### ISSUE THREAD

**Issue by MDzyga** [angular/universal#1527]
Hi,
I have to deploy my application on azure and after executing `ng run traceabilit-universal:build:dev && ng run traceabilit-universal:server:dev`, next copying on Azure, application does't work.

My options:

```
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist",
            "index": "src/index.html",
            "main": "src/main.browser.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/assets",
              "src/favicon.png",
              "src/robots.txt",
              "src/manifest.json"
            ],
            "styles": [],
            "scripts": []
          },
          "configurations": {
            "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "aot": true,
              "serviceWorker": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/browser/environment.dev.ts"
                }
              ]
            },
```

```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist-server",
            "main": "server.ts",
            "tsConfig": "tsconfig.server.json"
          },
          "configurations": {
            "dev": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "namedChunks": false,
              "extractLicenses": true,
              "vendorChunk": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/server/environment.dev.ts"
                }
              ]
            },
```

## 🌍 Your Environment
* Angular 9
* Angular Universal 9
* webpack 4.41.6

**Comment by MDzyga** [comment]
@alan-agius4 
here is my repository with sample code https://github.com/MDzyga/universal.
I try to use webpack before send on Azure but I have a problem with it.

**Comment by MDzyga** [comment]
@alan-agius4 
Do you know how can I generate server.js? I need this file to publish on Azure.

**Comment by MDzyga** [comment]
@alan-agius4 
I figured out I need to use webpack to generate server.js but I have a problem with paths defined in tsconfig.json. I don't know if a problem is with angular cli or webpack.

My application is building without using webpack but webpack throws some exceptions with e.g 'Cannot find module "@shared/.."'. Do you have some idea where is a problem or how to resolve it?

**Comment by alan-agius4** [comment]
@MDzyga, the standalone webpack build is redundant. `ng run test-universal:server:production` will generate the bundle for the server.

To spawn the server you'd need to run `main.js` located in your server dist folder.
Ex:
```
node dist/dist-server/main.js
```

**Comment by MDzyga** [comment]
Ok, but I'm not able to execute this command on Azure App Service.
I can only prepare web.config with redirections.
I would like to omit creating new Web App with docker to run my application because of the latest version of Angular :( 
Any idea?

**Comment by alan-agius4** [comment]
You can amend your web.config to point to the correct server entry point.
https://github.com/MDzyga/universal/blob/master/web.config

**Comment by MDzyga** [comment]
So should I change this line:
`<action type="Rewrite" url="track/server.js"/>`
on something like this:
`<action type="Rewrite" url="track/dist-server/main.[hash].js"/>`
It could be easier & faster if you have some web.config example. My client has a big conference soon and I have to deploy my changes :(

**Comment by MDzyga** [comment]
@alan-agius4 
I fixed web.config and server.ts file :)
In web.config I had to change rewrite rule on main.js (it can't be hashed) and in server.ts I have to check if it's production build and if it's I have to set proper path to dist folder
