### ISSUE TITLE
loading first time twice in angular ssr 9

### ISSUE THREAD

**Issue by shomid** [angular/universal#1546]
I having project with angular ssr 9.
this work with `ng serve` correctly.
but when build with `npm run build:ssr` and run server.js
loading first time twice in `http://localhost:4000` and there is fickering in loading first.
I tried very hard to find a cause but couldn't.

![Screenshot from 2020-03-10 07-52-15](https://user-images.githubusercontent.com/8733354/76288090-2eb14f80-62bb-11ea-8bf1-9b590fc992aa.png)

source: [source my project](https://drive.google.com/file/d/1ETi4ycSh3-hAG5KpGVDeTslskMoOwHTB/view?usp=sharing)
If anyone can find a cause, thank you.

**Comment by alan-agius4** [comment]
Hi @shomid, what is happening here  is that the application is being bootstrapped and executed twice, first on the server, followed by the browser, which is the expected behaviour.

However, your `CanonicalService` doesn't handle this properly, as it only check for the existence of the `link` tag in the service instance.

A better approach would be to check the existence of the `link` tag in the document example:
```ts
import { Injectable, Inject } from '@angular/core';
import { DOCUMENT } from '@angular/common';

@Injectable({
  providedIn: 'root'
})
export class CanonicalService {
  constructor(
    @Inject(DOCUMENT) private dom: Document
  ) { }

  setCanonicalURL() {
    let link = this.dom.querySelector('link[rel=canonical]');

    console.log(this.dom.head);

    if (!link) {
      link = this.dom.createElement('link');
      link.setAttribute('rel', 'canonical');
      this.dom.head.appendChild(link);
    }
    link.setAttribute('href', this.dom.URL.split('?')[0]);
  }

}
```

**Comment by shomid** [comment]
Thank you for your quick response.
some problems:
-Carousel images are loaded twice if you care
-fickering menu in header

![Screenshot from 2020-03-10 13-29-09](https://user-images.githubusercontent.com/8733354/76303550-2b2bc180-62d7-11ea-9f4c-81e9346a81bf.png)
![Screenshot from 2020-03-10 13-55-33](https://user-images.githubusercontent.com/8733354/76303569-3252cf80-62d7-11ea-8b30-94ff911cf668.png)

**Comment by shomid** [comment]
> Hi @shomid, what is happening here is that the application is being bootstrapped and executed twice, first on the server, followed by the browser, which is the expected behaviour.
> 
> However, your `CanonicalService` doesn't handle this properly, as it only check for the existence of the `link` tag in the service instance.
> 
> A better approach would be to check the existence of the `link` tag in the document example:
> 
> ```ts
> import { Injectable, Inject } from '@angular/core';
> import { DOCUMENT } from '@angular/common';
> 
> @Injectable({
>   providedIn: 'root'
> })
> export class CanonicalService {
>   constructor(
>     @Inject(DOCUMENT) private dom: Document
>   ) { }
> 
>   setCanonicalURL() {
>     let link = this.dom.querySelector('link[rel=canonical]');
> 
>     if (!link) {
>       link = this.dom.createElement('link');
>       link.setAttribute('rel', 'canonical');
>       this.dom.head.appendChild(link);
>     }
>     link.setAttribute('href', this.dom.URL.split('?')[0]);
>   }
> 
> }
> ```



> Hi @shomid, what is happening here is that the application is being bootstrapped and executed twice, first on the server, followed by the browser, which is the expected behaviour.
> 
> However, your `CanonicalService` doesn't handle this properly, as it only check for the existence of the `link` tag in the service instance.
> 
> A better approach would be to check the existence of the `link` tag in the document example:
> 
> ```ts
> import { Injectable, Inject } from '@angular/core';
> import { DOCUMENT } from '@angular/common';
> 
> @Injectable({
>   providedIn: 'root'
> })
> export class CanonicalService {
>   constructor(
>     @Inject(DOCUMENT) private dom: Document
>   ) { }
> 
>   setCanonicalURL() {
>     let link = this.dom.querySelector('link[rel=canonical]');
> 
>     if (!link) {
>       link = this.dom.createElement('link');
>       link.setAttribute('rel', 'canonical');
>       this.dom.head.appendChild(link);
>     }
>     link.setAttribute('href', this.dom.URL.split('?')[0]);
>   }
> 
> }
> ```

Notice the post above

**Comment by shomid** [comment]
> Thank you for your quick response.
> some problems:
> -Carousel images are loaded twice if you care
> -fickering menu in header
> 
> ![Screenshot from 2020-03-10 13-29-09](https://user-images.githubusercontent.com/8733354/76303550-2b2bc180-62d7-11ea-9f4c-81e9346a81bf.png)
> ![Screenshot from 2020-03-10 13-55-33](https://user-images.githubusercontent.com/8733354/76303569-3252cf80-62d7-11ea-8b30-94ff911cf668.png)

images loading twice ,once by `Parser` and once by `main.js`.
why ?
