### ISSUE TITLE
No ResourceLoader implementation has been provided. Can't read the url "xxx.html" with Angular 9

### ISSUE THREAD

**Issue by daniloff200** [angular/universal#1547]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

## 🔥 Exception or Error
<pre><code>
Error: No ResourceLoader implementation has been provided. Can't read the url "promotion.component.html"
    at Object.get (/home/vs/Projects/my-project/node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js:322:19)
    at DirectiveNormalizer._fetch (/home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:19585:47)
    at DirectiveNormalizer._preParseTemplate (/home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:19624:33)
    at DirectiveNormalizer.normalizeTemplate (/home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:19612:40)
    at CompileMetadataResolver.loadDirectiveMetadata (/home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:21863:62)
    at /home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:28283:59
    at Array.forEach (<anonymous>)
    at /home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:28282:76
    at Array.forEach (<anonymous>)
    at JitCompiler._loadModules (/home/vs/Projects/my-project/node_modules/@angular/compiler/bundles/compiler.umd.js:28279:79)

</code></pre>

I have this error only related to components from Shared module
Here's my **shared.module.ts** file: 

<pre><code>

@NgModule({
  imports: [
    CommonModule,
    RouterModule,
    FormsModule,
    TooltipModule.forRoot(),
    PaginationModule.forRoot(),
    ModalModule.forRoot(),
    BsDatepickerModule.forRoot(),
    NguCarouselModule,
    ReactiveFormsModule
  ],
  declarations: [
   PromotionComponent
    ProductsCategoryComponent,
    ComponentListItemComponent,
    PaginationComponent,
    ValidatorMessageComponent,
    ImgExistDirective,
    RelatedProductsComponent,
    AgeVerificationModalComponent,
    MinValueValidatorDirective,
    MaxValueValidatorDirective,
    AutoTabDirective,
  ],
  exports: [
   PromotionComponent
    ProductsCategoryComponent,
    ComponentListItemComponent,
    PaginationComponent,
    ValidatorMessageComponent,
    ImgExistDirective,
    RelatedProductsComponent,
    AgeVerificationModalComponent,
    MinValueValidatorDirective,
    MaxValueValidatorDirective,
    AutoTabDirective,
  ]
})
export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: [
        { provide: HTTP_INTERCEPTORS, useClass: BaseUrlInterceptorService, multi: true },
        { provide: HTTP_INTERCEPTORS, useClass: RefreshTokenInterceptor, multi: true }
      ]
    };
  }
}
</code></pre>

Code, related to rendering at the server:
<code><pre>
  renderHtml(options, callback) {
    renderModule(ServerAppModule, {
      document: this.template,
      url: options.req.url,
      extraProviders: [
        provideModuleMap(LAZY_MODULE_MAP),
        {
          provide: 'REQUEST',
          useValue: options.req
        },
        {
          provide: 'RESPONSE',
          useValue: options.req.res
        }
      ]
    }).then(html => {
      callback(null, html);
    });
  }
</code></pre>

That's actually failed with the first component, but, no issues with directives (I've tried to remove all components from here, and also, remove all templates and .ts files, related to these components, then, Universal works well)

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect                  0.900.3
@angular-devkit/build-angular              0.900.3
@angular-devkit/build-optimizer            0.900.3
@angular-devkit/build-webpack              0.900.3
@angular-devkit/core                       9.0.1
@angular-devkit/schematics                 9.0.1
@angular/cdk                               9.1.0
@ngtools/webpack                           9.0.3
@nguniversal/common                        9.0.1
@nguniversal/express-engine                9.0.1
@nguniversal/module-map-ngfactory-loader   9.0.0-next.9
@schematics/angular                        9.0.1
@schematics/update                         0.900.1
rxjs                                       6.5.3
typescript                                 3.7.5
webpack                                    4.41.2

</code></pre>

Any ideas, what I've made wrong?

I've checked https://github.com/angular/universal/issues/579, but, it's definitely outdated for my case. I assume, that something has been changed, because, previously, with NG7, there was no any issues, like that

**Comment by alan-agius4** [comment]
Can you please provide a reproduction? You somehow, you are ending up using the JIT compiler instead of the AOT compiler.

**Comment by daniloff200** [comment]
@alan-agius4  yeah, sorry for not providing that from the beginning

here's the repo: 
https://github.com/daniloff200/ng9-ssr-demo

You can launch it by `npm run ssr:local`  in first terminal tab, and `npm run ssr-server:start` in the second

I little bit messed up with the code, right now, with no-ssr build you will just see the white screen and Maximum called stack error, but, with ssr you will get the error, I mentioned in the issue

**Comment by alan-agius4** [comment]
@daniloff200, thanks for the repo, I’ll try to take a look in the coming days.

**Comment by daniloff200** [comment]
I've tried to remove these 2 components from Shared module (afaik, with Ivy Shared module is not a good solution), and made them as Single Component Angular Modules, but, no success.

Right now I get the same error, but, with app.component.html

`Error: No ResourceLoader implementation has been provided. Can't read the url "app.component.html"
`

**Comment by daniloff200** [comment]
hey, @alan-agius4 
Sorry for bother, in these hard times, but, did you have a chance to look at this issue?

**Comment by alan-agius4** [comment]
@daniloff200, unfortunately not yet.

Though I did spot some potential issues in https://github.com/daniloff200/ng9-ssr-demo/blob/fa9a80a2930eab533c660e73e4b335fb5fc95b1c/ssr-server/src/html-renderer.ts#L3-L5 and https://github.com/daniloff200/ng9-ssr-demo/blob/fa9a80a2930eab533c660e73e4b335fb5fc95b1c/ssr-server/src/main.ts#L5

Any package which is dependent on Angular DI should be exported from the server bundle. As otherwise, you will end up with multiple instances.

Also, in version 9 you no longer need a separate webpack build (ie: https://github.com/daniloff200/ng9-ssr-demo/blob/master/webpack.config.js), you can take a look at one of our tests: https://github.com/angular/universal/tree/master/integration/express-engine-ivy

**Comment by daniloff200** [comment]
hello @alan-agius4 

Thanks you so much!
I changed my imports from 

`import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
const { ServerAppModule, LAZY_MODULE_MAP } = require('../../dist/universal/main.js');
import { renderModule } from '@angular/platform-server';`

to 

const { ServerAppModule, LAZY_MODULE_MAP, renderModule, provideModuleMap } = require('../../dist/universal/main.js')

and also, the same change for `import { enableProdMode } from '@angular/core';` 
and the error was fixed

There was also some minor stuff, related to packages, I use after it, but, I've managed to run SSR for Angular 9 right now!

Thanks again for your help!
