### ISSUE TITLE
@nguniversal/module-map-ngfactory-loader v9 ?

### ISSUE THREAD

**Issue by squelix** [angular/universal#1557]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [x] module-map-ngfactory-loader

### Description
Update v9 ?

When this package will be updated to v9 please ?

**Comment by alan-agius4** [comment]
NB: This package is deprecated, and is no longer required unless you use the string based lazy loading syntax.

If you updated to Angular 9, using `ng update`, it should have been removed from your problem.

That said, probably we should still release it until string based lazy loading is supported by the Angular framework.

//cc @kyliau

**Comment by squelix** [comment]
I did the `ng update` but I still have the 
```
export { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
```

in my `main.ssr.ts`

**Comment by alan-agius4** [comment]
@squelix, if you are not using string based lazy loading you can remove those.

**Comment by squelix** [comment]
I'm not using it since v8 :p 

Thank you guys ! :)

**Comment by squelix** [comment]
I have a white screen if i remove all uses of `@nguniversal/module-map-ngfactory-loader` ad i'm not using string based lazy loading anymore.

**Comment by kosso** [comment]
Due to the variance of tutorials on getting started with Universal these days, can someone please confirm that `@nguniversal/module-map-ngfactory` is **no longer required** on Angular 9 projects if you are already using the `loadChilden()` callback syntax for lazy-loaded modules?

Thanks.

**Comment by alan-agius4** [comment]
@kosso, that is correct.

**Comment by alan-agius4** [comment]
Closing as deprecation notice was added.
