### ISSUE TITLE
You must pass in a NgModule or NgModuleFactory to be bootstrapped

### ISSUE THREAD

**Issue by BruneXX** [angular/universal#1558]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

Yes, the previous version in which this bug was not present was: **Angular 8.2.14**

### Description

Making new build and serve for with Angular 9.0.6 causes this new error.

## 🔬 Minimal Reproduction

Make new build and serve for with Angular 9.0.6 causes this new error.

## 🔥 Exception or Error
<pre><code>
You must pass in a NgModule or NgModuleFactory to be bootstrapped

</code></pre>

## 🌍 Your Environment
<pre><code>
Node v12.16.1 (LTS)
@angular/core: 9.0.6
@nguniversal/express-engine: 9.0.2
npm v6.13.4

</code></pre>

**Comment by alan-agius4** [comment]
Hi, did you update `@nguniversal/express-engine` using `ng update`?

**Comment by BruneXX** [comment]
Hi @alan-agius4 I've tried both, but it was an issue on server.ts, removing **AppServerModuleNgFactory** and useing **AppServerModule** instead seems to solve the issue.
Then other issue airise:
It was: **Unhandled Promise rejection: Can't resolve all parameters for ApplicationModule:Unhandled Promise rejection: Can't resolve all parameters for ApplicationModule:(?)**
I fixed that reviewing ohter issues in angular repo, adding **import 'reflect-metadata';** at the top of server.ts solve the issue, then a new issue arise after build, this is during serve universal app with node

** errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'my.component.html'
} Error: ENOENT: no such file or directory, open 'my.component.html'
Unhandled Promise rejection: ENOENT: no such file or directory, open 'my.component.html' ; Zone: <root> ; Task: Promise.then ; Value: [Error: ENOENT: no such file or directory, open 'my.component.html**

Any suggestions to solve that?

Thanks!

**Comment by alan-agius4** [comment]
From the above it seems that the migration didn’t run as if it did you shouldn’t have any reference to ngfactories.

Can you please try the below
```
ng update @nguniversal/express-engine —migrate-only —from 8 —to 9
```

**Comment by BruneXX** [comment]
@alan-agius4 Yes, trying now, thanks! I'll let you know the results.

**Comment by BruneXX** [comment]
@alan-agius4 Migration was successfull! I'm trying to serve my project now, this is the output I've got:

> The installed local Angular CLI version is older than the latest stable version.
> Installing a temporary version to perform the update.
> Installing packages for tooling via npm.
> Installed packages for tooling via npm.
> Using package manager: 'npm'
> Collecting installed dependencies...
> Found 67 dependencies.
> ** Executing migrations of package '@nguniversal/express-engine' **
> 
> ▸ Update @nguniversal/express-engine to version 9.
> RENAME server.ts => server.ts.bak
> CREATE server.ts (1999 bytes)
> UPDATE package.json (4006 bytes)
> UPDATE src/app/app.server.module.ts (1024 bytes)
> UPDATE src/tsconfig.server.json (462 bytes)
> UPDATE angular.json (8338 bytes)
> UPDATE src/app/app-routing.module.ts (500 bytes)
> ✔ Packages installed successfully.
>   Migration completed.
> 


But then trying to serve I've this error: **ERROR in error TS6053: File '/var/www/html/bairesjobs/frontend/src/server.ts' not found.**

I'm searching where the path could be wrong.. may be tscnofig.ts checking...

**Comment by BruneXX** [comment]
It's seems to be working but now I've got any other errors like:

provideModuleMap is not logner available? how to replace it?

I'm having issues with cookies too

**Comment by BruneXX** [comment]
Managed to fix that, here's a new issue (hard to fix I guess):

```
(node:21893) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
ERROR Error [NullInjectorError]: StaticInjectorError(AppServerModule)[request]: 
  StaticInjectorError(Platform: core)[request]: 
    NullInjectorError: No provider for request!
```

**Comment by BruneXX** [comment]
In the past that configuration was:

```
server.engine('html', (_, options, callback) => {
   const engine = ngExpressEngine({
       bootstrap: AppServerModule,
       providers: [
          { provide: 'request', useFactory: () => options.req, deps: [] },
           provideModuleMap(LAZY_MODULE_MAP)
       ]
   });
   engine(_, options, callback);
});
```

Now it's:
```
server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule
    }),
  );
```

What do you suggest to fix that in this new angular version?

**Comment by alan-agius4** [comment]
`provideModuleMap` is no longer required unless you are using string based lazy loaded.

You can amend the above engine call to the below:

```ts
server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
       providers: [
          { provide: 'request', useFactory: () => options.req, deps: [] },
       ]
    }),
  );
```

**Comment by BruneXX** [comment]
Yes, but I've got a tslint error in options object, "Did you men 'Option'?" since option seems to not be declared..

**Comment by alan-agius4** [comment]
Apologies edited the above snippet.

**Comment by BruneXX** [comment]
oh, yes, I've tried that but I've other errors.. regarding options... IDK why, here's a screenshot:

![Captura de pantalla de 2020-03-19 14-47-36](https://user-images.githubusercontent.com/28172522/77098141-a46e9700-69f0-11ea-9d03-f8362fb4b298.png)

**Comment by BruneXX** [comment]
Using type **any** after **options** => **options: any** avoid errors but I don't think that will be the correct solution... BTW it's working now :)

**Comment by BruneXX** [comment]
This is the final code I've used in order to avoid those errors:

``` javascript
server.engine('html', (_, options: any, callback) => {
  const engine = ngExpressEngine({
      bootstrap: AppServerModule,
      providers: [
        { provide: 'request', useFactory: () => options.req, deps: [] },
      ]
  });
  engine(_, options, callback);
});
```

**Comment by BruneXX** [comment]
@ alan-agius4 Thank you so much for your help, it was fundamental in order to deal with the end of this migration to ng9, it was really harderd, almost like it was on the initials of 2.beta to 2.rc haha ​​what a good times xD

**Comment by alan-agius4** [comment]
Closing as it seems to be resolved.
