### ISSUE TITLE
TS2315: Type '...' is not generic.

### ISSUE THREAD

**Issue by cromefire** [angular/universal#1559]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Maybe, not tested

### Description

The build errors (see below)

## 🔬 Minimal Reproduction

Not yet, can develop one on request

## 🔥 Exception or Error

```
ERROR in node_modules/@nguniversal/express-engine/tokens/tokens.d.ts:7:46 - error TS2315: Type 'Request' is not generic.

7 export declare const REQUEST: InjectionToken<Request<ParamsDictionary>>;
                                               ~~~~~~~~~~~~~~~~~~~~~~~~~
node_modules/@nguniversal/express-engine/tokens/tokens.d.ts:9:47 - error TS2315: Type 'Response' is not generic.

9 export declare const RESPONSE: InjectionToken<Response<any>>;
                                                ~~~~~~~~~~~~~
```

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.6
Node: 12.16.1
OS: linux x64

Angular: 9.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cdk                      9.1.3
@angular/material                 9.1.3
@angular/pwa                      0.900.6
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.39.1
</code></pre>

**Comment by alan-agius4** [comment]
Hi, what the version of your `@types/node` please?

**Comment by cromefire** [comment]
Have to look it up late but it should be 12.X.X

**Comment by cromefire** [comment]
```
"@types/express": "4.17.0",
"@types/node": "~12.7.1"
```

**Comment by alan-agius4** [comment]
Hi @cromefire, I tried to reproduce this locally but I was unable. Can you try to update `@types/node` to `^12.11.1`.?

**Comment by cromefire** [comment]
Upgrading that did work, thanks
