### ISSUE TITLE
Angular universal demo not working

### ISSUE THREAD

**Issue by BruneXX** [angular/universal#1560]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?
No
### Description

Demo from https://angular.io/guide/universal not working

## 🔬 Minimal Reproduction
1 ) Go to https://angular.io/guide/universal
2) Download https://angular.io/generated/zips/universal/universal.zip
3) Extract and get into the new extracted folder (named usually as **universal**)
4) Run `npm install && npm run build:ssr:dev && npm run serve:ssr`

## 🔥 Exception or Error
I's doing nothing, but if I comment the following code:
<pre><code>
// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
// declare const __non_webpack_require__: NodeRequire;
// const mainModule = __non_webpack_require__.main;
// if (mainModule && mainModule.filename === __filename) {
  run();
// }
</code></pre>

 in server.ts it works and a new error arise:

**Error: Failed to lookup view "index" in views directory "/universal_demo/dist/express-engine-ivy/browser"**

Change that path to be dist/browser result in a new error:

**Error: Can't resolve all parameters for ApplicationModule: (?).**

Also to fix that I've added the follwoing at the top of server.ts file:

**import 'reflect-metadata';**

Throws a new error that is related with a file not found (file from project)

```
 errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'my.component.html'
} Error: ENOENT: no such file or directory, open 'my.component.html'
Unhandled Promise rejection: ENOENT: no such file or directory, open 'my.component.html' ; Zone: <root> ; Task: Promise.then ; Value: [Error: ENOENT: no such file or directory, open 'my.component.html
```

## 🌍 Your Environment
Linux Debian stretch
Node 12.16.1
Angular: 9.0.6

</code></pre>

**Comment by alan-agius4** [comment]
The current universal TOH is out-of-date and is currently tracked here: https://github.com/angular/angular/issues/35289

You can however, create a universal demo app as follows;

```cmd
npx @angular/cli@latest new universal-demo --routing
cd universal-demo
ng add @nguniversal/express-engine
```
