### ISSUE TITLE
twice loading image and flickering site with angular ssr 9

### ISSUE THREAD

**Issue by shomid** [angular/universal#1566]
I have two problem with my project in angular ssr 9:
1-twice loading images in carousel.
![Screenshot from 2020-03-22 17-52-12](https://user-images.githubusercontent.com/8733354/77250592-a3df3600-6c66-11ea-8399-e8fd326db64c.png)

2-flickering header in load first time.
![Screenshot from 2020-03-22 17-52-26](https://user-images.githubusercontent.com/8733354/77250597-acd00780-6c66-11ea-96d5-1a1e036d9fc7.png)

I tried very hard to find a cause but couldn't.
[source of my project.](https://drive.google.com/file/d/1njCJ84JQA7frEQrP9VONEFlIBS0P9BbN/view?usp=sharing)
If anyone can find a cause, thank you.

**Comment by CaerusKaru** [comment]
This is likely not an issue with Angular Universal, especially without a minimal reproduction pointing to Universal as the source. Better avenues for support are StackOverflow or Gitter.
