### ISSUE TITLE
Change ngModel binding on <select> to be ssr compatible

### ISSUE THREAD

**Issue by sod** [angular/universal#1569]
# 🚀 Feature request

Change ngModel binding on `<select [ngModel]="x"><option [ngValue]="y">...` to be ssr compatible

### Description

Consider this template:

```html
        <input [ngModel]="foo"> <!-- foo = 'test' -->
        <select [ngModel]="bar"> <!-- bar = 2 -->
            <option [ngValue]="1">1</option>
            <option [ngValue]="2">2</option>
        </select>
```

The ssr output looks like this:
![image](https://user-images.githubusercontent.com/905328/77308779-c7a08b80-6cfb-11ea-8ddf-c287a8ff8620.png)

And the DOM:
![image](https://user-images.githubusercontent.com/905328/77308837-dedf7900-6cfb-11ea-987a-e44b0cc7dfad.png)

So the `ngModel` on the input field created a `value="test"` attribute, so the ssr output reflects the state.
But the `ngModel` on the select field didn't create a `selected` attribute on the `<option>2</option>`

In the client that code works. I guess it writes the state into the property `selected`, that is not serializable by ssr.

**Comment by sod** [comment]
Right now we do
```typescript
        <select [ngModel]="bar"> <!-- bar = 2 -->
            <option [ngValue]="1" [attr.selected]="isSsr && bar === 1 ? 'selected' : null">1</option>
            <option [ngValue]="2" [attr.selected]="isSsr && bar === 2 ? 'selected' : null">2</option>
        </select>
```

To have the selected attribute in the ssr result.

**Comment by CaerusKaru** [comment]
This is just how that component works, it does not set `selected`, even on the client. You can see for yourself [here](https://github.com/angular/angular/blob/4456e7e4dec87f237cee0ed2eb6eb4431e806ea5/packages/forms/src/directives/select_control_value_accessor.ts). If you set `id` on the `option` components, it will set the `selectedIndex` property correctly, which will amount to what you're looking for.

**Comment by sod** [comment]
I'd rather not as of angulars horrendous performance with that construct: https://github.com/angular/angular/issues/37285#issuecomment-635451082

We innerHTML the options now via directive. 50x faster and we can manage the initial selected state - that is ssr compatible - ourself. Basicly what [angularjs did with ngOptions](https://docs.angularjs.org/api/ng/directive/ngOptions).
