### ISSUE TITLE
Problem with angular universal running on platform side

### ISSUE THREAD

**Issue by Saeed-RM** [angular/universal#1571]
# Issue in my project

Im trying to convert my SPA angular 6 application to Angular universal so I could have a better seo in my website but the application is not getting rendered again on front side (only rendered server side)

### Description
After Fixing problems such as window undefined and document , local storage undefined problems 
im facing a new issue which is that i realized my angular app is just getting rendered server side and i have no functionalities in the fronted (for ex : if a have a on click method it doesn't work)as: ....

Im using 
Angular : 6
typescript : 2.7
and webpack

I dont know exactly which parts of the projects are important to paste here , so im justing pasting webpack.config and server.ts 

my webpack.server.config.ts file : 
<pre><code>
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
	entry: { server: './server.ts' },
	resolve: { extensions: ['.ts', '.js'] },
	target: 'node',
	// this makes sure we include node_modules and other 3rd party libraries
	externals: [/(node_modules|main\..*\.js)/],
	output: {
		path: path.join(__dirname, 'dist'),
		filename: '[name].js'
	},
	module: {
		rules: [
			{ test: /\.ts$/, loader: 'ts-loader' },
			{ test: /hammerjs/,loader: "null-loader"},
			// {test: /\.js$/, loader: 'string-replace-loader', options: {search: "import hammerjs from 'hammerjs'\n", replace: '',}},
			// { test: /hammerjs/,loader: "bundle-loader",options: { lazy: true}}
		]
	},
	mode: 'development',
	plugins: [
		// Temporary Fix for issue: https://github.com/angular/angular/issues/11580
		// for "WARNING Critical dependency: the request of a dependency is an expression"
		new webpack.ContextReplacementPlugin(
			/(.+)?angular(\\|\/)core(.+)?/,
			path.join(__dirname, 'src'), // location of your src
			{} // a map of your routes
		),
		new webpack.ContextReplacementPlugin(
			/(.+)?express(\\|\/)(.+)?/,
			path.join(__dirname, 'src')
		),
	]
};

</code></pre>

my server.ts file :

<pre><code>
// These are important and needed before anything else
import 'zone.js/dist/zone-node';
import 'reflect-metadata';

import { enableProdMode } from '@angular/core';
import { platformServer, renderModuleFactory } from '@angular/platform-server';
import * as express from 'express';
import { join } from 'path';
import { readFileSync } from 'fs';

// Faster server renders w/ Prod mode (dev mode never needed)
enableProdMode();

// Express server
const app = express();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist');

// Our index.html we'll use as our template
const template = readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist-server/main.js');

const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xmlhttprequest').XMLHttpRequest;
app.engine('html', (_, options, callback) => {
  renderModuleFactory(AppServerModuleNgFactory, {
    // Our index.html
    document: template,
    url: options.req.url,
    // DI so that we can get lazy-loading to work differently (since we need it to just instantly render it)
    extraProviders: [
      provideModuleMap(LAZY_MODULE_MAP)
    ]
  }).then(html => {
    callback(null, html);
  });
});

app.set('view engine', 'html');
app.set('views', join(DIST_FOLDER, 'browser'));

// Server static files from /browser
app.get('*.*', express.static(join(DIST_FOLDER, 'browser')));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.render(join(DIST_FOLDER, 'browser', 'index.html'), { req });
});

// Start up the Node server
app.listen(PORT, () => {
  console.log(`Node server listening on http://localhost:${PORT}`);
});

</code></pre>

 

please do not hesitate to ask questions related to my problem

**Comment by alan-agius4** [comment]
Hi @Saeed-RM, can you please provide a reproduction of the problem with the latest Angular version? 

Angular 6 is no longer supported please see: https://angular.io/guide/releases#support-policy-and-schedule. To update you can follow this guide: https://update.angular.io
