### ISSUE TITLE
npm run serve:ssr Cannot find module 'E:\example\dist\overseas\server\main.js'

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1573]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
my project file directory 
`example\dist\overseas\server\main.d7cfee5a69a5e62947f6.js`
execute cmd `npm run build:ssr` after.
 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
package.json
<pre><code>
  "scripts": {
    "ng": "ng",
    "start": "ng serve --port 8001",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ssr": "ng run overseas:serve-ssr",
    "dev:ssr": "ng run overseas:serve-ssr",
    "serve:ssr": "node dist/overseas/server/main.js",
    "build:ssr": "ng build --prod && ng run overseas:server:production",
    "prerender": "ng run overseas:prerender",
    "postinstall": "ngcc"
  },

Angular CLI: 9.1.0
Node: 12.14.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by mvgadagi** [comment]
Have you tried upgrading with following these instructions?
https://update.angular.io/#8.0:9.0l3

**Comment by alan-agius4** [comment]
Can you please share the `server` section of your ‘angular.json`?

**Comment by yangjunfocus** [comment]
thanks! i solved it
