### ISSUE TITLE
SVG loaded twice in server

### ISSUE THREAD

**Issue by Leanvitale** [angular/universal#1578]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

 I have a refresh problem on my page when it first starts. I could see that this is a reload of the SVG.
The funny thing is that it only happens when I raise the project with pm2, because with the command 'node dist/server.js' this does not happen.

## 🔬 Minimal Reproduction

**node dist/server.js:**
<img width="1440" alt="Captura de Pantalla 2020-03-27 a la(s) 10 37 12" src="https://user-images.githubusercontent.com/7925697/77742788-53c1f400-7017-11ea-8f1e-d949a810e1cb.png">

**pm2 start dist/server.js -n 'donar'** (Duplicate load SVG)
<img width="1440" alt="Captura de Pantalla 2020-03-27 a la(s) 10 42 44" src="https://user-images.githubusercontent.com/7925697/77743037-bdda9900-7017-11ea-8708-19a895a9833c.png">

## 🌍 Suggestion?
Any suggestion as to why this happens? If you need more information please just ask for it.
Thank you!

**Comment by CaerusKaru** [comment]
I don't think this is a problem with Angular Universal specifically. Better avenues for support on this would be StackOverflow or Gitter. If you can find a specific thing about Angular Universal causing this, we can reopen this issue.
