### ISSUE TITLE
Unclear Documentation in @nguniversal/module-map-ngfactory-loader/README.md

### ISSUE THREAD

**Issue by btakita** [angular/universal#1581]
It's unclear which files the code snippets should go into. Also, it's not clear what `app.platform = 'server'` means.

I did try adding:

```ts
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
const { AppModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/web/server/main');

renderModuleFactory(AppModuleNgFactory, {
  document: '<app-root></app-root>',
  url: '/',
  extraProviders: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
})
```

into `server.ts`, but get an error when running `npm run dev:ssr`:

```
ERROR in ./server.ts
Module not found: Error: Can't resolve './dist/web/server/main' in '/path/to/app'
```

This was my best guess based on what I see in the `README.md`, so I'm confused whether or not I'm performing the correct steps or if there is a bug in the `@nguniversal/module-map-ngfactory-loader` library.

I'm also confused about the design decision to require boilerplate that references the built bundle, instead of providing a module in the npm package that exports `AppModuleNgFactory` & `LAZY_MODULE_MAP`.

**Comment by alan-agius4** [comment]
Hi @btakita, 

`@nguniversal/module-map-ngfactory-loader` is deprecated and should only be used if you are using string based lazy loaded which is also deprecated.

If you are using Angular 8+ most likely you are not using this type of lazy loading and thus this module shouldn’t be used.

In case you are using string based lazy loading, let me know and I can provide further details.

**Comment by btakita** [comment]
Thank you. I removed `@nguniversal/module-map-ngfactory-loader` in the project...
