### ISSUE TITLE
How to use SSR with ASP.NET - Documentation is broken and outdated

### ISSUE THREAD

**Issue by Cyral** [angular/universal#1586]
Hello,

I am trying to use SSR with .NET Core 3 and Angular 9 and for the life of me I can't find any working documentation. 

The npm package itself has a lot of code samples: https://www.npmjs.com/package/@nguniversal/aspnetcore-engine

However it seems to assume some steps were already done? It starts off with "Within our main.server file, things haven't changed much...." Changed much from what? The code following tries to import "./app/app.server.module" What is that? There is no mention of this file in the docs.

After looking at the documentation on the Angular site (only for Node/Express rendering), I see the `ng add @nguniversal/express-engine` command will generate this structure. However, if I try and run the same command with the aspnetcore package, I get "The package that you are trying to add does not support schematics.".

On the server side, I see that some of the methods are deprecated. I found this GitHub issue: https://github.com/dotnet/aspnetcore/issues/12890#issuecomment-575197453 which says that many of the critical dependencies (at least from the npm page code) are being removed, such as `aspnet-prerendering`, `Microsoft.AspNetCore.SpaServices`, `Microsoft.AspNetCore.NodeServices`. Without these packages, will it still be possible do to SSR with .NET Core in the future?

I really want to get .NET Core SSR up and running and I do appreciate all the work that various maintainers have put in to this project. I can understand how fast dependencies change in the webdev world so it can be difficult keeping documentation up to date, but it is very frustrating to see official packages for this yet no clear installation instructions.

**Comment by boban984** [comment]
@Cyral did you solve the problem? It seems using exrpess is the way to go.
Im also having difficulties with this

**Comment by hheexx** [comment]
I switched to Rendertron and I am satisfied!

**Comment by maxisam** [comment]
https://github.com/MillersProfessionalImaging/angular-universal-dotnet-core-demo

Here is my solution to run angular universal in IIS with dotnet. Not pretty but it should work.

Disclaimer: I am not a nodejs expert, so it probably doesn't follow the best practice. If you find anything should change, please let me know. Thanks!

**Comment by alan-agius4** [comment]
Closing as ASP.NET integration is not official supported.
