### ISSUE TITLE
After updating to angular 9 i am getting error while server side rendering.

### ISSUE THREAD

**Issue by rankitbishnoi** [angular/universal#1587]
# 🐞 Bug report

#### What modules are related to this issue?
- [*] aspnetcore-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description
After updating to angular 9 i am getting error while server side rendering.

        /** @type {?} */
        const factory = yield getFactory(moduleOrFactory, compiler);
        /** @type {?} */
        const result = yield renderModuleFactory(factory, {
            document: options.document || options.appSelector,
            url: options.url || options.request.absoluteUrl,
            extraProviders,
        });
        /** @type {?} */
        const doc = result.moduleRef.injector.get(_angular_common__WEBPACK_IMPORTED_MODULE_1__["DOCUMENT"]);
        /** @type {?} */
        const universalData = _getUniversalData(doc);
        return {
            html: universalData.appNode,
            moduleRef: result.moduleRef,
            globals: {
                styles: universalData.styles,
                title: universalData.title,
                scripts: universalData.scripts,
                meta: universalData.meta,
                links: universalData.links
            }
        };

In this code while creating doc constant there is error of injector has been destroyed. the exception is given below.

## 🔥 Exception or Error
<pre><code>

Error: Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (\main.js:83227:19)
    at R3Injector.get (\main.js:83132:14)
    at NgModuleRef$1.get (\main.js:100500:33)
    at Module.<anonymous> (\main.js:165940:47)
    at Generator.next (<anonymous>)
    at fulfilled (\main.js:232571:62)
    at ZoneDelegate../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invoke (\main.js:235154:30)
    at Zone../node_modules/zone.js/dist/zone-node.js.Zone.run (\main.js:234911:47)
    at \main.js:235659:38
    at ZoneDelegate../node_modules/zone.js/dist/zone-node.js.ZoneDelegate.invokeTask (\main.js:235189:35)) ---> Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: Injector has already been destroyed.
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.0
Node: 13.10.1
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.0
@angular-devkit/build-angular              0.901.0
@angular-devkit/build-optimizer            0.901.0
@angular-devkit/build-webpack              0.901.0
@angular-devkit/core                       9.1.0
@angular-devkit/schematics                 9.1.0
@angular/cdk                               9.2.0
@angular/flex-layout                       9.0.0-beta.29
@angular/material                          9.2.0
@angular/material-moment-adapter           9.2.0
@ngtools/webpack                           9.1.0
@nguniversal/aspnetcore-engine             9.1.0
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        9.1.0
@schematics/update                         0.901.0
rxjs                                       6.5.4
typescript                                 3.8.3
webpack                                    4.42.0
</code></pre>

**Comment by amakhrov** [comment]
Same issue here

It happens in the code that initiates some background data refresh to be done in parallel to serving request.
Simplified code:
```
const globalCache = new Cache();

class BootstrapService {
  constructor() {
    if (globalCache.isStale(key) {
       setTimeout(() => {
          this.http.request('/some/data').toPromise()
           .then(data => globalCache.set(key, data)
           .catch(logger.error)
       }, 0)
    }
  }
}
```


It usually happens when such data refresh is initiated in a user request that completes quickly  (mostly those resulting in 301).

```
Injector has already been destroyed.
    at R3Injector.assertNotDestroyed (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/core/bundles/core.umd.js:11776:23)
    at R3Injector.get (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/core/bundles/core.umd.js:11705:18)
    at HttpInterceptingHandler.handle (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/common/bundles/common-http.umd.js:2204:50)
    at ZoneClientBackend.delegate (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/platform-server/bundles/platform-server.umd.js:501:33)
    at scheduleTask (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/platform-server/bundles/platform-server.umd.js:436:42)
    at Observable._subscribe (/Users/amakhrov/crunchbase/client_app/node_modules/@angular/platform-server/bundles/platform-server.umd.js:475:17)
    at Observable._trySubscribe (/Users/amakhrov/crunchbase/client_app/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/amakhrov/crunchbase/client_app/node_modules/rxjs/internal/Observable.js:30:22)
    at Object.subscribeToResult (/Users/amakhrov/crunchbase/client_app/node_modules/rxjs/internal/util/subscribeToResult.js:12:23)
    at MergeMapSubscriber._innerSub (/Users/amakhrov/crunchbase/client_app/node_modules/rxjs/internal/operators/mergeMap.js:82:53)
```

```
Angular CLI: 9.1.7
Node: 12.4.0
OS: darwin x64

Angular: 9.1.9
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cdk                      9.2.4
@angular/cli                      9.1.7
@angular/material                 9.2.4
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.43.0
```

**Comment by CaerusKaru** [comment]
Please provide a minimal GitHub reproduction that way we can investigate this further.

**Comment by amakhrov** [comment]
I don't have minimal repro, however, I have good understanding why it happened our cases. Maybe it will help someone.

So in our case we  we have some Http Interceptor configured in the app.
```
{provide: HTTP_INTERCEPTORS, useClass: InternalHeaderInterceptor, multi: true},
```
And the app schedules (via setTimeout) an http call to refresh cache shared across all requests.

In certain cases (usually, when request results in an error such as 404), the app has done processing a user request very quickly. So **by the time the scheduled http call is executed, the app (with the injector) has been destroyed**. Even though HttpClient instance intself is still available (it was injected upon app start), the **http interceptor could not be initialized** (interceptor initializes dynamically when an http call is initiated).

So in our case the fix was removing this setTimeout, and triggering the http call immediately - meking sure injector is still able to resolve http interceptors

**Comment by CaerusKaru** [comment]
If that's the case, then I'm closing this issue as working as expected. We're adding more detail about the rendering process to our "gotchas" guide in #1730. And in case you were wondering, the real issue for you was not `setTimeout`, it was that you were running `setTimeout` outside of the Angular Zone. If you ran it inside the Zone, the render would wait for the timeout to complete.

**Comment by amakhrov** [comment]
Thats for the clarification @CaerusKaru .

> If you ran it inside the Zone, the render would wait for the timeout to complete

Yep, and that's exactly what we wanted to avoid. The idea is that refreshing this shared cache in the background should not delay rendering the response for an individual user request.
