### ISSUE TITLE
npm run buils:ssr && npm run serve:ssr background-image 404

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1591]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/23710467/77985576-715cc980-7347-11ea-8178-8653292d55f4.png)

## 🌍 Your Environment
<pre><code>

"scripts": {
    "ng": "ng",
    "start": "ng serve --port 8001",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "ssr": "ng run example:serve-ssr",
    "dev:ssr": "ng run example:serve-ssr",
    "serve:ssr": "node dist/example/server/main.js --watch",
    "build:ssr": "ng build --prod && ng run example:server:production",
    "prerender": "ng run example:prerender",
    "postinstall": "ngcc"
  }
// angular.json:
"build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/example/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": [
              
            ]
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "4mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "6kb"
                }
              ]
            }
          }
        }

Angular CLI: 9.1.0
Node: 10.15.3
OS: win32 x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.0.2
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @yangjunfocus, most likely the cause is that you don't have the `"outputHashing": "media"` in your server production configuration.

**Comment by yangjunfocus** [comment]
> Hi @yangjunfocus, most likely the cause is that you don't have the `"outputHashing": "media"` in your server production configuration.

thanks! i try your method,and solved it.
