### ISSUE TITLE
Module '"../../parse5/lib"' has no exported member 'ElementLocation'

### ISSUE THREAD

**Issue by rfk91** [angular/universal#1602]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Not sure

### Description

 After adding Angular Universal to a project, running `firebase deploy --only functions:ssr` throws an error.

## 🔬 Minimal Reproduction
ng new dba
ng add @angular/fire@next
ng add @nguniversal/express-engine
firebase deploy --only functions:ssr

## 🔥 Exception or Error
<pre><code>
i  deploying functions
Running command: npm --prefix "$RESOURCE_DIR" run lint

> functions@ lint /home/rfk91/Desktop/dba/functions
> tslint --project tsconfig.json

Running command: npm --prefix "$RESOURCE_DIR" run build

> functions@ build /home/rfk91/Desktop/dba/functions
> tsc

../node_modules/@types/jsdom/index.d.ts:12:10 - error TS2305: Module '"../../parse5/lib"' has no exported member 'ElementLocation'.

12 import { ElementLocation } from 'parse5';

</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.0
Node: 13.8.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.2.0
@angular/fire                     6.0.0-rc.2
@angular/material                 9.2.0
@angular/youtube-player           9.2.0
@ngtools/webpack                  9.1.0
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by chris13524** [comment]
I'm also getting this error.

```
node_modules/@types/jsdom/index.d.ts:12:10 - error TS2305: Module '"../../parse5/lib"' has no exported member 'ElementLocation'.

12 import { ElementLocation } from 'parse5';
            ~~~~~~~~~~~~~~~


Found 1 error.
```

```
 % npm ls @types/jsdom
coconut@0.19.37 /home/chris13524/programming/coconut/client
└─┬ @nguniversal/builders@9.1.0
  └─┬ guess-parser@0.4.17
    └─┬ @wessberg/ts-evaluator@0.0.25
      └── @types/jsdom@16.2.0
```

**Comment by Lagistos** [comment]
Someonne found an answer to this?

**Comment by rfk91** [comment]
Install the latest version of parse5 in your project `npm install parse5@latest`

**Comment by troydcthompson** [comment]
@rfk91 thanks boss

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
