### ISSUE TITLE
9.1.0 nguniversal error in tokens.d.ts

### ISSUE THREAD

**Issue by cantacell** [angular/universal#1610]
### Affected Package
@nguniversal/express-engine

### Is this a regression?
Yes, work  in version 9.0.5

### Description
Error reported at line 9: export declare const RESPONSE: InjectionToken<Response<any>>;

## 🔥 Exception or Error
ERROR in node_modules/@nguniversal/express-engine/tokens/tokens.d.ts:9:47 - error TS2315: Type 'Response' is not generic.

9 export declare const RESPONSE: InjectionToken<Response<any>>;

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.1
Node: 10.15.0
OS: win32 x64

Angular: 9.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/pwa                      0.901.1
@ngtools/webpack                  9.1.1
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
Can you try to update @types/node to ^12.11.1?

**Comment by cantacell** [comment]
Tried but without success

**Comment by alan-agius4** [comment]
Can you run `npm ls @types/node` and post the output here please?

**Comment by cantacell** [comment]
+-- @angular-builders/custom-webpack@9.0.0
| `-- @angular-devkit/build-angular@0.900.7
|   `-- rollup@1.25.2
|     `-- @types/node@12.12.35  deduped
+-- @angular-devkit/build-angular@0.901.1
| +-- license-webpack-plugin@2.1.4
| | `-- @types/webpack-sources@0.1.7
| |   `-- @types/node@12.12.35  deduped
| `-- webpack-dev-server@3.10.3
|   `-- del@4.1.1
|     `-- @types/glob@7.1.1
|       `-- @types/node@12.12.35  deduped
+-- @compodoc/compodoc@1.1.11
| `-- cheerio@1.0.0-rc.3
|   `-- parse5@3.0.3
|     `-- @types/node@12.12.35  deduped
+-- @types/express@4.17.2
| +-- @types/body-parser@1.17.1
| | +-- @types/connect@3.4.32
| | | `-- @types/node@12.12.35  deduped
| | `-- @types/node@12.12.35  deduped
| `-- @types/express-serve-static-core@4.17.0
|   `-- @types/node@12.12.35  deduped
+-- @types/node@12.12.35
`-- protractor@5.3.2
  `-- @types/node@6.14.9

**Comment by Superlukec** [comment]
@cantacell today, I had the same problem. After couple of hours I've found a solution.

This was the last resort for me, but solution worked, maybe will not for you, but it's worth a try. 

Delete node_modules folder inside Angular project, and then run:
`npm install`

Before that I've double-checked all dependecnies. And also created a backup of original node_modules.

**Comment by emondora** [comment]
Same problem, and i tried to delete node_modules and npm install again. But not work for me.
Below is my types version:
"@types/express": "^4.17.0",
"@types/node": "^12.11.1",

**Comment by alan-agius4** [comment]
Can you try to pin down `@types/express` to `4.17.4`?

**Comment by cantacell** [comment]
> Can you try to pin down `@types/express` to `4.17.4`?

It works, thanks!
