### ISSUE TITLE
No meta tags in page source after getting data from resolver

### ISSUE THREAD

**Issue by kresogalic8** [angular/universal#1615]
Hi guys, I can't get meta tags in page source after i got the data from server.  I made a resolver and i am using route helper to update meta tags with all required meta informations for sharing the post on social media etc.

Here's the code:

    private setupRouting() {
        this.router.events
            .pipe(
                filter((event) => event instanceof NavigationEnd),
                map(() => this.activatedRoute),
                map((route) => {
                    while (route.firstChild) {
                        route = route.firstChild;
                    }
                    return route;
                }),
                filter((route) => route.outlet === 'primary')
            )
            .subscribe((route: ActivatedRoute) => {
                let seo = route.snapshot.data['seo'];

                if (route.snapshot.data.post) {
                    const post = route.snapshot.data.post;
                    seo = {
                        title: 'Journal - ' + post.meta_title,
                        description: post.meta_description,
                        image: post.feature_image,
                        published: post.published_at,
                        modified: post.updated_at,
                        author: post.primary_author.name,
                        url: API_URL + '/journal/' + post.slug,
                    };
                }

                const jsonLd = {
                    name: seo.title,
                    url: API_URL + this.router.routerState.snapshot.url,
                };
                this.jsonLdService.setData('Website', jsonLd);
                this.seoService.setData(seo);
                this.seoService.setCanonicalUrl(API_URL + this.router.url);
            });
    }

So this line **this.seoService.setData(seo);**  is setting meta tags which looks like this:

    public setData(data: SeoSocialShareData): void {
        this.setSection(data.section);
        this.setKeywords(data.keywords);
        this.setTitle(data.title);
        this.setType(data.type);
        this.setDescription(data.description);
        this.setImage(data.image);
        this.setUrl(data.url);
        this.setPublished(data.published);
        this.setModified(data.modified);
        this.setAuthor(data.author);
    }

Basically, meta tags are only visible if they are from routing configuration where i define things for static pages like home, services, contact etc. which looks like thiis:

      {
                path: 'services',
                component: ServicesComponent,
                data: {
                    animation: 'services',
                    seo: {
                        title: META_VALUES.routes['/services'].title,
                        description:
                            META_VALUES.routes['/services'].description,
                        keywords: META_VALUES.routes['/services'].keywords,
                        image: META_VALUES.routes['/services'].image,
                        url: API_URL + '/services',
                        type: META_VALUES.routes['/services'].type,
                        author: META_VALUES.routes['/services'].author,
                    },
                },
            },

Is there any way to get data from server in routing configuration with resolver, fill seo object with post data, I believe then meta tags will be available?

**Comment by sameretto** [comment]
have you figured out a way for this?

**Comment by CaerusKaru** [comment]
This is far from a minimal reproduction, and doesn't look like an issue with Angular Universal. Better avenues for support with this would be StackOverflow or Gitter.
