### ISSUE TITLE
there is no way to debug when running with ssr-dev-server

### ISSUE THREAD

**Issue by hakobpogh** [angular/universal#1624]
Hi there. Before angular v9 I was using the nodemon for running ssr in dev environment but after the v9 I've switched to use `@nguniversal/builders:ssr-dev-server`. And now I'm unable to debug the server or ssr code.

Is there any way I can pass any argument to @nguniversal/builders:ssr-dev-server to make it run in the inspect mode?

It'll be better to see it there.

**Comment by alan-agius4** [comment]
That’s seems like an oversight. Thanks for pointing this out.


I’ll look at this in a the coming days

**Comment by tincho-despegar** [comment]
Any news on this? It would be nice to be able to debug with vscode. Thanks !

**Comment by luchopcerra** [comment]
Same happens to me !! it would be nice to have a guideline to proper config debug settings for node code, having universal as engine.

**Comment by Andrurodr** [comment]
Same issue !

**Comment by phihochzwei** [comment]
+1

**Comment by tincho-despegar** [comment]
Hi @alan-agius4 !! How are you?? I would like to know if you have an example of how to configure the VSCode debugger to run the app (`ng run my-app:serve-ssr`) in inspect mode. Thanks!!

**Comment by alan-agius4** [comment]
@tincho-despegar, here's the vs configuration needed.
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "Debug SSR Server",
            "port": 9229,
            "skipFiles": [
                "<node_internals>/**"
            ]
        }
    ]
}
```

To run the server application in inspect mode you can use the below;
```
yarn dev:ssr --inspect
```
