### ISSUE TITLE
when i run  command 'npm run serve:ssr' it gives me  a error that ' self is not defined at main.js' 

### ISSUE THREAD

**Issue by neeraj-kritivity** [angular/universal#1627]
ma pakage.json is 
{
    "name": "goblitz-frontend",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve --aot",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e",
        "compile:server": "webpack --config webpack.server.config.js --progress --colors",
        "serve:ssr": "node dist/server",
        "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
        "build:client-and-server-bundles": "ng build --prod && ng run goblitz-frontend:server:production --bundleDependencies all"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~8.1.2",
        "@angular/common": "~8.1.2",
        "@angular/compiler": "~8.1.2",
        "@angular/core": "~8.1.2",
        "@angular/forms": "~8.1.2",
        "@angular/platform-browser": "~8.1.2",
        "@angular/platform-browser-dynamic": "~8.1.2",
        "@angular/platform-server": "~8.1.2",
        "@angular/router": "~8.1.2",
        "@ctrl/ngx-emoji-mart": "^1.0.6",
        "@nguniversal/express-engine": "^8.1.1",
        "@nguniversal/module-map-ngfactory-loader": "8.1.1",
        "@syncfusion/ej2-angular-calendars": "^17.4.51",
        "@types/jquery": "^3.3.31",
        "express": "^4.15.2",
        "flv.js": "^1.5.0",
        "jquery": "^3.4.1",
        "moment": "^2.24.0",
        "ng2-material-dropdown": "^0.11.0",
        "ngx-chips": "^2.1.0",
        "ngx-owl-carousel": "^2.0.7",
        "ngx-select-dropdown": "^1.3.1",
        "ngx-socket-io": "^3.0.1",
        "ngx-toastr": "^11.2.1",
        "rxjs": "~6.4.0",
        "tslib": "^1.9.0",
        "underscore": "^1.9.2",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-builders/custom-webpack": "^8.4.0",
        "@angular-devkit/build-angular": "^0.803.8",
        "@angular/cli": "~8.1.2",
        "@angular/compiler-cli": "~8.1.2",
        "@angular/language-service": "~8.1.2",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/node": "~8.9.4",
        "codelyzer": "^5.0.0",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "postcss-import": "^12.0.1",
        "postcss-loader": "^3.0.0",
        "postcss-scss": "^2.0.0",
        "protractor": "~5.4.0",
        "tailwindcss": "^1.1.4",
        "ts-loader": "^5.2.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "typescript": "~3.4.3",
        "webpack-cli": "^3.1.0"
    }
}
![Screenshot (21)](https://user-images.githubusercontent.com/61724591/79630919-eff09e00-8172-11ea-9322-f94fa1737db9.png)

**Comment by alan-agius4** [comment]
Hi, seems like `flv.js` is not compatible to be executed on the server.
