### ISSUE TITLE
We are not allowed to hard code the server port

### ISSUE THREAD

**Issue by csbenjamin** [angular/universal#1628]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

In the server.ts file, if we edit the line
```typescript
const port = process.env.PORT || 4000;
```
to
```typescript
const port = 4000;
```
we get an error when we run
```shell
$ ng run my-app:serve-ssr
```

## 🔬 Minimal Reproduction
```
$ ng new my-app
$ cd my-app
$ ng add @nguniversal/express-engine
```
then edit the file `server.ts` as described above and try
```
$ ng run my-app:serve-ssr
```
## 🔥 Exception or Error
<pre><code>
connect ECONNREFUSED 127.0.0.1:44763
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.1
Node: 13.12.0
OS: linux x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@ngtools/webpack                  9.1.1
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
The ssr serve builder needs to provide a “known” port, by the means of the `PORT` environment variable, because of the browser syncing proxy.

You can provide your own port via the `—port` option, which can be set either in `angular.json` or command line.

**Comment by csbenjamin** [comment]
@alan-agius4  I think there could be a comment above that line in the auto generated server.ts file to prevent us to edit that line. It taken me several hours to discover that the problem was because I have edited that line. What do you think about that?

**Comment by alan-agius4** [comment]
We can add a comment! Important to point that the port environment variable is also used by hosting and cloud provides to provide their own port.
