### ISSUE TITLE
Get hostname on server

### ISSUE THREAD

**Issue by Mackao** [angular/universal#1632]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

I don't know, this is the first version I've used

### Description

It's not possible to get hostname when app is generated on server

## 🔬 Minimal Reproduction
`ng new foo`
`ng add @nguniversal/express-engine`
Change app.component.ts to:
<pre><code>import { Component, PLATFORM_ID, Inject, Optional } from '@angular/core';
import { Request } from 'express';
import { REQUEST } from '@nguniversal/express-engine/tokens';
import { isPlatformServer } from '@angular/common';
import * as urlParse from 'url-parse';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {

  constructor(
    @Inject(PLATFORM_ID) private platformId: Object,
    @Optional() @Inject(REQUEST) protected request: Request,
  ) { }

  ngOnInit() {
    if (isPlatformServer(this.platformId) && this.request.hostname === 'localhost' && this.request.headers.referer) {
      console.log('server 1: ' + urlParse(this.request.headers.referer).hostname);
    }
    if (isPlatformServer(this.platformId)) {
      console.log('server 2: ' + this.request.hostname);
    } else {
      console.log('browser: ' + window.location.hostname);
    }
  }
}
</code></pre>

Build the project to production:
`npm run build:ssr`

## 🔥 Exception or Error
On server I get this in the console:
"server 2: localhost"
And in the browser I get this:
"browser: foo.com" (just an example)
<pre><code>
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.7
Node: 10.13.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@nguniversal/builders             9.1.0
@nguniversal/common               9.0.2
@nguniversal/express-engine       9.0.2
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Comment by alan-agius4** [comment]
Hi,

Most likely you should check for x-forwarded-host

See:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host

**Comment by Mackao** [comment]
Hi @alan-agius4 , thank you for the tip, can you please point me in the direction on how to implement x-forwarded-host?
I really need this to work, my thought is to have one angular universal code to serve several domains
To make that work, I have to know what domain is calling the api on the initial load (on the server)
I hope this is going to be implemented in the universal repo in the future

**Comment by alan-agius4** [comment]
`x-forwarded-host` will be sent either by your load balance, CDN or proxy, depending were you put your domain routing logic.

From the application perspective, you'd need to change 
```
const host = this.request.hostname;
```

to 
```
const host = this.request['x-forwarded-host'] ?? this.request.hostname;
```

**Comment by Mackao** [comment]
I'm using IIS to host my application, and I run the application using:
`node main.js`
This give me a "dedicated" ip on localhost:4500
I then make an url rewrite in the IIS like so:
`http://localhost:4500/{R:1}`

I tried to run the code you provided in my angular application, but it only returns "localhost" 

Do I completely misunderstand what you mean?
