### ISSUE TITLE
clear build process

### ISSUE THREAD

**Issue by gilamran** [angular/universal#164]
Hi,
I'm trying to build your project and I'm getting too many errors... few examples:
* node.d.ts Duplicate identifier with the node.d.ts that comes with angular2 and the node.d.ts that you get from tsd.
* I'm always getting "modules/universal/server/src/render.ts(19,29): error TS2307: Cannot find module 'preboot'."

Can you gather the minimal information on how to build your project from 0? or maybe just note what each gulp tasks do?

Thanks!

**Comment by gdi2290** [comment]
The warnings are normal since it's a problem with Angular2 bundling node.js typings as well as node.js typings needed for the repo itself. The preboot module error is a problem with preboot not having a type definition which we need to write

**Comment by gdi2290** [comment]
@jeffwhelpley can you provide type info for `preboot`

**Comment by jeffwhelpley** [comment]
Yeah, I can fix this. Also, I think I had a solution for the node dupe ts files, but I can't remember off the top of my head. I will look into both these things tonight and get back to you.

**Comment by mcpDESIGNS** [comment]
Having the same issue as well (now that I finally got it to install everything)
Lots of duplicate identifier node.d.ts & the preboot.

Just a fyi :)

**Comment by gdi2290** [comment]
the duplicate identifier problem is with `angular2` requiring `node.js` and `browserify` requiring `node.js`

**Comment by gilamran** [comment]
The TypeScript node.d.ts issues are not showstoppers, but the preboot missing module is something that I can't even run the project without... it's not definitions missing, I can't run the project. when I run `gulp serve` I get:

`
Error: Cannot find module 'preboot'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
`

**Comment by wesleycho** [comment]
FWIW, there is https://github.com/angular/universal-starter for a starter pack - the preboot issue does need to be fixed though.

**Comment by gilamran** [comment]
@wesleycho thanks that will help, but I'm asking this because I wanted to become a contributor... Without the ability to compile/understand what's going on. no one can...

**Comment by mcpDESIGNS** [comment]
@gilamran I believe @jeffwhelpley is working on creating something to fix the `Cannot find module 'preboot'.` issues.

I'm sure soon enough we'll be able to contribute!

**Comment by jeffwhelpley** [comment]
yes, that is literally the next thing on my list that I am trying to get to today. will provide update later tonight.

**Comment by jeffwhelpley** [comment]
These issues should be fixed with my latest PR.
