### ISSUE TITLE
How to deploy the latest Angular Universal on azure App Service?

### ISSUE THREAD

**Issue by hysnyasir** [angular/universal#1653]
Hi,
I have to deploy my application on azure and after executing npm run build:ssr.  Next I am deploying it to the Azure web app with .Net stack. I also set the path in the web.config which I found in the 
https://github.com/angular/universal/issues/1527. But after these change I am getting Internal Server Error. 
My web config is

<?xml version="1.0" encoding="utf-8"?>

<configuration>
  <system.webServer>
    
    <webSocket enabled="false" />
    <handlers>
      
      <add name="iisnode" path="server/main.js" verb="*" modules="iisnode"/>
    </handlers>
    <rewrite>
      <rules>
        
        <rule name="NodeInspector" patternSyntax="ECMAScript" stopProcessing="true">
          <match url="^server/main.js\/debug[\/]?" />
        </rule>

        
        <rule name="StaticContent" stopProcessing="true">
          <match url="^login/*"></match>
          <action type="Rewrite" url="manage/index.html"/>
        </rule>

        <rule name="StaticContent2" stopProcessing="true">
          <match url="^manage/*"></match>
            <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
          </conditions>
          <action type="Rewrite" url="manage/index.html"></action>
        </rule>

        <rule name="StaticContent3" stopProcessing="false">
         <match url="^((?!manage).)*$"></match>
         <action type="Rewrite" url="public{{REQUEST_URI}}"/>
        </rule>

        
        <rule name="DynamicContent">
          <match url="^(?!.*login).*$"></match>
          <conditions>
            <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true"/>
          </conditions>
          <action type="Rewrite" url="server/main.js"/>
        </rule>
      </rules>
    </rewrite>

    
    <security>
      <requestFiltering>
        <hiddenSegments>
          <remove segment="bin"/>
        </hiddenSegments>
      </requestFiltering>
    </security>

    
    <httpErrors existingResponse="PassThrough" />

    
    
  </system.webServer>
</configuration>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
