### ISSUE TITLE
Error after updating to angular 9 | keeps crashing | memory consumption

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#1660]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

After upgrading to version 9 of the angular, I am no longer able to generate build.
High memory consumption.
Locks the build operation.

How to solve problems and be able to compile, because I'm currently stuck, unable to upload new resources, because I can't generate build

I even thought it could be something related to Angular universal https://github.com/angular/universal/issues/1658, but I'm not sure, because I'm in the build process.

## 🔥 Exception or Error
The compilation is consuming a lot of memory and reaches 92% of the image below and does not come out of it.
And before upgrading to version 9, everything worked, so something tells me that it may be related to the files that will be modified.
If you can tell me how the files would look, because the way they were, it’s not working

![Captura de Tela_20200503181411](https://user-images.githubusercontent.com/11314585/80957678-0ab14c80-8dda-11ea-8b8a-affd4c584e8b.png)

if I test it in development, it stays at 10% and it doesn't go away.
Problem I have no way of knowing if something is wrong or what is wrong.
![Captura de Tela_selecionar área_20200504103420](https://user-images.githubusercontent.com/11314585/80971040-8f0fc980-8df2-11ea-9f83-cf9e6d9ea4c8.png)

about the memory consumption part, I'm having to put **node --max_old_space_size = 6072 ./node_modules/@angular/cli/bin/ng ...** because before that I had the following errors:
![Captura de Tela_selecionar área_20200504110759](https://user-images.githubusercontent.com/11314585/80974575-49093480-8df7-11ea-8e1b-356ffc19925d.png)

![Captura de Tela_selecionar área_20200504110812](https://user-images.githubusercontent.com/11314585/80974585-4c042500-8df7-11ea-87ac-88ea98f288d8.png)

## 🌍 Your Environment
```
Angular CLI: 9.1.4
Node: 10.15.3
OS: linux x64

Angular: 9.1.3
... animations, common, compiler, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@angular/cdk                       9.2.1
@angular/cli                       9.1.4
@angular/compiler-cli              9.1.4
@angular/flex-layout               9.0.0-beta.29
@angular/language-service          9.1.4
@angular/material                  9.2.1
@angular/material-moment-adapter   9.2.1
@ngtools/webpack                   9.1.4
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.4
@schematics/update                 0.901.4
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by GlauberF** [comment]
@alan-agius4 right, before I try here.
In order to proceed with the build, did you remove the * custom webpack builder * and keep the standard of the angular team cli?

**Comment by alan-agius4** [comment]
@GlauberF, both of them ended up having the same result. Though the custom webpack did take slightly more time.

**Comment by GlauberF** [comment]
what is the exact version of your node and npm, updated to v12.16.3 and npm 6.14.4 and now even the npm run serves does not work perfectly.

it gets stuck, it takes time.
An example, with serving running, I edited a file, it starts recompiling, but does not end.
Look this is very complicated, it may be the node or npm the problem, so ask for the version you are using for me to do more tests.

I even updated my angle back to ~ 9.1.1, see my updated package: https://gist.github.com/GlauberF/79c30f7e3e1e4016824d50e973249330


```
Angular CLI: 9.1.4
Node: 12.16.3
OS: linux x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.4
@angular-devkit/build-angular      0.901.4
@angular-devkit/build-optimizer    0.901.1
@angular-devkit/build-webpack      0.901.4
@angular-devkit/core               9.1.4
@angular-devkit/schematics         9.1.4
@angular/cdk                       9.1.3
@angular/flex-layout               9.0.0-beta.29
@angular/material                  9.1.3
@angular/material-moment-adapter   9.1.3
@ngtools/webpack                   9.1.4
@nguniversal/builders              9.1.0
@nguniversal/common                9.1.0
@nguniversal/express-engine        9.1.0
@schematics/angular                9.1.4
@schematics/update                 0.901.4
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
```

**Comment by GlauberF** [comment]
I'm closing the problem, because after several tests, I came up with several local problems and one of them was the version of nodejs.
Thanks @alan-agius4  for the help.
