### ISSUE TITLE
Render content of pop-up from server side in Angular 7 SSR

### ISSUE THREAD

**Issue by umairjameel1** [angular/universal#1662]
I am using Angular 7 and I have a list of products. When I click on each product, new route gets triggered and url becomes dynamic like {{host}}/product/:id. After clicking on a product, pop-up opens up and show the data on it (data gets generated from an api call). I want to render this data from server side. Is it possible to render api response data from server side which shows up on a pop-up?

Note: Not just the api data, but static content (on popup) is also not being rendered from server side. It works on normal routes but not working on pop-ups. Is it like, we can't render pop-up data from server side?

**Comment by CaerusKaru** [comment]
Hello, this issue tracker is not the correct forum for support requests. Better options include StackOverflow and Gitter.
