### ISSUE TITLE
express-engine respect the base href

### ISSUE THREAD

**Issue by alfaex** [angular/universal#1663]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description

When building angular with SSR, my lack of knowledge of express made me spend two or probably more days searching for why the app breaks when I follow the documentation for using. `base href` (the base tag on the docs) with SSR

I end up finding a medium post showing that I need to mount the specific path using `app.use()` 

example:
```typescript
	server.use('/my/app', customBaseHREF())

	function customBaseHREF(){
		const router = express.Router()
		
			// Serve static files from /browser
			router.get('*.*', express.static(distFolder, {
			maxAge: '1y'
		}));

		// All regular routes use the Universal engine
		router.get('*', (req, res) => {
			res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
		});

		return router
	}
```

### Describe the solution you'd like

As I understand I have three strategies to use base href.

 1. index.html inserting the `<base href="/my/app/">`
 2. On appmodule with `providers: [{ provide: APP_BASE_HREF, useValue: '/my/app/' }],`
 3. On angular.json with `"baseHref": "/my/app/",` on the build.configuration.[build name]

So if is possible, the file `server.ts` should 'know' which strategy was used and mount the path for the express server

Another thing that came to my mind was using the `fileReplacements` options, but since this is angular related, I don't know if would work for the building of the express server, so I could use the correct file for the step that I'm building, stage, feature, prod.

### Describe alternatives you've considered

At the moment, when I need to send a version to the 'boss' for review I uncomment the the express mounted path 😆 to do jenkins and stuff. And while i'm developing I comment the mounted path because on my machine I don't need.

**Comment by CaerusKaru** [comment]
Can you provide a link to the Medium post? I find it hard to believe that none of the three options you provided work correctly.
