### ISSUE TITLE
Selective SSR?

### ISSUE THREAD

**Issue by marcoripa96** [angular/universal#1667]
I'm new to Angular Universal and I'm trying to understand what's the best approach for SSR. I set up Angular Universal in my application and it's rendering server side all routes. By watching guides and reading articles, this isn't always the best solution in fact if the pages have a lot of content (HTML, CSS) SSR could overload my server.
What I want to do is doing some sorts of selective SSR. For X pages I want to render a component which is different from the component in the route the user requested (and this component will show only the essential of the page, maybe toolbar, navbar and footer. I want to use the same component for all the pages sharing the same layout). If the layout changes, a different component (and always a simplified version of the full page) will be rendered during server side. Would this be a good approach? If so, can I have some help clearing my thoughts out theoretically and practically.

**Comment by CaerusKaru** [comment]
Hello, this issue tracker is not the correct forum for support requests. Better options include StackOverflow or Gitter.
