### ISSUE TITLE
Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1670]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

<--- Last few GCs --->

[237840:0000029FB4CC4C40]   281470 ms: Mark-sweep 1331.3 (1453.8) -> 1321.9 (1457.3) MB, 3742.7 / 0.0 ms  (average mu = 0.097, current mu = 0.048) allocation failure scavenge might not succeed
[237840:0000029FB4CC4C40]   284506 ms: Mark-sweep 1335.2 (1457.3) -> 1326.1 (1457.3) MB, 2885.5 / 0.0 ms  (average mu = 0.074, current mu = 0.049) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000000D5138DC5C1]
Security context: 0x01af6e61e6e9 <JSObject>
    1: _(aka _) [0000033529102201] [C:\git-angular\ICC\Server\AuraLiteOnline\PwC.Aura.Online\node_modules\terser-webpack-plugin\node_modules\terser\dist\bundle.min.js:~1] [pc=000000D515B25DD6](this=0x02b3515826f1 <undefined>,n=0x013bb58a2bb9 <String[4]: punc>,i=0x02b351586629 <String[1]: .>,o=0x02b3515826f1 <undefined>)
    2: arguments adaptor frame: 2->3...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF7E490C6AA v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF7E48E7416 node::MakeCallback+4534
 3: 00007FF7E48E7D90 node_module_register+2032
 4: 00007FF7E4C0189E v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF7E4C017CF v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF7E4DE7F94 v8::internal::Heap::MaxHeapGrowingFactor+9620
 7: 00007FF7E4DDEF76 v8::internal::ScavengeJob::operator=+24550
 8: 00007FF7E4DDD5CC v8::internal::ScavengeJob::operator=+17980
 9: 00007FF7E4DE6317 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF7E4DE6396 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF7E4F10637 v8::internal::Factory::NewFillerObject+55
12: 00007FF7E4F8DCD9 v8::internal::operator<<+74697
13: 000000D5138DC5C`enter code here`1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.4
Node: 12.16.3
OS: win32 x64

Angular: 9.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/localize                 9.1.5
@angular/platform-server          9.1.5
@ngtools/webpack                  9.1.4
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
