### ISSUE TITLE
Error Adding Universal: "Invalid rule result instance of class promise"

### ISSUE THREAD

**Issue by ImTung** [angular/universal#1671]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
### Description

 
- Trying to remove node_modules, package-lock, and update latest version.
## 🔬 Minimal Reproduction
- ng add @nguniversal/express-engine

## 🔥 Exception or Error
<pre><code>
Invalid rule result: Instance of class Promise.
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.5
Node: 12.16.1
OS: darwin x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              7.3.10
@angular-devkit/schematics        7.3.10
@angular/cdk                      9.2.3
@angular/cli                      9.1.5
@angular/material                 9.2.3
@ngtools/webpack                  9.1.5
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by CaerusKaru** [comment]
Probably has something to do with the fact that you're using outdated `@angular-devkit` dependencies. Can you upgrade and try again?

**Comment by ImTung** [comment]
> Probably has something to do with the fact that you're using outdated `@angular-devkit` dependencies. Can you upgrade and try again?

`@angular-devkit` is latest version, also when I run `npm outdated` I got the result:

```
Package                           Current  Wanted  Latest  Location
inquirer                            6.5.2   6.5.2   7.1.0  chatorder
karma-coverage-istanbul-reporter    2.1.1   2.1.1   3.0.2  chatorder
```

**Comment by CaerusKaru** [comment]
```bash
@angular-devkit/schematics@9.1.5 | MIT | deps: 3 | versions: 296
Angular Schematics - Library
https://github.com/angular/angular-cli
```

**Comment by ImTung** [comment]
> ```shell
> @angular-devkit/schematics@9.1.5 
> ```

Wow, Thank you so much. I don't know required `@angular-devkit/schematics`.
