### ISSUE TITLE
enableProdMode once

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#168]
we need to ensure enableProdMode happens only once

**Comment by wesleycho** [comment]
I could take a look at this

**Comment by alexpods** [comment]
We can't set [`_modeLocked`](https://github.com/angular/angular/blob/2.0.0-beta.1/modules/angular2/src/facade/lang.ts#L50) flag to `false` after it was set to `true` (at least now). 
Also `enableProdMode` doesn't have any sense for render engine. It's dynamic option. What should we do if user passes `true` for one request and `false` for another? 

I think we should just revert [this commit](https://github.com/angular/universal/commit/a1c39bf26cdd644a7baba5efd3eeefd8b65eb60f) and allow user to control prod/dev mode just by using `angular/core` API directly:

```js
import * as express from 'express';
import { enableProdMode } from 'angular2/core';
import { ng2engine } from  'angular2-universal-preview';
import { App } from '../app/App.ts';

enableProdMode(); // <= Like this

export const app = express();
app.engine('html', ng2engine);
app.get('/', (req, res) => res.render('index.html', { App, providers: [] }));
```

**Comment by gdi2290** [comment]
@alexpods has a good point, there is no reason for us to configure it. If someone can make a pull-request to revert it then that would be awesome.

**Comment by alexpods** [comment]
@gdi2290 Done #186

**Comment by gdi2290** [comment]
@wesleycho if you're working on this we decided not to include prod mode as an option

**Comment by wesleycho** [comment]
Didn't get a chance to look into it yet, so sounds good to me :)
