### ISSUE TITLE
ChunkLoadError: Loading chunk 39 failed.

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#1683]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

![image](https://user-images.githubusercontent.com/23710467/81806031-75872400-954e-11ea-8585-91569f3c32cb.png)
ChunkLoadError: Loading chunk 49 failed.
(error: https://addons-amo.cdn.mozilla.net/amo-i18n-pl-5895ff0e3199834fe71a.js)
  at location (./src/locale/fr/amo.js?0bc5:7:1)
  at __webpack_require__ (./src/amo/components/LanguagePicker/index.js:36:28)
  at e/< (./src/amo/components/LanguagePicker/index.js:36:13)
  at G (./src/amo/utils/errors.js:14:14)
  at a (./src/amo/components/LanguagePicker/index.js:57:14)
...
(16 additional frame(s) were not displayed)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.5
Node: 12.16.3
OS: win32 x64

Angular: 9.1.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router      
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.5
@angular-devkit/build-angular     0.901.5
@angular-devkit/build-optimizer   0.901.5
@angular-devkit/build-webpack     0.901.5
@angular-devkit/core              9.1.5
@angular-devkit/schematics        9.1.5
@angular/cli                      9.1.5
@ngtools/webpack                  9.1.5
@nguniversal/builders             9.1.0
@nguniversal/common               9.1.0
@nguniversal/express-engine       9.1.0
@schematics/angular               9.1.5
@schematics/update                0.901.5
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
