### ISSUE TITLE
Universal 5 Min QuickStart

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#169]
It would be great to have a 5 minute quickstart writeup for Ng2Universal

**Comment by thomasjosephgreco** [comment]
@gdi2290 I can definitely put something together for this and would love to help out. I just got up and running with universal so i'm going to be poking around a bit taking note of different things. 

Do you think it would be solid if I provided a basic tutorial on using gulp and explained a little bit about the file structure and addition technologies being used?

**Comment by jeffwhelpley** [comment]
@thomasjosephgreco I am in the process of folding all documentation efforts into our one combined effort to get everything up on angular.io. This will be tracked as part of #258. I will ping you once we have the outline up and we just need people to help fill out the details. Until that point, everything we have so far is going to get dumped into this temporary doc:

https://docs.google.com/document/d/1Qem6PJ1EO5tYpGxfpj5w-4kuykW072GCrC3FmWI3_yY/edit?usp=sharing
