### ISSUE TITLE
Window is undefined 

### ISSUE THREAD

**Issue by mshahzebedu** [angular/universal#1695]
Hi 
while i am working with angular universal and trying to build the project the build complete  but when i serve application server side it show error that "window is undefined" first showing about local storage but by installing package and importing local storage error gone but next window is undefined error rise i am trying a lot but it not resolving .
Please guide me how can i handle this error .
thanks

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
