### ISSUE TITLE
add performance benchmarking

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#170]
We should make an Angular 2 example for an initial benchmark comparison from the community
1mb json and 1000 items
react:                  1250 ms
react prod opt:  650 ms
hogan:                450 ms
mustache:          30 ms
https://github.com/ndreckshage/react-boston-ssr

**Comment by gdi2290** [comment]
@alexpods you asked about this during the meeting. It would be great if you can take this on with your starter

**Comment by alexpods** [comment]
@gdi2290 Yeah, I take this one.

**Comment by jeffwhelpley** [comment]
hey, so what are we going to use to record the benchmarks? if we are trying to use benchpress, we should probably merge this with #135.

**Comment by alexpods** [comment]
@jeffwhelpley I've never used benchpress before and I'm not quite sure that we need to use kind of "e2e benchmark" tool. So I need to make some experiments with several different tools. 

1. **ab**, which is used in the `react-boston-ssr`. I'm going to make a fork of this repo and add angular2 universal example there.
2. Make some experiments with **benchpress**. As a result maybe integrate it into my starter or angular/universal-starter.
3. I think our main "competitor" is React. So it will be very useful to compare `React.renderToString` vs angular2 universal `renderToString`. I'm going to use **benchmark.js** here.

**Comment by jeffwhelpley** [comment]
Yeah, that is cool. Let's leave the benchpress metrics to #135 since that involves a lot more. Let's first get some timings with benchmark.js and compare to react. We will do benchpress afterwards.

**Comment by alexpods** [comment]
Today morning I had some free time. So I've spend it to add `angular2` example to `react-boston-ssr` (see it [here](https://github.com/alexpods/ssr-comparison/tree/master/6-angular2-ssr)). Here is the result for my computer:

```bash
> cd 2-react-ssr
> NOD_ENV=production node server.js &
> ab -n 40 http://localhost:3000/

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        4840884 bytes

Concurrency Level:      1
Time taken for tests:   60.824 seconds
Complete requests:      40
Failed requests:        31
   (Connect: 0, Receive: 0, Length: 31, Exceptions: 0)
Total transferred:      194656531 bytes
HTML transferred:       194648371 bytes
Requests per second:    0.66 [#/sec] (mean)
Time per request:       1520.606 [ms] (mean)
Time per request:       1520.606 [ms] (mean, across all concurrent requests)
Transfer rate:          3125.30 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0       0
Processing:  1470 1520  40.3   1510    1697
Waiting:     1466 1517  40.0   1506    1692
Total:       1470 1520  40.3   1510    1698

Percentage of the requests served within a certain time (ms)
  50%   1510
  66%   1536
  75%   1544
  80%   1550
  90%   1562
  95%   1569
  98%   1698
  99%   1698
 100%   1698 (longest request)


> cd 6-angular2-ssr
> NOD_ENV=production node server.js &
> ab -n 40 http://localhost:3000/

Server Software:        
Server Hostname:        localhost
Server Port:            3000

Document Path:          /
Document Length:        1683568 bytes

Concurrency Level:      1
Time taken for tests:   65.159 seconds
Complete requests:      40
Failed requests:        0
Total transferred:      67350880 bytes
HTML transferred:       67342720 bytes
Requests per second:    0.61 [#/sec] (mean)
Time per request:       1628.964 [ms] (mean)
Time per request:       1628.964 [ms] (mean, across all concurrent requests)
Transfer rate:          1009.42 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:  1336 1629 427.5   1448    3015
Waiting:     1334 1627 427.4   1446    3014
Total:       1336 1629 427.5   1448    3016

Percentage of the requests served within a certain time (ms)
  50%   1448
  66%   1468
  75%   1552
  80%   2091
  90%   2366
  95%   2867
  98%   3016
  99%   3016
 100%   3016 (longest request)

```

**Comment by gdi2290** [comment]
I have angular2, react-prod, and mustache generated from Alex's work https://gist.github.com/gdi2290/c460b7c72f8c4586eac0

**Comment by SynerG** [comment]
I'm not familiar with Angular Universal, just doing some research to consider it for upcoming projects. It seems that 1 req/sec is rather low for server-side performance.

Is it due to the complexity of the test used?
Otherwise, are there expected significant performance gains in the following months?  

This is an awesome project, but I still have no idea which performance can we expect from it.

**Comment by jeffwhelpley** [comment]
@SynerG a couple things. The 1 req/second is just a setting for the test and not a limitation. In general, though, don't take any metrics yet to mean anything. We are still trying to set up the appropriate controls to do a proper recording for the universal example code. Also, there are a series of upcoming changes that will have a dramatic effect on server side performance.

In short, I can't give you specific numbers now, but what I can tell you is that I managed to get my custom Angular 1 server rendering solution down to < 100ms response times and my single core AWS instances can easily handle ~1000 simultaneous users. Performance is a huge deal for me and we will eventually get Angular Universal to match or exceed my Angular 1 solution.

Check back in a month or so and we should have more defitive info for you

**Comment by SynerG** [comment]
@jeffwhelpley thank you very much for the comments, it looks very promising then.

One question: Is Angular Universal expected to include a cache and change detection algorithms? For instance, the first request of a url would be fully rendered and stored in the cache. For later requests, Angular Universal would check if bound data has changed and reuse the response from the cache (the complete previous rendered version or parts of it).

In that case, the x reqs/sec figure would be much less important in scenarios that can benefit from it. (For example, if we cheated and enabled the cache during the test :) 

Or the cache+change detection strategy is not expected for some reason? (So we should expect to re-render the whole page in every request)

**Comment by jeffwhelpley** [comment]
So, we do have a couple levels of caching on our roadmap including the something very similar to the one you are describing. The other major area for optimization will be in sharing data between the server and client via initial payload. In either case, though, it will be something configurable that you can adjust to suit your needs.

**Comment by jeffwhelpley** [comment]
I just changed the title for this. The key is adding benchmarking such that we can run it and record the results for each check in. This may or may not include benchpress or other tools.

**Comment by jeffwhelpley** [comment]
Actually, I am going to close this in favor of #135.
