### ISSUE TITLE
Reference Error Event is not defined 

### ISSUE THREAD

**Issue by bharatprj** [angular/universal#1701]
I added the domino for using window and document, window event and etc.But still throwing errror on serve:ssr --Reference Error Event is not defined

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-ssr`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
