### ISSUE TITLE
Refused to set unsafe header "Accept-Encoding"

### ISSUE THREAD

**Issue by RomanChygryn** [angular/universal#1702]
# 🐞 Bug report

Logs from ssr throws this error Refused to set unsafe header "Accept-Encoding"
I added "Accept-Encoding" header to all requests to enable gzip.
I did something wrong or it is a bug, or not supported by Universal?

**Comment by alan-agius4** [comment]
You cannot modify `Accept-Encoding` header programmatically.

See: https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name
