### ISSUE TITLE
Make Slack room for Universal

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#171]
It would be great to switch to Universal rather than gitter

**Comment by wesleycho** [comment]
This looks finished, probably could be closed now.

**Comment by manekinekko** [comment]
@jeffwhelpley did you send the invitations ?

**Comment by jeffwhelpley** [comment]
OK, I have the slack room set up and I think I sent out the invites to everyone. I am going to close this issue, but if someone else wants to get invited you can either ping me here, on gitter or twitter.
