### ISSUE TITLE
refactor NodeImpl into a separate file

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#172]
NodeImpl should live inside platform/

**Comment by dbabaioff** [comment]
I can take this one.. @gdi2290 Can you clarify the issue?

**Comment by gdi2290** [comment]
@dbabaioff  can you move NodeImpl into a separate file next to node.ts as xhr_node_impl.ts and rename it as XhrNodeImpl

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/287b293dbdab13553cbbbcf2e76220d32f75795f
