### ISSUE TITLE
Websockets with SSR concerning the Express server and the client

### ISSUE THREAD

**Issue by xtianus79** [angular/universal#1724]
I know t[here is this thread](https://github.com/angular/universal/issues/846) that touches on the subject regarding socket.io and the client side but my issue I believe and don't know if that's 100% true is coming from the server side of the express application. 

The thread, while there is a lot of good information in there but to an incoming onlooker seems convoluted and lost in it's overall projection of the issue and or a solution. 

What I am trying to accomplish is having a real-time data connection from the database to the client. The idea is to use a traditional websocket on the express server that would connect to a front-end client websocket api to maining a connection on that route. 

I am not sure if SSR and Angular do something already to address the connection to the server but A. How can I achieve a websocket like connection to a data source using Angular Universal via SSR? 

Also, kind of the first issue I am having is the ability to know if I am able to create a websocket at all on the Express server.  Specifically, I use express-ws and try to setup a websocket /echo on the server. Then I go the browser and test in the console let test = new Websocket('ws://..') and it says can't connect error. This is why I am think the server is not hosting the websocket properly. Am I wrong in that thinking?

**Comment by xtianus79** [comment]
I put a bounty on it. 
https://stackoverflow.com/questions/62293771/is-there-anyway-to-use-the-websockets-with-express-ws-and-the-websocket-client-a

**Comment by CaerusKaru** [comment]
StackOverflow issues do not belong on this issue tracker. Please limit your discussion to that forum.
