### ISSUE TITLE
Expose CommonEngine

### ISSUE THREAD

**Issue by VagrantAI-c** [angular/universal#1733]
# Proposal

#### What is the summary of the proposal?
Expose `CommonEngine` without theta prefix

#### What is the proposal?
`CommonEngine` is a good way to start making integrations with other web servers like fastify (since express is [considered slower](https://www.techempower.com/benchmarks/#section=data-r19&hw=ph&test=composite&p=zik0zj-zijocf-zik0zj-zik0zj-v) that almost any other node web server), but using it with theta prefix makes developers think of unstable API inside. Is `CommonEngine` API ready to be exposed? Are there any plans for publishing it within `@nguniversal/common/engine` subpackage?

**Comment by invaderb** [comment]
Is there any update on this? I've looked through the other tickets asking either for a fastify engine or opening up the common engine and all of them are a couple years old now.

**Comment by VagrantAI-c** [comment]
It is currently exposed right now, one can use it via `import { CommonEngine } from '@nguniversal/common/engine';`
