### ISSUE TITLE
Upgrading angular from 8 to 9, There are warning message and serve angular universal loading to infinite

### ISSUE THREAD

**Issue by mohamedaboelmagd** [angular/universal#1737]
# 🐞 Bug report

### Command 

> ng run badgewell:server:dev
....
WARNING in ./node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression

> node dist/server 
It successes in console to open localhost:4000
but nothing load in browser it's always loading without response.

### Is this a regression?
It worked with angular 8 but didn't with angular 9

 Yes, the previous version in which this bug was not present was: ....

### Description
That's all dependencies
"dependencies": {
    "@agm/core": "^1.0.0-beta.6",
    "@angular/animations": "~9.1.9",
    "@angular/cdk": "~9.2.4",
    "@angular/common": "~9.1.9",
    "@angular/compiler": "~9.1.9",
    "@angular/core": "~9.1.9",
    "@angular/fire": "^6.0.0",
    "@angular/forms": "~9.1.9",
    "@angular/material": "~9.2.4",
    "@angular/platform-browser": "~9.1.9",
    "@angular/platform-browser-dynamic": "~9.1.9",
    "@angular/platform-server": "~9.1.9",
    "@angular/router": "~9.1.9",
    "@bugsnag/js": "^7.1.1",
    "@bugsnag/plugin-angular": "^7.1.1",
    "@ngrx/effects": "~9.2.0",
    "@ngrx/entity": "~9.2.0",
    "@ngrx/router-store": "~9.2.0",
    "@ngrx/store": "~9.2.0",
    "@ngrx/store-devtools": "~9.2.0",
    "@nguniversal/common": "^9.1.1",
    "@nguniversal/express-engine": "9.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.2.6",
    "@ngx-loading-bar/core": "^4.2.0",
    "@ngx-loading-bar/router": "^4.2.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@swimlane/ngx-charts": "^14.0.0",
    "@types/faker": "^4.1.8",
    "@zxing/ngx-scanner": "^3.0.0",
    "angular-google-charts": "^0.1.6",
    "angular-shepherd": "^0.6.0",
    "angularx-qrcode": "^2.1.0",
    "echarts": "^4.2.1",
    "express": "^4.15.2",
    "faker": "^4.1.0",
    "firebase": "^7.1.0",
    "moment": "^2.24.0",
    "ng-connection-service": "^1.0.4",
    "ngx-color-picker": "^9.1.0",
    "ngx-echarts": "^5.0.0",
    "ngx-google-analytics": "^8.0.0",
    "ngx-order-pipe": "^2.0.2",
    "ngx-pagination": "^5.0.0",
    "ngx-permissions": "^7.0.3",
    "ngx-stripe": "^9.0.2",
    "rxjs": "^6.5.0",
    "tslib": "^2.0.0",
    "vis": "^4.21.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.901.8",
    "@angular/cli": "^9.1.8",
    "@angular/compiler-cli": "~9.1.9",
    "@angular/language-service": "~9.1.9",
    "@types/jest": "^25.2.3",
    "@types/node": "~14.0.12",
    "bufferutil": "^4.0.1",
    "codelyzer": "^5.0.0",
    "css-star-rating": "^1.2.4",
    "domino": "^2.1.4",
    "jasmine-marbles": "^0.6.0",
    "jest": "^26.0.1",
    "jest-canvas-mock": "^2.2.0",
    "jest-preset-angular": "^8.2.0",
    "rxjs-tslint": "^0.1.7",
    "ts-loader": "^7.0.5",
    "ts-node": "~8.10.2",
    "tslint": "~6.1.2",
    "typescript": "^3.6.5",
    "utf-8-validate": "^5.0.2",
    "webpack": "^4.42.1",
    "webpack-bundle-analyzer": "^3.3.2",
    "webpack-cli": "^3.1.0",
    "ws": "^7.2.0",
    "xhr2": "^0.2.0"
  }

## 🔥 Exception or Error

> ng run badgewell:server:dev
....
WARNING in ./node_modules/encoding/lib/iconv-loader.js 9:12-34
Critical dependency: the request of a dependency is an expression

**Comment by alan-agius4** [comment]
The warning seems to be coming due to the following statement https://github.com/andris9/encoding/blob/91ae950aaa854a119122c27cdbabd8c5585106f7/lib/iconv-loader.js#L9

Were the require is an expression.

Try to not bundle the `encoding` package using the `externalDependencies` option under the server builder.

**Comment by mohamedaboelmagd** [comment]
> externalDependencies

what is value for `externalDependencies` ?

**Comment by alan-agius4** [comment]
`externalDependencies: [“encoding”]`

**Comment by mohamedaboelmagd** [comment]
@alan-agius4 
> node dist/server

/home/mohamed/Desktop/careerograph/web/dist/server/main.js:22664
            throw err;
            ^

Error: ENOENT: no such file or directory, open 'google/protobuf/api.proto'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at fetch (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:22732:34)
    at Root.load (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:22766:13)
    at Root.loadSync (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:22807:17)
    at Object.loadSync (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:94455:17)
    at Object.8ZNE (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:67338:37)
    at __webpack_require__ (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:26:30)
    at Object.BYZf (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:71277:19)
    at __webpack_require__ (/home/mohamed/Desktop/careerograph/web/dist/server/main.js:26:30) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: 'google/protobuf/api.proto'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! badgewell@0.0.0 serve:ssr: `node dist/server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the badgewell@0.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mohamed/.npm/_logs/2020-06-17T15_16_33_483Z-debug.log

**Comment by kgajera** [comment]
For `@angular/fire`, you also need to add `@firebase/firestore` to  `externalDependencies`:

`externalDependencies: ["@firebase/firestore", "encoding"]`

**Comment by mohamedaboelmagd** [comment]
when I serve server-side rendering, the angular app is loading to infinite

**Comment by tskweres** [comment]
@mohamedaboelmagd  same issue

**Comment by mohamedaboelmagd** [comment]
I uninstall angular universal and upgrade the angular app to 9 then reinstall angular universal 
moved to this issue
https://github.com/angular/universal/issues/1748

**Comment by GlauberF** [comment]
I've been in this fight for a long time and there is no solution for the issue. https://github.com/angular/universal/issues/1711

**Comment by SyedUmerHasan** [comment]
I have found a solution that works with my case, you can also try 
please have a look, I tried by closing Ivy compiler in angular 10 it works perfectly 
https://github.com/angular/universal/issues/1711#issuecomment-675303074

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the issue.
