### ISSUE TITLE
It takes more time to load client side page

### ISSUE THREAD

**Issue by Bizotics-Dev** [angular/universal#1746]
Here we used lazyload module structure in angular 7.When page load it first render ssr page after that it takes more time to load client side page.How we remove this time span?

**Comment by alan-agius4** [comment]
I'm sorry, but we don't understand the problem you are reporting.

If the problem persists, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by Bizotics-Dev** [comment]
@alan-agius4 kindly check this issue reproduced earlier https://github.com/angular/universal/issues/1164#issue-445886900
