### ISSUE TITLE
Import undefined on server side, but available client side

### ISSUE THREAD

**Issue by tskweres** [angular/universal#1749]
I'm using ngeohash for geohashing with Angular SSR. I'm finding that when I import it at the top of my global service, ngeohash is unavailable on the server side, but exists client side:

`import geohash from 'ngeohash';
`

Server side:
`const geoHash = geohash.encode(lat, lng);`
Error, geohash undefined

Client side:
works great!

**Comment by alan-agius4** [comment]
@tskweres, thanks for reporting this issue.

The issue template is non optional as it help us tin triaging issues in a more efficient and meaningful way. Kindly open a new issue and provide all the requested information.

Thank you for your cooperation.
