### ISSUE TITLE
Universal support for proxy.conf.json

### ISSUE THREAD

**Issue by Trysor** [angular/universal#1757]
# 🚀 Feature request

#### What modules are relevant for this feature request?
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [x] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
Using Angular CLI, one is able to use a file (namely proxy.conf.json) and name this as proxyConfig in dev-server target options of angular.json, or as a parameter to ng serve.

### Describe the solution you'd like
It would be preferable to have proxyConfig as an available option for ssr-dev-server as well.

### Describe alternatives you've considered
Three main workarounds spring to mind;
1) Routing middleware which redirects the request in the server.ts file
2) HTTP Interceptor
3) environment variable

However, all three requires changes to code. There is a reason the proxyConfig exists for dev-server; the same reasons could be applied for ssr-dev-server.

**Comment by imran3** [comment]
Any update on this?

**Comment by materazu** [comment]
+1

**Comment by cbernth** [comment]
+1

**Comment by lennybakkalian** [comment]
+1
