### ISSUE TITLE
No NgModule metadata found for 'AppServerModule' when importing AppServerModule from compiled SSR app

### ISSUE THREAD

**Issue by AlabasterAxe** [angular/universal#1759]
For more context see this issue: https://github.com/angular/universal/issues/1363

It's not possible to import the AppServerModule from the compiled SSR app and register the ssr handlers on another Express app.

When you do this and attempt to visit the app it displays the above error: No NgModule metadata found for 'AppServerModule'

See this repository for a minimal reproduction and steps to reproduce: https://github.com/AlabasterAxe/ng-universal-test 

I tried to change my Angular tsconfig.json to "emitDecoratorMetadata": true but it didn't have any effect.

Thanks!

Matt

**Comment by dnikomon** [comment]
Same issue here. I use import statement it actually says it doens't have exported member `AppServerModuleNgFactory` or `LAZY_MODULE_MAP`

**Comment by alan-agius4** [comment]
@AlabasterAxe, this is because in your server.ts file you are using Angular deps, yet this file is not being bundled with the rest of the application.

What you need to do is to export `ngExpressEngine`, `APP_BASE_HREF` etc... from the `main.server.ts` and used the exported symbols in server.ts.

**Comment by Teebo** [comment]
@alan-agius4 that does not work
