### ISSUE TITLE
Unable to make http during SSR

### ISSUE THREAD

**Issue by lightbulb112** [angular/universal#1761]
@angular version: ~9.1.9
"@nguniversal/express-engine": "^9.1.1",
"express": "^4.15.2",

When I "ng serve" everything is fine. When I "npm run dev:ssr" I am getting the following error in the console during http call:

> ERROR HttpErrorResponse {
>   headers: HttpHeaders {
>     normalizedNames: Map {},
>     lazyUpdate: null,
>     headers: Map {}
>   },
>   status: 0,
>   statusText: 'Unknown Error',
>   url: 'https://localhost/webapi/Weather/GetWeatherForecast',
>   ok: false,
>   name: 'HttpErrorResponse',
>   message: 'Http failure response for https://localhost/webapi/Weather/GetWeatherForecast: 0 Unknown Error'
>   error: ProgressEvent {
>     type: 'error',
>     target: XMLHttpRequest {
>       onloadstart: null,
>       onprogress: null,
>       onabort: null,
>       onerror: null,
>       onload: null,
>       ontimeout: null,
>       onloadend: null,
>       _listeners: [Object],
>       onreadystatechange: null,
>       _anonymous: undefined,
>       readyState: 4,
>       response: null,
>       responseText: '',
>       responseType: 'text',
>       responseURL: '',
>       status: 0,
>       statusText: '',
>       timeout: 0,
>       upload: [XMLHttpRequestUpload],
>       _method: 'GET',
>       _url: [Url],
>       _sync: false,
>       _headers: [Object],
>       _loweredHeaders: [Object],
>       _mimeOverride: null,
>       _request: null,
>       _response: null,
>       _responseParts: null,
>       _responseHeaders: null,
>       _aborting: null,
>       _error: null,
>       _loadedBytes: 0,
>       _totalBytes: 0,
>       _lengthComputable: false
>     },
>     currentTarget: XMLHttpRequest {
>       onloadstart: null,
>       onprogress: null,
>       onabort: null,
>       onerror: null,
>       onload: null,
>       ontimeout: null,
>       onloadend: null,
>       _listeners: [Object],
>       onreadystatechange: null,
>       _anonymous: undefined,
>       readyState: 4,
>       response: null,
>       responseText: '',
>       responseType: 'text',
>       responseURL: '',
>       status: 0,
>       statusText: '',
>       timeout: 0,
>       upload: [XMLHttpRequestUpload],
>       _method: 'GET',
>       _url: [Url],
>       _sync: false,
>       _headers: [Object],
>       _loweredHeaders: [Object],
>       _mimeOverride: null,
>       _request: null,
>       _response: null,
>       _responseParts: null,
>       _responseHeaders: null,
>       _aborting: null,
>       _error: null,
>       _loadedBytes: 0,
>       _totalBytes: 0,
>       _lengthComputable: false
>     },
>     lengthComputable: false,
>     loaded: 0,
>     total: 0
>   }
> }

**Comment by CaerusKaru** [comment]
Looks like you haven’t loaded certs as part of your Node instance.

**Comment by lightbulb112** [comment]
Thank you for your reply. Any other hints you can throw at me? Perhaps a link that explains what this means?

**Comment by CaerusKaru** [comment]
https://lmgtfy.com/?q=load+certs+for+node

**Comment by lightbulb112** [comment]
Please forgive me for my many questions, why would I need a cert on my express server to make a http call?

**Comment by CaerusKaru** [comment]
You’re calling an HTTPS address. That requires a cert

**Comment by lightbulb112** [comment]
My webapi is running in IIS and has a cert installed (dotnetcore). I am able to query the webapi without issue from a browser.

**Comment by CaerusKaru** [comment]
That’s not how HTTPS works. And your browser has its own certs already loaded.

**Comment by alan-agius4** [comment]
Closing as this is not an issue with Angular universal.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
