### ISSUE TITLE
Jade Template Engine

### ISSUE THREAD

**Issue by imthehell** [angular/universal#177]
Hi guys,

is it possible to use Jade template engine with Angular Universal? If not, do you foreseen to include Jade template engine on future version of Angular Universal?

I have a big application developed with Nodejs + Express + Jade + Angularjs and I would like to upgrade to Angular 2  in order to take advantages of Server Side Rendering.

**Comment by jeffwhelpley** [comment]
Is your app open sourced  so I can see the code or can you let me somehow see it privately? I would be interested in seeing exactly how you are using your Jade templates today. The reason I am asking this is that my answer to you will largely depend on the way in which you use Jade today. In the simplest case, if you just have it generating your primer page for a single page app then there is something we can help you with right now.

A more complex scenario is if you have a server-driven website that uses Angular 1.x sprinkled in on specific pages. In other words, you don't have client side routing and Angular is just used to enhance a server side (i.e. from Jade) generated page. For this scenario, you can use Angular Universal as well, but it will require a little bit more custom work on your side to set up.

Anyways, give me some more details and perhaps some examples and then we can help you further.

**Comment by imthehell** [comment]
Hi Jeff, thank you for your answer. Unfortunately I cannot show you the source code, since the app is a commercial app of the Company that I'm working for.

Anyway, I'm afraid that our case is the most complex one. Let me try to better explain the architecture.

We are using angular ui-router in order to load pages from the server. When a route is requested by the user, the server load data from the database and renders the template written in Jade. We also have logics implemented inside the templates.
When the page is loaded client side, most of the data is loaded and sent calling server side API through $http service.

I think there is no more things to say.. let me know if you need further details.

It is not a problem to modify our code, just find the simple way to switch to angular 2 and angular universal.

Thank you for you support

**Comment by jeffwhelpley** [comment]
Ah, OK, I think I understand. So, first, realize that the Angular UI Router doesn't yet work with Angular 2. Nate Abele and crew are working on it, but I don't believe it is ready yet. You have to use the Angular 2 Component Router for now until they are ready.

That said, you can likely do something similar to what you are doing right now. The trick, however, is that you would need to use 2 different server side rendering engines together. The default implementation of Angular Universal requires that it is the primary rendering engine. See this example:

https://github.com/angular/universal-starter/blob/master/src/server.ts#L12

What you would need to do is to use the Jade template engine like you have now and then in each server side template, you would need to call renderToString() directly:

https://github.com/angular/universal/blob/master/modules/universal/server/src/render.ts#L73

If possible, though, I would suggest you get rid of the Jade layer and just use Angular. Let me know if that makes sense or if you run into any issues.

@gdi2290 weigh in if you have any additional thoughts.

**Comment by imthehell** [comment]
Jeff, thank you for the advices, I will try as suggested and let you know.

Get rid of Jade was our first idea, but unfortunately it is not possible right now. There are too many Jade templates with logics inside it. Change all of them requires too much effort.

it would be beautiful if the universal.ng2engine could render also Jade templates.
Do you think could be possible to implement in the near future? There are plenty of developers and software houses that has used Jade engine, and for them will be very difficult to switch to angular 2 / universal..

**Comment by gdi2290** [comment]
adding jade support is easy mode ;)
```es6
app.get('/yolo', function(req, res) {
  renderToString(App, []).then(function(app) {
    res.render('index', { app: app});
  });
});
```
```jade
doctype html
html(lang="en")
  head
    title= pageTitle
  body
    app= app
    script(src='bundle.js')
```

**Comment by imthehell** [comment]
Thank you! I will try asap your solution!

**Comment by gdi2290** [comment]
@imthehell I'm going to close this issue. Currently, we have a problem with router-outlet but otherwise that solution should work for jade
