### ISSUE TITLE
Getting 504 error  in Angular Universal application on page refresh while using ngx-socket-io

### ISSUE THREAD

**Issue by manju-405** [angular/universal#1778]
we are using ngx-socket-io for chat application, It is working fine with normal page clicks but whenever try to refresh the page getting 504 Bad request error with SSR build.

`
import express from "express";
import bodyParser from "body-parser";
import cors from "cors";
import morgan from "morgan";
import logger from "./core/logger/app-logger";
import config from "./core/config/config.dev";
import users from "./routes/users.route";
import chatHistories from "./routes/chathistories.route";
import compression from "compression";
import connectToDb from "./db/connect";
import rabbitConn from "./connection";

const port = config.serverPort;
logger.stream = {
  write(message) {
    logger.info(message);
  },
};

connectToDb();

const app = express();
app.use(cors());
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb" }));

app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(morgan("dev", { stream: logger.stream }));
app.use(compression());

app.use("/api/user", users);
app.use("/api/chat-history", chatHistories);

// Index route
app.get("/", (req, res) => {
  res.send("Invalid endpoint!");
});

var server = app.listen(port, () => {
  logger.info("server started - ", port);
});

var io = require("socket.io").listen(server);

var usersCollection = [];
var usersCollection2 = {};

// Socket.io operations
io.on("connection", function (socket) {

  socket.on("join", function ({ username, userId, userSocketId }) {
    // Same contract as ng-chat.User
    usersCollection.push({
      participant: {
        id: socket.id, 
        fromUserId: userId,
        displayName: username,
        status: 0,
        avatar: null,
      },
    });
    usersCollection2[socket.id] = {
      id: socket.id,
      fromUserId: userId,
      displayName: username,
      status: 0,
      avatar: null,
    };

    socket.broadcast.emit("friendsListChanged", usersCollection);
    socket.broadcast.emit("friendsListChanged2", usersCollection2);

    // This is the user's unique ID to be used on ng-chat as the connected user.
    socket.emit("generatedUserId", socket.id);

    // On disconnect remove this socket client from the users collection
    socket.on("disconnect", function () {
 
      var i = usersCollection.findIndex((x) => x.participant.id === socket.id);
      usersCollection.splice(i, 1);

      delete usersCollection2[socket.id];

      socket.broadcast.emit("friendsListChanged", usersCollection);
      socket.broadcast.emit("friendsListChanged2", usersCollection2);
    });
  });

  socket.on("giveMeOnlineUsersList", function (userId) {
    io.to(userId).emit("friendsListChanged2", usersCollection2);
  });
});

`

**Comment by alan-agius4** [comment]
Closing as the bug report doesn't follow the issue template.
