### ISSUE TITLE
accept encoding

### ISSUE THREAD

**Issue by maxisam** [angular/universal#1779]
for some reason the accept encoding for the very first request (which is html request) is identity only. But I check my request, it should have gzip, deflate and br

Any clue? thx!

note: I test it with a simple node + express, and it works fine.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blog/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by maxisam** [comment]
@alan-agius4 but it is a bug.  Apparently it work fine if I fire up node directly, but if I use angular universal tool chain to serve it, it doesn't.

**Comment by maxisam** [comment]
@alan-agius4  It actually causes an issue if someone tries to create their own cache layer for prerender pages with gzip. It is good that it works correctly under node, because it will work on production. However, it is annoy that is works different in dev.

**Comment by alan-agius4** [comment]
@maxisam, in such case please file a new issue and kindly follow the issue template.

**Comment by maxisam** [comment]
@alan-agius4 There are only 2 issue templates. This is none of them. Do I miss anything?

![image](https://user-images.githubusercontent.com/456807/89062056-66349d00-d32b-11ea-9fcd-9bd444f7a513.png)

**Comment by alan-agius4** [comment]
Oops something isn’t quite right. Will fix hay soon

**Comment by alan-agius4** [comment]
Should be fixed now

**Comment by maxisam** [comment]
@alan-agius4 #1783 , I am glad we have fixed one issue already lol
