### ISSUE TITLE
"npm run prerender" never stops

### ISSUE THREAD

**Issue by hohler** [angular/universal#1781]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

I don't know, if it did work before. I just started using it.

### Description

There is already a Stackoverflow issue: https://stackoverflow.com/questions/62474082/angular-universal-npm-run-prerender-command-never-stops

When executing the default `npm run prerender` script, it will successfully prerender all the defined routes, but the script actually never exits after all routes have been rendered.

I could fix it with the following workaround:

In file `prerender/render.js` (compiled, in node_modules), replace the following line:
```
}))().then().catch();
```
with
```
}))().then(()=>process.exit(0)).catch(()=>process.exit(1));
```

This will correctly terminate the forked process. I don't know, if this would go as a good solution, but at least for me it solved the issue.

## 🔬 Minimal Reproduction

Just use a newly generated Angular app and add Universal.

## 🔥 Exception or Error

There is no exception or error, the prerendering simply doesn't exit after all routes are rendered.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 10.14.1
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@angular/pwa                      0.900.5
@ngtools/webpack                  9.1.12
@nguniversal/builders             9.1.1
@nguniversal/common               10.0.1
@nguniversal/express-engine       9.1.1
@schematics/angular               8.3.25
@schematics/update                0.901.12
rxjs                              6.6.0
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by constantant** [comment]
In case you use `setInterval` which is initiated not by a user you will get the same hanging, 
so even `}))().then(()=>process.exit(0)).catch(()=>process.exit(1));` do not help you.

**Comment by hohler** [comment]
I guess it's related to the project, as I lately upgraded another project to Angular 9 / new nguniversal stuff, and there it doesn't happen.

**Comment by alan-agius4** [comment]
Closing as it probably related to use code.

See gotchas here: https://github.com/angular/universal/blob/master/docs/gotchas.md
