### ISSUE TITLE
HttpClient URLs not fixed in prerender

### ISSUE THREAD

**Issue by jdforsythe** [angular/universal#1788]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Unsure

### Description

I am attempting to load JSON from the assets directory with HttpClient and use that to populate a component. This works fine when serving the application normally, however it errors when I use prerender.

I am guessing this has something to do with the translation of relative to absolute URLs in the prerenderer. Again, this works fine serving with `npm start` and if I change the URLs to start with `http://localhost:4300` and run the app with `npm start` in a separate terminal, the prerendering works as expected. I just can't get it to load the file from it's own copy of the application during prerender.

## 🔬 Minimal Reproduction

Service:

```ts
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';

import { Observable } from 'rxjs';
import { shareReplay } from 'rxjs/operators';

import { Article } from './article.interface';

@Injectable({
  providedIn: 'root'
})
export class ArticleService {

  articles$: Observable<Article[]>;

  constructor(private readonly http: HttpClient) {
    this.articles$ = this.http.get<Article[]>(`/assets/blog/articles.json`)
      .pipe(shareReplay(1));
  }
}
```

Component:

```ts
import { Component, OnInit } from '@angular/core';

import { Observable } from 'rxjs';
import { take } from 'rxjs/operators';

import { Article } from '../shared/article.interface';
import { ArticleService } from '../shared/article.service';

@Component({
  selector: 'app-blog',
  templateUrl: './blog.page.html',
  styleUrls: ['./blog.page.scss'],
})
export class BlogPage implements OnInit {

  articles$: Observable<Article[]>;

  constructor(private readonly articleService: ArticleService) {}

  ngOnInit() {
    this.articles$ = this.articleService.articles$.pipe(take(1));
  }
}
```

## 🔥 Exception or Error
<pre><code>

CREATE /Users/username/dev/testapp/dist/app/browser/news/blog/index.html (2769 bytes)
ERROR Error
    at XMLHttpRequest.send (/Users/username/dev/testapp/dist/app/server/main.js:1:1687903)
    at Observable_Observable.rxjs__WEBPACK_IMPORTED_MODULE_2__.a.observer [as _subscribe] (/Users/username/dev/testapp/dist/app/server/main.js:1:3152655)
    at Observable_Observable._trySubscribe (/Users/username/dev/testapp/dist/app/server/main.js:1:1279674)
    at Observable_Observable.subscribe (/Users/username/dev/testapp/dist/app/server/main.js:1:1279456)
    at _task (/Users/username/dev/testapp/dist/app/server/main.js:1:1229830)
    at Observable_Observable.Observable.a.observer [as _subscribe] (/Users/username/dev/testapp/dist/app/server/main.js:1:1230175)
    at Observable_Observable._trySubscribe (/Users/username/dev/testapp/dist/app/server/main.js:1:1279674)
    at Observable_Observable.subscribe (/Users/username/dev/testapp/dist/app/server/main.js:1:1279456)
    at subscribeToResult (/Users/username/dev/testapp/dist/app/server/main.js:1:1740059)
    at MergeMapSubscriber._innerSub (/Users/username/dev/testapp/dist/app/server/main.js:1:832282)
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.12
Node: 10.15.3
OS: darwin x64

Angular: 9.1.12
... cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/animations               10.0.7
@ngtools/webpack                  9.1.12
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @jdforsythe, this issue will be fixed `10.1.0`, which is currently in a prerelease state.

if the problem persists after updating to `10.1`, kindly file a new issue. Thanks.
