### ISSUE TITLE
Angular Universal 9 does not translate the source HTML file when using Angular-i18n

### ISSUE THREAD

**Issue by pmachaux** [angular/universal#1789]
# 🐞 Bug report

#### What modules are related to this issue?
- [x] universal
- [x] i18n

### Is this a regression?
I did not try on previous versions.

### Description

When using Angular i18n with Angular Universal, the files are properly translated from a user perspective.
However, when using view-source in the URL, we can see the source HTML file is not translated.
The translation seems to be handled by the JS file attached to the source HTML.

This will prevent web crawlers from working properly.

## 🔬 Minimal Reproduction
Please see: https://github.com/pmachaux/angular-universal-i18n-demo
Run the following command to serve the project after installing the modules: npm run dev:ssr

Type in the browser URL: view-source:http://localhost:4200/fr/
You should see it as such:
![image](https://user-images.githubusercontent.com/21976890/89463763-5c50d680-d73d-11ea-92d2-9a84799e1689.png)

You will see the source file NOT translated. Even if on http://localhost:4200/fr/, everything works fine.

![image](https://user-images.githubusercontent.com/21976890/89463686-48a57000-d73d-11ea-88df-a79835913aa5.png)

## 🌍 Your Environment
Angular 9
Node v12.16.1

**Comment by alan-agius4** [comment]
@pmachaux. Looks like you don’t have localize enable for the server builder.

https://github.com/pmachaux/angular-universal-i18n-demo/blob/723f2c5b1887925b2bfa9f361a404e1891618e1c/angular.json#L134

**Comment by pmachaux** [comment]
@alan-agius4 indeed, it fixes the issue. The only drawback is that I cannot use the server.ts to serve both languages directly.
I need extra work.
Thanks for your help!
