### ISSUE TITLE
Angular 10 SSR build:  Generic type 'ModuleWithProviders<T>' requires 1 type argument(s)

### ISSUE THREAD

**Issue by githmans** [angular/universal#1790]
Hi,

I have a problem with build SSR on Angular 10 app with ngUniversal.

There is a small problem with missing typings.

![image](https://user-images.githubusercontent.com/34391956/89618281-13f3fe80-d88c-11ea-8eff-73305917144a.png)

# 🐞 Bug report

#### What modules are related to this issue?

- [x] module-map-ngfactory-loader
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

## 🔥 Exception or Error
<pre><code>
ERROR in node_modules/@nguniversal/module-map-ngfactory-loader/module-map-ngfactory-loader.d.ts:24:112
 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

24     static withMap(moduleMap: ɵnguniversal_modules_module_map_ngfactory_loader_module_map_ngfactory
_loader_a): ModuleWithProviders;
</code></pre>

## 🌍 Your Environment
<pre><code>
  "dependencies": {
    "@angular/animations": "^10.0.1",
    "@angular/common": "^10.0.1",
    "@angular/compiler": "^10.0.1",
    "@angular/core": "^10.0.1",
    "@angular/forms": "^10.0.1",
    "@angular/localize": "^10.0.1",
    "@angular/router": "^10.0.1",
    "@ng-bootstrap/ng-bootstrap": "^6.1.0",
    "@ng-select/ng-select": "^4.0.1",
    "@ngtools/webpack": "^10.0.1",
    "@nguniversal/aspnetcore-engine": "^10.0.1",
    "@nguniversal/common": "^10.0.1",
    "@nguniversal/express-engine": "^10.0.1",
    "@nguniversal/module-map-ngfactory-loader": "9.0.0-next.9",
    "@ngx-lite/json-ld": "^0.6.2",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@schematics/angular": "^10.0.1",
    "@schematics/update": "^0.1000.1",
    "@trademe/ng-defer-load": "^8.2.1",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.1.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^3.6.5",
    "ng-inline-svg": "^10.1.0",
    "ngx-page-scroll": "^7.0.1",
    "ngx-page-scroll-core": "^7.0.1",
    "node-sass": "^4.12.0",
    "rxjs": "^6.5.5",
    "svg-sprite": "^1.5.0",
    "ts-loader": "^7.0.5",
    "tslib": "^2.0.0",
    "webpack": "^4.43.0",
    "zone.js": "~0.10.3"
  },

</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
