### ISSUE TITLE
angular SSR using @nguniversal/express-engine package get this error (ERROR in error TS6053: File '/project/src/server.ngtypecheck.ts' not found.)

### ISSUE THREAD

**Issue by mnfi3** [angular/universal#1793]
I am using @nguniversal/express-engine to Server Side Rendering in angular.When I run `$ nmp build:ssr` or `$ npm run dev:ssr` i get this error.
```ERROR in error TS6053: File 'C:/dev/web/workspace/project/src/server.ngtypecheck.ts' not found.
error TS6053: File 'C:/dev/web/workspace/project/src/server.ts' not found.
error TS6053: File 'C:/dev/web/workspace/project/src/src/main.server.ngtypecheck.ts' not found.
error TS6053: File 'C:/dev/web/workspace/project/src/src/main.server.ts' not found.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! client@0.0.0 build:ssr: `ng build --prod && ng run client:server:production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the client@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. ```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
