### ISSUE TITLE
builders['ssr-dev-server']" should have required property 'class'

### ISSUE THREAD

**Issue by amandaytq** [angular/universal#1794]
Hi guys, I'm trying to add in SSR using the universal package for an existing angular project. But I am experiencing this error `builders['ssr-dev-server']" should have required property 'class'` whenever I tried to run the `serve-ssr` command. 

- "@angular-devkit/build-angular": "0.13.9",
- "@angular/cli": "7.3.8",
- "@angular/compiler-cli": "7.2.9",
- "@nguniversal/express-engine": "7.0.2",

**Comment by alan-agius4** [comment]
Hi @amandaytq, you need to use Angular and Angular CLI version 9 or later.


Kindly update using `ng update @angular/cli @angular/core` 

Please be aware that Angular version 7 is no longer supported. See: https://angular.io/guide/releases
