### ISSUE TITLE
TransferState (TransferHttpCacheModule) issues with non GET requests.

### ISSUE THREAD

**Issue by jacksnipe24** [angular/universal#1795]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [X] common
- [ ] express-engine
- [ ] hapi-engine

### Description

When using `TransferHttpCacheModule` in conjunction with `ServerTransferStateModule` that installs an interceptor to avoid duplicate Http requests, and having a non GET request in the middle of request chain, either TransferState is not added for all GET request or is added but ignored. For example when starting the app i have 5 requests, first two are GET, third is PUT and last two are GET again. The interceptor from `TransferHttpCacheModule` will make requests for first two GET url, add them into state, but when doing PUT request (upon first non GET request), it will make caching no longer active and any GET request after that will not be added into state. 
Even filtering requests, so that non GET requests won't be made in SSR, still when client side will made a request to non GET url, everything will break again. In that case even tho responses from 4 GET requests were added to transfer state, after triggering PUT request in client side, transferState will be ignored.

## 🔬 Minimal Reproduction
Every universal app with latest Angular and Universal that has non GET request in initial request chain when rendering the app,

## 🌍 Your Environment
<pre><code>

</code>     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 10.16.0
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</pre>

**Comment by deerua** [comment]
It's default behavior of TransferHttpCacheInterceptor (POST/PUT means you are modifying something, should not happens while rendering)
1. convert your PUT to GET (if not possible move it to UI part)
2. copy TransferHttpCacheInterceptor to your local code and modify POST/PUT behaviors

**Comment by jacksnipe24** [comment]
hey @deerua . I think this should not be the intended behavior. Ok the interceptor can skip modifying requests, but it doesn't have to break completely for the rest requests afterwards, even more so your suggestion to move it to UI doesn't work either. When skipping PUT or POST in server, it still causes issues when doing that in client side. (read the last  part of my issue). 
I think the interceptor should only skip modifying requests but not stop and continue to cache normal GET requests after that.

**Comment by hiepxanh** [comment]
wow, that really make sense until I'm using graphql, it pure post request :D It is imposible to cache request for angular. I wish we have this feature

**Comment by vz-tl** [comment]
I agree with the OP, current behavior is far too restrictive, especially when doing graphql calls in parallel. In a GraphQL scenario this completely prevents making use of this very convenient module.

I also don't get why cache has to be disabled completely once a non-GET/HEAD request is being invoked. Couldn't the condition rather be changed to skip caching non-GET/HEAD calls but still keeping cache active? How I understood the implemented logic, there shouldn't be any responses for e.g. POST request cached. But from my understanding, doing a POST actually shouldn't lead to completely disabling cache once such request will be done. What should be the reason for such restrictive decision?

Another proposal would be to make the module configurable via e.g. `TransferHttpCacheModule.forRoot(...)`, so it'd be possible to adapt the default behavior to the individual needs.

Would be really glad to continue using TransferHttpCacheModule without monkey-patching or copying it into own code base.

**Comment by fitness23** [comment]
> I agree with the OP, current behavior is far too restrictive, especially when doing graphql calls in parallel. In a GraphQL scenario this completely prevents making use of this very convenient module.
> 
> I also don't get why cache has to be disabled completely once a non-GET/HEAD request is being invoked. Couldn't the condition rather be changed to skip caching non-GET/HEAD calls but still keeping cache active? How I understood the implemented logic, there shouldn't be any responses for e.g. POST request cached. But from my understanding, doing a POST actually shouldn't lead to completely disabling cache once such request will be done. What should be the reason for such restrictive decision?
> 
> Additionally I noticed that on server side in some scenarios once `appRef.isStable` emitted true (disabling cache) there still have been requests pending and application hasn't finished initial render state. This buggy behavior isn't related to TransferHttpCacheInterceptor, but it seems not reliable to disable cache based on `appRef.isStable`, at least not on server side.
> 
> My proposal would be to make the module configurable via e.g. `TransferHttpCacheModule.forRoot(...)`, so it'd be possible to adapt the default behavior to the individual needs.
> 
> Would be really glad to continue using TransferHttpCacheModule without monkey-patching or copying it into own code base.



> I agree with the OP, current behavior is far too restrictive, especially when doing graphql calls in parallel. In a GraphQL scenario this completely prevents making use of this very convenient module.
> 
> I also don't get why cache has to be disabled completely once a non-GET/HEAD request is being invoked. Couldn't the condition rather be changed to skip caching non-GET/HEAD calls but still keeping cache active? How I understood the implemented logic, there shouldn't be any responses for e.g. POST request cached. But from my understanding, doing a POST actually shouldn't lead to completely disabling cache once such request will be done. What should be the reason for such restrictive decision?
> 
> Additionally I noticed that on server side in some scenarios once `appRef.isStable` emitted true (disabling cache) there still have been requests pending and application hasn't finished initial render state. This buggy behavior isn't related to TransferHttpCacheInterceptor, but it seems not reliable to disable cache based on `appRef.isStable`, at least not on server side.
> 
> My proposal would be to make the module configurable via e.g. `TransferHttpCacheModule.forRoot(...)`, so it'd be possible to adapt the default behavior to the individual needs.
> 
> Would be really glad to continue using TransferHttpCacheModule without monkey-patching or copying it into own code base.

I’m trying to do a POST request. Did you manage to get it working?

**Comment by ahstudee** [comment]
What does this now mean? If I pull down the latest changes for Angular 15 will POST requests no longer be invalidated?
