### ISSUE TITLE
Angular 9 SSR error - Cannot find module 'stream'

### ISSUE THREAD

**Issue by samjoe5** [angular/universal#1805]
In my project I am using Angular SSR, I tried to build the ssr and it's working and when I tried to serve it throws an error "**Cannot find module 'stream**'" . This error is inside the dist/server/main.js. Please help to resolve this error. Below is the screenshot for that error,

<img width="1110" alt="Screenshot 2020-08-17 at 11 28 43 AM" src="https://user-images.githubusercontent.com/43204242/90361849-d6a62280-e07c-11ea-91fa-972eae126c66.png">

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
