### ISSUE TITLE
Using openpgp in Angular 9 SSR leads to error - Cannot find module 'stream'

### ISSUE THREAD

**Issue by samjoe5** [angular/universal#1807]
In my angular project I am using openpgp for encryption purpose. Using openpgp I also want to do SSR, when I start to build it works fine but when I want to serve the server file main.js it throws an error - **Cannot find module 'stream'**.  This is my package.json dependencies,

```
  "dependencies": {
    "@angular/animations": "~9.0.2",
    "@angular/common": "~9.0.2",
    "@angular/compiler": "~9.0.2",
    "@angular/core": "~9.0.2",
    "@angular/forms": "~9.0.2",
    "@angular/platform-browser": "~9.0.2",
    "@angular/platform-browser-dynamic": "~9.0.2",
    "@angular/platform-server": "~9.0.2",
    "@angular/router": "~9.0.2",
    "@blockstack/connect": "^2.10.1",
    "@blockstack/stacks-transactions": "^0.5.1",
    "@nguniversal/express-engine": "^9.0.2",
    "blockstack": "21.1.0",
    "express": "^4.15.2",
    **"openpgp": "^4.10.7"**,
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "uuid": "^8.0.0",
    "zone.js": "~0.10.2"
  },
```

This is my login service.ts,

```
// Import openpgp
const openpgp = require('openpgp');

   let passpharse = uuid.v4();
    const { privateKeyArmored, publicKeyArmored, revocationCertificate } = await openpgp.generateKey({
      userIds: [{ id: userData.username }], // you can pass multiple user IDs
      // curve: 'XXXXX', // ECC curve name
      rsaBits: XXXX, // RSA
      passphrase: passpharse // protects the private key
    });

    let pgp = {
      "privateKeyArmored": privateKeyArmored,
      "publicKeyArmored": publicKeyArmored,
      "revocationCertificate": revocationCertificate,
      "passpharse": passpharse
    };
```

Following is the error screenshot,

<img width="1215" alt="Screenshot 2020-08-17 at 8 35 25 PM" src="https://user-images.githubusercontent.com/43204242/90411336-3f1af100-e0c9-11ea-9557-73e62896accd.png">

Please do help to resolve this issue.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
