### ISSUE TITLE
(126,14): error TS4023: Exported variable 'NG_PRELOAD_CACHE_PROVIDERS' has or is using name 'Provider'

### ISSUE THREAD

**Issue by dbabaioff** [angular/universal#181]
I'm getting this error when trying to run:

```bash
$ tsc -p ./node_modules/angular2-universal-preview
```

```
error TS6053: File 'custom_typings/_custom.d.ts' not found.
error TS6053: File 'tsd_typings/tsd.d.ts' not found.
node_modules/angular2-universal-preview/client/src/ng_preload_cache.ts(126,14): error TS4023: Exported variable 'NG_PRELOAD_CACHE_PROVIDERS' has or is using name 'Provider' from external module "node_modules/angular2/src/core/di/provider" but cannot be named.
```

**Comment by manekinekko** [comment]
Hi @dbabaioff is there any reason you're using this command?

--> `tsc -p ./node_modules/angular2-universal-preview`

Are you trying to build the project? or are you seeking something else?

**Comment by dbabaioff** [comment]
I was trying to build the universal module inside my [universal seed project](https://github.com/dbabaioff/ng2-universal-seed).

**Comment by manekinekko** [comment]
In order to build universal, you just need to npm install and then gulp build.

**Comment by gdi2290** [comment]
the repo shouldn't be built as a dependacy since it's more than one module within the repo. `NG_PRELOAD_CACHE_PROVIDERS` shouldn't be used since it's not working at the moment but I'll refactor it to make it so
