### ISSUE TITLE
Lazy-loaded routes crash firebase cloud function

### ISSUE THREAD

**Issue by inorganik** [angular/universal#1810]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [X] express-engine
- [ ] hapi-engine

### Is this a regression?

Yes, I had this working in Angular 7 and @ng-universal/express 7

### Description

My project builds and serves fine with `npm run serve:ssr`, but when served with `firebase serve`, I get a route match error on lazy-loaded routes that are directly requested from the server (e.g., refresh page on a lazy-loaded route). I have debated about where to post this, but I'm fairly certain it's a universal config issue.

## 🔬 Minimal Reproduction

Clone [this minimal reproduction repo](https://github.com/inorganik/ngx-countup-with-ssr/tree/firebase), make sure you clone the "firebase" branch.
- `npm i `
- `npm run build`
- `npm run serve:ssr`
- ✅ Verify the app works by visiting http://localhost:4000
- Run `firebase serve`
- ✅ Verify app works by visiting http://localhost:5000
- ❌ Reload page on lazy-loaded route - function crashes: http://localhost:5000/lazy

## 🔥 Exception or Error
<pre><code>
ERROR { Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'ssr-demo-b3ef3/us-central1/ssr'
>  Error: Cannot match any routes. URL Segment: 'ssr-demo-b3ef3/us-central1/ssr'
>      at router_ApplyRedirects.noMatchError (/Users/jamieperkins/Web-projects/GitHub/ngx-countup-with-ssr/functions/dist/webpack/server.js:149267:16)
>      at catchError_CatchSubscriber.urlTrees$.pipe.catchError [as selector] (/Users/jamieperkins/Web-projects/GitHub/ngx-countup-with-ssr/functions/dist/webpack/server.js:149231:28)
</code></pre>

## 🌍 Your Environment
<pre><code>
Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.900.7
@angular-devkit/build-angular              0.803.24
@angular-devkit/build-optimizer            0.803.24
@angular-devkit/build-webpack              0.803.24
@angular-devkit/core                       8.3.24
@angular-devkit/schematics                 8.3.24
@angular/cli                               8.3.24
@angular/fire                              5.4.2
@ngtools/webpack                           8.3.24
@nguniversal/express-engine                v8.2.6
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        8.3.24
@schematics/update                         0.803.24
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
node                                     10.22
</code></pre>

Related: https://github.com/firebase/firebase-tools/issues/1890

**Comment by muellerdberlin** [comment]
@inorganik did you find any solution for that? I have the same problem... Looking for a solution for days. I'm using Angular 11 (latest version) with Angular universal + ssr option for firebase.

What I found so far (don't know, if that helps):
1. Adding to server module provider's list:
`{provide: APP_BASE_HREF, useFactory: () => isDevMode() ? '/us-central1/ssr' : '/ssr'}`

When starting `firebase serve` my output is following:
```shell
✔  functions: Using node@10 from host.
i  functions: Watching "/Users/path/dist/project" for Cloud Functions...
i  hosting[project]: Serving hosting files from: dist/project/dist/project/browser
✔  hosting[project]: Local server: http://localhost:5000
✔  functions[ssr]: http function initialized (http://localhost:5001/project/us-central1/ssr).
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
