### ISSUE TITLE
Prerender

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#182]
We need to be able to prerender snapshots of our Angular 2 app
* [x] gulp render as [`angular2-gulp-prerender`](https://www.npmjs.com/package/angular2-gulp-prerender) (@gdi2290)
* [x] grunt render https://github.com/angular/universal/pull/236 @manekinekko
* [x] webpack plugin https://github.com/angular/universal/pull/237 @manekinekko

**Comment by gdi2290** [comment]
gulp is done

**Comment by simb** [comment]
It looks like all three of the chores for this task are completed.

**Comment by gdi2290** [comment]
@simb you're right thanks! done via https://github.com/angular/universal/pull/236 https://github.com/angular/universal/pull/237 https://github.com/angular/universal/pull/234
