### ISSUE TITLE
Server-side rendering (SSR) with Angular Universal issues with swarm-js

### ISSUE THREAD

**Issue by saurabh-innovator** [angular/universal#1825]
On running the command for server-side rendering: **ng run project-name:server:production**

Getting the following error:

ERROR in ./node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve './package' in 'Project-path\node_modules\swarm-js\node_modules\got'

ERROR in ./node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in 'Project-path\node_modules\swarm-js\node_modules\got'

I'm using Angular 10 and windows system.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
