### ISSUE TITLE
Move ng2engine into modules/

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#183]
ng2engine should live in `modules/` now since the implementation shouldn't need to change after a refactor to remove ng2scripts

**Comment by wesleycho** [comment]
Where is this located currently?

**Comment by gdi2290** [comment]
https://github.com/angular/universal/blob/master/modules/universal/server/src/express/engine.ts

**Comment by wesleycho** [comment]
Should the ng2scripts refactor happen first? Currently the engine depends on it.

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/pull/204 and merged via https://github.com/angular/universal/commit/bdbe32a5ac402ef60a11a9a81f7255cbafb2f216
