### ISSUE TITLE
router-outlet is empty for lazy loaded modules in Angular 9 SSR 

### ISSUE THREAD

**Issue by Poorna-k** [angular/universal#1846]
#🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description
We are using the angular 9 with lazy loading, and we enabled the SSR to it. Routing with lazy loading is working fine in browser and server mode but in the ssr mode, when i view the document response of any lazy-loaded module, I can't see the content in the router-outlet tag in the app-root tag. It is showing empty, in all the cases. Also, it is giving `Error: Runtime compiler is not loaded` error. 
I'm adding the configuration and errors snapshots.

## 🌍 Your Environment
<pre><code>

"dependencies": {
    "@angular/animations": "^9.0.5",
    "@angular/cdk": "^9.1.1",
    "@angular/cli": "^9.0.5",
    "@angular/common": "^9.0.5",
    "@angular/compiler": "^9.0.5",
    "@angular/core": "^9.0.5",
    "@angular/forms": "^9.0.5",
    "@angular/material": "^9.1.1",
    "@angular/platform-browser": "^9.0.5",
    "@angular/platform-browser-dynamic": "^9.0.5",
    "@angular/platform-server": "^9.0.5",
    "@angular/router": "^9.0.5",
    "@nguniversal/express-engine": "^9.0.1",
    "rxjs": "^6.5.4",
    "zone.js": "^0.10.3",
  },
"devDependencies": {
    "@angular-builders/custom-webpack": "^8.4.1",
    "@angular-devkit/build-angular": "^0.900.7",
    "@angular/compiler-cli": "^9.1.12",
    "@angular/language-service": "^9.0.5",
    "@biesbjerg/ngx-translate-extract": "^4.2.0",
    "@nguniversal/builders": "^9.0.1",
    "@types/express": "^4.17.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.0",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "^5.4.0",
    "ts-node": "~5.0.1",
    "tslint": "^5.9.1",
    "typescript": "3.7.5",
  }

tsconfig.json
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2017", "dom", "esnext.asynciterable", "es2016", "es2018.promise"],
    "plugins": [{ "name": "@divyenduz/ts-graphql-plugin" }],
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true
  }
}

tsconfig.server.json
{
  "extends": "./tsconfig.app.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app-server",
    "module": "commonjs",
    "types": ["node"]
  },
  "files": ["./main.server.ts", "../server.ts"],
  "angularCompilerOptions": {
    "entryModule": "./app/app.server.module#AppServerModule",
    "enableIvy": false
  }
}

app-routing.module.ts (just placed the routes array)
const routes: Routes = [
  { path: '', pathMatch: 'full', redirectTo: '/' },
  {
    path: '',
    canActivate: [AuthGuard],
    component: layoutonecomponent,
    loadChildren: () => import('./modules/user/user.module').then(m => m.UserModule)
  },
  {
    path: 'dashboard',
    canActivate: [AuthGuard],
    component: layouttwocomponent,
    loadChildren: () => import('./modules/two/two.module').then(m => m.TwoModule)
  },
  {
    path: 'admin',
    canActivate: [AuthGuard],
    component: layoutthreecomponent,
    loadChildren: () => import('./modules/three/three.module').then(m => m.ThreeModule)
  },
  {
    path: '',
    component: layoutfourcomponent,
    canActivate: [UnAuthGuard],
    loadChildren: () => import('./modules/next/next.module').then(m => m.NextModule)
  },
  { path: '**', redirectTo: '/' }
];

@NgModule({
  imports: [RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })],
  exports: [RouterModule]
})
export class AppRoutingModule {}

Platform: Windows
Node: 12.18.0

</code></pre>

Response of SSR document. It is same for all the routes.
![router-outlet](https://user-images.githubusercontent.com/71828200/94223184-e41cbb00-ff0c-11ea-88f2-5b8b54e298de.PNG)

I hope i provided the required information!

**Comment by shafqatjan** [comment]
any luck?, im facing too

**Comment by Poorna-k** [comment]
No @shafqatjan HTML is not coming in the router-outlet with lazy loading. It is happening, only for the Non-lazy loaded modules.

Ex:
```
const routes: Routes = [
  { path: 'some-x', component: SomeXComponent },
  {
    path: 'some-y',
    canActivate: [AuthGuard],
    component: layoutonecomponent,
  },
];
```

**Comment by shafqatjan** [comment]
yeah without lazy loading it is working at my side too, but i read do lazy loading for faster loading but source code sucks

**Comment by shafqatjan** [comment]
try to remove routing.module for module, put routing code in module directly and try it

**Comment by Poorna-k** [comment]
That didn't work @shafqatjan

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
