### ISSUE TITLE
ECONNREFUSED 127.0.0.1:53233 when running "serve-ssr" from @nguniversal/builders

### ISSUE THREAD

**Issue by mmeylan** [angular/universal#1848]
We are using Angular Universal in production and are very happy with it. We want to work with server side rendering all the way down to our day-to-day development lifecycle and have chosen to use the `@nguniversal/builders` package to do that.

Unfortunately, since upgrading to Angular 10.x and @nguniversal/builders 10.x, the schematic `serve-ssr` from `@nguniversal/builders` fails with the following error:

```
connect ECONNREFUSED 127.0.0.1:55304
```

# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

Yes, this did not happen with Angular 9.x and @nguniversal/builders 9.x but it now happens with version 10.x.

### Description

After a lot of debugging, I've found a curious behavior: It seems as though the node net server created by `@nguniversal/builders` succesfully starts to listen, but after a few seconds shuts down silently. I've recorded this behavior and it can be seen in [this short video](https://www.loom.com/share/69e583aea75a481aa931b6a9bf8c54d8). 

Context:
* Right-side terminal is watching all ports being listened to locally
* Left side terminal is the `server-ssr` command being executed
* At the beginning of the build, a port is opened by node (**55304**) 
* After a few seconds, node stops listening on **55304** silently
* Once the build (browser and server) succeeds, my SSR server successfully starts on **4200**
* The "builder process" now tries to connect to **55304** but it's no longer there, thus failing the command with `connect ECONNREFUSED 127.0.0.1:55304`

Curiously, the command works when setting `"inspect": true` in the config of @nguniversal/builders (angular.json). This forces us to connect a debugger to the process though, and isn't very developer friendly.

## 🔬 Minimal Reproduction

Unfortunately, I don't have a reproduction environment.

## 🔥 Exception or Error
<pre><code>
connect ECONNREFUSED 127.0.0.1:55304
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 10.1.2
Node: 12.18.2
OS: darwin x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@nguniversal/builders           10.1.0
@nguniversal/express-engine     10.1.0
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.2
</code></pre>

This is maybe related to https://github.com/angular/universal/issues/1796

**Comment by danieldanielecki** [comment]
Hey, you're not alone. I can confirm that when upgrading `Angular` `8` to `10` I could face exactly same issue once trying to run with the new `server-ssr` schematic.

**Comment by fischermatte** [comment]
This is indeed a very annoying bug: It makes local development with SSR almost impossible since one has to rebuild the full prod bundle on each change.

**Comment by Avcajaraville** [comment]
I stumbled upon this issue while having the same error. Then what I did was to follow [this project](https://github.com/Angular-RU/universal-starter) which showcases an integration between universal and angular 9 (though, I'm using angular 10).

Anyway, as I was **coming from angular 7** (maybe you are migrating as well), I notice a quite dramatic  change inside `angular.json`, architect server, the options.main property now points to the **actual express server**, before angular 9, I believe the setup was to point to `src/main.server.ts`, the file that exposes the `AppServerModule`.

This fixed my issue, maybe it helps as well :)

**Comment by vmasek** [comment]
As @Avcajaraville written, I also recommend checking your project against the [universal starter](https://github.com/Angular-RU/universal-starter).

This is an error related to bad SSR setup/structure.

My flow was to check (Yours can be different, but in general it should match):
- `"architect"."server"` [angular.json](https://github.com/Angular-RU/universal-starter/blob/master/angular.json)
  - `"main"` has to be `"server.ts"` not `"src/main.server.ts"`
- `ngExpressEngine` [server.ts](https://github.com/Angular-RU/universal-starter/blob/master/server.ts)
  - get rid of the `require` for `ngExpressEngine`, `AppServerModuleNgFactory`, `LAZY_MODULE_MAP` or`provideModuleMap`. It should not be "required" anymore. It has different syntax now.
  - your `ngExpressEngine` should `bootstrap: AppServerModule` with module imported from server `main.server` file `import { AppServerModule } from './src/main.server';`
- [main.server.ts](https://github.com/Angular-RU/universal-starter/blob/master/src/main.server.ts) shouldn't contain unnecessary stuff but it should export the `AppServerModule`
- your [tsconfig.server.json]https://github.com/Angular-RU/universal-starter/blob/master/src/tsconfig.server.json should have `server.ts` in the `"files"`

**Comment by rsouthgate** [comment]
Stumbled across this and discovered for me it was that i'd changed the `process.env.PORT` in server.ts `run()` to `process.env.WEBSITES_PORT` (Azure App Services passes that env var through by default). So it would seem that the dev server passes the port to the child process via the hard coded PORT env var invisibly.

**Comment by littlebigjuko** [comment]
Had the similar problem as @rsouthgate.
Changing the port to 443 depending on the environment (for local one). Wasn't able to debug what's happening.

**Comment by marekberger** [comment]
Have the same issue. I tried to investigate the source code of the `@nguniversal/builders` package and I discovered that if I increase the number of attempts here: https://github.com/angular/universal/blob/3ca407beb3a4f5d96f140cf47c259f80b62f3ae5/modules/builders/src/ssr-dev-server/utils.ts#L79 then it works well. 

It seems  like my app don't boot fast enought to be connected to the dev-ssr process until the number of attempts are exceeded,

**Comment by SDAdham** [comment]
> Have the same issue. I tried to investigate the source code of the `@nguniversal/builders` package and I discovered that if I increase the number of attempts here:
> 
> https://github.com/angular/universal/blob/3ca407beb3a4f5d96f140cf47c259f80b62f3ae5/modules/builders/src/ssr-dev-server/utils.ts#L79
> 
> then it works well.
> It seems like my app doesn't boot fast enought to be connected to the dev-ssr process before the number of attempts are exceeded.

Thank you very much @marekberger , you are genius. I was suffering because of this.

**Comment by Tim-mhn** [comment]
> 
> 
> Have the same issue. I tried to investigate the source code of the `@nguniversal/builders` package and I discovered that if I increase the number of attempts here:
> 
> https://github.com/angular/universal/blob/3ca407beb3a4f5d96f140cf47c259f80b62f3ae5/modules/builders/src/ssr-dev-server/utils.ts#L79
> then it works well.
> 
> It seems like my app doesn't boot fast enought to be connected to the dev-ssr process before the number of attempts are exceeded.

Did you actually edit the file in the node_modules folder ? That doesn't sound like a viable solution :/

**Comment by xraybrain** [comment]
> Have the same issue. I tried to investigate the source code of the `@nguniversal/builders` package and I discovered that if I increase the number of attempts here:
> 
> https://github.com/angular/universal/blob/3ca407beb3a4f5d96f140cf47c259f80b62f3ae5/modules/builders/src/ssr-dev-server/utils.ts#L79
> 
> then it works well.
> It seems like my app doesn't boot fast enought to be connected to the dev-ssr process before the number of attempts are exceeded.

thanks bro

**Comment by yura-moryliak** [comment]
> Have the same issue. I tried to investigate the source code of the `@nguniversal/builders` package and I discovered that if I increase the number of attempts here:
> 
> https://github.com/angular/universal/blob/3ca407beb3a4f5d96f140cf47c259f80b62f3ae5/modules/builders/src/ssr-dev-server/utils.ts#L79
> 
> then it works well.
> It seems like my app doesn't boot fast enought to be connected to the dev-ssr process before the number of attempts are exceeded.

So as i understand it's just temporary solution, any updates with permanent solution?

My environment: NG13 + NestJS + NgUniversal - npm run dev:ssr - spit's out same issue...

**Comment by martinsotirov** [comment]
I'm struggling with this issue in one of my Angular containers for development purposes. No value for `attempts` seems to fix it. Tried up to 200.

**Comment by SDAdham** [comment]
@martinsotirov is it consistent or sometimes randomly that it happens?

**Comment by martinsotirov** [comment]
@SDAdham I consistently can't launch our rather heavy and slowly building Angular app with the ssr dev server in a Docker container, while a vanilla demo app with nguniversal added on top always launches correctly on port  4200.

**Comment by valeri879** [comment]
> @martinsotirov is it consistent or sometimes randomly that it happens?

you should update all dependencies in same version, for me this was an issue.

**Comment by bageren** [comment]
I just tried installing angular universal in angular 13 app. When I run yarn dev:ssr, after it says "Compiled succesfully" it seems like it prints out the entire dist/server/main.js in red, and at the bottom it just says: 

```
A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:57222
```

How am I supposed to debug this?

**Comment by valeri879** [comment]
> I just tried installing angular universal in my angular 13 app. When I run yarn dev:ssr, after it says "Compiled succesfully" it seems like it prints out the entire dist/server/main.js in red, and at the bottom it just says: 
> 
> ```
> A server error has occurred.
> node exited with 1 code.
> connect ECONNREFUSED 127.0.0.1:57222
> ```
> 
> How am I supposed to debug this?

You should update all dependencies to same version, for me this was an issue

**Comment by bageren** [comment]
I tried running yarn serve:ssr instead which also also failed but it printed some useful errors in my console. In my case it was caused by usage of the window. I added a couple of if statements and now it works.

**Comment by Berihugebre** [comment]
Hey @bageren  can you mention the couple of if statements? it is something like this?
`
constructor(@Inject(PLATFORM_ID) private platformId: Object)
`
and then
`
 if(isPlatformBrowser(this.platformId)){
   // access window here
 }
`

Thanks

**Comment by bageren** [comment]
@Berihugebre Exactly. If you don't want if statements all over your app, alternatively you can make a window provider which provides the real thing in the browser and a mock on the server.

**Comment by jitterbox** [comment]
I get this same error trying to enable SSR with a .NET 6/Angular 14 app, but only when `architect:server:options:main` is set to `src\main.server.ts`. When I set it to `server.ts`, I get a "the module at ...\main.js does not export a default function" [error via a **NodeInvocationException**](https://github.com/dotnet/AspNetCore.Docs/issues/12434).

The Angular Universal [downloadable sample](https://angular.io/generated/zips/universal/universal.zip) shows it set to `server.ts`, but [this super-helpful article](https://pieterjandeclippel.medium.com/server-side-rendering-in-asp-net-core-angular-2022-version-7aaed8157976) points it to `src\main.server.ts`. Which should it be?

@alan-agius4 & Angular team, with Microsoft [obsoleting ](https://github.com/dotnet/aspnetcore/issues/12890) their `SpaServices` and `NodeServices` three years ago now, can the community _implore_ you guys again to reach out to Microsoft and create a doc/repo of unified guidance for developing _and_ deploying .NET/Angular projects **with Angular Universal SSR**? We're working with sticks and rocks from kind-hearted community members and a dozen dead-end StackOverflow threads.

**Comment by kirylvarykau** [comment]
I found a solution for this. Well, I don't like it but what can we do. 

So, actually `builder` passes process.env['PORT'] as a random number. So what you could do is just use it. 

`
> port = parseInt(process.env['PORT'] ?? '4000');
> this.app.listen(port, () => {
>    Logger.info('Node Express server listening.', { port }); // ----> you'll see the actual port here
> });
`

I've tried to set port in `angular.json` file, but it doesn't help. It seems like it uses 0 by default. The interesting moment, that you application will be available on two ports: 4200 and the random port you got by `dev-server`. 

Maybe it runs a webpack listener and proxies request from 4200 to <random port>, but I hope it would help someone

**Comment by CharlieGreenman** [comment]
For me I found the error was caused by passing in `--port=4200`to my package json script. As soon I removed that, it started to work as expected.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by jitterbox** [comment]
I understand why this was closed and that resources are limited, but for cases like this that are experienced by a significant number of users who aren't able to identify the source of the issue, can the @nguniversal team consider handling these more like customer service requests than backlog items, and help share the repro burden? Maybe have an intern look at it? Even if it's not bug-related, it's clearly still a common "gotcha"; there's value in finding and documenting the cause and any workarounds.

**Comment by alan-agius4** [comment]
Hi @jitterbox, The issue seems to have been caused by back setups. At least based on the comments as such this is not actionable from our end right now.

Unfortunately, there is no reproduction attached to this issue, as such there is no way we can investigate the problem. If you still have the problem please file a new issue with a minimal reproduction. This also is an OSS project and PRs are welcome.
