### ISSUE TITLE
TLS (https) on the server

### ISSUE THREAD

**Issue by Flo0806** [angular/universal#1849]
Hi all.

I'm playing around with Angular Universal right now. Now I have a problem for which I have not found any documentation.
I created my project (build: ssr), loaded it on my server, started Node and called the page in the browser. It's going well. However, I can't find a way to activate https.
In the "server.ts" I tried the following:

```
const server = require('https').createServer(credentials, app);
server.listen(port, () => {
console.log(`Node Express server listening on http://localhost:${port}`);
});
```

Unfortunately without success. Node was starting - no error. The server was listening. But the page loads into the blank - no error (timeout at some point). Can someone help me?

Thx, Flo

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
