### ISSUE TITLE
Issue Regarding Gsap with anuglar universal

### ISSUE THREAD

**Issue by shreyas-1997** [angular/universal#1857]
hello Sir!
I have Developed a website in angular using gsap for the animations and much more and also it's work properly on CSR(Client Side Rendering).But i want to Rendered this app on SSR(Server Side Rendering) because of SEO purpose..for that i used angular universal .After using angular universal i am facing one issue i.e.. (intermediate value)(intermediate value).getBoundingClientRect is not a function. Here is the screenshot of the error
![image](https://user-images.githubusercontent.com/66195578/95168144-7c992200-07ce-11eb-8ba8-dd9bd60c3528.png)

I am getting this error only on SSR by using angular universal. Please guide or help me to fix this issue because i am working around since 2 weeks basically it is coming from gsap packages .if i removed that package then its works fine as expected but when reused that plugin than it's through the error (intermediate value)(intermediate value).getBoundingClientRect is not a function

Here is my project Repositary:-https://github.com/shreyas-1997/Angular-Development

Thank you so much! I hope i will get solution here asap..

**Comment by moczix** [comment]
getBoundingClientRect is DOM api, on SSR you cant access DOM. Try to use ifPlatformBrowser

**Comment by shreyas-1997** [comment]
I used that but still not working see the line number 647
![image](https://user-images.githubusercontent.com/66195578/95199795-0a8b0200-07fb-11eb-8840-2b86efdf426d.png)

**Comment by moczix** [comment]
Im guessing your library, tweenMax is using some global state of window right in bundle. Try to load it dynamically in your if condition. You can also try to load it dynamically, this way ssr should not load this chunk on ssr

**Comment by shreyas-1997** [comment]
Can you elaborate in more simple way

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
