### ISSUE TITLE
Issues with Lighthouse and Largest Contentful Paint when using Prerendering

### ISSUE THREAD

**Issue by initplatform** [angular/universal#1858]
# 🚀 Feature request

Prerendered sites are getting pinged by Largest Contentful Paint even if the user won't notice the LCP

I've commented on a git issue started by @h3d0 

https://github.com/GoogleChrome/lighthouse/issues/10845

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
Prerendered sites are getting pinged by Largest Contentful Paint even if the user won't notice the LCP

### Describe the solution you'd like

I'm not really sure of a solution. In my case, the components are replaced in the DOM, but no change or content shift occurs. I just wanted to start a conversation and raise awareness of this issue. 

### Describe alternatives you've considered

No Alternatives. Prerendering is super exciting for large sites to be able to deliver fast initial payloads and then enhance the site, but issues like this are disheartening.

**Comment by initplatform** [comment]
@h3d0 just pointed me here -> https://github.com/angular/angular/issues/13446

**Comment by alan-agius4** [comment]
Let continue tracking this in https://github.com/angular/angular/issues/13446
