### ISSUE TITLE
Build error after pg-promise integration. Module not found: Error: Can't resolve 'pg-native'

### ISSUE THREAD

**Issue by Halynsky** [angular/universal#1861]
# 🐞 Bug report

#### What modules are related to this issue?
- [x] builders

### Is this a regression?

I don't know

### Description
I am trying to prepare an app with my favorite nodejs libs and PostgreSQL database. But after adding pg-promise I have got an error at build time. Maybe there is some workaround with this issue? Thx.

## 🔬 Minimal Reproduction
1 - add "pg-promise" library
2 - run build:ssr

## 🔥 Exception or Error
<pre><code>
ERROR in ./node_modules/pg/lib/native/client.js
Module not found: Error: Can't resolve 'pg-native' in '...\node_modules\pg\lib\native'
</code></pre>

## 🌍 Your Environment
<pre><code>
@angular-devkit/architect         0.1000.2
@angular-devkit/build-angular     0.1000.2
@angular-devkit/build-optimizer   0.1000.2
@angular-devkit/build-webpack     0.1000.2
@angular-devkit/core              10.0.2
@angular-devkit/schematics        10.0.2
@angular/cli                      10.0.2
@ngtools/webpack                  10.0.2
@nguniversal/builders             10.0.1
@nguniversal/common               10.0.1
@nguniversal/express-engine       10.0.1
@schematics/angular               10.0.2
@schematics/update                0.1000.2
rxjs                              6.5.5
typescript                        3.9.5
webpack                           4.43.0

"express": "4.15.2",
"inversify": "5.0.1",
"pg-promise": "10.6.1"
</code></pre>

**Comment by Mhd-Adnan-Askar** [comment]
please any updates on this ???

**Comment by RiggedToBlow** [comment]
Yes I'm having the same issue when installing pg `npm i pg`

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/universal/issues/1508#issuecomment-586283291

**Comment by Halynsky** [comment]
@alan-agius4 Thank you very much!
It would be nice to mention this solution somewhere in the documentation in the future.
Also, I can provide some simple examples of nodejs backend + angular universal full-stack app starter project if you need that.

Solution for this case:
```
  "server": {
    "builder": "@angular-devkit/build-angular:server",
    "options": {
      "outputPath": "dist/server",
      "main": "server.ts",
      "tsConfig": "tsconfig.server.json",
      "externalDependencies": [
        "pg"
      ]
    },
    ...
  }  
```
