### ISSUE TITLE
RxJs compatibility bug with a local npm link

### ISSUE THREAD

**Issue by CraigComeOnThisNameCantBeTaken** [angular/universal#1865]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x ] express-engine
- [ ] hapi-engine

### Is this a regression?
Unknown

### Description
When serverside rendering my app locally I get the following error:

TS2322: Type 'import("D:/myApp/node_modules/rxjs/internal/Observable").Observable<boolean>' is not assignable to type 'import("D:/myLibrary/node_modules/rxjs/internal/Observable").Observable<boolean>'.

 A clear and concise description of the problem...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Kindly see: https://angular.io/guide/creating-libraries#linked-libraries
