### ISSUE TITLE
Angular 7 universal router outlet not generating source code in lazy loading

### ISSUE THREAD

**Issue by shafqatjan** [angular/universal#1867]
Whem i m not doing lazyloading it is generating by using TransferHttpCacheModule but when im doing with modules lazy loads router outlets are empty, what can be the issue.
**SERVER.TS**
import 'reflect-metadata';
import 'zone.js/dist/zone-node';
import { enableProdMode } from '@angular/core';
import { ngExpressEngine } from '@nguniversal/express-engine';
import { provideModuleMap } from '@nguniversal/module-map-ngfactory-loader';
import * as express from 'express';
import { join } from 'path';
import * as path from 'path';
import { renderModuleFactory } from '@angular/platform-server';
import { APP_BASE_HREF } from '@angular/common';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';
import * as morgan from 'morgan';
import * as compression from 'compression';
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
enableProdMode();
export const app = express();
const ROOT = path.join(path.resolve(__dirname, '../..'));
app.use(compression());
app.use(cookieParser('Angular 2 Universal'));
app.use(bodyParser.json());
app.use(morgan(<any>'dev'));
function cacheControl(req, res, next) {
  res.header('Cache-Control', 'max-age=3600000');
  next();
}
app.use(cacheControl, express.static(ROOT, {index: false}));
const PORT = process.env.PORT || 4200;
const DIST_FOLDER = join(process.cwd(), 'dist/browser');
const domino = require('domino');
const fs = require('fs');
const template = fs.readFileSync(join(DIST_FOLDER, 'index.html')).toString();
const win = domino.createWindow(template);
global['window'] = win;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['navigator'] = win.navigator;
global['Event'] = win.Event;
global['Event']['prototype'] = win.Event.prototype;
Object.defineProperty(win.document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true
    };
  },
});
global['document'] = win.document;
global['CSS'] = null;
const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist/server/main');
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));
app.set('view engine', 'html');
app.set('views', DIST_FOLDER);

app.get('*.*', express.static(DIST_FOLDER, {
  maxAge: '1y'
}));
app.get('*', (req, res) => {
  res.render('index', {
    req, providers: [
      { provide: APP_BASE_HREF, useValue: req.baseUrl },
      { provide: REQUEST, useValue: req, },
      { provide: RESPONSE, useValue: res, },
      { provide: 'serverUrl', useValue: req.originalUrl }
    ]
  });
});
**APP.MODULE**
let redirectRoutes: Routes = [];

const errorRedirection: Routes = [
  { path: '**', redirectTo: '404' }
];

const routes: Routes = [
  ...redirectRoutes,
  ...no_lang_routes,
  ...en_routes,
  ...fr_routes,
  ...nl_routes,
  ...dk_routes,
  ...errorRedirection
];
@NgModule({
  declarations: [
    AppComponent,
    ActivateAccountComponent,
    ResetComponent,
    UnderConstructionComponent,
    UnsubscribeNewsletterComponent,
    MaintenanceComponent,
    ExceptionLogsComponent,
    RedirectComponent,
    ConfirmRegisterDialog
  ],
  schemas: [NO_ERRORS_SCHEMA],
  imports: [
    BrowserModule.withServerTransition({ appId: 'app-root' }),
    SharedModule,
    RouterModule.forRoot(routes, {
      onSameUrlNavigation: 'reload',
      scrollPositionRestoration: "enabled",
      preloadingStrategy: PreloadAllModules
    }),
    NgtUniversalModule
  ],
  exports: [],
  providers: [
    TransferHttpService,
  ],
  entryComponents: [ConfirmRegisterDialog],
  bootstrap: [AppComponent]
})
export class AppModule { }

**HOME.MODULE**

import { NgModule } from '@angular/core';
import { SharedModule } from '../shared.module';
import { HomepageComponent, HomepagePopupDialog } from './homepage/homepage.component';
import { CountUpModule } from 'countup.js-angular2';
import { ScrollEventModule } from 'ngx-scroll-event';
import { RouterModule, Routes } from '@angular/router';
const routes: Routes = [
  { path: '', component: HomepageComponent }
];
@NgModule({
  declarations: [
    HomepageComponent,
    HomepagePopupDialog
  ],
  entryComponents: [HomepagePopupDialog],
  exports: [],
  imports: [
    SharedModule,
    RouterModule.forChild(routes),
    CountUpModule,
    ScrollEventModule
  ]
})
export class HomeModule { }

**Comment by alan-agius4** [comment]
Kindly follow issue template and provide a minimal reproduction.

Note: Angular 7 is no longer supported by the Angular team. The current LTS is version 8, and it’s support will terminate on the 28th November 2020. See: https://angular.io/guide/releases#support-policy-and-schedule
