### ISSUE TITLE
Express Engine has incorrect type

### ISSUE THREAD

**Issue by ocket8888** [angular/universal#1869]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?
Yes, the previous version in which this bug was not present was: 8.3

### Description
The typing of the callback parameter of `ngExpressEngine`'s return type is incorrect:

```
	server.engine("html", ngExpressEngine({
		bootstrap: AppServerModule,
	}));
```
fails to compile with: 
```
Argument of type '(filePath: string, options: Readonly<RenderOptions>, callback: (err?: Error | null | undefined, html?: string | undefined) => void) => void' is not assignable to parameter of type '(path: string, options: object, callback: (e: any, rendered: string) => void) => void'.
  Types of parameters 'callback' and 'callback' are incompatible.
    Types of parameters 'rendered' and 'html' are incompatible.
      Type 'string | undefined' is not assignable to type 'string'.
        Type 'undefined' is not assignable to type 'string'.
```

## 🔬 Minimal Reproduction
This problem only surfaces when compiling with `strictNullChecks` set to "true" - because otherwise `string` *is* assignable to `string | undefined`. So create a new project, enable strict null checks in the compiler, and try to build ssr.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 13.14.0
OS: linux x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@ngtools/webpack                  9.1.12
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi @ocket8888,

This should no longer be an issue in version 10. 

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.

**Comment by ocket8888** [comment]
appears to work in v10 - but should that fix get backported to 9?

**Comment by alan-agius4** [comment]
Version 9 is currently in LTS and only critical security fixes are applied.
