### ISSUE TITLE
Fastify Engine

### ISSUE THREAD

**Issue by Sikora00** [angular/universal#1871]
# 🚀 Feature request

#### What modules are relevant for this feature request?
- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
- [x] a new one

### Description
[@nestjs/ng-universal](https://github.com/nestjs/ng-universal) successively combine Angular, Angular Universal, NestJS and its features. The only exception is that NestJS is trying to strongly support Fastify what is not achieved in nestjs/ng-universal yet nestjs/ng-universal#3. What makes it even more important we can see that missing support for Fastify is slowing down the new features for Express powered apps nestjs/ng-universal#164. I have tried to add the implementation for Fastify, but as the implementation for Express uses an official package from angular/universal the custom one for Fastify can be considered as not stable enough.

### Describe the solution you'd like
There should be an official fastify-engine package.

### Describe alternatives you've considered
Creating 3rd party packages with CommonEngine #1733

**Comment by sod** [comment]
I can highly suggest fastify. We switched from express to fastify for our ssr pretty early on and got higher throughput and predictable response times.

**Comment by alan-agius4** [comment]
Kindly see: https://github.com/angular/universal/pull/1892
