### ISSUE TITLE
Update universal type definition

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#188]
Right now the type definition file only contains three values:

https://github.com/angular/universal/blob/master/modules/universal/universal.d.ts

Add more of what is actually exposed from the library:

https://github.com/angular/universal/blob/master/modules/universal/server/server.ts

For example, the server-side version of HTTP_PROVIDERS.

**Comment by gdi2290** [comment]
a couple of types were added
```
export var SERVER_LOCATION_PROVIDERS: [any];
export var BASE_URL: string;
export var HTTP_PROVIDERS: [any];
```
