### ISSUE TITLE
i18n multilingual routes - @nguniversal/builders:prerender

### ISSUE THREAD

**Issue by muehle28** [angular/universal#1893]
My app is using multilingual routes. The route definition in the app.module.ts is looking like the following:
 
`{ path: $localize`:@@app.routes.menu:menu`, component: MenuComponent, pathMatch: 'full' }`

Since the ivy update this is working fine.

It would be useful to be able to prerender different routes per language. My angular.json prerender definition is looking like: 

```
"prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "browserTarget": "app:build:production",
            "serverTarget": "app:server:production",
            "routesFile": "./routes.txt"
          }
}
```

It is not possible to prerender different routes per locale.

A solution would be to use the $localize`:@@app.routes.menu:menu` syntax in the routeFile or to add a routeFile per locale.

**Comment by alan-agius4** [comment]
@muehle28, can you please provide a reproduction? It would greatly speed up the process of looking into this.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

Thanks

**Comment by muehle28** [comment]
[Here](https://github.com/muehle28/universal-prerender) you find the repo.
You can start the prerendering by `npm run prerender:all`
All paths are generated, but the routenames are changing from language to language. There is no possibility to say which path belongs to which language.

**Comment by alan-agius4** [comment]
@muehle28, You'd need to specify a separate `routesFile` for each configuration.

**Comment by muehle28** [comment]
Do I have to start the whole prerender process for every locale individually?
npm run prerender:en
npm run prerender:it
npm run prerender:de
