### ISSUE TITLE
setting hostname and https 

### ISSUE THREAD

**Issue by boban984** [angular/universal#1894]
# 🚀 Feature request
I am using the default project created by Angular CLI and then adding SSR as described in the Angular Guide.
There is no documentation for setting SSL so i can serve the project on https in development.
Also i can change the host name, for non SSR it's easy just use "host" option in angular.json.
Adding the feature to set host name and https would be great.

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
SSL is currently not possible during development and is is being tracked here https://github.com/angular/universal/issues/1633

As for the host, you can set it up using the `host` option either via command line or in angular.json.

See: https://github.com/angular/universal/blob/master/modules/builders/src/ssr-dev-server/schema.json for a full set of available options.
