### ISSUE TITLE
The target entry-point "@nguniversal/express-engine" has missing dependencies

### ISSUE THREAD

**Issue by eng-dibo** [angular/universal#1896]
I added "Universal" to a fresh Angular project using the cli command `ng add @nguniversal/express-engine`, it installs `@angular/platform-server`,

but when I run `ng run cms:server:production`, I got the error 
```
ERROR in The target entry-point "@nguniversal/express-engine" has missing dependencies:
 - @angular/platform-server
```

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by eng-dibo** [comment]
[Solved] The issue was from npi-cache that prevents to install all the required packages (some @angular/* packages are installed, but @angular/platform-server didin't). 

I cleaned the npm cache and installed all packages again, and it worked, so I'm closing the issue.
