### ISSUE TITLE
switch preboot from browserify to rollup.js

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#190]
Refactor client code bunding (used for preboot code generation) as a module under `modules/` we need this for pre-rendering. We can also rethink how it's done via webpack after the initial refactor

**Comment by jeffwhelpley** [comment]
I get the request to move from browserify to webpack, but what exactly are you suggestion should be a separate module? What is the issue that is prompting this?

**Comment by jeffwhelpley** [comment]
OK, so I am switching gears for this issue. The thing is that we need the output of preboot to be as small as possible. The output of rollup.js is a lot less than webpack, so I suggest we try that out. Note that this task should just be switching the bundling tool. There is a separate task for optimizing the size of our custom code (i.e. #257). If for whatever reason rollup.js doesn't work, we can do webpack.

**Comment by jeffwhelpley** [comment]
Closing this since really the goal is #257. The solution may not include rollup but some other solution such as webpack 2.
