### ISSUE TITLE
Express-engine res.render freezes app.

### ISSUE THREAD

**Issue by impulsenok** [angular/universal#1900]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] express-engine

### Is this a regression?

nope

### Description

I'm trying to implement FaceBook sharing functionality, in that case i'm using the minimum of Universal features. It is as simple, as that: i added middleware to handle some urls, where i'm making an additional request to get movie data, then render index.html with appropriate <og> tags(replace defaults with previously received movie data) that FaceBook required for its crawlers.
It is working properly with routes like `localhost:4000/content/movies/:id` and `localhost:4000/content/series/:id`, but the problem occures when i'm trying to handle `localhost:4000/content/music/songs/:id`. For some reason, `res.render` is not executed.

## 🔬 Minimal Reproduction
I found the place in `main.js` bundle, where everything stops: it is `function ngExpressEngine(setupOptions)`, after `const extraProviders = ...` there is `getFactory(moduleOrFactory, compiler)` function, in first promise, after it gets `factory`, there is construction: `return Object(platform_server["renderModuleFactory"])(factory, {extraProviders});` - it returns nothing. Nothing resolved, nothing rejected.
I'm using simple `res.render('index', {req, res}, (err, html) => {...}` without any custom options.

## 🔥 Exception or Error
No errors, nothing, just freezed app, there is pending status on client-side.

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.29
Node: 12.18.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.29
@angular-devkit/build-angular              0.803.29
@angular-devkit/build-optimizer            0.803.29
@angular-devkit/build-webpack              0.803.29
@angular-devkit/core                       8.3.29
@angular-devkit/schematics                 8.3.29
@angular/cdk                               8.2.3
@angular/cli                               8.3.29
@angular/material                          8.2.3
@ngtools/webpack                           8.3.29
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.29
@schematics/update                         0.803.29
rxjs                                       6.5.4
typescript                                 3.5.3
webpack                                    4.39.2

</code></pre>

Guys, what i wanted to add, i would like to kindly ask you to improve docs. For me it is not clear for what reason i can change `Url`, it is just described that developer can do it. Maybe i have to do something with Url in my case, but i don't understand what.

Thank you in advance!

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by impulsenok** [comment]
Morning @alan-agius4. I will try to take care about repro today. Thnks in advance!

**Comment by impulsenok** [comment]
Was closed because everything works fine on app reproduction. Will try to investigate inside app.
P.S. more details DOCs are required, improve them please
