### ISSUE TITLE
Showing Login page for a second 

### ISSUE THREAD

**Issue by sai-ui** [angular/universal#1902]
Hello everyone,

I have the following problem with angular and SSR. I use angular 10. Everything works fine but when
I click F5/refresh I'm getting login screen for a second even after successful login. In user profile all routes working fine but if refresh the page it shows login page first and showing the page as per the routing. May be the server is not aware if the user is authenticated.

Any suggestion?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
