### ISSUE TITLE
Migration to Angular Universal does not working

### ISSUE THREAD

**Issue by BrandonQuintanilla** [angular/universal#1903]
Executed with a  functional webApp: 
1. ng add @nguniversal/express-engine --clientProject [name] 
-server module and many other files created as documentation guides
2. npm run build:ssr && npm run serve:ssr
-Builds dist(browser and server) folder for dynamic SSR. Can run at localhost and be deployed in AWS with ProcFile(web: node dist/[projectName]/server/main.js). 
The problem comes when execute "curl [url:port]"(that is executed by crawlers) returns empty <app-root>. The consequence is that our webApp is still not SEO friendly. 
I find that many "server" tags are added in this angular universal version when I inspect html, but the "curl" command and social media crawlers shows only index.html content. I suppose that there is some problem with server side rendering. 
The webApp consumes rest services from a private api, it may generate some problem with the livecycles during the server side rendering?

**Comment by alan-agius4** [comment]
Closing as the issue template is not followed and no reproduction has been provided.

Please file a new issue and follow the issue template. 

Thanks.
