### ISSUE TITLE
anuglar-universal in deployment not using ssr

### ISSUE THREAD

**Issue by closeSupply** [angular/universal#1905]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: NO_VERSION

### Description

 A clear and concise description of the problem: I want to test the angular-universal project bevor I upload it to the server. So I copied the browser files to XAMPP where they get hosted to the localhost. I run the server.js or main.js with node main.js. The express server listens on 127.0.0.1:4000, but angular isn't using it. when I look into the source of the served page I can see it is a normal angular and no signs of ssr.

## 🔥 Exception or Error
<pre>angular not using ssr<code>

</code></pre>

## 🌍 Your Environment
<pre>XAMPP and pm2<code>

</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
