### ISSUE TITLE
Refactor universal folder structure

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#191]
currently
```
universal/
  client/
  dist/
    client/
    server/
  server/
```
which should be 
```
universal/
  src/
    client/
    server/
  dist/
    client/
    server/
```

**Comment by gdi2290** [comment]
the file paths need to be consistent for browser field metadata spec https://github.com/defunctzombie/package-browser-field-spec and `examples/` folder

**Comment by jeffwhelpley** [comment]
Duplicate of #194
