### ISSUE TITLE
Angular Universal only for specific routes

### ISSUE THREAD

**Issue by KumarKaruppaiah** [angular/universal#1915]
I want to implement the social media sharing only for two pages. So I am using Angular Universal in order to render the pages on the server side. But I don't want to run all the pages in  my application on the server since I am getting too much incompatible issues in all the pages. So I want to run only two pages in my application on the server side. I am searching for the solution for the past few days, and I was not able to find it.

Is it possible to run only specific routes on SSR ?

It would be very helpful if you assist me.

Thanks.

**Comment by alan-agius4** [comment]
Yeah, and this is pretty straightforward to do.

You need to do something like the below in your `server.ts`
```diff
+  const staticRoutes = ['/home', '/contact-us'];
  server.get('*', (req, res) => {
+    if (staticRoutes.includes(req.path)) {
+      res.sendFile(indexHtml);
+    } else {
      res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
+   }
  });

```
