### ISSUE TITLE
TransferState.onSerialize corrupting state transferring

### ISSUE THREAD

**Issue by d46** [angular/universal#1919]
# 🐞 Bug report
Took 2 days before getting mad.

#### What modules are related to this issue?
@angular/platform-browser

### Is this a regression?
Yes

### Description
When to use callback of `transferState.onSerialize` for the debug purpose, it is overriding the actual behaviour and then the state is not transferring.
 
### Minimal reproduce
```javascript
.. key = makeStateKey<any>('some-key')
transferState.onSerialize(
      key,
      () => {
        console.log(
          transferState.get(key, {})
        );

        console.log('serializing');
      }
);
```

**Comment by alan-agius4** [comment]
Hi @d46,

The above `onSerialize` Is not implemented corrected. The handler doesn’t appear to be implemented correctly as it should return the value of the key. 

See: https://angular.io/api/platform-browser/TransferState#onserialize
