### ISSUE TITLE
document how to swap files per environment at build-time

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#192]
during a build for something like webpack you're able to swap files per environment (browser/server)

spec: https://github.com/defunctzombie/package-browser-field-spec

webpack: support diffrent packages https://github.com/webpack/webpack/issues/151
systemjs: only supports browser https://github.com/systemjs/systemjs/issues/860
browserify: only supports browser (they created the field)

**Comment by jeffwhelpley** [comment]
Added this to the brain dump doc:

https://docs.google.com/document/d/1Qem6PJ1EO5tYpGxfpj5w-4kuykW072GCrC3FmWI3_yY/edit?usp=sharing

Will be tracking with #258.
