### ISSUE TITLE
Guide for using DOM-using libraries(like plotly.js)

### ISSUE THREAD

**Issue by alanpurple** [angular/universal#1926]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [V] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader

### Description
 A clear and concise description of the problem or missing capability...
how to use dom-using libraries( like plotly.js ) with ng-universal

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
some workaround for plotly.js(or angular-plotly.js)

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
or tell me if this is impossible

**Comment by TatyanaMolchanova** [comment]
I would like this guide for using Bootstrap or Angular Material modals and popups, toasts with Universal Angular.

**Comment by alan-agius4** [comment]
We are looking into improving this docs in the near future. Let's track this in https://github.com/angular/universal/issues/1732
