### ISSUE TITLE
Angular 11 express engine not updating any updates which happened in client side in view source

### ISSUE THREAD

**Issue by MobackChetanKumar** [angular/universal#1928]
Once View source generated in server side and if any updates in client side like updating meta tags or insert new script dynamically those content is not updating in the view page source.
On click updating the script inside head tag the route schema is not showing in the view page source.
`const script = document.createElement('script');
script.setAttribute('type', 'application/ld+json');
script.async = true;
script.src = 'assets/data/' + routeName + '-schema.js';
document.head.appendChild(script);`

also data received from API is also not updating.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
