### ISSUE TITLE
remove server-patch. Create polyfills module

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#193]
we should create our own context and patch that environment or allow the developer to include their own polyfills

**Comment by manekinekko** [comment]
@gdi2290 please assign this one to me ;)

**Comment by jeffwhelpley** [comment]
I am a little confused by this one. @manekinekko it looks like you submitted a PR for this one but was it abandoned? Is this still something you are looking at?

**Comment by manekinekko** [comment]
@jeffwhelpley check this PR https://github.com/angular/universal/pull/230

**Comment by jeffwhelpley** [comment]
Ah, got it.

**Comment by manekinekko** [comment]
@gdi2290 could we close this one?

(cc @jeffwhelpley)
