### ISSUE TITLE
Refactor repo folder structure

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#194]
Every module (within `modules/`) should own their own build tools etc. The `examples/` should also live at the top level and we require the other modules either by alias from build tool or npm file map. Shared build tool should also live in `modules/` or `build/`.

**Comment by jeffwhelpley** [comment]
Are you thinking we would not have any build tools at the root?

**Comment by jeffwhelpley** [comment]
Merging notes from #191 


the file paths need to be consistent for browser field metadata spec https://github.com/defunctzombie/package-browser-field-spec and examples/ folder

currently

universal/
  client/
  dist/
    client/
    server/
  server/
which should be

universal/
  src/
    client/
    server/
  dist/
    client/
    server/
