### ISSUE TITLE
Cannot control which routes are prerendered

### ISSUE THREAD

**Issue by inorganik** [angular/universal#1948]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

Unsure

### Description

Before posting this issue, I searched high and low for any documentation around prerendering, and have only found third-party articles describing the process, and but no official docs - so posting this as a last resort

The issue is: Angular attempts to prerender many more routes than what I list in angular.json, and I can't prevent it from doing so. In angular.json:
```json
"prerender": {
"builder": "@nguniversal/builders:prerender",
"options": {
  "browserTarget": "podcasts11:build:production",
  "serverTarget": "podcasts11:server:production",
  "routes": [
    "/",
    "/doc"
  ]
},
```
But after running `npm run prerender`, in /dist/podcasts11/browser:
```
📁 about
📁 foo
📁 bar
📁 baz
📁 doc
...
index.html
...
```
Particularly, this happens with auth-guarded routes, and Angular prerenders a bunch of sign-in pages. As I understand something called "guess parser" is controlling what routes are rendered - but I don't want there to be any _guessing_, because it guesses wrong. 🙂 

## 🔬 Minimal Reproduction

Here is a new Angular 11 project that reproduces the issue: https://github.com/inorganik/podcasts

1. Run `npm i`
2. Run `npm run prerender`
3. Look in dist folder and see all the extra prerendered routes

## 🔥 Exception or Error

No errors, just unwanted prerendered routes

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.0.5
Node: 14.7.0
OS: darwin x64

Angular: 11.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.5
@angular-devkit/build-angular   0.1100.5
@angular-devkit/core            11.0.5
@angular-devkit/schematics      11.0.5
@angular/cdk                    11.0.3
@angular/fire                   6.1.4
@angular/material               11.0.3
@nguniversal/builders           11.0.1
@nguniversal/express-engine     11.0.1
@schematics/angular             11.0.5
@schematics/update              0.1100.5
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Comment by alan-agius4** [comment]
Hi,

You need to disable `guessRoutes`.

https://github.com/angular/universal/blob/3e0efbeb2ad490caead49d53809af97ace6e03a7/modules/builders/src/prerender/schema.json#L30:L34

**Comment by inorganik** [comment]
Thanks. Wish this was documented somewhere 🙂 .

One more question, do you run prerendering _in lieu_ of `build:ssr`, or in addition?

**Comment by inorganik** [comment]
@alan-agius4 with the generated scripts,
```json
    "dev:ssr": "ng run project:serve-ssr",
    "serve:ssr": "node dist/project/server/main.js",
    "build:ssr": "ng build --prod && ng run project:server:production",
    "prerender": "ng run project:prerender",
```
is it safe to run the `prerender` script in lieu of `build:ssr`? It's a little confusing because the `build:ssr` script does a prod build, but it appears the `prerender` script does not. Thanks very much.
