### ISSUE TITLE
Angular SSR working for one module only not for other modules

### ISSUE THREAD

**Issue by UzairAshraf1314141** [angular/universal#1959]
Hello
I need your help to fix an issue with my angular application. I've moved my app to SSR but only one module is working perfectly but not others. There is not even an error in the console. 
If you need anything let me know.

I'll be waiting for your response.

Thanks.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
