### ISSUE TITLE
Observables and objects decorated with @input are being considered as readonly

### ISSUE THREAD

**Issue by kgcorner** [angular/universal#1967]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [X] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Working in CSR (Client-side rendering)

### Description

 A clear and concise description of the problem...
Objects passed as Input to child component and Observables are being considered as read-only
ERROR TypeError: Cannot assign to read only property 'offers' of object '[object Object]'
## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
