### ISSUE TITLE
✖ Service worker generation failed.

### ISSUE THREAD

**Issue by mazlano27** [angular/universal#1989]
# 🐞 bug report

✖ Service worker generation failed in CLI

### Is this a regression?

Yes, the previous version in which this bug was not present was: 11.1.2

### Description

After updating to Angular 11.2.0 from 11.1.2, running pre-rendering script results in the following error: 

✖ Service worker generation failed.
The "path" argument must be of type string. Received an instance of NodeJsSyncHost

**Comment by alan-agius4** [comment]
Fixed via https://github.com/angular/universal/pull/1984

**Comment by mazlano27** [comment]
> Fixed via #1984

I'm sorry, I don't understand what this means. Does this mean this issue will be fixed in the next update?

**Comment by alan-agius4** [comment]
Yes, that is correct.

**Comment by mazlano27** [comment]
> Yes, that is correct.

Thank you
