### ISSUE TITLE
ERROR in ./node_modules/swarm-js/node_modules/got/index.js Module not found

### ISSUE THREAD

**Issue by mshubhamtyagi** [angular/universal#1997]
Angular Global Version: 10.2.0
Angular Local Version: 10.1.0-next.5
OS: Windows

Hi Team,

I am facing an issue. I have installed **@nguniversal/express-engine** in my project. It installed successfully. When I tried to run my application with the command  **npm run dev:ssr** or if I am trying to build with the command **npm run build:ssr**. I am continually getting the below error:

**ERROR in ./node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve './package' in 'E:\ProjectPath\frontend\node_modules\swarm-js\node_modules\got'

ERROR in ./node_modules/swarm-js/node_modules/got/index.js
Module not found: Error: Can't resolve 'electron' in 'E:\ProjectPath\frontend\node_modules\swarm-js\node_modules\got'**

Please help me with this.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
