### ISSUE TITLE
How to add Cache-Control header to SSR response?

### ISSUE THREAD

**Issue by vkml** [angular/universal#2001]
Hi,
I need to add Cache-Control header to the response containing server-side rendered page. Tried to set using Express.js function `app.set()`, but cannot see it added at the client side.
```
server.get('*', (req, res) => {
    // this one is set without any issues
    res.set('Foo', 'fasfsf');

    // this one seems like it gets removed before sending to client side
    res.set('Cache-Control', 'max-age=1200');

    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] }, (err, html) => {
      ...
      }
      // can read header value here
      console.log(res.getHeader('Cache-Control'));
    });
  });
```

Client response:
```
< HTTP/1.1 200 OK
< foo: fasfsf
< content-type: text/html; charset=utf-8
< content-length: 456488
< etag: W/"6f728-ZRxLHUHtkGBkKEqipZdyMjJlcsY"
< date: Wed, 24 Feb 2021 16:20:15 GMT
< connection: close
< 
{ [65298 bytes data]
* Closing connection 0
```

As you can see, Cache-Control header is not present in the response.
Any idea what is the reason for such behavior and how can I overcome that?

**Comment by alan-agius4** [comment]
It is unclear if this is from the dev-server or from the actual server. 

If it's from the dev-server, the cache-control header is deliberately omitted.

**Comment by vkml** [comment]
Thanks for the reply, and yes that was dev-server build, tested header with production build and it works perfectly.
