### ISSUE TITLE
Is there any way to remove header from the script tag, included in SSR page?

### ISSUE THREAD

**Issue by vkml** [angular/universal#2008]
Hi,
Using SSR result in adding such script tag containing Backend API server response object:
```
<script id="serverApp-state" type="application/json">
...
&q;headers&q;:{&q;date&q;:[&q;Fri, 05 Mar 2021 12:44:26 GMT&q;],&q;content-type&q;:[&q;application/json; charset=utf-8&q;],&q;content-length&q;:[&q;2933&q;],&q;connection&q;:[&q;keep-alive&q;],&q;server&q;:[&q;nginx/1.18.0&q;],&q;vary&q;:[&q;origin,accept-encoding&q;],&q;cache-control&q;:[&q;no-cache&q;],&q;accept-ranges&q;:[&q;bytes&q;]}
...
</script>
```
How can I remove certain header (Date) from that object, so that final constructed HTML won't include that value? Considering that there is no chance of removing this HTTP header from Backend API response.

**Comment by alan-agius4** [comment]
Hi @vkml, 

Likely you can do this by using an HTTP interceptor. https://angular.io/guide/http#intercepting-requests-and-responses
