### ISSUE TITLE
Delay some content load for client side 

### ISSUE THREAD

**Issue by mohammedzamakhan** [angular/universal#201]
Sometimes the developer would want things like ads, or comments section to load progressively on the browser so that the page load faster. So if this has to be done with server renderering, how could this be achieved with angular universal?

**Comment by wesleycho** [comment]
I would think that one would do this by rendering that particular component purely on the client.

**Comment by jeffwhelpley** [comment]
Wesley is correct. The solution is to only have a particular component render on the client and not the server. We will eventually have a decorator that you can use on the component to specify client-only, but for now you can use the "browser" field in your package.json to give webpack (or whatever bundler you use) hints for how to replace one component with another.

https://github.com/defunctzombie/package-browser-field-spec

There is already an open issue to document exactly how this should work:

https://github.com/angular/universal/issues/192

I am going to close this for now, but feel free to ask follow up questions.
