### ISSUE TITLE
Better error reporting for non-universal dependencies

### ISSUE THREAD

**Issue by edbzn** [angular/universal#2017]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description

Hi there, 

I'm building an universal pre-rendered app and I had some issues related to non-universal code in my dependencies, now I know which dependency is failing but the error reporting when running the pre-render builder was not helping me. 

Here is the build output : 

```
✖ Prerendering routes to **********/browser failed.
Unable to render **********/browser/index.html.
Error: window is not defined
error Command failed with exit code 1.
```

Actually I can't figure out which dependency is failing, I need to remove by hand each module and rerun the builder to see which one is causing the error,  the more we have a big app the more it's time expensive. Hopefuly mine was relatively small. 

### Describe the solution you'd like

Could we point to the module which is causing the failure ?

### Describe alternatives you've considered

N/A

Thank you for your time.

**Comment by edbzn** [comment]
Related issue found https://github.com/angular/universal/issues/1371

**Comment by alan-agius4** [comment]
Unfortunately at this stage the code is bundled into a single file and the context of the modules is removed due to minification and removal of comments and sourcemaps not generated for production builds.

To track down such issue  you can disable minification, which should make analyzing the bundle easier.
