### ISSUE TITLE
feat(router): support for different urls

### ISSUE THREAD

**Issue by alexpods** [angular/universal#202]
Current implementation of `ServerLocationStrategy` doesn't support different urls. So the server renders default home page even if user requests page with `/some/other/url`. To solve this problem in my project I've implemented `ServerPathLocation`. Look at it [here](https://github.com/alexpods/angular2-universal-starter/blob/master/src/server/.universal/router.ts#L8) and if you like it I can create a pull request.

**Comment by manekinekko** [comment]
Hi @alexpods I think you should definitely create a PR.

**Comment by gdi2290** [comment]
:+1: @alexpods it would be awesome if you could make a PR

**Comment by gdi2290** [comment]
@alexpods what's the status on this PR?

**Comment by alexpods** [comment]
@gdi2290 I'm sorry, I was kinda busy these days. I'll do PR tomorrow morning (now midnight in Moscow, so in 12 hours PR will be done).

**Comment by gdi2290** [comment]
thanks!

**Comment by alexpods** [comment]
@gdi2290 I think we can close this issue since #218 was merged.
