### ISSUE TITLE
docs(readme): DOM vs DomAdapters vs Renderer

### ISSUE THREAD

**Issue by valorkin** [angular/universal#203]
Would be good to have in Style Guide note about interacting with DOM or any other native elements
Trying to avoid using BrowserDomAdapter and use Renderer instead

//cc @gdi2290

**Comment by manekinekko** [comment]
We could link to these two docs:
- Best Practices in the Universal readme: https://github.com/angular/universal#best-practices)
- The Web Worker documentation:  https://github.com/angular/angular/blob/eda6a5d52aa352825308f3345c41474c07f41b44/modules/angular2/docs/web_workers/web_workers.md#writing-webworker-compatible-components

**Comment by jeffwhelpley** [comment]
Added this to our brain dump doc that will be rolled into #258 

https://docs.google.com/document/d/1Qem6PJ1EO5tYpGxfpj5w-4kuykW072GCrC3FmWI3_yY/edit?usp=sharing
