### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by temitopeog** [angular/universal#2030]
What is the expected behavior?
serve:ssr -> run the app

What is the current behavior?
Error while running the app : serve:ssr

ReferenceError: Blob is not defined
    at Module.<anonymous> (/Users/temi/Desktop/app/dist/server.js:270154:12)
    at __webpack_require__ (/Users/temi/Desktop/app/dist/server.js:36:30)
    at Module.<anonymous> (/Users/temi/Desktop/app/dist/server.js:267771:75)
    at __webpack_require__ (/Users/temi/Desktop/app/dist/server.js:36:30)
    at Module.<anonymous> (/Users/temi/Desktop/app/dist/server.js:267514:88)
    at __webpack_require__ (/Users/temi/Desktop/app/dist/server.js:36:30)
    at Module.<anonymous> (/Users/temi/Desktop/app/dist/server.js:246422:75)
    at __webpack_require__ (/Users/temi/Desktop/app/dist/server.js:36:30)
    at Module.<anonymous> (/Users/temi/Desktop/app/dist/server.js:242990:66)
    at __webpack_require__ (/Users/temi/Desktop/app/dist/server.js:36:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! app@1.0.0 serve:ssr: `firebase deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the app@1.0.0 serve:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/i508752/.npm/_logs/2021-03-22T10_51_12_956Z-debug.log

Minimal reproduction with instructions:
Package.json
{
  "name": "app",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "npm run build:ssr",
    "build:functions": "npm run --prefix functions build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run app:serve-ssr",
    "serve:ssr": "firebase deploy",
    "compile:server": "webpack --config webpack.server.config.ts --progress --colors",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server && npm run build:functions",
    "prerender": "ng run app:prerender",
    "build:client-and-server-bundles": "ng build --prod && ng run app:server:production --bundleDependencies none"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~10.1.3",
    "@angular/cdk": "^10.2.3",
    "@angular/common": "~10.1.3",
    "@angular/compiler": "~10.1.3",
    "@angular/core": "~10.1.3",
    "@angular/fire": "^6.0.3",
    "@angular/flex-layout": "^10.0.0-beta.32",
    "@angular/forms": "~10.1.3",
    "@angular/material": "^10.2.3",
    "@angular/platform-browser": "~10.1.3",
    "@angular/platform-browser-dynamic": "~10.1.3",
    "@angular/platform-server": "~10.1.3",
    "@angular/router": "~10.1.3",
    "@angular/service-worker": "~10.1.3",
    "@nguniversal/express-engine": "^10.1.0",
    "bootstrap": "^4.5.2",
    "bufferutil": "^4.0.1",
    "cache-manager": "^3.4.0",
    "express": "^4.15.2",
    "firebase": "^8.0.0",
    "firebase-admin": "^9.3.0",
    "firebase-functions": "^3.13.0",
    "globalthis": "^1.0.1",
    "hammerjs": "^2.0.8",
    "memory-cache": "^0.2.0",
    "moment": "^2.29.1",
    "ngx-image-compress": "^11.0.3",
    "ngx-image-cropper": "^3.2.1",
    "ol": "^6.4.3",
    "rxjs": "~6.6.0",
    "ts-loader": "^8.0.4",
    "ts-md5": "^1.2.7",
    "tslib": "^2.0.0",
    "utf-8-validate": "^5.0.2",
    "ws": "^7.3.1",
    "xhr2": "^0.2.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1002.0",
    "@angular/cli": "~10.1.3",
    "@angular/compiler-cli": "~10.1.3",
    "@nguniversal/builders": "^10.1.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "blob-polyfill": "^5.0.20210201",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.0.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~3.0.2",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-loader": "^8.0.7",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2",
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12"
  }
}

I have tried the below according to https://github.com/angular/universal/issues/1209
npm install --save-dev blob-polyfill

in server.ts :

import { Blob } from "blob-polyfill";
....
global['Blob'] = Blob

but it doesn't work

Server.ts
(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xhr2');
import 'globalthis/auto';
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
import { Blob } from "blob-polyfill";
global['Blob'] = Blob;
// NgUniversalTools: Express Engine and moduleMap for lazy loading
// import { ngExpressEngine } from '@nguniversal/express-engine';
import { ngFlavrHubExpressEngine } from './express-engine';
// import { enableProdMode } from '@angular/core';

import express from 'express';
import { join } from 'path';
import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/app/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
  const routeCaches = [
    {path: '/home', ttl: 86400},
    {path: '/admin', ttl: 86400},
  ];

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngFlavrHubExpressEngine({
    bootstrap: AppServerModule,
    routeCaches
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 4000;
  // Start up the Node server
  const server = app();
  // If we're not in the Cloud Functions environment, spin up a Node server
  if (!process.env.FUNCTION_NAME) {
    // Start up the Node server
    server.listen(port, () => {
        console.log(`Node Express server listening on http://localhost:${port}`);
    });
  }
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';

Is there anything else we should know?

**Comment by temitopeog** [comment]
@vikerman do you have any idea on this, please?

**Comment by alan-agius4** [comment]
`Blob` is a browser specific API which is not available in Node.JS

We reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
