### ISSUE TITLE
Javascript out of memory exception - Azure CI/ CD pipeline

### ISSUE THREAD

**Issue by KumarKaruppaiah** [angular/universal#2046]
I have integrated the angular universal SSR with my current application. Please find the version details below.

Angular version : 9.0.5
Angular universal version: 9.0.2

It is working fine when I am building the application in my local machine. I didn't get any errors.  

But when  I am building the application in Azure CI / CD and getting the error "Javascript out of memory".

![SSR_Error_Azure](https://user-images.githubusercontent.com/42509994/114174792-c36efc80-9956-11eb-868a-653da91fc7b4.png)

I have increased the node memory size and  added the following scripts to my package.json file. But still it is not working.

 **"build:prod:ssr": "node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --configuration=production --base-href=/learning/ && ng run customerplatform-learning:server:production",**

Can someone help me on this issue ? Please let me know if you need any further information.

**Comment by alan-agius4** [comment]
It looks like you only increased the memory for the browser build

Kindly try
```
node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --configuration=production --base-href=/learning/ && node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng run customerplatform-learning:server:production
```

**Comment by KumarKaruppaiah** [comment]
> It looks like you only increased the memory for the browser build
> 
> Kindly try
> 
> ```
> node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng build --configuration=production --base-href=/learning/ && node --max_old_space_size=8192 ./node_modules/@angular/cli/bin/ng run customerplatform-learning:server:production
> ```

Thank you so much for quick reply. It is working fine now.
