### ISSUE TITLE
Manually delete Angular2 typings

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#205]
rather than dealing with the typings within Angular 2 I rather delete them and manage the types so we don't have to ignore all the duplication warnings

**Comment by NathanWalker** [comment]
Could help here if you don't get to it in next 2 days; are you thinking gulp task?

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/63761877be1dd479e64b772ff0e389b6df9a11f7
