### ISSUE TITLE
switch to `typings`. `tsd` is deprecated

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#206]
`tsd` is deprecated and we should switch to `typings`

**Comment by NathanWalker** [comment]
If this is still open by Sunday, I'll help get this out of the way using your guide...
https://github.com/angular/answers-app/pull/27/files
:)

**Comment by NathanWalker** [comment]
@gdi2290  Ok I got through the `typings` upgrade on the angular2-seed repo (thx for all your help) and if you haven't started on this yet, I can start into upgrading here?

**Comment by gdi2290** [comment]
this repo might be more advanced since we're dealing with many modules

**Comment by NathanWalker** [comment]
I was looking at that. Since you're more familiar, you will be better at this for sure. I'll look for other issues this week I can assist on.

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/2ebfa7f6c413e41385747092dc1b7a407fc80495
