### ISSUE TITLE
Angular Universal express engine - problem with ampersands in links in response from server

### ISSUE THREAD

**Issue by NormanLecter** [angular/universal#2061]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

hard to say - I didn't checked in others apps which I created

### Description

1. an object reference is set with `ViewChild('paginationControls') paginationControlsEl: ElementRef<HTMLElement>`
2. if we have an element, function `setAnchorsToPaginatorLinks()`  is called, which injecting links to next pages buttons (digits buttons) in `PaginatonControlsComponent` (outer library, which hasn't native service for that functionality, and such links are indicated among others for Google crawlers) 
3. Operation of assigning links looks like this ` element.children[0].href = '${urlWithoutOffset}offset=${offsetNumber}'`
4. If we use `View Source Code` for example in Google Chrome we will see good links (e.g. https://angular.io/blog&limit=24&offset=24), but in Postman or if we use `cURL` or `Invoke-RestMethod (Microsoft.PowerShell.Utility)` we will see `https://angular.io/blog&amp;limit=24&amp;offset=24` what is wrong and unused for Google crawler because links don't work at all
5.  for example `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons&display=block" />` that link added in `index.html`  in Postman looks like this `<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons&amp;display=block" />` (`&amp;` instead of `&`)
5. FOR NOW I resolved this using `res.send(html.replace(/&amp;/g, '&'))` instead of `res.send(html)` in `server.ts` file but maybe it is not good? Maybe is simple express configuration property and I am not found this? :( 

#### Motivation for or Use Case
add necessary links (with simply `&` not with HTML Entity `&amp;`) for next pages in pagination component for a.o. Google crawlers

#### Related Issues
 I don't see, only I found https://github.com/angular/universal/issues/304 but I don't think that can help me (or I don't know how)

#### Browsers and Operating System
all browsers, all systems

## 🔬 Minimal Reproduction

1. Angular SSR application
2. add `href` to `anchor` element using `ViewChild('customanchor') anchorElement:  ElementRef<HTMLElement>` and `anchorElement.href` property (link must have ampersand sign)
3. view the built link in `Postman` or using `cURL` / `Invoke-RestMethod (Microsoft.PowerShell.Utility)` 

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.1.12
Node: 12.16.1
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.12
@angular/cdk                       9.2.4
@angular/material                  9.2.4
@angular/material-moment-adapter   9.1.3
@ngtools/webpack                   9.1.12
@nguniversal/builders              9.1.1
@nguniversal/common                9.1.1
@nguniversal/express-engine        9.1.1
@schematics/angular                9.1.12
@schematics/update                 0.901.12
rxjs                               6.5.5
typescript                         3.7.5
webpack                            4.42.0

</code></pre>

**Comment by alan-agius4** [comment]
Hi @NormanLecter,

This is working as expected.

As when using the ampersand character `&` in HTML it should always be encoded, this is because ampersand is a special character that declares the beginning of an entity reference (a special character) and hence replacing `&amp;` with `&` might yield broken behaviour.

The browser is able to decode this, but if you copy the URI and use it outside of a browser without properly decoding it, this is expected to fail.
