### ISSUE TITLE
Prerenderer doesn't wait for HttpBackend

### ISSUE THREAD

**Issue by paulThorsen** [angular/universal#2070]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

No

### Description

When using HttpBackend for HttpClient to avoid interceptor chain, `yarn prerender` doesn't wait for http request to finish. 

## 🔬 Minimal Reproduction

- `ng new httpBackendTest`
- `ng add @nguniversal/express-engine`
- `ng g c test-comp --module app`
- `app.component.html`
```
<app-test-comp></app-test-comp>
```
- `test-comp.component.ts`
```
export class TestComponent implements OnInit {
  test = false;

  private http: HttpClient | null = null;
  constructor(private handler: HttpBackend) {
    this.http = new HttpClient(handler);
    this.http.get<any>('https://api.agify.io/?name=bella').subscribe((resp) => {
      this.test = true;
    });
  }

  ngOnInit(): void {}
}
```
- `test-comp.component.html`
```
content {{ test }}
```
- `yarn prerender`

You will notice that in `dist/httpBackendTest/browser/index.html` it will display "content false". If, instead, you inject `HttpClient` directly as opposed to using `HttpBackend` as the handler, the prerendered page will display "content true" and would be expected. 

## 🔥 Exception or Error

No error, the route is prerendered, but the data from the HTTP request is not applied to DOM, nor is the JSON from `TransferState` embedded in the prerendered HTML file. 

## 🌍 Your Environment
<pre><code>
Angular CLI: 11.1.4
Node: 15.5.1
OS: darwin x64

Angular: 11.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.4
@angular-devkit/build-angular   0.1101.4
@angular-devkit/core            11.1.4
@angular-devkit/schematics      11.1.4
@angular/cli                    11.1.4
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.1.2
@schematics/angular             11.1.4
@schematics/update              0.1101.4
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by petebacondarwin** [comment]
Is this not one of the known gotchas: https://github.com/angular/universal/blob/4bd5f8c7074d7df03f32063e2dc8239a5021ae7e/docs/gotchas.md#my-http-firebase-websocket-etc-wont-finish-before-render

> In Angular Universal, we have patched the Angular HTTP client to turn it into a macrotask, to ensure that any needed HTTP requests complete for a given render.

If you create your own `HttpClient` then it is probably not patched. That being said, I can't find any code that does this patching.

**Comment by intellix** [comment]
I'm having this problem with `AwsLambda from 'aws-sdk/clients/lambda'` and guessing it's already related to not being patched. Is there any info about patching it manually? Will report it back here if I find out how

**Comment by alan-agius4** [comment]
Here is an example of the patching https://github.com/angular/angular/blob/main/packages/platform-server/src/http.ts
