### ISSUE TITLE
Arbitrary code injection in dependency

### ISSUE THREAD

**Issue by ocket8888** [angular/universal#2091]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?
I believe so

### Description
`npm audit` output with `@nguniversal/express-engine@11.2.1` installed:
```
xmlhttprequest-ssl  <1.6.2
Severity: high
Arbitrary Code Injection - https://npmjs.com/advisories/1665
No fix available
node_modules/xmlhttprequest-ssl
  engine.io-client  1.6.0 - 4.1.3
  Depends on vulnerable versions of xmlhttprequest-ssl
  node_modules/engine.io-client
    socket.io-client  1.4.0 - 3.1.3
    Depends on vulnerable versions of engine.io-client
    node_modules/socket.io-client
      browser-sync-ui  >=1.0.1
      Depends on vulnerable versions of socket.io-client
      node_modules/browser-sync-ui
        browser-sync  >=2.11.2
        Depends on vulnerable versions of browser-sync-ui
        Depends on vulnerable versions of socket.io
        node_modules/browser-sync
          @nguniversal/builders  *
          Depends on vulnerable versions of browser-sync
          node_modules/@nguniversal/builders
      socket.io  1.0.0-pre - 1.0.0 || 1.4.0 - 3.0.0-rc4
      Depends on vulnerable versions of socket.io-client
      node_modules/browser-sync/node_modules/socket.io

7 high severity vulnerabilities
```

## 🔬 Minimal Reproduction
`npm audit`

## 🔥 Exception or Error

<pre><code>

xmlhttprequest-ssl  <1.6.2
Severity: high
Arbitrary Code Injection - https://npmjs.com/advisories/1665
No fix available
node_modules/xmlhttprequest-ssl
  engine.io-client  1.6.0 - 4.1.3
  Depends on vulnerable versions of xmlhttprequest-ssl
  node_modules/engine.io-client
    socket.io-client  1.4.0 - 3.1.3
    Depends on vulnerable versions of engine.io-client
    node_modules/socket.io-client
      browser-sync-ui  >=1.0.1
      Depends on vulnerable versions of socket.io-client
      node_modules/browser-sync-ui
        browser-sync  >=2.11.2
        Depends on vulnerable versions of browser-sync-ui
        Depends on vulnerable versions of socket.io
        node_modules/browser-sync
          @nguniversal/builders  *
          Depends on vulnerable versions of browser-sync
          node_modules/@nguniversal/builders
      socket.io  1.0.0-pre - 1.0.0 || 1.4.0 - 3.0.0-rc4
      Depends on vulnerable versions of socket.io-client
      node_modules/browser-sync/node_modules/socket.io

7 high severity vulnerabilities

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.11
Node: 16.0.0
OS: linux x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cdk                    11.2.11
@angular/cli                    11.2.11
@angular/material               11.2.11
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.3
typescript                      4.0.3

</code></pre>

**Comment by alan-agius4** [comment]
This is caused by a transitive dependency from BrowseSync which is used by our the dev-server.

We do not expect the dev-server as being used on production environments therefore this shouldn’t effect users.

Let’s continue tracking this https://github.com/BrowserSync/browser-sync/issues/1863 since there isn’t much we can do in this regards but wait for a fix upstream.

**Comment by ocket8888** [comment]
Good, that's what I was expecting to hear when I didn't find an issue for it already. Looks like I can proceed with my upgrade, thanks
