### ISSUE TITLE
Class constructor Critters cannot be invoked without 'new'

### ISSUE THREAD

**Issue by amakhrov** [angular/universal#2095]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

I don't know. I suspect it has always been like that.

### Description

We have a Universal project with express-engine. For various reasons it's built with `"bundleDependencies": false`. (I'm not 100% sure it's relevant - but might be).

Today I tried to enable `inlineCriticalCss: true` for the `ngExpressEngine` (accompanied by `"inlineCritical": true` setting in `angular.json`).

The app builds and starts without issues. However when I try to open it in a browser, the app crashes with the following error logged in the terminal:
```
TypeError: Class constructor Critters cannot be invoked without 'new'
    at new CrittersExtended (/crunchbase/client_app/node_modules/@nguniversal/common/bundles/common-engine.umd.js:355:32)
```

I believe it's because the default entry point in `@nguniversal/` packages, as configured in `package.json`, is a .js bundle compiled with `es5` target - so ES6 classes are downgraded to functions. However, the `critters` package is not downgraded - the actual .js bundle has real `class Critters {...}` inside.

## 🔥 Exception or Error

<pre><code>
TypeError: Class constructor Critters cannot be invoked without 'new'
    at new CrittersExtended (/crunchbase/client_app/node_modules/@nguniversal/common/bundles/common-engine.umd.js:355:32)
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.1.2
Node: 12.14.1
OS: darwin x64

Angular: 11.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.2
@angular-devkit/build-angular   0.1101.2
@angular-devkit/core            11.1.2
@angular-devkit/schematics      11.1.2
@angular/cli                    11.1.2
@nguniversal/builders           11.1.1
@nguniversal/express-engine     11.1.1
@schematics/angular             11.1.2
@schematics/update              0.1101.2
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Comment by alan-agius4** [comment]
@amakhrov, I believe this issue is fixed. Can you update to the latest universal packages (11.1.2)

**Comment by amakhrov** [comment]
Oh, I see a related commit! I'll give it a try tomorrow, but it definitely looks like it should fix it

**Comment by amakhrov** [comment]
Works good with 11.2.1 - thanks for the help!
