### ISSUE TITLE
deployed apps get few seconds 404 page when refresh/reload 

### ISSUE THREAD

**Issue by wilson-young** [angular/universal#2115]
Hi
I deployed my angular build with SSR to the server
Currently getting problem when I reload pages except for my homepage I am getting few seconds of 404 page while the page loading.

I understand if we deploy SPA we need to fallback to index.html
I am using Nginx which mean when I haven't use SSR 
we are doing 

`try_files $uri $uri/ /index.html;`

but currently, we deployed universal / SSR build we get this error and we don't know what to fix.
since we are proxy the Nginx to localhost:4000 for the server now
and we didn't want to use hash in route

so I wish to ask is there any way to solve or make the fallback to index,html?
adding Nginx configuration? or can it solve in server.ts / express?
any suggestions or solutions?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
