### ISSUE TITLE
prerender fails on new angular-cli 12 app

### ISSUE THREAD

**Issue by amitport** [angular/universal#2120]
using `@angular/cli@12.0.1`

`ng new app`
`ng add @nguniversal/express-engine`
`npm run build:ssr`
`npm run prerender`

gives the following error:
>>
```bash
Schema validation failed with the following errors:
  Data path "" must have required property 'serverTarget'
```
manually adding `"serverTarget": "appname:server:production"` to `angular.json` seems to work, but this  probably should be done by the `@nguniversal/express-engine` schematics

I get that there may be a configuration step I'm missing, but the documentation is very unclear about this, and I couldn't find additional info about the prerender npm task.

Thank you

**Comment by alan-agius4** [comment]
@amitport indeed this is bug
