### ISSUE TITLE
SSR working for all routes but not for "/" or "no path" one

### ISSUE THREAD

**Issue by ilprima** [angular/universal#2140]
# 🐞 Bug report

#### What modules are related to this issue?

My SSR server, served with firebase, is working for all the routes but but for none routes, I mean, It works for eg mydomain.com/home or mydomain.com/aboutus but not for mydomain.com or mydomain.com/

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ X] express-engine
- [ ] hapi-engine

### Description

 A clear and concise description of the problem...

Take a look to my website source [www.roomlessrent.com](www.roomlessrent.com) and to one of my website pages [www.roomlessrent.com/en/home](www.roomlessrent.com/en/home), you can see that our the first url (just the domain) the SSR is not working but I don't know why.

## 🔬 Minimal Reproduction

server.ts file:
<pre><code>
import 'zone.js/dist/zone-node';

(global as any).WebSocket = require('ws');
(global as any).XMLHttpRequest = require('xhr2');

import { ngExpressEngine } from '@nguniversal/express-engine';
// import * as express from 'express';
import express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync, readFileSync } from 'fs';

const cache = require('memory-cache');

const distFolder = join(process.cwd(), 'dist/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html'))
  ? 'index.original.html'
  : 'index.html';

// The Express app is exported so that it can be used by serverless Functions.
  export function app() {
    try {

    const server = express();

    // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
    server.engine(
      'html',
      ngExpressEngine({
        bootstrap: AppServerModule,
      })
    );

    server.set('view engine', 'html');
    server.set('views', distFolder);

    // Example Express Rest API endpoints
    // server.get('/api/**', (req, res) => { });
    // Serve static files from /browser
    /* server.get('*.*', express.static(distFolder, {
       maxAge: '1y'
     }));
   */

    // Serve static files from /dist/browser folder with a cache policy
    server.get('*.*', express.static(distFolder, {
       maxAge: '1y',
      setHeaders: (res, path) => {
        res.setHeader('Cache-Control', 'public, max-age=2592000');
        res.setHeader("Expires", new Date(Date.now() + 2592000000*30).toUTCString());
      }
     }));

    // All regular routes use the Universal engine
    // Serve routes with a cache policy + caching rendering
    server.get('*', (req, res) => {
      res.setHeader('Cache-Control', 'public, max-age=2592000');
      res.setHeader('Expires', new Date(Date.now() + 2592000000).toUTCString());

      // *** CACHE ***
      // https://samvloeberghs.be/posts/creating-a-simple-memory-cache-for-your-angular-universal-website-or-application
      const config = {
        req,
        providers: [{provide: APP_BASE_HREF, useValue: req.baseUrl}],
      };

      const paths = req.originalUrl.split('?');
      if (paths && paths.length > 0 && !(paths.includes('.js') || paths.includes('.css'))) {
        // delete query params from caching to avoid aving too much pages
        const entry = cache.get(paths[0]); // check if we have a cache entry
        if (entry) {
          res.send(entry); // send the cache entry
        } else {
          res.render(indexHtml, config, (err, html) => {
            cache.put(paths[0], html); // save the HTML in the cache
            res.send(html);
          });
        }
      } else {
        res.render(indexHtml, config);
      }
      // *** END CACHE ***

      // Old
      // res.render(indexHtml, config);
    });

    return server;

    }catch (e) {
      console.log(e)
    }

  }

  function run() {
    const port = process.env.PORT || 4000;

    // Start up the Node server
    // Avoid to start the server to allow Cloud Fuctions do it for me
    /*
      const server = app();
      server.listen(port, () => {
        console.log(`Node Express server listening on http://localhost:${port}`);
      });
    */
  }

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
  declare const __non_webpack_require__: NodeRequire;
  const mainModule = __non_webpack_require__.main;
  const moduleFilename = (mainModule && mainModule.filename) || '';
  if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
    run();
  }

export * from './src/main.server';
</code></pre>

app.server.ts file

<pre><code>
import { NgModule } from '@angular/core';
import {ServerModule, ServerTransferStateModule} from '@angular/platform-server';

import { AppModule } from './app.module';
import { AppComponent } from './app.component';
import { IonicServerModule } from '@ionic/angular-server';

import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { Observable, Observer } from 'rxjs';
import { readFileSync } from 'fs';

export function universalLoader(): TranslateLoader {
  return {
    getTranslation: (lang: string) => {
      return new Observable((observer: Observer<any>) => {
        observer.next(JSON.parse(readFileSync(`./dist/browser/assets/i18n/${lang}.json`, 'utf8')));
        observer.complete();
      });
    },
  } as TranslateLoader;
}

@NgModule({
  imports: [
    AppModule,
    ServerModule,
    IonicServerModule,
    TranslateModule.forRoot({
      loader: { provide: TranslateLoader, useFactory: universalLoader },
    }),
    //ServerTransferStateModule //TODO: togliere se non serve, vedere in fondo a https://github.com/angular/universal/blob/master/docs/transfer-http.md
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule {}

</code></pre>

And app-routing.module.ts

<pre><code>

import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AuthGuard } from './auth.guard';
import { AuthGuardAdmin } from './authGuardAdmin';
import { QuicklinkModule, QuicklinkStrategy } from 'ngx-quicklink';

const routes: Routes = [
  {
    path: '',
    children: [
      {
        path: 'home',
        loadChildren: () => import('./home/home.module').then((m) => m.HomePageModule),
      },
      {
        path: ':lang/home',
        loadChildren: () => import('./home/home.module').then((m) => m.HomePageModule),
      },
...
      {
        path: '',
        redirectTo: 'home',
        pathMatch: 'full',
      },

      { path: '**', redirectTo: 'home', pathMatch: 'full' },
    ],
  },
  { path: '**', redirectTo: '', pathMatch: 'full' },
];

@NgModule({
  imports: [
    QuicklinkModule,
    RouterModule.forRoot(routes, { preloadingStrategy: QuicklinkStrategy }),
  ],
  exports: [RouterModule],
  providers: [AuthGuard, AuthGuardAdmin],
})
export class AppRoutingModule {}

</code></pre>

## 🌍 Your Environment
ng version:
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.0
Node: 12.18.3
OS: darwin x64

Angular: 10.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.1001.0
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.1001.0
@angular-devkit/core              10.1.0
@angular-devkit/schematics        10.1.0
@angular/cdk                      10.2.0
@ngtools/webpack                  9.1.12
@nguniversal/builders             10.1.0
@nguniversal/common               10.1.0
@nguniversal/express-engine       10.1.0
@schematics/angular               8.3.29
@schematics/update                0.1001.0
rxjs                              6.6.3
typescript                        4.0.2
webpack                           4.42.0

</code></pre>

**Comment by vaikunthan93** [comment]
Can you share your error log?

**Comment by pmathulan** [comment]
Can you share the error log?

**Comment by ilprima** [comment]
> Can you share the error log?

No error at all 😢

**Comment by ilprima** [comment]
> Can you share the error log?

I checked better, seems like for that url (as I said url with no sub path) the cloud function doesn't load at all, therefore there is no log in the Google Cloud console

**Comment by ilprima** [comment]
> This is not an issue with express-engine but with firebase functions. All you have to do is change the name of index.html to something else e.g index-1.html

Thank you for your reply. Can you explain why this should work? II just would like to understand

**Comment by vmasek** [comment]
A short explanation would be: the `index.html` is returned when empty `/` route is visited as it is found by the static hosting and rendering cloud function is never even called. This is due to firebase hosting behaviour, not Universal nor Express engine.

A simple renaming of the `index.html` to something like `index-original.html` will solve this problem.

**Comment by maranmaran** [comment]
> A short explanation would be: the `index.html` is returned when empty `/` route is visited as it is found by the static hosting and rendering cloud function is never even called. This is due to firebase hosting behaviour, not Universal nor Express engine.
> 
> A simple renaming of the `index.html` to something like `index-original.html` will solve this problem.

How do you mean? If i change the index.html name I can't build (build:ssr) I'd have to change my angular.json file too and I'm back where I started.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
