### ISSUE TITLE
Support for Client Hints

### ISSUE THREAD

**Issue by alfaproject** [angular/universal#2151]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [x] common
- [ ] express-engine
- [ ] hapi-engine

### Description

It's been challenging to remove content flashing from server to browser due to the server not knowing what the client viewport size is or whether it has a preference for dark mode or not, etc

### Describe the solution you'd like

I'm wondering if adding native support for HTTP Client Hints and mock things like document viewport and whatnot in a more accurate way with what will ultimately be re-rendered in the client would help that

Reference:
* https://developer.mozilla.org/en-US/docs/Glossary/Client_hints
* https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/client-hints

### Describe alternatives you've considered

We have our own support for some of this but it's always better when it comes natively in the frameworks we use that deal with the web better than we could ever do, especially coming from Google where it penalises this sort of thing.

**Comment by alan-agius4** [comment]
Hi @alfaproject,

Thanks for this feature request.

Can you elaborate a bit more about the use-case of using client hints with universal? Do you have viewport calculations inside your JavaScript? 

HTTP client hints are still in experimental phase https://datatracker.ietf.org/doc/rfc8942/ and are not supported by FireFox and Safari.

**Comment by alfaproject** [comment]
Yes, we do have viewport calculations being done and load certain resources from a headless CMS depending on viewport size.

Our websites are data driven and load specific data for different view ports, like on narrow view port we would load from the CMS a certain type of menu resource but on bigger view port we would load another type of resource, etc

That's just an example, but there's also theming as another example. We load some CSS from the CMS as well and if the user prefers dark mode then we would load dark mode resources, etc

We can of course over fetch and we do a bit of that but depending on how much user agent context we have we can fetch things smarter. That's basically what led to this request

**Comment by alan-agius4** [comment]
I think this is quite user-specific
, 

In general for CSS resources I'd expect that most of the logic is offloaded to the handled by the browser directly.

Example
```
<link rel="stylesheet" media="screen and (min-width: 900px)" href="widescreen.css">
<link rel="stylesheet" media="screen and (max-width: 600px)" href="smallscreen.css">
<link rel="stylesheet" media="(prefers-color-scheme: dark)" href="dark.css">
<link rel="stylesheet" media="(prefers-color-scheme: light)" href="light.css">
```

**Comment by alfaproject** [comment]
I mean, I would just expected the mocked window/document globals to have whatever can be inferred from the agent to be set, so that the logic that eventually runs in the browser is as close as possible as the server. I think we all strive for that for any SSR page.

You know, like `window.innerWidth` would have the same value that ultimately the browser will return to the user, etc.

As for the CSS, we don't know which CSS to load until we know who the agent/domain is. That was just another example in any case.

As for our use case specifically I was trying to not mention too much as to not sound biased to what we have but for the sake of perspective: basically, if the user hits `wwww.brand1.com/en/whatever`, then w load configuration for www.brand1.com, fetch the routes, app settings, layout configuration, components, whatever custom CSS, and all other resources needed to be able that particular route in that particular domain from the CMS and then build the page dynamically based on all that. These API calls are then transferred to the client via TransferState so that the client doesn't fetch this again, BUT if the client has a different view port size (as an example), then it needs to refetch all the layout configuration again, all the components for said layout, etc. We obviously have some hacks to try to minimise this so as to prevent flashing of content as much as possible. I was just trying to suggest an improvement from the framework level if possible, ofc

**Comment by alan-agius4** [comment]
At this point this is currently not in the roadmap of the Universal project to provide helper API for client hints. If you need to interact with these, you should use a 3rd party library or use a custom helper.
