### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by PRR24** [angular/universal#2167]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] express-engine

### Description

ngExpressEngine successfully renders requests if route is followed by index.html

## 🔬 Minimal Reproduction

- Create new Angular cli project with routing.
- Add SSR as documented
- Have a route "/page" with basic implementation
- Have a route "**" for Page not found.
- Run the server and make a request to http://localhost:4200/page/index.html

Expected result: rendering should return Page not found.
Actual result: rendering is the same as for http://localhost:4200/page

## 🌍 Your Environment

Angular 12.0.1,
Express-engine 12.0.0

**Comment by alan-agius4** [comment]
This is working as expected.
