### ISSUE TITLE
Error in Service Worker when using Angular Universal

### ISSUE THREAD

**Issue by GlauberF** [angular/universal#2175]
# 🐞 Bug report

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Description
I use it in my system made in Angular, Angular Universal together with Service Worker.
However after doing build(npm run build:ssr) running without SSR the Service Worker Works(NORMAL ((nominal))) and running with the SSR command(node dist/server/main.js) does not work(EXISTING_CLIENTS_ONLY).

Below I explain better, bugs and tests done, as well as a test repository.

## Exception or Error
NGSW Debug Info:

Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://app-homologacao.vimbo.com.br/ngsw-worker.js:763:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://app-homologacao.vimbo.com.br/ngsw-worker.js:196:32))
Latest manifest hash: 2fce0503941ec162304bac74567f750c37aef515
Last update check: 8m58s281u

=== Version 2fce0503941ec162304bac74567f750c37aef515 ===

Clients: 

=== Idle Task Queue ===
Last update tick: 1s541u
Last update run: 8m51s677u
Task queue:
 * check-updates-on-navigation

Debug log:

[8m51s565u] Error(Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting), Error: Hash mismatch (cacheBustedFetchFromNetwork): https://app-homologacao.vimbo.com.br/index.html: expected 5de6c86e05d6b19ff5af1ddc70b13ddf5a9c5b1d, got 2ae958e133c27c01180cf89450c7eaaa06e04758 (after cache busting)
    at PrefetchAssetGroup.<anonymous> (https://app-homologacao.vimbo.com.br/ngsw-worker.js:763:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://app-homologacao.vimbo.com.br/ngsw-worker.js:196:32)) initializeFully for 2fce0503941ec162304bac74567f750c37aef515
[7s914u] TypeError(Failed to fetch, TypeError: Failed to fetch) Driver.fetch(https://www.google.com.br/ads/ga-audiences?t=sr&aip=1&_r=4&slf_rd=1&v=1&_v=j90&tid=UA-80436761-1&cid=825317964.1623532590&jid=112875176&_u=QACAAEAAAAAAAC~&z=1381826650)
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.12
Node: 14.16.1
OS: linux x64

Angular: 11.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1102.11
@angular-devkit/build-angular      0.1102.12
@angular-devkit/build-optimizer    0.1101.4
@angular-devkit/core               11.2.11
@angular-devkit/schematics         11.2.12
@angular/cdk                       11.2.12
@angular/cli                       11.2.12
@angular/flex-layout               11.0.0-beta.33
@angular/material                  11.2.12
@angular/material-moment-adapter   11.2.12
@nguniversal/builders              11.2.1
@nguniversal/express-engine        11.2.1
@schematics/angular                11.2.12
@schematics/update                 0.1102.12
rxjs                               6.6.7
typescript                         4.1.5
</code></pre>

## Tests done
After more than a day of testing, I discovered the problem, but it is something related to Angular.

When I generate the build(npm run build:ssr) the `dist` folder is created containing the `browser` and `server` folder.
Having these files, I performed some analysis before getting to the problem.

1 - Looking at the files and the hash, they are identical, so it's not a build problem.
2 - Going into the `dist/browser` folder and running the command `http-server -c-1 --proxy http://localhost:9000 .` the service worker registers and works perfectly `NORMAL ((nominal))` .
3 - Now uploading the server with SSR `node dist/server/main.js` the service worker does not work, it is in the EXISTING_CLIENTS_ONLY state

All tests were done locally, without interference from another service.

The way I register the `ngsw-worker.js`.
```typescript
ServiceWorkerModule.register('ngsw-worker.js', {
    enabled: environment.production,
    registrationStrategy: 'registerWhenStable:30000'
})
```

My server.ts file for SSR is the default, generated by the CLI itself.

**Note**, if you generate a new application via CLI and include Servie Worker and Angular Universal, you can reproduce exactly what I mentioned above.

If you prefer, there is a repository here for testing https://github.com/GlauberF/ssr-and-service-worker-error

**temporarily**, what might work is comment out `ServiceWorkerModule.register` in `app.module.ts` and register differently in `main.ts`, but that doesn't work for min, because I need to use `Push(SwPush), SWUpdate`

```typescript
ServiceWorkerModule.register('ngsw-worker.js', {
      enabled: environment.production,
      registrationStrategy: 'registerWhenStable:30000'
    })
```

And register within main.ts
```typescript
document.addEventListener('DOMContentLoaded', () => {
  platformBrowserDynamic().bootstrapModule(AppModule)
  .then(() => {
		if ('serviceWorker' in navigator && environment.production) {
			navigator.serviceWorker.register('./ngsw-worker.js');
		}
	})
  .catch(err => console.error(err));
});
```

And registering without using `ServiceWorkerModule.register` ends up resulting in errors
<pre><code>
NullInjectorError: R3InjectorError(AppServerModule)[ApplicationModule -> ApplicationRef -> ErrorHandler -> SystemUpdateService -> SwUpdate -> SwUpdate -> SwUpdate]: 
  NullInjectorError: No provider for SwUpdate!
    at NullInjector.get (/var/www/html/pwa_vimbo/dist/server/main.js:2229:278435)
    at R3Injector.get (/var/www/html/pwa_vimbo/dist/server/main.js:2229:280830)
    at R3Injector.get (/var/www/html/pwa_vimbo/dist/server/main.js:2229:280830)
    at R3Injector.get (/var/www/html/pwa_vimbo/dist/server/main.js:2229:280830)
    at injectInjectorOnly (/var/www/html/pwa_vimbo/dist/server/main.js:2229:209181)
    at Module.ɵɵinject (/var/www/html/pwa_vimbo/dist/server/main.js:2229:209351)
    at Object.SystemUpdateService_Factory [as factory] (/var/www/html/pwa_vimbo/dist/server/main.js:1037:46010)
    at R3Injector.hydrate (/var/www/html/pwa_vimbo/dist/server/main.js:2229:283653)
    at R3Injector.get (/var/www/html/pwa_vimbo/dist/server/main.js:2229:280620)
    at injectInjectorOnly (/var/www/html/pwa_vimbo/dist/server/main.js:2229:209181)
</code></pre>

**Comment by alan-agius4** [comment]
Hi @GlauberF, 

What are the steps to replicate the issue using the reproduction https://github.com/GlauberF/ssr-and-service-worker-error? I am having some trouble to reproduce this with the reproduction provided.

**Comment by GlauberF** [comment]
After cloning, Install the packages and generate the build using the command `npm run build:ssr`

The steps would be these:

1 - Looking at the files and the hash, they are identical, so it's not a build problem.
2 - Going into the dist/browser folder and running the command http-server -c-1 --proxy http://localhost:9000 . the service worker registers and works perfectly NORMAL ((nominal)) .
3 - Now uploading the server with SSR node dist/server/main.js the service worker does not work, it is in the EXISTING_CLIENTS_ONLY state

In 3 it would fail(EXISTING_CLIENTS_ONLY).

**Comment by alan-agius4** [comment]
I am still not able to reproduce.

I also don't follow how running the client application with `http-server` effects the service worker when using SSR. From a browser point of view these are different application since they use different ports.

http://127.0.0.1:8080/ngsw/state
```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: d63a4ddc3de870ac4a01702846944a4eca166b3e
Last update check: 10s425u

=== Version d63a4ddc3de870ac4a01702846944a4eca166b3e ===

Clients: 

=== Idle Task Queue ===
Last update tick: 15s450u
Last update run: 10s450u
Task queue:


Debug log:
```

http://127.0.0.1:4000/ngsw/state
```
NGSW Debug Info:

Driver state: NORMAL ((nominal))
Latest manifest hash: d63a4ddc3de870ac4a01702846944a4eca166b3e
Last update check: 12s284u

=== Version d63a4ddc3de870ac4a01702846944a4eca166b3e ===

Clients: fddfb4a8-be73-44f0-8b5e-cee98dfc4e7a, fb915ae3-ac57-4833-8067-2cfd854ca42c, bc7a75cf-680e-44ae-a71f-924b5c1c483a, b22d26ae-6df1-4792-b0cf-3c0540d1cd61, 8aa994c7-4f14-4d8e-8bd7-ccb0f9a6d426, 6a109d15-0df4-4d41-8863-dcf1d5ca4137, 617d07c4-6612-49a2-beda-bf6eec5825d2, ffd448e6-4426-4608-85e8-80d1b5d7e854

=== Idle Task Queue ===
Last update tick: 1s919u
Last update run: 2s514u
Task queue:
 * check-updates-on-navigation

Debug log:
```

**Comment by GlauberF** [comment]
So the http-server the only reason I mentioned it is that when I used it locally the Service Worker worked.
And the service worker just didn't work if started as SSR.

I will close the issue, try to clear everything and whatever cache I have, delete node_modules and redo the tests, if the error persists I open an issue again.
Thanks @alan-agius4
