### ISSUE TITLE
Angular 12 Universal npm run prerender make an error (ng add @nguniversal/common)

### ISSUE THREAD

**Issue by TatyanaMolchanova** [angular/universal#2179]
I created Angular 12 app.
Then I add Universal with this command: 
ng add @nguniversal/common

I choosed such options in installing process:

i Using package manager: npm
√ Found compatible package version: @nguniversal/common@12.0.2.
√ Package information loaded.

The package @nguniversal/common@12.0.2 will be installed and executed.
Would you like to proceed? Yes
√ Package successfully installed.
? Do you want to add built time rendering (pre-rendering)? Yes
? Do you want to add server-side rendering (SSR)? Yes
CREATE src/server.ts (1024 bytes)
CREATE tsconfig.server.json (274 bytes)
UPDATE src/app/app.module.ts (579 bytes)
UPDATE package.json (1568 bytes)
UPDATE angular.json (4163 bytes)
√ Packages installed successfully.

Then I try to run app with 

npm run prerender

and got this error:

> angular12-at-first-installation@0.0.0 prerender D:\PRACTICE\angular12-at-first-installation
> ng run angular12-at-first-installation:prerender

An unhandled exception occurred: Could not find any routes to generate.
See "C:\Users\tanyamt\AppData\Local\Temp\ng-jM4TpB\angular-errors.log" for further details.
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file C:\WINDOWS\system32\cmd.exe
npm ERR! errno ENOENT
npm ERR! angular12-at-first-installation@0.0.0 prerender: `ng run angular12-at-first-installation:prerender`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the angular12-at-first-installation@0.0.0 prerender script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tanyamt\AppData\Roaming\npm-cache\_logs\2021-06-19T16_35_29_195Z-debug.log

C:\Users\tanyamt\AppData\Local\Temp\ng-jM4TpB\angular-errors.log contains:

[error] Error: Could not find any routes to generate.
    at D:\PRACTICE\angular12-at-first-installation\node_modules\@nguniversal\builders\src\static-generator\index.js:49:23
    at Generator.next (<anonymous>)
    at fulfilled (D:\PRACTICE\angular12-at-first-installation\node_modules\@nguniversal\builders\src\static-generator\index.js:11:58)

On request I created repository with this app:
https://github.com/TatyanaMolchanova/angular12-universal-prerender-error

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] express-engine

### Is this a regression?

 I don't know

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.0.5
Node: 14.17.1
Package Manager: npm 6.14.2
OS: win32 x64

Angular: 12.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.5
@angular-devkit/build-angular   12.0.5
@angular-devkit/core            12.0.5
@angular-devkit/schematics      12.0.5
@schematics/angular             12.0.5
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by alan-agius4** [comment]
Based on the routing configuration there are indeed no routes to render.

https://github.com/TatyanaMolchanova/angular12-universal-prerender-error/blob/52b6435e36bf911842ae0cca74c300f31f41ef1e/src/app/app-routing.module.ts#L4
