### ISSUE TITLE
Cannot inspect server.js: Starting inspector on 127.0.0.1:9229 failed: address already in use

### ISSUE THREAD

**Issue by hjJunior** [angular/universal#2198]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

I cannot confirm, but it helps, this feature was added on this PR: https://github.com/angular/universal/pull/1673/files

### Description

I expect given the --inspect attributes to `dev:ssr` command would make it possible to debug the app in chrome (chrome://inspect)
When I added it, I see an error saying that the address is already in use

```
Starting inspector on 127.0.0.1:9229 failed: address already in use
``` 

I can confirm that there is no process running into this port when I got this error message

## 🔬 Minimal Reproduction

1. Clone the example project from [Angular Universal docs](https://angular.io/guide/universal)
2. install depencies
3. Add any block of code to be inspected on the server side, eg:

```
# server.ts
...
  server.get("/debugger", (req, res) => {
    debugger;
    res.send("testing debugger");
  })
...
```
4. run the `dev:ssr` command passing the inspect arg (`yarn dev:ssr --inspect`)
5. You might see the error `Starting inspector on 127.0.0.1:9229 failed: address already in use`

## 🔥 Exception or Error

<pre><code>
** Angular Universal Live Development Server is listening on http://localhost:4200, open your browser on http://localhost:4200 **
⠸ Generating localized bundles...Debugger listening on ws://127.0.0.1:9229/72393715-4212-44c7-bcd0-b64b935e6211
For help, see: https://nodejs.org/en/docs/inspector

✔ Localized bundle generation complete.
✔ Index html generation complete.

5 unchanged chunks

Build at: 2021-07-07T21:22:46.156Z - Hash: a0582ba15edba5fbc363 - Time: 5207ms

Compiled successfully.
Starting inspector on 127.0.0.1:9229 failed: address already in use

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.0.2
Node: 14.15.4
Package Manager: npm 6.14.11
OS: linux x64

Angular: 12.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@nguniversal/builders           12.0.1
@nguniversal/express-engine     12.0.1
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.2.4
</code></pre>

**Comment by Allcharles** [comment]
Any update on this? The lack of debugging tools makes SSR debugging fairly difficult. Or is there another method available for getting around this issue?

**Comment by alan-agius4** [comment]
Thanks for opening this issue. This has been addressed in the new application builder `@angular-devkit/build-angular:application` which was introduced in Angular CLI 16.2.0
