### ISSUE TITLE
decouple ng2Engine/render into 3 stages

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#22]
decouple the current `toString` rendering process

prior art:
[yahoo/fluxible](https://github.com/yahoo/fluxible)

### Server Life Cycle
init:
 * stateless app (create injector)

request:
 * create stateful app (create RootElement)
 * inject cache data
 * detect changes
 * serialize (toString)
 * dispose stateful app
 * inject serialized app into html 
 * send html app to client

### 3 Stages
 - [ ] Explicit: dev is able to have full control over the life cycle
  * init:
    * stateless app
    * server bindings
  * request:
    * create stateful app
    * inject cache data
    * detect changes
    * serialize
    * dispose stateful app
    * inject serialized app into html 
    * send html app to client
 - [ ] Render: A small abstraction that would expose injecting cache/bindings 
  * init:
    * stateless app
    * server bindings
  * request:
    * inject cache data
    * inject serialized app into html 
    * send html app to client
 - [ ] Fullstack: use angular server app to build precompiled angular client app
  * init:
    * server bindings
  * request:
    * optionally inject preload cache

**Comment by gdi2290** [comment]
there needs to be a way to package angular2/zones.js/reflect (with commonjs) and universal for other backends. see https://github.com/angular/universal/issues/40

current strategy and lifecycle of a NodeEnvironment in another language:

require angular2/universal

require universal app

get data/state from process args

render to string data/state, universal app

log the string that will then be sent to the client


```es6
var angular    = require('universal/angular2'); // pending universal module distribution discussion  
var App        = require('app/App'); // our universal code that also runs in the client
var state      = JSON.parse(process.argv[2]); // process serialized App/Model state
var serialized = angular.renderToString(App, state); // serialized
console.log(serialized); // stream back to original env
```

**Comment by gdi2290** [comment]
also related https://github.com/angular/universal/issues/22
There needs to be a stage that's available for fullstack angular which is Angular as a server framework

**Comment by gdi2290** [comment]
We need to update the ApplicationRef to manage the lifecycle of the application or split up application from rendering. For example, replace/update injector, recompile, defer compile (after splitting up renderer)

**Comment by jeffbcross** [comment]
Opened new issues #131 and #130 to capture some of the remaining enhancements.
