### ISSUE TITLE
Development compiler stops on error ng run serve-ssr

### ISSUE THREAD

**Issue by SDAdham** [angular/universal#2200]
Hello team,

When I run `ng run serve-ssr`, I expect the angular server will run and watch for changes, and per my changes, it would rebuild (which it does pretty great) but all that continues just till an error happens or a mistake in the code. In that sense, it would stop and exit.

I don't know if this is a bug or not, I just upgraded my angular to `12` and nguniversal to `v12` hoping that this issue would go away but it didn't and I don't know where to go.

I am working on a complicated project that takes some good time to compile from scratch. When running in dev environment and I make a accident and write something wrong, I'd get the error of that wrong and then the `this.debug is not a function` message will come up then the watch/compiler will stop.

Please help.... I also created a stackoverflow question here https://stackoverflow.com/questions/68151309/how-can-we-prevent-this-debug-is-not-a-function-from-causing-the-compiler-to-exi , i don't know how to avoid such exits...

`angular.json`:
```
"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "server.ts",
            "tsConfig": "tsconfig.server.json",
            "sourceMap": true,
            "optimization": false
          },
          "defaultConfiguration": ""
        },
"build-for-ssr": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/browser",
            "index": "src/index.template.html",
            "main": "src/main.browser.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/manifest.json",
              "src/assets",
              {
                "glob": "**/*",
                "input": "node_modules/intro.js",
                "output": "./assets/intro.js/"
              },
              { "glob": "**/*", "input": "node_modules/monaco-editor", "output": "assets/monaco-editor" }
            ],
            "styles": [
              "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
              "src/styles.scss",
              "node_modules/intro.js/introjs.css"
            ],
            "scripts": ["node_modules/intro.js/intro.js"],
            "vendorChunk": true,
            "extractLicenses": false,
            "buildOptimizer": false,
            "sourceMap": true,
            "optimization": false,
            "namedChunks": true
          },
          "defaultConfiguration": ""
        },
"serve-ssr": {
          "builder": "@nguniversal/builders:ssr-dev-server",
          "options": {
            "browserTarget": "build-for-ssr",
            "serverTarget": "server"
          },
        },
```

`ng version`
```
Angular CLI: 12.1.1
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            10.1.7
@angular-devkit/schematics      10.1.7
@nguniversal/builders           11.2.1
@nguniversal/express-engine     12.1.0
@schematics/angular             10.1.7
rxjs                            6.6.7
typescript                      4.3.5
webpack                         5.44.0
```

**Comment by alan-agius4** [comment]
Looks like the builders package is outdated, Can you please try to update and see if the issue persists?

```
@nguniversal/builders           11.2.1
```

If the problem persists, please provide a minimal reproduction that demonstrates the issue, as we are unable to replicate the mentioned issue from our end.

**Comment by SDAdham** [comment]
Upgrading the `@nguniversal/builders` didn't help, but it seems that this answer solved my issue https://github.com/angular/universal/issues/1848#issuecomment-867212235

I'll keep monitoring for a while.

**Comment by SDAdham** [comment]
It's been very stable since the change I made. Closing this issue, thanks @alan-agius4 for trying to help. Appreciated.
