### ISSUE TITLE
Bad Performance when update @nguniversal/express-engine from 11.1 to 12.1

### ISSUE THREAD

**Issue by Aventrue** [angular/universal#2230]
After we updated the @nguniversal/express-engine from 11.1 to 12.1 we have much slower performance.
With 11.1 we have a average response time from 750ms and with the new version it is about 1600ms.
What can cause this problem and how can we solve it?

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/universal/issues/2106
