### ISSUE TITLE
Angular 12 Update – CSS loading delay on angular SSR

### ISSUE THREAD

**Issue by valeri879** [angular/universal#2244]
I have recently updated my angular app version 11 to 12. also using SSR. previously it was working perfectly. now on SSR build it's loading CSS a bit late & display raw HTML first & after some time loads the CSS. I tried changing the sequence of the CSS file from angular.json but nothing worked.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by valeri879** [comment]
I have recently updated my angular app version 11 to 12. also using SSR. previously it was working perfectly. now on SSR build it's loading CSS a bit late & display raw HTML first & after some time loads the CSS. I tried changing the sequence of the CSS file from angular.json but nothing worked.


# 🐞 Bug report

#### What modules are related to this issue?



- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [X] express-engine
- [ ] hapi-engine

### Is this a regression?


 Yes, the previous version in which this bug was not present was: Before updating it worked perfectly

### Description

 
this is angular 12 on production [servisebi.ge](https://servisebi.ge/ka)
this is angular 11 on production [servisebi.kz](https://servisebi.kz/ru)

if you hard refresh both application you can see difference between those two project

## 🔬 Minimal Reproduction



## 🔥 Exception or Error

<pre>
There is no compilation error
<code>



</code></pre>

## 🌍 Your Environment

<pre>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.1.4
Node: 16.4.0 (Unsupported)
Package Manager: npm 7.19.1
OS: linux x64

Angular: 12.1.4
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.901.15
@angular-devkit/build-angular              12.1.4
@angular-devkit/core                       9.1.15
@angular-devkit/schematics                 11.2.12
@nguniversal/builders                      9.1.1
@nguniversal/express-engine                11.0.1
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        11.2.12
rxjs                                       6.6.3
typescript                                 4.3.5
<code>



</code></pre>

**Comment by alan-agius4** [comment]
Looks like your `@nguniversal` are outdated, please update to the version 12.
