### ISSUE TITLE
Angular universal overwrites process.env.NODE_ENV

### ISSUE THREAD

**Issue by Avcajaraville** [angular/universal#2245]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description

When running the builder `@nguniversal/builders:ssr-dev-server` via `serve-ssr` command to locally serve my angular-universal express server, it overwrites my `process.env.NODE_ENV` and sets it to production, no matter how I set `NODE_ENV`.

I usually set this flag via `dotenv`.

I know we should be using `enviroment.ts` for setting `production` or `development` mode, but due to some external dependencies, I need to have this process variable set to `development` when working on local development.

## 🔬 Minimal Reproduction

You can just add a `console.log(process.env.NODE_ENV)` on the server file, without any dependency or extra code, just as it comes, and the logged string would be `production` no matter how you set this environment variable.

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
