### ISSUE TITLE
Release for Angular 12.2?

### ISSUE THREAD

**Issue by restfulhead** [angular/universal#2298]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [?] aspnetcore-engine
- [x] builders
- [x] common
- [x] express-engine
- [?] hapi-engine

### Description

Would it be possible to release a version of Angular Universal compatible with Angular 12.2.x? I noticed the following merged pull request https://github.com/angular/universal/pull/2248 which seems to address this?

### Describe the solution you'd like

Release a new version of Angular Universal to NPM.

**Comment by alan-agius4** [comment]
Universal 12.1 is compatible with Angular 12.2
