### ISSUE TITLE
schema is using the keyword id

### ISSUE THREAD

**Issue by its-dibo** [angular/universal#2310]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

Yes, v11.x

### Description

trying to add the universal express-engine via `ng add @nguniversal/express-engine`  to a freshly created Angular v12 project.
but got an error `Could not find version.` without any details

**trace**
```
> ng "add" "@nguniversal/express-engine"

Skipping installation: Package already installed
Could not find version.
```

it seems that it searches for `@angular/core`, but it is already installed in the above directory
![image](https://user-images.githubusercontent.com/57308531/134035854-3325b587-b45a-44c9-bed7-695926897120.png)

as a temporary workaround, I added `@angular/core` to packag.json where `angular.json` lives without installing it.

**Comment by alan-agius4** [comment]
`@angular/core` is expected to be in the root  `package.json`. It’s unclear how you ended up in a situation where it isn’t present.

**Comment by eng-dibo** [comment]
as mentioned in the issue description, it is a monorepo that contains multiple angular projects. 
dependencies are moved to the top level, i.e the parent folder where angular.json lives

**Comment by alan-agius4** [comment]
This is is working as expected and the mentioned use-case is not supported.
