### ISSUE TITLE
ReferenceError: Blob is not defined

### ISSUE THREAD

**Issue by rom5jp** [angular/universal#2319]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ x ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?
No

### Description

Get the error "ReferenceError: Blob is not defined" after running `npm run dev:ssr` when trying to use Blob type. 

## 🔬 Minimal Reproduction

Declare a const with Blob type. Example: `const blob: Blob = file;`

Run: `npm run dev:ssr` 

package.json example:
{
  "name": "theapp",
  "version": "0.0.0",
  "scripts": {
    ...
    "dev:ssr": "ng run theapp:serve-ssr",
  },
  "private": true,
  "dependencies": {
    "@angular-slider/ngx-slider": "^2.0.3",
    "@angular/animations": "^11.2.3",
    "@angular/cdk": "^11.2.2",
    "@angular/common": "^11.2.3",
    "@angular/compiler": "^11.2.3",
    "@angular/core": "^11.2.3",
    "@angular/flex-layout": "^12.0.0-beta.34",
    "@angular/forms": "^11.2.3",
    "@angular/material": "^11.2.2",
    "@angular/platform-browser": "^11.2.3",
    "@angular/platform-browser-dynamic": "^11.2.3",
    "@angular/platform-server": "^11.2.3",
    "@angular/router": "^11.2.3",
    "@ng-select/ng-select": "^6.1.0",
    "@ngrx/store": "^12.4.0",
    "@nguniversal/express-engine": "^11.2.0",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@segment/consent-manager": "^5.2.0",
    "@sentry/node": "^6.10.0",
    "@sentry/tracing": "^6.10.0",
    "algoliasearch": "^3.35.1",
    "angular-instantsearch": "^3.0.0-beta.5",
    "angularx-social-login": "^3.5.4",
    "bootstrap": "^4.6.0",
    "express": "^4.15.2",
    "heic2any": "0.0.3",
    "instantsearch.css": "^7.4.5",
    "instantsearch.js": "^3.7.0",
    "ng-recaptcha": "^8.0.0",
    "ngx-bootstrap": "^6.2.0",
    "ngx-cookie": "^5.0.2",
    "ngx-cookie-service": "^11.0.2",
    "ngx-device-detector": "^2.1.1",
    "ngx-owl-carousel-o": "^6.0.0",
    "ngx-seo": "^5.3.0",
    "ngx-spinner": "^11.0.1",
    "rxjs": "^6.6.7",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.1102.2",
    "@angular/cli": "^11.2.2",
    "@angular/compiler-cli": "^11.2.3",
    "@nguniversal/builders": "^11.2.0",
    "@types/algoliasearch": "^4.0.0",
    "@types/algoliasearch-helper": "^3.0.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.6.0",
    "@types/jest": "^26.0.24",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "husky": "^4.3.8",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "jest": "^27.0.6",
    "jest-preset-angular": "^9.0.4",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "lint-staged": "^11.0.0",
    "moment": "^2.29.1",
    "npm-run-all": "^4.1.5",
    "prettier": "^2.3.2",
    "pretty-quick": "^3.1.1",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "tslint-config-prettier": "^1.18.0",
    "typescript": "~4.1.2"
  }
}

## 🔥 Exception or Error

<pre><code>
C:\...\app\server\main.js:114332
var blob = new Blob([workerString], {type: 'application/javascript'});
           ^

ReferenceError: Blob is not defined
    at C:\...\app\server\main.js:114332:12
    at C:\...\app\server\main.js:114326:26
    at Object.TEVI (C:\...\app\server\main.js:114330:2)
    at __webpack_require__ (C:\...\app\server\main.js:26:30)
    at Module.QwIL (C:\...\app\server\main.js:108792:66)
    at __webpack_require__ (C:\...\app\server\main.js:26:30)
    at Module.PCNd (C:\...\app\server\main.js:106167:109)
    at __webpack_require__ (C:\...\app\server\main.js:26:30)
    at Module.ZAI4 (C:\...\app\server\main.js:128098:80)
    at __webpack_require__ (C:\...\app\server\main.js:26:30)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:51088
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.2
Node: 14.17.6
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.2.2
@angular/cli                    11.2.2
@angular/flex-layout            12.0.0-beta.34
@angular/material               11.2.2
@angular/platform-server        11.2.14
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.0
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by CaerusKaru** [comment]
`Blob` is a [Web API](https://developer.mozilla.org/en-US/docs/Web/API/Blob), and is not available in Node unless you shim it. This is _not_ a Universal issue.
