### ISSUE TITLE
Got This Error While ng add @nguniversal/express-engine

### ISSUE THREAD

**Issue by CuisineCastLtd** [angular/universal#2323]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] common
- [ ] aspnetcore-engine
- [ ] builders
- [*] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

Schematic input does not validate against the Schema: {}
Errors:

  Data path "" should have required property 'clientProject'.

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 8.3.26
Node: 12.18.3
OS: win32 x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.26
@angular-devkit/build-angular     0.803.29
@angular-devkit/build-optimizer   0.803.29
@angular-devkit/build-webpack     0.803.29
@angular-devkit/core              8.3.26
@angular-devkit/schematics        8.3.26
@angular/cli                      8.3.26
@angular/http                     7.2.16
@ngtools/webpack                  8.3.29
@nguniversal/express-engine       8.2.6
@schematics/angular               8.3.26
@schematics/update                0.803.26
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

</code></pre>

**Comment by alan-agius4** [comment]
Version 8 is no longer supported please update to the latest stable version.

https://angular.io/guide/releases#support-policy-and-schedule
