### ISSUE TITLE
Angular Prerendering routes twice resulting in 2 transfer state script Tags and 2 "prerendered"-Comments

### ISSUE THREAD

**Issue by Jeremias-Nater** [angular/universal#2334]
# 🐞 Bug report

#### What modules are related to this issue?

- [X] builders
- [X] express-engine
- [X] TransferState
- [X] universal

#### Double Prerender
When providing routes to prerender, Angular starts prerendering my files twice starting from some point
End of prerendered file:
![image](https://user-images.githubusercontent.com/8191311/135411036-142d5c7b-51d3-4edf-958e-f27e67d0cbf0.png)

## 🔬 Minimal Reproduction
You can download the Project that i created to reproduce the problem [here from my github](https://github.com/Jeremias-Nater/universal-double-prerendering-minimal-reproduction)

in my project run:
- npm i
- npm run prerender
- check /dist/browser/detail/20 (The problem isn't there initially so at /dist/browser/detail/1 everything works fine for me)
- the file now should have 2 comments and 2 app state script tags at the end

to create this reproduction i did the following:
- Download finished tour of heroes example from https://angular.io/guide/universal
- add ServerTransferStateModule / BrowserTransferState Modules to the corresponding "app.server.module.ts" / "app.module.ts"
- create routes.txt file with routes to /detail/1-20
- mention routes.txt file in  angular.json in options of prerender script (angular.json:169)

## 🔥 Exception or Error

While in the minimal reproduction i did not provide any transfer state, in my real app the transferstate is set. The big issue now is that the first script tag with the same id is always empty which causes transferState to be useless essentially and the request to be made again

## 🌍 Your Environment

<pre><code>Angular CLI: 12.1.4
Node: 14.17.6
Package Manager: npm 6.14.15
OS: linux x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@nguniversal/builders           12.1.0
@nguniversal/express-engine     12.1.0
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5

</code></pre>

**Comment by alan-agius4** [comment]
I think this should be solved by https://github.com/angular/universal/commit/00cc596fe83fb4f4206b00e6a21975862dfd60e5

**Comment by alan-agius4** [comment]
Can you please check if the problem persists with the latest release?

**Comment by Jeremias-Nater** [comment]
The issue is resolved in that release. Thanks alot!
