### ISSUE TITLE
How to pass in environment variables during pre-rendering?

### ISSUE THREAD

**Issue by restfulhead** [angular/universal#2339]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [ ] builders
- [?] common
- [x] express-engine
- [ ] hapi-engine

### Description
It's sometimes necessary to pass in environment variables such as the server host name. Therefore I've added some code to `server.ts`. The code works when running `serve-ssr`, but seems to be ignored when running `prerender`.

```
server.get('*', (req, res) => {
    console.log('Setting up provider with', process.env.UI_BASE_URL)
    res.render(indexHtml, {
      req,
      providers: [
        { provide: APP_BASE_HREF, useValue: req.baseUrl },
        {
          provide: 'UI_BASE_URL',
          useValue: process.env.UI_BASE_URL,
        },
      ],
    })
  })
```

When I run `ng run may-app:serve-ssr --configuration development` I can see the log message and my service retrieves the base url via injection as expected. However, when running `ng run my-app:prerender`, then the code never executes. It seems that `prerender` does not use the Express route. How does `prerender` work and how can I provide it with an environment variable?

Update: Based on [this comment](https://github.com/angular/universal/issues/2339) there seem to be no requests during pre-rendering. So the Express server is not used and that's why the above code is never executed. The question remains, how can I provide environment variables when pre-rendering?

**Comment by alan-agius4** [comment]
You should be able to get this working during prerendering by configuring these providers in the applications’ server module instead of the server file.

**Comment by restfulhead** [comment]
Thanks, I missed to also move `dotenv.config()` from server.ts to AppServerModule in the beginning, but now it works.
