### ISSUE TITLE
Duplicate http requests after navigating

### ISSUE THREAD

**Issue by restfulhead** [angular/universal#2346]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [x] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?
Don't know, probably not.

### Description
When using TransferHttpCacheModule (or using the transferState service), the results seem to be cached only for the initial page load. Any client side navigation does not seem to use the cache, but retrieves the results via http again. Besides performance implications, this requires that API access is possible from the client, not just from the server (e.g. API keys need to be available client-side, which can be a problem).

I found the following related Stackoverflow post: https://stackoverflow.com/questions/50958193/angular-universal-ssr-transferstate-only-first-page-data-available

There is a non trivial answer proposing to write the JSON response into a separate file. Is this really required? If it is, should this not be part of Angular Universal? Or is this supposed to work out of the box, but maybe there's a bug or a user error?

## 🔬 Minimal Reproduction

- Download the example app https://angular.io/generated/zips/universal/universal.zip
- Replace the in-memory hero service http client with a real http call and add `TransferHttpCacheModule`
- Observe that e.g. when directly navigating to http://localhost:4200/detail/1 no http request is made by the browser
- Click on the "go back" button and then click on the hero again to go to the detail page
- Observe that now the browser issues a http request to the Heros API
- If you use `transferState` to manually set/get heros, you will observe that the state is available on first page load, but empty when navigating

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.8
Node: 14.17.3
Package Manager: npm 7.21.0
OS: darwin x64

Angular: 12.2.8
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.8
@angular-devkit/build-angular   12.2.8
@angular-devkit/core            12.2.8
@angular-devkit/schematics      12.2.8
@nguniversal/builders           12.1.1
@nguniversal/common             12.1.1
@nguniversal/express-engine     12.1.1
@schematics/angular             12.2.8
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by alan-agius4** [comment]
Closing as per above explanation is correct.
