### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by martijnhiemstra** [angular/universal#2347]
# 🐞 Bug report

@nguniversal/express-engine
- [x] express-engine

### Is this a regression?

Hasn't worked at all

### Description

When I install @nguniversal/express-engine so that I can use Angular SSR I get this error when running `npm run serve:ssr`

## 🔬 Minimal Reproduction

```
ng add @nguniversal/express-engine
npm run serve:ssr
```

## 🔥 Exception or Error

<pre><code>
/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:3389
document.webL10n = function (window, document, undefined) {
^

ReferenceError: document is not defined
    at Object.<anonymous> (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:3389:1)
    at __w_pdfjs_require__ (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:343:30)
    at Object.<anonymous> (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:3227:1)
    at __w_pdfjs_require__ (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:343:30)
    at Object.<anonymous> (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:527:20)
    at __w_pdfjs_require__ (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:343:30)
    at /home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:407:18
    at /home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:410:10
    at webpackUniversalModuleDefinition (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:321:20)
    at Object.+Nuo (/home/martijn/Projects/MyProject/Websites/Website/dist/Website/server/main.js:323:3)

A server error has occurred.
node exited with 1 code.
connect ECONNREFUSED 127.0.0.1:40169

</code></pre>

## 🌍 Your Environment

<pre><code>

Your global Angular CLI version (12.1.1) is greater than your local version (9.1.15). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.15
Node: 14.17.2
OS: linux x64

Angular: 9.0.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.7
@angular-devkit/build-angular     0.1001.7
@angular-devkit/build-optimizer   0.1001.7
@angular-devkit/build-webpack     0.1001.7
@angular-devkit/core              10.1.7
@angular-devkit/schematics        9.1.15
@angular/cdk                      11.2.13
@angular/cli                      9.1.15
@ngtools/webpack                  10.1.7
@nguniversal/builders             9.1.1
@nguniversal/common               9.1.1
@nguniversal/express-engine       9.1.1
@schematics/angular               9.1.15
@schematics/update                0.901.15
rxjs                              6.5.5
typescript                        3.7.7
webpack                           4.44.1

</code></pre>

I have tried several "so called" solutions that involve editing server.js however they all DON'T work.

**Comment by CaerusKaru** [comment]
Please read the issue template before opening any issues. This is a common, avoidable problem that you must solve for your own application.
