### ISSUE TITLE
How to load SSR just in a specific module

### ISSUE THREAD

**Issue by calldeludo** [angular/universal#2351]
After hours researching and trying a lot of things... i could not find the way to implement SSR just in a specific module...
In my case i have a big App which use a lot of libraries. One of them is not compatible with Angular SSR.
So i would need to "exclude" or just load the module that i want to implement SSR

When you install the Angular universal package by CLI it is prepared to work loading the AppModule... what do i have to change  to be loaded in a specific module?

This is my routes code.

```
const routes: Routes = [
    { path: '', pathMatch: 'full', canActivate: [CheckDomainGuard], component: LandingPageComponent },
    // { path: 'areaEmpresa', canActivate: [CheckDomainGuard], loadChildren: () => import('./modules/area-empresa/area-empresa.module').then(m => m.AreaEmpresaModule) },
    //{ path: 'eventos', canActivate: [CheckDomainGuard], loadChildren: () => import('./modules/eventos/eventos.module').then(m => m.EventosModule) },
    {
        path: 'shop',
        canActivate: [IsModuloTiendaGuard, GetTiendaConfigGuard],
        loadChildren: () => import('./components/tienda/home/home.module').then(m => m.HomeModule)
    },
    { path: '**', canActivate: [CheckDomainGuard], component: LandingPageComponent }
];
```
I wanted use SSR just in my HomeModule ( path: shop )...
Any help is really appreciate. Thanks in advance

**Comment by nagavenkateshK** [comment]
server.get('/areaEmpresa/**', (req, res) => {
    res.sendFile(path.join(distFolder, indexHtml));
  });

Add this code in server.ts file. Above code will exclude your module routing starts with "areaEmpresa" on server side.

**Comment by calldeludo** [comment]
> server.get('/areaEmpresa/**', (req, res) => { res.sendFile(path.join(distFolder, indexHtml)); });
> 
> Add this code in server.ts file. Above code will exclude your module routing starts with "areaEmpresa" on server side.

Thanks for you answer @nagavenkateshK , i will try it but... i think this does not solve the problem of compatibility that i have with some libraries... as @alan-agius4 commented the whole app has to be compatible with SSR...
