### ISSUE TITLE
ReferenceError: document is not defined - Bootstrap 5

### ISSUE THREAD

**Issue by yoyo3071a** [angular/universal#2352]
Hi,

I have an error with my script without any correction.
SSR doesn't work : ReferenceError: document is not defined

I have tries to add this a the top of server.ts : 
```
import * as domino from 'domino'
const distFolder = join(process.cwd(), 'dist/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
const template = readFileSync(join(distFolder, indexHtml)).toString();
const window = domino.createWindow(template.toString());

global['document'] = window.document;
```
But nothing work. My angular app used Angular Material (and there no probleme of document is not defined) before but now we are now using pure Bootstrap 5 (no component library and working for the browser part) and the server part of the application doesn't work anymore. This server part is used for SEO only.

Have you any other proposition to correct this problem ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
