### ISSUE TITLE
Missing cookies in SSR rendering

### ISSUE THREAD

**Issue by radudalbea** [angular/universal#2354]
Hi Guys,

The ngExpressEngine doesn't attach the cookies to the request when the component renders from server.

I have a component that makes a http call on ngOnInit and when it renders from server everthing is empty on the cookies.

 app.engine('html', ngExpressEngine({
    bootstrap: AppServerModule
  }));
  app.set('view engine', 'html');
  app.set('views', distFolder);
  app.get('/api/test-route', function (request: any) {
    console.log(request.headers.cookie); // is undefined
  }); 

The call from ngOnInit is http.get('/api/test-route');

Could you please provide a solution for this? I have been looking online for one and it doesn't seem to be one available.

I suppose that as long as you are rendering a component then everything about the request should be already in place.

Thanks.

**Comment by peturh** [comment]
Not sure if this is best practice anymore, but I solved it by adding an interceptor running server side that I add to `app-server.module.ts`

It takes the cookies from the request and adds as a header. Then on the Node, I can change the header to a cookie.  

```
import { HttpHandler, HttpHeaders, HttpInterceptor, HttpRequest } from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';

import { PlatformService } from '../platform.service';

@Injectable()
export class CookieInterceptor implements HttpInterceptor {
  requestHeader: HttpHeaders;

  constructor(
    @Optional() @Inject('REQUEST') protected req: any,
    public platformService: PlatformService,
  ) {}

  intercept(request: HttpRequest<any>, next: HttpHandler) {
    if (this.platformService.isServer) {
      let headers = new HttpHeaders();

      headers = headers.set('MyCookies', JSON.stringify(this.req.cookies));

      const authReq = request.clone({
        headers: headers,
      });

      return next.handle(authReq);
    } else {
      return next.handle(request);
    }
  }
}

```

Then on the node, I add this middleware before cookies are needed.

```
app.use((req, res, next) => {
  const myCookies = req.get('MyCookies');
  try {
    req.cookies = JSON.parse(myCookies);
  } catch (e) {}
  next();
});
```

**Comment by radudalbea** [comment]
Thanks for the answer. I implemented a similar solution. This should be handled by the framework though. With all the things included in angular they lack support for simple tasks like this :)

**Comment by CaerusKaru** [comment]
I think you're putting a lot of pressure on the framework to meet your needs here. While I agree we definitely need _docs_ around how to handle this issue, there's enough ambiguity from server provider to server provider to make it untenable from a framework perspective. This is covered in https://github.com/angular/universal/issues/1732, so I'm closing this in favor of that, especially since this works as expected.
