### ISSUE TITLE
getBrowserCodeStream eats up errors

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#239]
wrapping `getBrowserCodeStream` with a try catch I was able to detect that an error was being thrown when I provided an invalid preset 

`Invalid preset: keydown`

**Comment by jeffwhelpley** [comment]
@JohnGorter mentioned he wanted to work on this one.

**Comment by jeffwhelpley** [comment]
@JohnGorter tested this out and it works now. May have been fixed with one of the other preboot changes.
