### ISSUE TITLE
TypeError: window.addEventListener is not a function

### ISSUE THREAD

**Issue by GNURub** [angular/universal#2390]
Error compiling the project in SSR mode

![image](https://user-images.githubusercontent.com/1318648/137588123-aa53c610-8b17-4e10-b51b-d3d6a4a00fcf.png)

	  $ ng version
	  
	       _                      _                 ____ _     ___
	      / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
	     / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
	    / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
	   /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
	                  |___/
	      
	  
	  Angular CLI: 12.2.10
	  Node: 14.18.1
	  Package Manager: yarn 1.22.5
	  OS: linux x64
	  
	  Angular: 12.2.10
	  ... animations, cdk, cli, common, compiler, compiler-cli, core
	  ... forms, language-service, localize, material
	  ... platform-browser, platform-browser-dynamic, platform-server
	  ... router, service-worker
	  
	  Package                         Version
	  ---------------------------------------------------------
	  @angular-devkit/architect       0.1202.10
	  @angular-devkit/build-angular   12.2.10
	  @angular-devkit/core            12.2.10
	  @angular-devkit/schematics      12.2.10
	  @nguniversal/builders           12.1.1
	  @nguniversal/express-engine     12.1.1
	  @schematics/angular             12.2.10
	  rxjs                            7.4.0
	  typescript                      4.4.4
	      
	  Done in 0.89s.

**Comment by CaerusKaru** [comment]
Please read the issue template. This is not an issue with Universal.
