### ISSUE TITLE
Angular SSR build failure when using dynamically loaded components

### ISSUE THREAD

**Issue by adigourdi** [angular/universal#2425]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

Yes, the previous version in which this bug was not present was: ^8

### Description

We successfully use dynamically loaded components with custom HTML containing Angular components without using SSR, with latest @angular/* packages and AOT set to false

But attempting to build with SSR fails not recognizing code related to the Angular compiler and component decorator(s)

There is no option like AOT for SSR builder in `angular.json`, and setting `optimization` to `false` doesn't resolve the issue

## 🔬 Minimal Reproduction

I have created a [repo demonstrating the issue](https://github.com/adigourdi/angular-ssr-dynamic-html), containing the code below:

```typescript
private async createComponent(template: string) {
  const metadata = {
    template: template,
  };

  const cmpntCls = class DynamicComponent {};
  const decoratedCmpntCls = Component(metadata)(cmpntCls);

  @NgModule({
    imports: [CommonModule, CounterModule],
    declarations: [decoratedCmpntCls],
  })
  class RuntimeComponentModule {}

  const targetMdl = await this.compiler.compileModuleAsync(RuntimeComponentModule);

  return [decoratedCmpntCls, targetMdl];
}
```

More with a readme at the repo: [https://github.com/adigourdi/angular-ssr-dynamic-html](https://github.com/adigourdi/angular-ssr-dynamic-html)

## 🔥 Exception or Error

<pre><code>Error: src/app/app.component.ts:43:21 - error NG1010: Value at position 0 in the NgModule.declarations of RuntimeComponentModule is not a reference
  Value could not be determined statically.

43       declarations: [decoratedCmpntCls],
                       ~~~~~~~~~~~~~~~~~~~

  src/app/app.component.ts:43:22
    43       declarations: [decoratedCmpntCls],
                            ~~~~~~~~~~~~~~~~~
    Unable to evaluate this expression statically.
  src/app/app.component.ts:39:31
    39     const decoratedCmpntCls = Component(metadata)(cmpntCls);
                                     ~~~~~~~~~~~~~~~~~~~
    Unable to evaluate this expression statically.
  src/app/app.component.ts:39:31
    39     const decoratedCmpntCls = Component(metadata)(cmpntCls);
                                     ~~~~~~~~~
    Unable to evaluate an invalid expression.
</code></pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 12.2.12
Node: 14.17.6
Package Manager: npm 6.14.15
OS: linux x64

Angular: 12.2.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.12
@angular-devkit/build-angular   12.2.12
@angular-devkit/core            12.2.12
@angular-devkit/schematics      12.2.12
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.12
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by alan-agius4** [comment]
SSR requires an application to be fully AOT. In general JIT mode is not recommended to be used on production environments were typically SSR is expected to be used. This is due to the increase in bundle size and degraded performance when using JIT.

While, JIT SSR can be an option, I don't see a very appealing use-case. Typically, you add SSR If you want to improve the application's performance and SEO ranking, however by using JIT you are opting out of a large set of optimisations both during runtime and build time such as advanced dead-code elimination etc.. which IMHO are too big to mitigate using SSR.

**Comment by adigourdi** [comment]
SSR can make the application seem performant by prerendering the initial page, but our main use case is SEO

I agree with you not seeing a very appealing use-case, but we do have one, as written in the repo mentioned above

> We need this so using a WYSIWYG editor, we can simply write a tag `[tag]` and transform it to a `<app-tag>` component
> 
> Following the example in this repo, we can use `[counter start="2" step="2"]` to generate `<app-counter start="2" step="2"><app-counter>`
> 
> We can use javascript to make interactive HTML instead of the angular component, but the access to most of the angular/typescript code (api, logging, npm packages, ...) will be hacky or require a js rewrite, so this solution seems cleaner

**Comment by alan-agius4** [comment]
Note, that in the above case, unless the HTML is validated you are exposing yourself to XHR vulnerabilities since you are using JIT and arbitrary HTML input. 

In general in cases like the above, using Angular Elements or Web elements would be a better option.  For SSR aspect in your case I think you can use the experimental JSDOM based SSR which I think it should work for JIT applications. To opt-in run `ng add @nguniversal/common`.

Realistically speaking, unless there is a large request from this from the community (which I don't think so), I don't think we will support SSR in JIT mode.

**Comment by alan-agius4** [comment]
[`ng add @nguniversal/common`](https://github.com/angular/universal/tree/master/modules/common/clover) will add a different experimental SSR approach. You need to remove the SSR logic from the current application though to get this working.

**Comment by adigourdi** [comment]
Alright, confirmed working on the above test repo, with AOT enabled. I'll confirm if it works on our main repo ASAP

**Comment by adigourdi** [comment]
The app works fine, or even better than before:

* no `server.module` with special server implementations
* and almost no more testing for `isPlatformBrowser` (testing now only for `scrollIntoView` calls, which can be expected in a server environment)

Only issue is that server.ts built into dist contains require calls to packages `@nguniversal/common`, `express`, `path`, and `url`. This makes the dist folder not standalone for docker builds

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module '@nguniversal/common/clover/server'
Require stack:
- /app/server/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.510 (/app/server/main.js:11:18)
    at __webpack_require__ (/app/server/main.js:65:41)
    at /app/server/main.js:120:91
    at /app/server/main.js:165:3
    at Object.<anonymous> (/app/server/main.js:170:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/app/server/main.js' ]
}
```

I tried creating a separate package.json to inject into the build folder (dist/projectname/.), another issue shows up:

```
internal/modules/cjs/loader.js:948
    throw new ERR_REQUIRE_ESM(filename);
    ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /app/node_modules/@nguniversal/common/fesm2015/clover/server.mjs
    at new NodeError (internal/errors.js:322:7)
    at Module.load (internal/modules/cjs/loader.js:948:11)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.510 (/app/server/main.js:11:18)
    at __webpack_require__ (/app/server/main.js:65:41)
    at /app/server/main.js:120:91
    at /app/server/main.js:165:3
    at Object.<anonymous> (/app/server/main.js:170:12) {
  code: 'ERR_REQUIRE_ESM'
}
```

Anyway, the clover implementation seems promising, but just how experimental is it ? I suppose the requires should not be left in the server build

**Comment by adigourdi** [comment]
Update:

> with AOT enabled

Excuse me for the confusion about AOT, it is still required for the dynamic loading in browser regardless of SSR usage

For the required packages mentioned in my previous comment, now I realize that we need to include production modules withing the docker image, which we didn't need previously

Other than that, I suppose clover does solve the main issue.

**Comment by alan-agius4** [comment]
You can remove `bundleDependencies: false` from your angular.json which should result in all modules to be bundled as part of the main.js server bundle.

**Comment by adigourdi** [comment]
Thanks for the reply Alan, but I have already updated my docker image to use node_modules

For the record, removing `bundleDependencies: false` or setting it to true results in the errors below (new ng@12 project with node@14)

```
./node_modules/jsdom/node_modules/ws/lib/buffer-util.js:105:21-42 - Warning: Module not found: Error: Can't resolve 'bufferutil' in '/workspace/project/node_modules/jsdom/node_modules/ws/lib'

./node_modules/jsdom/node_modules/ws/lib/validation.js:86:20-45 - Warning: Module not found: Error: Can't resolve 'utf-8-validate' in '/workspace/project/node_modules/jsdom/node_modules/ws/lib'

./node_modules/jsdom/lib/jsdom/utils.js:154:2-27 - Error: Module not found: Error: Can't resolve 'canvas' in '/workspace/project/node_modules/jsdom/lib/jsdom'
```

**Comment by alan-agius4** [comment]
Closing as JIT is not supported.
