### ISSUE TITLE
Unknown option: '--base-href'

### ISSUE THREAD

**Issue by mebibou** [angular/universal#2445]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
No

### Description

 A clear and concise description of the problem...

I am trying to prerender an app where the `base-href` needs to be specified. When doing `ng build --base-href` it works fine, but it doesn't work for pre-rendering.

## 🔬 Minimal Reproduction

1. Create a new app
2. Add universal plugin
3. Call `ng run myapp:prerender --base-href=/test/`

## 🔥 Exception or Error

<pre><code>
$ ng run myapp:prerender --base-href=/test/
Unknown option: '--base-href'
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 12.2.13
Node: 12.22.6
Package Manager: npm 6.14.15
OS: darwin x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.9
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.9
@angular-devkit/schematics      12.2.13
@angular/cdk                    12.2.12
@angular/google-maps            12.2.12
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

**Comment by alan-agius4** [comment]
This is expected since the `baseHref` is a browser builder option. 

Instead of using the command line argument to provide the value, you can configure this option in `angular.json`. This cause the `baseHref` option from the config to be used when the browser build is executed when running the prerender buiilder.

```json
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "baseHref": "/test/",
            "index": "src/index.html",
```

**Comment by mebibou** [comment]
@alan-agius4 ok but the `base-href` option is supposed to override this on the command line, so you can do it without modifying the `angular.json` file
