### ISSUE TITLE
replay 'input' and 'change' events during preboot

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#245]
when binding to the `(input)` event the events being played back are. I think the change event probably needs to be replayed too

**Comment by jeffwhelpley** [comment]
Should be just adding "input" to "keyPress" preset in presets.ts for preboot.

**Comment by gdi2290** [comment]
we also need `change` event

**Comment by manekinekko** [comment]
see PR https://github.com/angular/universal/pull/288
