### ISSUE TITLE
Module '"@angular/core"' has no exported member 'NgModuleFactoryLoader'

### ISSUE THREAD

**Issue by oneclickwebstudio** [angular/universal#2451]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 After upgrading to Angular v13 it stopped working

## 🔬 Minimal Reproduction

```ng serve```

## 🔥 Exception or Error

<pre><code>

Error: node_modules/@nguniversal/module-map-ngfactory-loader/src/module-map-ngfactory-loader.d.ts:8:10 - error TS2305: Module '"@angular/core"' has no exported member 'NgModuleFactoryLoader'.

8 import { NgModuleFactoryLoader, InjectionToken, NgModuleFactory, Compiler } from '@angular/core';

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 13.0.3
Node: 16.13.0
Package Manager: npm 8.1.4
OS: darwin x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1300.3 (cli-only)
@angular-devkit/build-angular              13.0.3
@angular-devkit/core                       13.0.3 (cli-only)
@angular-devkit/schematics                 13.0.3 (cli-only)
@angular/cli                               13.0.3
@angular/flex-layout                       12.0.0-beta.35
@nguniversal/express-engine                13.0.1
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        13.0.3 (cli-only)
rxjs                                       7.4.0
typescript                                 4.4.4

</code></pre>

**Comment by CaerusKaru** [comment]
That API was removed as part of v13 (see [CHANGELOG](https://github.com/angular/angular/blob/master/CHANGELOG.md#router)). This is also not a Universal issue, so I'm closing this.

**Comment by alan-agius4** [comment]
`@nguniversal/module-map-ngfactory-loader` package was deprecated and removed since version 9, as this is no longer required.
