### ISSUE TITLE
Server cant start 

### ISSUE THREAD

**Issue by phihochzwei** [angular/universal#2466]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Description

 A clear and concise description of the problem...

I just added Universal to our current project and the below exception is thrown. I did not alter the main.ts in any way

## 🔥 Exception or Error

<pre><code>

module.exports = require("@angular/core");
                 ^
Error [ERR_REQUIRE_ESM]: require() of ES Module C:\__GIT\deich-lib\node_modules\@angular\core\fesm2015\core.mjs not supported.
Instead change the require of C:\__GIT\deich-lib\node_modules\@angular\core\fesm2015\core.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.@angular/core (C:\__GIT\deich-lib\dist\apps\storefront-ssr\main.js:26591:18)
    at __webpack_require__ (C:\__GIT\deich-lib\dist\apps\storefront-ssr\main.js:26687:41)
    at C:\__GIT\deich-lib\dist\apps\storefront-ssr\main.js:26708:16
    at C:\__GIT\deich-lib\dist\apps\storefront-ssr\main.js:26747:3
    at Object.<anonymous> (C:\__GIT\deich-lib\dist\apps\storefront-ssr\main.js:26752:12)

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.0.4
Node: 16.13.0
Package Manager: npm 8.1.0
OS: win32 x64

Angular: 13.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.1300.4
@angular-devkit/build-angular              13.0.4
@angular-devkit/core                       13.0.4
@angular-devkit/schematics                 13.0.4
@angular/cli                               13.0.4
@nguniversal/express-engine                13.0.1
@nguniversal/module-map-ngfactory-loader   v8.2.6
@schematics/angular                        13.0.4
ng-packagr                                 13.0.8
rxjs                                       7.4.0
typescript                                 4.4.4

</code></pre>

**Comment by amakhrov** [comment]
As suggested here (https://github.com/angular/universal/issues/2425#issuecomment-963190893) , removing `bundleDependencies: false` from angular.json solves this issue. But brings in other errors (like `Error: Module not found: Error: Can't resolve 'hiredis' in '<root>/node_modules/redis-parser/lib'`.

Also in our case the original error is not with `angular/core` but with `angular/common`:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/amakhrov/crunchbase/client_app/node_modules/@angular/common/fesm2015/common.mjs
at Module.load (internal/modules/cjs/loader.js:861:11)
```

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
