### ISSUE TITLE
Reload cause pending request

### ISSUE THREAD

**Issue by conradkirschner** [angular/universal#2476]
Currently the live reloading feature cause a pending request (after "manuelly reloading" it works) 

Therefore I would suggest to give a optional timeout parameter here, that would be configurable in the config. 

https://github.com/angular/universal/blob/f14d5e670bfc42f28e73faa452c17a74dc47f88e/modules/builders/src/ssr-dev-server/index.ts#L128

Any doubts about some optional parameter for waiting there?

**Comment by conradkirschner** [comment]
Added suggestion as code 
https://github.com/angular/universal/pull/2477

**Comment by conradkirschner** [comment]
I guess it has something to do with internationalization + slow hardware -> after setting a timeout to 2 seconds it worked as expected.

**Comment by Gkleinereva** [comment]
I likely have other underlying problems contributing to hanging requests on SSR hot reloads (potentially I18N and un-handled platform-specific functionality like interaction with localStorage), and I'll look into those.  But I thought I'd chime in to say that adding a configurable timeout where @conradkirschner suggests does fix this issue in my repository!

**Comment by TheJLifeX** [comment]
I have the same problem (hot reload reload causes pending request) in Angular Universal (Version 14.2.0). I have tested it on different browsers (Chrome, Microsoft Edge and Firefox) and the same thing happens.
