### ISSUE TITLE
iisnode encountered an error when processing the request

### ISSUE THREAD

**Issue by broy-github** [angular/universal#2484]
Hello,

I am trying to host my Angular 8 universal app in the IIS of Windows Server 2019.
I have the dist folder, main.js and web.config file in the root directory of the hosted site.
I have installed the iisnode in the server.
When I browse the site a blank iisnode folder is created on the root directory.
I have set the full control permissions to IIS_IUSR and IUSR to the root directory.
But I am getting the following errors:

![error](https://user-images.githubusercontent.com/67911901/146812684-bee4bb50-f75c-474e-93aa-38d6b88d1973.png)

Please help me.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com).

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
