### ISSUE TITLE
Universal Not Working in Production Version with Service Worker

### ISSUE THREAD

**Issue by jdgamble555** [angular/universal#2488]
1. `npm i -g @angular/cli`
2. `ng new test`
3. `ng add @nguniversal/express-engine`
4. `ng add @angular/pwa`
5. `npm run build:ssr && npm run serve:ssr`

The browser version (regular Angular) is always displayed, and not the server version (Angular Universal).  You can change the port and open up in a private browser window, and it still does not work.

However, running `npm run dev:ssr` in the development environment works fine.

J

**Comment by alan-agius4** [comment]
Working as expected. 

See: https://github.com/angular/angular/issues/37131
