### ISSUE TITLE
rethink angular2-webpack-prerender

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#249]
We probably should rethink the API for this. cc @manekinekko

**Comment by manekinekko** [comment]
@gdi2290 could we spec out the new API?

**Comment by jeffwhelpley** [comment]
@gdi2290 it would be good if you can explicitly list out what is wrong with the current API and what we want to achieve.

**Comment by jeffwhelpley** [comment]
Closing for now. I think we will end up doing this along with some other future refactoring. Not enough pain to warrant doing something for right now.
