### ISSUE TITLE
Restful 

### ISSUE THREAD

**Issue by vishalmanchanda** [angular/universal#250]
I want to use server side rendering over a restful interface -Is there a sample for that or if you can let us know how to approach this? Looking for angular HTML and json to be sent to server over restful and get the plain html after server rendering.

**Comment by jeffwhelpley** [comment]
This is a good example:

https://github.com/angular/universal-starter 

Try it out and let us know if you have any questions.

**Comment by gdi2290** [comment]
I think he was talking about [restful](https://www.npmjs.com/package/restful)

**Comment by jeffwhelpley** [comment]
Ah, OK, Sorry, I am unfamiliar with restful. OK, so @vishalmanchanda check out the information in this issue as the use of pretty much any node.js server side template engine alongside Angular 2 Universal works pretty much the same way:

https://github.com/angular/universal/issues/177

Let me know if you have any questions.
