### ISSUE TITLE
Beautify markup please

### ISSUE THREAD

**Issue by Munhoziii** [angular/universal#251]
Beautify pre-rendered application. Currently markup is questionable.

<img width="476" alt="screen shot 2016-02-04 at 4 41 21 pm" src="https://cloud.githubusercontent.com/assets/6660156/12834679/2c23bc7e-cb5e-11e5-842a-41f76ae8ef70.png">

**Comment by jeffwhelpley** [comment]
@gdi2290 I am not familiar with this. What specifically needs to be changed here?

**Comment by gdi2290** [comment]
`<div></div>` and  `<section>` are on the same line so maybe we should use something like https://github.com/beautify-web/js-beautify

**Comment by jeffwhelpley** [comment]
Ahhh..ok, got it. I thought it was the comments that were the problem (which I didn't recognize). Just having stuff on the right new lines and tabbing makes sense and is doable.

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/4873b6c4a4af585e54ffdd11d0c3d416e340eba1
