### ISSUE TITLE
Angular Universal app keeps loading problem

### ISSUE THREAD

**Issue by tohedul** [angular/universal#2517]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

Issue 1: 
When I run dev:ssr, the browser keeps loading but nothing happens.
Not even show any error just keep loading, though API call from service works fine.

Issue 2:
When I run serve:ssr right after build:ssr, it shows garbage value in the console and happens nothing.
ex:
void 0===ignoreDuplicate&&(ignoreDuplicate=!1),patches.hasOwnProperty(name)){if(!ignoreDuplicate&&checkDuplicate)throw Error("Already loaded patch: "+name)}else if(!global2["__Zone_disable_"+name]){var perfName="Zone:"+name;mark(perfName),patches[name]=fn2(global2,Zone3,_api),performanceMeasure(perfName,perfName)}},Object.defineProperty(Zone3.prototype,"parent",{get:function(){return this._parent},enumerable:!1,configurable:!0}),Object.defineProperty(Zone3.prototype,"name",{get:function(){return this._name},enumerable:!1,configurable:!0}),Zone3.prototype.get=function(key){var zone=this.getZoneWith(key);if(zone)return zone._properties[key]},Zone3.prototype.getZoneWith=function(key){for(var current=this;current;){if(current._properties.hasOwnProperty(key))return current;current=current._parent}return null},Zone3.prototype.fork=function(zoneSpec){if(!zoneSpec)throw new Error("ZoneSpec required!");return this._zoneDelegate.fork(this,zoneSpec)},Zone3.prototype.wrap=function(callback,source){if("function"!=typeof callback)throw new Error("Expecting function got: "+callback);var _callback=this._zoneDelegate.intercept(this,callback,source),zone=this;return function()

How can I solve those issues?

</code></pre>

## 🌍 Your Environment

<pre><code>

 _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.2
Node: 16.13.1
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/flex-layout            13.0.0-beta.36
@nguniversal/builders           13.0.1
@nguniversal/express-engine     13.0.1
@schematics/angular             13.1.2
rxjs                            6.6.7
typescript                      4.4.4

</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by LeParadoxHD** [comment]
@tohedul This also happens to me sometimes, usually is caused by long processes running in the server mode like Observables. What I did in my project is to comment out every part and start uncommenting parts of the project to discover which piece of code was causing the response to never end. As I said, most of the time is caused by Observables like `interval` or `timer`. Make sure they run only on Browser mode with `isPlatformBrowser()`.

Hope it helps.

**Comment by hiepxanh** [comment]
check all your interval, timer, settimeout, subscribe object, ws object, all async think could be problem.
My solution, binary check:
- 1) go to app routing file 
- 2) turn off half of page you have
- 3) try SSR again
- 4) test one by one page, and then you can find the root of cause
binary check is the key.

(for faster, you can begin with turn off every page accept the most simple page: about-us, 404-not-found, and see SSR can work)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
