### ISSUE TITLE
document the difference between tasks, microtasks, queues and schedulers

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#252]
It turns out this is pretty important for developers who debugging universal apps on the server. We don't have to go deep only a brief guideline

**Comment by alexpods** [comment]
@gdi2290 Maybe we should just give a link on [this article](https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/)?

**Comment by alexpods** [comment]
For more advanced developers: [part from ES6/2015 specification](http://www.ecma-international.org/ecma-262/6.0/#sec-jobs-and-job-queues)

**Comment by jeffwhelpley** [comment]
I am going to start to consolidate all documentation here for now:

https://docs.google.com/document/d/1Qem6PJ1EO5tYpGxfpj5w-4kuykW072GCrC3FmWI3_yY/edit?usp=sharing

I am working with Ward Bell to get everything to angular.io. Closing this for now, but this will be included in our official docs.
