### ISSUE TITLE
Hi @diogen737, that is because you are mocking the window only for the SSR'd page. That's because the `app` method is not called during prerendering.

### ISSUE THREAD

**Issue by chuhancheng** [angular/universal#2520]
Hi @diogen737, that is because you are mocking the window only for the SSR'd page. That's because the `app` method is not called during prerendering.

https://github.com/diogen737/angular-prerender/blob/0634458122ce310e1faa2d46a99b5322d8bb9b2d/server.ts#L20-L22

You'd need to patch the Window object prior to that, or opt in using dependency injection instead of access the Window global directly.

_Originally posted by @alan-agius4 in https://github.com/angular/universal/issues/1742#issuecomment-649490187_

---
Hi @alan-agius4,

Sorry, I get same issue recently. I don't understand where or how to patch window object for prerender environment. Any suggestion?

Many thanks!

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
