### ISSUE TITLE
Proposal: align releasing time of @nguniversal minor versions with @angular packages

### ISSUE THREAD

**Issue by Platonn** [angular/universal#2527]
# Proposal

#### What is the summary of the proposal?
Currently the `@angular` packages are in v13.2.x, but `@nguniversal` didn't yet release the v13.1 final (it's -next only at the moment of writing). For library consumers this might a bit confusing (actually it is for me), when bumping `@angular` packages to the latest minor, but not allowed to bump `@nguniversal` to the same minor version, but keep on a lower version. 

#### What is the proposal?
Do you think you could align the releasing time of the `@nguniversal` minor versions with the `@angular` packages?

**Comment by alan-agius4** [comment]
Hi @Platonn,

In general outside of majors we’d like not to couple releases.

While at the moment ‘@angular` packages are released with the same minor version, there is no guarantee that it will always be the case.

//FYI @dgp1130 & @josephperrott
