### ISSUE TITLE
When code include browser function (like setTimeout), builder return error

### ISSUE THREAD

**Issue by sundaynamaste** [angular/universal#2541]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [v] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description
- angular version : 12

When use AngularUniversal, sometimes can miss wrap browser function (like setTimeout) with "isPlatformBrowser".
(if (isPlatformBrowser(this.platformId)) { // Client only code })

Now builder and express show no errors.
so It can be used at Production and keep loading and fail.
(https://stackoverflow.com/questions/54700345/angular-universal-express-server-keeps-loading-and-fails-with-err-empty-response)

### Describe the solution you'd like
It would be better to show errors and fail to build when build for server (ssr)

### Describe alternatives you've considered
express-engine shows the error.

Thanks for your great works!

**Comment by CaerusKaru** [comment]
We consider using `isPlatformBrowser` in most cases to be an anti-pattern. You can learn more about why in [this article](https://medium.com/@caerus.karu/isplatformbrowser-is-not-your-friend-5ee52b06da89). As such, we won't be considering this proposal for any of the libraries in this repo. However, if you feel strongly enough about this, you are of course welcome to develop your own engine and vend it through NPM. The express-engine after all is little more than a thin wrapper around the utilities vended in the `common` library.
