### ISSUE TITLE
Update dependencies to latest @angular/cli

### ISSUE THREAD

**Issue by alfaproject** [angular/universal#2544]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] aspnetcore-engine
- [x] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Description

Latest stable version requires an old version of @angular/cli and makes me have duplicates of architect and whatnot in my dependency tree

### Describe the solution you'd like

Either relax the dependency versions or release a new stable release for @angular/cli 13.2

### Describe alternatives you've considered

I'm using yarn resolutions but that feels unnecessary if this package gets updated together with the rest of the ecosystem

**Comment by alan-agius4** [comment]
Closed via https://github.com/angular/universal/pull/2582/commits
