### ISSUE TITLE
JIT compilation failed for injectable [class PlatformLocation] when the app is rin in Webpack

### ISSUE THREAD

**Issue by MiguelAngelGarciaGomez** [angular/universal#2549]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] aspnetcore-engine
- [ ] builders
- [ ] common
- [x] express-engine
- [ ] hapi-engine

### Is this a regression?

Yes, the previous version in which this bug was not present was: 7.1.1

### Description

When the application is bundled with Webpack and you try to run it the following error is thrown. There were no compilations errors, only when the application is run is when the error is thrown.

## 🔬 Minimal Reproduction

I have created the following repo: https://github.com/MiguelAngelGarciaGomez/angular13-webpack that contains the minimum configuration that is needed to reproduce the problem. 

It can be reproduced executing the following commands:
```
npm run build:ssr:uat
```
This command generates the `dist` folder with the `server.js` file.
Then, to try this as in the production environment that we have, we are using PM2, that can be installed with:
```
npm install pm2@latest -g
```
And then, to run the `server.js` file:
```
pm2 start ecosystem.config.js --env uat
```
In order to get the logs:
```
pm2 logs dex
```
And in this log is where the error I posted earlier is thrown.

## 🔥 Exception or Error

<pre><code>
JIT compilation failed for injectable [class PlatformLocation]
Error: The injectable 'PlatformLocation' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.
The injectable is part of a library that has been partially compiled.
However, the Angular Linker has not processed the library such that JIT compilation is used as fallback.
Ideally, the library is processed using the Angular Linker to become fully AOT compiled.
Alternatively, the JIT compiler should be loaded by bootstrapping using '@angular/platform-browser-dynamic' or '@angular/platform-server',
or manually provide the compiler with 'import "@angular/compiler";' before bootstrapping.
    at getCompilerFacade ([...]/server.js:[...])
    at Module.ɵɵngDeclareFactory ([...]/server.js:[...])
    at Module.<anonymous> ([...]/server.js:[...])
    at __webpack_require__ ([...]/server.js:[...])
    at Module.XMLHttpRequestEventTarget.constructor ([...]/server.js:[...])
    at __webpack_require__ ([...]/server.js:[...])
    at Module.<anonymous> ([...]/server.js:[...])
    at __webpack_require__ ([...]/server.js:[...])
    at Module.<anonymous> ([...]/server.js:[...])
    at __webpack_require__ ([...]/server.js:[...])
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.3
Node: 14.17.1
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@nguniversal/builders           13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.3
rxjs                            7.5.4
typescript                      4.5.5
webpack                         5.68.0
</code></pre>

**Comment by alan-agius4** [comment]
Hi @MiguelAngelGarciaGomez,

The problem is that the server bundle is not being compiled using the Angular compiler, and therefore it is using JIT which requires the compiler during runtime.

it is recommended to use the Angular cLI to generate the server bundle. Custom webpack configurations are not supported by the Angular team.
