### ISSUE TITLE
build angularair.com on ng2 + universal

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#255]
This issue is used to track the building of angularair.com on ng2 + universal

**Comment by jeffwhelpley** [comment]
We want to have some open source showcase apps and this will be one of them. While Patrick will take the pre-rendering approach with angular.io, we will use the runtime server rendering approach with angularair.com.

**Comment by gdi2290** [comment]
for angularair.com we probably should stick with pre-rendering too

**Comment by jeffwhelpley** [comment]
No question that from a requirements standpoint it makes sense to make angularair a pre-rendered site, BUT I was thinking that we want to showcase different ways of doing things anyways, so why not take some more risks with angularair.com (since we want to go conservative with angular.io) and instead show off all sorts of stuff. This goes well beyond the scope of the Universal project, but I was thinking that eventually it would be cool to have little experiments on angularair to highlight the tech being discussed on a particular show. Basically we would be able to kill a bunch of birds with one stone:

1. Get a near-term showcase for a production app with real time Universal rendering that we can show off at ng-conf
2. Get early feedback from the community on a "real" implementation. I have a feeling that many early "real" implementations will be private (GetHuman included) so will be harder to get feedback.
3. Eventually good SEO for angularair.com because it will have more than just the schedule and show notes.

That said, it is obviously less work to just do angularair.com and angular.io is the same exact way. Let's discuss on slack this week and come to a decision on this.

**Comment by gdi2290** [comment]
this issue should really live in https://github.com/angularair/site rather than the universal repo

**Comment by jeffwhelpley** [comment]
Yep, closing this.
