### ISSUE TITLE
update express dependency to 5.0.0-beta

### ISSUE THREAD

**Issue by alanpurple** [angular/universal#2551]
# Proposal

#### What is the summary of the proposal?

update express dependency

#### What is the proposal?

update express dependency

#### Is there anything else we should know?

It's clear and obvious, nothing else

**Comment by CaerusKaru** [comment]
We don't create dependencies on non-stable resources. When `express` or any other libraries reach that stage, we will create a PR to update (or likely our automation will open one for us).
