### ISSUE TITLE
How to remove angular universal from Project

### ISSUE THREAD

**Issue by myrok2** [angular/universal#2552]
To make seo works i added angular universal to my project. Somehow i was unable to run the project. So i decided to back to normal client side rendering. When i added angular universal it changed some of my files that is below.
 ```
 C:\AngularJS\MWS_web>ng add @nguniversal/express-engine
Skipping installation: Package already installed
CREATE server.ts (2032 bytes)
UPDATE package.json (3414 bytes)
UPDATE tsconfig.server.json (477 bytes)
UPDATE src/app/app-routing.module.ts (1350 bytes)
UPDATE src/app/app.module.ts (3201 bytes)
v Packages installed successfully

```

### I reverted every file back to normal like previous But when i start the server, it just show a blank page. I am in so trouble with my production project i cant even run it. 
Please help me anyone.

**Comment by CaerusKaru** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag angular-cli.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md?rgh-link-date=2022-02-15T17%3A29%3A25Z#-got-a-question-or-problem).
