### ISSUE TITLE
Custom type not taken into account with SSR

### ISSUE THREAD

**Issue by mbagiella** [angular/universal#2557]
# 🐞 Bug report

#### What modules are related to this issue?
- [ ] aspnetcore-engine
- [ X] builders
- [ ] common
- [ ] express-engine
- [ ] hapi-engine

### Is this a regression?
No

### Description
Custom type file in src folder are not taken into account with SSR

## 🔬 Minimal Reproduction

`ng new app`

create new simple type in src e.g CustomType.d.ts

`declare var CustomType:String;`

change environment.ts code by 

`export const environment = {
  production: CustomType
};`

serve
`ng serve` -- No ERROR

Add SSR
`ng add @nguniversal/express-engine`

serve
`npm run dev:ssr`

ERROR :(

## 🔥 Exception or Error

<pre><code>
`/Users/x/app/dist/app/server/main.js:387
    production: CustomType
                ^

ReferenceError: CustomType is not defined`
</code></pre>

## 🌍 Your Environment

<pre><code>
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.4
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.2.4
@angular-devkit/schematics      13.2.4
@angular/cli                    13.2.4
@nguniversal/builders           13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.4
rxjs                            7.5.4
typescript                      4.5.5

</code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
