### ISSUE TITLE
window is not defined ApexCharts 

### ISSUE THREAD

**Issue by tguimmaraess** [angular/universal#2560]
# 🐞 Bug report

Apex charts causing Angular SSR to fail

- [ ] common
- [ ] express-engine

The problem is that when I simply import `NgApexchartsModule`, in my` app.module.ts` file, I get an error when running Angular in SSR mode. "window is not defined". While it might not be a problem directly related to Angular Universal, it might still be related to it somehow. I know that window object doesn't exist in the server but the problem is that I tried the workarounds listed in [](https://github.com/angular/universal/blob/master/docs/gotchas.md) but no success. I am using Angular 13 and everything is working as expected, just the SSR isn't working due to this third party library. So I would like to know what my options are. I tried domino and I tried to create a `app.browser.module.ts` file but I didn't understand how to make `app.module` agnostic and how to call `app-browser.module`.

## 🔬 Minimal Reproduction
There's no much to say. When I remove the module that was cuasing the issue from `app.module`, it worked.

Here's the reproduction: https://github.com/tguimmaraess/ssr-issue-reproduction

I have this in my server.ts file:

```
import 'zone.js/dist/zone-node';
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { createWindow } from 'domino';
import * as domino from 'domino';
import { existsSync, readFileSync } from 'fs';

const template = readFileSync(join(DIST_FOLDER, INDEX_HTML)).toString();
const win: any = domino.createWindow(template);
global['window'] = win;
global['document'] = win.document;

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
```

Didn't give me any errors but didn't work either.

I also tried this:

```
import 'zone.js/dist/zone-node';
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { createWindow } from 'domino';
import * as domino from 'domino';
import { existsSync, readFileSync } from 'fs';

const template = readFileSync(join(DIST_FOLDER, INDEX_HTML)).toString();
const win: any = domino.createWindow(template);
(global as any).window = win;
(global as any).document = win.document;

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
```
But same thing, no errors but the window is not defined error still there. Seeing as it's a third party library I can't use any of the other solutions like isPlatformBrowser or creating a window service. So again, I would like to know what my options in this case, seeing as ApexCharts is not compatible with Angular SSR.

## 🔥 Exception or Error

<pre><code>
ReferenceError: window is not defined
    at Object.40862 (charts/dist/server/main.js:91089:3924)
    at __webpack_require__ (charts/dist/server/main.js:242744:42)
    at Module.46298 (charts/dist/server/main.js:100243:74)
    at __webpack_require__ (charts/dist/server/main.js:242744:42)
    at Module.36747 (charts/dist/server/main.js:98683:111)
    at __webpack_require__ (charts/dist/server/main.js:242744:42)
    at Module.28061 (charts/dist/server/main.js:98791:69)
    at __webpack_require__ (charts/dist/server/main.js:242744:42)
    at Module.81789 (charts/dist/server//main.js:103073:80)
    at __webpack_require__ (charts/dist/server/main.js:242744:42)

A server error has occurred.
node exited with 1 code.

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cdk                    13.2.3
@angular/cli                    13.2.3
@angular/material               13.2.3
@angular/platform-server        13.2.4
@nguniversal/builders           13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.3
rxjs                            7.5.4
typescript                      4.5.5

</code></pre>

**Comment by Santoshah** [comment]
Your problem is you're using SSR .. and in the server window doesn't EXIST ... so you can basically check for which environment you're in (client or server)

Try to use the apex chart in this format. 
```
import { isPlatformBrowser } from '@angular/common';
import { PLATFORM_ID } from "@angular/core";

  isBrowser : boolean;
  constructor(
    @Inject(PLATFORM_ID) private platformId: any
){
    this.isBrowser = isPlatformBrowser(this.platformId);
}

renderChart(){
    const ApexCharts = require('apexcharts');
    this.chart = new ApexCharts(document.querySelector('#video_circle_chart'), this.configOption);
    this.chart.render();
}


ngAfterViewInit(){
  (isPlatformBrowser(this.platformId) ? this.renderChart() : '');
}
```

**Comment by tguimmaraess** [comment]
Thank you but by simply importing the modules in my `app.module.ts` file gives me error. So I wanted a way to import it in a `browser.module`, but if I do it, it doesn't recognise the modules.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
