### ISSUE TITLE
Server bundles are larger compared to browser bundles 

### ISSUE THREAD

**Issue by nagavenkateshK** [angular/universal#2561]
![image](https://user-images.githubusercontent.com/49555160/156151258-b88e1396-03dd-4191-8cb9-2a7b3e608717.png)
![image](https://user-images.githubusercontent.com/49555160/156151348-b0157dbe-c359-40c5-82a0-b437c07d1ad9.png)

Using angular universal 13.0.0
 "@nguniversal/builders": "^13.0.0"

**Comment by alan-agius4** [comment]
This is expected since for server bundles the optimization is less aggressive as bundle size is not as critical as for browser bundles.
