### ISSUE TITLE
URL Segment: ''https:' at ApplyRedirects.noMatchError after server has started both on http (locally) and on https (on Heroku)

### ISSUE THREAD

**Issue by wisnercelucus** [angular/universal#2565]
I am building a new Angular application and as always I prefer to deploy in Prod early to avoid too many complications later. 
The application only has a home page with a few components. I use Angular Material for style and SCSS. it runs very well locally with 'ng serve'. Though, It keeps throwing an error when I try to run it with SSR (nguniversal/express-engine). 

## Error message: ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: ''https:'
Error: Cannot match any routes. URL Segment: ''https:'

The error occurs both with npm run serve:ssr and with npm run dev:ssr, it does not prevent the page to load on Heroku over https but it still give the error though. Locally it does not load the page at all only after I cut the serve.

## 🌍 Environment

<code>
<pre>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.5
Node: 16.14.0
Package Manager: npm 8.3.1
OS: linux x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, router

Package                             Version
-------------------------------------------------------------
@angular-devkit/architect           0.1302.5
@angular-devkit/build-angular       13.2.5
@angular-devkit/core                13.2.5
@angular-devkit/schematics          13.2.5
@angular/cli                        13.2.5
@angular/platform-browser-dynamic   13.2.5
@angular/platform-server            13.2.5
@nguniversal/builders               13.0.2
@nguniversal/express-engine         13.0.2
@schematics/angular                 13.2.5
rxjs                                7.5.4
typescript                          4.5.5

**@nguniversal/express-engine": "^13.0.2"**

</code>
</pre>

**Comment by alan-agius4** [comment]
Without a reproduction it would be hard to help here.

**Comment by wisnercelucus** [comment]
Thank you @alan-agius4.

Here is the repo link so: https://github.com/wisnercelucus/failangularssr

I have recreated the app:

ng new appname

ng add @angular/material
ng add @nguniversal/express-engine

when I run it without my already built components, it worked over npm run dev:ssr

once I have added the components which only have vanilla scss and some materials components it fails over npm run dev:ssr
but it works well with 'ng serve'

**Comment by wisnercelucus** [comment]
> Without a reproduction it would be hard to help here.
> 
> You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to Github and link it here.
> 
> This might be related to your directory structure so it's really important to get an accurate repro to diagnose this.

There may be compatibility breaks between `@nguniversal/express-engine": "^13.0.2" with Angular 13.2.X.`

I have downgraded the whole project to angular-CLI 12, it works!

**Comment by alan-agius4** [comment]
The problem appears to be the `index.html` file

```diff
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Valnum</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <link rel="preconnect" href="https://fonts.gstatic.com">
- <link href="'https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap'" rel="stylesheet">
+ <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <app-root></app-root>
</body>
</html>

```

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by wisnercelucus** [comment]
Thank you @alan-agius4. You are so right. I was progressing with it with angular 12. I'll upgrade it.
