### ISSUE TITLE
Universal and Angular Material Icon ERROR Error: Error retrieving icon :lock! ErrorEvent is not defined

### ISSUE THREAD

**Issue by mikloshumli** [angular/universal#2573]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine
- [x] material

## 🔬 Minimal Reproduction
IconModule constructor I added this.matIconRegistry.addSvgIcon('lock', this.domSanitizer.bypassSecurityTrustResourceUrl('assets/svg-icons/lock.svg'));
and html I use <mat-icon svgIcon="lock"></mat-icon>
Universal dev:ssr (ng run project:serve-ssr) console drop this error

## 🔥 Exception or Error
ERROR Error: Error retrieving icon :lock! ErrorEvent is not defined
 at Object.error main.js
 at SafeSubscriber.webpack_modules.3317.Subscriber._error main.js
 at OperatorSubscriber.webpack_modules.3317.Subscriber._error main.js

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.2.2
Node: 16.13.0
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 13.2.1
... animations, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.2
@angular-devkit/build-angular   13.2.2
@angular-devkit/core            13.2.2
@angular-devkit/schematics      13.2.2
@angular/cli                    13.2.2
@angular/flex-layout            13.0.0-beta.37
@angular/google-maps            13.2.5
@nguniversal/builders           13.0.2
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.2
rxjs                            7.5.2
typescript                      4.5.5

</code></pre>

<pre>
<code>
{
  "name": "project",
  "version": "0.0.6",
  "scripts": {
    "ng": "ng",
    "start": "npm run version && ng serve --open",
    "build": "npm run version && ng build",
    "build:serve": "npm run version && ng build && http-server -p 8080 -c-1 dist/pwa/browser",
    "serve-pwa": "npm run version && ng build && http-server -p 8080 -c-1 dist/pwa",
    "dev:ssr": "npm run version && ng run praktiker-pwa:serve-ssr",
    "build:ssr": "npm run version && ng build && ng run pwa:server:production",
    "serve:ssr": "npm run version && node dist/pwa/server/main.js",
    "prerender": "npm run version && ng run pwa:prerender",
    "test": "npm run version && ng test",
    "lint": "ng lint --fix",
    "prettier": "npx prettier --write .",
    "version": "node gen-version.js $npm_package_version",
    "compodoc:build": "node_modules/.bin/compodoc -p tsconfig.doc.json",
    "compodoc:build-and-serve": "node_modules/.bin/compodoc -p tsconfig.doc.json -s",
    "compodoc:serve": "node_modules/.bin/compodoc -s",
    "prepare": "husky install"
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run prettier:check"
    }
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~13.2.0",
    "@angular/common": "~13.2.0",
    "@angular/compiler": "~13.2.0",
    "@angular/core": "~13.2.0",
    "@angular/flex-layout": "^13.0.0-beta.37",
    "@angular/forms": "~13.2.0",
    "@angular/google-maps": "^13.2.5",
    "@angular/material": "^13.2.1",
    "@angular/platform-browser": "~13.2.0",
    "@angular/platform-browser-dynamic": "~13.2.0",
    "@angular/platform-server": "~13.2.0",
    "@angular/router": "~13.2.0",
    "@angular/service-worker": "~13.2.0",
    "@compodoc/compodoc": "^1.1.19",
    "@ngrx/effects": "^13.0.2",
    "@ngrx/schematics": "^13.0.2",
    "@ngrx/store": "^13.0.2",
    "@nguniversal/express-engine": "^13.0.2",
    "eslint-config-prettier": "^8.4.0",
    "eslint-plugin-prettier": "^4.0.0",
    "express": "^4.15.2",
    "http-proxy-middleware": "^2.0.2",
    "http-server": "^14.1.0",
    "localstorage-polyfill": "^1.0.1",
    "prettier": "^2.5.1",
    "prettier-eslint": "^13.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.2.2",
    "@angular-eslint/builder": "13.1.0",
    "@angular-eslint/eslint-plugin": "13.1.0",
    "@angular-eslint/eslint-plugin-template": "13.1.0",
    "@angular-eslint/schematics": "13.1.0",
    "@angular-eslint/template-parser": "13.1.0",
    "@angular/cli": "~13.2.2",
    "@angular/compiler-cli": "~13.2.0",
    "@nguniversal/builders": "^13.0.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "@typescript-eslint/eslint-plugin": "5.11.0",
    "@typescript-eslint/parser": "5.11.0",
    "eslint": "^8.2.0",
    "husky": "^7.0.4",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
}

</code>
</pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
