### ISSUE TITLE
get documentation up on angular.io

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#258]
Work with Ward Bell to get the Universal documentation up on angular.io. I am going to consolidate existing doc tasks to this one. After we get initial iteration of docs up on angular.io, then we can start opening other issues for anything missing.

**Comment by jeffwhelpley** [comment]
To be clear, this task scope is just creating the initial documentation which includes stuff we have already discussed plus an outline for everything else. So it will not be comprehensive. The goal is to get to the point where we know exactly what else needs to be filled in.

**Comment by gdi2290** [comment]
understanding creating context and ensuring the same module references should also be on the list to document
