### ISSUE TITLE
failed install angular universal

### ISSUE THREAD

**Issue by bobwatcherx** [angular/universal#2586]
i have problem with command install like this :
ng add @nguniversal/express-engine

ng --version

Angular CLI: 13.1.4
Node: 16.10.0
Package Manager: npm 7.24.0
OS: linux x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            7.4.0
typescript                      4.5.5

**### erroor message:**
54 error code ERESOLVE
55 error ERESOLVE unable to resolve dependency tree
56 error
57 error While resolving: angular-main@0.0.0
57 error Found: @angular/animations@13.1.3
57 error node_modules/@angular/animations
57 error   @angular/animations@"~13.1.0" from the root project
57 error
57 error Could not resolve dependency:
57 error peer @angular/animations@"13.3.0" from @angular/platform-server@13.3.0
57 error node_modules/@angular/platform-server
57 error   peer @angular/platform-server@"^13.1.0" from @nguniversal/express-engine@13.0.2
57 error   node_modules/@nguniversal/express-engine
57 error     @nguniversal/express-engine@"13.0.2" from the root project
57 error
57 error Fix the upstream dependency conflict, or retry
57 error this command with --force, or --legacy-peer-deps
57 error to accept an incorrect (and potentially broken) dependency resolution.
57 error
57 error See /root/.npm/eresolve-report.txt for a full report.
58 verbose exit 1

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular CLI version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
