### ISSUE TITLE
make preboot work with multiple apps

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#259]
If a server rendered page has multiple root elements (i.e. multiple apps), then preboot won't work. It just works with one app. This is for particular use that mostly involves pre-rendering. To accomplish this, most of the logic will be on the server side preboot library to generate client side preboot code for each root element.

**Comment by JohnGorter** [comment]
Something 4 me to work on?

**Comment by jeffwhelpley** [comment]
That would be awesome. The key is that you can't increase the size of the generated client side preboot.

**Comment by JohnGorter** [comment]
The key is that you can't increase the size of the generated client side
preboot?
You mean that we do not want to generate the same reboot code for all the
toplevel components?


John.

**Comment by jeffwhelpley** [comment]
So, the client side preboot code is generated by the server side preboot library based on the input options. Most of the time the defaults are used. These options determine the size of the resulting client side preboot code since we use browserify (currently) to remove code that we know won't be used. So, my point is that the ability to deal with multiple root elements is a minority use case. We should support it but it would be an option passed into the server side preboot library (or perhaps just something if an array of appRoot elements are passed in). So, my point is that we would need to figure out a way to implement this when the user specifies multiple root components BUT if the user does not then we just need to make sure there is not any unnecessary code generated that is only really used to support the multiple root use case.

How about this: forget what I just said and first think of how you would modify the current preboot code to support multiple appRoot elements (look at how the options are passed in to getBrowserCode()). Then we can discuss how to implement your design in such a way that doesn't adversely affect the generated code size.

**Comment by gdi2290** [comment]
multiple ng2 server rendering works so ling as preboot can take an array for `appRoot`

**Comment by gdi2290** [comment]
closing for https://github.com/angular/universal/compare/9541a9bfa8bd39d9a68135805b496ed8f0526a90...d5e34c165eed243248d2acadac22b88ee901b3a9 open again if preboot doesn't support arrays for `appRoot`

**Comment by yazeedb** [comment]
@gdi2290 Could you point me to any resources indicating how to set up a Universal project with multiple app roots?
