### ISSUE TITLE
Google web cache not loading router outlet components for angular 10 universal app

### ISSUE THREAD

**Issue by lakhanWebol** [angular/universal#2595]
I have this issue with the Angular 10 Universal app. I am not able to view the full webpage when I try to view the web cache of it. If I inspect the page, I only see the header and footer and nothing else inside the body of the router outlet. I also have noticed this one thing, where I could see the page for a few moments, and then it goes away after a split second. This is weird, as I can view the full page source on the actual website but not on the web cache of it. But when I open-source the file of the page that got downloaded in the network tab, I can see the whole HTML content. what could be causing this problem? any suggestion will be really helpful.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
