### ISSUE TITLE
ServerDomRenderer

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#26]
Create a subclass of angular's `DomRenderer` that has special handling for `setElementProperty` and `invokeElementMethod`, so that the state of the UI is completely contained within attributes of elements. With that, serializing the DOM at the end of processing it via angular is just a matter of serializing the DOM nodes. I.e. we can reuse the existing DOM adapters of Angular.

E.g.

`setElementProperty` should translates changes to properties to changes to attributes. E.g.
- set property `value` on an `input` should set the attribute `value` on the element.
- set property `checked` on `input` with a boolean should add/remove the `checked` attribute on the element
- ...

`invokeElementMethod` should also translate methods into changes to attributes. E.g.
- call method `focus` should result in adding the attribute `autofocus` to this element and removing the attribute from the previously focussed one.

Notes:
- please implement this in a way that does not rely on `parse5` but use the `DOM` adapter instead. With this, we can make this work even for Dart...
- when we have a working prototype, please create a PR for the angular/angular repo to move the renderer to there.

**Comment by gdi2290** [comment]
Blocked pending new Renderer that will simplify the API

**Comment by tbosch** [comment]
Updated the comment on what should be done.
