### ISSUE TITLE
spec out universal plugin to angular CLI

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#260]
At a high level we want to smooth over creating a new Universal app and modifying an existing app to become universal through the CLI. The actual requirements for this, though, are a bit ambiguous, though, so this task is for someone to think about and spec out what we would actually be doing here.

**Comment by jeffwhelpley** [comment]
@wesleycho was thinking about taking an initial shot at this.

**Comment by wesleycho** [comment]
Yep, in progress, but been busy the past week - this will definitely take some dedicated time to get an initial document ready.

**Comment by gdi2290** [comment]
@wesleycho any updates?

**Comment by wesleycho** [comment]
Not yet :( . Been a very busy past couple of weeks for me. If I don't have something by the end of next week, better for someone else to spec this out.

**Comment by jeffwhelpley** [comment]
I talked to @Brocco at ng-conf about this and we should start this up again. @wesleycho did you still want to take this one on?

**Comment by wesleycho** [comment]
Oof, another big task...sure, why not! I'll do some research over the next week, figure out an approach, and document it

**Comment by briananderson1222** [comment]
:+1: would love to have this for updating existing angular CLI projects.

**Comment by MarkPieszak** [comment]
It might have to be a separate plugin for the CLI I'm guessing right, since it's more of a server-side thing. I imagine we'd really only be able to cater to NodeJS as well (since it's just a bunch of package.json dependencies & a server.ts file)

**Comment by wesleycho** [comment]
There are people working on this I believe currently, it's currently being prototyped in another repository.

**Comment by jeffwhelpley** [comment]
Yes, Wesley is right. @devCrossNet is working on this with me now. It is going to take some time, but we the CLI should make it much easier to use Universal.

**Comment by gdi2290** [comment]
obsolete, waiting for cli

**Comment by jaumard** [comment]
Any news on this ? Having universal integrate with CLI will be awesome!

**Comment by devCrossNet** [comment]
Yes, we're working hard on it and hope to get it into the CLI RC :-)

**Comment by jaumard** [comment]
@devCrossNet is there an issue or something where we can follow the status of this ? :D thanks for your great work !

**Comment by devCrossNet** [comment]
@jaumard here is the PR: https://github.com/angular/angular-cli/pull/2318
