### ISSUE TITLE
prerender: An unhandled exception occurred: Could not find the main bundle: <PATH>/server/main.js

### ISSUE THREAD

**Issue by sanjay51** [angular/universal#2602]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [x] common
- [x] express-engine

### Is this a regression?
No / Not sure

### Description
When I run `npm run prerender`, I get this error:

```
An unhandled exception occurred: Could not find the main bundle: /Users/.../dist/myproject/server/main.js
See "/private/var/folders/4x/q8_vdsrd4wzc7y6n3yfkl6gw0000gn/T/ng-SkPjd6/angular-errors.log" for further details.
```

I found that other people also had the same issue, but didn't provide a resolution: https://github.com/angular/universal/issues/2159

## 🔬 Minimal Reproduction

`npm run prerender`

## 🔥 Exception or Error

```
An unhandled exception occurred: Could not find the main bundle: /Users/.../dist/myproject/server/main.js
See "/private/var/folders/4x/q8_vdsrd4wzc7y6n3yfkl6gw0000gn/T/ng-SkPjd6/angular-errors.log" for further details.
```

## 🌍 Your Environment

<pre><code>
Node.js version v17.8.0 detected.
Odd numbered Node.js versions will not enter LTS status and should not be used for production. For more information, please see https://nodejs.org/en/about/releases/.

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.2
Node: 17.8.0 (Unsupported)
Package Manager: npm 8.5.5
OS: darwin x64

Angular: 13.3.2
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.2
@angular-devkit/build-angular   13.3.2
@angular-devkit/core            13.3.2
@angular-devkit/schematics      13.3.2
@angular/cdk                    12.2.13
@angular/fire                   6.1.5
@angular/material               12.2.13
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             13.3.2
rxjs                            6.6.7
typescript                      4.4.4
</code></pre>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by sanjay51** [comment]
Thanks @alan-agius4 . I unfortunately cannot repro it in a new app, especially as my application is quite large. Is it possible that I can see some detailed/verbose logs somewhere to figure it out? Thanks.

**Comment by sanjay51** [comment]
Turns out it's caused by window:resize event capture:

```
@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
  host: {
    '(window:resize)': 'onResize()'
  }
})
...
```

Not sure how to fix that though (other than removing it)

**Comment by sanjay51** [comment]
Still can't figure out why ` An unhandled exception occurred` occurs. I wonder if there is a way to get more logs, or debug the application?. Standard node debug doesn't get me anywhere.

**Comment by alan-agius4** [comment]
The fact that the main server bundle is not being generated it means that something went terrible wrong.  Does `ng run <project>:server` generate the bundle successfully?

Still can't figure out why An unhandled exception occurred occurs. I wonder if there is a way to get more logs, or debug the application?.

You can debug this like any other Node application using VsCode or Chrome DevTools.

**Comment by sanjay51** [comment]
> Does ng run <project>:server generate the bundle successfully?
No, same issue. ng serve works though.

> You can debug this like any other Node application using VsCode or Chrome DevTools.
These don't work as the bundle generation itself fails. Also tried ndb but couldn't find any trace of the exception. The reason is that the main server bundle is not generated, silently. When it tries to render, it's expecting the bundle and fails. Because the root cause and exception occur at different places, it's hard to debug.

There is some good news though - I downgraded to angular 12 and the issue is resolved for me.

**Comment by kaname-png** [comment]
Same problem:
![image](https://user-images.githubusercontent.com/56084970/165602021-7638d8e1-cdf6-4fd7-9cef-3ef7f21387ed.png)

**Comment by ysongur** [comment]
@sanjay51, @kaname-png ....shot in the dark here:  In my `angular.json` I had both my `prerender.configuration.production.outputHashing` and `server.configurations.production.outputHashing` set to "all".  I resolved the issue by changing `server.configurations.production.outputHashing` to "media"

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
