### ISSUE TITLE
Angular Universal/SSR

### ISSUE THREAD

**Issue by rajeevdhi** [angular/universal#2603]
Hi, 

I am working with angular 12 I have integrated angular SSR in project but npm run dev:ssr command working properly but while I use npm run build:ssr than http request not working.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
