### ISSUE TITLE
Error: Uncaught (in promise): Error: Cannot match any routes. for several .js.map files

### ISSUE THREAD

**Issue by victorbadila** [angular/universal#2604]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

No

### Description

I upgraded a big project to have ssr and the app loads properly in the browser, but on the server there are a lot of console errors about unmatched routes. All of them have to do with `.js.map` files it seems. Like `input.js.map`, `clipboard.js.map`, `ngrx-store-localstorage.js.map` and other .map files from the libraries used in the project. I thought at first it was an express-engine related error that it can't match requests for those lib files, but I added `server.use((err, req, res, next) => { console.error('err :)'); });` to the server and it is never called, furthermore the text in the error is very "angular" like.

## 🔬 Minimal Reproduction

The project is too big and tight together to extract and reproduce with any similar results. I tried on new projects and didn't seem to get the same result.

## 🔥 Exception or Error

<pre><code>
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'clipboard.js.map'
Error: Cannot match any routes. URL Segment: 'clipboard.js.map'
    at router_ApplyRedirects.noMatchError
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.14
Node: 14.17.3
OS: win32 x64

Angular: 11.2.14
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.14
@angular-devkit/build-angular   0.1102.14
@angular-devkit/core            11.2.14
@angular-devkit/schematics      11.2.14
@angular/cdk                    10.2.7
@angular/fire                   6.1.5
@angular/material               10.2.7
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.0.1
@schematics/update              0.1102.14
rxjs                            6.6.7
typescript                      4.0.7

</code></pre>

**Comment by alan-agius4** [comment]
This typically indicates some misconfiguration in the server routing unfortunately without at the very minimal the server.ts file we will be unable to look into this any further.

**Comment by victorbadila** [comment]
I left the `server.ts` just as it was when it was generated:

```
import 'zone.js/dist/zone-node';

import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';

import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/SkinBidFE/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  // Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
  server.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
  }));

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
  });

  return server;
}

function run(): void {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = mainModule && mainModule.filename || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
