### ISSUE TITLE
Error when installing @nguniversal/express-engine "SchematicsAngularUniversalApp" schema is using the keyword "id" which its support is deprecated.

### ISSUE THREAD

**Issue by victorbadila** [angular/universal#2605]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

No

### Description

I tried adding ssr to a project I recently migrated from angular 11 to 12, it fails on install

## 🔬 Minimal Reproduction

This is what I did

```
ng add @nguniversal/express-engine

i Using package manager: npm
√ Found compatible package version: @nguniversal/express-engine@12.1.3.
√ Package information loaded.

The package @nguniversal/express-engine@12.1.3 will be installed and executed.
Would you like to proceed? Yes
```

It installed the package, but then it tried to automatically apply some changes and yielded the following error. No file were changed, meaning it tried to modify angular.json and failed.

## 🔥 Exception or Error

<pre><code>
"SchematicsAngularUniversalApp" schema is using the keyword "id" which its support is deprecated. Use "$id" for schema ID.
Schematic input does not validate against the Schema: {"project":"MyApp","appId":"serverApp","main":"main.server.ts","appDir":"app","rootModuleFileName":"app.server.module.ts","rootModuleClassName":"AppServerModule","skipInstall":true}
Errors:

  Data path "" must have required property 'clientProject'.
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 12.2.17
Node: 14.17.3
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.17
@angular-devkit/build-angular   12.2.17
@angular-devkit/core            12.2.17
@angular-devkit/schematics      12.2.17
@angular/cdk                    12.2.13
@angular/cli                    12.2.17
@angular/fire                   6.1.5
@angular/material               12.2.13
@nguniversal/express-engine     12.1.3
@schematics/angular             11.0.1
rxjs                            6.6.7
typescript                      4.3.5

Note: keep in mind I just upgraded from angular 11, in case it's relevant

</code></pre>

**Comment by alan-agius4** [comment]
Hi @victorbadila,

Unfortunately, I am unable to replicate the described behaviour

```
npx @angular/cli@12 new twelve-project
? Would you like to add Angular routing? Yes
? Which stylesheet format would you like to use? SCSS   [ https://sass-lang.com/documentation/syntax#scss                ]
CREATE twelve-project/README.md (1060 bytes)
CREATE twelve-project/.editorconfig (274 bytes)
CREATE twelve-project/.gitignore (604 bytes)
CREATE twelve-project/angular.json (3255 bytes)
CREATE twelve-project/package.json (1078 bytes)
CREATE twelve-project/tsconfig.json (783 bytes)
CREATE twelve-project/.browserslistrc (703 bytes)
CREATE twelve-project/karma.conf.js (1431 bytes)
CREATE twelve-project/tsconfig.app.json (287 bytes)
CREATE twelve-project/tsconfig.spec.json (333 bytes)
CREATE twelve-project/src/favicon.ico (948 bytes)
CREATE twelve-project/src/index.html (299 bytes)
CREATE twelve-project/src/main.ts (372 bytes)
CREATE twelve-project/src/polyfills.ts (2820 bytes)
CREATE twelve-project/src/styles.scss (80 bytes)
CREATE twelve-project/src/test.ts (788 bytes)
CREATE twelve-project/src/assets/.gitkeep (0 bytes)
CREATE twelve-project/src/environments/environment.prod.ts (51 bytes)
CREATE twelve-project/src/environments/environment.ts (658 bytes)
CREATE twelve-project/src/app/app-routing.module.ts (245 bytes)
CREATE twelve-project/src/app/app.module.ts (393 bytes)
CREATE twelve-project/src/app/app.component.scss (0 bytes)
CREATE twelve-project/src/app/app.component.html (24617 bytes)
CREATE twelve-project/src/app/app.component.spec.ts (1097 bytes)
CREATE twelve-project/src/app/app.component.ts (219 bytes)
✔ Packages installed successfully.
    Successfully initialized git.
➜  cli-reproductions cd twelve-project
➜  twelve-project git:(master) ng add @nguniversal/express-engine
ℹ Using package manager: npm
✔ Found compatible package version: @nguniversal/express-engine@12.1.3.
✔ Package information loaded.

The package @nguniversal/express-engine@12.1.3 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.
CREATE src/main.server.ts (698 bytes)
CREATE src/app/app.server.module.ts (318 bytes)
CREATE tsconfig.server.json (396 bytes)
CREATE server.ts (2043 bytes)
UPDATE package.json (1488 bytes)
UPDATE angular.json (5270 bytes)
UPDATE src/main.ts (531 bytes)
UPDATE src/app/app.module.ts (438 bytes)
UPDATE src/app/app-routing.module.ts (283 bytes)
✔ Packages installed successfully.
```

**Comment by victorbadila** [comment]
Hi @alan-agius4 , it works well for me on new projects too, but as mentioned this has been upgraded from angular 11 to 12. At any rate deciphering the error message could help, I take it it's something related to `angular.json`, but I can't tell where or how it fails, the error lacks details. Maybe if there was a more verbose way or adding express engine I could get to the bottom of it.

**Comment by alan-agius4** [comment]
So the problem is that you have a dependency on `@schematics/angular` version `11.0.1`. Can you please run `npm ls @schematics/angular`

**Comment by victorbadila** [comment]
Sure, here's the result:
```
npm ls @schematics/angular
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
my-app@0.0.0 D:\Projects\MyApp
+-- @angular/cli@12.2.17
| `-- @schematics/angular@12.2.17 
`-- @schematics/angular@11.0.1 
```

**Comment by alan-agius4** [comment]
It looks like the problem is that your project directly depends on `@schematics/angular`.

Unless you are developing your own schematics this is not needed.

**Comment by victorbadila** [comment]
Thanks, I updated @schematics/angular to 12 and now the command works well.

**Comment by alan-agius4** [comment]
Unless you are developing schematics, that dependency should be removed from your project.

**Comment by victorbadila** [comment]
There are some custom schematics being used apparently and it was added related to that commit
