### ISSUE TITLE
Have a build step for the server part that doesn't include starting the server

### ISSUE THREAD

**Issue by victorbadila** [angular/universal#2614]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [x] builders
- [ ] common
- [x] express-engine

### Description

When adding universal to my angular projects I get the folllowing new npm commands in package.json that is relevant for building:
```
"build:ssr": "ng build --prod && ng run testtt:server:production",
```
The `ng build` command only compiles the "frontend" part of the project, the server files are compiled in the `ng run testtt:server:production` and after that the server starts up. I need to be able to define a command where the server is built, but not started. Maybe there is one, but I have had no luck of finding the solution. This is especially important in the case where I build the whole thing as a docker image and I need the build commands separate from running the ssr server, which would be just `node dist/testtt/server/main.js`

### Describe the solution you'd like

A separate command for building the server, if there isn't already one.

### Describe alternatives you've considered

The workaround I do now is build and serve the content locally, stop the server, this ensures that the server build it up to date, then run my dockerfile which builds the "frontend" part with `ng build` and has the ready command `CMD ['node', './dist/testtt/server/main.js']`. I build images locally for different environments and because of having to start/stop the app I can't properly automate it.

**Comment by devglrd** [comment]
Yes ! It's right

**Comment by alan-agius4** [comment]
`ng run testtt:server:production` will open build the server bundle. (Given that you are using the default settings)
