### ISSUE TITLE
ng add returns error: Cannot read properties of undefined (reading 'kind')

### ISSUE THREAD

**Issue by JohnMeisterWork** [angular/universal#2621]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x ] express-engine

### Is this a regression?

unknown
### Description

 when adding universal/express-engine to app it returns an error.

## 🔬 Minimal Reproduction
create multi project workspace
using angular cli run ""ng add @nguniversal/express-engine --skip-confirmation""

## 🔥 Exception or Error

<pre><code>

Cannot read properties of undefined (reading 'kind')
</code></pre>

## 🌍 Your Environment

<pre><code>

ngular CLI: 13.3.3
Node: 16.13.0
Package Manager: npm 8.7.0
OS: win32 x64

Angular: 13.3.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.3
@angular-devkit/build-angular   13.3.3
@angular-devkit/core            13.3.3
@angular-devkit/schematics      13.3.3
@angular/cli                    13.3.3
@nguniversal/express-engine     13.1.0
@schematics/angular             13.3.3
ng-packagr                      13.3.1
rxjs                            6.6.7
typescript                      4.6.3
</code></pre>

**Comment by JohnMeisterWork** [comment]
Downgrading global  package @angular/cli down to 12.2.17 seemed to get past the typescript error.

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by damienwebdev** [comment]
```bash
damien:frontend$ npx ng add @nguniversal/common
Skipping installation: Package already installed
? Do you want to add built time rendering (pre-rendering)? No
? Do you want to add server-side rendering (SSR)? Yes
Cannot read properties of undefined (reading 'kind')
```

```
npx ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.6
Node: 16.14.2
Package Manager: npm 8.5.0
OS: linux x64

Angular: 13.2.6
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6
@angular-devkit/schematics      13.2.6
@angular/elements               13.3.6
@nguniversal/builders           13.0.2
@nguniversal/common             13.1.1
@nguniversal/express-engine     13.0.2
@schematics/angular             13.2.6
ng-packagr                      13.2.1
```

@alan-agius4 I'll work on a repro if I can't solve this myself, but just re-confirming that this is likely a bug.

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
