### ISSUE TITLE
recreate NodeConnection without BrowserXhr

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#264]
Replace NodeConnection with a Node version that uses `'http'` module
https://github.com/angular/universal/blob/10443e968c3afcff7610ef98f71c2abeb0a29473/modules/universal/server/src/platform/node.ts#L102
and module [angular2-http-node_backend](https://www.npmjs.com/package/angular2-http-node_backend)

see previous see comments here.
https://github.com/angular/universal/issues/176#issuecomment-181146862 

issue assigned to: @svallory

**Comment by gdi2290** [comment]
@svallory wil be taking this one

**Comment by svallory** [comment]
Should we use the package I created or incorporate the package source directly on Universal?

**Comment by gdi2290** [comment]
incorporate the package source directly on Universal would be better

**Comment by gdi2290** [comment]
@svallory any updates?

**Comment by gdi2290** [comment]
this was merged
