### ISSUE TITLE
browser-sync throwing syntax error in ie11

### ISSUE THREAD

**Issue by C-racker** [angular/universal#2640]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

https://github.com/BrowserSync/browser-sync/issues/1845

"@nguniversal/builders": "^12.1.3",

There seems to be a transpilation bug in the browser-sync js files, since there are arrow functions included although the render target of ts is "es5". This results in a syntac error in IE11 of course, since the client file injected does not get transpiled on the way.

## 🔥 Exception or Error

![image](https://user-images.githubusercontent.com/20217449/167350223-933af765-984d-473c-ad83-de65d99e222d.png)

</code></pre>

## 🌍 Your Environment

ie11
</code></pre>

**Comment by alan-agius4** [comment]
IE 11 support is deprecated in version 12 and has been removed in v13.

Unfortunately, since this is not a regression nor a security issue this doesn’t warrant an LTS fix.

https://angular.io/guide/releases#lts-fixes
