### ISSUE TITLE
Service destroyed and created every session although it is Singleton. 

### ISSUE THREAD

**Issue by robert589** [angular/universal#2659]
# Question
Right now I am trying to implement a Redis Service., However, I have many connected clients to Redis, Because for each session, this service is always called and destroyed. How could I make this service always up even though it is a different session?

    import { isPlatformServer } from '@angular/common';
    import { Inject, Injectable, NgZone, OnDestroy, PLATFORM_ID } from '@angular/core';
    import Redis from 'ioredis';
    import { Observable, from } from 'rxjs';
    import { REDIS_HOSTNAME } from '../app.services';
    
    
    @Injectable({
      providedIn : 'root'
    })
    export class RedisService implements OnDestroy {
    
    redisClient : Redis;
  
    constructor(@Inject(PLATFORM_ID) private platformId: Object) {
      if(isPlatformServer(platformId) && this.redisClient == null) {
        console.log("Setup Redis");
        this.redisClient = new Redis(REDIS_HOSTNAME);
      }
    }
  
    get(key: string) : Observable<any> {
        return from(this.redisClient.get(key));
    }
  
    set(key: string, value: string, timeoutInSeconds: number)  {
      return this.redisClient.set(key, value, 'EX', timeoutInSeconds);
    }
  
    ngOnDestroy(): void {
      console.log("Destroy on ServeR: " + isPlatformServer(this.platformId));
      if(isPlatformServer(this.platformId)) {
        this.redisClient.disconnect();
        this.redisClient = null;
      }
    }
  }

Here is the logs if i keep refreshing my page: 
    Setup Redis
    
    Destroy on ServeR: true
    
    Setup Redis
    
    Destroy on ServeR: true
    
    Setup Redis
    
    Destroy on ServeR: true

I only expect 1 "Setup Redis" for the entire lifecycle of the angular server.

**Comment by alan-agius4** [comment]
This is working as intended since the application is re-bootstrapped for every request.
