### ISSUE TITLE
Angular 13:  Angular universal fails to serve

### ISSUE THREAD

**Issue by gabboman** [angular/universal#2671]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

In theory it was fixed in a previous version, as stated in [this other issue](https://github.com/angular/angular-cli/issues/21735)

### Description

When building a SSR application, and serving the SSR application an error is logged during the process and the server dies.

## 🔬 Minimal Reproduction

Download [this repo](https://github.com/gabboman/wafrn) and use the branch develop.

Then do the command
<pre><code>
git checkout develop
npm install
npm run dev:ssr 
</pre></code>
## 🔥 Exception or Error

<pre><code>

const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf( /*#__PURE__*/_wrapAsyncGenerator(function* () {})).prototype);
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.7
Node: 16.15.0
Package Manager: npm 8.5.5
OS: darwin arm64

Angular: 13.3.10
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cdk                    13.3.8
@angular/cli                    13.3.7
@angular/youtube-player         13.3.8
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.3.7
rxjs                            7.5.5
typescript                      4.6.4
  
</code></pre>

**Anything else relevant?**

I tried removing "strange" libraries like dompurify and it would still happend.

**Comment by hiepxanh** [comment]
![image](https://user-images.githubusercontent.com/16970990/170911373-a303a7dc-9bbd-47ef-b40a-641613dc461b.png)

your package.json in develop branch not exist that command, and anything relevant to angular ssr

**Comment by gabboman** [comment]
@hiepxanh sorry, it's updated now [https://github.com/gabboman/wafrn/blob/develop/package.json](https://github.com/gabboman/wafrn/blob/develop/package.json)

**Comment by alan-agius4** [comment]
@gabboman, I tried to take a look at this but I am getting a totally different error message

```
const AsyncIteratorPrototype = Object.getPrototypeOf(Object.getPrototypeOf( /*#__PURE__*/_wrapAsyncGenerator(function* () {})).prototype);
                                      ^

TypeError: Cannot convert undefined or null to object
    at Function.getPrototypeOf (<anonymous>)
```

**Comment by gabboman** [comment]
yeah I also got that one. wait  i also copied the wrong error message? @alan-agius4 well goddammit I'm sorry

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. I am unable to replicate using the reproduction provided. 

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
