### ISSUE TITLE
installation failed for angular v14.0.0

### ISSUE THREAD

**Issue by qx-juilliard** [angular/universal#2682]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: @angular/cli@13

### Description

 A clear and concise description of the problem...

I have initialized a brand new project using @angular/cli, the latest version, giving me the following package.json:

```json
{
  "name": "app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^14.0.0",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.0.0",
    "@angular/forms": "^14.0.0",
    "@angular/platform-browser": "^14.0.0",
    "@angular/platform-browser-dynamic": "^14.0.0",
    "@angular/router": "^14.0.0",
    "@nguniversal/express-engine": "14.0.0",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.0.0",
    "@angular/cli": "~14.0.0",
    "@angular/compiler-cli": "^14.0.0",
    "@types/jasmine": "~4.0.0",
    "jasmine-core": "~4.1.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.7.2"
  }
}
```

Then running `ng add @nguniversal/express-engine` fails immediately, producing the following log:

```bash
$ yarn run ng add @nguniversal/express-engine
yarn run v1.22.18
warning ../package.json: No license field
$ ng add @nguniversal/express-engine
ℹ Using package manager: yarn
✔ Found compatible package version: @nguniversal/express-engine@14.0.0.
✔ Package information loaded.

The package @nguniversal/express-engine@14.0.0 will be installed and executed.
Would you like to proceed? Yes
✔ Packages successfully installed.
Package dependency "@nguniversal/express-engine" already exists with a different specifier.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## 🔬 Minimal Reproduction

- Using @angular/cli v14.0.0, bootstrap a new project using `ng new`
- run `ng add @nguniversal/express-engine`

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

yarn run v1.22.18
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 14.0.0
Node: 16.15.0
Package Manager: yarn 1.22.18 
OS: linux x64

Angular: 14.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0
@angular-devkit/build-angular   14.0.0
@angular-devkit/core            14.0.0
@angular-devkit/schematics      14.0.0
@nguniversal/express-engine     14.0.0
@schematics/angular             14.0.0
rxjs                            7.5.5
typescript                      4.7.3
    
Done in 0.59s.
</code></pre>

**Comment by alan-agius4** [comment]
From the package.json supplied it looks like you already have `@nguniversal/express-engine` in your package.json. Kindly remove this and try again.
