### ISSUE TITLE
Error: node_modules/@nguniversal/common/common.d.ts

### ISSUE THREAD

**Issue by yangjunfocus** [angular/universal#2684]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report
![image](https://user-images.githubusercontent.com/23710467/172116169-fc8e8d18-983c-4a7c-9f49-76a218b794e9.png)
I am getting this error while building the application.
#### What modules are related to this issue?

- [ ] builders
- [x] common
- [ ] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/23710467/172116699-a85e1037-06d3-448e-9dba-94c3c8f34e50.png)
<pre><code>

</code></pre>

## 🌍 Your Environment
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cli                    11.2.19
@nguniversal/builders           13.0.2
@nguniversal/common             13.1.1
@nguniversal/express-engine     13.0.2
@schematics/angular             11.2.19
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.1.6

<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Angular version 11 is no longer supported. Please update to a supported version https://angular.io/guide/releases#support-policy-and-schedule
