### ISSUE TITLE
Error retrieving icon

### ISSUE THREAD

**Issue by Zuenda25** [angular/universal#2685]
getting Error retrieving icon mat-icon with local svg file on sever console but icon show on browser.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/40710198/172118315-2ba192ed-a46c-4b1e-8612-bceaef0cd0af.png">

# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [x] common
- [ ] express-engine

### Description
getting Error retrieving icon mat-icon with local svg file on sever console but icon show on browser. I tried to use mat icon from local svg file and load the svg with array of objects

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>ERROR Error: Error retrieving icon :arrow-left! Cannot read properties of undefined (reading 'length') at Object.error</code></pre>

## 🌍 Your Environment

<pre><code>
"dependencies": {
    "@angular/animations": "~12.2.0",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "~12.2.0",
    "@angular/compiler": "~12.2.0",
    "@angular/core": "~12.2.0",
    "@angular/forms": "~12.2.0",
    "@angular/material": "^12.2.13",
    "@angular/platform-browser": "~12.2.0",
    "@angular/platform-browser-dynamic": "~12.2.0",
    "@angular/platform-server": "~12.2.0",
    "@angular/router": "~12.2.0",
    "@angular/service-worker": "~12.2.0",
    "@apollo/client": "^3.0.0",
    "@ngbmodule/material-carousel": "^0.7.2",
    "@nguniversal/express-engine": "^12.1.3",
    "apollo-angular": "^3.0.0",
    "domino": "^2.1.6",
    "express": "^4.15.2",
    "graphql": "^16.3.0",
    "ng-lazyload-image": "^9.1.2",
    "reflect-metadata": "^0.1.13",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "xmlhttprequest": "^1.8.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.2.5",
    "@angular/cli": "~12.2.5",
    "@angular/compiler-cli": "~12.2.0",
    "@nguniversal/builders": "^12.1.3",
    "@tailwindcss/aspect-ratio": "^0.4.0",
    "@tailwindcss/forms": "^0.5.0",
    "@tailwindcss/typography": "^0.5.2",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.8.0",
    "@types/node": "^12.11.1",
    "autoprefixer": "^10.4.4",
    "jasmine-core": "~3.8.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "localstorage-polyfill": "^1.0.1",
    "postcss": "^8.4.12",
    "tailwindcss": "^3.0.23",
    "tailwindcss-children": "^2.1.0",
    "typescript": "~4.3.5"
  }

</code></pre>

**Comment by Zuenda25** [comment]
Anyone can help me?

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

**Comment by hiepxanh** [comment]
@Zuenda25  please, can you setup a example repo here? I can take a look

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
