### ISSUE TITLE
Dynamic routes from database using environment.ts

### ISSUE THREAD

**Issue by RazRes** [angular/universal#2687]
# 🚀 Feature request

#### What modules are relevant for this feature request?

builders

- [ ] builders
- [ ] common
- [ ] express-engine

### Description

Hi, I am trying to prerender some dynamic routes using a `routes.txt` file. The contents of `routes.txt` can be generated using node.js before doing the prerender by calling an API at a specific URL added in the `environment.ts` file like so `node generate-routes.js &&  ng run ngcasino:prerender -c staging`. The problem is that I want to be able to access the URL based on the environment the prerender in running on ("staging", "prod", etc) but my node.js service can't access the environment correctly because the environment files are merged by the `ng` CLI. For example I have an `environment.staging.ts` and a `environment.prod.ts` and in angular.json I do file replacements based on my config of choice. This way Angular knows to use the `staging` environment file or `prod` environment file. But Node.js doesn't know how to get those files based on the config.

I also tried creating the `routes.txt` file in a provider added in AppServerModule using the APP_INITIALIZER token but it seems the prerender script doesn't pick it up. I assume the file is read before it starts doing the prerender.

How can I make my script do those `fileReplacement`s before runing?

### Describe the solution you'd like

 If you have a solution in mind, please describe it.

### Describe alternatives you've considered

 Have you considered any alternative solutions or workarounds?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-ssr`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
