### ISSUE TITLE
3d-party library with Angular Universal

### ISSUE THREAD

**Issue by Y4Rick** [angular/universal#2719]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [x] express-engine

### Description

As usual I declared 3d-part library in file `typings.d.ts`.
```
import * as _moment from 'moment/moment';

declare global {
  const moment: typeof _moment;
}
```
But with `Universal` - every use of `moment` in component throws the error `moment is not defined`

What is the way to import 3d-part library with Angular Universal to male it work ?

## 🔥 Exception or Error

<pre>rejection: ReferenceError: moment is not defined<code></code></pre>

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-universal`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
