### ISSUE TITLE
Create Universal cookies module

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#273]
we should allow users to use cookies both in server/client

**Comment by jeffwhelpley** [comment]
@gdi2290 I just realized something. So, this (and potentially other) services are not global but are request specific. That means on the server side we need a way to get the "context" of the current request. I do this in my current product app with the node.js CLS library, but I think we should be able to do this somehow with zones. Basically, the universal engine for a particular framework will need to set values on the context (in this case the current request cookies) and then anywhere in the code we can pull from that context. Does that make sense?

**Comment by zanettin** [comment]
@jeffwhelpley & @gdi2290 sounds great! with cookies it shouldn't be a problem at all when you catch them from the request headers. do you have a idea how to solve the local storage gap?
and do you have a roadmap about angular universal? we plan to bring out our latest CMS frontend totaly built on ng2. but we do need the server side rendering as well. deadline for us is april 2016. is there a chance to get cookies and http requests working till then? just a shy question :)

**Comment by gdi2290** [comment]
I'm planning on working on the abstract clases (cookie, localStorage,Title, etc) during this week

**Comment by keatz55** [comment]
+1

**Comment by laskoviymishka** [comment]
According to _https://github.com/angular/angular/pull/8898_  current implementation should be replaced in favor to new DOM_Adapror. 
@gdi2290 Should i refactor my PR?

**Comment by martinmcwhorter** [comment]
I have a question.

Should the Headers from the real client browser be passed by the NodeJS app to any HTTP services? 

This seems non trivial as is would require either forcing all users a Http Wrapper -- though this could be mitigated with a Http provider in the main.node.js that provides the wrapped service for Node. 

This would solve the problem of auth tokens in Headers (most, almost all?), but would do nothing for auth tokens that are passed in the message body.

**Comment by laskoviymishka** [comment]
@martinmcwhorter imho cookie should provided by some generic accessor, and each platform should have they own unique accessor implementation. For nodejs app you way is the right way. 

If you talk about tokens with message body - than you should add more code :). This issue is only about cookies.

**Comment by tinchou** [comment]
Hey, now that we're on the final release we could spend some time on our P0s, right? :)

My app saves a JWT in cookie storage and I'd like the server to use that to prerender the authorize-only sections of my website.

Thanks!

**Comment by jeffwhelpley** [comment]
@tinchou check out this as a short term workaround:

https://github.com/angular/universal/blob/master/DOCUMENTATION.md#servercontext

**Comment by tinchou** [comment]
Looks good! I'll use this for now and wait for Universal to implement it.

Question: if it's so simple why is it not implemented yet?

**Comment by MarkPieszak** [comment]
You know how it is, nothing is ever as easy as it seems :)

Plus there's been so many Core changes, think the priority has been to just try and keep up to date & evolve with it. Guessing now we'll be able to focus on improving every aspect of Universal... performance, docs, APIs, new things, etc.

**Comment by tinchou** [comment]
Awesome!

And I'm glad your answer is not "because there's this quirk that will make
you pull your hair out" :)

**Comment by kuldeepkeshwar** [comment]
@tinchou 
example for implementing cookie 

https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.node.ts
https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.browser.ts
https://github.com/kuldeepkeshwar/universal-starter/tree/master/src/common/utils

**Comment by tinchou** [comment]
I made it work, but not without a lot of work. @SteveSandersonMS you may want to read since you opened https://github.com/aspnet/JavaScriptServices/issues/130.

@kuldeepkeshwar your solution was really helpful, and I managed to make it work with ASP.NET Core :). I had to remove all calls to Angular internal APIs (e.g. `isBlank`, `isPresent`) since that broke my client code, but it was pretty straightforward.

I saw you depend on the `res` and `req` objects passed by Express [as shown here](https://github.com/angular/universal/blob/7dad715bfacd0110352ff34d4fd43368ce4bedd2/DOCUMENTATION.md), but we don't have that in ASP.NET Core.

As seen here in this issue, https://github.com/aspnet/JavaScriptServices/issues/130, we can get the cookies object by passing it through `asp-prerender-data` and then in `boot-server.ts` doing:

```ts
properties: {
        // ....
        cookies: params.data.cookies,
        // ....
}
```

And in `cookie-node.ts` filling the cache:

```ts
for (let c of Zone.current.get("cookies")) {
    this._cache[c.key] = c.value; // Cookies from .NET are {key:string, value:string}
}
```

But that only gives us a read-only view of the cookies (which may be enough for most cases, including mine, I'm just pointing it out).

Let me know if I can help in any way to get this working seamlessly!

**Comment by jeffwhelpley** [comment]
Cool. Just note that we will make this easier. We have a couple high priority bugs we are working on now, but do have a ToDo for making it easier to pass server request values to Angular (i.e. so you can use DI instead of Zone to get the value).

**Comment by canda** [comment]
@kuldeepkeshwar would you please point out which commit was that code present in?
since those files were deleted
so we can still take a look

**Comment by kuldeepkeshwar** [comment]
@canda you can check `lazy-route` branch

**Comment by gdi2290** [comment]
won't be supported officially 
https://github.com/angular/angular/issues/13822
