### ISSUE TITLE
ng add @nguniversal/express-engine failed to angular 13.1.1

### ISSUE THREAD

**Issue by haagsma** [angular/universal#2740]
# 🐞 Bug report

#### What modules are related to this issue?

- [ x] animations
- [ ] builders
- [ ] common
- [ ] express-engine

### Is this a regression?
no

### Description
when i use the command "ng add @nguniversal/express-engine" i got error conflict dependency

## 🔬 Minimal Reproduction
start a project with angular 13.1.1
run ng add @nguniversal/express-engine

## 🔥 Exception or Error

<pre><code>

ℹ Using package manager: npm
✔ Found compatible package version: @nguniversal/express-engine@13.0.2.
✔ Package information loaded.

The package @nguniversal/express-engine@13.0.2 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: xxxx@0.0.0
npm ERR! Found: @angular/animations@13.1.3
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.1.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"13.3.11" from @angular/platform-server@13.3.11
npm ERR! node_modules/@angular/platform-server
npm ERR!   peer @angular/platform-server@"^13.1.0" from @nguniversal/express-engine@13.0.2
npm ERR!   node_modules/@nguniversal/express-engine
npm ERR!     @nguniversal/express-engine@"13.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.2
Node: 16.13.2
Package Manager: npm 8.1.2
OS: linux x64

Angular: 13.1.1
... animations, common, compiler, compiler-cli, core, elements
... forms, localize, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.2.4
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cdk                    13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4

</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
