### ISSUE TITLE
SSR development execution time is very high

### ISSUE THREAD

**Issue by shanmugapriyak1788** [angular/universal#2748]
<--
Please follow the below issue template. Issues not following the issue template will be closed.
Please provide _as much detail as possible_ in as minimal a reproduction as possible. This means no/only one third-party
libraries, no application-specific code, etc. Essentially, we're looking for an `ng new` project with maybe one
additional file/change. If this is not possible, please look deeper into your issue or post it to StackOverflow
for support. This is a bug/feature tracker, meaning that something is actively _missing or broken_ in Angular Universal.
Anything else does not belong on this forum.

For very common issues when using Angular Universal, please see [this doc](docs/gotchas.md). This includes
issues for `window is not defined` and other hiccups when adopting Angular Universal for the first time.
-->

# 🐞 Bug report

#### What modules are related to this issue?

- [X] builders
- [X] express-engine

### Is this a regression?

No
 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
When we used the last version of Code we had no problem with the development execution time. Latest Angular 14 is taking long time.
We almost spent a minimum of 10 minutes after running the  npm I

## 🔬 Minimal Reproduction
 1. npm I 
 2. npm run dev:ssr

## 🔥 Exception or Error
We see lot of exceptions for node modules regarding scss
## 🌍 Your Environment

<pre><code>

Angular CLI: 14.0.6
Node: 16.13.1
Package Manager: npm 8.1.2 
OS: darwin x64

Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@angular/cdk                    14.0.5
@angular/material               14.0.5
@nguniversal/builders           14.0.3
@nguniversal/express-engine     14.0.3
@schematics/angular             14.0.6
rxjs                            7.5.6
typescript                      4.7.4

</code></pre>

**Comment by alan-agius4** [comment]
Closing due to lack of information.
