### ISSUE TITLE
Data path "" should NOT have additional properties(clientProject).

### ISSUE THREAD

**Issue by PiyushAgrawal1243** [angular/universal#2751]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

After running this command i am getting this error.

ng add @nguniversal/express-engine.

I have gone through StackOverflow and I find out this.

https://stackoverflow.com/questions/62269357/angular-8-error-while-adding-nguniversal-express-engine-to-project-schema

### Please provide the exception or error you saw

```true
Schematic input does not validate against the Schema: {"clientProject":"frontend-app","appId":"serverApp","main":"main.server.ts","serverFileName":"server.ts","serverPort":4000,"tsconfigFileName":"tsconfig.server","appDir":"app","rootModuleFileName":"app.server.module.ts","rootModuleClassName":"AppServerModule","skipInstall":true,"project":"frontend-app"}
Errors:

  Data path "" should NOT have additional properties(clientProject).
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.19
Node: 14.18.3
OS: linux x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      11.2.19
@angular/cdk                    11.2.13
@angular/cli                    11.2.19
@angular/material               11.2.13
@schematics/angular             12.2.17
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.0.8
```

### Anything else?

Here is my package.json

"dependencies": {
    "@angular-material-components/datetime-picker": "^6.0.2",
    "@angular-material-components/moment-adapter": "^6.0.0",
    "@angular/animations": "~11.2.4",
    "@angular/cdk": "~11.2.3",
    "@angular/common": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/localize": "^11.2.4",
    "@angular/material": "^11.2.3",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@material-extended/mde": "^3.0.3",
    "@nguniversal/express-engine": "^11.2.1",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "@swimlane/ngx-datatable": "^19.0.0",
    "angular-google-tag-manager": "1.4.2",
    "angularx-social-login": "^3.5.7",
    "bootstrap": "^4.4.1",
    "hammerjs": "^2.0.8",
    "i": "^0.3.6",
    "ngx-bootstrap": "^5.3.2",
    "ngx-captcha": "^10.0.0",
    "ngx-color-picker": "^8.2.0",
    "ngx-csv-parser": "0.0.7",
    "ngx-google-places-autocomplete": "^2.0.5",
    "ngx-infinite-scroll": "^8.0.0",
    "ngx-quill": "13.2.0",
    "ngx-youtube-player": "^12.0.1",
    "ngxs-reset-plugin": "^1.3.1",
    "quill": "^1.3.6",
    "rxjs": "~6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.3",
    "@angular/cli": "~11.2.3",
    "@angular/compiler": "^11.2.4",
    "@angular/compiler-cli": "^11.2.0",
    "@angular/language-service": "~11.2.4",
    "@ngxs/devtools-plugin": "^3.7.1",
    "@schematics/angular": "^12.2.9",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.14.31",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^2.0.3",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.7"
  }

**Comment by alan-agius4** [comment]
From the output of `ng version` it appears that you have mismatching versions. 

Likely this is caused because you define `@schematics/angular` as a dev dependency.

**Comment by PiyushAgrawal1243** [comment]
I moved it from dev dependency to dependency but still facing the same issue.

Is there any solution or command that can update all the dependencies in the right way?

**Comment by alan-agius4** [comment]
You need to remove this dependency completely from project.

**Comment by PiyushAgrawal1243** [comment]
After removing   @schematics/angular from the project.

package.json

"dependencies": {
    "@angular-material-components/datetime-picker": "^6.0.2",
    "@angular-material-components/moment-adapter": "^6.0.0",
    "@angular/animations": "~11.2.4",
    "@angular/cdk": "~11.2.3",
    "@angular/common": "~11.2.4",
    "@angular/core": "~11.2.4",
    "@angular/forms": "~11.2.4",
    "@angular/localize": "^11.2.4",
    "@angular/material": "^11.2.3",
    "@angular/platform-browser": "~11.2.4",
    "@angular/platform-browser-dynamic": "~11.2.4",
    "@angular/router": "~11.2.4",
    "@material-extended/mde": "^3.0.3",
    "@nguniversal/express-engine": "^11.2.1",
    "@ngx-translate/core": "^13.0.0",
    "@ngx-translate/http-loader": "^6.0.0",
    "@ngxs/storage-plugin": "^3.7.1",
    "@ngxs/store": "^3.7.1",
    "@swimlane/ngx-datatable": "^19.0.0",
    "angular-google-tag-manager": "1.4.2",
    "angularx-social-login": "^3.5.7",
    "bootstrap": "^4.4.1",
    "hammerjs": "^2.0.8",
    "i": "^0.3.6",
    "ngx-bootstrap": "^5.3.2",
    "ngx-captcha": "^10.0.0",
    "ngx-color-picker": "^8.2.0",
    "ngx-csv-parser": "0.0.7",
    "ngx-google-places-autocomplete": "^2.0.5",
    "ngx-infinite-scroll": "^8.0.0",
    "ngx-quill": "13.2.0",
    "ngx-youtube-player": "^12.0.1",
    "ngxs-reset-plugin": "^1.3.1",
    "quill": "^1.3.6",
    "rxjs": "~6.6.6",
    "tslib": "^2.0.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.1102.3",
    "@angular/cli": "~11.2.3",
    "@angular/compiler": "^11.2.4",
    "@angular/compiler-cli": "^11.2.0",
    "@angular/language-service": "~11.2.4",
    "@ngxs/devtools-plugin": "^3.7.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^14.14.31",
    "codelyzer": "^6.0.1",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~6.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "^2.0.3",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.5.4",
    "protractor": "~7.0.0",
    "sonar-scanner": "^3.1.0",
    "ts-node": "~7.0.0",
    "tslint": "~6.1.3",
    "typescript": "~4.0.7"
  }


And the again running ng add @nguniversal/express-engine

new error arises 


An unhandled exception occurred: Cannot find module '@angular-devkit/schematics'
Require stack:
- /home/Desktop/Project/template/project/node_modules/@nguniversal/common/schematics/add/index.js
- /home/Desktop/Project/template/project/node_modules/@nguniversal/express-engine/schematics/install/index.js
See "/tmp/ng-Ukv9ze/angular-errors.log" for further details.


I need to add @angular-devkit/schematics as a dev dependency.

and I added it with ng add --save-dev @@angular-devkit/schematics

and again running ng add @nguniversal/express-engine

getting a new schematic error

An unhandled exception occurred: Cannot find module '@schematics/angular/utility/dependencies'
Require stack:
- /home/knoldus/Project/template/project/node_modules/@nguniversal/common/schematics/add/index.js
- /home/knoldus/Project/template/project/node_modules/@nguniversal/express-engine/schematics/install/index.js
See "/tmp/ng-ANUJhG/angular-errors.log" for further details.

**Comment by alan-agius4** [comment]
Can you try the below

```
ng add @nguniversal/express-engine@11
```

**Comment by PiyushAgrawal1243** [comment]
same again

`piyush-Vostro-3590:~/Desktop/Project/template/project$ ng add @nguniversal/express-engine@11
Your global Angular CLI version (14.0.6) is greater than your local version (11.2.19). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Skipping installation: Package already installed
An unhandled exception occurred: Cannot find module '@schematics/angular/utility/dependencies'
Require stack:
- /home/Desktop/Project/template/project/node_modules/@nguniversal/common/schematics/add/index.js
- /home/Desktop/Project/template/project/node_modules/@nguniversal/express-engine/schematics/install/index.js
See "/tmp/ng-eUIwmh/angular-errors.log" for further details.
piyush-Vostro-3590:~/Desktop/Project/template/project$ `

**Comment by alan-agius4** [comment]
Looks like your node_modules are tained. 

Please remove the current node_modules and do a fresh installation prior to running `ng add`

**Comment by PiyushAgrawal1243** [comment]
After deleting node_module  => run npm install then your command right?

**Comment by PiyushAgrawal1243** [comment]
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.19
Node: 14.18.3       
OS: linux x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.19
@angular-devkit/build-angular   0.1102.19
@angular-devkit/core            11.2.19
@angular-devkit/schematics      14.1.0
@angular/cdk                    11.2.13
@angular/cli                    11.2.19
@angular/material               11.2.13
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.19 (cli-only)
@schematics/update              0.1102.19
rxjs                            6.6.7
typescript                      4.0.8

**Comment by PiyushAgrawal1243** [comment]
Should i use --force?

ng add @nguniversal/express-engine@11 --force

**Comment by PiyushAgrawal1243** [comment]
> Should i use --force?
> 
> ng add @nguniversal/express-engine@11 --force

same error with this

**Comment by alan-agius4** [comment]
From the ng version it appears that you still have mismatching versions.

```
@angular-devkit/schematics 14.1.0
```

Please run the following
```
$ npm uninstall @angular-devkit/schematics
$ rm -rf node_modules package-lock.json 
$ npm i
$ ng add @nguniversal/express-engine@11
```

If the problem persists please provide the output of 
```
$ npm ls @angular-devkit/schematics
```

You don't need to use the `force` options, as that option is used to force overriding existing files.

**Comment by alan-agius4** [comment]
Did the above work?

**Comment by PiyushAgrawal1243** [comment]
Sorry for the late reply, I did not use it. I updated my project to angular 14 as I have a critical timeline for delivery.
