### ISSUE TITLE
[Clover]: Clover server exhibits memory leak as a result of JSDOM

### ISSUE THREAD

**Issue by damienwebdev** [angular/universal#2761]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [x] common
- [ ] express-engine

### Is this a regression?

No.

### Description

See: https://github.com/jsdom/jsdom/issues/3408. I'm cross-posting the issue so that the universal team is aware of the issue.

## 🔬 Minimal Reproduction

Run any clover rendered Angular app as currently documented. You will see a memory leak.

**Comment by alan-agius4** [comment]
Duplicate of https://github.com/angular/universal/issues/2733

Thanks for looking into this. Much appreciated.
