### ISSUE TITLE
[Clover] Use Linkedom over jsdom

### ISSUE THREAD

**Issue by damienwebdev** [angular/universal#2766]
# Proposal

Supposedly, `linkedom` is faster than `jsdom`. We should try it and see what happens, here's a repo.

https://github.com/damienwebdev/angular-linkedom-universal

#### What is the summary of the proposal?

Faster, memory-leak-less SSR.

#### What is the proposal?

Replace `jsdom` with `linkedom`

#### Is there anything else we should know?
No.

#### Current Blockers

I'm adding them as I find them:

- https://github.com/WebReflection/linkedom/issues/151
- Memory Leak caused by  `runtime.js` - https://github.com/damienwebdev/angular-linkedom-universal
- I had to patch `injectableDefOrInjectorDefFactory` because `DefaultUrlSerializer` is not an instance of `Function`

```js
function injectableDefOrInjectorDefFactory(token) {
    // Most tokens will have an injectable def directly on them, which specifies a factory directly.
    const injectableDef = getInjectableDef(token);
    const factory = injectableDef !== null ? injectableDef.factory : getFactoryDef(token);
    if (factory !== null) {
        return factory;
    }
    // InjectionTokens should have an injectable def (ɵprov) and thus should be handled above.
    // If it's missing that, it's an error.
    if (token instanceof InjectionToken) {
        throw new RuntimeError(204 /* INVALID_INJECTION_TOKEN */, ngDevMode && `Token ${stringify(token)} is missing a ɵprov definition.`);
    }
    // Undecorated types can sometimes be created if they have no constructor arguments.
    if (token instanceof Function || typeof token === "function") { <-- patch
        return getUndecoratedInjectableFactory(token);
    }
    // There was no way to resolve a factory for this token.
    throw new RuntimeError(204 /* INVALID_INJECTION_TOKEN */, ngDevMode && 'unreachable');
}
```

**Comment by alan-agius4** [comment]
Linkedom and HappyDom are two projects that I closely follow as these are also valid candidates to replace Domino in `@angular/platform-server`.

That said, Clover is still experimental and before changing it's DOM implementation we should decide it's future, as such let's close this for now.
