### ISSUE TITLE
Prerendering fails when template contains an attribute with colon

### ISSUE THREAD

**Issue by tommueller** [angular/universal#2785]
I am building a page with Angular, which will then be further processed by thymeleaf. All is working well, if I however want to prerender the page and I have any thymeleaf attributes in HTML (like: `th:value="${value}"`), the prerendering fails with:
`ERROR NAMESPACE_ERR: NAMESPACE_ERR (14): the operation is not allowed by Namespaces in XML`

Everything else is working as expected. I can serve the app, build the app (even with SSR), but I cannot prerender it.

**Comment by tommueller** [comment]
I added a repro here: https://github.com/tommueller/colon-bug-repro

**Comment by alan-agius4** [comment]
The index html is expected to be valid HTML. 

As a workaround you can disable critical css inlining although we cannot guarantee that this workarounds will continue to work in future releases.
