### ISSUE TITLE
Is it possible to use Angular Universal with Standalone components only?

### ISSUE THREAD

**Issue by sandrumirceaioan** [angular/universal#2799]
# 🚀 Feature request
Is Angular Universal working only with standalone components (bootstraping without app.module.ts or app.server.module.ts)? It may actually already work, but can't find anywhere an example of how main.server.ts will look like and how we should replace the  app.server.module?

**Comment by alan-agius4** [comment]
This is not yet possible. However this is definitely on our roadmap to support once standalone components APIs are more stable. 

As such closing.
