### ISSUE TITLE
Data path "" should NOT have additional properties(clientProject).

### ISSUE THREAD

**Issue by chechooxd** [angular/universal#2815]
After adding Express Universal

ng add @nguniversal/express-engine.

Got these errors on application dependencies 

Schematic input does not validate against the Schema: {"clientProject":"appArquetipo","appId":"serverApp","main":"main.server.ts","serverFileName":"server.ts","serverPort":4000,"tsconfigFileName":"tsconfig.server","appDir":"app","rootModuleFileName":"app.server.module.ts","rootModuleClassName":"AppServerModule","skipInstall":true,"project":"appArquetipo"}
Errors:

  Data path "" should NOT have additional properties(clientProject).

**ng version**

  _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.2.13
Node: 16.14.0
OS: win32 x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cdk                    12.2.13
@angular/cli                    11.2.13
@angular/fire                   6.1.5
@nguniversal/express-engine     11.2.1
@schematics/angular             13.3.0
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5

**npm ls @angular-devkit/schematics**

app-arquetipo@0.0.0 C:\Fuentes\Link 2.0\Front-End\Branches\TEST_NGUniversal\Fuentes
├─┬ @angular/cli@11.2.13
│ ├── @angular-devkit/schematics@11.2.13
│ ├─┬ @schematics/angular@11.2.13
│ │ └── @angular-devkit/schematics@11.2.13 deduped
│ └─┬ @schematics/update@0.1102.13
│   └── @angular-devkit/schematics@11.2.13 deduped
└─┬ @schematics/angular@13.3.0
  └── @angular-devkit/schematics@13.3.0

**Package.json Dependencies**

  "dependencies": {
    "@angular/animations": "~11.2.10",
    "@angular/cdk": "^12.2.13",
    "@angular/common": "~11.2.10",
    "@angular/compiler": "~11.2.10",
    "@angular/core": "~11.2.10",
    "@angular/fire": "^6.1.5",
    "@angular/forms": "~11.2.10",
    "@angular/platform-browser": "~11.2.10",
    "@angular/platform-browser-dynamic": "~11.2.10",
    "@angular/router": "~11.2.10",
    "@fdograph/rut-utilities": "^1.4.0",
    "@nguniversal/express-engine": "^11.2.1",
    "crypto-js": "^4.1.1",
    "firebase": "^8.10.1",
    "ng9-rut": "^0.1.1",
    "ngx-cookie-service": "^12.0.3",
    "ngx-device-detector": "^2.2.1",
    "postcss": "^8.3.8",
    "primeicons": "^4.1.0",
    "primeng": "^11.2.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.9",
    "@angular/cli": "~11.2.9",
    "@angular/compiler-cli": "~11.2.10",
    "@schematics/angular": "^13.3.0",
    "@types/crypto-js": "^4.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.1.5"
  }

**Comment by alunatam** [comment]
Please guys any info on this issue. We are also facing same problem with the same versions.

**Comment by alan-agius4** [comment]
Angular 11 is no longer supported. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.

**Comment by alunatam** [comment]
@alan-agius4 thanks for the feedback. Do you think is possible to upgrade to 12 or 13 for example? We are trying to limit any possible issues on code after upgrade.
