### ISSUE TITLE
<ng-content> rendering content in the wrong spot

### ISSUE THREAD

**Issue by Simon-Hayden-iteratec** [angular/universal#2825]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [x] common
- [ ] express-engine

### Is this a regression?

Unsure

### Description

We are using a component, which uses `<ng-content>` for content projection. However, we have discovered, that during SSR, sometimes the `<ng-content>`'s content is rendered *outside* the supposed element.

Here the wrapping code:

```html
<!-- rail.component.html -->
<div class="rail" #rail>
  <div class="rail__content" #content [style.scroll-padding-inline.px]="margin" (scroll)="onRailScrolled()">
    <div class="row container" #row>
      <ng-content></ng-content> <!-- <-- This ng-content is faulty -->
      <div class="rail__last-item" [style.width.px]="margin"></div>
    </div>
  </div>
</div>
```

Here is the usage of it:

```ts
<rbcp-rail class="top-pick-rail">
  <rbcp-top-pick-asset
    *ngFor="let product of products"
    [product]="product"
  ></rbcp-top-pick-asset>
</rbcp-rail>
```

But this is how the server renders it:

![image](https://user-images.githubusercontent.com/79910240/190358649-86a03dc2-cbcf-4791-9a18-ae85b7e652b9.png)

- The first `rbcp-top-pick-asset` is rendered at the correct spot
- The second `rbcp-top-pick-asset` is rendered as **sibling of the `div.rail__content` element**
- All other `rbcp-top-pick-asset` components are rendered as **siblings of the `div.rail` element**

After some investigation, we discovered, that changing the HTML template of the `rbcp-top-pick-asset` like so:

```diff
--<button class="top-pick-asset" >
<rbcp-top-pick-card
  (click)="openPreview()"
  [imageUrl]="asset.attributes.imageUrl"
  [imageWidth]="asset.attributes.imageWidth"
  [imageHeight]="asset.attributes.imageHeight"
  [imageSizes]="columns"
  [imageAlt]="asset.relationships.translations?.[0]?.attributes?.title ?? ('Asset ' + asset.attributes.assetId)"
  [videoUrl]="videoUrl"
 >
  <div class="top-pick-asset__description">
    <rbcp-cosmos-text appearance="light" [clamp]="3" size="small" weight="medium">{{ title }}</rbcp-cosmos-text>
    <rbcp-cosmos-text appearance="light" kind="subtle" size="x-small">{{
      asset.attributes.publishedAt | date: 'fullDate'
    }}</rbcp-cosmos-text>
  </div>
  <rbcp-badge class="top-pick-asset__duration" icon="play" kind="cover-up" *ngIf="duration">{{ duration }}</rbcp-badge>
</rbcp-top-pick-card>
--</button>
```

After removing the button, the HTML is rendered correctly:

![image](https://user-images.githubusercontent.com/79910240/190362069-e49b2715-e337-48bb-a831-8a3bdc4172a1.png)

## 🔬 Minimal Reproduction

I have not yet found time to create a minimal repo that shows the same behaviour. If this issue seems like something that is relevant to you, I can try and allocate some company time to it.

## 🌍 Your Environment

Sorry, we're using Nx to manage our monorepo, so `ng version` isn't working.

We are using Angular 14.2.1 though, since we recently updated to hope and fix the issue.

<pre><code>
   Node : 16.14.0
   OS   : linux x64
   npm  : 8.3.1
   
   nx : 14.7.5
   @nrwl/angular : 14.7.5
   @nrwl/cypress : 14.7.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.5
   @nrwl/eslint-plugin-nx : 14.7.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.5
   @nrwl/js : 14.7.5
   @nrwl/linter : 14.7.5
   @nrwl/nest : 14.7.5
   @nrwl/next : Not Found
   @nrwl/node : 14.7.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.5
   @nrwl/web : 14.7.5
   @nrwl/workspace : 14.7.5
   typescript : 4.7.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @auth0/auth0-angular: 1.10.1
         @ngrx/effects: 14.0.2
         @ngrx/entity: 14.0.2
         @ngrx/store: 14.0.2
         @ngrx/store-devtools: 14.0.2
         @ngrx/schematics: 14.0.2
         @nguniversal/builders: 14.2.0
         @nguniversal/express-engine: 14.2.0
         ng-mocks: 14.2.1
</code></pre>

**Comment by alan-agius4** [comment]
Hi @Simon-Hayden-iteratec, thanks for opening this issue. However to investigate this issue further we'd need a runnable reproduction.

A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Closing as no reproduction was provided.
