### ISSUE TITLE
Prerendering fails on node.js 18.9 but succeeds on node 18.8

### ISSUE THREAD

**Issue by tom-b-wright** [angular/universal#2831]
Using latest node image (18.9) on Google cloud build we consistently get this error message for the pre-render command.
- Prerendering [nr] route(s) to /workspace/dist/[xyz]/browser...
Rendering: /[url-path]
✖ Prerendering routes to /workspace/dist/[xyz]/browser failed.
Method Promise.prototype.then called on incompatible receiver [object Object]

Reverting back the node image to 18.8 make the build to succeed.

Since I lost my Sunday to this issue, I thought someone can find this message helpful.

This is a cloudbuild.yaml config file section to specify node image version.
 - name: node:18.8.0
    entrypoint: npm
    args: ['run', 'prerender']

Many thanks for the developers and managers who created and keeps this solution live.

**Comment by alan-agius4** [comment]
Node.js 18 is not yet officially supported, I strongly suggest to use Node.js versions that are officially supported to avoid such issues in the future.

Please see: https://angular.io/guide/setup-local#prerequisites
