### ISSUE TITLE
meta tags not working with lazy loaded module

### ISSUE THREAD

**Issue by Eslam-95** [angular/universal#2833]
# 🐞 Bug report

lazy loaded modules with meta tags

    "@nguniversal/builders": "^12.1.3",
    "@angular/common": "~12.2.0",
    "@nguniversal/express-engine": "^12.1.3",

### Is this a regression?

not sure haven't tried before

### Description

i have an angular 12 app which i turned into universal and added seo though angular meta , the issue here is that the meta working on componenet only , what i mean by that is it's shown in both inspect element and page source but the bug i am facing is the same meta and static data doesn't update or get added no matter what i tried inside a lazy loaded module , note here that i want it to be fully dynamic so i can't just add them in authguard or routing i need them to be added through ts component and what happens that they are shown inside the inspect head tag but not inside the page source , wish someone can help me through is thanks in advance

## 🔥 Exception or Error

expecting my meta tags to show in page source when module is lazy loaded
<pre>
<code>
this.meta.addtag('title": 'home')

</code>
</pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.18
Node: 14.17.5
Package Manager: npm 6.14.14
OS: win32 x64

Angular: 12.2.16
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.18
@angular-devkit/build-angular   12.2.18
@angular-devkit/core            12.2.18
@angular-devkit/schematics      12.2.18
@angular/cdk                    13.3.9
@angular/cli                    12.2.18
@nguniversal/builders           12.1.3
@nguniversal/express-engine     12.1.3
@schematics/angular             12.2.18
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
