### ISSUE TITLE
"this.debug is not a function" on running >>npm run dev:ssr

### ISSUE THREAD

**Issue by bassem-nabil** [angular/universal#2882]
Hello team,

When I run `ng run serve-ssr`, I expect the angular server will run and watch for changes, 
BUT i got this 

## 🔥 Exception / Error

<pre>
this.debug is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! proj-web-client@0.0.0 dev:ssr: `ng run Z2DataDMWebClient:serve-ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the proj-web-client@0.0.0 dev:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
<code>
</code></pre>

## 🌍 Your Environment

<pre>

  "dependencies": {
    "@agm/core": "^3.0.0-beta.0",
    "@amcharts/amcharts4": "^4.10.23",
    "@amcharts/amcharts4-geodata": "^4.1.22",
    "@angular-slider/ngx-slider": "^2.0.3",
    "@angular/animations": "^14.2.8",
    "@angular/cdk": "^13.1.0",
    "@angular/common": "^14.2.8",
    "@angular/compiler": "^14.2.8",
    "@angular/core": "^14.2.8",
    "@angular/forms": "^14.2.8",
    "@angular/localize": "^14.2.8",
    "@angular/platform-browser": "^14.2.8",
    "@angular/platform-browser-dynamic": "^14.2.8",
    "@angular/platform-server": "^14.2.8",
    "@angular/router": "^14.2.8",
    "@ctrl/ngx-codemirror": "^4.0.1",
    "@microsoft/signalr": "^6.0.9",
    "@ng-bootstrap/ng-bootstrap": "13.1.0",
    "@ngrx/data": "^13.0.2",
    "@ngrx/effects": "^13.0.2",
    "@ngrx/entity": "^13.0.2",
    "@ngrx/router-store": "^13.0.2",
    "@ngrx/store": "^13.0.2",
    "@ngrx/store-devtools": "^13.0.2",
    "@nguniversal/express-engine": "^14.2.0",
    "@popperjs/core": "^2.11.6",
    "express": "^4.15.2",
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.7",
    "@angular/cli": "^14.2.7",
    "@angular/compiler-cli": "^14.2.8",
    "@angular/language-service": "^14.2.8",
    "@nguniversal/builders": "^14.2.0",
    "@types/express": "^4.17.0",
    "@types/googlemaps": "3.39.12",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "13.7",
    "tslint": "~6.1.0",
    "typescript": "~4.8.4",
  }
<code>

**Comment by alan-agius4** [comment]
This seems like a bug but we'll need to look at a reproduction to find and fix the problem. Can you setup a minimal repro please?

You can read [here](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.
