### ISSUE TITLE
Prerendering: Allow creating static files other than /index.html

### ISSUE THREAD

**Issue by ayyash** [angular/universal#2884]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-server

### Description

The current behavior of `ng run prerender` is to create routes as folders, and `index.html` inside the folder. That has a very painful result that a lot of people complained about: SEO drop. Because we do not take notice that the URLs now redirect from `/route` to `/route/` as a default behavior in Express, or any hosting. 

### Proposed solution

The static Express rendered can have the following 
```
server.get('*.*', express.static(distFolder, {
  maxAge: '1y',
  extensions: ['htm', 'html']
}));
```
And make the Angular prerender command accept this option to create routes as files with `.html` instead of as folders with `index.html`

### Alternatives considered

Or the least you can do is advice in the documentation, there are ways to handle it in different hostings. But it will go unnoticed if we just use the out of the box commands. I personally took a slight SEO dip. I can survive

**Comment by alan-agius4** [comment]
Hi @ayyash, 

I am unable to replicate this using the generated `server.ts` have you modified the express configuration by any chance?

**Comment by ayyash** [comment]
> Hi @ayyash,
> 
> I am unable to replicate this using the generated `server.ts` have you modified the express configuration by any chance?

Not sure what your question is? replicate the "/" redirect? that is what servers do, when you have nodejs and expressjs and browse to domain/route it will look for domain/route/index.html, if it finds it i will serve it, but after the browser 301 redirects. Is this the part you could not reproduce?

**Comment by alan-agius4** [comment]
Yes, I am unable to replicate the redirect with the default server setup provided ie, using `@nguniversal/express-engine` or `@nguniversal/common-engine`.

That said, I do see that this can be problematic when either using express directly or other hosting provider as to avoid the redirect as in such case additional configuration might be required.

**Comment by ayyash** [comment]
after a lot of digging, I think I understand what your asking :) 
So the `app.get('*.*', express.static(distFolder, {maxAge: '1m'}));` apparently takes care of that loose end. 

I was using `app.use(express.static...)`

But I'll be damned, how is it working with the first option? there is no "." in the route? and why when I use `use` it redirects? I guess this thread is not the place to ask that question
