### ISSUE TITLE
Prerenderer daemon

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#290]
This is lower priority, but it may be beneficial to create a new module for a daemon process that takes in as configuration a set of rules (which includes URLs and frequencies for when to hit those URLs as well as where the resulting HTML gets distributed) and then just runs indefinitely. The reason for this would be that there are huge benefits to keeping certain things in memory. Also, this would save people the time from having to set up their own separate process if they don't need to. The just run this on a tiny EC2 instance on AWS or whatever and then it just works.

**Comment by gdi2290** [comment]
should we call it fastboot :stuck_out_tongue:

**Comment by jeffwhelpley** [comment]
Closing this for now. May bring back up in the future, but lower priority
