### ISSUE TITLE
Support Stand-Alone Components

### ISSUE THREAD

**Issue by GregOnNet** [angular/universal#2906]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] builders
- [ ] common
- [x] express-engine

### Description

It would be nice, if `express-engine` allows rendering Angular Applications on the Server that use Stand-Alone Components

### Describe the solution you'd like

- Idea: Maybe providing a `bootstrapServerApplication`-Method.

### Describe alternatives you've considered

- I did not really consider alternatives
- I am thinking how the API-Surface could look like for setting up SSR-Angular quickly. :-)

**Comment by alan-agius4** [comment]
We are looking into this, but there are some pieces that we need to investigate/design further before pushing it to the public.

**Comment by vnistorica** [comment]
A workaround can be found here: https://github.com/angular/angular/issues/46473 or https://github.com/hiepxanh/universal-test . Basically, the renderModule method is changed to renderApplication in the express-engine library.

**Comment by Judp0m** [comment]
I updated my app to standalone components. It is all working, until realizing that SSR is not yet supported? Now that standalone components are advertised as stable and production ready, this seems urgent.
I will investigate the workaround in the meantime...

**Comment by alfaproject** [comment]
Just noticed the lack of support as well ):

**Comment by mchoraine** [comment]
Here is a way to render standalone components on server-side while waiting for the support of angular universal: https://dev.to/mchoraine/angular-universal-with-standalone-component-206c

**Comment by mchoraine** [comment]
I would be happy to help implement the support in universal if needed

**Comment by alfaproject** [comment]
Thank you @mchoraine, I'll have a look tomorrow and get back to you with my feedback (:

**Comment by Judp0m** [comment]
Any ETA for support of Standalone components + SSR? I tried workarounds, but it is causing some side effects which were not happening before the transition to Standalone Components, e.g.
Zone: <root> ; Task: Promise.then ; Value: ReferenceError: navigator is not defined

**Comment by donaldxdonald** [comment]
Need this~

**Comment by Benzilla** [comment]
Just spent an afternoon converting my entire SSR web app to standalone components only to realise it's not yet supported 😭

**Comment by arturober** [comment]
It's sad because the popularity of Angular keeps decreasing over time (main reason being its complexity). With standalone components we have a chance to make things simpler and more appealing to the community. It's declared a stable API in Angular 15, but months come by and still not a viable option (no SSR, partial support in CLI, lots of libraries not adapting their schematics, ...).
For pepople like us who have embraced this new methodology it's been a pain in the ass for the last 3 months. I love this framework but I'm starting to have doubts... At least, don't encourage people to use this until there's enough ecosystem support...

**Comment by tsenguunchik** [comment]
Still waiting for the support...

**Comment by tomastrajan** [comment]
Any ETA on this?

**Comment by robertIsaac** [comment]
> Just spent an afternoon converting my entire SSR web app to standalone components only to realise it's not yet supported 😭

you can make everything standalone, only keeping the `AppModule` for SSR

**Comment by ciriousjoker** [comment]
@robertIsaac Can you elaborate? How does your `app.module.ts` look? Is it a "fake" app module or does it contain all your declarations?

**Comment by robertIsaac** [comment]
> @robertIsaac Can you elaborate? How does your `app.module.ts` look? Is it a "fake" app module or does it contain all your declarations?

something like that
```
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
    HeaderComponent,
    SidenavComponent,
  ],
  providers: [
    provideHttpClient(),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

**Comment by ciriousjoker** [comment]
@robertIsaac So basically use standalone components for everything and additionally export them in an otherwise unused app.module.ts?

**Comment by robertIsaac** [comment]
> @robertIsaac So basically use standalone components for everything and additionally export them in an otherwise unused app.module.ts?

No you don't need to export them
Just import them
FYI only the components imported in AppComponent needs to be imported

**Comment by donaldxdonald** [comment]
👀  ICYMI #3045
