### ISSUE TITLE
Unknown error with status 0

### ISSUE THREAD

**Issue by mirkovicmiroslav** [angular/universal#2935]
# 🐞 Bug report
#### What modules are related to this issue?
- [ ] builders
- [x] common
- [x] express-engine

### Is this a regression?
Unsure, the first version I have used is Angular 14, then I upgrade to 15 but an issue is still present

### Description
Firstly, I was thinking an issue is related to the CORS but although that I had already configured CORS on backend side, just for sure I've also added following to all response headers on the server in web-config (IIS):
```
access-control-allow-headers: *
access-control-allow-methods: GET,POST,PATCH,PUT,DELETE,OPTIONS
access-control-allow-origin: *
```
Also I've read that it might be related to the bad internet connection (as per Angular official documentation) but that is not an issue here (maybe but just in 1% of 10% of cases).

Those users have tried to change their network connection from `WIFI` to `mobile` but still the same issue appears.

## 🔥 Exception or Error

<pre><code>
"error": "[ProgressEvent]",
"headers": "[ti]",
"message": "Http failure response for https://api.xxxxxx:5000/api/public-web/files: 0 Unknown Error",
"name": "HttpErrorResponse",
"ok": false,
"status": 0,
"statusText": "Unknown Error",
"url": "https://api.xxxxxx:5000/api/public-web/files"
</code></pre>

Since I'm using Sentry for log management, I also have details about error:

<pre><code>
"stacktrace": {
"frames": [
{
"function": "XMLHttpRequest.B",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 21395,
"context_line": "{snip} eduleMicroTask(()=>{throw G})}}}const B=function(R){return N(this,R,!1)},H=function(R){return N(this,R,!0)};function J(R,_){if(!R)return!1;l {snip}",
"in_app": true
},
{
"function": "N",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 21129,
"context_line": "{snip} .type][K?ce:ae]];if(X){const j=[];if(1===X.length){const E=Z(X[0],x,_);E&&j.push(E)}else{const E=X.slice();for(let G=0;G<E.length&&(!_||!0!= {snip}",
"in_app": true
},
{
"function": "Z",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 20836,
"context_line": "{snip} R.callback=E=>x.handleEvent(E),R.originalDelegate=x);try{R.invoke(R,_,[K])}catch(E){X=E}const j=R.options;return j&&\"object\"==typeof j&&j.on {snip}",
"in_app": true
},
{
"function": "m.invokeTask [as invoke]",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 8273,
"context_line": "{snip} ask(T,e,r){T||(T=this),ee++;try{return T.runCount++,T.zone.runTask(T,e,r)}finally{1==ee&&_(),ee--}}get zone(){return this._zone}get state(){ {snip}",
"in_app": true
},
{
"function": "M.runTask",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 2587,
"context_line": "{snip} eriodic&&(e.cancelFn=void 0);try{return this._zoneDelegate.invokeTask(this,e,r,k)}catch(l){if(this._zoneDelegate.handleError(this,l))throw l {snip}",
"in_app": true
},
{
"function": "v.invokeTask",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 7143,
"context_line": "{snip} Task(T,e,r,k){return this._invokeTaskZS?this._invokeTaskZS.onInvokeTask(this._invokeTaskDlgt,this._invokeTaskCurrZone,T,e,r,k):e.callback.ap {snip}",
"in_app": true
},
{
"function": "Object.onInvokeTask",
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 102872,
"context_line": "{snip} arZone:!0},onInvokeTask:(t,r,i,o,s,a)=>{try{return eD(e),t.invokeTask(i,o,s,a)}finally{(e.shouldCoalesceEventChangeDetection&&\"eventTask\"=== {snip}",
"in_app": true
},
{
"function": "v.invokeTask",
"module": "polyfills",
"filename": "/polyfills.35bb4c22a0d64359.js",
"abs_path": "https://www.xxxxxx/polyfills.35bb4c22a0d64359.js",
"lineno": 1,
"colno": 7222,
"context_line": "{snip} nvokeTaskDlgt,this._invokeTaskCurrZone,T,e,r,k):e.callback.apply(r,k)}cancelTask(T,e){let r;if(this._cancelTaskZS)r=this._cancelTaskZS.onCan {snip}",
"in_app": true
},
{
"function": "XMLHttpRequest.r",
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 582520,
"context_line": "{snip} t.apply(this,arguments);const o=i.map(s=>ha(s,n));return e.apply(this,o)}catch(o){throw iz(),_4(s=>{s.addEventProcessor(a=>(n.mechanism&&((0 {snip}",
"in_app": true
},
{
"function": "XMLHttpRequest.u",
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 299250,
"context_line": "{snip} statusText:i.statusText||\"Unknown Error\",url:v||void 0});r.error(E)};let p=!1;const h=g=>{p||(r.next(a()),p=!0);let v={type:qt.DownloadProgr {snip}",
"in_app": true
},
{
"function": "Lr.error",
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 2940,
"context_line": "{snip} ){return A(\"E\",void 0,e)}(n),this):(this.isStopped=!0,this._error(n))}complete(){this.isStopped?le(_,this):(this.isStopped=!0,this._complete {snip}",
"in_app": true
},
{
"function": "Lr._error",
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 8001,
"context_line": "{snip} (l){n.error(l)}}:super._next,this._error=i?function(a){try{i(a)}catch(l){n.error(l)}finally{this.unsubscribe()}}:super._error,this._complete {snip}",
"in_app": true
},
{
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 161588,
"context_line": "{snip} et o,r=null,i=!1;r=n.subscribe(Ge(t,void 0,void 0,s=>{o=ur(e(s,Ii(e)(n))),r?(r.unsubscribe(),r=null,o.subscribe(t)):i=!0})),i&&(r.unsubscrib {snip}",
"in_app": true
},
{
"module": "main",
"filename": "/main.3fef6fd2e31440f3.js",
"abs_path": "https://www.xxxxxx/main.3fef6fd2e31440f3.js",
"lineno": 1,
"colno": 407304,
"context_line": "{snip} is.localStorageService.logout(),location.reload());const s=new Error(i.error.message||i.statusText);return co(s),zs(()=>s)}))}}return e.\\u02 {snip}",
"in_app": true
}
</code></pre>

## 🌍 Your Environment
```
Angular CLI: 15.0.0
Node: 16.13.2
Package Manager: npm 8.17.0
OS: win32 x64

Angular: 15.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      15.0.0
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.0
rxjs                            7.5.6
typescript                      4.8.4
```

</code></pre>

**Comment by alan-agius4** [comment]
This is unlikely that is caused by Angular Universal as such errors typically indicate server misconfiguration.

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
