### ISSUE TITLE
Possibility to render Observable/Promises on server side

### ISSUE THREAD

**Issue by Serehactka** [angular/universal#2948]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [ ] express-engine

### Description

Cannot find any docs or examples how to render observables/promises on server side. As for example, I may like to use fs or request API to get file/source content at server side and appear at resulted html.

### Describe the solution you'd like

It would be nice to have option at Module level (or if it is possible at Component (decorator like thing)) to emit resulted html after all promises and observables being resolved.

### P.S.

If it is already introduces and I'm just missed some parts of specs I would be appreciated to get link to check them out

**Comment by alan-agius4** [comment]
> As for example, I may like to use fs or request API to get file/source content at server side and appear at resulted html.

Since you would use FS how would you render the same content when the application is rendered on the client side?

**Comment by eneajaho** [comment]
Maybe you can use `isPlatformServer` in combination with `TransferState` to read data on server side, store it as json on transfer state and use them on client side by reading inside `isPlatformBrowser` the transferred state.

**Comment by eneajaho** [comment]
```ts
transferState = inject(TransferState);
platformId = inject(PLATFORM_ID);

data = [];

ngOnInit() {
   if (isPlatformServer(this.platformId) {
       let rawdata = fs.readFileSync('student.json');
       let studentData = JSON.parse(rawdata);
       this.transferState.set('data', studentData);
   }
   
   if(isPlatformBrowser(this.platformId)) {
     this.data = this.transferState.get('data');
   }
}

```

**Comment by alan-agius4** [comment]
Closing due to lack of response from the author.
