### ISSUE TITLE
Documentation for redirections

### ISSUE THREAD

**Issue by stephane-tessier** [angular/universal#2957]
# 🚀 Feature request

### Description

I've been trying to do a **simple redirection with HTTP code (301)** for days now, but didn't find a solution yet.  
I've tried a lot of sample codes that I found here and there, but none seems to be working for me.

### Describe the solution you'd like

Could you please help me by **providing some documentation** about how to do that the official way?

### Describe alternatives you've considered

I could do it here : `server.get('*', (req, res) => { // HERE` but this really doesn't seem clean to me and I don't want to go that way. (specially because I need to use load some configuration, use services, call the api...)

**Comment by alan-agius4** [comment]
Redirects are not handled directly by Angular Universal. Typically these are added at a higher level such as in a Load Balancer or NGINIX. However, if you'd like to add these in your application using the Express server `.get` or middleware example: 

```js
app.use((req, res) => {
  if (req.get('Host') === 'foo.com') {
    return res.redirect(301, 'https://bar.com/' + req.originalUrl);
  }
}));
```

**Comment by stephane-tessier** [comment]
Ok Thanks

I did think of that implementation, but **I need to access services** in order to do it properly.
(otherwise it's quite ugly...)
