### ISSUE TITLE
NA

### ISSUE THREAD

**Issue by CharlieGreenman** [angular/universal#2961]

**Comment by alan-agius4** [comment]
This is most likely caused because a node.js debugger is not attached. As it will break on the first line of the application code.

**Comment by CharlieGreenman** [comment]
Can we then add documentation for that. Also no documentation for inspect in angular documentation ?

**Comment by alan-agius4** [comment]
We should defiantly add some docs about the SSR dev server. That being said, more information on how to inspect can be also be found in the Node.js documentation as all we are doing in exposing the inspect break option.

**Comment by CharlieGreenman** [comment]
ok then we will go ahead and add more documentation
