### ISSUE TITLE
Use WASM for server side rendering 

### ISSUE THREAD

**Issue by CharlieGreenman** [angular/universal#2965]
# Proposal

#### What is the summary of the proposal?

Using WASM for server-side rendering

#### What is the proposal?

Let's look into using WASM for server-side rendering. I'm not sure how long that initial start-up time would take for an express server but it would be a low-level approach toward getting universal going. 

Users can continue their regular deployment to their cloud providers, and all changes will be client-side only. 

#### Is there anything else we should know?

1. Potentially we can move off of the express server and use something else. 
2. WASM can be baked into app-initializer

**Comment by alan-agius4** [comment]
Thanks for this request however we don't have immediate plans to dive into WebAssembly code compilation support. We might revisit it in the future but this is not actionable for us at the moment.

**Comment by CharlieGreenman** [comment]
I'm not sure if you realize how easy this approach is. Fine I'll go ahead and do it myself, thank you

**Comment by CharlieGreenman** [comment]
I feel the people in the room have lost empathy for their end user. Do you know how much time your average user loses with universal? More than anything else related to angular I can assure you

**Comment by CharlieGreenman** [comment]
Also @alan-agius4 not sure why this was closed? Even if not supporting this is still a good idea. Let's keep this issue open and mull it over a bit more.

**Comment by alan-agius4** [comment]
We have a number of items that we want to implement to improve the overall Universal DX. 

That being said realistically speaking WASM support is not something that we will looking at anytime soon.
