### ISSUE TITLE
Changing the main component name to anything other that app causes an error

### ISSUE THREAD

**Issue by rlavoie** [angular/universal#299]
Changing the main component name to anything other that app causes an error. Would be nice if there was an option to change this.

Uncaught TypeError: Cannot read property 'cloneNode' of null

**Comment by gdi2290** [comment]
app is the default `res.render('index', { App: App })` you can change it `res.render('index', { App: WebSite })`

**Comment by jeffwhelpley** [comment]
@gdi2290 even if it is simply a matter of doing this, we should have a better, more informative error. @rlavoie were you able to get this working?

**Comment by rlavoie** [comment]
@jeffwhelpley Yes it did. Thank you. I had to also make sure my main app file exported the same name. So you can't export class App and choose a different name as the selector.

**Comment by gdi2290** [comment]
ya good idea, I can add an error
