### ISSUE TITLE
ng add @nguniversal/express-engine fails to install

### ISSUE THREAD

**Issue by Eidar** [angular/universal#3017]
# 🐞 Bug report

I cannot install Angular Universal with Angular Material. Running a fresh installation, adding Angular Material and then Angular Universal results in a dependency error.

- [ ] builders
- [ ] common
- [ x] express-engine

### Is this a regression?

I have been able to successfully install both Angular Material and Angular Universal using version 12. It worked but it was broken a bit, but I did not invest time and effort to fix it.  I had hoped that this was resolved.

### Description

Cannot ng add Angular Universal because of the version mismatch. It seeks 15 or greater, I have 15.01. and it's apparently not something that Universal can work with.

## 🔬 Minimal Reproduction

Initialize new Angular project and add Angular Material. Try and run ng add @nguniversal/express-engine.

## 🔥 Exception or Error

<pre><code>
λ ng add @nguniversal/express-engine
i Using package manager: npm
√ Found compatible package version: @nguniversal/express-engine@15.1.0.
√ Package information loaded.

The package @nguniversal/express-engine@15.1.0 will be installed and executed.
Would you like to proceed? Yes
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: kcp-frontend@0.0.0
npm ERR! Found: @angular/animations@15.1.2
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^15.0.0 || ^16.0.0" from @angular/material@15.1.2
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^15.1.2" from the root project
npm ERR!   peerOptional @angular/animations@"15.1.2" from @angular/platform-browser@15.1.2
npm ERR!   node_modules/@angular/platform-browser
npm ERR!     peer @angular/platform-browser@"15.1.2" from @angular/forms@15.1.2
npm ERR!     node_modules/@angular/forms
npm ERR!       peer @angular/forms@"^15.0.0 || ^16.0.0" from @angular/material@15.1.2
npm ERR!       node_modules/@angular/material
npm ERR!         @angular/material@"^15.1.2" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @angular/platform-browser@"^15.0.0 || ^16.0.0" from @angular/material@15.1.2
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^15.1.2" from the root project
npm ERR!     3 more (@angular/platform-browser-dynamic, @angular/router, the root project)
npm ERR!   1 more (the root project)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! @nguniversal/express-engine@"15.1.0" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/animations@15.1.4
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"15.1.4" from @angular/platform-server@15.1.4
npm ERR!   node_modules/@angular/platform-server
npm ERR!     peer @angular/platform-server@"^15.0.0" from @nguniversal/express-engine@15.1.0
npm ERR!     node_modules/@nguniversal/express-engine
npm ERR!       @nguniversal/express-engine@"15.1.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Matija\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Matija\AppData\Local\npm-cache\_logs\2023-02-12T12_10_17_463Z-debug.log
× Packages installation failed, see above.
</code></pre>

## 🌍 Your Environment

<pre><code>

1. [Angular CLI](https://github.com/angular/angular-cli) version 15.1.4.
2. node 16.13.1
3. npm 8.1.2
4. nvm 1.1.9.
5. Angular Material 15.1.2

</code></pre>

**Comment by alan-agius4** [comment]
Hi @Eidar, 

Can you try to update the Angular packages to the latest patch version?

**Comment by NiC0DAV** [comment]
Hey @Eidar, have you solved it?, I am presenting the same error...  :(

**Comment by dhovhannisyan** [comment]
use this command "npm install @nguniversal/express-engine --legacy-peer-deps"

**Comment by Eidar** [comment]
> Hi @Eidar,
> 
> Can you try to update the Angular packages to the latest patch version?

This is a newly created project, so it's the latest version. Node is a bit older cause Ghost CMS doesn't work with higher versions. 



> Hey @Eidar, have you solved it?, I am presenting the same error... :(

Unfortunately I quit on that project and made a new one using new version of node and everything works perfectly



> use this command "npm install @nguniversal/express-engine --legacy-peer-deps"

I tried, and it was kind of broken.

**Comment by dhovhannisyan** [comment]
1) remove the package node-modules
2) remove the file package-lock.json
3) run this command in the terminal <npm install @nguniversal/express-engine --legacy-peer-deps>
if the package "@nguniversal/express-engine" will be installed, without creating files "server.ts" and "app.server.module.ts", then run the command <ng add @nguniversal/express-engine>

**Comment by NiC0DAV** [comment]
> > Hi @Eidar,
> > Can you try to update the Angular packages to the latest patch version?
> 
> This is a newly created project, so it's the latest version. Node is a bit older cause Ghost CMS doesn't work with higher versions.
> 
> > Hey @Eidar, have you solved it?, I am presenting the same error... :(
> 
> Unfortunately I quit on that project and made a new one using new version of node and everything works perfectly
> 
> > use this command "npm install @nguniversal/express-engine --legacy-peer-deps"
> 
> I tried, and it was kind of broken.

Which version of node are you using on your new project?, I'm using node 18.13.0 and angular 15.1.3 but still not working

![image](https://user-images.githubusercontent.com/52676193/221875134-cbe1357f-f428-41e2-b062-9dd2bf4ff418.png)
