### ISSUE TITLE
index.html is being served as a static file

### ISSUE THREAD

**Issue by scottmizo** [angular/universal#3019]
# 🐞 Bug report

#### What modules are related to this issue?

- [X] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

 Unknown

### Description

 
When using a starter app and universal, index.html is being served as a static file.  http://localhost:4000 is being server side rendered but http://localhost:4000/index.html is not.  I believe the following code from server.ts is the issue:

<pre><code>
server.get('*.*', express.static(distFolder, {
    maxAge: '1y'
  }));

// All regular routes use the Universal engine
server.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
});
</code></pre>

## 🔬 Minimal Reproduction

- Create Angular starter app
- Add angular/universal
- Execute npm run build:ssr
- Execute npm run serve:ssr
- Check http://localhost:4000/index.html for server side rendering

## 🔥 Exception or Error

<pre><code>

None
</code></pre>

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.1.6
Node: 18.13.0
Package Manager: npm 8.19.3
OS: darwin x64

Angular: 15.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1501.6
@angular-devkit/build-angular   15.1.6
@angular-devkit/core            15.1.6
@angular-devkit/schematics      15.1.6
@angular/cli                    15.1.6
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.1.0
@schematics/angular             15.1.6
rxjs                            7.8.0
typescript                      4.9.5
</code></pre>

**Comment by alan-agius4** [comment]
This is expected when using SSR as when you are requesting `http://localhost:4000/index.html` you are requesting the static file, which does not go through the Express rendering engine.

The html files will contain the rendered view only when using you can use SSG (Prerendering) which happens during build time.
