### ISSUE TITLE
Allow TransferHttpCacheModule to accept POST requests

### ISSUE THREAD

**Issue by ahstudee** [angular/universal#3037]
# Proposal

#### What is the summary of the proposal?

Allow TransferHttpCacheModule to cache POST requests not just GET requests.

#### What is the proposal?

Rather than only cache GET api requests, please allow POST api requests too. There are certain situations where we still need to acquire data when using POST. For example when searching on an api which requires an extenstive search criteria. We are trying to send a very big object full of arrays and have no option but to send this as the body in a POST request. If we were to send this as GET as queries through the url we would breach the character limit.

**Comment by fitness23** [comment]
Any update on this? I’m also facing this problem too

**Comment by ahstudee** [comment]
Yeah any update on this? It's been an issue for quite a while now :)
