### ISSUE TITLE
fix(platform/node/document): encodeHtmlEntities

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#304]
encodeHtmlEntities is currently set to false rather than true. The serializer blows up if it's set to true for some reason.

see https://github.com/angular/universal/commit/d5e34c165eed243248d2acadac22b88ee901b3a9

**Comment by bjwyse** [comment]
I tested with encodeHtmlEntities set to true and it worked as expected, for ampersands at least.

Can you give an example of some HTML that caused an issue?

**Comment by jeffwhelpley** [comment]
@gdi2290 can you test this issue again? I can't reproduce either and this may have been fixed with one of the recent changes to core.

**Comment by gdi2290** [comment]
I can't reproduce this error anymore. I updated the repo to set it back to true as `0.104.4` see commit https://github.com/angular/universal/commit/1a0f1f39518b72fd13bade51e39bc5c82320a2dc

**Comment by MarkPieszak** [comment]
I believe encodeHtmlEntities is gone with parse 2.* as well

**Comment by gdi2290** [comment]
@MarkPieszak we can switch to Parse 2.0 now
