### ISSUE TITLE
Why Angular Universal is not having the same features as NextJS 13

### ISSUE THREAD

**Issue by alexcibotari** [angular/universal#3047]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [x] builders
- [x] common
- [x] express-engine

### Description

NexJS 13 is bringing so many features, especially now Angular with Standalone Components can achieve the same, why not invest in it?

### Describe the solution you'd like

Starting investing in SSG with Angular Standalone componenets

### Describe alternatives you've considered

Move to NextJS

**Comment by alan-agius4** [comment]
What features are you interested in other than SSG with Angular Standalone?

**Comment by alexcibotari** [comment]
I'm missing SSG route generation.
For example, I would like to generate all my pages with SSG and integration with any Headless CMS like [Localess](https://github.com/Lessify/localess)
Where I have URL with all available pages (routes) and the content of every page. How I can do exactly the same in the Angular Universal world?

At the moment I see routes to be configured in angular.json or text file. and I would like to have something more development-friendly experience, like REST call or anything different that can fulfill those routs and content of routs.

**Comment by alexcibotari** [comment]
Perfect description
