### ISSUE TITLE
Meta Title doesn't appear in view page source but its does in inspect

### ISSUE THREAD

**Issue by G-Abdullatif** [angular/universal#3056]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] common
- [ ] builders
- [ x ] express-engine

### Description

I was trying to make my meta tags dynamic with installing angular universal. After a lot of issues I had to solve to add angular universal to my project. and now its working perfectly. I run the project using npm run dev:ssr tag. hopefully to see my dynamic meta tags works. but unfortunately its didn't work and there is no any error message.

After a lot of search about this issue I just think the problem could be because of code cant work with angular universal. but the question is how to know what works and what doesn't with angular universal?

## 🔬 Minimal Reproduction
https://github.com/G-Abdullatif/SSR_Proplem

## 🌍 Your Environment

<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.2.10
Node: 16.14.0
Package Manager: npm 9.1.1
OS: win32 x64

Angular: undefined
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1402.10 (cli-only)
@angular-devkit/core         14.2.10 (cli-only)
@angular-devkit/schematics   14.2.10 (cli-only)
@schematics/angular          14.2.10 (cli-only)
</code></pre>

I created a new project and installed angular universal and set meta tags its work without any issues. then I just compared between the two projects all the files which related to angular universal to make sure there is no difference.

Please if you need more informations just tell me.

**Comment by alan-agius4** [comment]
Hi @G-Abdullatif, your reproduction is far from minimal. 

Can you please delete everything that is not needed to reproduce the problem? 

Thanks.

**Comment by G-Abdullatif** [comment]
Its very hard to remove more , a lot of errors shows up

**Comment by G-Abdullatif** [comment]
@alan-agius4 
Its very hard to remove more , a lot of errors shows up

**Comment by alan-agius4** [comment]
@G-Abdullatif, in general using browser specific APIs such as window, document, navigator, or location should be avoided if you intend to use SSR. 

If you however need to use these APIs, you can either use `isPlatformBrowser` or replace the implementation of the service that is using these APIs using DI.
