### ISSUE TITLE
[Documentation|Help] How to deploy Angular Universal to AWS lambda using serverless-express??

### ISSUE THREAD

**Issue by Jun711** [angular/universal#3059]
# Proposal

#### What is the summary of the proposal?
Include documentations on how to deploy it to popular cloud services

#### What is the proposal?
Include documentation on how to deploy to AWS Lambda

#### Is there anything else we should know?
I have followed steps written on this medium article but it is pretty outdated.

**Comment by rahulexpo** [comment]
Are you using s3 bucket? or an EC2 instance/elastic beanstalk? I recently deployed on both, may be I can help.

**Comment by Jun711** [comment]
@rahulexpo Can you please share with the documentation on how to deploy it using elastic beanstalk?
 
I have been trying to deploying on AWS Lambda using serverless-express following the steps in this [article](https://levelup.gitconnected.com/deploy-your-serverless-server-side-rendering-ssr-angular-app-on-aws-lambda-a01a3aab6ef6): Deploy Your Serverless Server-side-rendered (SSR) Angular App on AWS Lambda
The author did include a GitHub repo https://github.com/theideasaler/angular-serverless-server-side-rendering
But a lot of things have been changed since then.

**Comment by CharlieGreenman** [comment]
@Jun711 if your organization is willing to hire consultants, please reach out to charlie@razroo.com. We have done this before and we have a consultant or two that can help. The documentation is long so we haven't had a chance to publish it yet. We plan do so in a month or two. Thank you

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
