### ISSUE TITLE
Angular 15 SSR and Lazy-Loading module not loading state on server

### ISSUE THREAD

**Issue by guiligan** [angular/universal#3061]
#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [X] express-engine

### Is this a regression?

No

### Description

Recently we started changing our architecture from Angular SSR to use SSR with Lazy Loading modules.

In the first versions the modules were all imported on our `routes` file.

A component, for instance, would load data from our API and if running at the server would add data to the `transferState`. At the browser, we would check if the state existed, if not, load from the backend.

Now our components are lazy-loaded in different modules:

 - `App Module` lazy-loads `A module` with `A component`
 - `A Module` lazy-loads `B module` with `B component`

before `B component` would load data as stated before (with `transferState`), but the behavior now is to load only on the client side.

Did we get it wrong that it would be possible to continue using server-side loading, or something was implemented wrongly?

## 🌍 Your Environment

<pre><code>
Angular CLI: 15.0.4
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    15.0.3
@angular/material               15.0.3
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.4
rxjs                            7.8.0
typescript                      4.8.4
</code></pre>

**Comment by guiligan** [comment]
hey @alan-agius4 , we are using `HTTPClient`, but not `TransferHttpCacheModule`. However, we don't see the request being made on server-side

**Comment by alan-agius4** [comment]
@guiligan, without a reproduction it’s hard to tell what is happened. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
What is happening here is actually that the page is not being server rendered. 

The culprit code seems to be 
https://github.com/guiligan/repro-app-3061/blob/6a545de42cf6621561d03a856094c09b78c57d9f/server.ts#L36-L44

Not really sure why you are adding `localhost/` to the `baseUrl` and `url` but this breaks the Angular router as it cannot locate the right routes since `localhost/b-module` does not exist.

**Comment by guiligan** [comment]
@alan-agius4 sorry about that, we are using a custom matcher for multiple domain serving. I have managed to make it work on the repo, but don't know why it does not work in the full project. Are there any circumstances that make it not load the module for pre-rendering on server? It seems it never gets to the second level router

**Comment by alan-agius4** [comment]
> project. Are there any circumstances that make it not load the module for pre-rendering on server? It seems it never gets to the second level router

Typically misconfiguration of the router APP_BASE_HREF and/or incorrect request parameters

**Comment by guiligan** [comment]
@alan-agius4 any known issue with SSR and MatMenuModule? Found out that the modules that are not running on server-side are those that have Angular Material Menu Module imported

**Comment by alan-agius4** [comment]
No, they should work. At least no one reported such issues.

**Comment by guiligan** [comment]
@alan-agius4 , just did a quick test using the [clean repo](https://github.com/guiligan/repro-app-3061/) stated before. I have removed the unused code that you pointed before.

Upon opening `http://localhost:4200` it will lazy load `AModule`, display `AComponent`, lazy load `BModule` and display `BComponent`.

In `BComponent`, if it runs in the server, will set and pass the stateKey to the browser (https://github.com/guiligan/repro-app-3061/blob/main/src/app/B/b.component.ts#L22-L26) with the value `<state key set in server>`.

It works fine:

![image](https://user-images.githubusercontent.com/1742604/229176493-22153dfb-dcb1-49bc-aa1d-0b49711a1fec.png)

However, if I import `MatInputModule`, like [here](https://github.com/guiligan/repro-app-3061/blob/main/src/app/A/a.module.ts#L12), it will stop working and display the default state of `<no state>`

![image](https://user-images.githubusercontent.com/1742604/229176773-f5306b88-3570-43e1-b187-61b6cf173a7f.png)

Only two changes from before (not the same environment from original issue):

 - Return `server.ts` to its default
 - Installed Angular Material

<pre><code>
Angular CLI: 15.0.5
Node: 18.12.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.0.4
... animations, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.4
@angular-devkit/build-angular   15.2.4
@angular-devkit/core            15.2.4
@angular-devkit/schematics      15.0.5
@angular/cli                    15.0.5
@nguniversal/builders           15.0.0
@nguniversal/express-engine     15.0.0
@schematics/angular             15.0.5
rxjs                            7.8.0
typescript                      4.8.4
</code></pre>

**Comment by alan-agius4** [comment]
Let me take a look at this on Monday.

**Comment by alan-agius4** [comment]
The problem is https://github.com/guiligan/repro-app-3061/blob/f15cea8858754d45aeba3eb7c2077aaa2bf219a6/server.ts#L9

**Comment by guiligan** [comment]
@alan-agius4 great, thank you very much for the help, was able to make everything work here.
