### ISSUE TITLE
Getting "TypeError: (intermediate value).ngOnDestroy is not a function" on Angular v15

### ISSUE THREAD

**Issue by yousaf101** [angular/universal#3075]
Following are the **dependencies** and **devDependencies** from **package.json** file:

"dependencies": {
    "@angular/animations": "^15.0.3",
    "@angular/cdk": "^15.0.2",
    "@angular/common": "^15.0.3",
    "@angular/compiler": "^15.0.3",
    "@angular/core": "^15.0.3",
    "@angular/forms": "^15.0.3",
    "@angular/platform-browser": "^15.0.3",
    "@angular/platform-browser-dynamic": "^15.0.3",
    "@angular/platform-server": "^15.0.3",
    "@angular/router": "^15.0.3",
    "@ng-bootstrap/ng-bootstrap": "^14.0.0",
    "@nguniversal/express-engine": "^15.2.0",
    "@popperjs/core": "^2.11.6",
    "bootstrap": "^5.2.3",
    "express": "^4.15.2",
    "rxjs": "~7.5.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^15.0.3",
    "@angular/cli": "^15.0.3",
    "@angular/compiler-cli": "^15.0.3",
    "@angular/localize": "^15.0.3",
    "@nguniversal/builders": "^15.2.0",
    "@types/express": "^4.17.0",
    "@types/jasmine": "~3.10.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~4.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.8.4"
  }

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
