### ISSUE TITLE
create `NodeDomSharedStylesHost`

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#308]
create `NodeDomSharedStylesHost ` that extends from `DomSharedStylesHost` to be decoupled more from DOCUMENT

**Comment by manekinekko** [comment]
@gdi2290 could we just fake DOCUMENT? something like: 
```
new Provider(DOCUMENT, {
   useFactory: (dom: DOM) => () => dom.createHtmlDocument(),
   deps: [DOM]
})
```

**Comment by gdi2290** [comment]
we already fake it but we need more control over the styles. For multiple applications the style host is shared since it's at the platform level. At the moment we are relying on mutating the fake document

**Comment by gdi2290** [comment]
a directive hosting the styles are needed `<ng-style-host></ng-style-host>`

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/e8befd4d0843ffb51dc2b987fe56a37cd38c9d3e as NodeStyleHost where the directive `<ng-style-host></ng-style-host>` is needed for html components
