### ISSUE TITLE
Build SSR : error SVG is not defined

### ISSUE THREAD

**Issue by nguyentrunghieutcu** [angular/universal#3080]
__zone_symbol__value: ReferenceError: SVG is not defined

# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [ ] common
- [x] express-engine

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>

</code></pre>

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
