### ISSUE TITLE
Index.html file of the folder not rendered unless explicitly refreshed

### ISSUE THREAD

**Issue by upesh-mp** [angular/universal#3096]
When I click on a link in a pre-rendered static page (the link leads to another static pre-rendered page), it currently routes to the URL of that page without the index.html extension, and the resulting page is not the static version, but rather the dynamic version that makes server calls. However, if I hit refresh, the page renders as a static page with all the server data in it.

I am wondering if you could provide assistance in resolving this issue. Ideally, the static page should render without the need for a browser refresh. Thank you.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
