### ISSUE TITLE
Prerendered files are not linked

### ISSUE THREAD

**Issue by upesh-mp** [angular/universal#3097]
# 🐞 Bug report

#### What modules are related to this issue?

- [yes ] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

Not sure if it was working in the previous version, I am using 
"@nguniversal/builders": "^13.1.1",
"@nguniversal/express-engine": "^13.1.1",

### Description

I am trying to implement dynamic rendering for SEO purpose, when I run prerender, it generates index.html files for all the routes that I configured, but the problem is, when I click on a anchor tag with routerlink (for which prerendering is done), it is not navigating to the index.html file of that route but instead does an inbuilt routing which invokes server to fetch the data.

## 🔬 Minimal Reproduction
Just need to prerender multiple routes and see if you are able to navigate to those routes by clicking on links that leads to those routes.

## 🔥 Exception or Error
There are no exceptions when I generate the static files

## 🌍 Your Environment

<pre><code>
Angular CLI: 14.1.3
Node: 14.15.0
Package Manager: npm 6.14.8 
OS: win32 x64

Angular: 14.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.10
@angular-devkit/build-angular   14.2.10
@angular-devkit/core            14.2.10
@angular-devkit/schematics      14.1.3
@angular/cdk                    14.2.7
@angular/cli                    14.1.3
@angular/material               14.2.7
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             14.1.3
rxjs                            7.5.7
typescript                      4.7.4

</code></pre>

**Comment by alan-agius4** [comment]
Hi @upesh-mp, that is expected because a the Angular application is a single page application, once Angular is bootstrap navigation and rendering happen on the client side, which is far more performant than doing a HTTP request.

From SEO purposes this is also not a problem because.
1. If the search engine crawler does not support JS when the navigation happens a request is made to retrieve the requested page (you can check this by disabling JS support in your browser.
2. Most search engine crawlers nowadays support running JS.

**Comment by upesh-mp** [comment]
Thanks @alan-agius4 , I was able to get the navigation working when javascript was disabled. But in your second point, as you mentioned that most of the crawlers support running JS, would it be a problem that the navigation will not be rendering the pre-rendered and makes a server call to paint the data?

**Comment by alan-agius4** [comment]
No, and also from my understanding search engine crawls will force a new server navigation when navigating from one page to another.

**Comment by upesh-mp** [comment]
Thanks. And one more favor if you could. I looked at my search console and I could see that many of the pages were crawled with proper content by Google even though they were client side rendered. So is it really necessary for us to do SSR or prerendering?

**Comment by alan-agius4** [comment]
It is not necessary to do SSR and SSG to have SEO, but these will improve the core web vitals which in turn causes search engines to prioritise your ranking.
