### ISSUE TITLE
use Webpack for building

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#31]
Working with gulp it would be great to use Webpack when building our TypeScript files to commonjs

**Comment by gdi2290** [comment]
yo @ashsidhu, after Karma you can do this one. You can take inspiration from https://github.com/angular-class/angular2-webpack-starter/blob/master/webpack.config.js and  https://github.com/rackt/react-router/blob/master/webpack.config.js

**Comment by ashsidhu** [comment]
@gdi2290 I can take care of this issue.

**Comment by gdi2290** [comment]
@ashsidhu any updates?

**Comment by gdi2290** [comment]
this needs to be thought out a bit more to figure out which environments to build for. The idea behind using webpack for building is being able create multiple built scripts for preboot.js as well as client bundles.

**Comment by gdi2290** [comment]
I'll work on switching the build system to webpack

**Comment by malfborger** [comment]
what's the status here @gdi2290 ?

**Comment by gdi2290** [comment]
@malfborger I've been avoiding it until we have a better build system and our type definitions are fixed. At the moment we're still using typescript to compile the modules

**Comment by gdi2290** [comment]
closing now as we need webpack more so for the examples than the modules. After the new module workflow refactor done a couple of weeks ago, we can simply stay with regular typescript compile
