### ISSUE TITLE
provide new document during each request

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#310]
parse the initial document during each request

**Comment by manekinekko** [comment]
@gdi2290 can you explain more? what is the expected result?

**Comment by gdi2290** [comment]
the problem when you dispose an application (using AppRef). After serializing the document it is that the rootElement that is removed from the document. So during the next request/response cycle there is an error when the app can not find the document.

**Comment by gdi2290** [comment]
at the moment I'm making sure to reference the same document for each new application within a prerender cycle
