### ISSUE TITLE
Standalone Support Docs

### ISSUE THREAD

**Issue by ferranJS** [angular/universal#3112]
# Proposal
Standalone Support Docs
#### What is the summary of the proposal?
Add Standalone component rendering support docs
#### What is the proposal?
The change is kind of explained in [the first commit of this pr](https://github.com/angular/universal/pull/3045/commits/51e4353a599d3d46ae8cbb24c9e876d81f918589) and it is not very clear if this change is even fully supported or if it is a workaround. I think this needs proper documentation either way.
#### Is there anything else we should know?
Angular is pushing a lot for standalone and SSR being so talked about and important nowadays, this should be supported and well documented. Sorry if any of this is a bit informal, and thanks in advance.

**Comment by alan-agius4** [comment]
Standalone are fully supported. What would you like to see documented? From Universal side using an NgModule or Standalone based app is pretty much the same.

**Comment by ferranJS** [comment]
> Standalone are fully supported. What would you like to see documented? From Universal side using an NgModule or Standalone based app is pretty much the same.

I've seen a lot in the [this angular official doc](https://angular.io/guide/universal) how to set it up but only with NgModules and not a mention about standalone. However, now that I think it, maybe I should have opened the issue in the angular project, my bad.

**Comment by alan-agius4** [comment]
That page has actually been updated

See the prerelease version:
https://next.angular.io/guide/universal
