### ISSUE TITLE
require() of ES Module from node_modules/@nguniversal/builders/src/prerender/worker.js not supported.

### ISSUE THREAD

**Issue by Startouf** [angular/universal#3114]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

 The problem started to occur after I enabled prerendering and upgraded angular v13->v15. (https://firebase.google.com/docs/hosting/frameworks/angular). I'm not sure if this is a regression 

### Description

After upgrading angular 13 -> 15 and trying to enable prerendering via firebase, the deployment fails with 

```
require() of ES Module [...]/myapp/frontend/dist/rock-it/server/main.js from [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js not supported.
```

## 🔬 Minimal Reproduction

Add Firebase prerendering to an angular 15 application 
- with angular/universal following the guide https://firebase.google.com/docs/hosting/frameworks/angular
- with `"type": "module"` in package.json

Then run firebase deploy --only hosting

Here is my firebase.json 

```
{
  "hosting": {
    "source": "frontend/",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "/api/**",
        "function": "api"
      },
      {
        "source": "/login/**",
        "function": "api"
      },
      {
        "source": "/oauth/**",
        "function": "api"
      },
      {
        "source": "/sitemap.xml",
        "destination": "/sitemap.xml"
      },
      {
        "source": "**",
        "destination": "/index.html"
      }
    ],
    "headers": [
        {
        "source": "**/*.@(eot|otf|ttf|ttc|woff|font.css)",
        "headers": [ {
          "key": "Access-Control-Allow-Origin",
          "value": "*"
        } ]
      }, {
        "source": "**/*.@(jpg|jpeg|gif|png)",
        "headers": [ {
          "key": "Cache-Control",
          "value": "max-age=7200"
        } ]
      }, {
        "source": "404.html",
        "headers": [ {
          "key": "Cache-Control",
          "value": "max-age=300"
        } ]
      }
    ],
    "predeploy": [
      "npm --prefix ./frontend run lint",
      "npm --prefix ./frontend run build:prod"
    ]
  },
  "prerender": {
    "builder": "@nguniversal/builders:prerender",
    "options": {
      "routes": [
        "/",
        "/home/newcomer"
      ]
    },
    "configurations": {
    },
    "defaultConfiguration": "production"
  },
  "storage": {
    "rules": "storage.rules"
  },
  "emulators": {
    "firestore": {
      "port": 8080
    },
    "database": {
      "port": 9000
    },
    "storage": {
      "port": 9199
    },
    "ui": {
      "enabled": true
    },
    "functions": {
      "port": 5001
    },
    "hosting": {
      "port": 4200
    }
  },
  "functions": {
    "predeploy": [
      "npm --prefix ./backend run lint",
      "npm --prefix ./backend run build"
    ],
    "source": "backend"
  }
}
```

## 🔥 Exception or Error

<pre><code>

Prerendering 1 route(s) to [...]/myapp/frontend/dist/rock-it/browser...Unhandled Promise rejection: require() of ES Module [...]/myapp/frontend/dist/rock-it/server/main.js from [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js not supported.
main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in [...]/myapp/frontend/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).
 ; Zone: <root> ; Task: Promise.then ; Value: Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/myapp/frontend/dist/rock-it/server/main.js from [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js not supported.
main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in [...]/myapp/frontend/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js:55:137
    at _ZoneDelegate.invoke ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:409:30)
    at Zone.run ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:169:47)
    at [...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:1326:38
    at _ZoneDelegate.invokeTask ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:443:35)
    at Zone.runTask ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:214:51)
    at drainMicroTaskQueue ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:632:39) {
  code: 'ERR_REQUIRE_ESM'
} Error [ERR_REQUIRE_ESM]: require() of ES Module [...]/myapp/frontend/dist/rock-it/server/main.js from [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js not supported.
main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in [...]/myapp/frontend/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

    at [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js:55:137
    at _ZoneDelegate.invoke ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:409:30)
    at Zone.run ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:169:47)
    at [...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:1326:38
    at _ZoneDelegate.invokeTask ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:443:35)
    at Zone.runTask ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:214:51)
    at drainMicroTaskQueue ([...]/myapp/frontend/node_modules/zone.js/bundles/zone.umd.js:632:39)
✖ Prerendering routes to [...]/myapp/frontend/dist/rock-it/browser failed.
require() of ES Module [...]/myapp/frontend/dist/rock-it/server/main.js from [...]/myapp/frontend/node_modules/@nguniversal/builders/src/prerender/worker.js not supported.
main.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename main.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in [...]/myapp/frontend/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).

Error: An unexpected error has occurred.

</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 15.2.7
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin x64

Angular: 15.2.8
... animations, cdk, common, compiler, compiler-cli, core, forms
... google-maps, language-service, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.7
@angular-devkit/build-angular   15.2.7
@angular-devkit/core            13.3.11
@angular-devkit/schematics      13.3.11
@angular/cli                    15.2.7
@nguniversal/builders           15.2.1
@nguniversal/express-engine     15.2.1
@schematics/angular             15.2.7
rxjs                            6.5.5
typescript                      4.8.4
</code></pre>

**Comment by alan-agius4** [comment]
This is expected since you are adding `"type": "module"` to your package.json. 

There are two solutions to this. 
1) Remove `"type": "module"`
2) In the `dist` add a `package.json` with `"type": "commonjs"`
