### ISSUE TITLE
static-generator gives 'Angular application failed to stablize after in time.' error while pre-rendering

### ISSUE THREAD

**Issue by varun-av** [angular/universal#3120]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

Gives the same error with 15.x and the latest 16.0.0 versions.

### Description

While trying to pre-render the angular app in nx workspace using `@nguniversal/builders:static-generator`, it fails and I get the following error: `Angular application failed to stablize after in time.`

## 🔬 Minimal Reproduction

- Created a new angular app
- setup angular universal ssr for the angular app by installing `@nguniversal/builders`, `@nguniversal/express-engine` and `@angular/platform-server`
- update project.json (nx workspace) with `static-generator` target
- run the `static-generator` target

## 🔥 Exception or Error
<pre><code>`Angular application failed to stablize after in time.`
</code></pre>

## 🌍 Your Environment

<pre><code>Angular CLI: 16.0.0
Node: 18.15.0
Package Manager: npm 9.5.0
OS: darwin arm64

Angular: 16.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.0
@angular-devkit/build-angular   16.0.0
@angular-devkit/core            16.0.0
@angular-devkit/schematics      16.0.0
@nguniversal/builders           16.0.0
@nguniversal/express-engine     16.0.0
@schematics/angular             16.0.0
ng-packagr                      16.0.0
rxjs                            7.5.7
typescript                      5.0.4
</code></pre>

**Comment by alan-agius4** [comment]
Hi, thanks for opening the issue. 

`@nguniversal/builders:static-generator` has been deprecated in version 15 and it cannot be used with `@angular/platform-server` and `@nguniversal/express-engine`. Please use `@nguniversal/builders:prerender` instead.

See: https://angular.io/guide/prerendering

**Comment by varun-av** [comment]
Hi @alan-agius4 ,

Thanks for clearing that out.

I was wondering if it is possible to prerender angular apps and deploy them without the server? Handling multiple server for every pre-rendered app won't be feasible for us.

**Comment by varun-av** [comment]
Thanks! Worked like a charm.
