### ISSUE TITLE
To make a lazy loaded module load Http request on server, an Http request must be present in AppComponent

### ISSUE THREAD

**Issue by ayyash** [angular/universal#3137]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [x] common
- [x] express-engine

### Is this a regression?
Yes, the previous version in which this bug was not present was: 14 at least, not sure if 15 worked, I did not have the chance to test it.

### Description
Reopening this issue: https://github.com/angular/universal/issues/2656
I have the same repo referred to here: https://github.com/paulheising/ng-universal-lazy-loading-bug/
But I don't import the `HttpClientModule` anywhere except in the `AppModule`, (through a sub module that provides Http Interceptors). The `subscribe` calls to Http requests work fine, and log on server. The `async` subscriptions however don't. I must make an http call in `AppComponent` for the `async` to work properly on lazy loaded modules.

## 🔬 Minimal Reproduction
https://github.com/paulheising/ng-universal-lazy-loading-bug/

**Comment by alan-agius4** [comment]
This should have been addressed in version 16.  Please update to the most recent version to resolve the problem.

If the problem persists in your application after upgrading, please open a new issue.

**Comment by ayyash** [comment]
I am using v 16.0.0 (sorry did not make that clear)
