### ISSUE TITLE
Prerender does not support esbuild

### ISSUE THREAD

**Issue by ishaarawy** [angular/universal#3154]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders (prerender)
- [ ] common
- [ ] express-engine

### Is this a regression?
It is working with build-angular:browser

### Description
Prerender does not work with Esbuilds (@angular-devkit/build-angular:browser-esbuild)
It builds both targets ( the server and the browser ) fine
then finishes without executing the prerendering

## 🔬 Minimal Reproduction

```
 "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser-esbuild"
          ...
          }
 }
...
  "prerender": {
          "builder": "@nguniversal/builders:prerender",
          "options": {
            "routesFile": "./ssr-routes.txt",
            "guessRoutes": false,
            "numProcesses": 8
          },
          "configurations": {
            "stage": {
              "browserTarget": "app:build:stage",
              "serverTarget": "app:server:stage"
            },
       }
}
```
ng run app:prerender:stage

## 🔥 Exception or Error

There is no exception it just close without executing the prerendering

## 🌍 Your Environment

<pre><code>
Angular CLI: 16.0.3
Node: 16.17.0
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.3
@angular-devkit/build-angular   16.0.3
@angular-devkit/core            16.0.3
@angular-devkit/schematics      16.0.3
@angular/cdk                    16.0.2
@angular/fire                   7.6.1
@angular/material               16.0.2
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.3
rxjs                            7.8.1
typescript                      5.0.4

</code></pre>

**Comment by marcusfeeney** [comment]
Same thing here

**Comment by alan-agius4** [comment]
The application builder (`@angular-devkit/build-angular:application`) which was release in version 16.2 should be used instead.
