### ISSUE TITLE
Render ngFor after http call

### ISSUE THREAD

**Issue by joaogarin** [angular/universal#316]
Hello,

I have a component rendering a ngFor with data coming from an Http request. The http request works fine after the latest changes (beta8 and latest of universal-preview) and the data is received corectly.

However it does not copy it to the template. Very similar to what is done here https://angular.io/docs/ts/latest/guide/server-communication.html with the heroes example. Is there something specific that needs to be done so that the ngFor actually prints the data into the template with Universal?

Best regards
Joao Garin

**Comment by gdi2290** [comment]
we're working on adding this back

**Comment by gdi2290** [comment]
closing for this issue you can track https://github.com/angular/universal/issues/274

**Comment by joaogarin** [comment]
Thanks;)

**Comment by joaogarin** [comment]
Hello,

I am still getting this problem with latest version.

https://github.com/angular/universal/issues/274 seems to be resolve but in my app it looks like the client side is never really picked up.

My repo is https://github.com/joaogarin/myblog-angular2, the HTTP calls do seem okay as I can log and see that I receive a response but in the client nothing is really rendered.

**Comment by wellingWilliam** [comment]
This is also the case for me. The server is able to make and receive a response from the http request, but does not template the observable with the async pipe before handing the html to the client.

https://github.com/wellingWilliam/Angular2DSpaceUIPrototype/tree/redesign

"dependencies": {
    "angular2": "2.0.0-beta.11",
    "angular2-universal-preview": "~0.82.0",
    "angular2-websocket": "^0.6.2",
    "express": "^4.13.4",
    "preboot": "^2.0.5",
    "rxjs": "5.0.0-beta.2"
  },

When the client app is running, preboot.dom.state.appRoot in buffer_manager is null and throws exceptions all the way to the zone microtask promise handling.

Additionally, in order to make 'https' requests I had to add the following to node_http.

var http;
if (reqInfo.protocol === 'https:')
    http = require('https')
else
    http = require('http')

**Comment by gdi2290** [comment]
@wellingWilliam I'll fix the https issue and look into |async you can track the http issue at https://github.com/angular/universal/issues/326

**Comment by wellingWilliam** [comment]
Found cause of client side error. preboot_browser start was conditioning true on an empty object created on dom init. 

`dom.state.body ? load() : dom.onLoad(load);
`
maybe more like:

```
if (Object.keys(dom.state.body).length == 0) {
        dom.onLoad(load);
    }
    else {
        load();
    }
```

alternatively 

dom init should default to null

**Comment by wellingWilliam** [comment]
@gdi2290 any way to track progress on templating through async pipe on server?

**Comment by wellingWilliam** [comment]
my bad. bootloader serializeApplication gives the undocumented property on ngApp

```
res.render('index', {
        directives: [AppComponent, TitleComponent],
        providers: [
            provide(APP_BASE_HREF, { useValue: baseUrl }),
            provide(REQUEST_URL, { useValue: url }),
            ROUTER_PROVIDERS,
            NODE_LOCATION_PROVIDERS,
            NODE_PRELOAD_CACHE_HTTP_PROVIDERS,
            DSpaceService,
            HttpService,
            WebSocketService
        ],
        async: true,
        preboot: true,
        precache: true,
    });
```

server-side rendering of async calls work great. thanks again

**Comment by gdi2290** [comment]
@wellingWilliam can you create an issue about the preboot error?

**Comment by joaogarin** [comment]
Using 

`providers: [
            provide(APP_BASE_HREF, { useValue: baseUrl }),
            provide(REQUEST_URL, { useValue: url }),
            ROUTER_PROVIDERS,
            NODE_LOCATION_PROVIDERS,
            NODE_PRELOAD_CACHE_HTTP_PROVIDERS
        ],
        async: true,
        preboot: true,
        precache: true,`

I can get it to render on the template. But still my client side app does not actually kick in and I think that might be the issue with preboot.

Should NODE_PRELOAD_CACHE_HTTP_PROVIDERS or NODE_HTTP_PROVIDERS by used for http requests?

**Comment by gdi2290** [comment]
I'm going to replace NODE_PRELOAD_CACHE_HTTP_PROVIDERS with NODE_HTTP_PROVIDERS soon so for now use NODE_PRELOAD_CACHE_HTTP_PROVIDERS. 

@joaogarin on the client you need to tell preboot to complete and swap the views

```es6
import {prebootComplete} from 'angular2-universal-preview'
import {bootstrap} from 'angular2/core';

import {App} from './src/app/app';

bootstrap(App).then(prebootComplete);
```

**Comment by joaogarin** [comment]
`import 'angular2-universal-preview/polyfills';
import {prebootComplete} from 'angular2-universal-preview';

import {bootstrap} from 'angular2/platform/browser';
import {ROUTER_PROVIDERS} from 'angular2/router';
import {HTTP_PROVIDERS} from 'angular2/http';

import {App} from './app/app';

bootstrap(App, [
    ...ROUTER_PROVIDERS,
    ...HTTP_PROVIDERS
])
.then(prebootComplete);
`

This is how my client looks like. I am debugging now and it get in the start() method of preboot_browser with what looks to be the correct dom representation. Trying to figure it out.
tks

**Comment by wellingWilliam** [comment]
This is how I finally had the server render async requests if client javascript disabled.

```
// Serverside Angular
function ngApp(req, res) {
    let baseUrl = '/';        
    let url = req.originalUrl || '/';
    console.log('url: ' + url);
    res.render('index', {
        directives: [AppComponent, TitleComponent],
        providers: [
            provide(APP_BASE_HREF, { useValue: baseUrl }),
            provide(REQUEST_URL, { useValue: url }),
            ROUTER_PROVIDERS,
            NODE_LOCATION_PROVIDERS,
            NODE_PRELOAD_CACHE_HTTP_PROVIDERS,
            DSpaceService,
            HttpService,
            WebSocketService
        ],
        async: true,
        preboot: true,
        precache: true,
    });
}
```

Specifivally having both async and precache true with NODE_PRELOAD_CACHE_HTTP_PROVIDERS. Even though a warning says to use async instead of precache.

**Comment by joaogarin** [comment]
Yes I noticed the **async** and **precache** true both need to stay so that it works on the server (rendering to the template). However for some reason I think due to some problems on my app the client side does not kick in..but server http works fine like @wellingWilliam mentions.

**Comment by lngr** [comment]
FWIW, I have a similar, possibly related problem where the src attribute is empty when rendered as `<img src="{{imgSrc}}">`, but works when I use `<img attr.src="{{imgSrc}}">`. On the client both methods work.

**Comment by wellingWilliam** [comment]
I have a working example on this. There is a slight flicker after the client runs prebootComplete. I recall a webinar saying this transition would eventually be smoother so the client does not have to re-render the template the server already rendered. However,if JavaScript is disabled the server returns templated html.

https://github.com/wellingWilliam/AngularUniversalDSpaceUIPrototype

There is an issue opened to resolve an error with the preboot dom init. 

https://github.com/angular/universal/issues/328

**Comment by joaogarin** [comment]
@lngr I think for these cases you should be using the rendered https://github.com/angular/universal#best-practices

**Comment by lngr** [comment]
@joaogarin thanks, I thought that this only referred to manipulation via `element.nativeElement.style = "font-weight: bold". But `img src` is also mentioned. I'll take a closer look.

**Comment by wellingWilliam** [comment]
I have another potential issue with rendering *ngFor templates. Not sure if related with this issue or should be separate. When using async child routes and creating routerLinks within an ngFor the link provided by the server side rendering is broken. It does not append the path variable to the child route. Such as:

```
<ul class="list-group">
    <li *ngFor="#directory of directories" class="list-group-item">        
        <!-- Router link -->
        <a [routerLink]="[directory.path, directory.component, {id:directory.id}]" (click)="select(directory)" class="clickable">{{ directory.name }}</a>        
    </li>
</ul>
```

The client side works as expected and the link navigates to the desired component. With JavaScript disabled the links href is missing the id.

**Comment by gdi2290** [comment]
@wellingWilliam can you create a new issue about async child routes with routerLink

**Comment by gdi2290** [comment]
@lngr can you create another issue about `src="{{ url }}"`

**Comment by wellingWilliam** [comment]
@gdi2290 done. https://github.com/angular/universal/issues/330

**Comment by lngr** [comment]
@gdi2290 done. #331

**Comment by jeffwhelpley** [comment]
So, it seems like there are 3 or 4 different issues here. #330 has a PR pending in core so we are just waiting for that. #331 is fixed. Some of the preboot issues mentioned are fixed. It seems like this issue is resolved, but please comment here if any of you on this issue think differently after getting the latest and re-testing.

**Comment by cyrilletuzi** [comment]
Same issue with the very last version of Universal (2.0.4). Static contents are well rendered by Universal, but async content retrieved by HTML calls are not rendered. Http calls work and get the data, but as the operation is async, rendering has already been done (verified by checking ngAfterViewInit).

**Comment by jeffwhelpley** [comment]
@cyrilletuzi if you are saying data retrieved from http calls are not displayed, then it must be due to issues with the zone patch. Can you post your code where the http calls are being made and your bootstrap code? cc @gdi2290

**Comment by cyrilletuzi** [comment]
@jeffwhelpley Thanks for the tip. With Universal 2.0.3 I needed to go back to zone.js 0.6.21 as there was an error with the last 0.6.23 zone.js, but it works now with Universal 2.0.4. Universal package.json should be updated consequently (can do a PR but for such a small change I think it's quicker to be done by a member).
