### ISSUE TITLE
Can not set a fixed port for ssr-dev-server

### ISSUE THREAD

**Issue by tkiefer24** [angular/universal#3180]
# 🐞 Bug report

#### What modules are related to this issue?

- [x] builders / ssr-dev-server
- [ ] common
- [ ] express-engine

### Is this a regression?

The behavior seems to work in previous versions see here:
https://github.com/angular/universal/issues/1628#issuecomment-616322722

### Description

The `--port` parameter for ssr-dev-server executor is not considered.
Server always starts on a dynamic port.

What I can see in the code is that no `options.port` is considered betweeen the following lines:
https://github.com/angular/universal/blob/main/modules/builders/src/ssr-dev-server/index.ts#L84..L94

## 🔬 Minimal Reproduction

Start on command line inside a fresh project:
```
ng serve-ssr --port 1234
```

## 🔥 Exception or Error

<pre><code>
Server is started on a dynamic port number.
</code></pre>

## 🌍 Your Environment

<pre><code>
ngular CLI: 15.2.1
Node: 16.17.1
Package Manager: yarn 3.4.1
OS: linux x64

Angular: 15.2.1
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, localize, material
... material-moment-adapter, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@angular/platform-server        15.2.9
@nguniversal/builders           15.1.0
@nguniversal/express-engine     15.1.0
@schematics/angular             15.2.1
ng-packagr                      15.2.2
rxjs                            7.8.0
typescript                      4.9.5

</code></pre>

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.

Can you please set up a reproduction?

**Comment by tkiefer24** [comment]
Thanks for investigation. I tried it with a fresh installation and it works now. Issue a wrong version of the async package that was used from portscanner util of browser-sync.
