### ISSUE TITLE
Inability to send requests to assets using APP_BASE_HREFf in an Angular unviersal application

### ISSUE THREAD

**Issue by khajatakreemulla** [angular/universal#3187]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
-  express-engine

### Is this a regression?

  I haven't wokred on previous version we migrated our angular app to angular unviersal.

### Description

I recently migrated my angular project to angular universal for better seo and I am facing a 404 error when hosting my Angular Universal web app. The HTML page loads correctly, but the other files generated in the browser folder are getting 404 and the request is going via `/` wheare as the request should have went through `/angular` as i want to send request to angular application from prefix using APP_BASE_HREF.

The problem arises even in new angular project on server.

<pre><code>
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'main.70cd7ff3a114efdd69a5.js' 
Error: Cannot match any routes. URL Segment: 'assets/favicon.ico' error. and for oher files also
</code></pre>

I have configured my NGINX server to handle the requests and proxy them to the appropriate backend server.
Here is the NGINX configuration I am using:

<pre><code>
server {
    listen       443 ssl;
    server_name  example.com;

    location /api {
        return 301 $uri/;
    }

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass http://127.0.0.1:3000;
        proxy_redirect off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location /agnular/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwared-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto https;

        proxy_pass http://127.0.0.1:4200;
        proxy_redirect off;proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

server {
    listen      80;
    server_name example.com;
    return 301 https://$server_name$request_uri;
}
</code></pre>

I am also using the APP_BASE_HREF value of **/angular/** for the domain.

### Code Changes as mentioned in the documentation ( APP_BASE_HREF)[https://angular.io/api/common/APP_BASE_HREF]
1. added APP_BASE_HREF in app.module.ts
<pre><code>
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { APP_BASE_HREF } from '@angular/common';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { LoginComponent } from './login/login.component';
import { ListComponent } from './list/list.component';

@NgModule({
  declarations: [
    AppComponent,
    LoginComponent,
    ListComponent
  ],
  imports: [
    BrowserModule.withServerTransition({ appId: 'serverApp' }),
    AppRoutingModule,
  ],
  providers: [ { provide: APP_BASE_HREF, useValue: '/angular' }],
  bootstrap: [AppComponent]
})
export class AppModule { }
</code></pre>

## 🔥 Exception or Error

<pre><code>
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'styles.7974a85c5f54bdffa3a8.css'
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'runtime.7b63b9fd40098a2e8207.js'
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'assets/favicon.ico'
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'polyfills.00096ed7d93ed26ee6df.js'
</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 11.2.13
Node: 14.20.1
OS: linux x64

Angular: 11.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.13
@angular-devkit/build-angular   0.1102.13
@angular-devkit/core            11.2.13
@angular-devkit/schematics      11.2.13
@angular/cli                    11.2.13
@nguniversal/builders           11.2.1
@nguniversal/express-engine     11.2.1
@schematics/angular             11.2.13
@schematics/update              0.1102.13
rxjs                            6.6.7
typescript                      4.1.5
</code></pre>

**Comment by alan-agius4** [comment]
Angular version 11 is no longer under support. Please update to a more recent version. If the problem persists please file a new issue with a minimal reproduction.
