### ISSUE TITLE
Unable to add the nguniversal/express-engine

### ISSUE THREAD

**Issue by ZT00OK53** [angular/universal#3192]
` ng add @nguniversal/express-engine`

Above command not working.

Getting error 

`Option "appId" is deprecated: This option is no longer used.
Cannot read properties of undefined (reading 'some')`

Angular configuration 
`
Angular CLI: 16.0.1
Node: 18.16.0
Package Manager: npm 8.7.0
OS: win32 x64

Angular: 16.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router`

Here is mypackages file

"dependencies": {
    "@abacritt/angularx-social-login": "^2.1.0",
    "@angular/animations": "^16.0.0",
    "@angular/common": "^16.0.0",
    "@angular/compiler": "^16.0.0",
    "@angular/core": "^16.0.0",
    "@angular/forms": "^16.0.0",
    "@angular/platform-browser": "^16.0.0",
    "@angular/platform-browser-dynamic": "^16.0.0",
    "@angular/router": "^16.0.0",
    "@kolkov/angular-editor": "^3.0.0-beta.0",
    "@nguniversal/express-engine": "^16.1.1",
    "ngx-countdown": "^15.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.13.0"
  },

**Comment by alan-agius4** [comment]
Can you please provide the output of `ng v`?

**Comment by ggombau** [comment]
Here it is

```
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 16.1.5
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 16.1.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.5
@angular-devkit/build-angular   16.1.5
@angular-devkit/core            16.1.5
@angular-devkit/schematics      16.1.5
@angular/cli                    16.1.5
@angular/fire                   7.6.1
@nguniversal/builders           16.1.2
@nguniversal/express-engine     16.1.2
@schematics/angular             16.1.5
rxjs                            7.5.5
typescript                      5.1.6
zone.js                         0.13.1
```

Finally I created a new project from scratch and move the files I need to my existing project

**Comment by Santoshah** [comment]
After update to Angular version 16 we need to update appId to APP_ID. Refer to https://update.angular.io/?v=15.0-16.0

```If you're running multiple Angular apps on the same page and you're using BrowserModule.withServerTransition({ appId: 'serverApp' }) make sure you set the APP_ID instead since withServerTransition is now deprecated. [Read further](https://github.com/angular/angular/blob/main/CHANGELOG.md#platform-browser-4)```

**Comment by alan-agius4** [comment]
I'm sorry, but we can't reproduce the problem following the instructions you provided.
Remember that we have a large number of issues to resolve, and have only a limited amount of time to reproduce your issue.
Short, explicit instructions make it much more likely we'll be able to reproduce the problem so we can fix it.

If the problem persists, please open a new issue following [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue).

A good way to make a minimal repro is to create a new app via `ng new repro-app` and add the minimum possible code to show the problem. Then you can push this repository to github and link it here.
