### ISSUE TITLE
Cannot change port for dev:ssr

### ISSUE THREAD

**Issue by zetti-caletti** [angular/universal#3196]
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [ ] common
- [ ] express-engine

### Is this a regression?

Don't know

### Description

PORT=4201 npm run dev:ssr does not work as described here [https://github.com/angular/universal/issues/1628](https://github.com/angular/universal/issues/1628)

npm run dev:ssr --port 4201 also does not work. It removes the port arguments and then says:
Error: Unknown argument: 4201

I think it should work like normal ng serve. Don't know why here were made some special things and nothing is documented.

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 16.1.4
Node: 16.16.0
Package Manager: npm 8.11.0
OS: linux x64

Angular: 16.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.4
@angular-devkit/build-angular   16.1.4
@angular-devkit/core            16.1.4
@angular-devkit/schematics      16.1.4
@nguniversal/builders           16.1.1
@nguniversal/express-engine     16.1.1
@schematics/angular             16.1.4
rxjs                            7.8.1
typescript                      4.9.5
</code></pre>

**Comment by alan-agius4** [comment]
Since you are using NPM to run the command to need to add the additional arguments following `-- `

```
npm run dev:ssr -- --port 4201
```

**Comment by alan-agius4** [comment]
Closing as per above.

**Comment by zetti-caletti** [comment]
Thanks @alan-agius4 . My mistake
