### ISSUE TITLE
Href not known property

### ISSUE THREAD

**Issue by splintercode** [angular/universal#321]
Look like the rendering doesn't like setting link href properties. Both property syntax and interpolation fail. Not sure if I'm doing something wrong here. I'm still trying to debug this.

Can&#39;t bind to &#39;href&#39; since it isn&#39;t a known native property (&quot;_btns&quot;&gt;
                    &lt;span *ngFor=&quot;#source of candidate.sources&quot;&gt;
                        &lt;a [ERROR -&gt;]href=&quot;{{source}}&quot; target=&quot;_blank&quot; class=&quot;btn float-right&quot;&gt;Source&lt;/a&gt;
                    &lt;/span&gt;

Can&#39;t bind to &#39;href&#39; since it isn&#39;t a known native property (&quot;_btns&quot;&gt;
                    &lt;span *ngFor=&quot;#source of candidate.sources&quot;&gt;
                        &lt;a [ERROR -&gt;] [href]=&quot;source&quot; target=&quot;_blank&quot; class=&quot;btn float-right&quot;&gt;Source&lt;/a&gt;
                    &lt;/span&gt;

**Comment by gdi2290** [comment]
this is a problem with angular2. you can use `[attr.href]="source"`

**Comment by gdi2290** [comment]
I'll update the renderer to default to an attribute when using href for the server

**Comment by splintercode** [comment]
ah thanks! Totally forgot that href is an attribute and not a property.

**Comment by ocombe** [comment]
I wonder why we don't get this error client side but we have it server side...
