### ISSUE TITLE
Setup dynamic build options for prerendering

### ISSUE THREAD

**Issue by dimakuba** [angular/universal#3216]
# 🚀 Feature request

#### What modules are relevant for this feature request?

- [x] builders
- [ ] common
- [ ] express-engine

### Description

Currently it's not possible to setup dynamic build options while prerendering, like `baseHref`, `outputPath` etc.
I've tried to run prerendering with this command to setup dynamic `baseHref`, but it doesn’t work since the argument is not defined in prerender builder's schema: `ng run <app-name>:prerender --base-href /test/`

### Describe the solution you'd like

Support dynamic build arguments: `ng run <app-name>:prerender --browser-base-href /test/`

### Describe alternatives you've considered

As a workaround, I've created custom builder for prerendering which accepts dynamic build arguments

**Comment by alan-agius4** [comment]
To change the base-href you need to set the option in the browser builder.
