### ISSUE TITLE
How to stop server side prerender for CSS

### ISSUE THREAD

**Issue by sohelkhan00000** [angular/universal#3234]
Hi All,

we are using angular prerender for server side rendering, but we want to stop prerendering for CSS.

CSS file link in index.html file on this site  [freeforonline.com](https://freeforonline.com/?utm_source=github&utm_medium=social&utm_campaign=post)

How we can prevent CSS for prerender server side ?

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
