### ISSUE TITLE
SSR on change detection in same page or same route.

### ISSUE THREAD

**Issue by test-mhrana** [angular/universal#3244]
Hi.
I make a application on angular 16.2.0  and Implemented ssr on it. But Problem is when page load from initially it's work file and render page from server. but when i change some in a page it only render from client not from server . How can i Do it From Server?

Or Can any one give me any recourse about ssr in angular which have this kind of solution .

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
