### ISSUE TITLE
Angular14 ssr page document loads very slow 

### ISSUE THREAD

**Issue by ranjeet-navsoft** [angular/universal#3245]
i have used angular14 ssr for an application. i use lazy load strategy to load my application based on requirement of my application. but when i load any of my module it holds for 5-10s .i checked the page module document also. it seems the ssr loads very slow. @angular-robot

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
