### ISSUE TITLE
Anguar 14 | Angular Universal | this._removeListenerFns.pop(...) is not a function

### ISSUE THREAD

**Issue by Raheelbutt786** [angular/universal#3254]
I'm working on Angular 14 with angular universal version 14.2.3 The project is running fine but when tried to run npm run prodbuild I get the following error

this._removeListenerFns.pop(...) is not a function.

No other errors are occurred during the build process. I'm attaching the package.json file as well for reference

`{
  "name": "customer-angular-14",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "dev:ssr": "ng run universalAngular:serve-ssr",
    "serve:ssr": "node dist/universalAngular/server/main.js",
    "build:ssr": "ng build --prod && ng run universalAngular:server:production",
    "prerender": "ng run universalAngular:prerender",
    "prodbuild": "npm run prerender && npm run compress",
    "build:prod": "ng build --configuration production --aot && ng run universalAngular:prerender:production --no-guess-routes --routes /",
    "gzipper": "gzipper",
    "compress": "gzipper compress ./dist"
  },
  "private": true,
  "dependencies": {
    "@angular-builders/custom-webpack": "^14.0.0",
    "@angular/animations": "^14.0.0",
    "@angular/cdk": "^14.2.7",
    "@angular/common": "^14.0.0",
    "@angular/compiler": "^14.0.0",
    "@angular/core": "^14.2.1",
    "@angular/forms": "^14.2.1",
    "@angular/http": "^7.2.16",
    "@angular/localize": "^11.0.9",
    "@angular/material": "^14.2.7",
    "@angular/platform-browser": "^14.2.1",
    "@angular/platform-browser-dynamic": "^16.2.1",
    "@angular/platform-server": "~11.0.1",
    "@angular/router": "^14.2.1",
    "@miaguila/common": "^10.0.2",
    "@ng-bootstrap/ng-bootstrap": "^9.1.3",
    "@nguniversal/express-engine": "^14.2.3",
    "@nguniversal/module-map-ngfactory-loader": "^8.2.6",
    "@popperjs/core": "^2.11.8",
    "@sentry/angular": "^7.7.0",
    "@sentry/tracing": "^7.7.0",
    "@types/googlemaps": "^3.43.3",
    "angular2-cookie-law": "^7.0.1",
    "angular2-signaturepad": "^4.0.2",
    "bootstrap": "^4.6.1",
    "express": "^4.15.2",
    "file-saver": "^2.0.5",
    "font-awesome": "^4.7.0",
    "gzipper": "^5.0.0",
    "jquery": "^3.7.1",
    "jquery-ui": "^1.13.2",
    "jquery-ui-dist": "^1.12.1",
    "lato-font": "^3.0.0",
    "localstorage-polyfill": "^1.0.1",
    "mock-browser": "^0.92.14",
    "ng-lazyload-image": "^9.1.3",
    "ng-payment-card": "^0.0.8",
    "ngx-card": "^0.2.4",
    "ngx-google-places-autocomplete": "^2.0.5",
    "ngx-ui-loader": "^13.0.0",
    "rxjs": "~7.5.0",
    "sessionstorage": "^0.1.0",
    "signature_pad": "^4.1.6",
    "sweetalert2": "^11.7.23",
    "tslib": "^2.3.0",
    "universal-analytics": "^0.5.3",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^14.2.12",
    "@angular/cli": "^14.2.0",
    "@angular/compiler-cli": "^14.0.0",
    "@nguniversal/builders": "^14.2.1",
    "@types/express": "^4.17.0",
    "@types/file-saver": "^2.0.5",
    "@types/jasmine": "~4.0.0",
    "@types/jquery": "^3.5.17",
    "@types/jqueryui": "^1.12.17",
    "@types/node": "^12.20.55",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~4.1.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.7.2"
  }
}
`

![image](https://github.com/angular/universal/assets/53264811/2e2324f3-2082-4b02-881b-0bbb1b962b7a)

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
