### ISSUE TITLE
fix(bootloader): test for initial start conditions

### ISSUE THREAD

**Issue by wellingWilliam** [angular/universal#328]
* **I'm submitting a ...**
- [X ] bug report

* **What modules are related to this pull-request**
- [X ] preboot

* **Do you want to request a *feature* or report a *bug*?**

report a bug

* **What is the current behavior?**

cloneNode error, is null

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

```
"dependencies": {
    "angular2": "2.0.0-beta.11",
    "angular2-universal-preview": "~0.82.1",
    "angular2-websocket": "^0.6.2",
    "express": "^4.13.4",
    "jquery": "^2.2.1",
    "preboot": "^2.0.5",
    "rxjs": "5.0.0-beta.2"    
  },
```

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

`dom.state.body ? load() : dom.onLoad(load);`

always evaluates as true.

never waits for the dom to load.

**Comment by jeffwhelpley** [comment]
@wellingWilliam OK, I am crazy busy today, but I should be able to work on this later tonight. I will let you know if I have any questions.

**Comment by wellingWilliam** [comment]
Thanks. No hurry at all. I can patch for now to continue development. You will see the bug really quick.

Uncaught TypeError: Cannot read property 'cloneNode' of null

from buffer_manaeger serverRoot being null

caused by

preboot_browser calling dom.init, which defaults window and document to {}, causing the following line to evaluate wrong on the first pass

dom.state.body ? load() : dom.onLoad(load);

I would think the following would suffice to elevate the error

Object.keys(dom.state.body).length > 0 ? load() : dom.onLoad(load);

Thanks,
William

________________________________

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/commit/389238ba8c834a46b4d420696d142802783f6111
