### ISSUE TITLE
include conventional-changelog

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#33]
it would be great to start generating a changelog via [conventional-changelog](https://github.com/ajoslin/conventional-changelog)

**Comment by gdi2290** [comment]
also consider using github releases as a better way of managing the changelog

**Comment by manekinekko** [comment]
I will take this one.

**Comment by gdi2290** [comment]
thanks :+1:

**Comment by manekinekko** [comment]
Could you tell me more about your comment above? What do you mean by using GH release to manage the changelog?

**Comment by gdi2290** [comment]
we can look into GH releases later but essentially it's the releases page for a github repo 

page https://github.com/angular/universal/releases

rather than maintaining a changelog file it does make more sense to take advantage of more features github provides such as releases. 

releases example https://github.com/blakeembrey/typescript-simple-loader/releases

To keep the repo relatively the same as angular/angular we can stick with changelog for now

**Comment by manekinekko** [comment]
Sure. We will discuss the release page sooner or later ^^

About the changelog, it is ready! I am creating the PR right now, but it is taking into account all the latest commits . Is it possible to select which commit to include in the PR?

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/pull/48
