### ISSUE TITLE
server side rendering of async child route parameters with routerLink from http response

### ISSUE THREAD

**Issue by wellingWilliam** [angular/universal#330]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [X] bug report

* **What modules are related to this pull-request**
- [X] universal

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When using async child routes and creating routerLinks within an ngFor the link provided by the server side rendering is broken. It does not append the path variable to the child route. The href of the a element created from the [routerLink] directive excludes the route parameters.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

```
<ul class="list-group">
    <li *ngFor="#directory of directories" class="list-group-item">        
        <!-- Router link -->
        <a [routerLink]="[directory.path, directory.component, {id:directory.id}]" (click)="select(directory)" class="clickable">{{ directory.name }}</a>        
    </li>
</ul>
```

https://github.com/wellingWilliam/AngularUniversalDSpaceUIPrototype.git

* **What is the expected behavior?**

The rendered html to contain the complete path including the route parameter.

<a href="/communities/8">Electronic Theses And Dissertation Community</a>

* **What is the motivation / use case for changing the behavior?**

Be able to navigate with child routes using parameters. For when JavaScript is disabled and for crawlers and indexers.

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by wellingWilliam** [comment]
I have investigated this issue and have found a JavaScript patch. 

JavaScript patch:

angular2\src\router\instruction.js

```
line 182: - (lang_1.isPresent(this.child) ? this.child._toLinkUrl() : '');
line 182: + (lang_1.isPresent(this.child) ? this.child._toLinkUrl() : '/' + this.urlPath);
```

I am aware this is not a fix. I do not have a typescript solution yet.

A SWAG would be to make the second argument non optional of the constructor for an UnresolvedInstruction.

constructor(_resolver: () => Promise<Instruction>, _urlPath?: string, _urlParams?: string[]);

**Comment by gdi2290** [comment]
@wellingWilliam can you make a pull-request in the angular repo and provide a link to this one

**Comment by wellingWilliam** [comment]
@gdi2290 I did a bit more analysis and realized that it is due to the UnresolvedInstruction component being null and does not return the urlPath to append.

https://github.com/angular/angular/issues/7752

**Comment by wellingWilliam** [comment]
Had some trouble with the cla and which github account I made the commit for the pull request angainst angular repository.

**Comment by jeffwhelpley** [comment]
@jeffbcross is there any way to know when the PR for this in core will be merged? I know there are a lot of PRs backed up so it likely won't be for a little bit, but how can we track it?

**Comment by gdi2290** [comment]
obsolete with new router but may still be a problem with NodePlatformLocation

**Comment by kuldeepkeshwar** [comment]
@jeffwhelpley @gdi2290 I'm facing the same issue and below are the packages I'm using
   ```
   "@angular/common": "2.0.0-rc.4",
    "@angular/compiler": "2.0.0-rc.4",
    "@angular/core": "2.0.0-rc.4",
    "@angular/forms": "0.2.0",
    "@angular/http": "2.0.0-rc.4",
    "@angular/platform-browser": "2.0.0-rc.4",
    "@angular/platform-browser-dynamic": "2.0.0-rc.4",
    "@angular/platform-server": "2.0.0-rc.4",
    "@angular/router": "3.0.0-alpha.8",
    "angular2-express-engine": "0.15.0",
    "angular2-universal": "0.104.5"
```

**Comment by kuldeepkeshwar** [comment]
this happens if the response from the server is taking time. I have tested it by varying the response time.it works fine for response time below ~95 milliseconds.
