### ISSUE TITLE
server side rendering of img src attribute within ngFor-collection coming from an http call

### ISSUE THREAD

**Issue by lngr** [angular/universal#331]
* **I'm submitting a ...**
- [X] bug report
- [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

the `src` attribute on the `<img>` tag is not rendered within a *ngFor if the *ngFor loops over a collection that is fetched via ajax.

If `attr.src` is used, it works just fine.

On client rendering, both methods work just fine.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

see https://github.com/lngr/angular-universal-ssr-img-bug

* **What is the expected behavior?**

server side rendering should behave like client side rendering.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.11
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
@lngr does `[src]` work for you on the client side?

**Comment by lngr** [comment]
@jeffwhelpley yes
