### ISSUE TITLE
Allow to embed custom <script> tag

### ISSUE THREAD

**Issue by Quramy** [angular/universal#332]
* **I'm submitting a ...**
feature request

* **What modules are related to this pull-request**
express-engine (or universal bootloader option)

* **Do you want to request a *feature* or report a *bug*?**
A feature

* **What is the expected behavior?**

I want to embed my `<script>....</scrpt>` to rendered HTML on server-side.

I understand that I can realize this using some Express middleware library such as https://www.npmjs.com/package/express-interceptor .
However express-engine module already has mechanism to embed some `<script>` tags into rendered HTML for preboot or configuration of System.js.
So, I think it's not bad that express-engine has an option which allows developers to extends `<script>` tags. Would you be up for that?

* **What is the motivation / use case for changing the behavior?**

I want to transfer some variables used in SSR to client-side.

For example, https://github.com/Netflix/falcor is a Universal Data fetching library and is similar to ng2 `Http` service. It works on both server-side and client-side and has cache mechanism itself.

If I customized `<script>...</script>` in rendered HTML, I can configure Falcor's cache at client bootstrapping.

I want to coding as follows:

```ts
/* server.ts */
function ngApp(req, res) {
  let model: Falcor.Model = createModel(req, res);
  res.render('index', {
    directives: [App],
    providers: [...SERVER_SIDE_PROVIDERS, provide(Falcor.Model, {useValue: model})],
    
    /* the option of this feature request */
    additionnalScripts: [
      `var __cache__ = ${JSON.stringify(model.getCache())};`
    ]

  });
}

app.use('/', ngApp);
```

```html
<!-- rendered HTML -->
<html>

  <!-- Application body -->

  <script>
    var __cache__ = {
      /* variables used in server-side-rendering */
    };
  </script>
</html>
```

```ts
/* client.ts */

bootstrap(App, [
  provide(Falcor.Model, useValue: new Falcor.Model({
    cache: window['__cache__']
  }) 
]);
```

**Comment by Quramy** [comment]
What I want to do will be realized by cache transfer mechanism at #338 .

**Comment by gdi2290** [comment]
The prime cache feature in that issue us for http cache while this one is a general cache outside of http.

**Comment by Quramy** [comment]
@gdi2290 . I got it.

Will you add feature of the "general cache outside of http"?

And I found #271, which you opened.  It seems `ngCache` is a general cache service. 
It will me meet my goal?

**Comment by gdi2290** [comment]
Yup, if there was NgCache then you would make a simple wrapper around the Falcor model
