### ISSUE TITLE
CSS doesn't apply when using server-only-apps

### ISSUE THREAD

**Issue by jesussobrino** [angular/universal#342]
**I'm submitting a ...**
- [x] bug report

I don't know if you already know this issue, but I'm trying to explain it as best as I can.

When I try to apply any CSS styles to "server-only-apps", that styles never appears. So the CSS classes don't apply.

**Github repo** 

In order to make it easier to understand I forked universal-starter and I added "styles" attribute to "ServerOnlyApp" Component, but any styles are applied.

https://github.com/jesussobrino/universal-starter/commit/7c2df9f8f760c4a7a7ac455e2ebca525f737bbff

**Results:**

"new-color" class is not applied:

![angular-universal-0 85 1_sytles_not_applied](https://cloud.githubusercontent.com/assets/4729067/14278326/5be0ed76-fb27-11e5-88e8-e2ae37360002.jpg)

**Environment:**

- Angular version: 2.0.0-beta.13
- Angular-universal version: 0.85.1
- NodeJS version: 5.10.0
- Browser: [Chrome 49.0.2623.110 ]
- Language: [TypeScript]

Thanks for this amazing work!
Jesús.

**Comment by MarkPieszak** [comment]
Tested it myself, it seems to be ignoring all `styles : []` located in the `server-only-app` Folder. (In our case, the `html.component.ts` file.

Looking into it more right now.

**Comment by ocombe** [comment]
Yup that's a real problem because the web page has no style until the client side code is executed, which means that it's unusable.
In the meantime, if you use webpack, you can require your style files outside of the `@component` (at the beginning of your file for example).

**Comment by gdi2290** [comment]
added via https://github.com/angular/universal/commit/e8befd4d0843ffb51dc2b987fe56a37cd38c9d3e
renamed via https://github.com/angular/universal/commit/d804d7a15d7deb2d937e41b869cc656a0aa0856c

in the `<head>` of your `html` component include the `<universal-styles></universal-styles>` directive

```html
  <head>
    <title>{{ seo.title }}</title>
    <meta charset="UTF-8">
    <meta name="description" content="Angular 2 Universal">
    <meta name="keywords" content="Angular 2,Universal">
    <meta name="author" content="PatrickJS">

    <link rel="icon" href="data:;base64,iVBORw0KGgo=">

    <universal-styles></universal-styles>

    <base [attr.href]="seo.baseUrl">


  </head>
<body>
<app></app>
</body>
```

**Comment by MarkPieszak** [comment]
@gdi2290 So this is now a *required* component for someone who wants to Universal right? Just trying to keep track of everything needed to help with documentation!

**Comment by ocombe** [comment]
Yes, I think it should eventually be added automatically

Le ven. 15 avr. 2016 20:28, Mark Pieszak <notifications@github.com> a
écrit :

**Comment by gdi2290** [comment]
@MarkPieszak it's required only if you use an html component
