### ISSUE TITLE
Support making HTTP requests with relative URLs

### ISSUE THREAD

**Issue by SteveSandersonMS** [angular/universal#348]
As discussed on slack, currently you can't do this inside an Angular 2 component executing on the server:

    http.get('/api/my-json')

... because on the server, the URL isn't resolved against `BASE_URL`. Instead you have to give an absolute URL.

For consistency with client-side code, please resolve relative URLs against the base URL. Thanks!

**Comment by MarkPieszak** [comment]
@SteveSandersonMS Are you trying to implement Universal within .NET Core with Kestrel or anything? Very curious to see how you're doing all of that. I've only been able to play around with Universal in a Node environment so far.

**Comment by gdi2290** [comment]
I added `ORIGIN_URL` back but it needs to be provided as a platformProvider
```
res.render('index', {
   directives: [App],
   platformProviders: [
    provide(ORIGIN_URL, {useValue: 'http://127.0.0.1:3000'}),
    provide(BASE_URL, {useValue: '/examples/template_url'}),
  ],
  providers: [
    provide(REQUEST_URL, {useValue: req.originalUrl}),
  ],
  async: true,
  preboot: false
})
```

**Comment by gdi2290** [comment]
BASE_URL is referencing APP_BASE_HREF so they're the same token

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/20debdbc42afed2c6312601bc031c518f5139a59

**Comment by MarkPieszak** [comment]
Nice one man 👍
