### ISSUE TITLE
feat: BroccoliJS prerender plugin 

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#356]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Feature

I've started work on this for an app-specific broccoli plugin to work with [Angular CLI](https://github/angular/cli). I intend to convert my plugin into a general purpose broccoli plugin and submit here.

**Comment by gdi2290** [comment]
here's the code that's needed
```typescript
import {Bootloader, BootloaderConfig} from 'angular2-universal';

    const _options = options;
    const _template = template;
    const _Bootloader = Bootloader;

    let bootloader = _options.bootloader;
    if (_options.bootloader) {
      bootloader = _Bootloader.create(_options.bootloader);
    } else {
      _options.template = _options.template || _template;
      bootloader = _Bootloader.create(_options);
    }

    bootloader.serializeApplication() // returns a promise with the html
```

**Comment by jeffwhelpley** [comment]
@jeffbcross you created this for your presentation, right? If so, can you submit a PR to get it into the universal repo?

**Comment by gdi2290** [comment]
this is done already
