### ISSUE TITLE
Dev workflow for universal repo

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#357]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ ] bug report
- [X ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Errors and warnings when trying to build. General confusion by team members.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

Code away without much overahead

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
Most of this is all set with #361 & #364 that have been merged.

Currently a dev can pull down the Universal repo fresh, run `npm run install:all` & this will do everything needed to get them going. (Takes ~10min to install/build/compile all the modules) It also waits and then installs/compiles the examples folder.

Might be able to close this one out now. I'll add some documentation to the Contributing doc here in a second.
