### ISSUE TITLE
Fix Repo build issues on Windows 7

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#369]
* **I'm submitting a ...**
 bug report

**Modules fixed so far**
[ ] express-engine
[ ] grunt-prerender
[X] gulp-prerender
[X] hapi-engine
[X] preboot
[x] universal
[ ] webpack-prerender

- OS:  [ **Windows** ]

-----

####  Working on the fix for this now. 

> Multiple things such as `rm -rf` `tsc || true` etc break on windows since they aren't allowed.
** ^ Fixed so far **

**Comment by gdi2290** [comment]
can you make a pull-request?

**Comment by MarkPieszak** [comment]
Will do, working on it.  Got the rm -rf and pipe issue figured out, blowing up on `tsc` for some unknown reason

**Comment by MarkPieszak** [comment]
Partially waiting on results from typescript and npm people https://github.com/npm/npm/issues/12412

**Comment by jeffwhelpley** [comment]
@MarkPieszak please test with the latest code and let me know what the current status is here.

**Comment by MarkPieszak** [comment]
Will do. I got some things fixed with `rimraf` but the others could be `npm` lifecycle issues with Windows 7, been trying to talk with the npm team more to figure it all out. @jeffwhelpley 

I'll try and resolve this in the next few days.

**Comment by MarkPieszak** [comment]
Fixed via #434
