### ISSUE TITLE
npm install angular2-universal@0.98.1 fail

### ISSUE THREAD

**Issue by tamascsaba** [angular/universal#370]
npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants zone.js@^0.6.10
npm ERR! peerinvalid Peer angular2-universal-polyfills@0.4.1 wants zone.js@0.6.11 - 0.6.100
npm ERR! peerinvalid Peer angular2-universal@0.98.1 wants zone.js@0.6.11 - 0.6.100

**Comment by gdi2290** [comment]
can you run `npm prune` and `npm install`

**Comment by gdi2290** [comment]
or update zone.js if you included it

**Comment by tamascsaba** [comment]
thx, the quick answer :+1:
