### ISSUE TITLE
Checkbox rendering issue

### ISSUE THREAD

**Issue by barbatus** [angular/universal#372]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
bug report

* **What modules are related to this pull-request**
universal

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**

Renders checkboxes with `checked="false"`, i.e.,
`<input type="checkbox" [ngModel]="isChecked">` will be rendered as `<input type="checkbox" checked="false">` by default.
Don't see this behavior in angular2 in a browser.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

A demo app
https://github.com/barbatus/angular2-meteor-universal/tree/master/examples/app

Deployed here http://ng2-ssr.herokuapp.com/todo
(you can see in the initial HTML all checkboxes checked)

* **What is the expected behavior?**

Rendering w/o `checked="false"`

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.15
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
@jeffwhelpley Any idea? Looks like it could be Preboot related? 
Seems like during the playback it's unselecting all the checkboxes so the model must be coming back empty.

**Comment by jeffwhelpley** [comment]
Thanks, @MarkPieszak. Yes, this is actually one of those things where the underlying issue may be a bit more complex than it seems. Let me do a little investigation and I will post an update by tomorrow.

**Comment by MarkPieszak** [comment]
Oh great, I figured! Just wanted to get it on your radar just incase.

**Comment by jeffwhelpley** [comment]
@MarkPieszak @barbatus We fixed this issue with a flurry of other changes this week. Please get the latest which uses Angular RC 1 and let me know if you still see any issue.
