### ISSUE TITLE
Rendering issue when routing is used

### ISSUE THREAD

**Issue by barbatus** [angular/universal#377]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- bug report

* **What modules are related to this pull-request**
- universal

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**

Thanks for the awesome library! 

`universal/src/node/bootloader.ts` doesn't wait until Angular2 routing resolves current path to a associated component which leads to this component is not rendered.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

There is a simple Meteor app https://github.com/barbatus/angular2-meteor-universal/tree/master/examples/app, which is a demo of an Universal wrapper for Meteor (https://github.com/barbatus/angular2-meteor-universal).
The problem particularly is in this [part](https://github.com/barbatus/angular2-meteor-universal/tree/master/examples/app/imports/parties), which uses routing.
It's deployed and can be checked here http://ng2-ssr.herokuapp.com/parties.

Some notes:
If change `<router-outlet />` in the app template to a particular component instead, it starts rendering it on the server properly.
if I make use of `then(waitRouter)` (i.e. uncomment this line  https://github.com/angular/universal/blob/8e0549405c591e8c6044638c97de72b15b91e7d3/modules/universal/src/node/bootloader.ts#L264), rendering starts working almost properly (though not all binding applied).

This renderer for Meteor itself is pretty simple and based on the code for Express and Hapi, 
please check it [here](https://github.com/barbatus/angular2-meteor-universal/blob/master/modules/server_renderer.ts).

* **What is the expected behavior?**

Bootloader waits until routing is done and renders resolved component properly.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.15
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
the problem might be Meteor Promise not being tracked by zone.js
https://github.com/barbatus/angular2-meteor-universal/blob/master/modules/server_renderer.ts#L7...L14

**Comment by barbatus** [comment]
@gdi2290 thanks for the suggestion. Ok, I played around with it more.
Even I remove MeteorPromise, which means the one from `zone-node.js` is set globally, issue with the routing is still there.
And for this todo [sample](https://github.com/barbatus/angular2-meteor-universal/tree/master/examples/app/imports/todo), which is quite simple, I start getting "your application is taking longer than 2000 Zone turns",

BTW, this [fixStable](https://github.com/angular/universal/blob/master/modules/universal/src/node/bootloader.ts#L134) looks quite tangled, it's not clear right away what's supposed to do.

**Comment by gdi2290** [comment]
the application is taking longer than 2000 to render

**Comment by gdi2290** [comment]
you can set maxZoneTurns to 10000 if you like or higher

**Comment by barbatus** [comment]
As I understand zone-aware promise references to the global zone (`Zone.current`) internally,
at the same time Angular2 has its own fork of the zone, it sets microtasks with the help of it.
So you are sure that checking of `ngZone.hasPendingMicrotasks` is enough in the fixStable?

**Comment by Lavan** [comment]
I've got an issue that I believe is related. This [Plunk](http://plnkr.co/edit/8fYZGj3vfl00B0bvKNYK?p=preview) shows a form that works nicely in Plunker, but when it is prerendered using angular-universal the submit event won't fire.

As it's a bit difficult to prerender using plunker you'll have to do some copy/paste to test it.

If I wrap the form in `ngIf ` and a timeout the bindings will be restored correctly.

My setup is based on the [universal-starter](https://github.com/angular/universal-starter) package.

**Comment by gdi2290** [comment]
it's not enough. it all depends on how many async calls are made that aren't tracked by node.js (which may be a lot)

**Comment by gdi2290** [comment]
@Lavan can you fork the repo and reproduce it then drop a link?

**Comment by barbatus** [comment]
@gdi2290 In my case it's only 3-4 calls to read template files, everything else is synchronous.
Anyways, what would you recommend to fix that routing issue?
BTW, I have `then(waitRouter)` uncommented and use `setTimeout(f, 200)` in `waitRouter`, it works perfectly.

**Comment by Lavan** [comment]
@gdi2290 Here, try this one. [https://github.com/Lavan/universal-starter/tree/issue377](https://github.com/Lavan/universal-starter/tree/issue377).

3 versions of the same code on the same page:

1. Not working with prerender. Structured as in the [Angular 2 NgForm documentation](https://angular.io/docs/ts/latest/api/common/NgForm-directive.html).
2. Working with prerender. Replaced NgSubmit with click. It works but I have no idea if there are any weird sideeffects.
3. Working with prerender. Horribly ugly as it removes and adds the elements after load.

If you browse to `http://server/src/index.html` to avoid prerendering you'll see that the first version works as it should.

**Comment by gdi2290** [comment]
obsolete
