### ISSUE TITLE
update beta 16

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#378]

**Comment by MarkPieszak** [comment]
Do you need all Modules / etc need the upgrade? Trying it now to see if it all still works

**Comment by JoshAntBrown** [comment]
Seems as though DirectiveResolver that's used by `./modules/universal/src/node/helper.ts` has moved from `angular2/core` to `angular2/compiler`. Just something I noticed when I was running code on a colleagues machine which was using beta 16. 

Out of curiosity, what is the general approach to universal when angular2 introduces breaking changes like this?

**Comment by MarkPieszak** [comment]
@JoshAntBrown Do you mean when updating Universal?

**Comment by gdi2290** [comment]
there's also a change with the Location type that was moved into angular2/platform/common

**Comment by JoshAntBrown** [comment]
@MarkPieszak Yeah, so I was tempted to give this a go and put in a pull request to give beta.16 support but obviously just changing the places it referenced things from would break all support for pre 16 versions. 

So what's the general approach to updating universal when angular2 introduces breaking changes?

**Comment by gdi2290** [comment]
I updated the repo to beta.17 will publish soon
