### ISSUE TITLE
express always render the same view

### ISSUE THREAD

**Issue by Vloz** [angular/universal#379]
* **I'm submitting a ...**
- [x] bug report (or support request, how can i know?)

* **What modules are related to this pull-request**
- [x] express-engine

* **Do you want to request a *feature* or report a *bug*?**
bug (i guess)

* **What is the current behavior?**
I cant make express to serve another view, it always serve the first called view. I may have miss something in the params... :disappointed: 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

From the Angular 2 Universal Starter:
https://github.com/Vloz/Issue_ngUMultipleViews/commit/579bcf6e087ce43788380deb36003e18804cd4e1

* **What is the expected behavior?**

The "We are in index *" header should change whether "http://localhost:3000/" or http://localhost:3000/foo" is requested.

* **What is the motivation / use case for changing the behavior?**

Bring the ability to separate admin/public clients for instance..?

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.15
- Browser: [Chrome 50 ]
- Language: [TypeScript 1.8 ]
- OS:  [Linux]
- Platform: [ NodeJs]

**Comment by gdi2290** [comment]
multiple apps aren't supported with the express-engine so you would have to manually manage it.

```typescript
const baseUrl = '';

var app1 = bootloader({
  template: 'your index.html',
  directives: [ App ],
  platformProviders: [
    provide(ORIGIN_URL, {useValue: 'http://localhost:3000'}),
    provide(BASE_URL, {useValue: baseUrl}),
  ],
  async: true,
  preboot: false // { appRoot: 'app' } // your top level app component selector
});

var app2 = bootloader({
  template: 'your index.html',
  directives: [ App ],
  platformProviders: [
    provide(ORIGIN_URL, {useValue: 'http://localhost:3000'}),
    provide(BASE_URL, {useValue: baseUrl}),
  ],
  async: true,
  preboot: false // { appRoot: 'app' } // your top level app component selector
});

function ngApp1(req, res, next) {
  let url = req.originalUrl || '';
  app1.serializeApplication([
    provide(REQUEST_URL, {useValue: url}),
    NODE_ROUTER_PROVIDERS,
    NODE_HTTP_PROVIDERS,
  ])
  .then(html => {
    req.send(html);
    next();
  });
}

function ngApp2(req, res, next) {
  let url = req.originalUrl || '';
  app2.serializeApplication([
    provide(REQUEST_URL, {useValue: url}),
    NODE_ROUTER_PROVIDERS,
    NODE_HTTP_PROVIDERS,
  ])
  .then(html => {
    req.send(html);
    next();
  });
}

app.use('/foo', ngApp1);
app.use('/bar', ngApp2);
```

**Comment by Vloz** [comment]
Seem to work now (as intended in my first post), probably fixed by ianbelcher's thread.
