### ISSUE TITLE
Git submodule update failed!

### ISSUE THREAD

**Issue by manekinekko** [angular/universal#38]
Hi,

I have some free time and decided to contribute ^^
However, when trying to npm install, I had some issues with git not able to clone the angular submodule (see screenshot below).

![ng2-universal-git-submodule-issue](https://cloud.githubusercontent.com/assets/1699357/9048592/97a3871e-3a3a-11e5-8731-d42fb7cfcffc.png)

My git version is **2.3.5**

But good news is I fixed this issue by adding `git submodule init &&` at the beginning of the NPM `angular-submodule` task.

I will submit the corresponding PR soon.

**Comment by gdi2290** [comment]
fixed via #39
