### ISSUE TITLE
preboot focus fixes

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#390]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [X] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

In some cases, when focus is transferred from server to client, there is a flash due to the fact that focus is unset and then reset. Also, we need specific behavior for mobile.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

have cursor in text box during transfer from server to client

* **What is the expected behavior?**

Server to client view transition should be seemless in all environments

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
@jeffwhelpley is this fixed with preboot 4?

**Comment by gdi2290** [comment]
done in 1.0.4 with angular rc5/rc6/rc7 support
