### ISSUE TITLE
Enable Angular Universal with a Go backend

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#391]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.
- **I'm submitting a ...**
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [X] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**

Feature
- **What is the current behavior?**

Doesn't work with Go
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

So people that use Go can utilize Angular Universal.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
If you are interested in helping out in this effort email me at jeff at gethuman dot com. We are organizing a meeting between all interested parties to kick off this effort.

**Comment by owenhaynes** [comment]
This will nice to have. Nodejs just does not fit into our current environment set up.

**Comment by ishitatsuyuki** [comment]
Instead for do such a secret meeting, I will propose my solution here: simply use a JS interpreter inside go. Angular itself is JS, and we don't want to mess twice.
There's one using this solution for React: see [here](https://github.com/olebedev/go-starter-kit).
I believe Angular universe is capable for this as well. We currently have Otto as a Go, sandboxable interpreter or V8 bindings as the rapid way.

**Comment by pxwise** [comment]
Has anyone prototyped this?

**Comment by dneeleman** [comment]
Would be very interested in this!

**Comment by Toxicable** [comment]
Closed in favour of https://github.com/angular/universal/issues/1000

**Comment by N1nJaC0d3** [comment]
we need this
