### ISSUE TITLE
prototype hydration as alternative to server/client buffering

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#392]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.
- **I'm submitting a ...**
- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [X] preboot
- [ ] universal-preview
- [X] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**

Feature
- **What is the current behavior?**

Doesn't use this feature
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**

To see whether there are performance gains with using a hydration approach instead of the current server/client buffering. Previously hydration was less performant, required more code and would be less stable since it would rely on being in sync with core logic. However, with the API starting to stabilize we should revisit.
- **Please tell us about your environment:**
- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
@jeffbcross @tbosch we would like to have a quick discussion about this. It came up at ng-conf. We discussed hydration early on in this project and decided it wasn't a good idea at that time. However, we may want to revisit.

**Comment by gdi2290** [comment]
I think this might be easier with the new renderer

**Comment by jeffwhelpley** [comment]
@tbosch this is just a reminder per our discussion at AngularConnect to keep this in the back of your mind while you are tinkering around. Is there a way to hydrate the client on top of a server view? After a couple more fixes and the implementation of NgCache, we will have the current preboot buffer driven approach working well, but hydration could offer even more benefits. Just something to think about.

**Comment by tbosch** [comment]
Will do!

**Comment by gdi2290** [comment]
closed for https://github.com/angular/angular/issues/13446
