### ISSUE TITLE
move universal under @angular in npm and with package name

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#393]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [X] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Bhushan001** [comment]
@jeffwhelpley will there be major changes in universal as angular2 has moved to rc-state now?

**Comment by jeffwhelpley** [comment]
@Bhushan001 we are lagging behind core in terms of maturity. While core is at release candidate, you should still consider Universal right this second at Beta stage. We hope to make a bigger push in the coming weeks, though and hopefully will be able to announce Universal is production ready close to the core Angular 2 full release, but we'll see.

**Comment by timruffles** [comment]
@jeffwhelpley would you recommend steering clear of detailed discussion of universal's APIs in talks/teaching materials till then, given the beta status?

**Comment by jeffwhelpley** [comment]
Well, @timruffles,  first we are definitely changing the namespace at some point in the coming weeks to the standard. However, that should be a simple search and replace for the import namespace without any changes to the actual API. However, just be aware that before we declare Universal production ready, we likely will make some more serious changes to the API. It is something we have only started to discuss and we will try to keep backward compatibility as much as we can. I will make a note here when we have more details but feel free to ping me on gitter/slack/whatever if you have specific questions on that effort.

**Comment by gdi2290** [comment]
dup of https://github.com/angular/universal/issues/444
