### ISSUE TITLE
Angular Universal CLI docs generator

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#394]
Need to finish putting up the microsite and then create separate issues for each specific section needed so other people can jump on. Also have information about the process for how other people contribute to the docs.

**Comment by manekinekko** [comment]
@jeffwhelpley I'm taking over this issue. Tell me all what you know sir :)

**Comment by thomasjosephgreco** [comment]
@manekinekko @jeffwhelpley it seems the quickstart on universal.angular.io is using the `ambient` flag however I think that has been depreciated for `global`. You can check out what I am talking about [here](https://universal.angular.io/quickstart/).

**Comment by manekinekko** [comment]
thanks @thomasjosephgreco we'll update the doc.

**Comment by jeffwhelpley** [comment]
@manekinekko I am away this week, but just a heads up that we are going to kick off this effort again next week and would love to get your help. We will chat on slack.

**Comment by gdi2290** [comment]
will be supported in ng4 
https://github.com/angular/angular/issues/13822
