### ISSUE TITLE
Browser errors in latest rc1 build

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#395]
* **I'm submitting a ...**
- bug report

![screen shot 2016-05-07 at 6 55 37 pm](https://cloud.githubusercontent.com/assets/2574412/15095069/5363a96e-1485-11e6-9f22-a0daf9d29d7a.png)

Got latest this morning since the rc1 updates/etc, looking into it now just wanted to get it on the radar.

**Comment by zoechi** [comment]
Your code probably needs to be updated to rc.1 but hard to tell without a repo case. Please create a Plunker that demonstrates the issue.

**Comment by zoechi** [comment]
Sorry, thought this issue was from another GitHub repo

**Comment by jeffwhelpley** [comment]
@gdi2290 I am slammed today, but this is an important one. Can you look at this when you get a chance?

**Comment by MarkPieszak** [comment]
It looks like errors triggering inside Angular itself, I can't seem to pin-point when it's occurring though. It seems to be on the browser-side though, once things load up.

**Comment by MarkPieszak** [comment]
I think this issue has gone away, I'll close this one out.

**Comment by gdi2290** [comment]
this was a problem with our build script thing we created that injects the systemjs scripts. I updated it recently to get the examples working
