### ISSUE TITLE
create `isNode` (or `isServer`) and `isBrowser`

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#397]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [x] universal
- [ ] webpack-prerender

return `true` or `false` per code split path

**Comment by jeffwhelpley** [comment]
Nooooooooooooooooooooo.

OK, so at the very least can we not expose this feature unless users set a config flag? I understand that we need this for certain low level libraries when we don't have control over the user bootstrap, but we should discourage the use of this in most cases.

**Comment by gdi2290** [comment]
we should discourage use of it but we do need escape hatches. It's easier for demos and starting off with Universal and we can recommend how to refactor services/etc into the correct universal patterns

**Comment by JohnGorter** [comment]
Patrick, 

Talked about taking on this feature, tell me (here or slack) what needs to be done :-)

**Comment by jeffwhelpley** [comment]
Actually, to this point, I think during our last call, @gdi2290, you seemed to have an idea of how you wanted to implement this, but we never said it explicitly. There are really two approaches here:

1. Have user pass in some value to Universal at build time that specifies the environment.
2. Have Universal infer the environment based on some global known factor (ex. if (!window))

It would seem like the first option is preferable which would mean we would be modifying the Universal API to accept in an environment value which is then stored at the platform level and is accessible through getters in the Universal API. If that lines up with what you are thinking, then the only question is whether the user should be able to check arbitrary environment values (ex. if (universal.isEnvironment('server'))) or if we want to just have a boolean isNode/isBrowser. I think you were leaning toward the later on this one, but that approach is less flexible.

**Comment by gdi2290** [comment]
I ended up doing it via https://github.com/angular/universal/commit/2bdeb3294af329721c5253bab4c7390b8c4e8da0
