### ISSUE TITLE
Create initial e2e test for a todo app

### ISSUE THREAD

**Issue by tbosch** [angular/universal#4]
Using `protractor` npm module. Should test:

- Render a page on server
- Click on a button that that would change the ui (e.g. remove an item from a list)
- Assert that the change was done correctly

To make the test more robust, we might want to defer the client bootstrap until we click a special extra button, so we are sure we can do asserts on the server rendered version and then on the version that was replaced by the client.

**Comment by jeffwhelpley** [comment]
We are going to have several modules in this repo that may potentially be separated out into their own repos once things have stabilized. So although each module should have their own test directory, it seems like we should create a root level test directory for the full e2e tests that cover everything working together.

**Comment by tbosch** [comment]
These e2e tests could be part of the examples...

**Comment by gdi2290** [comment]
closed via https://github.com/angular/universal/commit/114bd88d8d63146b27ffa9d3b3ed7d99aa4408a7

current tests for client/server+client:
 * complete todo
 * create new todo
 * remove todo
 * complete all and clear completed

current tests for server:
 * check title
 * check if todo app is in body
 * check if todo was rendered
