### ISSUE TITLE
universal.angular.io: Quickstart page's text gets cut off on narrow screens 

### ISSUE THREAD

**Issue by jffry** [angular/universal#400]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

### **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

### **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender
- [X] docs

### **Do you want to request a *feature* or report a *bug*?**

Reporting a bug

*(btw is this question intentionally a duplicate of the first "I'm reporting a..." one?)*

### **What is the current behavior?**

On the Quickstart page (https://universal.angular.io/quickstart/), the text gets cut off on the right side.  Can't scroll right to read it.  I think this is a combination of the wide code snippets, the various `max-size`s on the content, along with the `overflow-x:hidden` style applied to `.mdl-layout__content`

### **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Go to https://universal.angular.io/quickstart/ on a mobile device, or just make your desktop browser really skinny.

### **What is the expected behavior?**

The text should wrap, or (less optimally) I should be able to scroll to the right to view it.

### **What is the motivation / use case for changing the behavior?**

People might try to read the Quickstart page on their phone (e.g. during a conference, or at a meet-up) and not being able to read half the text makes it hard to learn about.

### **Please tell us about your environment:**

- Angular version: n/a
- Browser:
  * ❌ Broken on Latest Chrome on Android 6.0.1
  * ❌ Broken on Latest Chrome (v50) on latest OSX
  * ❌ Broken on Latest Firefox (v46) on latest OSX
  * 🆗 Not Broken on Latest Safari (v9.1) on latest OSX
- Language: N/A
- OS: All?
- Platform: N/A

### **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Screenshot:

![overflow-on-android](https://cloud.githubusercontent.com/assets/602773/15166915/9e2e3068-16f1-11e6-8df8-7bb86e7008b1.png)

**Comment by jeffwhelpley** [comment]
Oh, yeah, that is ugly. Thanks for posting this @jffry. I am going a major revamp of the docs this weekend so will fix this then and post something here once they are good.

**Comment by manekinekko** [comment]
@jeffwhelpley I sent the fix here (https://github.com/ericjim/universal.angular.io/commit/e914909543ab891b8d0ed53f81e5e07ca2b2a008) It needs to be merged and deployed to firebase.

**Comment by gdi2290** [comment]
I think this is done. closing
