### ISSUE TITLE
Include preboot 4 for engine wrappers and universal

### ISSUE THREAD

**Issue by jeffwhelpley** [angular/universal#407]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [X] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [X] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Bug because if you have network throttling on now, preboot is not working.

* **What is the current behavior?**

Right now, with network throttling, preboot takes too long to download and start.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Simply turn on network throttling.

* **What is the expected behavior?**

When we inline, then it will run as soon as the server view is visible.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-beta.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .Net | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by JohnGorter** [comment]
would it be preferrable to inline the js aswell as the css for preboot in the express engine? My guess is that they both need to be inlined....

**Comment by jeffwhelpley** [comment]
Yep. Both. This will add some page weight but we will deal with that issue in the next preboot refactoring.

**Comment by gdi2290** [comment]
I updated the issue to reflects changes for preboot 4.0 that is inline by default

**Comment by gdi2290** [comment]
done in 1.0.4 with angular rc5/rc6/rc7 support
