### ISSUE TITLE
feat(Jsonp): add support for JSONP

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#409]
Create a binding for JSONP. Should behave similarly to the browser version, without the convenience of placing a `<script>` tag in the page.

**Comment by gdi2290** [comment]
for the jsonp we probably can use `new Function` wrapping `Http#request`
```es6
var responseFactory = new Function('callback', 'return ' + jsonpResponse)
var responseJson = responseFactory(json => json)
```
or
```es6
var jsonpResponse = 'callback({json: {}})';

var responseFactory = new Function('', 'function callback(json) { return json } \n return ' + jsonpResponse)

var responseJson = responseFactory()
```

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/4575cb0236749a1f2ee9a17f7291e8b539136a30
