### ISSUE TITLE
Does not work with new router

### ISSUE THREAD

**Issue by vangheem** [angular/universal#410]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Can not use with the new angular 2 router.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Any project with new router. The starter kit, changing to new router will cause this.

* **What is the expected behavior?**
To work with new router.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: [all  ]
- Language: [all ]
- OS:  [all]
- Platform: [NodeJs ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

I think the project just needs to update import locations.

**Comment by Splaktar** [comment]
Another new router has emerged: http://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

**Comment by gdi2290** [comment]
we were waiting for the latest router just released

**Comment by kenhahn85** [comment]
@gdi2290, do you have a ballpark estimate on when router 3.0 support will ship?

**Comment by ivanmayes** [comment]
+1 need the new router support

**Comment by gdi2290** [comment]
Alright, I updated universal to rc2 rc3 the other day with the new router is support. Here's the updated starter with it
https://github.com/angular/universal-starter
