### ISSUE TITLE
Using host properties throws EXCEPTION: Not implemented

### ISSUE THREAD

**Issue by rifmj** [angular/universal#412]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**
- [x] express-engine
- [x] universal

* **What is the current behavior?**
When using host properties on components or directives server throws "EXCEPTION: Not implemented"

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
This code is not working, to fix it I need to comment host property
```
@Directive({
  selector: '[routerLink]',
  inputs: ['routeParams: routerLink', 'target: target'],
  host: {
    '(click)': 'onClickWithEvent($event)',
    '[attr.href]': 'visibleHref',
    '[class.router-link-active]': 'isRouteActive'
  }
})
```

```
@Component({
  template: require('./blog-article-page.component.jade')(),
  host: {'class': 'ng-animate page-container'}
})
```

* **What is the expected behavior?**

I can use host properties in components and directives, and they are properly rendered (exception not thrown)

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: all
- Language: TypeScript 1.7
- OS: all
- Platform: NodeJs

**Comment by MarkPieszak** [comment]
Are you manipulating the DOM directly from these `host` functions? I'll try and test using `Host`, haven't tried this yet!

**Comment by rifmj** [comment]
@MarkPieszak, I found origin of this problem. It's not working only with 'ng-animate' class added as host attribute.

**Comment by MarkPieszak** [comment]
Ahh well that would make more sense I guess! Either way good to know, something to look into either way.

**Comment by manekinekko** [comment]
@rifmj can you use a node debugger (node-inspector for instance) and provide us the a trace call so we call locate which method is throwing this exception?

**Comment by jeffwhelpley** [comment]
@rifmj is this still an issue with all the latest updates? I am closing for now, but if you identify it is still a problem, I will re-open this and start investigating it again.
