### ISSUE TITLE
recreate Parse5Adapter with parse5 2.0

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#413]
update and replace Parse5Adapter

**Comment by MarkPieszak** [comment]
Assign to me I'll take a look this weekend 👍

**Comment by gdi2290** [comment]
I can assign the issue to you after we get you in the org. If you run into problems just ping me

**Comment by MarkPieszak** [comment]
done via https://github.com/angular/universal/pull/424 - all demos working

**Comment by gdi2290** [comment]
done in 1.0.4 with angular rc5/rc6/rc7 support
