### ISSUE TITLE
Unable to configure Angular Universal with Angular Cli project.

### ISSUE THREAD

**Issue by liongoncalves** [angular/universal#418]
The documentation is kinda out of date. And is not working on an Angular-cli generated project.

**Comment by MarkPieszak** [comment]
A lot of things are still in the works.
Check out https://universal.angular.io/ for a little more info on how to get it started.

Also, you can use the [universal starter repo](https://github.com/angular/universal-starter) as a good example on how to get started with it.

Universal isn't set up for the new Router just yet, that would probably be why it's not integrating with a `cli` project just yet.

**Comment by mwaaas** [comment]
How will angular universal work with nginx

**Comment by vforv** [comment]
It would be great if you someone can create blog post or something that will show how to add universal to angular-cli projects... A lot of us use angular-cli.
