### ISSUE TITLE
upgrade npm scripts to a task manager

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#42]
npm scripts can only go so far and we should also handle different environments (windows/osx). Being able to clean the repo on a failed install would be handy to prevent unintended errors. Expanding the current gulpfile.js with tasks from package.json would be ideal. For example `rm -rf` doesn't work in Windows which is why we have the `gulp-rimraf` plugin

**Comment by manekinekko** [comment]
I will take this one.

**Comment by manekinekko** [comment]
For cleaning purposes, I'd suggest the [del](https://github.com/sindresorhus/del) gulp pugin as it supports globbing patterns. Plus, the `gulp-rimraf` seems to be deprecated. 
What do you think?

**Comment by gdi2290** [comment]
sounds good

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/pull/58
