### ISSUE TITLE
App crashes on multiple concurrent requests

### ISSUE THREAD

**Issue by btrigueiro** [angular/universal#425]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Concurrent requests start to log errors like the ones below and memory consumption increases until the process runs out of memory and crashes.

```
ngOnStable Error: [TypeError: Cannot use 'in' operator to search for 'ngOnStable' in null]
preboot Error: [TypeError: Cannot use 'in' operator to search for 'preboot' in null]
Rendering Document Error: [TypeError: Cannot read property '0' of undefined]
ngOnRendered Error: [TypeError: Cannot use 'in' operator to search for 'beautify' in null]
```
```
<--- Last few GCs --->

  165155 ms: Scavenge 1375.0 (1458.0) -> 1375.0 (1458.0) MB, 4.2 / 0 ms (+ 1.0 ms in 1 steps since last GC) [allocation failure] [incremental marking delaying mark-sweep].
  166672 ms: Mark-sweep 1375.0 (1458.0) -> 1264.7 (1458.0) MB, 1517.0 / 0 ms (+ 2.0 ms in 2 steps since start of marking, biggest step 1.0 ms) [last resort gc].
  168397 ms: Mark-sweep 1264.7 (1458.0) -> 1264.3 (1458.0) MB, 1725.3 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1401787b4629 <JS Object>
    2: create [/Users/btrigueiro/projects/universal-starter/node_modules/@angular/core/src/linker/view.js:66] [pc=0x89936ed6a40] (this=0x3ca7ac1f6021 <a _View_App0 with map 0x209a2d08ee51>,context=0x3ca7ac1f60a9 <an App with map 0x2a42460cafc9>,givenProjectableNodes=0x3ca7ac1f6089 <JS Array[0]>,rootSelectorOrNode=0x140178704101 <null>)
    3: create [/Users/btrigueiro/projects/universal-starter...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

`npm start` any project using angular-universal (the logs above were taken from universal-starter) and hit it with multiple requests per second. For angular-universal JMeter with 20 users and 10 seconds ramp up was enough to log errors and crash the application within a minute.

It's also possible to spot it on more complex applications by refreshing the browser multiple times within a second. It could be that the issue happens when connections get canceled before they're fully responded.

* **What is the expected behavior?**
That angular-universal would be able to handle multiple simultaneous requests

* **What is the motivation / use case for changing the behavior?**
Same as above

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: Chrome or JMeter
- Language: TypeScript 1.8.9 and ES6/7
- OS:  Mac OS X
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
The errors get caught and logged [in this block of the bootloader](/angular/universal/blob/05a39629bffe2ebd6bbfb30a16a3384d039300cc/modules/universal/src/node/bootloader.ts#L132-L209). Still it doesn't look like those requests are returned with a 500 error.

**Comment by MarkPieszak** [comment]
Nice catch, ya even hitting F5 really fast for a few seconds can cause this.
It seems `this` inside of bootloader.ts loses it self / the closure.

     if ('ngOnStable' in this._config) { // <-- "this" undefined

**Comment by btrigueiro** [comment]
I'm still running some tests but I'm quite sure I have a patch for this issue... Ideally though, we should isolate the cause. At least I'm positive I've managed to prevent the memory leak.
If everything is fine I'll submit a PR tomorrow.
Cheers!

**Comment by btrigueiro** [comment]
Looks like the issue is caused because `Bootloader.dispose()` gets called before the promise chain is done, nullifying `this._config`. Apparently it leaked memory when the chain would go through the `catch` methods.
This patch just prevents `then` handlers to `throw` in this situation so the chain properly finishes and cleans up afterwards.

**Comment by gdi2290** [comment]
I updated universal to account for more concurrent requests. can you update to `0.102.1`

please open another issue if you run into more problems
