### ISSUE TITLE
UNMET PEER DEPENDENCY angular2-universal@^0.101.4

### ISSUE THREAD

**Issue by dehian** [angular/universal#427]
I'm submitting a ...
[x ] bug report
 feature request
 support request => Please do not submit support request here, see note at the top of this template.
Current behavior
I'm using angular2 with the universal component, i had my project working few weeks ago but now i wanted to install the app on another machine and i have a dependency issue
my package.json refers to 
"angular2": "2.0.0-beta.15",
"angular2-universal": "0.98.3"
...
on my local machine, the initial install made few weeks ago succesfully installed the following
+-- angular2@2.0.0-beta.15
+-- angular2-universal@0.98.3
| +-- angular2-express-engine@0.11.1
| +-- angular2-hapi-engine@0.11.1
| +-- angular2-universal-polyfills@0.4.1
| | +-- es6-promise@3.0.2
| | `-- ie-shim@0.1.0
...

same thing today on another machine gives 
+-- angular2@2.0.0-beta.15
+-- angular2-universal@0.98.3
| +-- angular2-express-engine@0.13.1
| +-- angular2-hapi-engine@0.13.1
| +-- UNMET PEER DEPENDENCY angular2-universal@^0.101.4
| +-- angular2-universal-polyfills@0.4.1
| | +-- es6-promise@3.0.2
| | `-- ie-shim@0.1.0
...
and i assume that this is why my project aint working there

Expected/desired behavior
have a package that works with those dependencies

What is the motivation / use case for changing the behavior?
it just fails

Please tell us about your environment:
node 5.11.1
windows 7

Angular version: 2.0.0-beta.15

Browser: [all ]

Language: [ TypeScript]

**Comment by MarkPieszak** [comment]
I think you need to update your Universal package in general you're using an older one with an older version of angular2@beta as well.

Universal is @ `0.101.8` now
Which works with `@angular 2.0.0-rc.1`
Just make sure you're still using `@angular/router-deprecated`

That might solve a few problems if you just upgrade everything.

**Comment by dehian** [comment]
ok i could upgrade to rc but is there any other workaround that could allow me to just change the packagng an not touch the code?

**Comment by MarkPieszak** [comment]
You might not have to change anything when trying to upgrade those packages?

Does the project not run because of that UNMET DEPENDENCY? Sometimes those come up during `npm i`'s but things can still work anyway.

**Comment by dehian** [comment]
yes it doesn't work because of that...i changed the packages to the ones of previous installation and then it works...so definitely a package issue

**Comment by MarkPieszak** [comment]
What happens error-wise when you try to install the latest versions of @angular (rc1) & angular2-universal?

**Comment by dehian** [comment]
"@angular/common":  "2.0.0-rc.1",
    "@angular/compiler":  "2.0.0-rc.1",
    "@angular/core":  "2.0.0-rc.1",
    "@angular/http":  "2.0.0-rc.1",
    "@angular/platform-browser":  "2.0.0-rc.1",
    "@angular/platform-browser-dynamic":  "2.0.0-rc.1",
    "@angular/router":  "2.0.0-rc.1",
    "@angular/router-deprecated":  "2.0.0-rc.1",
    "@angular/upgrade":  "2.0.0-rc.1",
    "systemjs": "0.19.27",
    "es6-shim": "^0.35.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "angular2-universal": "0.101.8",
    "body-parser": "^1.15.0",
    "es6-promise": "^3.0.2",
    "express": "^4.13.4",
    "pm2": "^1.1.2",
    "preboot": "^2.0.5"

gives me 

+-- angular2-universal@0.101.8
| +-- angular2-express-engine@0.13.1
| +-- angular2-hapi-engine@0.13.1
| `-- js-beautify@1.6.3
+-- angular2-universal-polyfills@0.4.1
| `-- reflect-metadata@0.1.2
+-- UNMET PEER DEPENDENCY reflect-metadata@0.1.3
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.6
+-- systemjs@0.19.27
`-- zone.js@0.6.12

**Comment by MarkPieszak** [comment]
You need to update your zone.js to `5.0.0-beta.6` as well (for @angular rc1)

**Comment by dehian** [comment]
yep saw it after...sorry...updated package.json...updated code...npm start gives no issue but still i get a "localhost refused to connect."
any clue on how to debug this?

**Comment by MarkPieszak** [comment]
Is the port being used by something else? That's usually when that happens

**Comment by dehian** [comment]
nope
i can access static files like templates from that project through the same url and port

**Comment by dehian** [comment]
ok i finally got it working
removed 
"@angular/router": "2.0.0-rc.1",
and
"@angular/upgrade": "2.0.0-rc.1",
from my package.json

but still dont get why in case of error npm didn't complain and i couldn't access the page...in that case it's really hard to debug things

**Comment by MarkPieszak** [comment]
Oh great! It might of been `upgrade` I've never included that one, or the combination of both. Glad you got it working though, cheers. 👍

**Comment by MarkPieszak** [comment]
Can you close this issue out when you get a chance @dehian ?

**Comment by dehian** [comment]
i can but i still don't get why i got a connection refused and no error message but ok i close it
