### ISSUE TITLE
Universal handle ajax calls in a erratic way 

### ISSUE THREAD

**Issue by xe4me** [angular/universal#431]
I've been using Angula2 + Universal from the day one they launched it, but today I'm getting confused around how it actually works.

In your example , in the server.ts file you will find :

```
app.get( '/data.json' , ( req , res ) => {
    res.json( {
        data : 'This fake data came from the server.'
    } );
} );

```
If you run the app , right click and view page source , you'll find 'This fake data came from the server' in the source code , meaning that the page got rendered in the server ? ( Is this correct ? )

So far , so great.

Next is in the app.ts , you can find :
```

ngOnInit () {
        setTimeout( () => {
            this.server = 'This was rendered from the server!';
        } , 10 );
}
```

Again , this text can be found in the page source as well.

Now here is the weird part for me :

If you , for any reason , increase the server latency like :

```
app.get( '/data.json' , ( req , res ) => {
    setTimeout( function() {
        res.json( {
            data : 'This fake data came from the server.'
        } );
    } , 2000 ); // Added setTimeOut with 2 seconds .
} );

```
This way , the page source wont get the text , however , if you do this :

```
app.get( '/data.json' , ( req , res ) => {
    setTimeout( function() {
        res.json( {
            data : 'This fake data came from the server.'
        } );
    } , 2 ); // **Added setTimeOut with 2 milli seconds.**
} );
```

This one, you can find the text in the server .!!!!!!

So far based on my tests , I'm guessing if the ajax call latency is to long ( more than one second I guess ? ) , you won't benefit from server side rendering .

BUT :

However , if you increase the timeOut in the app.component.ts , like :

```
ngOnInit () {
        setTimeout( () => {
            this.server = 'This was rendered from the server!';
        } , 3000 );  // Increased to 3 seconds
}

```
You can still get the server side rendering and source page will have the text rendered !

What's happening here ?

Obviously not all of the ajax calls can be lower than 1 seconds , so what is the benefit of using universal anyway ?

**Comment by gdi2290** [comment]
In production you would cache the http calls. I'm also setting a limit of 2000 milliseconds on the server before it renders. You can increase the limit with `maxZoneTurns` in the config

see refactored repo that demonstrates this https://github.com/angular/universal-starter/blob/master/src/backend/api.ts

**Comment by xe4me** [comment]
@gdi2290 Please read the bug again, it's not about caching , it's about how universal is behaving different with the same scenario.

**Comment by gdi2290** [comment]
@xe4me right now we're not canceling setTimeouts but for http requests we are ignoring them if they're looking than 2000 milliseconds which is why you see the server waiting for the setTimeout in the app and not via http calls

**Comment by gdi2290** [comment]
closing as I removed the force render on the server since we are still waiting for setTimeout and can't guarantee correct cancellation of all async calls.

**Comment by intergleam** [comment]
how do I pre-render a component with Ajax then?
I have 
```
  async ngOnInit() {
    this.message = 'Hello!!';
    var data = await this.http.get('https://api.github.com/users/github').toPromise();
    this.message = data['bio'];
  }
```

and it doesn't work as expected
