### ISSUE TITLE
Universal appends  styles twice at the head 

### ISSUE THREAD

**Issue by xe4me** [angular/universal#436]
- [x] bug report

Angular universal loads styles twice at the top of the page , which is head tag.
This beahviour can easily be reproduced via the rep itself , just pull and npm start and you'll see the bug.

http://stackoverflow.com/questions/37375003/angular2webpack-loads-styles-twice-at-the-head

**Comment by lemind** [comment]
Well, if we could set param witch turn off compile styleSheets in Angular this would be right solution for this issue. Can we do it now?

**Comment by gdi2290** [comment]
fixed in 1.0.4 with angular rc5/rc6/rc7 support

**Comment by drejohnson** [comment]
I still get duplicated styles with `ViewEncapsulation.None`

**Comment by KirilNN** [comment]
The issue can easily be reproduced with the latest version as well, when encapsulation is set to `ViewEncapsulation.None`. Are there any plans for fixing it?

**Comment by gdi2290** [comment]
for `ViewEncapsulation.None` the style host would have to be reworked for both server/client in order to determine which styles were generated on the server etc.

**Comment by KirilNN** [comment]
So should we reopen the issue and keep track on the progress? It also concerns the AoT compilation.

**Comment by halben** [comment]
Any updates on this? I'm still seeing the issue.
