### ISSUE TITLE
Animation fails when try to prerender

### ISSUE THREAD

**Issue by laskoviymishka** [angular/universal#440]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
When you try to load app that use animations you recieve:
```
RROR in C:\temp\aspnetu2\node_modules\angular2-universal\dist\node\platform\dom\node_dom_renderer.d.ts
(3,34): error TS2307: Cannot find module '@angular/platform-browser/src/animate/animation_builder'.
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**
Animation not played (obviously), but still can rendered.

* **What is the motivation / use case for changing the behavior?**
I wanna build fancy app that use animations, and enable prerender for it.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.1
- Browser: [all]
- Language: [all]
- OS:  [all]
- Platform: [NodeJs | .Net ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gdi2290** [comment]
this should be fixed with the latest release that supports rc.2 and rc.3
