### ISSUE TITLE
@angular/platform-browser/src/animate/animation_builder not found in node/platform/dom/node_dom_renderer.ts

### ISSUE THREAD

**Issue by casfnq** [angular/universal#441]
Bug - Universal

dependencies: 
    "@angular/common": "^2.0.0-rc.2",
    "@angular/compiler": "^2.0.0-rc.2",
    "@angular/core": "^2.0.0-rc.2",
    "@angular/http": "^2.0.0-rc.2",
    "@angular/platform-browser": "^2.0.0-rc.2",
    "@angular/platform-browser-dynamic": "^2.0.0-rc.2",
    "@angular/platform-server": "2.0.0-rc.2",
    "@angular/router": "^2.0.0-rc.2",
    "@angular/router-deprecated": "^2.0.0-rc.2",
    "angular2-universal": "^0.102.0",

tsc generates errors, dotnetcore run generates errors because of this.

- Angular version: 2.0.0-rc.2
- Language: TypeScript ^1.8.2
- OS:  Windows
- Platform: NodeJs, .Net

[package.json.zip](https://github.com/angular/universal/files/319598/package.json.zip)

**Comment by MarkPieszak** [comment]
At the moment Universal only works with rc1 and router-deprecated unfortunately. Router-rc2 is actually the new new new (totally different router from even rc1, it's more like NgRx router). Also i think you might need Typescript nightly (1.9) to use the new Router. More info on it here: http://victorsavkin.com/post/145672529346/angular-router

It's definitely something we'll be adding support for though.

**Comment by gdi2290** [comment]
the repo has been updated to rc.2 and rc.3
