### ISSUE TITLE
chore: identify and fix all private @angular imports

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#443]
There are some private Angular APIs that have been necessary to use to make Universal work. However, anything in Angular that's not exported from the root of a package (i.e. `@angular/core` or `@angular/platform-server) is considered a private API, and subject to breaking without notice. We should do an analysis of what private Angular APIs are being used throughout Universal modules, and determine a proper solution.

**Comment by robwormald** [comment]
This needs to go up the priority list, as RC6 is going to *only* ship unbundled w/ ESM code, and a single UMD for all packages.

**Comment by MarkPieszak** [comment]
@robwormald @jeffbcross If you take a look at the rc5 PR here (https://github.com/angular/universal/pull/524/files#diff-662075e86dfbda35f68811a6a2be580aR16) it's a merge of the previous Universal module with the new one Patricks made up) You can do a quick search for `// PRIVATE` to see the internal things that are still being accessed. You can see certain functions are copied from facade etc in platform-node as well.

What do you guys think we can do for these situations ?

**Comment by MarkPieszak** [comment]
Some other ones:

**NoOpAnimationDriver**
Useage: `{provide: AnimationDriver, useFactory: NoOpAnimationDriver}`

```
// Most of these are still accessible

import {APP_ID_RANDOM_PROVIDER} from '@angular/core/src/application_tokens';
import {ReflectionCapabilities} from '@angular/core/src/reflection/reflection_capabilities';
import {reflector} from '@angular/core/src/reflection/reflection';
import {ViewUtils} from '@angular/core/src/linker/view_utils';
import {PLATFORM_CORE_PROVIDERS, ApplicationRef_} from '@angular/core/src/application_ref';
            // ^ This one has been removed/private already (Not-accessible now)
import {SanitizationService} from '@angular/core/src/security';
import {getDOM} from '@angular/platform-browser/src/dom/dom_adapter';
```

**Comment by gdi2290** [comment]
done in master. I moved all private APIs to https://github.com/angular/universal/blob/c8201bc1e24763f3c2ca4cf87fe5943d6c54e7a7/modules/platform-node/__private_imports__.ts
