### ISSUE TITLE
chore: publish modules as @angular/<module>

### ISSUE THREAD

**Issue by jeffbcross** [angular/universal#444]
Now that Angular has moved away from `angular2-` prefixes for packages, and is now using npm scoped packages, `@angular/`, universal modules should do the same.
- preboot: leave as-is, not angular-specific
- angular2-universal -> `@angular/univeral`
- angular2-broccoli-prerender -> `@angular/broccoli-prerender`
- angular2-express-engine -> `@angular/express-engine`
- angular2-grunt-prerender -> `@angular/grunt-prerender`
- angular2-gulp-prerender -> `@angular/gulp-prerender`
- angular2-hapi-engine -> `@angular/hapi-engine`
- angular2-universal-polyfills -> `@angular/universal-polyfills`
- angular2-universal -> `@angular/universal`
- angular2-webpack-prerender -> `@angular/webpack-prerender`

TODO
- [ ] Update all package.jsons
- [ ] Publish all packages to new namespace when ready for next release
- [ ] Deprecate all old packages on npm

CC @IgorMinar since I just discussed this with him.

**Comment by gdi2290** [comment]
for the `webpack-prerender` integration we need to rename it to `@angular/prerender-webpack-plugin` as it's a convention of webpack for something like [`webpack-load-plugins`](https://github.com/samvloeberghs/webpack-load-plugins)

related 
https://github.com/jackfranklin/gulp-load-plugins
https://github.com/sindresorhus/load-grunt-tasks
https://github.com/samvloeberghs/webpack-load-plugins

**Comment by hdngr** [comment]
Hey there - I'm working on this.  

Updated all of the names to use the scoped convention, but now I am having problems with the different packages because npm isn't finding the peer depdencies registered (I am using npm 3.10).  

I am guessing there is a simple solution :-)

**Comment by jeffwhelpley** [comment]
As discussed with @jeffbcross we will move the package to @angular once we get the new build process and appropriate testing in place. This move will also include using the same version cadence as other angular core modules.
