### ISSUE TITLE
Cant install angular2-universal on Windows 10

### ISSUE THREAD

**Issue by Cedriking** [angular/universal#446]
* **I'm submitting a ...**
- [ x ] bug report

* **What is the current behavior?**
I'm unable to install angular2-universal on windows.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

1 - I do "npm install --save angular2-universal
2 - I get the message:
```
$ npm install --save angular2-universal
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\node.exe" "D:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save" "angular2-universal"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular2-universal@0.103.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2-hapi-engine@0.14.0 wants angular2-universal@^0.102.0
npm ERR! peerinvalid Peer angular2-express-engine@0.14.2 wants angular2-universal@^0.102.0

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Sync\Quiz\npm-debug.log
```

* **What is the expected behavior?**
To install angular2-universal in my current or new project.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.2
- Browser: all
- Language: Typescript
- OS:  Windows 10 x64
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
What version of Node are you using?

**Comment by Cedriking** [comment]
Hello there Mark, I'm using node v4.2.6 with npm 2.14.12

Thank you ^_^

**Comment by gdi2290** [comment]
can you update to npm 3?

**Comment by Cedriking** [comment]
Thanks a lot, now it's working! :+1:
