### ISSUE TITLE
ideas to leverage server environment to provide a better "developer experience"

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#45]
Angular 2 now is able to run on the server so what's the next step?
We can now take advantage of the benefits of having this control over the client's environment. We can create a small server layer that uses any of the underlying Node Frameworks such as ExpressJS, Hapi.js, or Koa.js. Doing so would be a great way for, normally client only developers, to be introduced to the backend. 

Having full control over the client's environment allows us to dramatically improve the developer experience with features such as: 
  * TypeScript inline script tags
  * ES6 features such as <module> and SystemJS
  * allow users to write a component DSL (such as JSX, RiotJS, or jsBlocks)
  * better control over testing/development/production environments
  * better logging
  * live app configuration
  * default jwt setup
  * asset pipeline
  * inject ES6 polyfills
  * inject RxJS as Observable
  * can be front-end agnostic
  * removing unnecessary Angular `import`s for each file (like Rails)

prior art
https://github.com/yahoo/fluxible
https://muut.com/riotjs
https://github.com/astoilkov/jsblocks
https://github.com/linnovate/mean
https://github.com/meteor/meteor
https://github.com/rails/rails
https://github.com/django/django
https://github.com/playframework/playframework
https://github.com/elierotenberg/react-nexus
https://github.com/facebook/relay

the Universal app is `<app>` while the Server app is the html document itself that we can call an `<html>` component.
```html
<html>
  <head>
    <title>Fullstack Angular 2</title>
    <meta></meta>
  </head>
  <body>
    <app></app>
    <!-- app-scripts -->
  </body>
</html>
```

currently `<doctype>` needs to be injected after the fact

code samples
https://gist.github.com/gdi2290/efa2061467c92243ca58
https://gist.github.com/gdi2290/f07fd579c6ec911d2305
https://gist.github.com/gdi2290/7c2280655dbf50450444

modules:
[mincer](https://github.com/nodeca/mincer)
[RxJS Next](https://github.com/ReactiveX/RxJS)
[polyfills](https://github.com/polyfills/polyfills)
[bunyan](https://github.com/trentm/node-bunyan)
[vantage](https://github.com/dthree/vantage)
[webpack](https://github.com/webpack/webpack)
[webpack-require](https://github.com/petehunt/webpack-require)
[autopolyfiller](https://github.com/azproduction/autopolyfiller)

related:
ngScripts https://github.com/angular/universal/issues/72
Environment  Service https://github.com/angular/universal/issues/44

**Comment by gdi2290** [comment]
related https://github.com/angular/universal/issues/44

**Comment by jeffwhelpley** [comment]
@gdi2290 This is not an actionable item in any way. Perhaps we should consider having a separate place (wiki or wherever) that has "thoughts for the future". Let's talk about this more and move it to the appropriate place.

**Comment by gdi2290** [comment]
let's just close it
