### ISSUE TITLE
Solution problem: adding SEO meta tags to <head> 

### ISSUE THREAD

**Issue by kaaboeld** [angular/universal#454]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

We have problem: adding SEO tags for any social networks without external HTML component.
https://gist.github.com/kaaboeld/851bc3190eec67f6723c6054751ee2dc  

* **Please tell us about your environment:**

- Angular version: 2.0.0-RC-1
- Browser: all
- Language: TypeScript 1.8
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by rjokelai** [comment]
We solved this by creating the elements with the `Renderer` and injecting the `Document` too:

    import { Component, AfterViewInit, Renderer, Inject } from '@angular/core';
    import { DOCUMENT } from '@angular/platform-browser';

    @Component({ ... })
    class AppComponent implements AfterViewInit {
      constructor(@Inject(DOCUMENT) private document: any, private renderer: Renderer) {}

      ngAfterViewInit(): void {
        const elem = this.renderer.createElement(this.document.head, 'meta');
        this.renderer.setProperty(elem, 'name', 'foo');
      }
    }

**Comment by edusoft** [comment]
Hi @rjokelai I'm searching a SEO Angular 2 example fully working for all internet! :) 
Please, can you share the code using your recomended fix? 

Thanks in advanced..

**Comment by gjuchault** [comment]
@rjokelai I guess this is not the point of prerendering, as this will (correct me if I'm wrong) be added after rendering to the browser

**Comment by rjokelai** [comment]
No, this the way we got it actually working in the universal app. The `meta` tags are already sent with the prerendered html response. The point here is to use the `DOCUMENT` token and `Renderer`, which the universal library is aware of.

They actually use this kind of approach in the universal starter:

https://github.com/angular/universal-starter/blob/master/src/app/app.component.ts#L20

Our specific case is that we have a CMS-backed angular application. The meta information comes from the CMS and should be rendered for crawlers.

**Comment by jeffwhelpley** [comment]
I am going to consolidate this issue with #309 where we are discussing creating universal services that will make it easy to change the meta tags.
