### ISSUE TITLE
Animation effects not available in plain HTML rendered on console using universal.

### ISSUE THREAD

**Issue by vinodbhargava** [angular/universal#457]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [ X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] preboot
- [ ] universal-preview
- [X ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I have taken the screenshot of the html rendered on browser using universal. On the browser, the animation is played but in the plain html/screenshots it never comes up. Animation always starts once the `response.render(html, options, function(err, htmlStream) { // do something; })`
is completed.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**
The plain html rendered on console should be able to play the animation.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.3
- Browser: Chrome
- Language: TypeScript 1.8.10 
- OS:  Windows 64 Bit
- Platform: NodeJs 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Can you please help.

**Comment by MarkPieszak** [comment]
What type of animations, css ones? Do you have some code (or github repo link) we could try?

**Comment by vinodbhargava** [comment]
I am trying angular 2 animation package. Please let me know if ineed to provide the repo.

**Comment by gdi2290** [comment]
can you provide a repo?

**Comment by vinodbhargava** [comment]
Please refer to this repo - https://github.com/vinodbhargava/universal-animation-screenshots.git

**Comment by vinodbhargava** [comment]
Hi Patrick @gdi2290 did you get a chance to look at this?

**Comment by gdi2290** [comment]
not yet but we did turn animations off for the server which would explain why it's not working. we probably should create a phantomjs dom renderer so your screenshots would work correctly

**Comment by vinodbhargava** [comment]
Thanks @gdi2290. Do you have reference/code snippet for phantomjs dom renderer to which i can refer too.

**Comment by vinodbhargava** [comment]
@gdi2290 also, are the animations turned off purposely? Is there a way we can turn them on in universal?

**Comment by jeffwhelpley** [comment]
Animations will not work on the server because there is no browser and thus nothing to "animate". However, once #512 is done then you will be able to prerender static screenshots of your animations (as Patrick sort of alluded to above). Please follow #512 for more.
