### ISSUE TITLE
universal.angular.io does not appear on iOS devices

### ISSUE THREAD

**Issue by ClickSimply** [angular/universal#459]
When I go to universal.angular.io on my iPhone and iPad the screen is completely white, nothing shows up.

I have an iPhone SE with iOS 9.3.2 and an iPad 2 with iOS 9.3.1.

I hooked up the phone to my MacBook and opened the inspector in Safari (This is inspecting the mobile safari page through the USB cable). The issue seems to be the container element just under the body of class ".mdl-layout", it has "display:flex" in it's style. When this is disabled or changed to "display:block" in the inspector the page suddenly appears, although not styled correctly.

**Comment by ericjim** [comment]
I'll look into it, `.mdl-layout` behaves differently across browsers. We were bumping into the same issues with the other angular microsites.

**Comment by ClickSimply** [comment]
The  issue seems to have been taken care of, everything is showing up on my iDevices now.
