### ISSUE TITLE
Stream serialized server rendered app to client

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#46]
support stream rendering on the server to client

~~There are a few best practices for web mobile development and one of them is streaming the HTML down to the client. Also consider movements such as [`JSON.stringifyAsync`](https://github.com/mohsen1/async-json#asynchronous-json-methods-for-ecmascript-proposal) which brings up the same point of sending the results. We could stream down the serialized server rendered app via
 `stringifyElement` => `stringifyElementAsync`~~

**Comment by jeffwhelpley** [comment]
@gdi2290 have you put thought into how this would work?

**Comment by gdi2290** [comment]
parse5 allows for easier support. we need to determine which components won't be rendered again due to a cascading change. closing for now
