### ISSUE TITLE
No more examples ?

### ISSUE THREAD

**Issue by jaumard** [angular/universal#473]
Previously a `/examples` was present and very helpful to start with universal but it look like it's gone now :( did they move elsewhere ?

**Comment by visikov** [comment]
@jaumard You can check out the [starter seed](https://github.com/angular/universal-starter). It's pretty function out of the box.

**Comment by jaumard** [comment]
Thanks @visikov I already check it but it used webpack and I don't (and don't want because I don't like it) :) and my problem are now mainly configuration so the I use the starter when I can but when it touch the system.config.js or other stuff done by webpack I'm in the dark ^^

**Comment by MarkPieszak** [comment]
I'm building up some examples now, apologies on the delay. I'll get a system one together for you. Webpack is better though, switch to the dark side :)  (I believe the CLI is switching to webpack as well)

**Comment by jaumard** [comment]
no problem at all @MarkPieszak  :) 
Webpack is far too complicated... I'm fine with gulp ^^ also I didn't like TS at all too lol but I don't have choice because angular 2 in JS has no community (and was in ES5) so for now I have my angular2 in TS and my server part in ES6 but mixing the 2 for making server rendering happy is a real challenge :)
Hope in near futur angular2 will have an ES6/7 version that can replace TS.
If you're curious I made an example here https://github.com/jaumard/trails-angular2-isomorphic where it mix ES6 for server side and TS for angular 2.

**Comment by MarkPieszak** [comment]
If you don't like TS very much I'd say just keep going at it, you'll realize you've been missing out! It's much much better than using regular ES6 with babel or anything. All of the tooling and intellisense is priceless.

**Comment by visikov** [comment]
Gonna have to agree with @MarkPieszak on this one. TS is an absolutely tremendous tool for the dev. When used right, it keeps everything in check and really minimizes runtime errors.

As for webpack, I find it to be much less complex than gulp. If all you're afraid of is the learning curve then you have nothing to worry about. We have a junior dev on our team who picked it up within a couple days.

If you have any questions feel free to DM me on gitter, I'm on the angular/universal channel.

**Comment by jaumard** [comment]
Thanks guys :) I suppose at some time I'll have to learn webpack ^^ but for now I have no time for this. Time will tell if I'll change my mind about TS :)

**Comment by jaumard** [comment]
@MarkPieszak in your example do you plan to have a service with different client/server implementation ?? Because this will be really helpful to me right now lol (for handled websockets) :)

**Comment by dottodot** [comment]
A service example for server/client would be a a great help, in particular how to add a client only service for things such as 3rd party plugins that require access to window or document.

**Comment by jaumard** [comment]
@dottodot it's quite easy when you have something to look :) I manage to do it quite easily with this video https://youtu.be/TCj_oC3m6_U?t=621 but example on this will be great ^^

**Comment by dottodot** [comment]
@jaumard that's actually the example I've been trying to use as a base but can only get the server side to work.

**Comment by gdi2290** [comment]
will be closed via https://github.com/angular/universal/issues/510 please follow that issue
