### ISSUE TITLE
Server rendering work once with new router

### ISSUE THREAD

**Issue by jaumard** [angular/universal#481]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Only hard coded component (header, footer) are rendered each time but router page is rendered only once.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Here is a demo of the problem https://github.com/jaumard/trails-angular2-isomorphic if you start the project and go do a curl to `localhost:3000` the first time you'll see : 
```
....
<router-outlet></router-outlet>
      <pages-home _nghost-uil-5="">
        <h1 _ngcontent-uil-5="">TODO HOME PAGE</h1>
      </pages-home>
....
```
If you do another curl call you'll see nothing about the router is rendered anymore : 
```
<router-outlet></router-outlet>
```
* **What is the expected behavior?**
The router page should be rendered each time we call the page, not once

* **Please tell us about your environment:**
- Angular version: 2.0.0-rc4
- Browser: [all]
- Language: [all]
- OS:  [Mac OS X]
- Platform: [NodeJs]

**Comment by gdi2290** [comment]
what's the url you're using for curl?

**Comment by jaumard** [comment]
@gdi2290 juste `http://localhost:3000` :) or I just click `see source page` on chrome and then refresh and I see it was not rendered anymore after the first time.

**Comment by slevp** [comment]
+1

**Comment by jeffwhelpley** [comment]
With all the latest versions of Angular and Universal, I can't recreate this issue any longer. Please test this out again and if you find anything, post your results here and we will re-open the investigation.
