### ISSUE TITLE
Preboot buffer doesn't start angular2 app after rendering

### ISSUE THREAD

**Issue by jaumard** [angular/universal#482]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
When we load a page, server rendering render the page correctly (the first time only because of this bu https://github.com/angular/universal/issues/481) But once rendering is done angular 2 app doesn't seems to be started because if we click on router link the page is loaded instead of just the component.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Demo is here https://github.com/jaumard/trails-angular2-isomorphic, go to `api/controllers/ViewController` and enable the buffer option, then `npm start` and go to `localhost:3000` if you click on Home or About you'll see the page is reload, router doesn't do his job.

* **What is the expected behavior?**
Once page is rendered angular2 app should take the lead like when buffer option is false

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc4
- Browser: [all]
- Language: [all]
- OS:  [Mac OS X]
- Platform: [NodeJs]

**Comment by jeffwhelpley** [comment]
Moving this issue to the new preboot repo. I will fix it over there.

https://github.com/angular/preboot/issues/2

**Comment by jaumard** [comment]
Thanks @jeffwhelpley and sorry I didn't notice preboot was on it's own repo now :)
