### ISSUE TITLE
Installation for angular-cli project 

### ISSUE THREAD

**Issue by beckmeindia** [angular/universal#488]
Hey,
     I am using angular-cli project with Firebase. Presently the router takes time to initialize and angular universal is a great way to avoid that.

I tried searching through all docs available online for installing universal in an angular-cli project but could not find any.

Could you please help?

Cheers,
Rahul

**Comment by MarkPieszak** [comment]
Are you trying to figure out how to set it up initially? That'd be `ng new MyProjectName --mobile` (but I think that may not be working 100% currently).

Take a look at the [Node Universal Starter here](url), to see what the setup needs. You can see ([here](https://github.com/angular/universal-starter/tree/master/src)) the separation of browser & server, and how the server renders the pages and passes them through the universal expressEngine (in this case). That should get you started!

**Comment by beckmeindia** [comment]
Hey Mark,
             Thanks a lot for the reply. I will make the changes required in the src folder in my angular-cli project looking at the link. 
I was wondering if there are any other changes that I would need to make in System.config or tsconfig.json files or anywhere else for the server to run. 

Thanks,
Rahul

**Comment by MarkPieszak** [comment]
The Starter here is based off of webpack. The CLI project is also moving towards webpack (https://github.com/angular/angular-cli/tree/webpack) So very soon you might be able to just re-make your app with that, it'll be even easier for you. Just give it a little time :)

**Comment by beckmeindia** [comment]
Sounds Great. Thanks!
