### ISSUE TITLE
animations makes universal crash

### ISSUE THREAD

**Issue by mickael-kerjean** [angular/universal#491]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this pull-request**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-preview
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
While trying to use the new animation api, the server is crashing

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Create an animation: https://angular.io/docs/ts/latest/guide/animations.html

* **What is the expected behavior?**
Should not crash the server

* **What is the motivation / use case for changing the behavior?**
Would be cool to use the animation

* **Please tell us about your environment:**
- Angular version: Using [this seed](https://github.com/angular/universal): Angular version 2.0.0-rc.4
- Browser: server crash
- Language: TypeScript
- OS:  Linux
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
the app is crashing with the following stacktraces:
```
TypeError: Cannot read property 'animate' of undefined
    at NodeDomRenderer.DomRenderer.animate (/home/mickael/spotlive/application/node_modules/@angular/platform-browser/src/dom/dom_renderer.js:226:37)
    at Details_page_0_factory (Details.template.js:29:127)
    at AppView._View_Details3.detectChangesInternal (Details.template.js:433:5)
    at AppView.detectChanges (/home/mickael/spotlive/application/node_modules/@angular/core/src/linker/view.js:243:14)
    at AppView.detectContentChildrenChanges (/home/mickael/spotlive/application/node_modules/@angular/core/src/linker/view.js:261:19)
    at AppView._View_Details2.detectChangesInternal (Details.template.js:236:8)
    at AppView.detectChanges (/home/mickael/spotlive/application/node_modules/@angular/core/src/linker/view.js:243:14)
    at AppView.detectContentChildrenChanges (/home/mickael/spotlive/application/node_modules/@angular/core/src/linker/view.js:261:19)
    at AppView._View_Details0.detectChangesInternal (Details.template.js:97:8)
    at AppView.detectChanges (/home/mickael/spotlive/application/node_modules/@angular/core/src/linker/view.js:243:14)
```

**Comment by MarkPieszak** [comment]
Is this something we're missing or a Core issue? @gdi2290

**Comment by mickael-kerjean** [comment]
I investidate a bit and here it is:
The error is happenning [here](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L238) because the animationDriver attribute is undefined. 
I checked if the depedency injection is doing it job [here](https://github.com/angular/angular/blob/master/modules/%40angular/platform-browser/src/dom/dom_renderer.ts#L66) and it seems universal says it's undefined as the stacktrace says.

AnimationDriver is an abstract class defined [here](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/core/src/animation/animation_driver.ts) and [looking inside universal](https://github.com/angular/universal/blob/08f6f0f564f6e6fb9fea2b039561ab97465b7bd8/modules/universal/src/node/platform/node.ts#L124) it tried to use an implementation made inside [Angular core](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/core/src/animation/animation_driver.ts#L19)

**Comment by mickael-kerjean** [comment]
Ok I got something,
[here](https://github.com/angular/universal/blob/08f6f0f564f6e6fb9fea2b039561ab97465b7bd8/modules/universal/src/node/platform/node.ts#L124), i wasn't able to understand why we need to use useFactory instead of useClass. 

It might be a missunderstanding from my part but [here I see a simple class](https://github.com/angular/angular/blob/2.0.0-rc.4/modules/%40angular/core/src/animation/animation_driver.ts). not something that return another function.

So I update [this file](https://github.com/angular/universal/blob/08f6f0f564f6e6fb9fea2b039561ab97465b7bd8/modules/universal/src/node/platform/node.ts#L124), from 
```{provide: AnimationDriver, useFactory: NoOpAnimationDriver},```
to
```{provide: AnimationDriver, useClass: NoOpAnimationDriver},```

It's now working like a charm

**Comment by MarkPieszak** [comment]
That must be something changed in one of the latest rc updates to Core. Nice find Mickael! Put in a PR for it and we can close out this issue. :+1:

**Comment by gdi2290** [comment]
@mickael-kerjean can you make a PR

**Comment by mickael-kerjean** [comment]
Problem solved
