### ISSUE TITLE
Unable to use jquery-ui 

### ISSUE THREAD

**Issue by IamKritika** [angular/universal#493]
* **I'm submitting a ...**
- [ ] bug report

I was trying to integrate jquery-ui datepicker widget in my project. So jquery-ui requires 'jQuery' as a global variable which I have exposed through webpack provide plugin but the code is breaking on server side.

It says it is unable to find 'jQuery' variable. 

the code is as follows -

webpack.config.js

`  new webpack.ProvidePlugin({
      jQuery: 'jquery',
      $: 'jquery',
      jquery: 'jquery'
    })`

datepicker.component.ts

`import  "jquery-ui/ui/widgets/datepicker.js"
`

Can you suggest any workaround for using jquery widgets.

**Comment by MarkPieszak** [comment]
Same issue as #382 #490. jQuery on the server-side.

Can you follow issue #490 to see the progress on this one?

As alternatives, I would suggest using bootstrap for angular2 (it has a datepicker, and everything else)
https://valor-software.com/ng2-bootstrap/#/datepicker

Also (it's not there yet), but eventually Material2 for ng2 will have a datepicker as well (progress here: https://github.com/angular/material2/issues/675)
