### ISSUE TITLE
Create NodeBackend for Http

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#50]
This is really easy to do since you could just include a Node version of XMLHttpRequest (called NodeXhr) that replaces BrowserXhr for an MVP

in this file [modules/server/src/http_server.ts](https://github.com/angular/universal/blob/master/modules/server/src/http_server.ts)

replace [XMLHttpRequest ](https://github.com/angular/angular/blob/master/modules/angular2/src/http/backends/browser_xhr.ts#L7) with a node version [xmlhttprequest](https://www.npmjs.com/package/xmlhttprequest) as `NodeXhr`

and reuse the same `XHRBackend` with `bind(ConnectionBackend)
      .toClass(XHRBackend)` rather than `NodeBackend` and that should work

**Comment by manekinekko** [comment]
I'll take care of this one.

**Comment by gdi2290** [comment]
Here's the code currently for it.
https://github.com/angular/universal/blob/master/modules/server/src/http_server.ts
at the moment it's stubbed out to use the Mock version.

**Comment by manekinekko** [comment]
@gdi2290  Can you give more details about what you expect from this? The issue description lacks some details for new contributors (like me).

**Comment by gdi2290** [comment]
@manekinekko I updated the original post. Ping me again if you need more details/help

**Comment by manekinekko** [comment]
thanks @gdi2290. I will let you know. I need to take some time and wrap my head around how preboot works under the hood.

**Comment by manekinekko** [comment]
@gdi2290 do you really want to go with [node-XMLHttpRequest](https://github.com/driverdan/node-XMLHttpRequest), it seems to have some [limitations](https://github.com/driverdan/node-XMLHttpRequest#known-issues--missing-features). I dont know what level of support we want here.

I've found other [alternatives](https://www.npmjs.com/search?q=xmlhttprequest) such as [node-xhr2](https://github.com/pwnall/node-xhr2) which implements obviously XHR2 specs. There is also the well known [request](https://github.com/request/request) module.

**Comment by gdi2290** [comment]
@manekinekko `node-xhr2` looks great! I only picked `node-XMLHttpRequest` as a suggestion (first one, no research)

**Comment by gdi2290** [comment]
you can uncomment this [./index.js#L24..L46](https://github.com/angular/universal/blob/master/index.js#L24..L46) and [./examples/app/universal/App.ts#L92..L110](https://github.com/angular/universal/blob/master/examples/app/universal/app/App.ts#L92..L110) and only confirm that the request is being made on the server via console log

**Comment by manekinekko** [comment]
sure. I am on it right now :smiley:

**Comment by manekinekko** [comment]
Here is a cleaner PR https://github.com/angular/universal/pull/76

**Comment by gdi2290** [comment]
thanks, fixed via https://github.com/angular/universal/pull/76
