### ISSUE TITLE
Data is not getting rendered properly on UI after applying ngApp().then(prebootComplete) in client.ts

### ISSUE THREAD

**Issue by sudhakarphule1** [angular/universal#502]
We have used this seed project for our website development.
due to "prebootComplete" in client.ts, it is showing data and after some time it will remove the css of it and data is getting hide.
after commenting the "ngApp().then(prebootComplete);" it will work fine but this will not generate any click event , keyup event in DOM object.

**Comment by MarkPieszak** [comment]
What does your server.ts look like, is it all base settings for preboot / etc?
I'm not sure why things would get hidden after prebootComplete.

**Comment by sudhakarphule1** [comment]
Thanks Mark for your quick response .. I am using the seed project from https://github.com/angular/universal-starter 

This issue comes only for rendering on Chrome..for Edge and FireFox it works fine

Here is my server.ts
// the polyfills must be the first thing imported in node.js
import 'angular2-universal/polyfills';

import * as path from 'path';
import * as express from 'express';
import * as bodyParser from 'body-parser';

// Angular 2
import { enableProdMode } from '@angular/core';
// Angular 2 Universal
import { expressEngine } from 'angular2-universal';

// enable prod for faster renders
enableProdMode();

const app = express();
const ROOT = path.join(path.resolve(__dirname, '..'));

// Express View
app.engine('.html', expressEngine);
app.set('views', __dirname);
app.set('view engine', 'html');

app.use(bodyParser.json());

// Serve static files
app.use(express.static(ROOT, {index: false}));

import {
  serverApi, getServicesDetailsApi, getAboutusDetailsApi, getOnlineStoreProjectsApi,
  getInformationTechnologyProjectsApi, getHealthcareProjectsApi, getRealEstateProjectsApi, getUiUxProjectsApi,
  getWebProjectsApi, getMobileProjectsApi, getIoTProjectsApi, getApplicationArchitectProjectsApi,
  getProcessAutomationProjectsApi, getPerformanceOptimizationProjectsApi,
  getCloudDeploymentProjectsApi, getProcessDetailsApi, getContactUsDetailsApi, getBlogsDetailsApi, getNewsDetailsApi
} from './backend/api';
import { getWorkDetailsApi } from './backend/api';
// Routes with html5pushstate
import { ngApp } from './main.node';

import {getAutomobileProjectsApi} from "./backend/api";
import {getAgricultureProjectsApi} from "./backend/api";
import {sendMailApi} from "./backend/api";

// Our API for demos only
app.get('/api/data', serverApi);
app.get('/api/work',getWorkDetailsApi);
app.get('/api/process',getProcessDetailsApi);
app.get('/api/contactUs',getContactUsDetailsApi);
app.get('/api/services',getServicesDetailsApi);
app.get('/api/about',getAboutusDetailsApi);
app.get('/api/automobile',getAutomobileProjectsApi);
app.get('/api/agriculture',getAgricultureProjectsApi);
app.get('/api/onlinestore', getOnlineStoreProjectsApi);
app.get('/api/infoTech', getInformationTechnologyProjectsApi);
app.get('/api/healthcare', getHealthcareProjectsApi);
app.get('/api/realEstate', getRealEstateProjectsApi);
app.get('/api/uiux', getUiUxProjectsApi);
app.get('/api/web', getWebProjectsApi);
app.get('/api/mobile', getMobileProjectsApi);
app.get('/api/iot', getIoTProjectsApi);
app.get('/api/applicationArchitect', getApplicationArchitectProjectsApi);
app.get('/api/processAutomation', getProcessAutomationProjectsApi);
app.get('/api/performanceOptimization', getPerformanceOptimizationProjectsApi);
app.get('/api/cloudDeployment', getCloudDeploymentProjectsApi);
app.get('/api/blogs', getBlogsDetailsApi);
app.get('/api/news', getNewsDetailsApi);
app.post('/api/send', sendMailApi);



app.use('/', ngApp);
app.use('/about', ngApp);
app.use('/process', ngApp);
app.use('/work', ngApp);
app.use('/workDetail', ngApp);
app.use('/service', ngApp);
app.use('/serviceDetail', ngApp);
app.use('/contactUs', ngApp);
app.use('/home', ngApp);
app.use('/news', ngApp);
app.use('/blogs', ngApp);
app.use('/products', ngApp);
app.use('/:id', ngApp);
app.use('/work/:id', ngApp);
app.use('/blogs/:id', ngApp);
app.use('/news/:id', ngApp);
app.use('/service/:id', ngApp);

// use indexFile over ngApp only when there is too much load on the server
function indexFile(req, res) {
  // when there is too much load on the server just send
  // the index.html without prerendering for client-only
  res.sendFile('/index.html', {root: __dirname});
}

// Server
app.listen(80, () => {
  console.log('Listening on: http://localhost:80');
});
================================================

And client.ts

// the polyfills must be the first thing imported
import 'angular2-universal/polyfills';

// Angular 2
import {enableProdMode} from '@angular/core';
// Angular 2 Universal
import {prebootComplete} from 'angular2-universal';

// enable prod for faster renders
enableProdMode();

import {ngApp} from './main.browser';

// on document ready bootstrap Angular 2
document.addEventListener('DOMContentLoaded', () => {

  // TODO find the better solution for this
  // https://universal.angular.io/api/preboot/index.html
   ngApp()
    .then(prebootComplete);

});

**Comment by MarkPieszak** [comment]
I don't see anything unusual, so is there data from som of those APIs being delivered with the server-render but then it's wiped out after preboot?
@jeffwhelpley maybe this is something you know about?

**Comment by sudhakarphule1** [comment]
Yes..but data is there if we do view source/inspect element but it's not shown on UI. And when we change some CSS attribute during inspect element it start showing data...if I remove ngApp.ten(preboot) from client.ts then also it's able to render the data but that lead into other issue

**Comment by mhazy** [comment]
This sounds like it might be related to change detection and the new router. Change detection wasn't being triggered when components were created for the router outlet. We've been working around it by triggering a tick after the route is changed.

https://github.com/angular/angular/issues/9818

```
import {
  ApplicationRef,
  …,
} from '@angular/core';
import { 
  NavigationEnd, 
  …,
} from '@angular/router';
@Component({
  …,  
})
export class App implements OnInit {
  constructor(
    private router: Router,
    private applicationRef: ApplicationRef,
    …,
  ) {
    …
  }

  ngOnInit() {
    this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
        this.applicationRef.tick();
      }
    });
  }
};
```

**Comment by jeffwhelpley** [comment]
Hey, sorry about the confusion here @sudhakarphule1. The problem you are running into is a result of a change to preboot. @gdi2290 is right in the middle of making changes to the preboot universal integration, BUT the basic issue you are running into is that the preboot API has changed slightly. You need to do something like this:

```
import {prebootClient} from 'preboot';

// prebootClient is actually a generator for the preboot client object
var preboot = prebootClient();

ngApp()
.then(preboot.complete);
```

However, this would only work if you are using the latest preboot inline code. If you wait a couple days until RC5 is complete, this confusion should be cleared up, but let me know if you have any other questions in the meantime on this.

**Comment by kuldeepkeshwar** [comment]
@jeffwhelpley i'm using preboot v4.5.1 with below code
```
import 'angular2-universal/polyfills';
import {enableProdMode} from '@angular/core';
//import {prebootComplete} from 'angular2-universal';
import {prebootClient} from 'preboot';
var preboot = prebootClient();
enableProdMode();

import {ngApp} from './main.client';
document.addEventListener('DOMContentLoaded', () => {
  ngApp()
    .then(preboot.complete);
});
```

but this give "bundle.js:74 Uncaught TypeError: preboot_1.prebootClient is not a function" error.

earlier i was using preboot v2.1.2 and prebootComplete from 'angular2-universal' but this was causing flickering effect

**Comment by kuldeepkeshwar** [comment]
@jeffwhelpley thanks for the update,any idea on when will @gdi2290 release it ? we are using universal for our consumer site and we are almost in final phase to take it live so that we can plan accordingly

**Comment by jeffwhelpley** [comment]
@kuldeepkeshwar we are trying to get it out this weekend. Will let you know.

**Comment by gdi2290** [comment]
can you try again with latest updates github.com/angular/universal-starter with latest preboot version
I'm going to close this to keep the issues down
