### ISSUE TITLE
bug(): Passing in properyValue as whole object into super.setElementAttribute causes parse5 to error out with str.replace is not a function.

### ISSUE THREAD

**Issue by visikov** [angular/universal#505]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**
- [x] universal

* **What is the current behavior?**

In the parent component:
`private article = { title: 'foo', author: 'bar' };`

Template:
`<article-component [articleData]='article'></article-component>`

This passes in the complete object into super.setElementAttribute in the setElementProperty method of NodeDomRenderer. This then gets passed down into parse5, which throws error `TypeError: str.replace is not a function`

The same behavior is present if a number is passed in as well.

Quick and dirty solution, put the following right before super.setElementAttribute

```
if (typeof propertyValue !== 'string') {
    propertyValue = propertyValue.toString() || '';
}
```

I already have this in my local copy and it works well. Let me know if you'd like me to make a PR or if you have a more elegant solution.

**Comment by gdi2290** [comment]
done in 1.0.4 with angular rc5/rc6/rc7 support 
the propertyValue is only set as an Attribute if it's a string
