### ISSUE TITLE
expressEngine unable to render only in the server side?

### ISSUE THREAD

**Issue by dotansimha** [angular/universal#509]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this pull-request**
- [x] express-engine

* **Do you want to request a *feature* or report a *bug*?**
Possible bug, or confusing documentation.

* **What is the current behavior?**
`ExpressEngineExtraOptions` specifies two properties: `client` and `server`, which, I understand, should control the way of rendering the application. 
I assume that using `server: true, client: false, preboot: false` should render only in the server and server HTML, without bootstrap the application in the client side. 
This assumptions based on the following line from the design document of Angular Universal:

`Server/client - The developer should be able to specify at the route, page or component level whether a part of the app should be rendered just on the client, just on the server or both. `

(from "Optimizations" section).

At the moment, the server serves HTML content, but when the assets done loading, the application bootstraps in the client side instead of being completely static.

* **What is the expected behavior?**
The expected behavior is that the generated HTML won't even contain the `index.js` script, and remain static without bootstrap the application in the browser.

* **Please tell us about your environment:**
I am using the universal-starter, tried to modify the config under `server/main.node.ts`. 

At to moment I applied a workaround to remove the `index.js` script:

```
  res.render('index', config, (err, html) => {
    res.status(200).send(html.replace(`<script src="/index.js"></script>`, ""));
  });
```

- Angular version: 2.0.0-beta.4
- Browser: [all]
- Language: [all]
- OS:  [all]
- Platform: [all]

**Comment by MarkPieszak** [comment]
I can look into this, thanks for all the info @dotansimha

**Comment by gdi2290** [comment]
This was not intended for public use. There is no way for use to determine how the developer code works without having full control over the `index.html`. The demos worked because we were generating the index.html which gave us full control over client/server booleans. They should be removed in the next release
