### ISSUE TITLE
rebuild examples

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#510]

**Comment by MarkPieszak** [comment]
I have most setup if you want to take a look together sometime this week? The issue I was last stuck at was with the alias'ing, feel like you'd notice what's missing real quick.

**Comment by jeffwhelpley** [comment]
Yes, I agree with Mark. I started to look into this as well and after RC5 is in, we should talk about fixing the dependency issues among submodules so we can easily add back in an example (and it will help with other development/testing as well).

**Comment by dottodot** [comment]
Would also be nice to see a Angluar Cli (webpack) example too as it's pretty confusing trying to get the 2 working together.

**Comment by jeffwhelpley** [comment]
Yes, @dottodot that is something that Johannes Weber is working on now and should be ready in about a week.
