### ISSUE TITLE
No events trigger due to "compression-webpack-plugin" 

### ISSUE THREAD

**Issue by amitgaikwad712** [angular/universal#521]
We have used this seed project for our website development.
we have used "compression-webpack-plugin" for compress the index.js. It should result in "index.gz" I have been give that index.gz file path then it will don't triggers any DOM events like , click, Keyup and all other events related to "DOM"

**Comment by MarkPieszak** [comment]
Can you show some code, I'm not sure what you mean by this?
Do you have preboot on? What version, etc. @amitgaikwad712

**Comment by gdi2290** [comment]
can you try again with the latest changes github.com/angular/universal-starter
I'm going to close this to keep the issues lower
