### ISSUE TITLE
After changing the Title and meta data of site it shows page without css for few seconds.

### ISSUE THREAD

**Issue by amitgaikwad712** [angular/universal#523]
After changing the title and meta description of page using the universal. Initially it is not applying the css and it is appearing the page as like without css and then after few seconds it is applying the css.

**Comment by MarkPieszak** [comment]
Can you provide some code so I can take a look at what you're trying to do?

So you're saying `css` isn't being transferred from Universal? Are you using `styles` or `stylesUrl`.
I'd recommend using `style: require('./my-css.html')`. I'm not sure if stylesUrl is working fully just yet.

**Comment by u12206050** [comment]
@amitgaikwad712 How did you manage to set the meta data using universal. I have been trying now for the past three days without success.

I have a metaService through which I am trying to get a hold of the head element, and append meta elements, change attributes and set text with.

**Comment by scott-wyatt** [comment]
@amitgaikwad712 I'm going to guess that you are experiencing a server error, if there is any error at all the server render fails causing some text and maybe a few elements to appear.

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
