### ISSUE TITLE
context(headers or cookies) is getting lost for ajax call while rendering on server side

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal#525]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this Issue?**
- [x] universal

* **Do you want to request a *feature* or report a *bug*?**
-bug

* **What is the current behavior?**
-context(headers or cookies) is getting lost for ajax call while rendering on the server side.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

-Normally on the client side,context is maintained for ajax call i.e if a page is delivered with a cookie (city=ny) then this cookie will flow for the ajax call ('api/dosomething') made from the page,
but while rendering the page on the server side ,ajax call loses the context. by default, only one header('Angular 2 Universal') is present there.

* **What is the expected behavior?**
-context(headers,cookies) should be maintained for ajax call while rendering on the server side.

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.4
- Browser: [all  ]
- Language: [all ]
- OS:  [all ]
- Platform: [ NodeJs ]

**Comment by jeffwhelpley** [comment]
So, what you need to do is something along the lines of:

1. In your server side universal configuration, you should have access to the cookies (i.e. typically via request object in Express or some equivalent in other server side frameworks). Set that value in a universal provider.
2. Whenever you make your http/ajax call, you will need to make sure that token you set in the universal providers is pulled in via DI and then set in the http/ajax header to the API.

We do have plans to make this much easier in the future and part of the framework, but you should be able to build this relatively easily on your own right now. If you run into issues, let me know and we can do a screen share later this week.

**Comment by bohacc** [comment]
Please, can you show me any example, how implement cookie in angular universal?
I do not know how to do that point 2.

**Comment by kuldeepkeshwar** [comment]
@bohacc 
have a look at 

https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.node.ts
https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.browser.ts
https://github.com/kuldeepkeshwar/universal-starter/tree/master/src/common/utils

for second point , you need to write a wrapper of http service which can pull cookies/headers and set them in http request

@jeffwhelpley hope this is the right way to do it

**Comment by jeffwhelpley** [comment]
@kuldeepkeshwar so are you saying what you have here works or does not work? The looks correct to me, but if it doesn't work it must be something with the zone setup. In any case, please keep in mind that we will have a change in a future version of Universal that provides a cleaner way to get a handle on the request object so you don't have to use the zone. This is only temporary.

**Comment by kuldeepkeshwar** [comment]
@jeffwhelpley yes, it works and definitely this is a temporary solution.
As per my knowledge, @gdi2290 is working on `window` APIs

**Comment by jeffwhelpley** [comment]
Please follow #273 for this

**Comment by bohacc** [comment]
@kuldeepkeshwar Please somewhere you still have the http wrapper of service? https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.node.ts
https://github.com/kuldeepkeshwar/universal-starter/blob/master/src/main.browser.ts
https://github.com/kuldeepkeshwar/universal-starter/tree/master/src/common/utils, 
url is not found.

**Comment by teabagp** [comment]
@kuldeepkeshwar you still have these examples? Links are not found

**Comment by kuldeepkeshwar** [comment]
@bohacc @teabagp you can check [lazy-route](https://github.com/kuldeepkeshwar/universal-starter/tree/lazy-route/src/common/utils) branch

**Comment by intergleam** [comment]
so how do I access access in Universal?
