### ISSUE TITLE
Import Bootstrap and Jquery

### ISSUE THREAD

**Issue by martinop** [angular/universal#527]
How I can import bootstrap?

Jquery was imported in the plugins in the webpack.config, but how i can import bootstrap js?

**Comment by beckmeindia** [comment]
@martinop could you tell me how are you integrating this repo with webpack for rc5/rc6 (because the universal starter repo with webpack isn't updated to rc5/rc6 I believe)

**Comment by MarkPieszak** [comment]
@martinop You can follow issue #512 if you've reported this to the correct Repo. Universal at the moment has no support for jQuery.

@beckmeindia rc5/6 is coming, it's still not completely finished up & published.
