### ISSUE TITLE
List browser global that we need to support in Universal

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#534]
The next version of Universal can support/mock any browser global so please list out any of the that are the most important ones for me to make sure you can use it.

> It's worth noting there is a best practice way of dealing with 3rd party services that should be considered before falling back to these supported globals

**Browser**
- \- [x] `document`
- \- [x] `document.querySelector`
- \- [x] `document.querySelectorAll`
- \- [ ]  `document.cookie`
- \- [ ]  `XMLHttpRequest`
- \- [ ]  `fetch`
- \- [ ] `localStorage`
- \- [ ] `navigator`
- \- [ ]  `history`
- \- [ ]  `location`
- \- [ ]  `navigator`
- \- [ ]  `localStorage`
- \- [ ]  `sessionStorage`
- \- [ ]  `window` (please list out which properties you're using on `window` and how you use it)
- \- [ ]  `window.pageYOffset`
- \- [ ]  `window.pageXOffset`
- \- [ ]  `window.scrollTo`
- \- [ ]  `window.addEventListener`
- \- [ ] **{{ list_your_global }}**

**Common Libs** (with globals)
- \- [ ]  jQuery
- \- [ ] **{{ list_your_global }}**

**Research** (we need to determine if possible)
- \- [ ] Polymer
- \- [ ] Foundation
- \- [ ] d3
- \- [ ] videojs
- \- [ ] angularfire2
- \- [ ] firebase
- \- [ ] @angular2-material

**Supported** (so far)
- \- [ ] **{{ }}**

Twitter Poll
https://twitter.com/gdi2290/status/776893828045246466

The reason for this is to allow faster adoption of Universal JavaScript with components that the developer may or may not have control over

Please leave a comment of a browser global that you use (if `window` make sure to include some of the properties or functions used) and what you're using it for to make it in the next release

update: 
added research list
added polymer

**Comment by MarkPieszak** [comment]
Polymer would be a nice addition if it's possible.

**Comment by rogerpadilla** [comment]
Polymer++

**Comment by rogerpadilla** [comment]
Also Angular 2 Material

**Comment by josiah1888** [comment]
Supporting `window` would change the game for me

**Comment by gdi2290** [comment]
which properties on `window` does everyone use?

**Comment by buu700** [comment]
[`self`](https://developer.mozilla.org/en-US/docs/Web/API/Window/self)

**Comment by gdi2290** [comment]
@rogerpadilla I have material support added to Universal 2.0.5 
https://github.com/angular/universal-starter/commit/b34cfff1eeed79b66ff5c52f77b7175806e0884d

**Comment by kuldeepkeshwar** [comment]
-localstorage 
-location
-scroll
-onload

**Comment by cyrilletuzi** [comment]
+1 for localStorage

**Comment by jimmythesaint82** [comment]
XMLHttpRequest

**Comment by pxwise** [comment]
window.history - navigation
window.navigator - 3rd party scripts using userAgent detection
window.localStorage - browser storage
window.sessionStorage - session data
window.onresize - custom lazyload functions
window.onorientationchange - custom lazyload functions
window.innerWidth - custom lazyload functions
window.innerHeight - custom lazyload functions

document.documentElement.clientWidth - custom lazyload functions, cross browser
document.documentElement.clientHeight - custom lazyload functions, cross browser

our 3rd party global libs:

Foundation
d3
videojs

**Comment by orangesoup** [comment]
- window:wheel (event)
- window:scroll (event)

3rd party:
- angularfire2
- firebase

**Comment by Koslun** [comment]
3rd party:

- angular2-google-maps

 Seems to currently be the most popular angular 2 google maps wrapper library, can specifically see [issue 668 angular-universal support](https://github.com/SebastianM/angular2-google-maps/issues/668)

**Comment by ireade** [comment]
Hi @gdi2290 , you mention that there is a best practice for dealing with 3rd party services, what is it?

**Comment by FrozenPandaz** [comment]
Custom Elements would be interesting.

**Comment by aaltotsky** [comment]
- [ ] document.createEvent
- [ ] document.createEventObject

**Comment by ishandutta2007** [comment]
- [x] window.ace

ace editor comes with [brace](https://www.npmjs.com/package/brace) module
I was suggested to [hack](https://github.com/thlorenz/brace/issues/40#issuecomment-153394160) into brace and write
```
if(typeof window == "undefined"){
     return false;
}
```
but it introduces [other errors](https://github.com/thlorenz/brace/issues/40) in code.
without supporting it I doubt if a production level work and doing something like [this](https://github.com/substack/browserify-handbook#browser-field) beats the purpose of universal's tenet of same reusable code for server and client altogether.

**Comment by dottodot** [comment]
@gdi2290 Any idea when this might b available? If not can you provide the information on the best practice way of dealing with 3rd party services as at the moment it's a bit of a nightmare trying to integrate certain features.

**Comment by MarkPieszak** [comment]
@dotoodot At the moment using `isBrowser` etc is probably the best option, unless you want to use DI and try and abstract some of the methods for the server.

What are you trying to use?

**Comment by dottodot** [comment]
@MarkPieszak One example is https://github.com/zefoy/angular2-perfect-scrollbar 

I'm using DI for some things such as 3rd party scripts which I've kind of got my head round but when it come to things like the above i.e loading a module just for the client I get a bit lost.

**Comment by MarkPieszak** [comment]
One thing you could try doing is creating a ghost/empty Component directive for it (that you inject in your server NgModule file. You might be able to pull something like that off, if it's real simple, just so that the server completely ignores it. Make sure you don't include the Module for that library in your server NgModule, only do that in the Client part.

```
@Component({ 
    selector: 'perfect-scrollbar'
})
export class PerfectScrollbar { }
```
   
You're right though, it would be helpful to document this more thoroughly, it's a bit of a complicated process!

**Comment by artaommahe** [comment]
window.matchMedia?

**Comment by owencooney** [comment]
@MarkPieszak I want to do something similar to @dottodot, exept with a window.localstorage service.. there's a nice post here: http://stackoverflow.com/questions/39085632/localstorage-is-not-defined-angular-universal/39098748#39098748 on an approach for using window.localstorage in angular-universal except that it produces an error on the server... details here   http://stackoverflow.com/questions/41430971/angular-universal-starter-localstorage-in-production-using-window-in-browser ... I'm sure I'm missing something simple and it sounds like the ghost/empty approach might work... What do you think? Is there a good way to wrap 

```
providers: [
    // ...
    UserService,
    {provide: LocalStorage, useValue: {getItem() {} }}
]
```

so that it doesn't generate an error? (Many thanks and hope this is the right place for a question like this)

**Comment by MarkPieszak** [comment]
@owencooney You'd basically want to do a similar thing, so for your main.client providers, make sure `LocalStorage` (shown above) uses a BrowserStorage class that uses `localStorage / sessionStorage`. So make getItem / setItem methods (etc) that end up doing `localStorage.getItem(key)` for example. 

While in your main.node list of providers, for that `LocalStorage`, provide some MockStorage class, that has the same implementation (getItem/setItem/etc) but they do nothing.

That should do it! That's the gist of dependency injection magic :)

**Comment by owencooney** [comment]
@MarkPieszak awesome, I'll give that a go! Thanks a mil Mark!

**Comment by gdi2290** [comment]
won't be supported officially 
https://github.com/angular/angular/issues/13822

**Comment by jkuri** [comment]
I just find a workaround to avoid `if (typeof window === 'undefined') { return; }` in every case when dom is used directly. just use `jsdom-global` package as `require('jsdom-global')();` in in the main module or somewhere. no need to worry about workarounds anymore.

**Comment by MarkPieszak** [comment]
I get error `Error: Cannot find module "."` when trying to add it to the main.node file, how are you implementing it?

**Comment by jkuri** [comment]
I use it like so https://github.com/jkuri/angular-rollup-starter/blob/master/scripts/lib/prerender.ts#L39

**Comment by jkuri** [comment]
@MarkPieszak make sure you have both `jsdom` and `jsdom-global` installed, maybe thats the issue.

**Comment by MarkPieszak** [comment]
Interesting, yeah I tried both. Let me try with a fresh blank repo.

**Comment by martinop** [comment]
Doesnt work for me, this generate other errors

**Comment by hiepxanh** [comment]
angularfire 2 wont work because XMLHttpRequest not available

**Comment by Toxicable** [comment]
@hiepxanh it is avialable through something like @angular/common/http

**Comment by hiepxanh** [comment]
@Toxicable I mean, angular universal won't work with third party library like angularfire 2, when that lib making some request, I have to add:
`(global as any).XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;`
to the top of server.ts to clear that error.

**Comment by kaynz** [comment]
Does anyone know how to get https://github.com/biggora/express-useragent working with universal?

**Comment by adamzhu-xs** [comment]
In case anyone come here for angular ssr issue, you can use below webpack config for your server ts build.

{
      test: /hammerjs/,
      loader: "null-loader"
}

Similarly: https://medium.com/@puresmash/solve-hammer-js-issue-on-ssr-project-2e79664a7196

@egjs/hammerjs will work also, but it's not working properly with slider on mobile in my project.
