### ISSUE TITLE
NoJS, allow forms to work with JavaScript turned off

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#54]
The app needs to be able to work with JavaScript turned off. This is to allow older browsers (legacy) to function or large enterprise companies with crazy restrictions. Currently the links should be able to work with no problem. formDirectives(server)

this is done via `action` attribute in the `<form>` tag which makes a post request
- [x] Decorate for `<form>` tags with `action` and `method` attributes
- [x] Provide a way to pass data from the post request to the server
- [ ] Provide a way to invoke the correct method via submit event on the server
- [ ] Provide a way to only send down markup
- [ ] Improve developer API

**Comment by tamascsaba** [comment]
Nice features :+1:

**Comment by mcpDESIGNS** [comment]
Good call Pat :+1:

**Comment by wesleycho** [comment]
For the submit event on the server, what would be necessary for that option? Would it be desired to plug in routing the action URI, or the user configuring the URI used for the action attribute?

Also what are the thoughts on how to determine if markup only is to be sent down? That seems like a problem perhaps separate from this in particular, and may be a larger issue than just involving forms.

**Comment by gdi2290** [comment]
This feature was placed on the shelf soon after I started it. A client needs this feature so I'll be working on this again in March (moving to P2 from P3). With the compiler refactors done since the initial version it may be easier to get it working

**Comment by scarlz** [comment]
@gdi2290 We also require this feature for a large-scale project, and wondered how successful you were in implementing this for your client? I realise this feature is tagged with P2 and there is no milestone set, but in terms of viability, is there any expectation on when this might land?

**Comment by jamesbirrellgray** [comment]
@gdi2290 Is there a pull request or repo for this work you started? I work on a gov.uk project and we would like to contribute.

**Comment by thomasmeadows** [comment]
I thought this was supposed to be one of the reasons for server side rendering in a2.  Many government entities need this and some companies are strict and allow very little or no XMLHTTP request.

**Comment by MarkPieszak** [comment]
There is a large revamp / restructuring of Universal going on, but this is definitely a tough but important thing to have working (as you said for government etc agencies). We might have to wait for the restructuring before continuing on with this, but I'll try to help as well to get this going. @scarlz @jamesbirrellgray @thomasmeadows

**Comment by jamesbirrellgray** [comment]
@MarkPieszak thank you, let me know if we can help in anyway :-)

**Comment by gdi2290** [comment]
won't be supported officially 
https://github.com/angular/angular/issues/13822
