### ISSUE TITLE
The selector "app" did not match any elements

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal#542]
* **I'm submitting a ...**
bug report

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

Just my guess

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
It shows `The selector "app" did not match any elements` on server side (terminal), the client side works well.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Here is a small repo of the bug: https://github.com/Hongbo-Miao/universal-bug
Just run `npm i`, then go to http://localhost:3000/ , you will see the error on the terminal.

* **Please tell us about your environment:**
Angular version: 2.0.0
OS:  Mac OS X

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I checked http://stackoverflow.com/questions/35644123/the-selector-my-app-did-not-match-any-elements but does not help.

**Comment by gdi2290** [comment]
the problem was including BrowserModule with UniversalModule where the it blows up on the server since it's not using the correct Node services

**Comment by gdi2290** [comment]
the solution to this error is either detecting that other platforms are included and provide docs

**Comment by Hongbo-Miao** [comment]
thanks!

**Comment by gdi2290** [comment]
np, can you create an issue about providing better errors when including other platforms with the UniversalModule

**Comment by Hongbo-Miao** [comment]
yeah sure!
