### ISSUE TITLE
better error report when include other platform with UniversalModule

### ISSUE THREAD

**Issue by Hongbo-Miao** [angular/universal#543]
- **I'm submitting a ...**
  feature request
- **What modules are related to this Issue?**
  universal
- **Do you want to request a _feature_ or report a _bug_?**
  feature
- **What is the current behavior?**

The error information is not very helpful.
When use 

``` ts
imports: [
  BrowserModule
],
```

in **main.node.ts**, it gives the error

> The selector "app" did not match any elements

which is not helpful.
- **What is the expected behavior?**
  Better report.
- **What is the motivation / use case for changing the behavior?**
  https://github.com/angular/universal/issues/542

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
