### ISSUE TITLE
Include examples for testing envorinment

### ISSUE THREAD

**Issue by crebuh** [angular/universal#544]
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [x] universal
- **Do you want to request a _feature_ or report a _bug_?**

As discussed in the universal-starter-repo (https://github.com/angular/universal-starter/issues/165) it would be great to have some examples how to integrate a testing environment using Karma.

**Comment by jeffwhelpley** [comment]
We will get to this, but FYI, for most of my server side testing I just use Jasmine or Mocha/Chai without Karma. I will work on getting examples up with docs in the future.

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
