### ISSUE TITLE
Quick question on server rendering

### ISSUE THREAD

**Issue by mwaaas** [angular/universal#554]
Am a bit new in server rendering idea in angular. I have two questions: 
1. Where will server rendering be running on the browser or at the server
2. If it is at the server does it integrate well with nginx

**Comment by scott-wyatt** [comment]
The nignx part is kind of irrelevant here if that's how you are serving your node application.  The `server` is a node.js application that render's the application as if the client browser had rendered it and then servers the compiled html to the client where Angular then boots and continues where the server left off so to speak. 
1) The rendering happens on the server, and then the client re-renders once the app is served. 
2) You can setup nginx to proxy a node.js application, so yes.

**Comment by MarkPieszak** [comment]
@scott-wyatt is spot on here.

You could integrate with whatever you chose, you just need to to serialize the application with Universal so that it pre-renders it as a String to the client.

**Comment by mwaaas** [comment]
@scott-wyatt @MarkPieszak  Thanks its a bit more clearer now
