### ISSUE TITLE
Could i use it in a spring MVC based java web project

### ISSUE THREAD

**Issue by lihxhit** [angular/universal#555]

**Comment by MarkPieszak** [comment]
I don't believe Java->Universal integration has been done by anyone just yet. You can see the issue here (https://github.com/angular/universal/issues/280).

**Comment by gdi2290** [comment]
Hi, thanks for creating an issue and your interest in Angular Universal. As @MarkPieszak said you can follow the https://github.com/angular/universal/issues/280 issue for Java backend support with Angular Universal. Thanks!
