### ISSUE TITLE
What is the best way to implement Google Ads (DFP) and GA

### ISSUE THREAD

**Issue by esakkikrishnan** [angular/universal#562]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [X] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .NET | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

# Since Angular is removing every script tag I add,
1. what would be the best way to do Google Ads specially DFP
2. What would be the best way to Implement Google Analytics and ComScore

**Comment by scott-wyatt** [comment]
For Ads:
If you set the script tag as a variable and then use the `[innerHTML]` and bypass the security with a sanitizer, it should work, but use this with extreme caution because you are trusting a 3rdparty source.
```ts
...
  ad: string;

  constructor(
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit() {
      this.ad = this.sanitizer.bypassSecurityTrustHtml('<script>GOOGLE AD</script>');
  }
...
...
<div [innerHtml]="ad"></div>
...
```
For Analytics:
We personally use https://github.com/angulartics/angulartics2

**Comment by jeffbcross** [comment]
https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
