### ISSUE TITLE
How to add Title & meta tags dynamically on server side for SEO

### ISSUE THREAD

**Issue by rahulsgit** [angular/universal#563]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [X] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [X] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .NET | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

# How to add Title & meta tags dynamically on server side for SEO

**Comment by crebuh** [comment]
@rahulsgit 

maybe this [post](https://builtvisible.com/universal-angular-2-server-side-rendering-seo-crawl-friendliness/) is something you are searching for?

**Comment by drejohnson** [comment]
@crebuh That's solution seems outdated. You can't use EventEmitter in a service.

**Comment by FrozenPandaz** [comment]
@drejohnson You can use an Observable instead.

**Comment by rahulsgit** [comment]
@FrozenPandaz Can you provide a working example for same

**Comment by jeffbcross** [comment]
Please see https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
