### ISSUE TITLE
Get AoT working

### ISSUE THREAD

**Issue by pxwise** [angular/universal#566]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

feature

* **What is the current behavior?**

Cannot compile AoT without metadata.json config.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
n/a

* **What is the expected behavior?**

Compile with AoT by default.

* **What is the motivation / use case for changing the behavior?**

Perf

* **Please tell us about your environment:**

- Angular version: 2.0.0
- Browser: all
- Language: all
- OS:  all
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by jeffwhelpley** [comment]
Consolidating this with #540
