### ISSUE TITLE
httpservice call did not display in view-source .

### ISSUE THREAD

**Issue by percinor** [angular/universal#568]
when i use httpservice grab data from localhost ,the web page success and  display well in tag ul list table.use ngfor,
![1](https://cloud.githubusercontent.com/assets/16224957/19012524/1a9937be-87eb-11e6-904b-ac7f25fd8ec4.JPG)
but these content data  did not display  in html view-source , did universal rendering table in html work error?
![3](https://cloud.githubusercontent.com/assets/16224957/19012529/29567fd2-87eb-11e6-8f5a-c8c3babf5eca.JPG)

**Comment by MarkPieszak** [comment]
Try upgrading Zone.js dependency in your package json to 0.6.23 instead of 21. 
That should do the trick for now.

**Comment by MarkPieszak** [comment]
This is something on the Zone side that needs to be fixed, because 23 can potentially cause other issues, but let us know if anything else comes up!

**Comment by gdi2290** [comment]
can you try zone version 0.6.25 which should be tracking http now

**Comment by percinor** [comment]
i update zonejs to 23 or 25, if  httpservice call web json  file ,it work very well .but if  i  modify src/server.ts to connect  localhost mysql on express , in zonejs 23 ,25   condition ,  could not start / but  in zonejs21 condition ,web page could display  ok  but viewsource  have no data,

in zonejs23,25 error message 

[nodemon] starting `node dist/server/index.js`
D:\mediflip\an2un\universal-starter\node_modules\mysql\lib\protocol\Protocol.js:
152
    .on('packet', function(packet) {   ^

TypeError: Cannot read property 'on' of undefined
    at Protocol._enqueue (D:\mediflip\an2un\universal-starter\node_modules\mysql
\lib\protocol\Protocol.js:152:5)
    at Protocol.handshake (D:\mediflip\an2un\universal-starter\node_modules\mysq
l\lib\protocol\Protocol.js:52:41)
    at Connection.connect (D:\mediflip\an2un\universal-starter\node_modules\mysq
l\lib\Connection.js:136:18)
    at Object.<anonymous> (D:\mediflip\an2un\universal-starter\dist\server\index
.js:433:12)
    at Object.<anonymous> (D:\mediflip\an2un\universal-starter\dist\server\index
.js:463:30)
    at __webpack_require__ (D:\mediflip\an2un\universal-starter\dist\server\inde
x.js:21:30)
    at D:\mediflip\an2un\universal-starter\dist\server\index.js:65:18
    at Object.<anonymous> (D:\mediflip\an2un\universal-starter\dist\server\index
.js:68:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by gdi2290** [comment]
@percinor can you create an issue in the angular/zone.js repo

**Comment by Reuvenc** [comment]
@percinor [There's already a PR](https://github.com/angular/zone.js/pull/475) which solves the issue you encountered.

**Comment by percinor** [comment]
@Reuvenc   i already modified util.ts and events.ts  like #475, but how to build it to dist package ,it didn't  like angular2 just run  npm start  or run tsc to build.  tks .
