### ISSUE TITLE
Universal Version going along with CLI 1.0.0-beta.16?

### ISSUE THREAD

**Issue by mindruptive** [angular/universal#569]
Im using the CLI 1.0.0-beta.16 and would like to know if there is a universal sample that goes along with the CLI 1.0.0-beta.16. The samples are great but I ran into some problems (script paths in package.json, had to pin typecript version to 2.0.0 because of "https://github.com/angular/angular-cli/issues/1917" etc.) 
The information under https://universal.angular.io/quickstart/ seems to be a bit outdated, too.
Thanks in advance

**Comment by jeffbcross** [comment]
Not really sure, here is the PR to watch: https://github.com/angular/angular-cli/pull/2318
