### ISSUE TITLE
feat: support consolidate.js

### ISSUE THREAD

**Issue by amitport** [angular/universal#574]
- **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [x] universal-next
- [x] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**
  I'm requesting a feature that will allow angular universal to be included as a renderer in [tj/consolidate.js](https://github.com/tj/consolidate.js)
- **What is the motivation / use case for changing the behavior?**
  Such support should allow universal to work with express3/4 and koa1/2 and will _consolidate_ the efforts required for supporting those frameworks.
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - see https://github.com/angular/universal/issues/503#issuecomment-251215725
  - whoever starts working on this should probably also start an issue in [tj/consolidate.js](https://github.com/tj/consolidate.js) and link it here

**Comment by gdi2290** [comment]
won't be supported officially 
https://github.com/angular/angular/issues/13822
