### ISSUE TITLE
Proposal: use a formatter for style rather than tslint

### ISSUE THREAD

**Issue by alexeagle** [angular/universal#575]
universal currently has style rules in tslint.json which must be manually adhered to.
I suggest we do the same as angular/angular, and just hook up `clang-format` to let the computer do the formatting.
It requires letting go of some personal style preferences, but I think this is worth it in exchange for never thinking about it again.

See my long rant on this: https://medium.com/@Jakeherringbone/why-linting-makes-me-yawn-cadbd9a51ca9#.l61gmzxjb

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
