### ISSUE TITLE
No ResourceLoader implementation has been provided

### ISSUE THREAD

**Issue by pitAlex** [angular/universal#579]
Hi,
I'm using the latest version of angular 2 and angular universal and whenever I try to use templateUrl or styleUrls in components I get something like this:

No ResourceLoader implementation has been provided. "file:///Users/.../css/home.css" 
No ResourceLoader implementation has been provided. Can't read the url "file:///Users/.../views/home.html"

**Comment by MarkPieszak** [comment]
@pitAlex This is a common problem, and I'm making sure it's documented somewhere how to properly use those.

You have 2 options though:
Either use **template** instead of *templateUrl*: 

    template : require('')` 

Or better yet, add **angular2-template-loader** to your webpack configuration, that way you can use both.

More info on it here: https://github.com/TheLarkInn/angular2-template-loader The readme should help you if you run into any issues.

Chain it to your current TS loader, and you'll be able to use both `styleUrl` & `templateUrl`

    loaders: ['awesome-typescript-loader', 'angular2-template-loader']

Let me know if it doesn't work for you somehow!

**Comment by pitAlex** [comment]
Using template like you mentioned, works. Thats how I am doing it now. But I wanted a way to load the css file also into page, and without webpack.

**Comment by jkuri** [comment]
also trying to use that without webpack, any workarounds? thanks.

**Comment by MarkPieszak** [comment]
Do you mean just a regular import "something.css"; ?
What error is that throwing, haven't tried that yet!

**Comment by jkuri** [comment]
Yes, I am using `templateUrl` with `moduleId: module.id` to get relative paths, but there's still message `No ResourceLoader implementation has been provided`. 
I manage to get solved with custom build https://github.com/jkuri/ng2-platform-node/blob/master/node-platform.ts#L776-L786 but not so familiar with that project so not sure if that's the right way.

**Comment by MarkPieszak** [comment]
Might have to ask Pat @gdi2290 for guidance on what is missing for SystemJS support, maybe you'd be interested in trying to tackle it? Currently it's webpack only. #283 old system issue

**Comment by jkuri** [comment]
Cool, thanks! Actually I am using this in rollup.

**Comment by gdi2290** [comment]
@jkuri can you make a PR with a simple test?

**Comment by waterfoul** [comment]
I've found a way to work around this error for now. It's a but of a hack so I would recommend that this isn't the long term solution but it will get people up and running. To make this work you need to add this file

(it's src/app/resource-loader below)
```ts
import * as path from 'path';
import * as fs from 'fs';
import {ResourceLoader} from "@angular/compiler";

export class FileSystemResourceLoader extends ResourceLoader {
	resolve(url: string, baseUrl: string): string {
		//Angular assembles absolute URL's and prefixes them with //
		if (url.indexOf("/") !== 0) {
			//Resolve relative URL's based on the app root.
			return path.join(baseUrl, url);
		} else {
			return url;
		}
	}

	get(url: string): Promise<string> {
		const appDir = path.join(__dirname);
		const templatePath = this.resolve(url, appDir);

		return new Promise((resolve, reject) => {
			fs.readFile(templatePath, 'utf8', (err, data) => {
				if(err) {
					reject(err);
				} else {
					resolve(data);
				}
			})
		});
	}
}
```

add these imports

```ts
import { FileSystemResourceLoader } from './src/app/resource-loader';
import { ResourceLoader } from '@angular/compiler';
import { platformNodeDynamic } from 'angular2-universal/node';
```

and add this property to the object which is passed to createEngine

```ts
	platform: (extraProviders) => {
		var platform = platformNodeDynamic(extraProviders);
		(<any> platform).cacheModuleFactory_old = platform.cacheModuleFactory;

		platform.cacheModuleFactory = (moduleType: any, compilerOptions?: any): Promise<any> => {
			if(!compilerOptions) {
				compilerOptions = {
					providers: [
						{provide: ResourceLoader, useClass: FileSystemResourceLoader}
					]
				}
			}
			return (<any> platform).cacheModuleFactory_old(moduleType, compilerOptions);
		}
		return platform;
	},
```

Basically this is intercepting the cache module factory call and adding a compiler options param if there isn't one. The new compiler options contains the ResourceLoader provider which is defined in the first file. The correct solution would either be to supply this resource loader as part of angular-universal or (probably better) allow us to pass in the compiler options as a property so we can do it ourselves.

**Comment by jonathan-casarrubias** [comment]
@waterfoul your patch works just great, thanks!

**Comment by nicky-lenaers** [comment]
@waterfoul this patch works great, thanks!

**Comment by Wefeedthetroll** [comment]
Might seem like a stupid post ( and it probably is ) but for those of you getting the " No ResourceLoader implementation has been provided " error while using the default starter kit with webpack and angular2-template-loader make sure that you **don't put any white space between templateUrl and colon**

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
