### ISSUE TITLE
Allow express-engine to pass errors to the callback

### ISSUE THREAD

**Issue by rjokelai** [angular/universal#580]
* **I'm submitting a ...**
- [x] feature request

* **What modules are related to this Issue?**
- [x] express-engine

* **Do you want to request a *feature* or report a *bug*?**

Feature: change to the current behavior with, e.g., a configuration flag.

* **What is the current behavior?**

The `express-engine` swallows the exception providing no means of handling it in the application code. The line in question is [here](https://github.com/angular/universal/blob/master/modules/express-engine/src/index.ts#L129)

If the angular application itself throws an error, its never propagated to the express handler in the `err` parameter.

* **What is the expected behavior?**

What I'd like to do:

```
res.render('index', { propagateError: true, /* other conf */}, (err, html) => {
  if (!err) {
    res.status(200).send(html);
  } else {
    // my error handling logic
    res.status(500).send('error rendering application on server');
  }
})
```

Currently, this is not possible, since the err is always `null` even if server render fails.

* **What is the motivation / use case for changing the behavior?**

To allow users of the express engine library to handle their own errors.

* **Please tell us about your environment:**

- Angular version: 2.0.1
- Language: Typescript 2.0
- Platform: NodeJs

**Comment by MarkPieszak** [comment]
PR https://github.com/angular/universal/pull/551 should fix this, at the moment things aren't bubbling up inner errors during the serializing process. This will help point out template errors / anything that causes the serializer not to finish properly, and in the case of express-engine (which calls it), it'll be able to capture those errors.

**Comment by gdi2290** [comment]
can you try `angular2-universal` 2.1.0-rc.1 where this is merged. thanks!
