### ISSUE TITLE
style.innerText undefined for older version of Mozilla Firefox.

### ISSUE THREAD

**Issue by ZiyedBenAhmed** [angular/universal#586]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *~~feature~~* or report a *bug*?**
innerText is not defined for version < 45 on Mozilla Firefox.

* **What is the current behavior?**
`style.innerText` is undefined for version older to 45 on Mozilla Firefox: 
https://github.com/angular/universal/blob/master/modules/universal/src/browser/universal-module.ts#L102-L103
Here is the support for innerText. Not sure what is the expected support for Universal.
[Support](http://caniuse.com/#search=innerText). You have to click on showAll to see previous version.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Install a version older of Mozilla Firefox and run any project with angular universal.
![screen shot 2016-10-10 at 12 34 44 pm](https://cloud.githubusercontent.com/assets/17579411/19283774/03251110-8fa8-11e6-871a-a5403d448460.png)

* **What is the expected behavior?**
This should work on older version.

* **What is the motivation / use case for changing the behavior?**
Error on rendering the page , blocking the application.

* **Please tell us about your environment:**

- Angular version: 2.0.0
- Browser: [Firefox 43]
- Language: [TypeScript 2.0.3]
- OS:  [Mac OS X]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I could send a PR for the changes. We basically want to use textContent as fallback, this is supported for older version of Mozilla. [Support](http://caniuse.com/#search=textContent). You have to click on showAll to see previous version.
Replacing`style.innerText` by `(style.innerText || style.textContent)` in [here](https://github.com/angular/universal/blob/master/modules/universal/src/browser/universal-module.ts#L102-L103) fix the issue.
I can make a PR if this issue is valid and universal want to support older version of Firefox.

**Comment by gdi2290** [comment]
can you try `angular2-universal` 2.1.0-rc.1 where this is merged

**Comment by ZiyedBenAhmed** [comment]
Yes, it's fixed. Thanks 👍
