### ISSUE TITLE
SyntaxError: Unexpected token import; import { ChangeDetectionStrategy } ; ^^^^^^ 

### ISSUE THREAD

**Issue by esakkikrishnan** [angular/universal#588]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [X] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
error

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0-rc.X
- Browser: [all ]
- Language: [TypeScript X.X]
- OS:  [Windows]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**ISSUE**
\node_modules\@angular\core\src\metadata\directives.js:8
import { ChangeDetectionStrategy } from '../change_detection/constants';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (\dist\server\index.js:1799:18)
    at __webpack_require__ (\dist\server\index.js:21:30)

**Comment by esakkikrishnan** [comment]
The issue was that I import a wrong module.
I apologize for the mistake

**Comment by thebarada** [comment]
@esakkikrishnan so how you fix it? what module you imported?
because I have same error

**Comment by esakkikrishnan** [comment]
In my case I imported a wrong module for input I used webstrom so it automatically imported a wrong module, I rectified by importing input module from angular core. If possible provide the import statements

**Comment by phoenix3008** [comment]
@esakkikrishnan - thanks, I had the same problem, now it's ok)

**Comment by thebarada** [comment]
@esakkikrishnan oooh! thnx a lot!
