### ISSUE TITLE
Create Node version for Router 

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#60]
The router needs to be able to run on the server. History and other services needs to be replaced with Server versions. First let's create a version that works using the Mock version before converting it. 
Similar to https://github.com/angular/universal/issues/50

**Comment by gdi2290** [comment]
@manekinekko do you want to try this one out? you should only have to replace `LocationStrategy `

**Comment by manekinekko** [comment]
sure. I'll look at it tonight.

**Comment by gdi2290** [comment]
from gitter:
<img width="485" alt="screen shot 2015-08-12 at 3 16 04 pm" src="https://cloud.githubusercontent.com/assets/1016365/9238156/15c27fbc-4105-11e5-9126-998eb4ab3b97.png">

I like your proposal and we can mock it out for now so the router service won't error out on the server. Location on the server is questionable since history it’s fundamentally stateful. We can experiment with something like a UserSessionService later
For the warning you're seeing check out 
[custom_typings/ng2](https://github.com/angular/universal/blob/master/custom_typings/ng2.d.ts)
and create an `"angular2/src/router/location_strategy"` module

**Comment by manekinekko** [comment]
@gdi2290  I'll write some basic tests and push a PR.

**Comment by gdi2290** [comment]
@manekinekko  thanks :+1:

**Comment by gdi2290** [comment]
I'm going to rename the file to `router_server.ts`

**Comment by gdi2290** [comment]
close via https://github.com/angular/universal/commit/c07a18a1cd086657536827980e95bea1a6a9bfa6
