### ISSUE TITLE
angular2-gulp-prerender contains local dependencies in package.json

### ISSUE THREAD

**Issue by mindruptive** [angular/universal#601]
Seems like an error dev-dependencies (?)

node 6.5
npm 3.10.8
windows 10
universal-starter 2.0.0

`npm install angular2-gulp-prerender@latest`

package.json of this module contains

```
  "devDependencies": {
    "angular2": "2.0.0-beta.13",
    "angular2-universal": "file:../universal",
    "preboot": "file:../preboot",
```

My goal is to prerender all routes to static html files in order to deploy them to a regular http-server without having to use express. So it does not have to be the gulp pre-renderer. I'd appreciate hints on any other methods. 

Thanks a lot

**Comment by MarkPieszak** [comment]
I don't believe Gulp prerender has been re-worked since we had some major API changes within Universal itself, so that would explain it :) 

I'll take a look and get back to you.

**Comment by mindruptive** [comment]
Thanks a lot!
As mentioned, any hint how to set up pre-rendering of static html artifacts would be highly appreciated. :-)
Best

**Comment by pskhodad** [comment]
i think you can follow webpack example in repo. 
https://github.com/angular/universal/blob/master/examples/webpack/webpack.config.ts
it should generate index.html having pre-rendered content

**Comment by gdi2290** [comment]
won't be supported in ng4 
https://github.com/angular/angular/issues/13822
