### ISSUE TITLE
Bootstrapping an AOT app requires platformUniversalDynamic() which still ships RuntimeCompiler

### ISSUE THREAD

**Issue by alxhub** [angular/universal#602]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**

bug!
- **What is the current behavior?**

Bootstrapping with proper support for prerender requires calling `platformBrowserDynamic()`, even with AOT compiled apps. The issue is that this platform includes `RuntimeCompiler`, which defeats the bundle size benefits of AOT.
- **What is the expected behavior?**

There should be a separate `platformUniversal()` which doesn't ship the `RuntimeCompiler`.

**Comment by kuldeepkeshwar** [comment]
@gdi2290 @jeffwhelpley 
any way or workaround to avoid this ?

**Comment by gdi2290** [comment]
@kuldeepkeshwar  there's a workaround in [universal-starter](https://github.com/angular/universal-starter)
in webpack include these plugins for the client build

  new webpack.IgnorePlugin(/@angular(\\|\/)compiler/),
  new webpack.IgnorePlugin(/dom(\\|\/)debug(\\|\/)ng_probe/),
  new webpack.IgnorePlugin(/dom(\\|\/)debug(\\|\/)by/),

and replace 

import { platformUniversalDynamic } from 'angular2-universal/browser';

with

import { platformBrowser } from '@angular/platform-browser';

**Comment by gdi2290** [comment]
in webpack you can manually remove modules. in this case we're also removing some debug modules included in angular

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
