### ISSUE TITLE
minify rendered HTML

### ISSUE THREAD

**Issue by kuldeepkeshwar** [angular/universal#605]
rendered HTML should be in minified form ,current behavior increases the response size mainly because of generated style tags and preboot script

**Comment by nicowernli** [comment]
That could be done with an express middleware. I think (just personal opinion) that there is no need to add it to the platform

**Comment by kuldeepkeshwar** [comment]
@nicowernli although we minify the html during build process but during runtime angular/universal create style/script tags which are not minified

**Comment by gdi2290** [comment]
that's out of scope and should be requested in universal-starter. closing for now although it's a good idea to do
