### ISSUE TITLE
Fix 2.1.1 _private_ import issues

### ISSUE THREAD

**Issue by MarkPieszak** [angular/universal#606]
- **I'm submitting a ...**
- [X] bug report
- **What modules are related to this Issue?**
- [x] platform-node

---

In the latest Core/Compiler upgrades to **2.1.1**, compiler-private & core-private have changed a few things Universal uses.

**`__compiler_private__`** looks to of been removed from `@angular/compiler`.

SelectorMatcher & CssSelector (needed for Universal), seem to be public now.

Also **`_ViewUtils`** seems to be missing / removed from `__core_private__`
It looks like it was renamed to **`view_utils`** ?

Seems to fix it:

```
import {
  SelectorMatcher as SelectorMatcher211, 
  CssSelector as CssSelector211 } from '@angular/compiler';

let SelectorMatcher;
let CssSelector;

if (SelectorMatcher211 && CssSelector211) {
  SelectorMatcher = SelectorMatcher211;
  CssSelector = CssSelector211;
} else {
  const _compiler_private_  = require('@angular/compiler').__compiler_private__;
  SelectorMatcher = _compiler_private_.SelectorMatcher;
  CssSelector = _compiler_private_.CssSelector;
}
```

ViewUtils -> view_utils can be handled in a similar way.

**Comment by aiboy** [comment]
Can we merge this? Or is there any issues with this PR?

**Comment by stanbe** [comment]
Any news on this issue?

**Comment by MarkPieszak** [comment]
I'll talk to Pat about it today and let you guys know @stanbe @aiboy.
We have a nice workaround file for now you can use (and import at the top of your browser/node modules) for the time being as well. (https://github.com/angular/universal-starter/tree/master/src - you can see the workaround files in here)

**Comment by ScaryWolfMan** [comment]
Hi.  Is this issue fixed?  I am still getting this error, using angular2-universal version ~2.1.0-rc.1

**Comment by ScaryWolfMan** [comment]
@MarkPieszak I followed the link you posted and added those files to my project, and then imported the correct ones into my browser.module.ts and node.module.ts

Unfortunately I'm still getting the same error.  Here are my versions, if that is any help too:

    ```
"@angular/common": "~2.1.2",
    "@angular/compiler": "~2.1.2",
    "@angular/core": "~2.1.2",
    "@angular/forms": "~2.1.2",
    "@angular/http": "~2.1.2",
    "@angular/platform-browser": "~2.1.2",
    "@angular/platform-browser-dynamic": "~2.1.2",
    "@angular/platform-server": "~2.1.2",
    "angular2-express-engine": "~2.1.0-rc.1",
    "angular2-platform-node": "~2.1.0-rc.1",
    "angular2-universal": "~2.1.0-rc.1",
    "angular2-universal-polyfills": "~2.1.0-rc.1",
```

**Comment by MarkPieszak** [comment]
You have it setup similar to how the starters have it? Included at the top of each of those files? @ScaryWolfMan

**Comment by ScaryWolfMan** [comment]
@MarkPieszak Yep!  :(

**Comment by tinchou** [comment]
It isn't working for me with 2.2.3 either. But there's a 90% chance I'm
just too tired to work on this now.

**Comment by ScaryWolfMan** [comment]
I'm a noob but it seems like a pretty daunting task trying to manage all the various angular projects and making sure everything works. :o

**Comment by stanbe** [comment]
This error is rather annoying and the workaround is by definition just a workaround, not really satisfying. Is there still an issue with the pull request? @MarkPieszak @aiboy

**Comment by aiboy** [comment]
@stanbe I'm not a maintainer :/ so I can't do anything about it.

And yes, we have Angular 2.3 already, but I still can't update Angular-Universal. This is sad.

**Comment by MarkPieszak** [comment]
Let me make sure the workaround still works for the latest Angular release and I'll talk to @gdi2290 about it, see if it's possible to squeeze this in there! 
Apologies guys!

**Comment by ScaryWolfMan** [comment]
@MarkPieszak I've reverted to 2.10 and I'm able to run my project without any issues at the moment.

**Comment by fdambrosio** [comment]
how can we build with universal? We're started using angular2-webpack-starter

**Comment by MarkPieszak** [comment]
Check out the universal node starter to see what you need to add to the webpack-starter, check out the documentation.md file here as well that talks about the necessary files. @fdambrosio

**Comment by fdambrosio** [comment]
thanks @MarkPieszak we have "Call to Node module failed with error: TypeError: Cannot read property 'SelectorMatcher' of undefined" message error

**Comment by MarkPieszak** [comment]
If you're using the workaround I think you can't use Angular `2.3` as some other things changed.
As we move some Core things from Universal into AngularCore itself, it'll help alleviate problems like this from happening!

**Comment by ScaryWolfMan** [comment]
@MarkPieszak I was having the same issue, but I'm now using angular 2.1.0 and angular-universal 2.0.11.  no longer getting any issues :(

**Comment by dimonzav** [comment]
Workarounds from universal-starter repository is working well with Angular 2.4.1!

**Comment by MarkPieszak** [comment]
Oh that's great news 👍 haven't been able to check on holiday this week. @dimonzav

**Comment by szykov** [comment]
@dimonzav I just tried update to 2.4.1 version and adding files: __workaround.browser, __workaround.node.
Then adding appropriate import statements to server.ts and client.ts files and it didn't work. What did you do or what I did wrong?

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Comment by ParkourKarthik** [comment]
I tried the workaround. I'm still facing the problem in `angular@2.4.7`; currently using the latest `2.1.0-rc.1` version of Universal. Anything more to do?

**Comment by MarkPieszak** [comment]
Do you have it setup just like in the universal starter? @parkourkarthik

**Comment by ParkourKarthik** [comment]
I'm a noob and I'm using the **Asp.net Core with Angular** template. I faced this when I upgraded all my packages to the latest version. But now I downgraded all packages to the same in the template (`2.0.10`); so working for now.
I'm scared of upgrading the packages again. It seems there are multiple dependencies of packages which raise these errors; any guidelines would be helpful.

**Comment by MarkPieszak** [comment]
This template here has everything a little more up to date and is .net, take a look at the dependencies. https://github.com/MarkPieszak/aspnetcore-angular2-universal

Don't worry about warnings during install for now. @ParkourKarthik
