### ISSUE TITLE
[hidden]="true" not added to dom node when rendered on server

### ISSUE THREAD

**Issue by berndartmueller** [angular/universal#612]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
- **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender
- **Do you want to request a _feature_ or report a _bug_?**

bug
- **What is the current behavior?**

Using [hidden]="true" in template does not add "hidden" property in server-side rendered dom
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Using the latest angular universal version, simply try to use [hidden]="true" on any element inside template and render on server. Then in the rendered dom there is no "hidden" property present.
- **What is the expected behavior?**

"hidden" property should be added to dom node.
- **What is the motivation / use case for changing the behavior?**
## 
- **Please tell us about your environment:**
- Angular version: 2.1.0
- Browser: [all]
- Language: [TypeScript 2.0.3 ]
- OS:  [Mac OS X]
- Platform: [NodeJs]
- **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

It seems that the "hidden" property is set but during rendering it is not applied to the actual dom node.

**Comment by MarkPieszak** [comment]
Thanks for logging this! I'll take a look and see what I can find, this was at least working previously! Does using the 2.1.0-rc1 version of Universal help it by any chance?

**Comment by gdi2290** [comment]
can you try `[attr.hidden]="true"`

**Comment by berndartmueller** [comment]
@gdi2290 that is working! Thanks! But shouldn't it also work with just `[hidden]`?

**Comment by gdi2290** [comment]
it's not meant to work that way but we do try to convert some properties over to attributes.

**Comment by MarkPieszak** [comment]
strange, yeah hidden is in our attrToPro array, maybe something else changed that's stopping it from working. @gdi2290
