### ISSUE TITLE
 No NgModule metadata found for 'MainModule'. 

### ISSUE THREAD

**Issue by cfadvanced** [angular/universal#613]
Hi men,
I'm submitting a bug report, I download master and do npm install and then npm start and this is the message (widows 10):

C:\Users------\myproject\node_modules\@angular\compiler\bundles\compiler.umd.js:13726
                  throw new Error("No NgModule metadata found for '" + stringify(type) + "'.");
                  ^

Error: No NgModule metadata found for 'MainModule'.

My operating system is windows 10 and all other project based on nodejs and angular2 (angular cli) work properly.
 Thanks so much for help
Francesco
- Angular version: 2.0.0
- Browser: all  
- Language: TypeScript  
- OS: Windows 10
- Platform: NodeJs

**Comment by gdi2290** [comment]
@cfadvanced assuming you downloaded universal-starter there was a commit that reverted this error from happening
https://github.com/angular/universal-starter/commit/6a28e100f800bd679ed5a01c05bd6f90257d1f85
closing this for now but please reopen if you still have it
