### ISSUE TITLE
Does angular-universal support NgModule now?

### ISSUE THREAD

**Issue by webia1** [angular/universal#615]
After a while I wanted test angular-cli again and saw that the mobile flag was deactivated:

> The --mobile flag has been disabled temporarily while we await an update of angular-universal for supporting NgModule. Sorry for the inconvenience.

Would you please inform:  Does angular-universal support NgModule now?

**Comment by gdi2290** [comment]
yeah, for awhile now. you can download 2.1.0-rc.1 unless you're trying to use the cli which it's not merged in

**Comment by mwaaas** [comment]
@gdi2290  whats the eta when the feature will be merged to angularcli

**Comment by MarkPieszak** [comment]
@mwaaas Johannes @devCrossNet might be able to answer that one. It's in a branch of the CLI but I don't think it's been merged yet.

**Comment by devCrossNet** [comment]
@MarkPieszak as I know, Jeff Cross is working on a reimplementation of the `--mobile` flag. For the `--universal` flag we have to talk about publishing a separate npm package @jeffwhelpley, @gdi2290. Maybe we create an issue or talk in the slack channel. Unfortunately, I am not able to participate to hangouts during the next weeks.
