### ISSUE TITLE
Contributing guide

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#62]
Copy over from angular/angular

**Comment by manekinekko** [comment]
is this as simple as copying the [CONTRIBUTING.md](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) from the angular repo to this repo (plus some adjustments of course)?

**Comment by gdi2290** [comment]
yeah I want to save this for a new contributor or someone who is new to github

**Comment by manekinekko** [comment]
Sure! no worries :wink:
