### ISSUE TITLE
Update from git branch [fixed 2.1.1] to npm

### ISSUE THREAD

**Issue by nvs2394** [angular/universal#623]
Can you update new fixed to npm [2.1.1 fixed] 22 days ago but npm release a month ago.

**Comment by MarkPieszak** [comment]
I'm not positive, but we might be waiting on Core to fix the underlying issue? @jeffbcross Any ideas?
For now @nvs2394 you can take the __2.1.1.workaround.ts file here: https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/master/Client

And import it at the top of both client & server bootstrap files, and you'll be safe to use Core 2.1.1 (and higher) for now.

**Comment by nvs2394** [comment]
@MarkPieszak thank you !

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
