### ISSUE TITLE
Invalid server rendered page on https

### ISSUE THREAD

**Issue by pratts** [angular/universal#624]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
using running universal does not render updated elements on server side

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.'
This is the code that I used to run universal on https:
```
if(env === 'development') {
  let server = app.listen(process.env.PORT || 3333, () => {
    console.log(http on: http://localhost:${server.address().port});
  });
} else {
  var options = {
    hostname: 'www.myhost.in',
    key: fs.readFileSync('/home/myhost/www_myhost_in.key'),
    cert: fs.readFileSync('/home/myhost/www_myhost_in.crt')
  };

  require('https').createServer(options, app).listen(3333, function() {
    console.log(https on: http://localhost:3333);
  })
}
```

Is it the correct approach to run universal on https ?
If yes, then I am not getting the correct data in server rendered page. If I provide NODE_ENV=development then I am getting the server rendered page.

* **What is the expected behavior?**
Universal should properly render correct components on server side

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.0.0
- Browser: [ Chrome XX | Firefox XX ]
- Language: [ TypeScript X.X ]
- OS:  [Mac OS X | Windows | Linux ]
- Platform: [NodeJs ]
- Universal: 2.1.0-rc.1
- angular2-express-engine: 2.1.0-rc.1
- angular2-platform-node: 2.1.0-rc.1
- angular2-universal: 2.1.0-rc.1
- angular2-universal-polyfills: 2.1.0-rc.1

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I tried to run the server using command: NODE_ENV=production npm start

**Comment by MarkPieszak** [comment]
I'm not positive, but I can't really see anything wrong with what you have here, not sure if fs.readFileSync might be the culprit? @gdi2290 any ideas?

@pratts Can you post a repo, link to the rest of your server file just incase.
Are you certs ok as well?

**Comment by pratts** [comment]
Hello @MarkPieszak,
Below mentioned is the code I am using for server file. Certificates were ok. I also used a self signed certificate to test on my system, I had to use the line: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";`

`// the polyfills must be the first thing imported in node.js
import 'angular2-universal-polyfills';

import * as path from 'path';
import * as express from 'express';
import * as bodyParser from 'body-parser';
import * as cookieParser from 'cookie-parser';
var env = process.env.NODE_ENV || 'development';
var config = require('./backend/config/config')[env];
var fs = require('fs');

// Angular 2
import { enableProdMode } from '@angular/core';

import { createEngine } from 'angular2-express-engine';

// enable prod for faster renders
enableProdMode();

import { MainModule } from './main.node';

const app = express();
// app.use(express.static('common'));
const ROOT = path.join(path.resolve(__dirname, '..'));

// Express View
app.engine('.html', createEngine({
    precompile: true,
    ngModule: MainModule
}));
app.set('views', __dirname);
app.set('view engine', 'html');

app.use(cookieParser('Angular 2 Universal'));
app.use(bodyParser.json());
app.set('json spaces', 2);

// Serve static files
app.use('/assets', express.static(path.join(__dirname, 'assets'), {maxAge: 30}));
app.use('/common', express.static(path.join(__dirname, 'common'), {maxAge: 30}));
app.use(express.static(path.join(ROOT, 'dist/client'), {index: false}));

function ngApp(req, res) {
  res.render('index', {
    req,
    res,
    ngModule: MainModule,
    baseUrl: '/',
    requestUrl: req.originalUrl,
    originUrl: env=='production'?'https://myhost.com:3333':'http://localhost:3333'
  }, (err, html) => {
    res.status(200).send(html);
  });
}


// Routes with html5pushstate
// ensure routes match client-side-app
app.get('/', ngApp);

// use indexFile over ngApp only when there is too much load on the server
function indexFile(req, res) {
  // when there is too much load on the server just send
  // the index.html without prerendering for client-only
  res.sendFile('/index.html', {root: __dirname});
}
  app.get('*', function(req, res) {
    res.setHeader('Content-Type', 'application/json');
    var pojo = { status: 404, message: 'No Content' };
    var json = JSON.stringify(pojo, null, 2);
    res.status(404).redirect('/404_error');
  });

// Server
if(env === 'development') {
  let server = app.listen(process.env.PORT || 3333, () => {
    console.log(`http on: http://localhost:${server.address().port}`);
  });
} else {
  var options = {
    hostname: 'www.myhost.com',
    key: fs.readFileSync('./../server.key'),
    cert: fs.readFileSync('./../server.crt')
  };

  require('https').createServer(options, app).listen(3333, function() {
    console.log(`https on: http://localhost:3333`);
  });
}`

**Comment by FrozenPandaz** [comment]
Last time I checked the https node module wasn't the best option for serving a https server. I opted to use spdy, it works well for me. It's also h2.

**Comment by pratts** [comment]
Hello @FrozenPandaz , I looked for using https and express and found the above mentioned solution.
Regarding spdy, last time I checked I saw that it is deprecated and instead node-http2 should be used. But when I try to use node-http2, I face the error mentioned [here](https://github.com/molnarg/node-http2/issues/100). It is regarding node-http2 compatibility issues with express.

**Comment by FrozenPandaz** [comment]
The spdy node module was updated to be true http2, give it a shot. It works flawlessly in my experience with express and therefore universal.

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822

**Comment by ranjitnadar** [comment]
Https Server ride rendering issue not resolved in angular 4.

I am facing similar issue using http api url server side rendering working. With https server ride rending empty response. Tried https, spdy both is not working.
