### ISSUE TITLE
Flickering (rerender) when using a resolve in router

### ISSUE THREAD

**Issue by marklonquist** [angular/universal#625]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [X] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
Site flickers when client-side is loaded in - Using ng router resolve

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Use a resolver, which gets data via http (also tried using HttpCacheService)

* **What is the expected behavior?**
No flickering, as the data has already been resolved

* **What is the motivation / use case for changing the behavior?**
Remove the flickering

* **Please tell us about your environment:**
Angular version: 2.1.0
Browser: Chrome 54
Language: TypeScript 2.0.0
OS:  Windows
Platform: .NET

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
N/A

**Comment by MarkPieszak** [comment]
@marklonquist Hey Mark, can you post a little sample of the resolve you're doing just so I can make sure it's not something specific there? I'll test this out today and see if I can reproduce it!

**Comment by marklonquist** [comment]
@MarkPieszak I fixed the issue.. I had missed a spot with "Http". Changed it to "HttpCacheService" and did some minor tweaks to my own code, then it worked. :-)

Keep up the good work!
