### ISSUE TITLE
Rendering different apps on same node server instance

### ISSUE THREAD

**Issue by u12206050** [angular/universal#627]
* **I'm submitting a ...**
- [x] bug report
- [x] feature request

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

Ability to render a page for any given number of dynamic loaded modules(each belonging to a different project).

* **What is the current behavior and steps**
Currently I am able to dynamically include a compiled webpack-compiled js file which contains my one universal angular 2 built app and render a page for a specific path by using angular2-universal-render.

When I try and then load a second js file which contains another app entirely I get the following error: Cannot read property 'getMetadata' of __NAMEOFAPPMODULE_

I have  a suspected feeling it is because of the fact that the angular services and ngZone is already loaded in scope and can't be recreated again.

* **What is the expected behavior?**

Since I am just always rendering one page at a time, I would think that after a page is rendered then the app would be able to destroy itself somehow enabling another app to bootstrap and render a page

* **What is the motivation / use case for changing the behavior?**

Instead of having a node server for each of projects, I want to have a single one that can render all my static pages when requested, which I then use to push to ES. However since the views can become out dated I want to try a more dynamic approach.

* **Please tell us about your environment:**

- Angular version: 2.1.1
- Browser: [all  ]
- Language: [all  ]
- OS:  [all | ]
- Platform: [ NodeJs ]

* **Other information** 

This is the code I tried to use as a wrapper around each of my apps:

```
require("angular2-universal-polyfills");
const path = require("path");
const fs = require('fs');

const angular2 = require("@angular/core");
const renderer = require('angular2-universal-render');
angular2.enableProdMode();

const modules = require('./server');
const doc = fs.readFileSync(path.resolve(__dirname, './index.html'), 'utf-8');

module.exports = function () {
    return renderer.createRender({
      document: doc,
      ngModule: modules.MainModule
    });
};

```

It is this wrapper that I then import into my node server, when needed and then use to render a page like so:

```
var renderer = require('projects/'+__PROJECTNAME)();
renderer({
            preboot: {
                appRoot: ['app'],
                uglify: true,
                buffer: true
            },
            async: true,
            requestUrl: queueObj.page_url
        }).then(html => { pushContent(html); }
```

**Comment by MarkPieszak** [comment]
I'm not sure if this is an issue within Universal or potentially the [angular2-universal-render repo](https://github.com/AKIRA-MIYAKE/angular2-universal-render/blob/master/src/lib/create-render.ts#L47-L71).
Do you have a repo or anything we can see if there's something else obvious that might be causing this?

I'm not sure if it's the [Zone issue](https://github.com/AKIRA-MIYAKE/angular2-universal-render/blob/master/src/lib/create-render.ts#L61-L64) you were talking about, but it's possible?

**Comment by u12206050** [comment]
Sorry for the delay in response. 
Unfortunately we do not and cannot have our project as a public repo, however I do believe this will work for any two angular apps that you try and run with the same node server.

This is the latest error I get:

`Unhandled Promise rejection: Cannot enable prod mode after platform setup. ; Zone: <root> ; Task: Promise.then ; Value: [Error: Cannot enable prod mode after platform setup.] Error: Cannot enable prod mode after platform setup.
    at Object.enableProdMode (/root/prerender-server/node_modules/@angular/core/bundles/core.umd.js:6448:19)`

Now obviously both apps try to enable prod mode, but I can't understand why this error stops the entire module from running.

**Comment by MarkPieszak** [comment]
Are you running enableProdMode before you are setting up those apps by any chance?

**Comment by u12206050** [comment]
Yes, as you can see in my code snippet above I had: 

`const angular2 = require("@angular/core");
const renderer = require('angular2-universal-render');
//Here is the enableProdMode which I wrapped now with try-catch blocks
angular2.enableProdMode();
//This is where the app gets loaded
const modules = require('./server');`

**Comment by gdi2290** [comment]
will be fixed in ng4 
https://github.com/angular/angular/issues/13822
