### ISSUE TITLE
support for Zone.js 0.7.2?

### ISSUE THREAD

**Issue by alanpurple** [angular/universal#630]
I think Zone.js version dependency should be updated to 0.7.2, no?

**Comment by John0x** [comment]
Updating to 0.7.2 would solve a bug with http on the server.

**Comment by tjaartvanderWalt** [comment]
When trying to use angular2-universal with @angular/core@2.3.1 i get a peer dependency warning. **angular/core@2.3.1** needs zone.js@0.7.2 but **angular2-universal** needs zone.js@0.6.21

**Comment by gdi2290** [comment]
will be supported in ng4 
https://github.com/angular/angular/issues/13822
