### ISSUE TITLE
Angular cli + angular universal

### ISSUE THREAD

**Issue by vforv** [angular/universal#636]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [x] feature request

* **Do you want to request a *feature* or report a *bug*?**

Feature. It would be great if you consider to collaborate with peoples who created angular-cli. So It would be greate if in agnular-cli have option run angular with angular universal server.
Also it will be great if you can create some blog post or something like that, which show how to inplement angular universal into angular-cli projects?

Also please improve doc, it looks now like it is your internal project.

**Comment by MarkPieszak** [comment]
Hey @vforv, the Universal CLI is actually here (currently in a fork of the CLI)
https://github.com/devCrossNet/angular-cli

There should be all the needed instructions there. You can have it and the regular CLI installed at the same time. 😃 @devcrossnet made it all happen!

**Comment by devCrossNet** [comment]
@vforv there is a lot going on behind the scenes. Currently, the Universal-CLI is a little bit stuck in merging the Angular-CLI, it is also in Alpha. So please be patient.

**Comment by vforv** [comment]
@devCrossNet great job. I have some projects that I started with angular-cli, what you suggest me how to include angular universal inside that projects?

**Comment by devCrossNet** [comment]
@vforv if the universal-CLI works again it should be really easy to archive that. you run `ung init --universal` inside your project and put everything from your app.module into the two app-modules from universal.

But right know the universal-CLI is not stable.

**Comment by vforv** [comment]
That would be great When will be stable release?

**Comment by devCrossNet** [comment]
it is in the docs already. just read the first paragraph in the readme.md.

My goal is to have it stable again next week. But I have a surgery on Friday and I don't know if I am able to code on Saturday/Sunday.

But there is a PR that hopefully will solve most of the issues and we can get it to work soon.

**Comment by vforv** [comment]
I see this: `It supports Angular Universal (with --universal flag after ung new or ung init)` But you told me that we should change also  two app-modules from universal... 

Great, where can I find notification when it is stabile?

Good luck with surgery.

**Comment by devCrossNet** [comment]
https://github.com/devCrossNet/angular-cli#support-for-server-side-rendering

There is a section about universal. 

Thanks 🙂 I can write here if it is stable again.

**Comment by vforv** [comment]
That would be great, thanks.

**Comment by vforv** [comment]
Hello any news regarding this?

**Comment by devCrossNet** [comment]
@vforv there is a stable version again. but we're stuck for now, universal moves to @angular/universal. My fork is here: https://github.com/devCrossNet/universal-cli. you can use it but you can not use AOT or newer versions of Angular. We have to wait until the core team releases a new version of universal and maybe the angular-cli team will implement it (but I have no information on this).
