### ISSUE TITLE
Question: How to use querySelector ? Server says querySelector is not a function

### ISSUE THREAD

**Issue by haia212** [angular/universal#637]
Hello !

I am trying to use `document.querySelector` in a service to automatically update all meta tags in a page (it is based on ng2-meta : https://github.com/vinaygopinath/ng2-meta). 

`document` is injected in my service constructor as follow
```
constructor(@Inject(DOCUMENT) private document: any) 
```

The problem is that the server keeps displaying an exception 
```
EXCEPTION: this.document.querySelector is not a function
```
What I am doing wrong ? How to use querySelector properly ?

I am using universal v2.1.0-rc.1. According to this repository, `querySelector` is supported by universal.

**Comment by ScaryWolfMan** [comment]
Correct me if I'm wrong, but don't you need to import isBrowser from ng2-universal, and create a conditional where if that's true, then do your querySelector.

**Comment by haia212** [comment]
Yes it is a solution, except that I am using universal for seo purpose. I would like to render the meta tags of my html on server side. That's why I am using querySelector and I need it on server side (not in a isBrowser if).
According to this issue (https://github.com/angular/universal/issues/534) querySelector is supposed to be supported, no ?

**Comment by ScaryWolfMan** [comment]
Oh ok.  You can try using the meta service as is done here:  https://github.com/angular/universal-starter/blob/master/src/angular2-meta.ts

**Comment by haia212** [comment]
Thank you ! It works !

**Comment by ScaryWolfMan** [comment]
No problem dude!  Good luck
