### ISSUE TITLE
refactor batter out and use gulp in gulpfile 

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#64]
configuration is not clear. We have configuration living in task file and gulpfile. Having configurations in place place would allow for simpler reasoning on each moving part. Having a task per file limits the ability to compose multiple tasks. The repo doesn't need this level of abstraction just yet and would benefit more by having one gulpfile either requiring the configuration or keeping it inline

**Comment by manekinekko** [comment]
@gdi2290 do you need me to move all gulp tasks into one single gulpfile ?

**Comment by manekinekko** [comment]
I am on it.

**Comment by gdi2290** [comment]
@manekinekko yeah all in one gulpfile

**Comment by manekinekko** [comment]
PR sent (https://github.com/angular/universal/pull/69)

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/pull/69
