### ISSUE TITLE
Does not load styles on Server.

### ISSUE THREAD

**Issue by goriunov** [angular/universal#641]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **What is the current behavior?**
Universal do not render styles on the server, it loaded only in the browse therefore users have some time with out styles.

* **What is the expected behavior?**
Render styles on the server and send with html in head. On request.

* **Please tell us about your environment:**

- Angular version: 2.1.0
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [x Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .NET | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
How are you trying to render them? StyleUrls need require() or a webpack loader (on the server at least) to load properly. Let me know so I can help out!

**Comment by goriunov** [comment]
I am using universal cli. And as i can assume that it has template loader so it should work how ever it does not.

**Comment by goriunov** [comment]
As well i tested it with styles inside of ts and it worked some times, like not always

**Comment by goriunov** [comment]
The styles were added in router outlet component worked odd

**Comment by gdi2290** [comment]
will be supported in ng4 
https://github.com/angular/angular/issues/13822
