### ISSUE TITLE
Recommended Static HTML File Pre-Rendering is not working

### ISSUE THREAD

**Issue by StefanRein** [angular/universal#647]
* **I'm submitting a ...**
- [X] bug report
- [X] feature request

* **What modules are related to this Issue?**
- [ ] express-engine
- [X] grunt-prerender
- [x] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
I would think it is a bug, since everywhere I search I find: Go ahead and use static rendered views.
But if not, it would be immediately a feature request. 

* **What is the current behavior?**
It does nothing with gulp- and grunt-prerender.

* **What is the expected behavior?**
The renderer should output static rendered HTML files from the Angular application.

* **What is the motivation / use case for changing the behavior?**
This seemed to work half a year ago and somewhere stated that this would be not that hard to implement again.
https://github.com/angular/universal/issues/601#issuecomment-254946466

* **Other information**

Hey guys, as stated here:

https://github.com/angular/universal/blob/master/DOCUMENTATION.md#-what-about-caching

You say: 
>> In fact, it is our recommendation that **your first option** should be using Angular Universal **pre-rendering to generate static HTML files** so you don't need any dynamic rendering at run time and everything can be cached on a CDN.

But the implementation is since 30 august 2016 deleted and still empty:
https://github.com/angular/universal/commit/4cb29ba7e0eb98efbcbffba0e23709978a1c572a?diff=unified

Do I need to write my own implementation for requesting each route and save the resulting static HTML files?

Maybe it is just confusing for me, that's stated it should work - but it is not.. or maybe I am just missing something obvious here.

Thank you very much for your help and time in forward.
Stefan Rein

**Comment by gdi2290** [comment]
will be supported officially ng4 
https://github.com/angular/angular/issues/13822
