### ISSUE TITLE
Universal CLI (coming soon) - Any dates for this?

### ISSUE THREAD

**Issue by vitthalr** [angular/universal#649]
Been waiting for Universal CLI version, any date, plan for this?

**Comment by MarkPieszak** [comment]
Hey @vitthalr, it can be found here in a Fork of the CLI: https://github.com/devCrossNet/universal-cli
Note it is still in rather early stages like the CLI itself is. 

Hope that helps!

**Comment by vitthalr** [comment]
Great! But I tried installing it at it shows these issues: -

**Comment by MarkPieszak** [comment]
I believe you should be ok! If you run into any others, check out the issues in that repo here: https://github.com/devCrossNet/universal-cli/issues

**Comment by vitthalr** [comment]
ok, I got it working, I got the minified files in the dist folder using "ung build --prod"

Now how do I use these files on the production server? Do I map my domain directly to dist folder? How will the server-side rendering work on production?

**Comment by vitthalr** [comment]
I figured it out, I used this: - ung serve --prod --env=prod and it seems to be working well.

Please tell me if its correct or wrong? 

Thanks a lot!!

**Comment by vitthalr** [comment]
I figured it out, I used this: - "ung serve --prod --env=prod" and it seems to be working well.

Please tell me if its correct or wrong? 

Thanks a lot!!

**Comment by MarkPieszak** [comment]
Sounds about right to me! The readme there is a slightly different one than the usual CLI since there's a few new changes Johannes made to make it universal. Glad you got it working!
