### ISSUE TITLE
Configuration umd of library

### ISSUE THREAD

**Issue by yaroslavOshyyko** [angular/universal#652]
I created my custom libraries for easily creation of online store. I compiled TypeScript files to umd module format with d.ts files. All libraries have own index files that export components, services and modules to the world. Then I published them to `npm`.
When I want to import them into my project, like 
```
import { ProductComponent } from '@nodeart/product-component';
``` 
and start the project, I have an error, like
```
Cannot find module '@nodeart/product-component'
```
But when I don't compile my files to js and use native ts files and import them directly `../../../node_modules/@nodeart/product-component/src/product.component.ts` everything work correct.
So, there is a tutorial or anyone can help me with this? How must I bundle my component to use them without importing directly in Angular Universal projects? I want to use them like
```
import { Component } from '@angular/core'.
```
Without Angular Universal I can import them like this.

This issue was copied from [github.com/angular/universal-starter/issues/319](https://github.com/angular/universal-starter/issues/319). Maybe someone will help me here.

**Comment by IvanProdaiko94** [comment]
Face the same issue. + 1

**Comment by Raixur** [comment]
Hello. Probably I have the same problem. I write custom component in Angular, but it fails on server rendering part. And it's in UMD format already. Probably there is another way to pack component for being universal angular compatible?

**Comment by manekinekko** [comment]
@yaroslavOshyyko I'm sorry to say that, but please read the [contributions guidelines](https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question).
Also, please don't open duplicate issues on different repos, it's hard to maintain.

See [my response](https://github.com/angular/universal-starter/issues/319#issuecomment-278598009) in the starter repo.

**Comment by manekinekko** [comment]
@jeffwhelpley can we close this issue.

**Comment by nosovk** [comment]
Just in case - issue was resolved in starter repo - https://github.com/angular/universal-starter/issues/319
Problem was in hardcoded config values in universal-starter.
