### ISSUE TITLE
When will be supported angular ^2.3 and its dependent packages?

### ISSUE THREAD

**Issue by A50** [angular/universal#655]
Can't install angular-universal, since in my app installed packages are dependent on the angular 2.3. 

`angular2-universal@2.1.0-rc.1 requires a peer of zone.js@~0.6.21 but none was installed.`

How to solve this problem?

**Comment by Shiroh1ge** [comment]
https://github.com/angular/universal-starter/issues/329

**Comment by MarkPieszak** [comment]
Thank you @Shiroh1ge yes, at the latest we'll have to wait until Universals engine is moved into Angular Core (https://github.com/angular/angular/issues/13822). 

For now can you stick with 2.1.0 or up to 2.2.x (if you have the workarounds setup like in the starter) ?

There might be one last `angular2-universal` patch for 2.4 but I'm not positive right now.

**Comment by chrisjmccrum** [comment]
Unfortunately, I'm getting the same issue as @A50 .  I'm working on the a project using KendoUI Angular components and in their round of updates with a ton of bug fixes they required a dependency on     `"zone.js": "^0.7.4" & "@angular/common": "2.4.0"` .  angular2-Universal and angular2-universal-polyfills is complaining about the zone.js version

**Comment by gdi2290** [comment]
for updates see https://github.com/angular/angular/issues/13822
