### ISSUE TITLE
Get hostname for backend 

### ISSUE THREAD

**Issue by junjun16818** [angular/universal#658]
client
```
this._service.get('/api/user').subscribe(user => {

})
```
server
```
app.use('/api/user', function(req){
    console.log(req.hostname)  //always get localhost  

})
```
If my check isBrowser no problem ， can get hostname
```
if( isBrowser )
{
    this._service.get('/api/user').subscribe(user => {
        
    })
}
```
How to render in the backend Get the hostname

**Comment by MarkPieszak** [comment]
In your app.server NgModule make sure you have req in your providers like this:
https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/platform-modules/app.server.module.ts#L14-L44

```
export function getRequest() {
  return Zone.current.get('req') || {};
}
export function getResponse() {
  return Zone.current.get('res') || {};
}

@NgModule({
// ........
    providers: [
        { provide: 'req', useFactory: getRequest },
        { provide: 'res', useFactory: getResponse }
    ]
})
export class AppServerModule {}
```


Do the same in your app.browser but make sure those req and res functions are blank:
```
export function getRequest() {
  return {};
}
export function getResponse() {
  return {};
}
```


Usage, inject in your contructor (https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/Client/app/app.component.ts#L17)

        constructor(@Inject('req') req: any, @Inject('res') res: any) {

Let me know if that doesn't do the trick and we can reopen the issue!
