### ISSUE TITLE
How to set LOCALE_ID in angular universal ?

### ISSUE THREAD

**Issue by haia212** [angular/universal#659]
I am trying to set the LOCALE_ID according to an environment variable. I found this post to help me http://stackoverflow.com/questions/41099552/angular-2-universal-i18n-on-server-side

Exactly as described in this post, I added  `{provide: LOCALE_ID, useValue: 'fr'}` in `src/client.ts` and in `src/server.ts` but then when I print LOCALE_ID I always have `en-US`
```
constructor(@Inject(LOCALE_ID) private _locale: string) { 
    console.log(this._locale);
  }
```

How can I set LOCALE_ID in angular universal ?

**Comment by gdi2290** [comment]
please comment in https://github.com/angular/angular/issues/13822

**Comment by haia212** [comment]
This is a universal question. In my other project (which doesn't use universal), I have no problem to set the LOCALE_ID...
