### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kybarg** [angular/universal#662]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **What is the current behavior?**
Dependencies conflict when installing `@angular/material` 

* **What is the expected behavior?**
Want to be able to use `angular-universal` with latest angular modules.

* **Please tell us about your environment:**

- Angular version: 2.4.5
- Browser: all
- Language: all 
- OS:  all 
- Platform: NodeJs

**Comment by gdi2290** [comment]
closing for https://github.com/angular/angular/issues/13822
