### ISSUE TITLE
how use common/title ?

### ISSUE THREAD

**Issue by junjun16818** [angular/universal#664]
how use common/title ?

**Comment by KostyaEsmukov** [comment]
https://github.com/angular/universal/issues/309#issuecomment-251718156

**Comment by MarkPieszak** [comment]
Along with Kostya's reply, the universal starter also has a nice angular2-meta class/service that will let you update meta tags and everything as well. Hope that helps!

**Comment by fulls1z3** [comment]
`angular2-meta` in the `universal-starter` repo is quite useful.

Actually, I can suggest you to have a look at ([@nglibs/meta](https://github.com/nglibs/meta)) - which could be helpful if you're planning to set the meta tag contents from the route definitions.
