### ISSUE TITLE
Angular 4.0.0-rc.1 error with "angular2-universal": "~2.1.0-rc.1

### ISSUE THREAD

**Issue by damirkusar** [angular/universal#666]
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
Current behavior
After updating Angular 4 beta 8 to RC1, i am getting an error in Angular-Universal

```
Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'getDOM' of undefined
at Object.<anonymous> (...\WebAppSolution\WebApp\node_modules\angular2-universal\node_modules\angular2-platform-node\get-dom.js:3:61)
```

Expected behavior
Error should not occure

Minimal reproduction of the problem with instructions
Take this repo: https://github.com/damirkusar/AngularMeetsNetCore,
update in package.json the angular libraries to RC1

    "@angular/common": "4.0.0-rc.1",
    "@angular/compiler": "4.0.0-rc.1",
    "@angular/compiler-cli": "4.0.0-rc.1",
    "@angular/core": "4.0.0-rc.1",
    "@angular/forms": "4.0.0-rc.1",
    "@angular/http": "4.0.0-rc.1",
    "@angular/platform-browser": "4.0.0-rc.1",
    "@angular/platform-browser-dynamic": "4.0.0-rc.1",
    "@angular/platform-server": "4.0.0-rc.1",
    "@angular/router": "4.0.0-rc.1",

Remove in ClientApp/boot-client.ts and boot-server.ts the universal workourand since there is an error as well, but assuming it is not needed anymore.

`//import './_workaround.universal.ts';`
This is the error when keeping the workaround:

```
Exception: Call to Node module failed with error: Prerendering failed because of error: TypeError: Cannot read property 'ViewUtils' of undefined
at Object.c (C:\Users\TDAMIKUSA\Documents\docs\Code\WebAppSolution\WebApp\ClientApp\dist\main-server.js:690:29)
```

Start the app

What is the motivation / use case for changing the behavior?
I would like to use the newest angular release

Please tell us about your environment:

Windows 7, Visual Studio 2015

Angular version: 4.0.0-rc.1
All Browsers

Language: [all | TypeScript X.X | ES6/7 | ES5]
"typescript": "^2.1.6",

-> Opened Issue in Angular [https://github.com/angular/angular/issues/14753](https://github.com/angular/angular/issues/14753) as well

**Comment by MarkPieszak** [comment]
Thanks for posting the issue @damirkusar  
Closing for https://github.com/angular/angular/issues/13822 since Universal moving to Core is still a work in progress.
