### ISSUE TITLE
Load cookies sent by browser for XHR from universal (server-side render)

### ISSUE THREAD

**Issue by SystemDisc** [angular/universal#668]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

I'm requesting a feature

* **What is the current behavior?**

The current behavior is that when universal makes http requests, cookies sent by the browser are not forwarded.

* **What is the expected behavior?**

I would like it if:

1. browser requests page
2. universal loads cookies sent by browser for XHR (http/s) requests
3. if the angular page which is being setup on the server makes an XHR request, it forwards the cookies sent by the browser, allowing things like session cookies to be used for rendering the initial page view (when rendering also depends on content requested over XHR)
4. universal sends initial view
5. page loads, etc

**Comment by MarkPieszak** [comment]
So if you check out the starter lines here for node.module https://github.com/angular/universal-starter/blob/3e2c41a22694fac55b67023652753f85f8fda098/src/node.module.ts#L43

You can get those cookies by accessing this provider:

   ```
constructor(@Inject('req') req: any) {
     // console.log('req',  req)

   }

```

Hope that helps, let us know!

**Comment by SystemDisc** [comment]
Should I only be using `req` if `!isBrowser`?

**Comment by SystemDisc** [comment]
I really think that Angular Universal should load in cookies by default. It should emulate the browser which requested the page as closely as possible so that the initially rendered view matches what Angular shows after that initial view.

**Comment by MarkPieszak** [comment]
It does in that it passes this data down (you can see it [here](https://github.com/angular/universal-starter/blob/master/src/server.ts#L86-L87) being passed to the expressEngine).

The browser.module gets the req and pulls out the `cookie` here: https://github.com/angular/universal-starter/blob/master/src/browser.module.ts#L22-L25

    { provide: 'req', useFactory: getRequest },

While the server module does DI in a different way here: https://github.com/angular/universal-starter/blob/master/src/node.module.ts

Hope that helps explain it a little bit?

**Comment by MarkPieszak** [comment]
angular2-universal has since moved to @angular/platform-server within Angular Core, can you try upgrading your project and see if this issue has been fixed? Closing this out for now!

The new express-engine can be found here, and it passes `req` and `res` by default, so headers/cookies/etc can be grabbed from there:
https://github.com/angular/universal/tree/master/modules/ng-express-engine

**Comment by intergleam** [comment]
the docs moved here https://github.com/angular/universal/tree/master/modules/express-engine#using-the-request-and-response
how do I get access to cookies?

**Comment by Gorniv** [comment]
@intergleam 
for work with request:
https://github.com/Angular-RU/angular-universal-starter/blob/master/server.ts#L107
https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/app.browser.module.ts#L35
for use union cookie storage:
https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/app.browser.module.ts#L37
https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/app.server.module.ts#L26
 cookie storage:
https://github.com/Angular-RU/angular-universal-starter/tree/master/src/app/shared/for-storage
use:
https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/home/home.component.ts#L19
