### ISSUE TITLE
Getting Started Page `server.js` is written in Typescript

### ISSUE THREAD

**Issue by RPDeshaies** [angular/universal#669]
I think most people uses a pure JavaScript back end so this example should be written in Javascript

Or, if you really want it to be in TypeScript, you should rename the file in the example `server.ts` and explain a little how to have a typescript back end.

**Comment by Ks89** [comment]
I'm agree with you. Many users are still using pure JS back-end.
However, If you want to support only Typescript, you should consider all users with existing and stable configurations with gulp/grunt/npm scripts also for big enterprise projects.

I'm using Node.js in JS + npm scripts. Obviously I won't migrate to Typescript without a stable, tested and documented environment. For instance, I need unit/integration testing + code coverage + dev/prod scripts + CI and so on.
I can migrate to Typerscript if you provide a step-by-step tutorial or an environment that supports both JS and typescript to give you the right amount of time to migrate.

I think that 'universal' could be really powerful. So, I'm here to follow you :)

**Comment by truongvu2106** [comment]
I agree with @RPDeshaies, too. There are many developers still using JS in the back-end. Certainly, some one is like me who don't want to change all our source code to TS just for server rendering.

Hope your help

Thanks.

**Comment by Toxicable** [comment]
Since we don't host a `server.js` in this repo anymore this can be closed
