### ISSUE TITLE
angular2-universal-polyfills breaks library 'mysql'

### ISSUE THREAD

**Issue by cheerun** [angular/universal#671]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [ ] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**
If I import 'angular2-universal-polyfills',
nodejs library 'mysql' occurs error.

* **What is the current behavior?**
```javascript
/Users/develofrog/Development/baekkyeong/node_modules/mysql/lib/protocol/Protocol.js:146
    .on('packet', function(packet) {
    ^

TypeError: Cannot read property 'on' of undefined
    at Protocol._enqueue (/Users/develofrog/Development/baekkyeong/node_modules/mysql/lib/protocol/Protocol.js:146:5)
    at Protocol.handshake (/Users/develofrog/Development/baekkyeong/node_modules/mysql/lib/protocol/Protocol.js:52:41)
    at PoolConnection.connect (/Users/develofrog/Development/baekkyeong/node_modules/mysql/lib/Connection.js:123:18)
    at Pool.getConnection (/Users/develofrog/Development/baekkyeong/node_modules/mysql/lib/Pool.js:45:23)
    at Object.500 (/Users/develofrog/Development/baekkyeong/dist/server/index.js:430:6)
    at __webpack_require__ (/Users/develofrog/Development/baekkyeong/dist/server/index.js:21:30)
    at /Users/develofrog/Development/baekkyeong/dist/server/index.js:67:18
    at Object.<anonymous> (/Users/develofrog/Development/baekkyeong/dist/server/index.js:70:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
```javascript
// just add it
import 'angular2-universal-polyfills';
```

* **What is the expected behavior?**
without error.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 2.1.2
- Browser:  Not related
- Language: TypeScript 2.1
- OS:  Mac OS X
- Platform: NodeJs

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by cheerun** [comment]
The cause is 'angular2-universal-polyfills/zone-node'
It breaks mysql.

**Comment by cheerun** [comment]
I found causing line..

zone.js/dist/zone-node.js:904
```javascript
if (events && events.EventEmitter) {
    patchEventEmitterMethods(events.EventEmitter.prototype);
}
```

When I commented that line, mysql worked well.
So.. I know It is monkey-patch of EventEmitter for zone context,
But Can I remove it?

**Comment by gdi2290** [comment]
can you check the zone.js and see if it's there any make a pull-request
