### ISSUE TITLE
Using Title service on server side does not work when Meta service is working

### ISSUE THREAD

**Issue by feloy** [angular/universal#676]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ ] express-engine
- [ ] grunt-prerender
- [ ] gulp-prerender
- [ ] hapi-engine
- [ ] universal-next
- [x] universal
- [ ] webpack-prerender

* **Do you want to request a *feature* or report a *bug*?**

A bug

* **What is the current behavior?**

I've created a service 'SeoService' defined liked this:

```
import { Meta, Title } from '@angular/platform-browser';

@Injectable()
export class SeoService {

  constructor(private title: Title, private meta: Meta) { }

  setTitle(title: string): SeoService {
    this.title.setTitle(title);
    return this;
  }

  setDescription(description: string): SeoService {
    this.meta.updateTag({
      name: 'description',
      content: description
    });
    return this;
  }
}
```
and I'm using it this way:

```
this.seoService
      .setTitle('My Page Title')
      .setDescription('My Page Description');
```

When using Universal to generate the page on the server-side, the meta description is set correctly, but the title is not set with the specified value.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

A github repo reproducing the bug is available at: https://github.com/feloy/ng-univ

* **What is the expected behavior?**

Title and Meta should be set on server side.

* **What is the motivation / use case for changing the behavior?**
 

* **Please tell us about your environment:**

- Angular version: 4.0.0-rc.3
- Browser: NC
- Language: TypeScript 2.1.6 
- OS:  Linux 
- Platform: NodeJs
- Node v7.1.0

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by epgeroy** [comment]
in angular v5.2.9 only works for me if I inject Title first and then Meta, otherwise, only Meta works.
