### ISSUE TITLE
Access route with segments via the server.

### ISSUE THREAD

**Issue by joaogarin** [angular/universal#691]
* **I'm submitting a ...**
- [X ] bug report

* **What modules are related to this Issue?**
- [ X] express-engine

* **Do you want to request a *feature* or report a *bug*?**

Reporting a possible bug

* **What is the current behavior?**

Currently when accessing a route with the following setup : 

```
route/:id
```

Express actually fires multiple requests to some assets like 

```
GET: /spot/1: 0.670ms
GET: /spot/styles.css: 0.254ms
GET: /spot/client.js: 0.365ms
```

This is ofc not correct as only the first one should be issued. I dont know exactly what causes these requests to fire. My app is based on https://github.com/FrozenPandaz/ng-universal-demo

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

1 ) Setup a route in both client and server that has a segment like 'route:id'
2 ) Access the route directly (via server as in the client it all works fine)
3 ) See multiple GET requests being fired for several routes like mentioned previously.

* **What is the expected behavior?**

Only a GET request for route/1 (or whatever id is given) should be issued.

* **Please tell us about your environment:**

- Angular version: 4.0
- Browser: [all]
- Language: [TypeScript 2.2.1 ]
- OS:  [Mac OS X]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This is the logging I get when accessing this route : 

```
GET: /spot/1: 0.670ms
GET: /spot/styles.css: 0.254ms
GET: /spot/client.js: 0.365ms
```

when accessing http://localhost:8080/spot/1
route code for express looks like this :

```javascript
ROUTES.forEach(route => {
  app.get(route, (req, res) => {
   console.time(`GET: ${req.originalUrl}`);
      res.render('../dist/index', {
        req: req,
        res: res
      });
      console.timeEnd(`GET: ${req.originalUrl}`);
  });
});
```

This is how the routes are configured in my app : 

```javascript
export const ROUTES: string[] = [
  '/',
  '/explore',
  '/auth',
  '/spot/:id',
];
```

**Comment by joaogarin** [comment]
I fixed this by setting my base href in the index.html instead of in the .module file with
```
{ provide: APP_BASE_HREF, useValue: '/' },
```

**Comment by joaogarin** [comment]
Having a better look at this I could reproduce in the repository https://github.com/FrozenPandaz/ng-universal-demo just by doing the following : 

Setting the base href in the app.module file by setting a provider : 

```javascript
{ provide: APP_BASE_HREF, useValue: '/' },
```

Removing it from the index.html by removing the following line : 

```
<base href="/">
```

**Comment by MarkPieszak** [comment]
@joaogarin You're saying just providing the APP_BASE_HREF made an error happen?

@vikerman Haven't seen this one myself, wondering if you have?

**Comment by vikerman** [comment]
If this is a bug in Angular pltaform-server please open the issue in angular/angular

**Comment by Toxicable** [comment]
Closing as there has been no follow up.
If you you still have a problem open up another issue addressing the above questions
