### ISSUE TITLE
As  a user I need a way to build as a node module to run over existing ExpressJS server

### ISSUE THREAD

**Issue by lautarobock** [angular/universal#694]
* **I'm submitting a ...**
- [ ] bug report
- [x ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ x] express-engine
- [ ] aspnetcore-engine

* **Do you want to request a *feature* or report a *bug*?**
**Feature**

* **What is the current behavior?**
`npm run build:prod` create a dist build that's run exclusive angular pages

* **What is the expected behavior?**
I need to include this pages into existing Node+ExpressJS server. Maybe as a separate module

* **What is the motivation / use case for changing the behavior?**
I need an existing application (node+express), just a WebAPI now. I need to add web pages. 

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all]
- Language: [TypeScript 2.X]
- OS:  [all]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Suggestion: `npm run build:module` and creates standalone module which could be included in another node+express application

BTW: Maybe I could help with the development, but I will surely need help inserting myself into the project.

**Comment by lautarobock** [comment]
Nobody? even a workarround?

**Comment by MarkPieszak** [comment]
What are you trying to build as a node_module, are you trying to prerender your application and simply serve those (pre-built pre-rendered) files through Express?

**Comment by lautarobock** [comment]
I need to add angular-universal to an existing node+express application. And I would like to create a node module with all configurations.

**Comment by MarkPieszak** [comment]
If you're talking about angular2-universal, it's only for Angular 2.1 or lower.

It's since moved to `@angular/platform-server` within Angular Core, there's an express-engine you can use to utilize it within your existing app already, you can see it here: https://github.com/angular/universal/tree/master/modules/ng-express-engine

**Comment by lautarobock** [comment]
I mean `@angular/platform-server`

I will see the example. Thanks!
