### ISSUE TITLE
Publish to npm (for 4.0)?

### ISSUE THREAD

**Issue by diestrin** [angular/universal#697]
* **I'm submitting a ...**
- [x] feature request

* **What modules are related to this Issue?**
- [x] ng-express-engine

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
This package is not in npm yet (the new 4.0 compatible version)

* **What is the expected behavior?**
`@universal/ng-express-engine` to be available to install

* **Please tell us about your environment:**

- Angular version: 4.0

**Comment by diestrin** [comment]
Sorry, looks like the job is already done, I looked a couple of days ago and this wasn't on npm. Closing

**Comment by MarkPieszak** [comment]
I'm not sure if the express-engine is published just yet to npm ? 
I need to put in a PR to finish up the aspnetcore one as well and add it to the build / publish scripts.

@vikerman

**Comment by diestrin** [comment]
A RC or beta would be enough for now. I'd actually install this from github directly, but since it's located in an inner folder, it's more complex.

Thank you btw, I created my own engine but this one looks much better than mine.

**Comment by MarkPieszak** [comment]
It has been renamed a little bit, but it's been published! 

You can find it here: `@nguniversal/express-engine` :gift:
