### ISSUE TITLE
Rendering would return more HTML on request

### ISSUE THREAD

**Issue by mariohmol** [angular/universal#701]
* **I'm submitting a ...**
- [x] bug report

* **What modules are related to this Issue?**
- [ x ] express-engine

* **What is the current behavior?**
The html showing in the browser request is empty ` <body><demo-app></demo-app></body> `

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

http://stackoverflow.com/questions/43613514/angular4-universal-server-side-rending-would-return-more-html-rendered-on-reques

* **What is the expected behavior?**

I expect to have some html inside the tags `<demo-app></demo-app>`

* **Please tell us about your environment:**

 '@angular/common': '^4.0.0-rc.3',
     '@angular/compiler': '^4.0.0-rc.3',
     '@angular/core': '^4.0.0-rc.3',
     '@angular/http': '^4.0.0-rc.3',
     '@angular/platform-browser': '^4.0.0-rc.3',
     '@angular/platform-browser-dynamic': '^4.0.0-rc.3',
     '@angular/platform-server': '^4.0.0-rc.3',
     '@angular/router': '^4.0.0-rc.3',
"@nguniversal/express-engine": "^1.0.0-beta.0",

I suppose that this is the current implementation for NgExpress

https://github.com/angular/universal/tree/master/modules/ng-express-engine

So I used  `import { ngExpressEngine } from '@nguniversal/express-engine';``

I started my app based on the https://github.com/FrozenPandaz/ng-universal-demo

**Comment by FrozenPandaz** [comment]
What you posted looks fine. Please use the package published at [@nguniversal/express-engine](https://www.npmjs.com/package/@nguniversal/express-engine) and consider upgrading to @angular 4.0.3, there should be no breaking changes from 4.0.0-rc.5.

I see it working on https://github.com/FrozenPandaz/ng-universal-demo so I feel like its not the package?

**Comment by mariohmol** [comment]
Thanks for answering! I was following this package json:

* https://github.com/FrozenPandaz/ng-universal-demo/blob/master/package.json#L23

Forced to be angular 4.0.3 and same thing..

This link shows `import { ngExpressEngine } from '@universal/ng-express-engine';`
* https://www.npmjs.com/package/@nguniversal/express-engine

But shows as cant resolve `@universal/ng-express-engine` .. 

So i'm using the `import { ngExpressEngine } from '@nguniversal/express-engine';`

**Comment by mariohmol** [comment]
I did a new fork in this repo and i'm trying to reproduce what i have in mine project there.

I cant remember what i did to make these items to work:

* angular-material: getting document is not define
* mongoose: get an error module not found when create a new mongoose.Schema
* translate: remembered that this i had issues to make it work..

The thing is.. would be nice to have a full project using universal like in a real world.. (a lot of node modules and some for app).. this implies in changes in webpack as well..

**Comment by mariohmol** [comment]
Could make this work porting my project to this example (https://github.com/clbond/angular-ssr/tree/master/examples/demand-express) .. with translate, server with mongoose and frontend with material.. so far so good =)
