### ISSUE TITLE
RESPONSE is not easily accessible in @nguniversal/express-engine

### ISSUE THREAD

**Issue by yazeedb** [angular/universal#703]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] aspnetcore-engine

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
RESPONSE must be included into a project with
```javascript
import { RESPONSE } from '@nguniversal/express-engine/dist/src/tokens';
```

* **What is the expected behavior?**
```javascript
import { RESPONSE } from '@nguniversal/express-engine/tokens';
```

* **What is the motivation / use case for changing the behavior?**
User shouldn't need to go into a package's dist folder to access RESPONSE

**Comment by MarkPieszak** [comment]
https://github.com/angular/universal/commit/0741b6ddb099fb002e8d6a396b3c4e72a1a07c5d
