### ISSUE TITLE
Importing RESPONSE client-side breaks PhantomJS unit tests

### ISSUE THREAD

**Issue by yazeedb** [angular/universal#704]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] aspnetcore-engine

* **What is the current behavior?**
Importing  RESPONSE token from @nguniversal/express-engine breaks PhantomJS unit tests, with the error
```
SyntaxError: Unexpected token 'const'
@nguniversal/express-engine/dist/src/tokens.js:3:0
```

I believe this is because express-engine's currently exported as an ES6 module, which PhantomJS doesn't seem to support. Transpiling before running the test could work.

* **What is the expected behavior?**
Importing RESPONSE should not break PhantomJS tests.

**Comment by FrozenPandaz** [comment]
This is true @yazeedb can you make a PR?

**Comment by yazeedb** [comment]
No problem @FrozenPandaz 
 I can just target ES5, if that's acceptable.

**Comment by MarkPieszak** [comment]
Can you try now with the latest changes in https://github.com/angular/universal/commit/0741b6ddb099fb002e8d6a396b3c4e72a1a07c5d and your PR? Hopefully it's all set now!
