### ISSUE TITLE
Error when importing REQUEST token

### ISSUE THREAD

**Issue by joaogarin** [angular/universal#707]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ X] express-engine
- [ ] aspnetcore-engine

* **Do you want to request a *feature* or report a *bug*?**

A bug

* **What is the current behavior?**

Importing REQUEST at a service results in the following error : 

```
ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be ref
erenced because the value of this variable is needed by the template compiler (position 2:22 in the original .ts file)
, resolving symbol REQUEST in /Library/WebServer/Documents/spotshotuniversal/node_modules/@nguniversal/express-engine/
dist/src/tokens.d.ts, resolving symbol REQUEST in /Library/WebServer/Documents/spotshotuniversal/node_modules/@ngunive
rsal/express-engine/dist/index.d.ts
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Import REQUEST token : 

```
import { REQUEST } from '@nguniversal/express-engine';
```

* **What is the expected behavior?**

running without errors.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all]
- Language: [TypeScript 2.X ]
- OS:  [Mac OS X]
- Platform: [NodeJs]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MarkPieszak** [comment]
Can you try now with the latest changes in https://github.com/angular/universal/commit/0741b6ddb099fb002e8d6a396b3c4e72a1a07c5d

**Comment by joaogarin** [comment]
Yes that seems to fix it. I just downloaded it since there is still no release on npm with this fix but it looks oK :+1:

**Comment by joaogarin** [comment]
I dont know why but this was working with Angular 4.0 and now its breaking with 4.1. I also tried the new version beta.1 from npm and get the same error as here https://github.com/angular/universal/issues/713
