### ISSUE TITLE
Can you explain and provide working examples?

### ISSUE THREAD

**Issue by playground** [angular/universal#708]

**Comment by MarkPieszak** [comment]
Working example here: https://github.com/FrozenPandaz/ng-universal-demo
Documentation should be coming soon as well.

**Comment by playground** [comment]
@MarkPieszak Thanks, can't wait.  Meanwhile, I was hoping to find some guidance on integrating our existing widgets/apps with universal and using @nguniversal/express-engine.  I'm having a hard time in seeing how to piece them together.  

For example, we have this widget that can be consumed by any sites/apps such as
```
<my-app data-config='{"language": "de-DE", "units": "m", "lat": "33.75", "lng": "-84.39"}'>  Loading...
</my-app>
```
By passing in certain configurations, the child component will get initialized based on those values. 
 Currently the component is using nativeElement and location object and is also making ajax calls to populate the component.  When want to render this server-side, I want to know what is the best practices and patterns I should follow and some examples showing the entire workflow and how to utilize certain express tokens and functionalities will be helpful.

**Comment by webmutation** [comment]
My contribution to the examples https://github.com/webmutation/toh-aot-universal-ng4

**Comment by patrickmichalina** [comment]
I have a seed project using SSR with FuseBox: https://angular.patrickmichalina.com

**Comment by Toxicable** [comment]
can be closed 

---
We have an example of how you can use Universal here https://github.com/angular/universal-starter
which has both a CLI example and custom webpack config
