### ISSUE TITLE
@nguniversal/aspnetcore-engine returned a promise that did not resolve or reject

### ISSUE THREAD

**Issue by MapleYe** [angular/universal#712]
Run the repository MarkPieszak/aspnetcore-angular2-universal by replacing its temporary aspnetcore-engine with aspnetcore-engine. Unfortunately, an exception pop up: 
An unhandled exception occurred while processing the request.
Exception: Call to Node module failed with error: Prerendering timed out after 30000ms because the boot function in 'C:\Zest\aspnetcore-angular2-universal-master/Client/dist/main-server' returned a promise that did not resolve or reject. Make sure that your boot function always resolves or rejects its promise. You can change the timeout value using the 'asp-prerender-timeout' tag helper.
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance+<InvokeExportAsync>d__7.MoveNext()

**Comment by MarkPieszak** [comment]
Thanks for logging this, let me take a look!

**Comment by bdbrown4** [comment]
Any updates on this? Running into the same issue.

**Comment by MarkPieszak** [comment]
Apologies I'll get a PR in tomorrow to update this!

**Comment by shivark** [comment]
I have the same issue!

**Comment by Toxicable** [comment]
Is this still an issue on the latest versions?
Angular v5 and aspnetcore-engine v5.0.0-beta.5

**Comment by Toxicable** [comment]
Closing as gone stale, please open another issue if there is still a problem.
