### ISSUE TITLE
Injecting REQUEST/RESPONSE tokens throws errors in AoT

### ISSUE THREAD

**Issue by yazeedb** [angular/universal#713]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] aspnetcore-engine

* **What is the current behavior?**
Injecting `REQUEST` or `RESPONSE` throws the following error during an AoT build:
```Error encountered resolving symbol values statically. Could not resolve @nguniversal/express-engine/tokens```

I've seen this when ngc encounters a static value, usually exported as a `const`, rather than a `function()`. I was able to fix it by doing the following in `ng-express-engine/src/tokens.ts`:
```typescript
export function REQUEST() { return new InjectionToken<Request>('REQUEST'); }
export function RESPONSE() { return new InjectionToken<Response>('RESPONSE'); }
```

and then consuming them in my app by invoking those functions as follows:
```typescript
import { REQUEST } from '@nguniversal/express-engine/tokens';
constructor(@Inject(REQUEST()) req: any) {}
```

I personally think is ugly, but it works in AoT mode :man_shrugging: 
I could make a PR if you guys think it's a good idea, but please let me know if anyone has a better solution.

* **What is the expected behavior?**
Should not receive the above error when injecting REQUEST or RESPONSE tokens

**Comment by samvloeberghs** [comment]
related to https://github.com/angular/universal/issues/709

**Comment by FrozenPandaz** [comment]
There must be a prettier solution but i can't seem to find out what it is.

**Comment by joaogarin** [comment]
any new developments on this issue? or a way to get around it? Thanks!

**Comment by julienR2** [comment]
I'd be interested too ! The solution from @yazeedb doesn't compile for me in AOT neither.. I get a `no provider for MYPROVIDER`..

**Comment by theomathieubhvr** [comment]
This **compiles** in AOT but when you load the page it does say, as @julienR2 said, `No provider for InjectionToken REQUEST!`

Thanks !

**Comment by patrickmichalina** [comment]
I have been able to get around this by injecting the `Injector` and manually requesting it via `.get()`

```js
// Example:
import { REQUEST } from '@nguniversal/express-engine/tokens';
import { Injectable, Injector } from '@angular/core';

@Injectable()
export class MyService { 
  constructor(private injector: Injector) { 
    const req = this.injector.get(REQUEST);
    console.log('We have the object!');
    console.log(req);
  }
}



```

**Comment by FrozenPandaz** [comment]
Closed via https://github.com/angular/universal/pull/719

**Comment by gdi2290** [comment]
done via #719
