### ISSUE TITLE
Initial animation state on sever side rendering

### ISSUE THREAD

**Issue by julienR2** [angular/universal#716]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [x] express-engine
- [ ] aspnetcore-engine

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

When relying on @angular/animation to show or hide dropdown, since the animation are done on browser side, server side rendering shows elements that should be hidden.
Using BrowserAnimationsModule, or NoopBrowserAnimationsModule in server.modules doesn't do the trick (neither trigger any errors.. Am I missing something ?)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**

Maybe we should think about a basic NodeAnimationsModule only to handle the initial state ?

* **What is the motivation / use case for changing the behavior?**

More homogeneity between server side and browser side rendering. For now, one trick is too use `isPlatformBrowser()` to show or not the component on the beginning

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all]
- Language: [all]
- OS:  [all]
- Platform: [all]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

If you are aware of prettier trick than using `isPlatformBrowser()` to set the initial state of the animation on server side, without messing up with the animation behavior on browser side, I'd be interested !

**Comment by Serginho** [comment]
This is an interesting feature, but angular server rendering module has been moved out to angular core. You can ask for this in the angular oficial repository.

**Comment by Toxicable** [comment]
Agreed, should be reopened on angular/angular.
