### ISSUE TITLE
Angular universal with HashLocationStrategy

### ISSUE THREAD

**Issue by tami-k** [angular/universal#717]
I am wondering if angular universal actually supports HashLocationStrategy. And if it does, I am curious how the server knows which route is being requested?

**Comment by gdi2290** [comment]
https://tools.ietf.org/html/rfc2396#section-4
> When a URI reference is used to perform a retrieval action on the identified resource, the optional fragment identifier, separated from the URI by a crosshatch ("#") character, consists of additional reference information to **be interpreted by the user agent after the retrieval action has been successfully completed**. As such, it is not part of a URI, but is often used in conjunction with a URI.

The server is unaware of the hash by design. On the server you can generate the correct hash url for links but in terms of rendering a certain page you need another way to tell the server which page to generate
