### ISSUE TITLE
HTML page rendered from server still have angular attributes present and w3c validation failure

### ISSUE THREAD

**Issue by kalyan1102** [angular/universal#718]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
- [ X] express-engine
- [ ] aspnetcore-engine

* **Do you want to request a *feature* or report a *bug*?**
Report a Bug

* **What is the current behavior?**
In Angular generally when we enable enableprodmode() most of the angular related atributes sucha as routerlink, routerlinkactive etc removed and it helps to make it w3c valid html page. But in this case even I have added enableprodmode still the pages render from server with those tags and w3c giving errors on those attriibutes.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

* **What is the expected behavior?**
Expected behavior should be when enableprodmode activated the page should not have angular related attributes which not validated by w3c

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ] All
- Language: [all | TypeScript X.X | ES6/7 | ES5 ] All
- OS:  [all | Mac OS X | Windows | Linux ] All
- Platform: [all | NodeJs | Java | PHP | .NETCore | Ruby] NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by samvloeberghs** [comment]
this more angular core related than universal I'd believe

**Comment by kalyan11021980** [comment]
@samvloeberghs  but without universal if I enable prodmode then its working as expected.

**Comment by samvloeberghs** [comment]
@kalyan11021980 @kalyan1102 Just wondering, how can you know that? You don't have any HTML statically loaded if you use Angular only on the browser side.

**Comment by kalyan1102** [comment]
@samvloeberghs yes so without angular universal if I just enable pordmode and then take a copy of the rendered DOM from inspect its working fine and validated in w3c

**Comment by samvloeberghs** [comment]
The rendered DOM from inspect is probably not very representative to use as a check in the W3C validator as it is Chrome fixing given errors etc, even from Angular browser rendered code..

**Comment by kalyan1102** [comment]
@samvloeberghs this idea provided by angular team only. I had raised an defect for that and they told that if I enable prod mode then all the code should w3c validated.

**Comment by wesleycho** [comment]
The best way to verify the HTML itself is probably to do a curl and then copy/paste the response body to validate, or look at the network responses for the raw HTML document.

**Comment by kalyan1102** [comment]
@wesleycho I have done same as well. But many things which generated like  _ngcontent-c1="" , outerlink, routerlinkactive etc is invalid code for w3c

**Comment by Toxicable** [comment]
Is this still an issue on the latest versions? (Angular v5)
If so can you provide a repro

**Comment by Toxicable** [comment]
Closing as gone stale, please open another issue if you still have a problem

**Comment by Bhole007** [comment]
Hi, @kalyan1102 I am still facing the same issue **W3 validator** is not allowing any **_ngcontent** as attribute. Did you get any solution to fix it?
