### ISSUE TITLE
ngScripts

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#72]
this replaces `build_scripts.ts`

prior art:
[riot/compiler](https://github.com/riot/riot/blob/master/compiler.js)

create directives that emulates `<module import="angular2/angular2"><module>`  and also allow inline scripts such as 
```html
<script type="text/typescript">
  class App {}
</script>
```
and also inject dep angular with `type="angular"`
```html
<module type="angular">
  @Component({ selector: 'app' })
  @View({ template: '<div>hello world</div>' })
  class App {}
</module>
```
we can also inject systemjs and es6 module loader.

We should also allow for app state management from `build_scripts` where we are able to control how the application is ran on the client. Or leave that feature for another module such as ngAppState

`<ng-component>` element
```html
<ng-component name="app">
  <style>
    
  </style>

  <template view="app">

  </template>

  <module>
    import {Component, View} from '@angular/angular';
    @Component({

    })
    @View({

    })
    class App {
      constructor() {
      
      }
    }
  </module>
<ng-component>
```

 - [ ] allow Typescript/Babel(ES6/ES7)/CoffeeScript script tags
 - [ ] allow module elements
 - [ ] allow angular type module/script
 - [ ] allow <component> element
 - [ ] use Angular 2's compiler

**Comment by jeffwhelpley** [comment]
See how this can be implemented using AST transformations.

**Comment by wesleycho** [comment]
What is meant by supporting TypeScript/Babel/CoffeeScript script tags?

**Comment by jeffwhelpley** [comment]
I am wondering how relevant we think this is. @gdi2290 do we really need this? I suggest that if no one is asking for this yet, let's close and wait until it actually becomes an issue. I don't really see a need.

**Comment by gdi2290** [comment]
this is needed to combat "javascript fatigue" and/or to provide a better developer experience when progressively scaling the application complexity from a `toy/example app` -> `small app` it's a bit out of scope for now and we can circle back later. Closing for now

**Comment by gdi2290** [comment]
ngScripts will be done and tracked by https://github.com/angular/universal/issues/309 as the Script `<script>` and Module `<module>` directive
