### ISSUE TITLE
Hapi adapter for Universal

### ISSUE THREAD

**Issue by wesleycho** [angular/universal#720]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What modules are related to this Issue?**
N/A

* **What is the current behavior?**

Currently there is no hapi adapter for Universal.

* **What is the motivation / use case for changing the behavior?**

Hapi is a popular Node.js router, second to Express I believe, so it would be a good thing to support.

I would be willing to help assist in this if it is desired.

**Comment by patrickmichalina** [comment]
I am thinking about jumping on this, I prefer hapi as well.

**Comment by manekinekko** [comment]
thanks for this @wesleycho

**Comment by Toxicable** [comment]
can be closed via https://github.com/angular/universal/commit/30a40082f209c4dee7e2086e78e36492ade88077
