### ISSUE TITLE
Create a common universal module

### ISSUE THREAD

**Issue by wesleycho** [angular/universal#726]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Currently there is some code duplication across the ASP.Net and Express engines, and the in-progress Hapi engine. This creates risk of code divergence due to code duplication.

* **What is the expected behavior?**
I expect there to be a common module for imports so that the common code becomes easier to manage.

* **What is the motivation / use case for changing the behavior?**
Reduced burden of maintainability

**Comment by MarkPieszak** [comment]
Yeah this would definitely help, a lot of the files I tried to keep identical to Jasons (FileLoader / Tokens etc), so I'm sure there is certain things we can share to make life easier. The `main.ts` will definitely be different, but most everything else will be the same.

**Comment by manekinekko** [comment]
we should probably have a `@nguniversal/core-engine` package 🤔

**Comment by Toxicable** [comment]
Superseded by https://github.com/angular/universal/issues/790

**Comment by Toxicable** [comment]
done via https://github.com/angular/universal/commit/23a89ecc05b36b3b393e68b7ea51335b9690dfd6
