### ISSUE TITLE
Angular cli and Universal to server apache

### ISSUE THREAD

**Issue by GerardoRamirezC** [angular/universal#735]
I can use universal angular with angular cli, use ng build --prod && ngc or ng build --prod, I generate a new server with node.js on a new port and everything works fine, the problem comes when I pass it to an apache server , I pass the dist folder to the server but it does not recognize anything of the development of universal angular, that is to say it does not render the content as in the server of node that I have in my local, as it can pass a development to an apache server environment.

**Comment by adrianolsk** [comment]
I think that to use universal you really need a node server. You can sure deploy you angular app without universal to any server (like apache) or to a CDN. But for universal I don´t think is possible.

**Comment by Toxicable** [comment]
You can use Universal easily with the CLI now.
Here's an example showing how it can be done
https://github.com/angular/universal-starter/tree/master/cli
Here's a guide showing how it was done
https://github.com/angular/angular-cli/wiki/stories-universal-rendering

**Comment by Toxicable** [comment]
close as stale

**Comment by ishan123456789** [comment]
You can deploy using `.htaccess` redirection just redirect `your-domain.com/example` to `127.0.0.1:PORT-NUMBER/example` so your user will see your local running on your-domain.com

**Comment by strotmann** [comment]
not render page if url pathname is "/"
