### ISSUE TITLE
Universal on opera mini

### ISSUE THREAD

**Issue by deepakzoto** [angular/universal#747]
Does angular universal work on proxy browsers like opera mini and uc browser ?

**Comment by Toxicable** [comment]
Universal is browser independent, since it runs on the server

**Comment by thewebchameleon** [comment]
Is Opera Mini supported in Universal? Are there any tests / have any considerations been taken into account to validate it's compatibility?

**Comment by GeoffMahugu** [comment]
Angular still does't have support for Opera mini or Uc Browser. I'm on angular 6 and server side rendering with Universal but still not working with either browsers. Here is the link to the site https://pesaguide.com
