### ISSUE TITLE
* NodeJS :: Example repo not working

### ISSUE THREAD

**Issue by splincode** [angular/universal#751]
```

splincode@splincode-linux:~/Develop/meetup/2017/july/ng/examples/universal/ng-universal-demo$ npm run build

> ng-universal-demo@1.0.0 build /home/splincode/Develop/meetup/2017/july/ng/examples/universal/ng-universal-demo
> webpack -p

Hash: 95b94a2f70228cb45ce3
Version: webpack 2.6.1
Time: 16289ms
  Asset     Size  Chunks                    Chunk Names
   0.js  1.09 kB       0  [emitted]         
main.js  1.29 MB       1  [emitted]  [big]  main
   [0] ./~/rxjs/Observable.js 11.4 kB {1} [built]
   [2] ./~/@angular/core/@angular/core.es5.js 487 kB {1} [built]
  [13] ./~/rxjs/Subject.js 5.61 kB {1} [built]
  [15] ./~/@angular/common/@angular/common.es5.js 130 kB {1} [built]
  [28] ./~/@angular/animations/@angular/animations.es5.js 42.5 kB {1} [built]
  [29] ./~/@angular/animations/@angular/animations/browser.es5.js 187 kB {1} [built]
  [47] ./~/@angular/router/@angular/router.es5.js 218 kB {1} [built]
  [90] ./src/express-engine.ts 712 bytes {1} [built]
  [91] ./src/ngfactory/src/app.server.ngfactory.ts 7.07 kB {1} [built]
  [92] ./~/express/index.js 224 bytes {1} [built]
  [93] ./~/zone.js/dist/zone-node.js 76.3 kB {1} [built]
  [96] ./src/main.server.ts 735 bytes {1} [built]
 [111] ./~/express/lib/express.js 2.22 kB {1} [built]
 [157] ./~/rxjs/observable/merge.js 128 bytes {1} [built]
 [169] ./~/rxjs/operator/share.js 923 bytes {1} [built]
    + 174 hidden modules

WARNING in ./~/express/lib/view.js
80:29-41 Critical dependency: the request of a dependency is an expression

ERROR in /home/splincode/Develop/meetup/2017/july/ng/examples/universal/ng-universal-demo/node_modules/rxjs/Subject.d.ts (16,22): Class 'Subject<T>' incorrectly extends base class 'Observable<T>'.
  Types of property 'lift' are incompatible.
    Type '<R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
      Type 'Observable<T>' is not assignable to type 'Observable<R>'.
        Type 'T' is not assignable to type 'R'.


```

**Comment by fredrikredflag** [comment]
It's a problem with RxJS and Typescript 2.4.1 (https://github.com/ReactiveX/rxjs/issues/2539) downgrade your typescript version and you should be off to the races!

**Comment by Epotignano** [comment]
What is the version that you're using? I've downgraded to 2.1.6 and is not working at all.

<img width="1912" alt="captura de pantalla 2017-07-10 a la s 23 25 27" src="https://user-images.githubusercontent.com/5238080/28051049-287f6a82-65c7-11e7-86be-bd0b3a315bed.png">

**Comment by BillyQin** [comment]
@Epotignano suggest upgreat angular to 4.1+

**Comment by Epotignano** [comment]
@BillyQin, I've downgraded typescript to 2.1.6, I just cloned the project for Nodejs and is not working, I'm using the project as is, without touch anything

**Comment by Epotignano** [comment]
Any solution for this?

**Comment by MarkPieszak** [comment]
The universal-starter has been updated for the latest Angular platform-server, can you give it another shot and let us know if it's still not working?

**Comment by Epotignano** [comment]
Still is not working, it continues retrieving a huge amount of errors.

**Comment by Epotignano** [comment]
ERROR in Error encountered resolving symbol values statically. Could not resolve @angular/animations/browser relative to /Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/animations/index.d.ts., resolving symbol ɵf in /Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/animations/index.d.ts, resolving symbol BrowserAnimationsModule in /Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/animations/index.d.ts, resolving symbol BrowserAnimationsModule in /Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/animations/index.d.ts

ERROR in /Users/epotignano/Desarrollo/fandh/ng-universal-demo/src/main.server.ts (5,42): Cannot find module './ngfactory/src/app.server.ngfactory'.

ERROR in ./src/main.server.ts
Module not found: Error: Can't resolve './ngfactory/src/app.server.ngfactory' in '/Users/epotignano/Desarrollo/fandh/ng-universal-demo/src'
 @ ./src/main.server.ts 3:0-80

ERROR in ./~/@angular/platform-server/@angular/platform-server.es5.js
Module not found: Error: Can't resolve '@angular/animations/browser' in '/Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-server/@angular'
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js 9:0-63
 @ ./src/express-engine.ts
 @ ./src/main.server.ts

ERROR in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
Module not found: Error: Can't resolve '@angular/animations/browser' in '/Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/@angular/platform-browser'
 @ ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js 10:0-206
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js
 @ ./src/express-engine.ts
 @ ./src/main.server.ts

ERROR in ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js
Module not found: Error: Can't resolve '@angular/animations' in '/Users/epotignano/Desarrollo/fandh/ng-universal-demo/node_modules/@angular/platform-browser/@angular/platform-browser'
 @ ./~/@angular/platform-browser/@angular/platform-browser/animations.es5.js 9:0-83
 @ ./~/@angular/platform-server/@angular/platform-server.es5.js
 @ ./src/express-engine.ts
 @ ./src/main.server.ts

**Comment by splincode** [comment]
@Epotignano please, create new issues

**Comment by patrickmichalina** [comment]
@Epotignano try this repo: https://github.com/patrickmichalina/fusebox-angular-universal-starter

**Comment by Epotignano** [comment]
@patrickmichalina I think that repo is terrible bad for start, is huge and complex, there should be something similar to NextJS, to allow people to create easily SSR Angular apps.
I think SSR is not optional and this is a very huge problem if there is not even an official way of build SSR Angular apps and the official repos are broken.

**Comment by patrickmichalina** [comment]
@Epotignano so help fix it :)

**Comment by Epotignano** [comment]
@patrickmichalina 
if there is not even a guide to "START" how could I fix something or improve.
I'm a fan of Angular since the version 0.8 my friend, but I think is not serious if there is not even one working example that works as a basis to iterate and improve.
