### ISSUE TITLE
Can't use self-signed cert with @angular/http when running in Node

### ISSUE THREAD

**Issue by SteveSandersonMS** [angular/universal#752]
* **I'm submitting a ...**
```
- [x] bug report
```

* **What modules are related to this Issue?**
```
- [x] aspnetcore-engine
- [x] express-engine
- [x] hapi-engine
```

* **What is the current behavior?**

If you use `Http` from Angular's standard `@angular/http` module to make outbound HTTPS requests (e.g., to an API backend), and the target server uses HTTPS with a self-signed cert, then although this can work fine in the browser, it will fail when executing on the server in Node.

**Repro steps**

* `git clone https://github.com/FrozenPandaz/ng-universal-demo.git`
* `cd ng-universal-demo`
* `npm install`
* Replace the contents of `src/app/home/home-view.component.ts` with the following, so that it uses `Http` directly:

```javascript
import { Component, Inject } from '@angular/core';
import { Http } from '@angular/http';

@Component({
  selector: 'home-view',
  template: `<h3>{{responseBody}}</h3>`
})
export class HomeView {
  public responseBody: string;

  constructor(private http: Http) {
    this.http.get('http://localhost:8000/data').subscribe(result => {
      this.responseBody = result.text();
    }, error => {
      this.responseBody = error;
    });
  }
}
```

* Now start the application using `npm run start`.
* In your browser, **disable JavaScript** since this bug report is purely about server-side rendering, and we don't want to be confused by the fact that the bug doesn't affect client-side rendering
* In your browser, navigate to `http://localhost:8000/`, and verify that the application works when the server runs on HTTP (not HTTPS). You will see the output `{"greeting":"Hello","name":"World"}`, which represents the API request completing successfully.

Now to show the same thing fails if you're running on HTTPS:

* Create a self-signed cert by running the following (assuming Mac/Linux): `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/C=US/ST=Oregon/L=Portland/O=Company Name/OU=Org/CN=www.example.com"`
* Modify `src/main.server.ts` so the Express app listens for HTTPS connections by changing the block:

```
app.listen(8000, () => {
  console.log(`Listening at ${baseUrl}`);
});
```

... to:

```
const credentials = {
  key: require('fs').readFileSync('key.pem', 'utf8'),
  cert: require('fs').readFileSync('cert.pem', 'utf8')
};
const httpsServer = require('https').createServer(credentials, app);
httpsServer.listen(8000, () => {
  console.log(`Listening at ${baseUrl}`);
});
```

* Also modify the API request so it goes over HTTPS by editing `home-view.component.ts` again, changing the URL string `'http://localhost:8000/data'` to `'https://localhost:8000/data'`.
* Restart the application with `npm run start`
* In your browser, visit `https://localhost:8000/` (note: `https`, not `http`). If the browser complains about the self-signed cert, then either install that cert as a trusted CA in your OS, or more simply just click the "continue anyway" button in the browser. **Be sure you still have JS disabled in your browser.**
* **Desired result:** `http` call still works and page outputs `{"greeting":"Hello","name":"World"}`
* **Actual result:** `http` call fails and page outputs `Response with status: 0 for URL: null`

You can verify that the problem is with Node accepting the self-signed cert (even if it's trusted at the OS level), because if you also added the code `process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";` then it would work even over HTTPS. But of course disabling HTTPS cert verification completely is not a reasonable workaround!

Now, I know you may feel that the underlying issue is with Node failing to respect OS-level trusted CAs (and instead using its own hard-coded CA list). I would agree that is a fault in Node. But what I'm reporting here is the need to have a reasonable workaround, which currently there doesn't appear to be. And the reason there's no good workaround is because of the extreme level of abstraction where Angular's `Http` wraps `xhr2` which wraps Node's `https`, and there's no way of passing arbitrary options all the way down to Node's `https`.

To further clarify: When running on the server, Angular applications delegate their HTTP requests to the NPM package `xhr2`, but don't provide any way of configuring an `agent` parameter that is set on the underlying Node-native `https.request(...)` call. You can see this by looking at the `xhr2.js` file inside the `xhr2` module: it's hard-coded to use `https.globalAgent` for every single request, without giving any way to override that on a per-request basis. This means you can't use Node's native mechanism for skipping HTTPS cert validation on a per-request basis (you could disable it globally, but obviously that's not a reasonable workaround - HTTPS validation is an important security matter if you're calling external APIs).

* **What is the expected behavior?**

Unless Angular can do something to make Node automatically accept OS-trusted CAs, it should at least provide a way of overriding the `agent` setting on a per-request basis (so the developer can control whether or not HTTPS cert validation is enforced).

* **What is the motivation / use case for changing the behavior?**

Being able to use HTTPS in development (or in intranet deployments where there may be company-signed certs that are not chained to globally-recognised CAs), while still performing cert validation on calls to external servers.

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: not applicable - this is a server-side issue
- Language: all
- OS:  all
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

It would be possible for Angular's `PlatformServer` code to subclass the `xhr2` instance it uses and override their `_sendHxxpRequest` method, synchronously replacing `this.nodejsHttpsAgent` with a `new  https.Agent(options)` instance on every invocation. Then you could pass through some `enableHttpsValidation` parameter into it. Failing that, it might be better *not* to use `xhr2` at all because it doesn't appear to have reasonable HTTPS handling.

**Comment by CaerusKaru** [comment]
To follow-up on this issue, is it still a problem with `HttpClient` (since `Http` is slated for removal)?

**Comment by julmot** [comment]
It still seems to be an issue for me (using Apollo):

```
ERROR { Error: Network error: Http failure response for https://backend.cando-d8.local/graphql/: 0 Unknown Error
    at new ApolloError (P:\cando-website\frontend-ng\dist\server\main.js:99400:26)
    at P:\cando-website\frontend-ng\dist\server\main.js:100895:34
    at P:\cando-website\frontend-ng\dist\server\main.js:101315:15
    at Set.forEach (<anonymous>)
    at P:\cando-website\frontend-ng\dist\server\main.js:101313:26
    at Map.forEach (<anonymous>)
    at QueryManager.broadcastQueries (P:\cando-website\frontend-ng\dist\server\main.js:101311:20)
    at P:\cando-website\frontend-ng\dist\server\main.js:100790:29
    at ZoneDelegate.invoke (P:\cando-website\frontend-ng\dist\server.js:542:26)
    at Object.onInvoke (P:\cando-website\frontend-ng\dist\server\main.js:72844:33)
  graphQLErrors: [],
  networkError:
   HttpErrorResponse {
     headers:
      HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
     status: 0,
     statusText: 'Unknown Error',
     url: 'https://backend.cando-d8.local/graphql/',
     ok: false,
     name: 'HttpErrorResponse',
     message:
      'Http failure response for https://backend.cando-d8.local/graphql/: 0 Unknown Error',
     error:
      ProgressEvent {
        type: 'error',
        target: [XMLHttpRequest],
        currentTarget: [XMLHttpRequest],
        lengthComputable: false,
        loaded: 0,
        total: 0 } },
  message:
   'Network error: Http failure response for https://backend.cando-d8.local/graphql/: 0 Unknown Error',
  extraInfo: undefined }
```

**Comment by julmot** [comment]
Related to https://github.com/apollographql/apollo-angular/issues/1354

**Comment by kamilkisiela** [comment]
https://github.com/apollographql/apollo-angular/issues/1354#issuecomment-541825375

**Comment by iiLearner** [comment]
Is there any workaround to it yet?

**Comment by burnout87** [comment]
I just run into the same issue. Is there a fix planned? Or a reasonable workaround?

**Comment by CaerusKaru** [comment]
There is no fix for this, we no longer support the deprecated `@angular/http` library. Please try using `@angular/common/http`. If that also does not work, please open a separate issue to track it.
