### ISSUE TITLE
Cannot find module - and SASS imports issues

### ISSUE THREAD

**Issue by demiro** [angular/universal#753]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
I want to report a bug

* **What is the current behavior?**
Errors when building:
Error: Cannot find module 'app/pages/demo/matchcard-demo-page/matchcard-demo-page.component'

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
Using angular CLI
Using SCSS
followed[ this tutorial:](https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d
)

created and updated everything and ran npm run start (ng build --prod && ngc)

After a lot of fixes in my SCSS files (@import '~css/something' to @import '../../../../css/_something.scss') spending hours on that.... (ng serve and ng build worked fine before)

After I fixed the issues I now get an error that it cannot find a module in app-routing.module.ts (1:1)

So the first one... it says:
import { MatchcardDemoPageComponent } from 'app/pages/demo/matchcard-demo-page/matchcard-demo-page.component';

the file is there and it works fine with ng serve.... I have a feeling that is again the abs path issue and it would prefer a relative path

.... and confirmed.... it is a problem with the abs vs relative path... 

This should be solved.... abs paths makes the life so much easier if you do refactoring and moving files around... you preserve the integrity

* **What is the expected behavior?**
universal to be built I guess? never done it successfully

* **What is the motivation / use case for changing the behavior?**
the project to build?

* **Please tell us about your environment:**

- Angular version: 4.2.6
- Browser: [all ]
- Language: [TypeScript 2.3.3. ]
- OS:  [Windows] (but guessing all)
- Platform: [NodeJs ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Error: Cannot find module 'app/pages/demo/demo.component'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\DEVELOPMENT\XXX\new4\src\app\app-routing.module.ts:7:1)
    at Module._compile (module.js:570:32)
    at Module.m._compile (C:\DEVELOPMENT\XXX\new4\node_modules\ts-node\src\index.ts:382:23)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\DEVELOPMENT\XXX\new4\node_modules\ts-node\src\index.ts:385:12)
    at Module.load (module.js:487:32)

**Comment by chrillewoodz** [comment]
I'm experiencing a path issue as well when importing SASS files into an encapsulated component. Using absolute path is not the same when running with universal as it is without. When using universal it starts in the folder where the path is specified rather than at root which would be `src`.

**Comment by Toxicable** [comment]
Is this still an issue?
If you need a template to get your started you can use this here https://github.com/angular/universal-starter/tree/master/cli

**Comment by Toxicable** [comment]
looks like a dup of https://github.com/angular/universal/issues/759
