### ISSUE TITLE
Imports doesn't start from src folder when using universal 

### ISSUE THREAD

**Issue by chrillewoodz** [angular/universal#759]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Report a bug.

* **What is the current behavior?**
I'm trying to get angular universal to work but it throws error for all scss imports which are done in encapsulated components for this line:

`@import './src/assets/styles/utils/_exports';`

It works when running it normally without universal but when it runs with universal it treats the import as absolute to the component and not root.

So the path becomes:

`src/app/shared/components/breadcrumbs/src/assets/styles/utils`

Instead of just:

`src/assets/styles/utils`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
You can download https://github.com/chrillewoodz/ng-boilerplate/tree/universal and install it and then run `npm run start` to see the issue. Run `ng serve` to see how it's supposed to work. I.e. there are no errors.

* **What is the expected behavior?**
I expect the path to not start from the component folder (`breadcrumbs` for example), but rather start from `src`.

* **What is the motivation / use case for changing the behavior?**
This needs to be fixed or clarified what I'm doing wrong or you cannot use global styles without de-activating style encapsulation. Which frankly would be a bit ridiculous.

* **Please tell us about your environment:**

- Angular version: 4.0.0
- Browser: all
- Language: all
- OS:  Mac OS X
- Platform: NodeJS

**Comment by Toxicable** [comment]
Is this still an issue on the latest versions?
See here https://github.com/angular/universal-starter/tree/master/cli for a tempalte on the latest version

**Comment by chrillewoodz** [comment]
I don't know, I assume that it is since I haven't heard of any fix.

**Comment by Toxicable** [comment]
I tried to see if I could reproduce this with your repo linked above but could not compile Universal due to an error with ngx-translate.
Could you make a minimal reproduction of the error?

**Comment by Toxicable** [comment]
Closing as issue has gone stale
