### ISSUE TITLE
Server side renders wrong environment

### ISSUE THREAD

**Issue by mchambaud** [angular/universal#760]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
Server side renders the application using default **environment** while client side renders using environment passed as command line argument

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
https://github.com/mchambaud/angular-4-universal-cli

npm i && npm start

* **What is the expected behavior?**
SSR uses DEV environment while BSR uses PROD environment

* **What is the motivation / use case for changing the behavior?**
It does not work as expected

* **Please tell us about your environment:**

- Angular version: 4.X
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
<img width="1491" alt="screen shot 2017-07-24 at 10 27 29 am" src="https://user-images.githubusercontent.com/360109/28528187-0bf734a0-705b-11e7-9721-7200cefd0133.png">

**Comment by sunild** [comment]
FYI @mchambaud  I was experiencing this problem w/version 1.1.1 of the cli ... but if you follow the setup [shown here](https://medium.com/@cyrilletuzi/angular-server-side-rendering-in-node-with-express-universal-engine-dce21933ddce) using cli 1.3 and morph your setup as shown in the blog it works as expected.

**Comment by Toxicable** [comment]
Is this still an issue?
If you need a template we have a starter over here https://github.com/angular/universal-starter/tree/master/cli

**Comment by mchambaud** [comment]
Yup this seems to be resolved! Thanks
