### ISSUE TITLE
Prerendering failed? 

### ISSUE THREAD

**Issue by itanev** [angular/universal#761]
Hi,

I am trying to turn on the server side pre-rendering for my asp.net core application, but I keep getting this error in C# controller (Home Controller form the example) in the section that renders the pre-rendering.

`await Prerenderer.RenderToString(....`

The error: 

```
Call to Node module failed with error: Prerendering failed because of error: undefined
Current directory is: (My project directory path)
```

I am using the example from [here](https://github.com/angular/universal/tree/master/modules/aspnetcore-engine).

I noticed that the createTransferScript function is not defined anywhere in the example, but it is used in the angular. Could this be the problem? Maybe the function is undefined? From where should I get it or if it is already defined, who defines it? 

Thanks!

**Comment by arifnazir** [comment]
How to deploy angular universal app to IIS, i can see pre redering doesn't work when we host angular universal to IIS using iisnode.

**Comment by jrmcdona** [comment]
Yes, @MarkPieszak that documenation seems to be incomplete.  At least the same code is missing stufff.
https://www.npmjs.com/package/@nguniversal/aspnetcore-engine

**Comment by jrmcdona** [comment]
@arifnazir you can find more info here which uses a temporary version of what is in NPM and is a little more complete.  

https://github.com/MarkPieszak/aspnetcore-angular2-universal

https://github.com/MarkPieszak/aspnetcore-angular2-universal/blob/master/ClientApp/polyfills/temporary-aspnetcore-engine.ts

**Comment by Toxicable** [comment]
Is this still an issue on the latest versions?

**Comment by Toxicable** [comment]
Closing as gone stale, please open another issue if you still have a problem
