### ISSUE TITLE
Feature: automate absolute URLs for HttpClient in ExpressEngine

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/universal#766]
* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **What is the current behavior?**
Angular server-side rendering via `@angular/platform-server` requires absolute URLs in HTTP requests.

* **What is the expected behavior?**
Automate absolute URLs in Express Engine.

* **What is the motivation / use case for changing the behavior?**
That's really painful to manage this by hand, as the absolute URL is not the same on dev server and prod server.

So I used the new HttpClient interceptor feature of Angular 4.3 to automate this.

Repo example : [https://github.com/cyrilletuzi/nguniversal-expressengine-httpinterceptor/](https://github.com/cyrilletuzi/nguniversal-expressengine-httpinterceptor/)

If it's OK, I can do the PR for this.

**Comment by Toxicable** [comment]
Feel free to go ahead name make a PR if you like

**Comment by cyrilletuzi** [comment]
A confirmation from one of the members would be nice, because I don't have much time and it's not a quick PR, and I'm not sure that : 
- the principles of my feature are OK (maybe there is a good reason for this current limitation)
- not even sure this project is still active as there is no update from 3 months...

**Comment by MarkPieszak** [comment]
It's still active, I was actually just thinking of adding something like this. If you can't put in a PR for it I can throw it together. @cyrilletuzi

**Comment by cyrilletuzi** [comment]
I won't be able to do the PR until 2 weeks.

By the way, a changelog would be nice to know what's new, breaking, etc.

**Comment by Toxicable** [comment]
So this is a pretty easy fix
All it requires adding is an Interceptor class that devs can just import and provide
and a Function for providing the Url inside the server.js

However, this issue is where to put it.
Right now we'd have to put this code into every Engine that we support which is less than ideal so I propose that we wait untill we have a `core` module and put it there, otherwise we'll spend most of the time playing catch up

**Comment by kalyan11021980** [comment]
@cyrilletuzi thanks for this great solution!

**Comment by Toxicable** [comment]
Closing as will be fixed in HttpClient, can be tracked here https://github.com/angular/angular/issues/19224
