### ISSUE TITLE
 is Angular Universal and AOT can come together?

### ISSUE THREAD

**Issue by wizardnet972** [angular/universal#770]
something in the universal that I dont get.. is Angular Universal and AOT can come together?

I'm using node server to start the server right?
in server I have role: meaning that I have to upload my ts files to the server because of AppServerModuleNgFactory!
```
app.engine('html', (_, options, callback) => {
  const opts = { document: template, url: options.req.url };

  renderModuleFactory(AppServerModuleNgFactory, opts)
    .then(html => callback(null, html));
});
```
But on the AOT - everything is already rendered! in AOT I get index, js already complied!

**Comment by Toxicable** [comment]
`AppServerModuleNgFactory` This is the AOT compiled factory
So yes you can use Universal with AOT

**Comment by thedewpoint** [comment]
@Toxicable is it possible to disable AOT? In angular 6 I have an app where I am explicitly disabling aot on the browser ui so I can leverage the angular compiler. I can't figure out how to do the same for angular universal.

**Comment by thedewpoint** [comment]
@dockleryxk It's not a great idea, but this is a very small app that exists primarily to compile content and display it using angular. Would like to leverage universal for SEO purposes, but runtime compiler doesn't get bundled on the server
