### ISSUE TITLE
when i change ssr to my project,the project compiler slow

### ISSUE THREAD

**Issue by songjunyan** [angular/universal#773]
when i solved a bug,I needed restart the npm,but the project that be ssr is very slow,it is about two minutes

i would mad

**Comment by Toxicable** [comment]
Thanks for reporting this issue, however, without a reproduction of the problem you're facing it becomes hard to find what is causing it.
Could you please produce a minimal reproduction in a repo that we can clone to see the issue?

**Comment by MarkPieszak** [comment]
Can you re-open this issue in the universal-starter?
It's really just a webpack configuration setup that needs to be done, since there is no vendor/etc splitting, it's repacking the entire file (which takes a while).
