### ISSUE TITLE
Publish ModuleMapNgFactoryLoader as NPM package

### ISSUE THREAD

**Issue by josephliccini** [angular/universal#782]
Hello!

I have been using a built from source and tarballed version of `ModuleMapNgFactoryLoader`, and I think it would be great if this could be published to NPM to begin consuming in a standard way.  

You could always publish it as 0.0.1-beta.1 or something, so folks are aware that it is still in beta and will likely change in the future.

Thanks
Joe

**Comment by Toxicable** [comment]
can be closed via https://github.com/angular/universal/commit/309053364c282bf69342cfacf317ea7c7c54f0b4

**Comment by MarkPieszak** [comment]
Thanks @Toxicable

**Comment by josephliccini** [comment]
Thank you both!!
