### ISSUE TITLE
async not working with express server

### ISSUE THREAD

**Issue by Scipionh** [angular/universal#786]
Hello,

I have been stricly following the guides over there :
https://www.techiediaries.com/angular-4-universal-server-side-rendering/ and
https://coursetro.com/posts/code/68/Make-your-Angular-App-SEO-Friendly-(Angular-4-+-Universal)

The issue I am having though is that the rendering isn't waiting my async call to finish.
I thus modified my app.get to wait for async calls to finish by doing the following.
```
app.get('*', (req, res) => {
  req.async = true
  res.render('index', { req });
});
```

My app.component is basically doing an async call in its ngOnInit and none of what is retrieved appears in my source code.

Am I missing something here ?

**Comment by MarkPieszak** [comment]
Are you getting errors in your Node output console?

Also if you can, compare your code with what's going on here in the Starter: https://github.com/angular/universal-starter

**Comment by Toxicable** [comment]
I just attempted to reproduce this with this with the CLI from this repo here 
https://github.com/Toxicable/universal-starter/tree/cli
but was unsuccessful

in trying to I used the following code 
```
@Component({
  selector: 'app-root',
  template: `
    <h1>
      Welcome to {{title}}!!
    </h1>
  `,
  styles: []
})
export class AppComponent {
  title;
  ngOnInit(){
    this.title = 'before async';
    setTimeout(() => this.title = 'after async', 2000)
  }
}
```
and as expected with prerender it correctly rendered:` <h1>Welcome to after async!!</h1>`
the same happened when using the express engine, it served up:` <h1>Welcome to after async!!</h1>`

So I think we'll need a repo for identify the issue here

**Comment by Scipionh** [comment]
I indeed noticed something going on in the server's console.

Apparently, my aync api call is timing out. That's quite odd as what I can see from the browser shows me the call with a 200 and the answer of the call. Do I need to setup anything particular on the server side ?

**Comment by Toxicable** [comment]
If it indeed is an issue with your proxy then it would appear that the error is not Universal related.
If so would you mind closing this issue?

**Comment by Scipionh** [comment]
I think we can safely assume my issue isn't related to Angular Universal.

**Comment by pivalig** [comment]
just run 
npm run build:dynamic

Read the README file, please :


## Development (Client-side only rendering)
* run `npm run start` which will start `ng serve` (project served at the standard: localhost:4200)
---
## Production 
Depending on whether you're publishing dynamic or static prerendering, run the build command, and then serve up your dist folder assets.

> **NOTE**: To deploy your **Static** site to a static hosting platform you will have to deploy the *`dist/browser`* folder, rather than the usual *`dist`*

ie: `npm run build:dynamic` or `npm run build:static`. All of the files that need to be served will be found within the `/dist` folder.
