### ISSUE TITLE
Having 2 modules and only one being handled by angular-universal

### ISSUE THREAD

**Issue by Scipionh** [angular/universal#798]
I am basically looking to build an App with 2 modules inside it. One having static data I need to reference, and the other one being out of this. I really would like to have both in the same project and only have the first of my two modules served by the universal's express server. 
Is it something Universal would allow me to do ?

**Comment by Toxicable** [comment]
I don't understand.
Is what you're building 1 application or multiple?
You can choose to use Universal on specific routes if you like, only using it on the routes where it would work.

**Comment by Scipionh** [comment]
Indeed sir, you perfectly right, I have changed the `main.server.ts` to the following :

```
REFERENCED_ROUTES.forEach((route: string) => {
  app.get(route, (req: Request, res: Response) => {
    console.time(`GET: ${req.originalUrl}`);
    res.render('../dist/index', {
      req: req,
      res: res
    });
    console.timeEnd(`GET: ${req.originalUrl}`);
  });
})

ROUTES.forEach((route: string) => {
  app.get(route, (req: Request, res: Response) => {
    console.time(`GET: ${req.originalUrl}`);
    res.sendFile('/dist/index.html');
    console.timeEnd(`GET: ${req.originalUrl}`);
  });
})
```

**Comment by Toxicable** [comment]
In which case is there some issue with a module hosting by the repository? If not could you close this issue?

**Comment by Scipionh** [comment]
No issue at all, it's actually working fine, cheers.
