### ISSUE TITLE
proposal: tool for lib's to verify/test Universal compatibility 

### ISSUE THREAD

**Issue by Toxicable** [angular/universal#800]
```
- [x] feature request
```
## Problem
Right now every Lib that wants to test if their module works in Universal has to make an application plus all of the boilerplate required to render that application in a Universal Environment.

## Solution
A tool for testing if a Module works in Universal (and AOT).

## API
`assertUnivesalCompliant(module)`

## Usage
```
import { assertUnivesalCompliant } from '@nguniversal/testing`//(taking suggestions on package name)

@NgModule({
  imports: [KitchenSinkClientModule, ServerModule],
  bootstrap: [KitchenSink],
})
export class KitchenSinkServerModule { }

assetUniversalComliant(KitchenSinkServerModule)
```

## Prior Art
AngularFire2: https://github.com/angular/angularfire2/pull/1140
Material:         https://github.com/angular/material2/tree/master/src/universal-app

**Comment by vikerman** [comment]
I think testing needs to be addresses both at unit and e2e levels. I think the above covers more of the E2E tests.

For unit tests - With Domino, the browser unit tests should just work on node - by switching platformBrowserTesting with platformServerTesting.

**Comment by Toxicable** [comment]
I think this issue is better broken down into smaller chunks rather than introducing a catch all "it works in universal" since that often wont be enough
