### ISSUE TITLE
Using dynamic routing

### ISSUE THREAD

**Issue by Scipionh** [angular/universal#801]
I have tried unsucessfully to setup angular universal (using angular-cli) with an angular routing like this one:

```
RouterModule.forRoot([
      { path: 'page/:uid', component: PageComponent}
    ])
```

`uid` is then caught in my PageComponent's ngOnInit to retrieve the right informations linked to it.

Unfortunately, if I try to reach my page/hello, I keep getting 

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'hello'
Error: Cannot match any routes. URL Segment: 'hello'
```

My `server.js` is looking like this :

```
app.get('*', (req, res) => {
  console.time(`GET: ${req.originalUrl}`);
      // Static
      res.render('index.html', {
          req: req,
          res: res
      });
  console.timeEnd(`GET: ${req.originalUrl}`);
});

```

**Comment by Toxicable** [comment]
@Scipionh is this when you're using `ng build`?
Also what is the url you're trying to use that produces this error?

**Comment by Scipionh** [comment]
@Toxicable I am using `ng build && cpy ./server.js ./dist" &&  cd dist && node server`
I have the same error when using `ng build --prod`

**Comment by Toxicable** [comment]
I attempted to reproduce your error but was unsuccessful.
To reproduce I did:
* `git clone https://github.com/angular/universal-starter`
* `cd cli`
* edit `app.module.ts` to 
```
    RouterModule.forRoot([
      { path: 'page/:uid', component: HomeComponent, pathMatch: 'full'},
    ])
```
* `run npm run build:dynamic`
* navigate to localhost:8000/page/home
and it rends fine without errors

**Comment by Scipionh** [comment]
I'll keep digging into it. I'll close the issue if I don't find anything else.

**Comment by Scipionh** [comment]
It seems fine, the issue was coming from completely elsewhere. My very bad, thanks sir !
