### ISSUE TITLE
docs: Engines need better docs, demos and guidance

### ISSUE THREAD

**Issue by Toxicable** [angular/universal#804]
As pointed out by @wardbell here https://github.com/angular/angular/pull/18707#discussion_r138766009
We should address the points raised, most of which are simply due to a lack of docs, examples and demos.

**Comment by MarkPieszak** [comment]
Docs (.MD files even), or updates to the universal.angular.io would probably be best since it's a slippery slope if we start demo'ing everything. The starter starts turning into the kitchen-sink again 😆

**Comment by Toxicable** [comment]
I think we need to point `universal.angular.io` here instead of duplicating content.
And each module should have it's own demo showing it's specific feature, no kitchen sink here, these demo's could also be apart of intergration/e2e testing once we implement that

**Comment by alan-agius4** [comment]
Lets keep tracking this in https://github.com/angular/universal/issues/1732
