### ISSUE TITLE
bug(module-map-ngfactory-loader, express-engine): module export issues

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#805]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
- [x] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**

Bug report

* **What is the current behavior?**

Compiling a Universal project that includes module-map-ngfactory-loader@latest and express-engine@latest with AOT fails

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

1. Create a Universal-capable project with lazy-loaded routes
2. Include the module-map-ngfactory-loader@5.0.0-beta.0
3. Include express-engine@5.0.0-beta.0
4. Try to compile the server build with @angular/cli@latest
5. Receive AOT error for module-map and "cannot find error" for express-engine

* **What is the expected behavior?**

Should be able to compile server build using module-loader and express-engine with AOT

* **What is the motivation / use case for changing the behavior?**

Cannot compile the module-loader with AOT, leading to larger file sizes on the server, and possibly longer rendering times. Cannot include express-engine, meaning cannot run SSR in Express

* **Please tell us about your environment:**

- Angular version: 5.0.0-beta.7
- Language: [all | TypeScript 2.5.2 | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | **Linux** ]
- Platform: [all | **NodeJs** | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Module-map
```
Error: Error encountered resolving symbol values statically. Could not resolve @nguniversal/module-map-ngfactory-loader
```
Express-engine
```
Error: Cannot find module '@nguniversal/express-engine'
```

cc @Toxicable

**Comment by CaerusKaru** [comment]
To clarify, this is only an issue with @nguniversal/module-map-ngfactory-loader@5.0.0-beta.0, not 1.0.0-beta.3

**Comment by drejohnson** [comment]
`import { ModuleMapLoaderModule } from '@nguniversal/module-map-ngfactory-loader/modules/module-map-ngfactory-loader';` fixes that error. Don't believe importing this way is intended though.

**Comment by CaerusKaru** [comment]
It looks like it's an export error, other modules are affected as well, see #806

**Comment by Toxicable** [comment]
This has already been fixed by https://github.com/angular/universal/commit/5c705cb51362bd448c0b8ac293da867a3a1913f4

**Comment by CaerusKaru** [comment]
The latest version published to npm is 5.0.0-beta.0, which came after https://github.com/angular/universal/commit/f734771aef979b1feefed7a9f750d2c710120ba8, which includes 5c705cb

**Comment by Toxicable** [comment]
As the other issue, can you try on the latest version of Angular?

**Comment by CaerusKaru** [comment]
I'm using 5.0.0-beta.7 for angular, the 5.0.0-beta.0 is for the module-loader

**Comment by Toxicable** [comment]
Ahh my mistake, I see your error now, it's the same error so if you could close the other issue that would be great

**Comment by CaerusKaru** [comment]
@Toxicable What exactly is the error? I can file a common issue to encompass them both

**Comment by Toxicable** [comment]
looks like something changed with `ngc` that changes how we packaged our modules
as @drejohnson mentioned `import { ModuleMapLoaderModule } from '@nguniversal/module-map-ngfactory-loader/modules/module-map-ngfactory-loader';` 
is a reasonable work around for now

**Comment by CaerusKaru** [comment]
@Toxicable The real workaround is to simply keep using 1.0.0-beta.3 since the 5.0.0-beta.0 version has no significant changes in functionality except presumed compatibility with angular v5

**Comment by CaerusKaru** [comment]
For those following, 5.0.0-beta.1 has been released with a patch while the angular team works on the ngc issues. Closing since this is now an angular/angular issue.
