### ISSUE TITLE
@HostListener events not work in Universal

### ISSUE THREAD

**Issue by dknitrox** [angular/universal#814]
* **I'm submitting a ...**
```
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

report a *bug

* **What is the current behavior?**

I have defined a directive and this runs normal using angular-cli, but when I add the universal it does not work, and it does not send me any messages.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
1.-Create Angular-cli project v4.x
2.-To universal https://medium.com/@evertonrobertoauler/angular-4-universal-app-with-angular-cli-db8b53bba07d
3.-Create template and directive.
```

  <button myHighlight>Highlight me!</button>

@Directive({ selector: '[myHighlight]' })
export class HighlightDirective {
    constructor(el: ElementRef) {
        console.log("highligh directive");
    }
    @HostListener('click', ['$event'])
    toggleOpen($event: any) {
      console.log("toggle open")
     /* $event.preventDefault();
      document.querySelector('body').classList.toggle('sidebar-hidden');
      */
    }
}
```

4.-I need to import the directive into app.module, and this works fine when I run it with angular-cli only in prod mode, but when I run it with universal it does not work (PD: Most angular features if they work, except this one).

* **What is the expected behavior?**
Let me send the console.log message, as well as emits me when I call the constructor, in addition to the functionality that can be programmed when the event is executed.

* **What is the motivation / use case for changing the behavior?**
I don't know

* **Please tell us about your environment:**

- Angular version: 4.X   
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [ TypeScript X.X  ]
- OS:  [ Windows | Linux ]
- Platform: [ NodeJs ]

**Comment by MarkPieszak** [comment]
Can you use the official universal-starter CLI and see if this is still an issue? This shouldn't throw any errors during compilation, as long as you keep that "document" out, as it doesn't exist on the server.

Hope that helps, closing out for now.
