### ISSUE TITLE
e2e test for ServerDomRenderer and with preboot.js

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#82]
We need e2e tests for 

Server:
* default values for input value and checkbox
* focus an input element during Server rendering that adds autofocus

Server+Client:
* default values for input value and checkbox
* focus an input element during Server rendering that adds autofocus

Server+Client+Preboot.js
* default values for input value and checkbox
* focus an input element during Server rendering that adds autofocus
* selection is correct placement in an input
* selection is correct placement in an input during bootstrap

**Comment by gdi2290** [comment]
I'm working on this now

**Comment by gdi2290** [comment]
I'm not sure how to get element props with protractor to test client rendered elements and selection

**Comment by manekinekko** [comment]
Hi @gdi2290 have you started this?

**Comment by gdi2290** [comment]
@manekinekko I push up the wip. the problem is getting the props rather than the attrs
https://github.com/angular/universal/blob/master/test/test_page.e2e.js
you would need to inject js to grab elements and expose them to protractor I think

**Comment by manekinekko** [comment]
@gdi2290 which props do you wanna test? I managed to get pros from DOM element.

**Comment by gdi2290** [comment]
@manekinekko the input to ensure selection is correct and the value of the input

**Comment by manekinekko** [comment]
@gdi2290 using `executeScript` you can run arbitrary js code. So for example, this gives you the `value` property:
```javascript
it('should have default value for inputs', function() {
  subject = browser.executeScript('return document.querySelector("#defaultValueInput").value');
  result  = 'value8';

  expect(subject).toBe(result);
});
```

**Comment by gdi2290** [comment]
oh that's a good find and solves a lot of problems :+1:

**Comment by manekinekko** [comment]
should I emphasis on the difference between the prop "value" and the attribute "value" in the test suites?

**Comment by gdi2290** [comment]
yup, although for server only it's attrs while everything else it's props it's important to note that

**Comment by manekinekko** [comment]
@gdi2290 here is what I was able to test so far. As you can see from the screenshot below, there is one test that fails and 3 pending test that I don't know how to test (the preboot ones). 
I let you check that if you dont mind ;)

If you're OK. I'll send the PR right away.

![image](https://cloud.githubusercontent.com/assets/1699357/9345570/b468350a-4612-11e5-8c42-58429b79039b.png)

**Comment by gdi2290** [comment]
LGTM

**Comment by gdi2290** [comment]
selection isn't really working with preboot or at least not with the e2e tests

**Comment by gdi2290** [comment]
@jeffwhelpley can you take a look at the e2e tests to see why it's failing 
https://github.com/angular/universal/blob/master/test/test_page.e2e.js#L86...L103

**Comment by gdi2290** [comment]
done via https://github.com/angular/universal/commit/ae31bd2406157edb1107d1e770e87d3410def72f
