### ISSUE TITLE
ngAspnetCoreEngine Issue with Angular 5 Latest RC

### ISSUE THREAD

**Issue by naveedahmed1** [angular/universal#824]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [ x] bug report
```

* **What modules are related to this Issue?**
```
- [x ] aspnetcore-engine
```

* **Do you want to request a *feature* or report a *bug*?**

When using SSR with ngAspnetCoreEngine and Angular 5.0.0-rc.1, I am receiving below error:

```
NodeInvocationException: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
Error: StaticInjectorError[{provide:ResourceLoader, useClass:FileLoader}]: 'deps' required
at staticError (D:\MyProject\ClientApp\dist\main-server.js:6064:12)
at computeDeps (D:\MyProject\ClientApp\dist\main-server.js:6031:15)
at resolveProvider (D:\MyProject\ClientApp\dist\main-server.js:5826:33)
at recursivelyProcessProviders (D:\MyProject\ClientApp\dist\main-server.js:5883:53)
at recursivelyProcessProviders (D:\MyProject\ClientApp\dist\main-server.js:5872:17)
at recursivelyProcessProviders (D:\MyProject\ClientApp\dist\main-server.js:5872:17)
at new StaticInjector (D:\MyProject\ClientApp\dist\main-server.js:5783:9)
at Function.Injector.create (D:\MyProject\ClientApp\dist\main-server.js:5755:16)
at JitCompilerFactory.createCompiler (D:\MyProject\ClientApp\dist\main-server.js:152146:97)
at ngAspnetCoreEngine (D:\MyProject\ClientApp\dist\main-server.js:182617:36)
```

**Comment by Toxicable** [comment]
Will be fixed by https://github.com/angular/universal/pull/825

**Comment by vikerman** [comment]
@naveedahmed1 -  The aspnetcore-engine@5.0.0-beta.1 has been published. Can you confirm this works? The default in npm is still 1.0.0-beta.3 since that's the version that Angular CLI uses.

**Comment by MarkPieszak** [comment]
We're all set now, it's fixed 👍  @vikerman

**Comment by naveedahmed1** [comment]
@vikerman thanks for the update. Now I am receiving below error:

```
NodeInvocationException: StaticInjectorError[InjectionToken REQUEST]: 
StaticInjectorError[InjectionToken REQUEST]: 
NullInjectorError: No provider for InjectionToken REQUEST!
Error: StaticInjectorError[InjectionToken REQUEST]: 
StaticInjectorError[InjectionToken REQUEST]: 
NullInjectorError: No provider for InjectionToken REQUEST!
```

Any help would be really appreciated.

**Comment by naveedahmed1** [comment]
Hello @vikerman sorry for the late reply. I was trying to use aspnetcore-engine@5.0.0-beta.1 in my app but was having trouble. Finally concluded that it is due to HttpClient interceptor issue with zonejs v0.8.18. (ref 
https://github.com/angular/angular/issues/19853).

Though I tested it with @MarkPieszak repo https://github.com/MarkPieszak/aspnetcore-angular2-universal/tree/angular-5.0-updates and it was working fine (it uses zonejs v0.8.17)
