### ISSUE TITLE
feat(express-engine): add ability to disable factory cache

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#829]
* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

Feature request

* **What is the current behavior?**

Currently, all factories are committed to a cache in the express-engine after generation

* **What is the expected behavior?**

There should be an option to disable the factory cache (not the index cache, that one is always useful)

* **What is the motivation / use case for changing the behavior?**

Users should be able to disable this cache for use cases including secure route generation (i.e. if one user signs in, an unrelated, unauthenticated user will receieve the original user's authenticated page -- the auth service does not run again) 

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

The relevant code is found below. I'd be more than happy to contribute a PR for this with the config and tests, but I wanted to open this up for discussion first.
https://github.com/angular/universal/blob/35bfc5112a9c0b862b756718731849e761f3f588/modules/express-engine/src/main.ts#L97-L124

**Comment by Toxicable** [comment]
The only thing that cache is caching is the factory, in most cases where you're using the CLI you're not even using it since you already have a factory.
Just to clarify, the cache holds your compiled application, meaning the compiler has been run over the app and it's ready to boot, it hasn't actually been bootstrapped

**Comment by CaerusKaru** [comment]
That's not what I'm seeing in my application. ngExpressEngine is caching the entire application, authenticated by one user, and displaying it to everyone else in that same state. 

For reference, I'm intercepting auth requests made by the express server to check when they're going out, and they are only sent after the initial bootstrap. Subsequent requests, even sent in incognito mode (where there are no auth credentials stored), all return the same application state.

**Comment by Toxicable** [comment]
Hmm, ill take a look but to identify if it is this could you edit the script under your node_modules and remove the cache part of it?
This part
```
factoryCacheMap.set(moduleOrFactory, factory); 
```

**Comment by CaerusKaru** [comment]
Closing as this is not actually an issue with express-engine, at least not one that I can visibly identify.

What is clear is there is a caching mechanism somewhere in my code (from a third-party lib) that is caching auth requests such that when the code is bootstrapped after the first iteration, it just pulls from the cache. Will update if I find where it is specifically, and if I think it's a general use case.

**Comment by Toxicable** [comment]
I just did a little test with the universal-start and a added a little `console.log('app booting')` to the `AppModule.constructor` and started up the node server and on each request it was logging out the 'app booting' as expected.

**Comment by Toxicable** [comment]
Ah yeah, my guess is that it was something specific to your app.
If you do find an issue with it do let me know :D

**Comment by CaerusKaru** [comment]
The issue was with Apollo-GraphQL, which for Angular at least has very lacking documentation (mostly centered around Angular v2). It by default caches all queries, which makes sense client-side. Right now you can only disable caching by query, but they're working on having an option to disable this for all queries in their next version. Only time will tell when the apollo-angular package will support it.
