### ISSUE TITLE
Type 'Request' is not Generic error in beta.4

### ISSUE THREAD

**Issue by leo6104** [angular/universal#833]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
In beta.4 version `src/tokens.d.ts`, 
```
export declare const REQUEST: InjectionToken<Request<any, any, any, any>>;
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
```
1. npm install @nguniversal/express-engine
2. check node_modules/@nguniversal/express-engine/src/token.d.ts
```

* **What is the expected behavior?**
It should be 
```
export declare const REQUEST: InjectionToken<Request>;
```

* **What is the motivation / use case for changing the behavior?**
it is regression bug. 

* **Please tell us about your environment:**

- Angular version: 5.0.0-rc.8
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [Typescript 2.5 ]
- OS:  [Mac OS X]
- Platform: [NodeJS]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by vikerman** [comment]
Hi - What TypeScript version are you on? I saw it once but haven't been able to reproduce this since.

**Comment by lazarljubenovic** [comment]
I have the same isse with `2.5.3`. My guess is that you have a different version of `@types/express` installed locally; maybe a good idea to lock it? I'm on `@types/express@4.0.39`.

**Comment by Toxicable** [comment]
We just need to bumped the `@types/express` version to fix this up

**Comment by vikerman** [comment]
Release with fixed express types coming up shortyl
