### ISSUE TITLE
Possible bug: unable to transferState via child module

### ISSUE THREAD

**Issue by cmddavid** [angular/universal#839]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

Bug

* **What is the current behavior?**

I tried to use TransferState inside one of my child modules, but both set and get are not working. The stateTransfer object is just never set, even though according to Universal logging it is. For now I worked around the problem by using observables that I subscribe to via my parent module root component that stream me the data that needs to be set for TransferState. And I rehydrate the child module by using a service method called via the parent module root component as well.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Try using TransferState via a child module and you will see.

* **What is the expected behavior?**

TransferState should also work when being used by child modules

* **What is the motivation / use case for changing the behavior?**

I had to use a workaround that should not be needed

* **Please tell us about your environment:**

- Angular version: 5
- Browser: All
- Language: TS
- OS:  Mac OS
- Platform: Node.js

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by Toxicable** [comment]
Could you make am minimal reproduction showing this issue?

**Comment by cmddavid** [comment]
@Toxicable hoping to make a minimal repro tonight :-) I'll keep you posted.

**Comment by cmddavid** [comment]
So I tried making a reproduction, but everything is working fine in the repro. Will do a little more research to find the problem, perhaps its just the combination of packages or functionalities I'm using in this particular project that is causing the issue. Will keep you posted :-)

**Comment by cmddavid** [comment]
So after more testing, I think I just made a mistake in my own app. Will close this for now, if I do find the cause in my app and it appears to be a bug I will report back.
