### ISSUE TITLE
MutationObserver Error

### ISSUE THREAD

**Issue by MurhafSousli** [angular/universal#840]
* **I'm submitting a ...**
```
- [x] bug report
```

* **Do you want to request a *feature* or report a *bug*?**

I think it is a **bug**

* **What is the current behavior?**

`ERROR ReferenceError: MutationObserver is not defined`

* **If the current behavior is a bug, please provide the steps to reproduce

```ts
this.observer = new MutationObserver((mutations: MutationRecord[]) => {
   mutations.forEach(() => {
      // ....
   });
});
const config: MutationObserverInit = {
  // ...
};
this.observer.observe(this.el.nativeElement, config);
```

* **What is the expected behavior?**

No errors

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.X
- Browser: all
- Language: all
- OS:  all
- Platform: NodeJs

I tried [MutationObserver polyfill](https://github.com/webmodules/mutation-observer/issues/7), but that one throws another error because it uses `window` so it won't help in Universal.

I also found this old issue here https://github.com/fgnass/domino/issues/80

Is there a workaround or anything I can do to fix it?

**Comment by robisim74** [comment]
`MutationObserver` is an event on the objects of the DOM, so it is doesn't exist during SSR. Only way I found is detecting before using it:
```
        if (typeof MutationObserver !== "undefined") {
           this.observer = new MutationObserver((mutations: MutationRecord[]) => {
           ...
           });
        }
```

**Comment by CaerusKaru** [comment]
@robisim74's solution is correct. Domino (the SSR DOM) has no implementation of `MutationObserver`, although there is an ancient [issue open](https://github.com/fgnass/domino/issues/80) for it in the Domino repo. But this is definitely not a Universal issue, so closing.
