### ISSUE TITLE
 Event is not defined

### ISSUE THREAD

**Issue by Gorniv** [angular/universal#844]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

when I upgrade from angular 5.0.0 to 5.0.1 EventManager was broken with `ReferenceError: Event is not defined`

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
```
constructor(
    private eventManager: EventManager,
  ) {
  }
```
upgrade angular from 5.0.0 to 5.0.1

* **Please tell us about your environment:**

- Angular version: 5.0.1
- Browser: [all]
- Language: [all  ]
- OS:  [all]
- Platform: [NodeJs ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
```
ERROR { Error: Uncaught (in promise): ReferenceError: Event is not defined
ReferenceError: Event is not defined
```

**Comment by ychost** [comment]
i have the same issue , it may be caused by @HostListener

**Comment by wpcfan** [comment]
I experienced this as well, it seems adding hostlistener may lead to this error too

**Comment by wpcfan** [comment]
please have a look at the https://github.com/wpcfan/universal-starter.git, I did not add any document/window stuff, just a directive with @HostListener, and it will cause the error

**Comment by Toxicable** [comment]
Thanks for reporting this, looks like a bug to me, will investigate.
@wpcfan if you remove the `:Event` then you error goes away

**Comment by Gorniv** [comment]
me help `global['Event'] = null;` in server.ts

**Comment by rodrigjg** [comment]
Got the exact same error and after applying the fix from @Gorniv I get the same error just with FocusEvent and KeyboardEvent. I don't know what could cause this.

**Comment by patrickmichalina** [comment]
Removing the type fixes this

**Comment by Flood** [comment]
I am experiencing this bug as well, but I use aspnetcore-engine.

**Comment by JiaLiPassion** [comment]
I believe the error is caused by the code I added, I will check it.

**Comment by JiaLiPassion** [comment]
I created a PR to fix some issues about `Event is not defined` in here, https://github.com/angular/angular/pull/22905.
@thovo, could you post a reproduce repo about this error

```
ERROR { Error: Uncaught (in promise): Error: no Promise impl found
Error: no Promise impl found
```

**Comment by thovo** [comment]
I am sorry that I can not reproduce for you a repository with that errors. But, to resolve my problem, I isolated the part which had the call with Event by wrapping everything in the condition of `platformBrowser` and it worked normally now. I hope it could help other with similar issues. Actually, I wrapped almost everything inside of `platformBrowser` to prevent error like above.
