### ISSUE TITLE
Create client WebWorker app example

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#85]
An Angular app on the Client that's in a WebWorker should also be able to start off server rendered and preboot.js

**Comment by manekinekko** [comment]
I'm on this one.

**Comment by manekinekko** [comment]
I encountered an issue, here are some details... https://github.com/angular/angular/issues/3658

**Comment by gdi2290** [comment]
you can make the example in the `examples/` folder since we're building from source

**Comment by manekinekko** [comment]
Yeah! That what's I ended up doing. I am able to load the index in the browser but I have some issues with the Pipe class which is undefined. I am working on it.

![image](https://cloud.githubusercontent.com/assets/1699357/9291196/c8c352a8-43b2-11e5-8ba0-aa42a452ec4f.png)

**Comment by gdi2290** [comment]
can you open a PR so I can check it out?

**Comment by manekinekko** [comment]
sure! Here is the PR https://github.com/angular/universal/pull/95

**Comment by gdi2290** [comment]
will be done via [answers-app](https://github.com/angular/answers-app)
