### ISSUE TITLE
lodash.get not working with Angular Universal

### ISSUE THREAD

**Issue by untitledlt** [angular/universal#850]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
`lodash.get` throws an error when code is run on server:
`ERROR TypeError: l.default is not a function`

```
import get from 'lodash.get';

const path = get(item, 'pictures[0].path');
````

* **What is the expected behavior?**
It should return value and should not produce any errors.

* **Please tell us about your environment:**

- Angular version: 5
- Browser: [node server rendering]
- Language: [TypeScript]
- OS:  [Mac OS X]
- Platform: [NodeJs]

**Comment by Toxicable** [comment]
This is likely an issue with Lodash no Universal
