### ISSUE TITLE
Will not install properly

### ISSUE THREAD

**Issue by nigel-dewar** [angular/universal#857]
- [x] bug report

- [x] express-engine

Following instructions found here https://universal.angular.io/quickstart/ I followed them exactly.

Install fails at this stage here: 
 typings install node express body-parser serve-static express-serve-static-core mime --ambient

![image](https://user-images.githubusercontent.com/9402456/33508203-b4ec2214-d744-11e7-896d-be48165b80d5.png)

System
Windows 10 Pro x64
Node version 8.9.1
NPM v 5.5.1

Node-Gyp etc all installed well, and I got the angular starter working fine https://github.com/gdi2290/angular-starter and ran it.

The issue is with
 typings install node express body-parser serve-static express-serve-static-core mime --ambient

**Comment by rsquared86** [comment]
looks like typings is deprecated https://github.com/typings/typings

i changed the command to:

npm install node express body-parser serve-static express-serve-static-core mime --global

it installed these packages:

body-parser
express
mime
serve-static
node
express-serve-static-core

so hopefully that works.

**Comment by nigel-dewar** [comment]
Thank you very much . I will try this.

**Comment by nigel-dewar** [comment]
Your advice worked,

However, when trying to run the project the server bugged out

I lost patience, and just found this https://github.com/angular/universal-starter

Which works fine.

Cheers
