### ISSUE TITLE
Universal version initialized 3 times

### ISSUE THREAD

**Issue by phihochzwei** [angular/universal#859]
* **I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] support request 

* **What modules are related to this Issue?**

- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
As mentioned in [here](https://github.com/angular/universal/issues/858) we are trying to load JSON files via a service that is called/provided via APP_INITIALIZER. We also use an interceptor for our authentication chain later on. However, both, the TextService and the Interceptor have a console.log() within their constructor. And when the application in opened in the browser, I can see those calls 3 times in the server window (taken straight from [here](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md) ). The "regular" version does not show this behavior.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.
- Create a service to load json-files via HttpClient.
- Call it via APP_INITIALIZER
- Provide an interceptor
- Turn on Universal according to https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/universal-rendering.md

* **What is the expected behavior?**
The expected behaviour would be, that those services are only constructed once.

* **Please tell us about your environment:**

- Angular version: 5.0
- Browser: [all ]
- Language: [all ]
- OS:  [Mac OS X | Windows ]
- Platform: [all | NodeJS]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. Luckily, it has already been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.
