### ISSUE TITLE
aspnetcore engine template

### ISSUE THREAD

**Issue by chamikasandamal** [angular/universal#861]
Shall we communicate with aspnet team officially and make a common template by involving both teams.
I can see angular has a suggestion here
https://github.com/angular/universal/tree/master/modules/aspnetcore-engine

and aspnet team trying to create new template here
https://github.com/aspnet/JavaScriptServices/issues/1288

It would be great if we can combine and share the effort.

**Comment by MarkPieszak** [comment]
The goal is to move everything aspnet towards using the CLI as Steve Sanderson has done, and we'll just be helping here with making utilities that might come in handy with it.

At the moment there are some issues with the engine with the latest from 5.0 and the AngularCompilerPlugin so I'm still working on fixing those!

**Comment by chamikasandamal** [comment]
@MarkPieszak : Do you have any idea on this https://github.com/aspnet/JavaScriptServices/issues/1439

when we put a style file inside styles array in `.angular-cli.json` will it automatically added to index.html with serverside rendering. i think it is adding in client side rendering. what would be the expectation?

 "styles": [
    "./styles/styles.scss"
  ]

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
