### ISSUE TITLE
Lazy loaded modules throws loading error when entering the site on localhost:4000

### ISSUE THREAD

**Issue by christofferskog** [angular/universal#862]
* **I'm submitting a ...**
```
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Bug.

* **What is the current behavior?**
When I use lazy loading with `loadChildren` like:

```
{
  path: '',
  loadChildren: './routes/+home/home.module#HomeModule'
}
```

It throws this error when you navigate to that route:

`Error: Cannot find module './routes/+home/home.module.ngfactory'.`

Although the route still loads like it should, I'm not sure if this is something I can ignore or if it will break when robots will try to enter the site.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

First follow this guide:

https://github.com/angular/angular-cli/wiki/stories-universal-rendering

Then create a simple lazy loaded module like the example above, then run the app with `npm run build:ssr && npm run serve:ssr` and navigate to `localhost:4000` and check the **terminal**. 

* **What is the expected behavior?**
The expected behaviour would be that no errors are thrown and that the factory is loaded, or if the factory isn't needed on the server side, ignore the error as it creates confusion.

* **What is the motivation / use case for changing the behavior?**
To avoid confusion and the app possibly breaking.

* **Please tell us about your environment:**

- Angular version: 4.4.6
- Browser: [all]
- Language: [all]
- OS:  [all ]
- Platform: [NodeJs]

**Comment by Toxicable** [comment]
Are you using 
https://github.com/angular/universal/tree/master/modules/module-map-ngfactory-loader
?

**Comment by nekkon** [comment]
I probably have the same problem https://github.com/angular/universal/issues/854

**Comment by christofferskog** [comment]
@nekkon They seem to be similar but I'm unsure if it's exactly the same issue.

**Comment by mszewcz** [comment]
Ha the same problem:
```
ERROR { Error: Uncaught (in promise): Error: Cannot find module '../pages/lazy.module.ngfactory'.
Error: Cannot find module '../pages/lazy.module.ngfactory'.
```
@angular @ 5.1.1
@angular/cli @ 1.6.1
```

**Comment by csutorasr** [comment]
Thank you @nekkon . [This](https://github.com/angular/universal/issues/854#issuecomment-348981472) have solved it for me.

**Comment by Toxicable** [comment]
You likely just need https://github.com/angular/universal/tree/master/modules/module-map-ngfactory-loader
