### ISSUE TITLE
server side rendering hanging for minutes

### ISSUE THREAD

**Issue by rwmb** [angular/universal#863]
* **I'm submitting a ...**
```
- [x ] bug report
- [ ] feature request
- [ ] support request
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```
I have an app that I've setup the environment for server side rendering with nodejs, but when I use the server rendering, the app hangs for minutes before it loads the page (I believe it's because I use a lot of setTimeouts to make a "presentation").
If you guys think it's related to the timeouts I can post more information.

- Angular version: 5.0
- Browser: [all]
- Language: [all ]
- OS:  [ Windows | Linux ]
- Platform: [NodeJs]

**Comment by Toxicable** [comment]
This isn't an issue with Universal.
Universal will wait for all async operations ( including timeouts) to complete before rendering

**Comment by rwmb** [comment]
I thought this could be the problem. Thanks @Toxicable. Is there a way of preventing this from happening?

**Comment by Toxicable** [comment]
There is no "catch all" solution on this one sorry, you'll have to just manage your async operations

**Comment by rwmb** [comment]
Yeah, but is there a way to know if the app is being called from my domain? This way I could just return the app with "express.static", and if it's not, I would run different operations that don't include the async operations.
