### ISSUE TITLE
Response hangs on some routes when page reload

### ISSUE THREAD

**Issue by daright** [angular/universal#867]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

I have an angular application with lazy loaded routes. When I reload page some routes are working fine, but others hang and are pending until timeout, no error is thrown. Is there a way to debug this behaviour?
I used this tutorial https://angular.io/guide/universal

* **Please tell us about your environment:**

- Angular version: 5.1
- Browser: [all]
- Language: [TypeScript 2.5.2]
- OS:  [Windows]
- Platform: [NodeJs]

**Comment by naturalfreak** [comment]
Same here.

**Comment by CaerusKaru** [comment]
If this is an issue with Universal rendering, and not a package supplied by the nguniversal namespace (express-engine, common, etc), please report this issue in the angular/angular repository.

**Comment by CaerusKaru** [comment]
Also, the main method I use to trace debugging is to add console out along the rendering path, since likely there is a service or guard somewhere preventing a component from being loaded (though here it might sound like there's a deeper issue)

**Comment by Quovadisqc** [comment]
I had this problem when using an infinite ``Observable.interval`` to do a rotating slider. To fix this, I started only subscribing to the Observable on client side ( using ``isPlatformBrowser``).

You should look out for Observers that get created on init and are never completed.

**Comment by daright** [comment]
the problem was with ng2-slim-loading-bar library
I think it did never complete on those routes or something, but it took me too long to find this issue so I dropped that lib completly.
Thanks for the help!
