### ISSUE TITLE
Access to request inside Angular on server

### ISSUE THREAD

**Issue by m98** [angular/universal#869]
* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] express-engine
- [ ] hapi-engine
```

* **What is the current behavior?**
As far as I know there is no way to have access to express header when Angular is rendering on the server side.

* **What is the expected behavior?**
A way to pass the Express request to the Angular app, or, an API to access request on the Angular app.

* **What is the motivation / use case for changing the behavior?**
The request might be very helpful to design more optimized web app based on the user device which can be found on the user agent (need request to found it on Node)

For example, we can adaptively change the web app, when we detect the user agent is a mobile device, and on each component `onInit` we can decide which HTTP requests we make and which to avoid it it's a mobile device.

* **Please tell us about your environment:**

- Angular version: 5.1.0
- Browser: Chrome - Version 61.0.3163.100 (Official Build) (64-bit)
- Language: TypeScript
- OS:  Fedora
- Platform: NodeJs

**Comment by MarkPieszak** [comment]
It's actually already part of the express-engine:

https://github.com/angular/universal/tree/master/modules/express-engine#using-the-request-and-response

**Comment by m98** [comment]
Thank you.

Close as Express-engine already has the requested feature.
