### ISSUE TITLE
Make PreloadCache for server/client

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#87]
There needs to be a way for developers to preload their json data on the server to be sent to the client for to grab out of the preloaded cache.

```html
<module import="/preloadCache.js"></module>
<script>window.preloadCache.setRef('request');</script>

<app></app>
<module import="/preboot.js"></module>

<module>
  import {bootstrap} from '@angular/angular';
  import {App} from './app';

  bootstrap(App, []);
</module>
<script>window.preloadCache.complete('request', { data: 'serverData' });</script>
```

It's important that the PreloadCache can happen after bootstrap as the serialized data could be a large data set that is being streamed down to the client with the html

 - [x] PreloadCache https://github.com/angular/universal/issues/93
 - [x] NgPreloadCacheServer
 - [x] NgPreloadCacheClient
 - [x] Http Server/Client with PreloadCache

**Comment by tbosch** [comment]
The way React does it seems pretty smart and is independent of the data layer used: cache the responses for http requests made on the server and serialize the cache to the client.

**Comment by tbosch** [comment]
See https://github.com/facebook/relay/issues/36#issuecomment-130402024

**Comment by gdi2290** [comment]
done
