### ISSUE TITLE
Should I use hashing-ouput for the server side

### ISSUE THREAD

**Issue by Scipionh** [angular/universal#874]
For the server platform, the norm seems to go with `ng build --prod --environment=ci --app 1 --output-hashing=false`

Why do we need to turn off the `output-hashing` here ? Couldn't it lead to differences between what the browser and server have ? 

Also, kind of a similar thing, should I use my `serviceWorker=true` in the` .angular-cli.json` (for the `platform="server"`) ? According to the logic above, I should probably set it to false, but not sure to get why.

**Comment by MarkPieszak** [comment]
Yes we need to have `output-hashing=false` since we're grabbing the file in the `server.ts`. Otherwise you'd have to update the new name it created in the `/dist/server` folder for the server.js file. 

Hope that helps!
