### ISSUE TITLE
Lazy Loading breaks service injection in non-AOT builds

### ISSUE THREAD

**Issue by artemzakharov** [angular/universal#877]
* **I'm submitting a ...**
```
- [ X ] bug report
- [ ] feature request
- [ ] support request 
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**

bug

* **What is the current behavior?**

If the project is compiled in a non-AOT manner, injecting a service into a lazily loaded component causes an error when things are injected into that service as well.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

See following comment:
https://github.com/aspnet/JavaScriptServices/issues/1408#issuecomment-354992270

* **What is the expected behavior?**

A service injected into a lazily loaded component should be able to resolve all of its parameters whether the project was compiled with AOT or not.

* **What is the motivation / use case for changing the behavior?**

I would like to be able to leverage both lazy loading and server-side rendering in my project without always having to build with AOT. 

* **Please tell us about your environment:**

- Angular version: 5.0
- Browser: [ Chrome 61 ]
- Language: [ TypeScript 2.4.2 ]
- OS:  [ Windows ]
- Platform: [ .NET Core ]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

This issue was originally brought up in the aspnet/JavascriptServices project. Running into it myself, I initially thought it was a problem with the .NET Core 2.0 Angular CLI template; @SteveSandersonMS investigated the issue, and determined that it still occurred even when the Angular code was pulled out and made into a standard standalone CLI application, implying that there may be a bug with Angular itself. It thus seems prudent to raise the issue here. 

It's also possible that my project structure is what's to blame; it seems unlikely since I've never had similar errors when not using SSR, but for comprehensiveness, I outline how I structured the modules that raised the bug in this comment:

https://github.com/aspnet/JavaScriptServices/issues/1408#issuecomment-354938379

Here is the full stack trace; in this case, I'm injecting the Router into my own 'Cart' service, which itself is injected into the lazily loaded component. The cart service can't resolve the router injection, hence the (?).

```
NodeInvocationException: Can't resolve all parameters for CartService: (?).
Error: Can't resolve all parameters for CartService: (?).
at syntaxError (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:528:34)
at CompileMetadataResolver._getDependenciesMetadata (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15707:35)
at CompileMetadataResolver._getTypeMetadata (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15542:26)
at CompileMetadataResolver._getInjectableMetadata (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15522:21)
at CompileMetadataResolver.getProviderMetadata (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15882:40)
at C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15793:49
at Array.forEach (<anonymous>)
at CompileMetadataResolver._getProvidersMetadata (C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15753:19)
at C:\Users\arzakhar\jstemplates\ssr-error\ClientApp\node_modules\@angular\compiler\bundles\compiler.umd.js:15241:63
at Array.forEach (<anonymous>)
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases.
