### ISSUE TITLE
APP_BASE_HREF not working

### ISSUE THREAD

**Issue by dereklin** [angular/universal#878]
**Note: for support questions, please use one of these channels:** https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports. Also, **Preboot has moved** to https://github.com/angular/preboot - please make preboot-related issues there.

* **I'm submitting a ...**
```
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```
n/a

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
I deleted 
```
<base href="/">
``` 
from index.html

In app.module.ts, I added:
```
  providers: [
    {provide: APP_BASE_HREF, useValue: '/sub/starter/'}
  ]

```
After prerendering, the pathes to the scripts are wrong.  They are rendered as if the base href is '/'.  As a result, the prerendered lazy/index.html doesn't work.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

Clone this repo: https://github.com/dereklin/universal-starter
Run npm install
Run npm run build:prerender
Check the lazy/index.html in the dist folder, see that the pathes are wrong

* **What is the expected behavior?**

The pathes should be correct.

* **What is the motivation / use case for changing the behavior?**
Support the usage of something similar to:
```
  providers: [
    {provide: APP_BASE_HREF, useValue: '/sub/starter/'}
  ],
```

* **Please tell us about your environment:**

- Angular version: 5.2
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJs | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by xrobert35** [comment]
Hello,

I'm using **angular-cli** to manage my build and I wanted to access my server from localhost:8000/views. 

To do this I added  '-d /views/ --base-href /views/'  on both app build commande. Exemple : 
`ng build --prod -d /views/ --base-href /views/ --app 1`

And I told my server go manage this route changing base configuration to : 

```
app.use('/views', express.static('./', { index: false }));

app.get('/views/*', (req, res) => {
  res.render('index', {
    req,
    res
  });
});
```

**Comment by alan-agius4** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem persists after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior.
