### ISSUE TITLE
https://universal.angular.io/quickstart/ features Angular 2 and https://github.com/angular/ Angular 4

### ISSUE THREAD

**Issue by intergleam** [angular/universal#879]
https://universal.angular.io/quickstart/ features Angular 2 and https://github.com/angular/ Angular 4, that is confusing to say the least

**Comment by MarkPieszak** [comment]
Yes we need to update that microsite, apologies and thank you for creating the issue!

**Comment by CaerusKaru** [comment]
Related to https://github.com/angular/universal/issues/865#issuecomment-351509458

**Comment by Toxicable** [comment]
fixed  https://universal.angular.io now redirects to the angular.io Universal guide
