### ISSUE TITLE
Universal doesn't wait for child after a route resolver

### ISSUE THREAD

**Issue by Amiral1** [angular/universal#880]
If parent resolves, then universal does not catch the child's http calls and renders immediately. 

Router
```
 {
    path: 'user/:id',
    component: UserComponent,
    resolve: {
      user_profile: UserResolver
    },
    children: [
      {
        path: 'overview',
        component: UserOverviewComponent,
      },
      ...
    ]
}
```

Resolver
```
 @Injectable()
 export class UserResolver implements Resolve<User> {
 
   constructor(userService: UserService) { }

   resolve(route: ActivatedRouteSnapshot): Observable<any> {
     let id = route.paramMap.get("id");
     return this.userService.getUserProfile(id);
   }
 }
```

UserComponent (Parent)
```
    this.user_profile = this.route.snapshot.data.user_profile;
    // this data is rendered server-side correctly
```

UserOverviewComponent (Child)
```
    this.http.get('http://my-api.com') // <-- here the request will not be rendered server-side
    .subscribe(data => {
      this.child_data = data; // this data is not accessible server side
    });
```

Any idea how I can fix this?

Thanks for your help!

Otherwise fantastic work, a big thank you to the team :)

**Comment by svoychik** [comment]
Okay, what if you try to set `initialNavigation: 'enabled'`. Like this:
RouterModule.forRoot(yourRoutes, {
      enableTracing: false,
      initialNavigation: 'enabled'
    })

**Comment by Amiral1** [comment]
@svoychik It's not working either

**Comment by Amiral1** [comment]
Sorry, I think the problem comes from a misconfiguration of my main server. Thanks for your help!
