### ISSUE TITLE
HttpClient won't send a request. Errors with Unknown Error Immediately

### ISSUE THREAD

**Issue by JohnGalt1717** [angular/universal#883]
* **I'm submitting a ...**
```
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [X ] aspnetcore-engine
- [ ] express-engine
- [ ] hapi-engine
```

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
HttpClient that is direct injected by a constructed class called in app.module will fail to make any requests. It just immediately returns "Unknown Error". Without SSR enabled it works fine client side.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** by creating a github repo.

I have a provider like this in the providers section of the app.module

{ provide: APP_INITIALIZER, useFactory: AppModule.InitializeConfig, deps: [RestClient, Injector, Globals, TransferState, SITE_URL, SITE, QUERY_STRING, REQUEST_PATH], multi: true }

In the Imports is HttpClientModule

RestClient is a class library with the following definition in the constructor:

constructor( @Inject(SERVICE_URL) serviceUrl: string, @Inject(CLIENT_ID) clientId: string, private http: HttpClient) ...

http is set to an instance of HttpClient fine upon inspection using the node debugger.

this.http.get<IBaseResponse<T>>(<some valid http url>) will fail with "unknown" error

* **What is the expected behavior?**

Should work like it did in Angular 4.4.6

* **Please tell us about your environment:**

- Angular version: 5.2.5
- Browser: all
- Language: TypeScript 2.6.2
- OS:  windows
- Platform: .NETCore

**Comment by Toxicable** [comment]
Shot in the dark here, but do you provide an Absolute URL to `httpclient.get(absoluteUrl)`?
The HttpClient on the sever does not currently support relative urls

**Comment by patrickmichalina** [comment]
I recommend you write an http interceptor that checks for relative urls. Basically, if you perform an http request like `http.get('/api/note/1')`, the interceptor should detect that its not absolute and replace the relative url with the absolute URL

**Comment by MarkPieszak** [comment]
Think I forgot to close this one out, I spoke with John about this one over in the dotnet repo.

Note this error will occur in a normal (non-universal application as well).

The workaround is that you have to use the Injector to get HttpClient, and not add HttpClient as a dependency itself. 


    public get http() {
      return this.injector.get(HttpClient);
    }
