### ISSUE TITLE
npm-shrinkwrap exception

### ISSUE THREAD

**Issue by harikrishnan-u01** [angular/universal#890]
npm-shrinkwrap is throwing the following error:

`peer invalid: @angular/platform-server@^5.0.0-rc.6, required by @nguniversal/express-engine@5.0.0-beta.5`

My project is using angular version 5.2.1

Kindly help. This error is preventing in locking the npm versions.

**Comment by Toxicable** [comment]
Should be fixed in the latest version, feel free to open this back up if you still have issues
