### ISSUE TITLE
How to run build or dist code on server

### ISSUE THREAD

**Issue by Gajendrasinh** [angular/universal#892]
I know how to build project(sudo ung build --prod --env=prod)... but don't know how to run it...

I have 2 folders in dist:

client and server

Any exaple how to run it?

**Comment by cmddavid** [comment]
Try running `npm run serve:ssr`, or if that doesn't work: `node dist/server`

**Comment by Toxicable** [comment]
Checkout out our starter, https://github.com/angular/universal-starter
in the package.json it has scripts demoing the commands you need to start it
