### ISSUE TITLE
Workaround encapsulation NATIVE (doesn't work on server)

### ISSUE THREAD

**Issue by gdi2290** [angular/universal#90]
We need to either run EMULATED whenever we see NATIVE encapsulation setting or find another way to do this. Previously we would set EMULATED in the bindings but that never really solved the problem for components other than the root

we can probably overwrite the DomRenderer with ServerDomRenderer

**Comment by jeffbcross** [comment]
@gdi2290 I'm curious what happens now when `Native` is used.

**Comment by gdi2290** [comment]
fixed via https://github.com/angular/universal/commit/5d272bab1738d90326f2675a2847e1045c440d62#diff-219141a380d37405732141ba0a4c10c3R47
