### ISSUE TITLE
TransferHttpCacheModule Cannot instantiate cyclic dependency

### ISSUE THREAD

**Issue by dottodot** [angular/universal#901]
I'm just trying to include TransferHttpCacheModule into my app but I throws the errors below. I believe it's somehow related to the APP_INITIALIZER I have setup as when I remove that the error goes away.

> Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppServerModule in /src/client/app/app.server.module.ts@-1:-1
>     at NgModuleProviderAnalyzer.parse (/node_modules/@angular/compiler/bundles/compiler.umd.js:19593:19)
>     at NgModuleCompiler.compile (/node_modules/@angular/compiler/bundles/compiler.umd.js:20182:36)
>     at AotCompiler._compileModule (/node_modules/@angular/compiler/bundles/compiler.umd.js:30950:32)
>     at /node_modules/@angular/compiler/bundles/compiler.umd.js:30832:66
>     at Array.forEach (<anonymous>)
>     at AotCompiler._compileImplFile (/node_modules/@angular/compiler/bundles/compiler.umd.js:30832:19)
>     at /node_modules/@angular/compiler/bundles/compiler.umd.js:30803:26
>     at Array.map (<anonymous>)
>     at AotCompiler.emitAllImpls (/node_modules/@angular/compiler/bundles/compiler.umd.js:30802:52)
>     at AngularCompilerProgram.generateFilesForEmit (/node_modules/@angular/compiler-cli/src/transformers/program.js:506:42)
>     at AngularCompilerProgram.emit (/node_modules/@angular/compiler-cli/src/transformers/program.js:173:23)
>     at AngularCompilerPlugin._emit (/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:773:49)
>     at Promise.resolve.then.then.then (/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:602:54)
>     at <anonymous>
>     at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by dottodot** [comment]
I've resolved it for by using Injector for the HttpClient in my APP_INITIALIZER i.e

```
 get http() {
    return this.injector.get(HttpClient);
  }
```

**Comment by CaerusKaru** [comment]
Perfect, that’s exactly what you’re supposed to do.

**Comment by hymenoby** [comment]
Great this works for me. but as @bellizio asked is this the best way? 

i have three angular app and that error just happened on one out ouf three i don't kwow why, in the others i just inject the httpClient in the APP_INITIALIZER Service

**Comment by evgenyetoro** [comment]
Same issue here.
I use universal.
In my app if I add usage of my own interceptor (logging interceptor), i get same error.

ERROR in : Error: Provider parse errors:
Cannot instantiate cyclic dependency! ApplicationRef ("[ERROR ->]"): in NgModule AppServerModule in C:/etoro-lps/src/app/app.server.module.ts@-1:-1

If I remove my custom interceptor, the error disappears.

Any ideas?
