### ISSUE TITLE
allow node v8 and higher for hapi-engine

### ISSUE THREAD

**Issue by amelialaundy** [angular/universal#904]
Same issue as https://github.com/angular/universal/issues/851 but for hapi-engine:

`error @nguniversal/hapi-engine@5.0.0-beta.5: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 <= 7".
error Found incompatible module
`

**Comment by CaerusKaru** [comment]
Will be fixed by #903, which lifts this requirement for all modules

**Comment by CaerusKaru** [comment]
Can be closed with the release of 5.0.0-beta.6
