### ISSUE TITLE
Home and Dynamic Url Page not rendering

### ISSUE THREAD

**Issue by arun-maddheshia** [angular/universal#907]
Everything works fine but when I visit my blog listing to blog detail the page is not renderd, also my home page content is not render in Page Source. Any idea how to fix.

My Routes is
`{
    path: '',
    component: HomeComponent,
    pathMatch: 'full'
  },
  {
    path: 'blog/:id',
    component: BlogDetailComponent,
  },`

**Comment by denis-andrikevich** [comment]
any repo?

**Comment by arun-maddheshia** [comment]
nope but I can provide more info if u need

**Comment by denis-andrikevich** [comment]
Just checked universal starter. Ssr working perfect.
https://github.com/denis-andrikevich/universal-starter
