### ISSUE TITLE
Universal and firebase hosting not working with LAZY_MODULE_MAP

### ISSUE THREAD

**Issue by StudioTOB** [angular/universal#915]
Hi,
I've been trying to get universal with lazy loading to work with firebase hosting. But somehow it is not letting me use the ModuleMapLoaderModule. I think it's best to show what I did.

**The app.server.module**

    import { NgModule } from '@angular/core';
    import { ServerModule } from '@angular/platform-server';
    import { AppModule } from './app.module';
    import { AppComponent } from './app.component';
    import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

    @NgModule({
    imports: [
    AppModule,
    ServerModule,
    ModuleMapLoaderModule
    ],
    bootstrap: [AppComponent],
    })
    export class AppServerModule {} 

**The index.js inside the functions folder (created by firebase hosting)**

    require('zone.js/dist/zone-node');

    const functions = require('firebase-functions');
    const express = require('express');
    const path = require('path');
    const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');
    const { enableProdMode } = require('@angular/core');
    const { renderModuleFactory } = require('@angular/platform-server');
    const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist-server/main.bundle');

    enableProdMode();

    const index = require('fs')
    .readFileSync(path.resolve(__dirname, './dist/index.html'), 'utf8')
    .toString();

    let app = express();

    app.get('**', function (req, res) {
    renderModuleFactory(AppServerModuleNgFactory, {
     url: req.path,
    document: index,
    extraProviders: [
    provideModuleMap(LAZY_MODULE_MAP)
    ]
    }).then(html => res.status(200).send(html));
    });

When I remove the extraProviders array in the index.js and remove the ModuleMapLoaderModule import from the app.server.module it works, but then I only have the <router-outlet _ngcontent-c0=""></router-outlet> with no texts from the component. SO if anyone can point me to the right direction, it would be great.

Thanks in advance,

Brian

**Comment by Toxicable** [comment]
Have you tried debugging it locally?

**Comment by StudioTOB** [comment]
Hi Toxicable,

I've tried, but there is another issue. It had something to do with Node versions not matching.  But I went to another approach. 
And that's called Rendertron. It works great. No need to make my app Universal anymore with this.

**Comment by Toxicable** [comment]
Thanks. In that case ill consider this closed then
