### ISSUE TITLE
How it import express tokens without increasing the bundle size

### ISSUE THREAD

**Issue by dottodot** [angular/universal#920]
in express-engine@5.0.0-beta.5 the token where imported as 

```
import { REQUEST, RESPONSE } from '@nguniversal/express-engine/tokens';
```
but in express-engine@5.0.0-beta.6 you have to do 
```
import { REQUEST, RESPONSE } from '@nguniversal/express-engine';
```
This change alone adds domino into the production build adding an extra 280kb to the bundle size.

**Comment by Toxicable** [comment]
Thanks  for reporting us. This was a side affect of our recent change to use the Angular Package Format.
We're currently working on a fix to use a secondary entrypoint (similar to what it was before).

Until then we suggest either going back to beta.5 for now.

Will update when we have a fix
