### ISSUE TITLE
Missing specified styles (both through [ngStyle] or using Renderer2 .setStyle in custom component

### ISSUE THREAD

**Issue by agustinhaller** [angular/universal#929]
* **I'm submitting a ...**
```
- [X] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] common
- [X] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
Latest version of Angular does not include specified styles (both through `[ngStyle]` or using Renderer2 `.setStyle()` method in custom components

* **If the current behavior is a bug**, please provide the steps to reproduce and if possible a minimal demo of the 
problem by creating a github repo.

Just print elementRef and observe the style attribute is missing from `_attrsByQName`

*Working example using Angular `5.0.2`*
```javascript
this._renderer.setStyle(this._elementRef.nativeElement, 'paddingBottom', ratio_height);
console.log("_elementRef", this._elementRef.nativeElement);
```
```bash
_attrsByQName:
   { alt:
      { ownerElement: [Circular],
        localName: 'alt',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     class:
      { ownerElement: [Circular],
        localName: 'class',
        prefix: null,
        namespaceURI: null,
        data: 'user-image' },
     title:
      { ownerElement: [Circular],
        localName: 'title',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     style:
      { ownerElement: [Circular],
        localName: 'style',
        prefix: null,
        namespaceURI: null,
        data: 'padding-bottom:100%;' } },
```

* **NOT** working example using Angular `5.2.8`*
```javascript
this._renderer.setStyle(this._elementRef.nativeElement, 'paddingBottom', ratio_height);
console.log("_elementRef", this._elementRef.nativeElement);
```
```bash
_attrsByQName:
   { alt:
      { ownerElement: [Circular],
        localName: 'alt',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' },
     class:
      { ownerElement: [Circular],
        localName: 'class',
        prefix: null,
        namespaceURI: null,
        data: 'user-image' },
     title:
      { ownerElement: [Circular],
        localName: 'title',
        prefix: null,
        namespaceURI: null,
        data: 'profile image' } },
```

* **What is the expected behavior?**
Custom components has the specified styles.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.2.8
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: TypeScript
- OS:  Mac OS X
- Platform: NodeJS

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by CaerusKaru** [comment]
Closing as discussed in angular/universal-starter#552
