### ISSUE TITLE
introduce StateTransferInitializerModule - doesn't include to 5.0.0-beta.7 release

### ISSUE THREAD

**Issue by ArikEpstein** [angular/universal#936]
```
- [ x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
Bug report

* **What is the current behavior?**
according the new release 5.0.0-beta.7 on change log.
https://github.com/angular/universal/blob/master/CHANGELOG.md

There is new feature
* **common:** introduce StateTransferInitializerModule ([#916](https://github.com/angular/universal/issues/916)) ([5aef476](https://github.com/angular/universal/commit/5aef476))
But
introduce StateTransferInitializerModule - doesn't include to 5.0.0-beta.7 release

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by Toxicable** [comment]
This feature was not intended to be apart of this release, it's going into v6 instead.

**Comment by ArikEpstein** [comment]
Thanks @Toxicable will wait for v6 release.
