### ISSUE TITLE
error with beta.7 but not beta.5

### ISSUE THREAD

**Issue by Chk-rocks** [angular/universal#939]
![nguniversal error](https://user-images.githubusercontent.com/25702941/37790253-ff23f9b8-2e2b-11e8-9f44-e71106fce182.jpg)
**Note: for support questions, please use one of [these channels][Channels]**. This repository's issues are reserved 
for feature requests and bug reports. Also, **Preboot has moved** [here][preboot] - please make preboot-related issues 
there.

* **I'm submitting a ...**
```
- [Y ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ Y] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
I have seen multiple times like My application runs good for a while but at sometime it got failed due to some version issue.

* **What is the current behavior?**
Not Working

* **If the current behavior is a bug**, please provide the steps to reproduce and if possible a minimal demo of the 
problem by creating a github repo.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

- Angular version: 5.0.0
- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | TypeScript X.X | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | Windows | Linux ]
- Platform: [all | NodeJS | Java | PHP | .NETCore | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by patrickmichalina** [comment]
Are your version pinned in package.json? If not, it could have been bumped to a higher version during CI process? I would pin it to -beta5. 

In other words, make your package.json look like this:

```js
"@nguniversal/common": "5.0.0-beta.5",
"@nguniversal/express-engine": "5.0.0-beta.5"
```

**Comment by Chk-rocks** [comment]
I have pinned to static version still its getting fail 

Please find below package.json 
{
  "name": "data-science-python",
  "version": "1.2.0",
  "license": "SEE LICENSE IN LICENSE.pdf",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "prestart": "ng build",
    "build:client-and-server-bundles": "ng build --prod --no-aot && ng build --prod --app 1 --output-hashing=false",
    "build:ssr": "npm run build:client-and-server-bundles",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:prerender": "cd dist/browser && http-server",
    "serve:ssr": "node dist/server"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.0",
    "@angular-devkit/core": "^0.4.5",
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "@nguniversal/express-engine": "5.0.0-beta.5",
    "@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.5",
    "@ngx-meta/core": "5.0.0",
    "@ngx-share/button": "^5.0.1",
    "@ngx-share/buttons": "^5.0.1",
    "@ngx-share/core": "^5.0.1",
    "angular2-disqus": "^6.1.1",
    "angular2-highlight-js": "^6.0.1-alpha",
    "animate.css": "^3.5.2",
    "arrive": "^2.3.1",
    "bootstrap": "^3.3.5",
    "bootstrap-notify": "^3.1.3",
    "bootstrap-select": "^1.12.2",
    "bootstrap-tagsinput": "^0.7.1",
    "chartist": "0.11.0",
    "chartist-plugin-zoom": "^0.4.0",
    "chartjs-plugin-zoom": "^0.5.0",
    "core-js": "^2.4.1",
    "datatables": "1.10.12",
    "datatables.net-bs": "1.10.12",
    "datatables.net-buttons": "^1.5.1",
    "datatables.net-responsive": "^2.1.1",
    "domready": "^1.0.8",
    "eonasdan-bootstrap-datetimepicker": "4.17.47",
    "express": "^4.15.3",
    "firebase": "^4.8.1",
    "firebase-admin": "~5.4.2",
    "firebase-functions": "0.7.1",
    "fs": "0.0.1-security",
    "fullcalendar": "^3.4.0",
    "googleapis": "^19.0.0",
    "grpc": "^1.8.0",
    "jasny-bootstrap": "^3.1.3",
    "jquery": "^3.2.1",
    "mathjax": "^2.7.3",
    "ng2-adsense": "^5.1.4",
    "ng2-slim-loading-bar": "^4.0.0",
    "ngx-bootstrap": "^2.0.1",
    "ngx-disqus": "^2.3.7",
    "nouislider": "^9.2.0",
    "npm": "^5.7.1",
    "path": "^0.12.7",
    "rxjs": "5.5.6",
    "ts-loader": "^3.2.0",
    "twitter-bootstrap-wizard": "^1.2.0",
    "validate": "^3.0.1",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.6.3",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/bootstrap": "3.3.32",
    "@types/chartist": "0.9.34",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "1.10.31",
    "@types/node": "^8.0.30",
    "cpy-cli": "^1.0.1",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "5.1.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.2",
    "reflect-metadata": "^0.1.10",
    "@types/datatables.net": "^1.10.6"
  }
}

**Comment by Chk-rocks** [comment]
"@nguniversal/express-engine": "5.0.0-beta.5",
"@nguniversal/module-map-ngfactory-loader": "5.0.0-beta.5",

**Comment by CaerusKaru** [comment]
I can't apologize enough for this issue. This will be fully resolved in v5 final. We're finalizing some testing and then we'll release the patch hopefully early next week.

**Comment by stanleyeosakul** [comment]
Just as another data point, I tried to upgrade to 

* nguniversal/express-engine ^5.0.0-beta.7 and 
* nguniversal/module-map-ngfactory-loader ^5.0.0-beta.7

from 5.0.0-beta.6 yesterday.  Both packages generate the `Unexpected token export` error as described by the OP.  The new beta version 7 for me unfortunately is **unusable** for this reason so I've reverted back to "5.0.0-beta.6" which still works thankfully.

**Comment by CaerusKaru** [comment]
5.0.0-beta.6 and 5.0.0-beta.7 have both been deprecated. The latest version once again points to 5.0.0-beta.5.

The new fix is in #940 and has been tested with all modules in all formats. Please feel free to pull from the remote branch and build from source to confirm.

**Comment by stanleyeosakul** [comment]
I deleted my `yarn.lock` file and `node_modules`, and I tried to reinstall my packages, but ended up with this error:

```
error @nguniversal/express-engine@5.0.0-beta.5: The engine "node" is incompatible with this module. Expected version ">= 5.4.1 <= 8".
error An unexpected error occurred: "Found incompatible module".
```

My Node version is **v9.9.0**

5.0.0-beta.6 continues to work for me.

**Comment by Toxicable** [comment]
Hey all, we've just released beta.8 which should solve all of these issues.
Ill close this since it since the original issue has been resolved but if there are anymore problems then feel free to open another issue.

**Comment by patrickmichalina** [comment]
@Toxicable works like a charm, thanks so much!

**Comment by stanleyeosakul** [comment]
Works great for me too, thanks!

**Comment by mgol** [comment]
@Toxicable perhaps the deprecation message should be tweaked then. It now still says:
```
npm WARN deprecated @nguniversal/module-map-ngfactory-loader@5.0.0-beta.6: Has packaging issues. Use 5.0.0-beta.5
```
