### ISSUE TITLE
Is there any way to add ld+json tags

### ISSUE THREAD

**Issue by viranmalaka** [angular/universal#951]
* **I'm submitting a ...**
```
- [ ] bug report
- [*] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```
Google Search engine is recommended ```json+ld``` rather than meta tags. But I could not find a proper way inside Angular or Angular-Universal.

**Comment by Toxicable** [comment]
You can inject the DOCUMENT token like so `constructor(@Inject(DOCUMENT) doc) {}` then you have access to the document without worrying about what platform you're on.
From there you can use any of the normal browser APIs to edit the elements there.
