### ISSUE TITLE
[Feature Request] Ability to statically export Angular apps using the Universal Engine

### ISSUE THREAD

**Issue by michaeljota** [angular/universal#954]
**Note: for support questions, please use one of [these channels][Channels]**. This repository's issues are reserved 
for feature requests and bug reports. Also, **Preboot has moved** [here][preboot] - please make preboot-related issues 
there.

* **I'm submitting a ...**
```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ ] aspnetcore-engine
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**

Feature

* **What is the current behavior?**

Universal Engine works in a server and this is need to render the pages. 

* **What is the expected behavior?**

I would like to see an option to render each page into static html files, that contains references to the need files to run the full Angular application after the page is loaded.

Giving the ToH project, this command would create a build of the application, and additionally, html files that with static content.

```md
// Files currently build
[assets]
index.html // with real static content (dashboard content)
[javascript files - inline, main, polyfills]
[css file - styles]
// Additional files
dashboard.html // with real static content
heroes.html // with real static content
hero // a folder containing all the hero pages
 | - 1.html // with real static content
 | - {{n}}.html // with real static content
```

* **What is the motivation / use case for changing the behavior?**

Some pages are just too simple to setup a complete server to do the render, but still worth to have a static version of them, such a blogs, and landing pages. I think about typically Wordpress pages here, but with Angular can be made with out the extra processing of a server. 

* **Please tell us about your environment:**

- Angular version: 5.2.0
- Browser: [all]
- Language: [all ]
- OS:  [all]
- Platform: [NodeJS]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

There are several React frameworks that exports static pages using React.
- [Gastby](https://github.com/gatsbyjs/gatsby)
- [Next.js](https://github.com/zeit/next.js) `// Server side render and static export`
- [Phenomic](https://github.com/phenomic/phenomic)

---

I understand that such simple applications shouldn't even be using Angular in the first place, but as I see right now, that's because Angular does not have something like this. And being officially supported would be something that other frameworks does not have.

**Comment by Toxicable** [comment]
We already have this.
Take a look at this file here.
https://github.com/angular/universal-starter/blob/master/prerender.ts
It pre-renders your application to html and writes those files to dist to be served up later on

**Comment by michaeljota** [comment]
This is doable from CLI or this is something that you have to do on your own?

**Comment by michaeljota** [comment]
This is actually quite hard to implement, and need real advance knowledge to do it. I have been working on that for about two weeks, and still nothing. This need to be simplify.

**Comment by Toxicable** [comment]
@michaeljota What part are you struggling with?
