### ISSUE TITLE
I want a library like React next Can Universal provide data for each page of the angular without a server api call?

### ISSUE THREAD

**Issue by eddie-hm** [angular/universal#957]
I want a library like React's next.js or Vue's Nuxt.js
Can Universal provide data for each page of the angular without a server api call?

**Comment by gdi2290** [comment]
I was working on this in the past but there was a problem with ngc and ngfactories. With Angular 6/7 this should be possible  👍

**Comment by Toxicable** [comment]
While this is something that I think warrents more investigation on how it might work in Angulars ecosystem it's not something we want to tackle in the near future. There are other more pressing issues that are a higher priority right now.

**Comment by Toxicable** [comment]
Since this is not currently actionable near in the near future im going to close this one.
If you feel like making a design on this then do open another issue with the details there.
