### ISSUE TITLE
ssr not rendering dynamic content after app build content fetched through api call

### ISSUE THREAD

**Issue by ayushsinghal90** [angular/universal#960]
'use strict';

require('zone.js/dist/zone-node');
require('reflect-metadata');

const express = require('express');
const ngUniversal = require('@nguniversal/express-engine');
const { provideModuleMap } = require('@nguniversal/module-map-ngfactory-loader');

const { AppServerModuleNgFactory, LAZY_MODULE_MAP } = require('./dist-server/main.bundle');

function angularRouter(req, res) {

  res.render('index', {
    req,
    res,
    providers: [{
      provide: 'serverUrl',
      useValue: `${req.protocol}://${req.get('host')}`
    }]
  });
}
const app = express();

app.engine('html', ngUniversal.ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ],
  async: true
}));
app.set('view engine', 'html');
app.set('views', 'dist');

app.get('/', angularRouter);

app.use(express.static(`${__dirname}/dist`));

app.get('*', angularRouter);

app.listen(3000, () => {
  console.log('Listening on port 3000');
});

here is the server.js code for my angular project.
Dynamic content fetched through api call is not being rendered while running node serve.js
<!.......> is being displayed on view page source

**Comment by Gorniv** [comment]
you can clone https://github.com/Angular-RU/angular-universal-starter  and look on [transfer-back](https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/transfer-back/transfer-back.component.ts) and the most simple way for use `transfer state` with [transfer-http.service](https://github.com/Angular-RU/angular-universal-starter/blob/master/src/app/shared/transfer-http/transfer-http.service.ts)

**Comment by Toxicable** [comment]
https://github.com/angular/universal-starter is the recommended starter for Universal.
Without a minimal reproduction we cannot tell if this is an issue with Universal or not.

**Comment by patrickmichalina** [comment]
Also, be sure to set URLs to absolute on the server side request

**Comment by ayushsinghal90** [comment]
@[Toxicable ](https://github.com/Toxicable)Just followed you repo instruction from angular starter @Toxicable 
thanks for repo tag problem solved
 loved the response 
Closing the issue
