### ISSUE TITLE
Link redirection breaking SSR

### ISSUE THREAD

**Issue by isaac2004** [angular/universal#964]
**Note: for support questions, please use one of [these channels][Channels]**. This repository's issues are reserved 
for feature requests and bug reports. Also, **Preboot has moved** [here][preboot] - please make preboot-related issues 
there.

* **I'm submitting a ...**
```
- [X ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.
```

* **What modules are related to this Issue?**
```
- [ X] aspnetcore-engine
- [ X] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

* **Do you want to request a *feature* or report a *bug*?**
Bug

* **What is the current behavior?**
Using route navigation in template (anchor tag) causes cache to not be utilized

* **If the current behavior is a bug**, please provide the steps to reproduce and if possible a minimal demo of the 
problem by creating a github repo.
Using the sample ASP.NET Core [sample](https://github.com/MarkPieszak/aspnetcore-angular2-universal), doing something like this causes double requests for the Api call

````
  <a href="/post/{{post.url}}">Test</a>
````

Otherwise using router.navigate has no issues

````
  onSelect(url: string): void {
    this.router.navigate(['/post/' + url]);
  }
````

* **What is the expected behavior?**
I am not sure

* **What is the motivation / use case for changing the behavior?**
I had a bug in an SSR app for a while and thought it would be good to call out

* **Please tell us about your environment:**

- Angular version: 5.0.0
- Browser: [**all** | Chrome XX | Firefox XX | IE XX | Safari XX ]
- Language: [all | **TypeScript 2.5** | ES6/7 | ES5 ]
- OS:  [all | Mac OS X | **Windows** | Linux ]
- Platform: [all | NodeJS | Java | PHP | **.NETCore** | Ruby]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us 
to have context, eg. stackoverflow, gitter, etc)

I can create a repo if needed

[Channels]: https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
[preboot]: https://github.com/angular/preboot

**Comment by m98** [comment]
You answered the **What is the expected behavior?** the question with *"I am not sure"*

Could you explain what's the current behavior, and what should it be?

**Comment by Toxicable** [comment]
use `routerLink` instead of `href`, `href` will cause the entire app to boot up again.

Closing as not a Universal issue
