### ISSUE TITLE
Error: Zone already loaded.

### ISSUE THREAD

**Issue by pekubu** [angular/universal#966]
* **I'm submitting a bug repor**
I get this error when running node dist/server.js. How to fix it? 
Thank you
![image](https://user-images.githubusercontent.com/26251116/39094906-a93dbdf6-4661-11e8-91ac-d06088ecfa16.png)

**Comment by Toxicable** [comment]
It looks like you've loaded Zones twice.
Have you tried using out https://github.com/angular/universal-starter ?

**Comment by pekubu** [comment]
Thank you, there is a little problem with the ngx-charts module, I'm looking to replace it.

**Comment by Toxicable** [comment]
Since this dosen't appear to be an issue with Universal im going to go head and close it.
