### ISSUE TITLE
@next tag on npm for v6

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/universal#975]
## I'm submitting a ...
```
- [x] bug report
```

## What modules are related to this Issue?
```
- [x] aspnetcore-engine
- [x] common
- [x] express-engine
- [x] hapi-engine
- [x] module-map-ngfactory-loader
```

## Minimal reproduction with instructions
`npm install @nguniversal/express-engine@next`
Or any other `@nguniversal/x` package.

## Current behavior?
Install 5.0.0-beta.5

## Expected behavior?
Should install 6.0.0-rc.x

**Comment by vikerman** [comment]
Oops. Fixing it soon

**Comment by cyrilletuzi** [comment]
Yes, not necessary anymore.
