### ISSUE TITLE
where is https://universal.angular.io/ repo? I want to make PR

### ISSUE THREAD

**Issue by hiepxanh** [angular/universal#980]
well, documentation is old and we need to update this. I know universal team is very busy and I'm willing to contribute a lot of documentation if I find out where is that website https://universal.angular.io/ source? I cannot find it in any branch

**Comment by m98** [comment]
Those micro-sites used to be in [this repository](https://github.com/angular/microsites/tree/master/universal.angular.io), but I'm not sure if it's still working, or it's deprecated!

**Comment by hiepxanh** [comment]
thank you, we need someone verify this

**Comment by Toxicable** [comment]
We will be taking that website down soon.
@hiepxanh What kind of docs did you want to add to?

**Comment by hiepxanh** [comment]
I have a question, what kind of docs do you need?
I'm thinking of some topic:
- basic getting-start tutorial with working example
- how to convert basic angular project to universal
- how to integrate 3rd party library 
- how to convert normal library to working with universal (some kind of universal ready tag 😄 )

everything need Stackblitz example.

**Comment by Toxicable** [comment]
We have some most of that already.

From basics to app here: https://angular.io/guide/universal
Additional cli specific stuff here: https://github.com/angular/angular-cli/wiki/stories-universal-rendering
Full example here https://github.com/angular/universal-starter

However we don't have much on integrating 3rd party libs.

**Comment by Toxicable** [comment]
For now we will add the docs in this repository under `docs/*.md` 
If it's specific to a module then it should go into the README.md for that module.

So if you'd like to put together a PR adding some docs to that location i'd be happy to review

**Comment by hiepxanh** [comment]
yes, I love to do it. Thank you
