### ISSUE TITLE
Angular 6 Universal Server Side Rendering

### ISSUE THREAD

**Issue by laiwf94** [angular/universal#985]
The documentation for the server-side rendering (Universal) is outdated. Will you please update the documentation to let us know how to use the server-side rendering in Angular 6?

In the Angular documentation (https://angular.io/guide/universal), the "build and run with Universal" section (https://angular.io/guide/universal#build-and-run-with-universal) , it asks to change amend the build and serve script into the package.json.  One of the line for the build scripts is as follows:

"build:client-and-server-bundles": "ng build --prod && ng run angular.io-example:server",

What is the "ng run angular.io-example:server" means in the scripts? What does it run?

In the previous version (https://github.com/angular/angular-cli/wiki/stories-universal-rendering), the script for that part should be as follows: 

"ng build --prod --app 1 --output-hashing=false"

which will run the second app configuration in the angular-cli.json to build and generate the server.js.

However, the angular-cli.json is being updated to angular.json in Angular 6, and --app flag is not recognised anymore as it doesn't exist in the angular.json.

Would you please update the documentation, so I will know how to build the server.js with different build script in the package.json? Thanks

**Comment by Toxicable** [comment]
`ng run` will run any target in your angular.json.
`angular.io-example` part is the project name
`server` is the targets name

for example; here 
https://github.com/angular/universal-starter/blob/master/angular.json#L6
it be `ng run ng-universal-demo:server`

You can check here https://github.com/angular/universal-starter for a full working example

This: https://github.com/angular/angular-cli/wiki/stories-universal-rendering
has yet to be updated but `--app` will no longer works in v6

**Comment by njl07** [comment]
You can use `SSR` with [Hapiness module](https://github.com/hapinessjs/ng-universal-module)

Documentation is updated and I've just published the latest version.

**Comment by CaerusKaru** [comment]
Any documentation issues should be filed under the core repository. That being said, I know there's a PR in-flight (might've been merged) to fix these issues.
