### ISSUE TITLE
ReferenceError: Zone is not defined angular universal 6

### ISSUE THREAD

**Issue by hesampour** [angular/universal#988]
I try to update my angular project to angular 6. after a lot of tries I get this error when start the universal
ReferenceError: Zone is not defined
when I remove import 'zone.js/dist/zone-node' this problem fixed but there is another problem that zone is not loaded

**Comment by hesampour** [comment]
thanks a lot. the problem solved.

**Comment by scopsy** [comment]
@hesampour How you solved this ?

**Comment by hesampour** [comment]
just move the two following import to the top of the server.js file
import 'zone.js/dist/zone-node';
import 'reflect-metadata';
