### ISSUE TITLE
Get requests using HttpClient are not cached from server to client

### ISSUE THREAD

**Issue by eyalhakim** [angular/universal#990]
## I'm submitting a ...
```
- [x] bug report <!-- Please search GitHub for a similar issue or PR before submitting -->
- [ ] feature request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
```

## What modules are related to this Issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

## Current behavior?
When issuing a get request on the server while rendering, the same request is being executed again on the client.
## Expected behavior?
The request should be automatically cached and not send again from the browser.
## Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

**Comment by Toxicable** [comment]
I'ts possible that you're doing a POST request.
Once you do a POST the cache is disabled and will no longer cache requests

**Comment by eyalhakim** [comment]
@Toxicable thanks for your response! I have 3rd party analytics services doing POST requests but it's not from within the Angular zone and also these requests are done after my initial get request that should be doing the caching (it's the main request to get the index file).

Caching also doesn't work using the TransferState service.

@CaerusKaru I have the BrowserTransferStateModule imported on the client module and ServerTransferStateModule on the server.

Could you think of any other idea why this might not work?

Thank you!

**Comment by eyalhakim** [comment]
@Toxicable removed those 3rd party services and problem still persists

**Comment by Toxicable** [comment]
@eyalhakim Could you check your network traffic to see if there's any POST requests, that's the only thing we have  that disables the cache

**Comment by Toxicable** [comment]
That looks fine to be from StateTransfer wise.
Would it be possible to make a minimal reproduction?

**Comment by eyalhakim** [comment]
@Toxicable I uploaded a minimal subset of my application to a repository and confirmed the problem being reproduced.

https://github.com/eyalhakim/universal-cache-bug

After running build:ssr and serve:ssr, go to this url: http://localhost:4000/wellness/category/nutrition/smoothie-bar

You will see that the request from `ExperienceComponent.ngOnInit` at line 49 in file `src/app/experience.component/experience.component.ts` is being called twice from both server and client.

Awaiting your diagnosis 👍

**Comment by eyalhakim** [comment]
@CaerusKaru, @Toxicable would love your help on this.

Thank you!

**Comment by eyalhakim** [comment]
CaerusKaru, @Toxicable Tried moving the http request from the `ngOnInit` to a `Resolver` but the problem persists. Any chance you could take a look at my reproduction?

Thanks!

**Comment by Toxicable** [comment]
@eyalhakim Sorry i've been a bit silent lately. Everything has got me super busy lately, I should hopefully get a chance to take a look this weekend.

**Comment by eyalhakim** [comment]
@Toxicable great, thank you!

**Comment by eyalhakim** [comment]
Hi @Toxicable did you have time to look at it over the weekend?

Thanks

**Comment by Toxicable** [comment]
I just took a quick look and my inital thought from looking at the rendered output is that none of the content is cached at all which makes me think you've mis configured the `TransferHttpCacheModule`.
Here's some docs on how it's used: https://github.com/angular/universal/blob/master/docs/transfer-http.md
Compare that to your app and let me know how you get on.

**Comment by eyalhakim** [comment]
You were right! fixed, thank you
