### ISSUE TITLE
Server side not using production environment file

### ISSUE THREAD

**Issue by eyalhakim** [angular/universal#991]
## I'm submitting a ...
```
- [x] bug report <!-- Please search GitHub for a similar issue or PR before submitting -->
- [ ] feature request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
```

## What modules are related to this Issue?
```
- [ ] aspnetcore-engine
- [ ] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

## Current behavior?
When compiling using `ng build --prod && ng run wekudo-website:server` the correct `environment.prod.ts` file is being used for the client side but not for the server side.
## Expected behavior?
The same production file should be used on both the client and server
## Environment:
**@nguniversal versions**
  - aspnetcore-engine: 
  - common:
  - express-engine:
  - hapi-engine:
  - module-map-ngfactory-loader:
```
<!--
Output from: `ng --version`.
If nothing, output from: `node --version` and `npm --version`.
  Windows (7/8/10). Linux (incl. distribution). macOS (El Capitan? Sierra?)
-->
```

**Comment by Toxicable** [comment]
You need to add the config like here https://github.com/angular/universal-starter/pull/590/files

**Comment by eyalhakim** [comment]
Works! Thank you

**Comment by Toxicable** [comment]
@m98 the upgrade dosen't add in any default configurations

**Comment by m98** [comment]
But it used to work previously. If I got you correctly, you mean in the upgrade, they are not including environments (default configurations) into builds?
If yes, do you know what was the reason?

**Comment by Gorniv** [comment]
Also, you can use different environments for browser and server:
[browser](https://github.com/Angular-RU/angular-universal-starter/blob/37f2333468c9846113315c001f83ea7b0bb802cd/angular.json#L53)
[server](https://github.com/Angular-RU/angular-universal-starter/blob/37f2333468c9846113315c001f83ea7b0bb802cd/angular.json#L130)
