### ISSUE TITLE
feat(common): add missing globals

### ISSUE THREAD

**Issue by CaerusKaru** [angular/universal#992]
## I'm submitting a ...
```
- [ ] bug report <!-- Please search GitHub for a similar issue or PR before submitting -->
- [x] feature request
- [ ] Support request => Please do not submit support request here, instead see https://github.com/angular/universal/blob/master/CONTRIBUTING.md#question
```

## What modules are related to this Issue?
```
- [ ] aspnetcore-engine
- [x] common
- [ ] express-engine
- [ ] hapi-engine
- [ ] module-map-ngfactory-loader
```

## Current behavior?

Globals like `document` and `window` are available in Domino, but are not patched before app render

## Expected behavior?

These globals should be available to applications and libraries during render, via a proxy patch (so that each request gets its own document and window)

## Minimal reproduction with instructions

Access `document.body` in any part of the application

## Environment:
**@nguniversal versions**
  - common: 6.0.0

**Comment by friday** [comment]
We (mostly me) talked about this issue in: https://github.com/video-dev/hls.js/pull/1841#issuecomment-408563367

This information could be relevant to you as well (the caveats part). Or if you disagree with them, you could tell me why I'm wrong 😉 

Also see
* https://github.com/lukechilds/browser-env
* https://github.com/avajs/ava/issues/1092

**Comment by alan-agius4** [comment]
Closing as accessing `document` and `window` directly is not recommended and should not be encouraged.
