### ISSUE TITLE
not loading css file inside component when directly refresh at subroute

### ISSUE THREAD

**Issue by hesampour** [angular/universal#995]
hi
I recently switched to angular 6 in my angular project, but there is a strange problem that when I refresh the page at sub route It not loads the component css file. I mean that directly loading the interior route not loads the component css file. imagine that my site is domain.com when I directly loads the domain.com/someLinks case the css of the comeLinks component not loads. but when at first go to domain.com then domain.com/someLinks everything works properly.

**Comment by Toxicable** [comment]
This is likely some configuration with your http server.
If not then please make a minimal reproduction

**Comment by CaerusKaru** [comment]
@Toxicable asked for a reproduction months ago. If one is provided, we can reopen this issue.
